unpackaged/main/default/objects/ET_Finance_Document__c/ET_Finance_Document__c.object-meta.xml
<CustomObject>
    <label>Finance Document</label>
    <nameField>
        <displayFormat>FINETDEV-{0000000}</displayFormat>
        <label>Fin Doc Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Finance Documents</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/ET_Invoice_Header__mdt/ET_Invoice_Header__mdt.object-meta.xml
<CustomObject>
    <label>ET Invoice Header</label>
    <pluralLabel>ET Invoice Headers</pluralLabel>
</CustomObject>

unpackaged/main/default/objects/ET_Invoice_Header__mdt/fields/ET_BatchSource__c.field-meta.xml
<CustomField>
    <fullName>ET_BatchSource__c</fullName>
    <label>BatchSource</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/ET_Invoice_Header__mdt/fields/ET_BillToCustomerNumber__c.field-meta.xml
<CustomField>
    <fullName>ET_BillToCustomerNumber__c</fullName>
    <label>BillToCustomerNumber</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/ET_Invoice_Header__mdt/fields/ET_Comments__c.field-meta.xml
<CustomField>
    <fullName>ET_Comments__c</fullName>
    <label>Comments</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/ET_Invoice_Header__mdt/fields/ET_CustTrxType__c.field-meta.xml
<CustomField>
    <fullName>ET_CustTrxType__c</fullName>
    <label>CustTrxType</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/ET_Invoice_Header__mdt/fields/ET_PaymentMethod__c.field-meta.xml
<CustomField>
    <fullName>ET_PaymentMethod__c</fullName>
    <label>PaymentMethod</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/ET_Invoice_Header__mdt/fields/ET_TransactionCurrency__c.field-meta.xml
<CustomField>
    <fullName>ET_TransactionCurrency__c</fullName>
    <label>TransactionCurrency</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/classes/ET_FinanceControllerCalloutBatch.cls
/************************************************************************************************************************
 * Name               : ET_FinanceControllerCalloutBatch                                                                *
 * Test Class		  : ET_FinanceControllerBatchTest                                                                   *
 * Description        : Apex Class for automate to publish finance documents                                            *
 * Created Date       : 02/Feb/2024                                                                                    *
 * Created By         : Taj Shaik(SMAARTT)                                                                              *
 * -----------------------------------------------------------------------------------------------                      *
 * VERSION   AUTHOR      DATE                COMMENTS                                                                   *
 * 1.0       Taj Shaik   02/Feb/2024         Initial Draft.                                                             *
 ***********************************************************************************************************************/
global class ET_FinanceControllerCalloutBatch implements Database.Batchable<sObject>,Database.AllowsCallouts,Database.Stateful {
    global String invoiceType;
    global List<Id> recIds;
    global Database.QueryLocator start(Database.BatchableContext BC) {
        string query='SELECT Id FROM ET_Finance_Document__c WHERE Id IN: recIds';
        system.debug('query: '+query);
        return Database.getQueryLocator(query);
    }
    global void execute(Database.BatchableContext BC, List<ET_Finance_Document__c> docList){
        system.debug('docList Size: '+docList.Size());
        ET_Invoice_Header__mdt invHeader = [SELECT MasterLabel,developerName,ET_BatchSource__c,ET_BillToCustomerNumber__c,ET_Comments__c,ET_CustTrxType__c,ET_PaymentMethod__c,ET_TransactionCurrency__c FROM ET_Invoice_Header__mdt WHERE developerName =: invoiceType LIMIT 1];
        for(ET_Finance_Document__c finDoc: docList){
            ET_SOA_Services.syncInvoicesToEBSNew(finDoc.Id, invHeader);
        }
    }
    global void finish(Database.BatchableContext bc){
    }
}