unpackaged/main/default/objects/Contract_Pdf_Header__c/Contract_Pdf_Header__c.object-meta.xml
<CustomObject>
    <label>Contract Pdf Header</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Contract Pdf Header Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Contract Pdf Header</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Contract_Pdf_Header__c/fields/Customer_Quote__c.field-meta.xml
<CustomField>
    <fullName>Customer_Quote__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Customer Quote</label>
    <referenceTo>Customer_Quote__c</referenceTo>
    <relationshipLabel>Contract Pdf Header</relationshipLabel>
    <relationshipName>Contract_Pdf_Header</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Customer_Quote__c/Customer_Quote__c.object-meta.xml
<CustomObject>
    <description>Customer Quote</description>
    <label>Customer Quote</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Customer Quote Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Customer Quotes</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Customer_Vehicle_Quote_Item__c/Customer_Vehicle_Quote_Item__c.object-meta.xml
<CustomObject>
    <label>Customer Vehicle Quote Item</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Vehicle Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Customer Vehicle Quote Items</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Customer_Vehicle_Quote_Item__c/fields/Customer_Quote__c.field-meta.xml
<CustomField>
    <fullName>Customer_Quote__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Customer Quote</label>
    <referenceTo>Customer_Quote__c</referenceTo>
    <relationshipLabel>Customer Vehicle Quote Items</relationshipLabel>
    <relationshipName>Customer_Vehicle_Quote_Items</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Customer_Vehicle_Quote_Item__c/fields/Monthly_Rate_All_Unit_with_VAT__c.field-meta.xml
<CustomField>
    <fullName>Monthly_Rate_All_Unit_with_VAT__c</fullName>
    <label>Monthly All Units</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

unpackaged/main/default/objects/Customer_Vehicle_Quote_Item__c/fields/Number_of_Vehicles__c.field-meta.xml
<CustomField>
    <fullName>Number_of_Vehicles__c</fullName>
    <label>QTY</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

unpackaged/main/default/objects/Customer_Vehicle_Quote_Item__c/fields/Total_Annual_Price_Target_Prices__c.field-meta.xml
<CustomField>
    <fullName>Total_Annual_Price_Target_Prices__c</fullName>
    <label>Total Annual Price (Target Prices)</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

unpackaged/main/default/objects/Customer_Vehicle_Quote_Item__c/fields/Vehicle_Manufacture_Year__c.field-meta.xml
<CustomField>
    <fullName>Vehicle_Manufacture_Year__c</fullName>
    <label>Vehicle Manufacture Year</label>
    <precision>4</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

unpackaged/main/default/objects/Customer_Vehicle_Quote_Item__c/fields/Vehicle_Monthly_Price__c.field-meta.xml
<CustomField>
    <fullName>Vehicle_Monthly_Price__c</fullName>
    <label>Monthly/Unit</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

unpackaged/main/default/objects/Customer_Vehicle_Quote_Item__c/fields/Vehicle_Source__c.field-meta.xml
<CustomField>
    <fullName>Vehicle_Source__c</fullName>
    <label>Proposal Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Main</fullName>
            </value>
            <value>
                <fullName>optional</fullName>
            </value>
            <value>
                <fullName>Substitutional</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Service_Type__c/Service_Type__c.object-meta.xml
<CustomObject>
    <label>Service Type</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Service Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Service Types</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/classes/PRI_customerQuoteContractController.cls
public class PRI_customerQuoteContractController {
    
    public List<PRI_customerQuoteController.Article> contractDetails { get; set; }
    public list<Customer_Vehicle_Quote_Item__c> VehiclList { get; set; }
    
    public PRI_customerQuoteContractController(ApexPages.StandardController stdController) {
        String recordId = stdController.getId();
        contractDetails = PRI_customerQuoteController.getContractClauses(recordId);
        
        Contract_Pdf_Header__c PDFH =[Select Id, Name, Customer_Quote__c from Contract_Pdf_Header__c where Id =:recordId];
        System.debug(Customer_Quote__c.Id);
        VehiclList =[select Id,Name,Vehicle_Source__c,
                     Service_Type__c,
                     Vehicle_Manufacture_Year__c,
                     Number_of_Vehicles__c,
                     Vehicle_Monthly_Price__c,
                     Total_Annual_Price_Target_Prices__c,				
                     Monthly_Rate_All_Unit_with_VAT__c from Customer_Vehicle_Quote_Item__c where Customer_Quote__c =:PDFH.Customer_Quote__c];
        System.debug(VehiclList);
    }
     @AuraEnabled
    public static string generateQuoteDoc(string quoteId, String Sector){
        List<Contract_Pdf_Header__c>  cusQuote =[select Id, Name from Contract_Pdf_Header__c where Id =:quoteId];
        String CusQuoteName = cusQuote[0].Name;
        String VFpageName;
        if(Sector == 'School'){
            VFpageName ='ET_generateContractPdf_School';
        }
         if(Sector == 'Transport And Lease'){
            VFpageName ='ET_generateContractPdf_TL';
        }
		PageReference pdf = new PageReference('/' + VFpageName);
        pdf.getParameters().put('Id',quoteId);
        Blob pdfBlob;
        if (!Test.isRunningTest()) {
            pdfBlob = pdf.getContentAsPDF();
        }
        try{
            ContentVersion conVer = new ContentVersion();
            DateTime  dt = System.now();
            
            conVer.ContentLocation = 'S'; // TO USE S specify this document IS IN Salesforce, TO USE E FOR external files
            conVer.PathOnClient = CusQuoteName+'_'+dt.hour()+dt.minute()+dt.second()+'.pdf'; 
            conVer.Title = CusQuoteName+ '_'+dt.hour()+dt.minute()+dt.second()+'.pdf'; 
            conVer.VersionData = pdfBlob;
            insert conVer;  
            
            Id conDoc = [SELECT ContentDocumentId FROM ContentVersion WHERE Id =:conVer.Id].ContentDocumentId;
            
            ContentDocumentLink conDocLink = new ContentDocumentLink();
            conDocLink.LinkedEntityId = quoteId; //parentId
            conDocLink.ContentDocumentId = conDoc; 
            conDocLink.shareType = 'V';
            insert conDocLink;
        }
        catch(Exception e){
            throw new AuraHandledException(e.getMessage());
        }
        return quoteId;
        
    }
    
}