unpackaged/main/default/objects/ETT_Price_Information_History__c/ETT_Price_Information_History__c.object-meta.xml
<CustomObject>
    <label>Pricing Information History</label>
    <nameField>
        <displayFormat>PriceHistory-{00000}</displayFormat>
        <label>Price Information History Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Pricing Information Histories</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/ETT_Price_Information_History__c/fields/ETT_New_Buying_Price__c.field-meta.xml
<CustomField>
    <fullName>ETT_New_Buying_Price__c</fullName>
    <label>New Buying Price</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

unpackaged/main/default/objects/ETT_Price_Information_History__c/fields/ETT_New_Retread_Price_H__c.field-meta.xml
<CustomField>
    <fullName>ETT_New_Retread_Price_H__c</fullName>
    <label>New Retread Price H</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

unpackaged/main/default/objects/ETT_Price_Information_History__c/fields/ETT_Old_Buying_Price__c.field-meta.xml
<CustomField>
    <fullName>ETT_Old_Buying_Price__c</fullName>
    <label>Old Buying Price</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

unpackaged/main/default/objects/ETT_Price_Information_History__c/fields/ETT_Old_Retread_Price_H__c.field-meta.xml
<CustomField>
    <fullName>ETT_Old_Retread_Price_H__c</fullName>
    <label>Old Retread Price H</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

unpackaged/main/default/objects/ETT_Price_Information_History__c/fields/ETT_Pricing_Information__c.field-meta.xml
<CustomField>
    <fullName>ETT_Pricing_Information__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Pricing Information</label>
    <referenceTo>ETT_Pricing_Information__c</referenceTo>
    <relationshipName>Price_Information_Histories</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/ETT_Price_Information_History__c/fields/ETT_Retread_Price_H_Comments__c.field-meta.xml
<CustomField>
    <fullName>ETT_Retread_Price_H_Comments__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Retread Price H Comments</label>
    <type>TextArea</type>
</CustomField>

unpackaged/main/default/objects/ETT_Price_Information_History__c/fields/ETT_Retread_Price_P_Comments__c.field-meta.xml
<CustomField>
    <fullName>ETT_Retread_Price_P_Comments__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Retread Price P Comments</label>
    <type>TextArea</type>
</CustomField>

unpackaged/main/default/objects/ETT_Price_Information_History__c/fields/Ett_Scrap_Price_Comments__c.field-meta.xml
<CustomField>
    <fullName>Ett_Scrap_Price_Comments__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Scrap Price Comments</label>
    <type>TextArea</type>
</CustomField>

unpackaged/main/default/objects/ETT_Price_Information_History__c/fields/ETT_Selling_Price_H_Comments__c.field-meta.xml
<CustomField>
    <fullName>ETT_Selling_Price_H_Comments__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Selling Price H Comments</label>
    <type>TextArea</type>
</CustomField>

unpackaged/main/default/objects/ETT_Price_Information_History__c/fields/ETT_Selling_Price_P_Comments__c.field-meta.xml
<CustomField>
    <fullName>ETT_Selling_Price_P_Comments__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Selling Price P Comments</label>
    <type>TextArea</type>
</CustomField>

unpackaged/main/default/objects/ETT_Price_Master__c/ETT_Price_Master__c.object-meta.xml
<CustomObject>
    <label>Price Master</label>
    <nameField>
        <displayFormat>PMN-{0000}</displayFormat>
        <label>Price Master Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Price Masters</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/ETT_Price_Master__c/fields/ETT_Party_Name__c.field-meta.xml
<CustomField>
    <fullName>ETT_Party_Name__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Party Name</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Price Masters</relationshipLabel>
    <relationshipName>Price_Masters</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/ETT_Pricing_Information__c/ETT_Pricing_Information__c.object-meta.xml
<CustomObject>
    <label>Pricing Information</label>
    <nameField>
        <displayFormat>PI-{0000}</displayFormat>
        <label>Pricing Info Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Pricing Information</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

unpackaged/main/default/objects/ETT_Pricing_Information__c/fields/ETT_Buying_Approval_Status__c.field-meta.xml
<CustomField>
    <fullName>ETT_Buying_Approval_Status__c</fullName>
    <label>Buying Approval Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>New</fullName>
            </value>
            <value>
                <fullName>In Progress</fullName>
            </value>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>Rejected</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/ETT_Pricing_Information__c/fields/ETT_Buying_Price__c.field-meta.xml
<CustomField>
    <fullName>ETT_Buying_Price__c</fullName>
    <label>Buying Price</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

unpackaged/main/default/objects/ETT_Pricing_Information__c/fields/ETT_Buying_Price_Comments__c.field-meta.xml
<CustomField>
    <fullName>ETT_Buying_Price_Comments__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Remarks</label>
    <type>TextArea</type>
</CustomField>

unpackaged/main/default/objects/ETT_Pricing_Information__c/fields/ETT_New_Repair_Price__c.field-meta.xml
<CustomField>
    <fullName>ETT_New_Repair_Price__c</fullName>
    <label>New Repair Price</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

unpackaged/main/default/objects/ETT_Pricing_Information__c/fields/ETT_Old_Buying_Price__c.field-meta.xml
<CustomField>
    <fullName>ETT_Old_Buying_Price__c</fullName>
    <label>Old Buying_Price</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

unpackaged/main/default/objects/ETT_Pricing_Information__c/fields/ETT_Old_Repair_Price__c.field-meta.xml
<CustomField>
    <fullName>ETT_Old_Repair_Price__c</fullName>
    <label>Old Repair Price</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

unpackaged/main/default/objects/ETT_Pricing_Information__c/fields/ETT_OLD_Retread_Price_H__c.field-meta.xml
<CustomField>
    <fullName>ETT_OLD_Retread_Price_H__c</fullName>
    <label>OLD Retread Price H</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

unpackaged/main/default/objects/ETT_Pricing_Information__c/fields/ETT_Price__c.field-meta.xml
<CustomField>
    <fullName>ETT_Price__c</fullName>
    <label>Price</label>
    <referenceTo>ETT_Price_Master__c</referenceTo>
    <relationshipLabel>Pricing Information</relationshipLabel>
    <relationshipName>Pricing_Information</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

unpackaged/main/default/objects/ETT_Pricing_Information__c/fields/ETT_Purchase_Agreed_Price__c.field-meta.xml
<CustomField>
    <fullName>ETT_Purchase_Agreed_Price__c</fullName>
    <label>Purchase Agreed Price</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

unpackaged/main/default/objects/ETT_Pricing_Information__c/fields/ETT_Repair_Price__c.field-meta.xml
<CustomField>
    <fullName>ETT_Repair_Price__c</fullName>
    <label>Repair Price</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

unpackaged/main/default/objects/ETT_Pricing_Information__c/fields/ETT_Repair_Price_Approval_Status__c.field-meta.xml
<CustomField>
    <fullName>ETT_Repair_Price_Approval_Status__c</fullName>
    <label>Repair Price Approval Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>New</fullName>
            </value>
            <value>
                <fullName>In Progress</fullName>
            </value>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>Rejected</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/ETT_Pricing_Information__c/fields/ETT_Repair_Price_Comments__c.field-meta.xml
<CustomField>
    <fullName>ETT_Repair_Price_Comments__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Repair Price Comments</label>
    <type>TextArea</type>
</CustomField>

unpackaged/main/default/objects/ETT_Pricing_Information__c/fields/ETT_Retread_H_Price_Approval_Status__c.field-meta.xml
<CustomField>
    <fullName>ETT_Retread_H_Price_Approval_Status__c</fullName>
    <label>Retread Price H Approval Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>New</fullName>
            </value>
            <value>
                <fullName>In Progress</fullName>
            </value>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>Rejected</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/ETT_Pricing_Information__c/fields/ETT_Retread_Price_H__c.field-meta.xml
<CustomField>
    <fullName>ETT_Retread_Price_H__c</fullName>
    <label>Retread Price H</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

unpackaged/main/default/objects/ETT_Pricing_Information__c/fields/ETT_Retread_Price_P__c.field-meta.xml
<CustomField>
    <fullName>ETT_Retread_Price_P__c</fullName>
    <label>Retread Price P</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

unpackaged/main/default/objects/ETT_Pricing_Information__c/fields/ETT_Retread_Price_P_Approval_Status__c.field-meta.xml
<CustomField>
    <fullName>ETT_Retread_Price_P_Approval_Status__c</fullName>
    <label>Retread Price P Approval Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>New</fullName>
            </value>
            <value>
                <fullName>In Progress</fullName>
            </value>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>Rejected</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/ETT_Pricing_Information__c/fields/ETT_Scrap_Price__c.field-meta.xml
<CustomField>
    <fullName>ETT_Scrap_Price__c</fullName>
    <label>Scrap Price</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

unpackaged/main/default/objects/ETT_Pricing_Information__c/fields/ETT_Scrap_Price_Approval_Status__c.field-meta.xml
<CustomField>
    <fullName>ETT_Scrap_Price_Approval_Status__c</fullName>
    <label>Scrap Price Approval Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>New</fullName>
            </value>
            <value>
                <fullName>In Progress</fullName>
            </value>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>Rejected</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/ETT_Pricing_Information__c/fields/ETT_Scrap_Price_Comments__c.field-meta.xml
<CustomField>
    <fullName>ETT_Scrap_Price_Comments__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Scrap Price Comments</label>
    <type>TextArea</type>
</CustomField>

unpackaged/main/default/objects/ETT_Pricing_Information__c/fields/ETT_Selling_Price_H__c.field-meta.xml
<CustomField>
    <fullName>ETT_Selling_Price_H__c</fullName>
    <label>Selling Price H</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

unpackaged/main/default/objects/ETT_Pricing_Information__c/fields/ETT_Selling_Price_H_Approval_Status__c.field-meta.xml
<CustomField>
    <fullName>ETT_Selling_Price_H_Approval_Status__c</fullName>
    <label>Selling Price H Approval Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>New</fullName>
            </value>
            <value>
                <fullName>In Progress</fullName>
            </value>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>Rejected</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/ETT_Pricing_Information__c/fields/ETT_Selling_Price_P__c.field-meta.xml
<CustomField>
    <fullName>ETT_Selling_Price_P__c</fullName>
    <label>Selling Price P</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

unpackaged/main/default/objects/ETT_Pricing_Information__c/fields/ETT_Selling_Price_P_Approval_Status__c.field-meta.xml
<CustomField>
    <fullName>ETT_Selling_Price_P_Approval_Status__c</fullName>
    <label>Selling Price P Approval Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>New</fullName>
            </value>
            <value>
                <fullName>In Progress</fullName>
            </value>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>Rejected</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/ETT_Pricing_Information__c/fields/ETT_Selling_price_P_Comments__c.field-meta.xml
<CustomField>
    <fullName>ETT_Selling_price_P_Comments__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Selling price P Comments</label>
    <type>TextArea</type>
</CustomField>

unpackaged/main/default/classes/ETT_PricingInformationTriggerHandler.cls
/*
Created By  :G.Krishnareddy
Create Date :15/05/2020
Description :Pricing Information data
*/
public class ETT_PricingInformationTriggerHandler {
    
    public static boolean isRecursive = true; 
    
    //This is creating the Updated  Price History new records whenever the price changes happening 
    public static void pricingInformationHandleUpdate(map<Id,ETT_Pricing_Information__c> mapOfNewPricingInformations,map<Id,ETT_Pricing_Information__c> mapOfOldPricingInformations){
        list<Sobject> lstNewObjects = new list<Sobject>();
        
        //Preparing the Event Logs and Pricining Information History Preparation
        for(ETT_Pricing_Information__c objNewPricingInformation :[Select Id,ETT_Price__r.ETT_Party_Name__r.Party_Type__c,
                                                                  ETT_Buying_Approval_Status__c,ETT_Repair_Price_Approval_Status__c,
                                                                  ETT_Retread_H_Price_Approval_Status__c,
                                                                  ETT_Retread_Price_P_Approval_Status__c,ETT_Scrap_Price_Approval_Status__c,
                                                                  ETT_Selling_Price_H_Approval_Status__c,ETT_Selling_Price_P_Approval_Status__c,
                                                                  ETT_Buying_Price__c,ETT_Buying_Price_Comments__c,
                                                                  ETT_Repair_Price__c,ETT_Repair_Price_Comments__c,
                                                                  ETT_Retread_Price_H__c,ETT_Retread_Price_H_Comments__c,
                                                                  ETT_Retread_Price_P__c,ETT_Retread_Price_P_Comments__c,
                                                                  ETT_Scrap_Price__c,ETT_Scrap_Price_Comments__C,
                                                                  ETT_Selling_Price_H__c,ETT_Selling_Price_H_Comments__c,
                                                                  ETT_Selling_Price_P__c,ETT_Selling_Price_P_Comments__c,
                                                                  ETT_Purchase_Agreed_Price__c,
                                                                  ETT_Old_Buying_Price__c,ETT_New_Buying_Price__c,
                                                                  ETT_Old_Repair_Price__c,ETT_New_Repair_Price__c,
                                                                  ETT_Old_Retread_Price_H__c,ETT_New_Retread_Price_H__c,
                                                                  ETT_Old_Retread_Price_P__c,ETT_New_Retread_Price_P__c,
                                                                  ETT_New_Scrap_Price__c,ETT_Old_Scrap_Price__c,
                                                                  ETT_New_Selling_Price_H__c,ETT_Old_Selling_Price_H__c,
                                                                  ETT_New_Selling_Price_P__c,ETT_Old_Selling_Price_P__c
                                                                  FROM ETT_Pricing_Information__c where Id in :mapOfNewPricingInformations.keyset()]){ 
                                                                      
        System.debug(objNewPricingInformation);
        System.debug(mapOfOldPricingInformations);
                                                                      
                                                                      if(objNewPricingInformation.ETT_Buying_Price__c!=null && objNewPricingInformation.ETT_Buying_Price__c!=mapOfOldPricingInformations.get(objNewPricingInformation.Id).ETT_Buying_Price__c 
                                                                         && objNewPricingInformation.ETT_Buying_Approval_Status__c=='Approved'){ 
                                                                             objNewPricingInformation.ETT_Old_Buying_Price__c = mapOfOldPricingInformations.get(objNewPricingInformation.Id).ETT_Buying_Price__c;
                                                                             PricingHistoryWrapper objPriningHistoryWraper = PricingHistoryWrapper.objPricingHistoryObj('ETT_Old_Buying_Price__c',mapOfOldPricingInformations.get(objNewPricingInformation.Id).ETT_Buying_Price__c,
                                                                                                                                                                        'ETT_New_Buying_Price__c',objNewPricingInformation.ETT_Buying_Price__c,'ETT_Buying_Changed_Date__c',DateTime.now(),
                                                                                                                                                                        'ETT_Pricing_Information__c',objNewPricingInformation.Id,'ETT_Buying_Comments__c',objNewPricingInformation.ETT_Buying_Price_Comments__c,objNewPricingInformation.ETT_Price__r.ETT_Party_Name__r.Party_Type__c,
                                                                                                                                                                        'ETT_Is_Buying_Price__c',true);
                                                                             lstNewObjects.add(objPriningHistoryWraper.objEventLog);
                                                                             lstNewObjects.add(objPriningHistoryWraper.objPricingHistory);
                                                                         }
                                                                      else if(objNewPricingInformation.ETT_Buying_Approval_Status__c=='Rejected'
                                                                              && mapOfOldPricingInformations.get(objNewPricingInformation.Id).ETT_Buying_Approval_Status__c!=objNewPricingInformation.ETT_Buying_Approval_Status__c){
                                                                                  priceResetHandleUpdates(objNewPricingInformation, 'ETT_New_Buying_Price__c', 'ETT_Old_Buying_Price__c', objNewPricingInformation.ETT_Old_Buying_Price__c, objNewPricingInformation.ETT_Buying_Price_Comments__c,'ETT_Buying_Approval_Status__c');
                                                                              }
                                                                      
                                                                      
                                                                      
                                                                      if(objNewPricingInformation.ETT_Repair_Price__c!=null && objNewPricingInformation.ETT_Repair_Price__c!=mapOfOldPricingInformations.get(objNewPricingInformation.Id).ETT_Repair_Price__c
                                                                         && objNewPricingInformation.ETT_Repair_Price_Approval_Status__c=='Approved'){
                                                                             objNewPricingInformation.ETT_Old_Repair_Price__c = mapOfOldPricingInformations.get(objNewPricingInformation.Id).ETT_Repair_Price__c;
                                                                             PricingHistoryWrapper objPriningHistoryWraper = PricingHistoryWrapper.objPricingHistoryObj('ETT_Old_Repair_Price__c',mapOfOldPricingInformations.get(objNewPricingInformation.Id).ETT_Repair_Price__c,
                                                                                                                                                                        'ETT_New_Repair_Price__c',objNewPricingInformation.ETT_Repair_Price__c,'ETT_Repair_Changed_Date__c',DateTime.now(),
                                                                                                                                                                        'ETT_Pricing_Information__c',objNewPricingInformation.Id,'ETT_Repair_Price_Comments__c',objNewPricingInformation.ETT_Repair_Price_Comments__c,objNewPricingInformation.ETT_Price__r.ETT_Party_Name__r.Party_Type__c,
                                                                                                                                                                        'ETT_Is_Repair_Price__c',true);
                                                                             lstNewObjects.add(objPriningHistoryWraper.objEventLog);
                                                                             lstNewObjects.add(objPriningHistoryWraper.objPricingHistory);
                                                                         }
                                                                      else if(objNewPricingInformation.ETT_Repair_Price_Approval_Status__c=='Rejected'
                                                                              && mapOfOldPricingInformations.get(objNewPricingInformation.Id).ETT_Repair_Price_Approval_Status__c!=objNewPricingInformation.ETT_Repair_Price_Approval_Status__c){
                                                                                  priceResetHandleUpdates(objNewPricingInformation, 'ETT_New_Repair_Price__c', 'ETT_Old_Repair_Price__c', objNewPricingInformation.ETT_Old_Repair_Price__c, objNewPricingInformation.ETT_Repair_Price_Comments__c,'ETT_Repair_Price_Approval_Status__c');
                                                                              }
                                                                      
                                                                      
                                                                      if(objNewPricingInformation.ETT_Retread_Price_H__c!=null && objNewPricingInformation.ETT_Retread_Price_H__c!=mapOfOldPricingInformations.get(objNewPricingInformation.Id).ETT_Retread_Price_H__c
                                                                         && objNewPricingInformation.ETT_Retread_H_Price_Approval_Status__c=='Approved'
                                                                        ){
                                                                            objNewPricingInformation.ETT_OLD_Retread_Price_H__c =  mapOfOldPricingInformations.get(objNewPricingInformation.Id).ETT_Retread_Price_H__c; 
                                                                            PricingHistoryWrapper objPriningHistoryWraper = PricingHistoryWrapper.objPricingHistoryObj('ETT_Old_Retread_Price_H__c',mapOfOldPricingInformations.get(objNewPricingInformation.Id).ETT_Retread_Price_H__c,
                                                                                                                                                                       'ETT_New_Retread_Price_H__c',objNewPricingInformation.ETT_Retread_Price_H__c,'ETT_Retread_Price_H_Changed_Date__c',DateTime.now(),
                                                                                                                                                                       'ETT_Pricing_Information__c',objNewPricingInformation.Id,'ETT_Retread_Price_H_Comments__c',objNewPricingInformation.ETT_Retread_Price_H_Comments__c,objNewPricingInformation.ETT_Price__r.ETT_Party_Name__r.Party_Type__c,
                                                                                                                                                                       'Is_Retread_Price_H__c',true);
                                                                            objNewPricingInformation.ETT_Retread_Price_H__c = mapOfOldPricingInformations.get(objNewPricingInformation.Id).ETT_OLD_Retread_Price_H__c;
                                                                            lstNewObjects.add(objPriningHistoryWraper.objEventLog);
                                                                            lstNewObjects.add(objPriningHistoryWraper.objPricingHistory);
                                                                        }
                                                                      else if(objNewPricingInformation.ETT_Retread_H_Price_Approval_Status__c=='Rejected'
                                                                              && mapOfOldPricingInformations.get(objNewPricingInformation.Id).ETT_Retread_H_Price_Approval_Status__c!=objNewPricingInformation.ETT_Retread_H_Price_Approval_Status__c){
                                                                                  priceResetHandleUpdates(objNewPricingInformation, 'ETT_New_Retread_Price_H__c', 'ETT_Old_Retread_Price_H__c', objNewPricingInformation.ETT_Old_Retread_Price_H__c, objNewPricingInformation.ETT_Retread_Price_H_Comments__c,'ETT_Retread_H_Price_Approval_Status__c');
                                                                              }
                                                                      
                                                                      
                                                                      
                                                                      if(objNewPricingInformation.ETT_Retread_Price_P__c!=null && objNewPricingInformation.ETT_Retread_Price_P__c!=mapOfOldPricingInformations.get(objNewPricingInformation.Id).ETT_Retread_Price_P__c
                                                                         && objNewPricingInformation.ETT_Retread_Price_P_Approval_Status__c=='Approved'){
                                                                             objNewPricingInformation.ETT_Old_Retread_Price_P__c = mapOfOldPricingInformations.get(objNewPricingInformation.Id).ETT_Retread_Price_P__c;
                                                                             PricingHistoryWrapper objPriningHistoryWraper = PricingHistoryWrapper.objPricingHistoryObj('ETT_Old_Retread_Price_P__c',mapOfOldPricingInformations.get(objNewPricingInformation.Id).ETT_Retread_Price_P__c,
                                                                                                                                                                        'ETT_New_Retread_Price_P__c',objNewPricingInformation.ETT_Retread_Price_P__c,'ETT_Retread_Price_P_Changed_Date__c',DateTime.now(),
                                                                                                                                                                        'ETT_Pricing_Information__c',objNewPricingInformation.Id,'ETT_Retread_Price_P_Comments__c',objNewPricingInformation.ETT_Retread_Price_P_Comments__c,objNewPricingInformation.ETT_Price__r.ETT_Party_Name__r.Party_Type__c
                                                                                                                                                                        ,'ETT_Is_Retread_Price_P__c',true);
                                                                             lstNewObjects.add(objPriningHistoryWraper.objEventLog);
                                                                             lstNewObjects.add(objPriningHistoryWraper.objPricingHistory); 
                                                                         }   
                                                                      
                                                                      else if(objNewPricingInformation.ETT_Retread_Price_P_Approval_Status__c=='Rejected'
                                                                              && mapOfOldPricingInformations.get(objNewPricingInformation.Id).ETT_Retread_Price_P_Approval_Status__c!=objNewPricingInformation.ETT_Retread_Price_P_Approval_Status__c){
                                                                                  priceResetHandleUpdates(objNewPricingInformation, 'ETT_New_Retread_Price_P__c', 'ETT_Old_Retread_Price_P__c', objNewPricingInformation.ETT_Old_Retread_Price_P__c, objNewPricingInformation.ETT_Retread_Price_P_Comments__c,'ETT_Retread_Price_P_Approval_Status__c');
                                                                              }                  
                                                                      
                                                                      
                                                                      
                                                                      if(objNewPricingInformation.ETT_Scrap_Price__c!=null && objNewPricingInformation.ETT_Scrap_Price__c!=mapOfOldPricingInformations.get(objNewPricingInformation.Id).ETT_Scrap_Price__c
                                                                         && objNewPricingInformation.ETT_Scrap_Price_Approval_Status__c=='Approved'){
                                                                             objNewPricingInformation.ETT_Old_Scrap_Price__c = mapOfOldPricingInformations.get(objNewPricingInformation.Id).ETT_Scrap_Price__c;
                                                                             PricingHistoryWrapper objPriningHistoryWraper = PricingHistoryWrapper.objPricingHistoryObj('ETT_Old_Scrap_Price__c',mapOfOldPricingInformations.get(objNewPricingInformation.Id).ETT_Scrap_Price__c,
                                                                                                                                                                        'ETT_New_Scrap_Price__c',objNewPricingInformation.ETT_Scrap_Price__c,'ETT_Scrap_Price_Changed_Date__c',DateTime.now(),
                                                                                                                                                                        'ETT_Pricing_Information__c',objNewPricingInformation.Id,'ETT_Scrap_Price_Comments__C',objNewPricingInformation.ETT_Scrap_Price_Comments__C,objNewPricingInformation.ETT_Price__r.ETT_Party_Name__r.Party_Type__c,
                                                                                                                                                                        'ETT_Is_Scrap_Price__c',true);
                                                                             lstNewObjects.add(objPriningHistoryWraper.objEventLog);
                                                                             lstNewObjects.add(objPriningHistoryWraper.objPricingHistory);
                                                                         } else if(objNewPricingInformation.ETT_Scrap_Price_Approval_Status__c=='Rejected'
                                                                                   && mapOfOldPricingInformations.get(objNewPricingInformation.Id).ETT_Scrap_Price_Approval_Status__c!=objNewPricingInformation.ETT_Scrap_Price_Approval_Status__c){
                                                                                       priceResetHandleUpdates(objNewPricingInformation, 'ETT_New_Scrap_Price__c', 'ETT_Old_Scrap_Price__c', objNewPricingInformation.ETT_Old_Scrap_Price__c, objNewPricingInformation.ETT_Scrap_Price_Comments__C,'ETT_Scrap_Price_Approval_Status__c');
                                                                                   }  
                                                                      
                                                                      
                                                                      if(objNewPricingInformation.ETT_Selling_Price_H__c!=null && objNewPricingInformation.ETT_Selling_Price_H__c!=mapOfOldPricingInformations.get(objNewPricingInformation.Id).ETT_Selling_Price_H__c
                                                                         && objNewPricingInformation.ETT_Selling_Price_H_Approval_Status__c=='Approved'){
                                                                             objNewPricingInformation.ETT_OLD_Selling_Price_H__c = mapOfOldPricingInformations.get(objNewPricingInformation.Id).ETT_Selling_Price_H__c;
                                                                             PricingHistoryWrapper objPriningHistoryWraper = PricingHistoryWrapper.objPricingHistoryObj('ETT_Old_Selling_Price_H__c',mapOfOldPricingInformations.get(objNewPricingInformation.Id).ETT_Selling_Price_H__c,
                                                                                                                                                                        'ETT_New_Selling_Price_H__c',objNewPricingInformation.ETT_Selling_Price_H__c,'ETT_Selling_Price_H_Changed_Date__c',DateTime.now(),
                                                                                                                                                                        'ETT_Pricing_Information__c',objNewPricingInformation.Id,'ETT_Selling_Price_H_Comments__c',objNewPricingInformation.ETT_Selling_Price_H_Comments__c,objNewPricingInformation.ETT_Price__r.ETT_Party_Name__r.Party_Type__c,
                                                                                                                                                                        'ETT_Is_Selling_Price_H__c',true);
                                                                             lstNewObjects.add(objPriningHistoryWraper.objEventLog);
                                                                             lstNewObjects.add(objPriningHistoryWraper.objPricingHistory);
                                                                         }else if(objNewPricingInformation.ETT_Selling_Price_H_Approval_Status__c=='Rejected'
                                                                                  && mapOfOldPricingInformations.get(objNewPricingInformation.Id).ETT_Selling_Price_H_Approval_Status__c!=objNewPricingInformation.ETT_Selling_Price_H_Approval_Status__c){
                                                                                      priceResetHandleUpdates(objNewPricingInformation, 'ETT_New_Selling_Price_H__c', 'ETT_Old_Selling_Price_H__c', objNewPricingInformation.ETT_Old_Selling_Price_H__c, objNewPricingInformation.ETT_Selling_Price_H_Comments__c,'ETT_Selling_Price_H_Approval_Status__c');
                                                                                  }  
                                                                      
                                                                      
                                                                      if(objNewPricingInformation.ETT_Selling_Price_P__c!=null && objNewPricingInformation.ETT_Selling_Price_P__c!=mapOfOldPricingInformations.get(objNewPricingInformation.Id).ETT_Selling_Price_P__c
                                                                         && objNewPricingInformation.ETT_Selling_Price_P_Approval_Status__c=='Approved'){
                                                                             PricingHistoryWrapper objPriningHistoryWraper = PricingHistoryWrapper.objPricingHistoryObj('ETT_Old_Selling_Price_P__c',mapOfOldPricingInformations.get(objNewPricingInformation.Id).ETT_Selling_Price_P__c,
                                                                                                                                                                        'ETT_New_Selling_Price_P__c',objNewPricingInformation.ETT_Selling_Price_P__c,'ETT_Selling_Price_P_Changed_Date__c',DateTime.now(),
                                                                                                                                                                        'ETT_Pricing_Information__c',objNewPricingInformation.Id,'ETT_Selling_Price_P_Comments__c',objNewPricingInformation.ETT_Selling_Price_P_Comments__c,objNewPricingInformation.ETT_Price__r.ETT_Party_Name__r.Party_Type__c,
                                                                                                                                                                        'ETT_Is_Selling_Price_P__c',true);
                                                                             objNewPricingInformation.ETT_OLD_Selling_Price_P__c  = mapOfOldPricingInformations.get(objNewPricingInformation.Id).ETT_Selling_Price_P__c;  
                                                                             lstNewObjects.add(objPriningHistoryWraper.objEventLog); 
                                                                             lstNewObjects.add(objPriningHistoryWraper.objPricingHistory);                  
                                                                         }
                                                                      
                                                                      else if(objNewPricingInformation.ETT_Selling_Price_P_Approval_Status__c=='Rejected'
                                                                              && mapOfOldPricingInformations.get(objNewPricingInformation.Id).ETT_Selling_Price_P_Approval_Status__c!=objNewPricingInformation.ETT_Selling_Price_P_Approval_Status__c){
                                                                                  priceResetHandleUpdates(objNewPricingInformation, 'ETT_New_Selling_Price_P__c', 'ETT_Old_Selling_Price_P__c', objNewPricingInformation.ETT_Old_Selling_Price_P__c, objNewPricingInformation.ETT_Selling_Price_P_Comments__c,'ETT_Selling_Price_P_Approval_Status__c');
                                                                              }  
                                                                      
                                                                      
                                                                  }    
        
        //Inserting Event Log and Price Information History 
        if(!lstNewObjects.isEmpty() && !Test.isRunningTest()){
            ETT_PricingInformationTriggerHandler.isRecursive = false;
            insert lstNewObjects;
        } 
    }
    
    public static void priceResetHandleUpdates(ETT_Pricing_Information__c objnewObject,string strNewPriceField,string strOldField,Decimal oldPriceData,string strCommentField,string strStatusField){
        objnewObject.put(strNewPriceField,oldPriceData);
        objnewObject.put(strOldField,null);
        objnewObject.put(strStatusField,'New'); 
        objnewObject.put(strCommentField,'');
    }
    
    public static PricingHistoryWrapper objPricingHistoryObj(string strPriceOldApiName,Decimal oldPrice,string strPriceNewApiName,Decimal newPrice,string strChangedDateTimeField,DateTime changedDateTime,string strParentId,Id pricingInformationId,string strCommentsField,string strComments,string strRecordTypeName,
                                                             string strBooleanField,boolean isProcess){
                                                                 PricingHistoryWrapper objPricingInformationWrap = new PricingHistoryWrapper();
                                                                 
                                                                 ETT_Price_Information_History__c objPricingInformationHistory = new ETT_Price_Information_History__c();
                                                                 objPricingInformationHistory.put(strPriceOldApiName,oldPrice);
                                                                 objPricingInformationHistory.put(strPriceNewApiName,newPrice);
                                                                 objPricingInformationHistory.put(strCommentsField,strComments);
                                                                 objPricingInformationHistory.put(strChangedDateTimeField,changedDateTime);
                                                                 objPricingInformationHistory.put(strParentId,pricingInformationId);
                                                                 objPricingInformationHistory.put('RecordTypeId',Schema.SObjectType.ETT_Price_Information_History__c.getRecordTypeInfosByName().get(strRecordTypeName).getRecordTypeId());
                                                                 
                                                                 ETT_Event_Log__c objEventLog = new ETT_Event_Log__c();
                                                                 objEventLog.ETT_Object_Name__c = 'ETT_Pricing_Information__c';
                                                                 objEventLog.ETT_Sobject_Id__c  = pricingInformationId;
                                                                 objEventLog.put(strBooleanField,isProcess);
                                                                 objPricingInformationWrap.objPricingHistory = objPricingInformationHistory;
                                                                 objPricingInformationWrap.objEventLog = objEventLog;
                                                                 
                                                                 return objPricingInformationWrap;
                                                             }
    
    public Class PricingHistoryWrapper{
        public ETT_Price_Information_History__c objPricingHistory;
        public ETT_Event_Log__c objEventLog;
    }
    
    
}