unpackaged/main/default/objects/Correction_Cancel_Request__c/Correction_Cancel_Request__c.object-meta.xml
<CustomObject>
    <label>Vehicle Requests</label>
    <nameField>
        <displayFormat>Req - {000000}</displayFormat>
        <label>Request Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Vehicle Requests</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Correction_Cancel_Request__c/fields/Claim__c.field-meta.xml
<CustomField>
    <fullName>Claim__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Claim</label>
    <referenceTo>ETIN_Claim__c</referenceTo>
    <relationshipName>Correction_Cancel_Requests</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Correction_Cancel_Request__c/fields/Comments__c.field-meta.xml
<CustomField>
    <fullName>Comments__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Comments</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

unpackaged/main/default/objects/Correction_Cancel_Request__c/fields/Correction_for__c.field-meta.xml
<CustomField>
    <fullName>Correction_for__c</fullName>
    <label>Correction for</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Chassis Number</fullName>
            </value>
            <value>
                <fullName>Engine Number</fullName>
            </value>
            <value>
                <fullName>Vehicle Make</fullName>
            </value>
            <value>
                <fullName>Vehicle Model</fullName>
            </value>
            <value>
                <fullName>Year</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Correction_Cancel_Request__c/fields/Insurance_Company__c.field-meta.xml
<CustomField>
    <fullName>Insurance_Company__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Insurance Company</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Vehicle Requests</relationshipLabel>
    <relationshipName>Correction_Cancel_Requests</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Correction_Cancel_Request__c/fields/Request_Status__c.field-meta.xml
<CustomField>
    <fullName>Request_Status__c</fullName>
    <label>Request Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>New</fullName>
                <default>true</default>
                <label>New</label>
            </value>
            <value>
                <fullName>Insurance Pending</fullName>
            </value>
            <value>
                <fullName>Insurance Approved</fullName>
            </value>
            <value>
                <fullName>Insurance Rejected</fullName>
            </value>
            <value>
                <fullName>Vehicle Found</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Correction_Cancel_Request__c/fields/Vehicle_Insurance_Policy__c.field-meta.xml
<CustomField>
    <fullName>Vehicle_Insurance_Policy__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Vehicle Insurance Policy</label>
    <referenceTo>ETVIN_Vehicle_Insurance__c</referenceTo>
    <relationshipLabel>Vehicle Requests</relationshipLabel>
    <relationshipName>Correction_Cancel_Requests</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Correction_Cancel_Request__c/fields/Vehicle_Master__c.field-meta.xml
<CustomField>
    <fullName>Vehicle_Master__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Vehicle</label>
    <referenceTo>Vehicle_Master__c</referenceTo>
    <relationshipName>Correction_Cancel_Requests</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/ETIN_Claim__c/ETIN_Claim__c.object-meta.xml
<CustomObject>
    <label>Claim</label>
    <nameField>
        <displayFormat>CL-{000000}</displayFormat>
        <label>Claim Ref Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Claims</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/ETIN_Claim__c/fields/Claim_for__c.field-meta.xml
<CustomField>
    <fullName>Claim_for__c</fullName>
    <label>Claim for</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Vehicle Theft</fullName>
            </value>
            <value>
                <fullName>Accident</fullName>
            </value>
            <value>
                <fullName>Scrapped Vehicle</fullName>
            </value>
            <value>
                <fullName>Scrapped Vehicle Theft</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/ETIN_Claim__c/fields/ETIN_Claim_Status__c.field-meta.xml
<CustomField>
    <fullName>ETIN_Claim_Status__c</fullName>
    <label>Claim Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>New</fullName>
                <default>true</default>
                <label>New</label>
            </value>
            <value>
                <fullName>Under Process</fullName>
            </value>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>Rejected</fullName>
            </value>
            <value>
                <fullName>Pending with Zone Coordinator</fullName>
            </value>
            <value>
                <fullName>Under Approval</fullName>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
            <value>
                <fullName>Pending</fullName>
            </value>
            <value>
                <fullName>Admin Approval Pending</fullName>
                <isActive>false</isActive>
                <label>Admin Approval Pending</label>
            </value>
            <value>
                <fullName>Admin Approved</fullName>
                <isActive>false</isActive>
                <label>Admin Approved</label>
            </value>
            <value>
                <fullName>Admin Rejected</fullName>
                <isActive>false</isActive>
                <label>Admin Rejected</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/ETIN_Claim__c/fields/ETIN_Insurance_Partner__c.field-meta.xml
<CustomField>
    <fullName>ETIN_Insurance_Partner__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Insurance Partner</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Claim</relationshipLabel>
    <relationshipName>Claim</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/ETIN_Claim__c/fields/ETVIN_Vehicle_Insurance__c.field-meta.xml
<CustomField>
    <fullName>ETVIN_Vehicle_Insurance__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Vehicle Insurance</label>
    <referenceTo>ETVIN_Vehicle_Insurance__c</referenceTo>
    <relationshipLabel>Claims</relationshipLabel>
    <relationshipName>Claims</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/ETIN_Claim__c/fields/Vehicle_Master__c.field-meta.xml
<CustomField>
    <fullName>Vehicle_Master__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Vehicle</label>
    <referenceTo>Vehicle_Master__c</referenceTo>
    <relationshipLabel>Claims</relationshipLabel>
    <relationshipName>Claims</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/ETIN_Claim__c/recordTypes/Vehicle_Insurance.recordType-meta.xml
<RecordType>
    <fullName>Vehicle_Insurance</fullName>
    <active>true</active>
    <label>Vehicle Insurance</label>
</RecordType>

unpackaged/main/default/objects/ETIN_Insurance_Transactions__c/ETIN_Insurance_Transactions__c.object-meta.xml
<CustomObject>
    <label>Insurance Invoices</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Invoice Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Insurance Invoices</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/ETIN_Insurance_Transactions__c/fields/Claim__c.field-meta.xml
<CustomField>
    <fullName>Claim__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Claim</label>
    <referenceTo>ETIN_Claim__c</referenceTo>
    <relationshipName>Insurance_Transactions</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/ETIN_Insurance_Transactions__c/fields/ETIN_Amount__c.field-meta.xml
<CustomField>
    <fullName>ETIN_Amount__c</fullName>
    <label>Amount</label>
    <precision>18</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

unpackaged/main/default/objects/ETIN_Insurance_Transactions__c/fields/Vehicle_Insurance_Policy__c.field-meta.xml
<CustomField>
    <fullName>Vehicle_Insurance_Policy__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Vehicle Insurance Policy</label>
    <referenceTo>ETVIN_Vehicle_Insurance__c</referenceTo>
    <relationshipName>Insurance_Transactions</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/ETIN_Insurance_Transactions__c/fields/Vehicle_Master__c.field-meta.xml
<CustomField>
    <fullName>Vehicle_Master__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Vehicle</label>
    <referenceTo>Vehicle_Master__c</referenceTo>
    <relationshipName>Insurance_Transactions</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/ETVIN_Vehicle_Insurance__c/ETVIN_Vehicle_Insurance__c.object-meta.xml
<CustomObject>
    <description>Vehicle Insurance</description>
    <label>Vehicle Insurance Policy</label>
    <nameField>
        <displayFormat>VI-{0000}</displayFormat>
        <label>Insurance Ref Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Vehicle Insurance Policies</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/ETVIN_Vehicle_Insurance__c/fields/ETVIN_Effective_Date__c.field-meta.xml
<CustomField>
    <fullName>ETVIN_Effective_Date__c</fullName>
    <defaultValue>TODAY()</defaultValue>
    <encryptionScheme>None</encryptionScheme>
    <label>Effective Date</label>
    <type>Date</type>
</CustomField>

unpackaged/main/default/objects/ETVIN_Vehicle_Insurance__c/fields/ETVIN_Expiry_Date__c.field-meta.xml
<CustomField>
    <fullName>ETVIN_Expiry_Date__c</fullName>
    <defaultValue>DATE(YEAR(TODAY()), 12, 31)</defaultValue>
    <encryptionScheme>None</encryptionScheme>
    <label>Expiry Date</label>
    <type>Date</type>
</CustomField>

unpackaged/main/default/objects/ETVIN_Vehicle_Insurance__c/fields/ETVIN_Insurance_Company__c.field-meta.xml
<CustomField>
    <fullName>ETVIN_Insurance_Company__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Insurance Company</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Vehicle Insurance Policies</relationshipLabel>
    <relationshipName>Vehicle_Insurances</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/ETVIN_Vehicle_Insurance__c/fields/ETVIN_Insurance_Status__c.field-meta.xml
<CustomField>
    <fullName>ETVIN_Insurance_Status__c</fullName>
    <label>Insurance Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Active</fullName>
            </value>
            <value>
                <fullName>Inactive</fullName>
                <default>true</default>
                <label>Inactive</label>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
            <value>
                <fullName>Duplicate</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/ETVIN_Vehicle_Insurance__c/fields/ETVIN_Request_Status__c.field-meta.xml
<CustomField>
    <fullName>ETVIN_Request_Status__c</fullName>
    <label>Request Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>New</fullName>
                <default>true</default>
                <label>New</label>
            </value>
            <value>
                <fullName>Insurance Approved</fullName>
            </value>
            <value>
                <fullName>Insurance Rejected</fullName>
            </value>
            <value>
                <fullName>Insurance Pending</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/ETVIN_Vehicle_Insurance__c/fields/Vehicle__c.field-meta.xml
<CustomField>
    <fullName>Vehicle__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Vehicle</label>
    <referenceTo>Vehicle_Master__c</referenceTo>
    <relationshipLabel>Vehicle Insurance Policies</relationshipLabel>
    <relationshipName>Vehicle_Insurance_Policies</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Vehicle_Master__c/Vehicle_Master__c.object-meta.xml
<CustomObject>
    <description>Emirates Transport Oracle Vehicle Master</description>
    <label>ET Vehicle Master</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Vehicle No.</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>ET Vehicle Masters</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Vehicle_Master__c/fields/Internal_No__c.field-meta.xml
<CustomField>
    <fullName>Internal_No__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <externalId>true</externalId>
    <label>Internal No</label>
    <length>100</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Vehicle_Master__c/fields/Plate_Type__c.field-meta.xml
<CustomField>
    <fullName>Plate_Type__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Plate Type</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/classes/ETVIN_ShowVehicleInsuranceCtrlTest.cls
@isTest(SeeAllData=true)
public class ETVIN_ShowVehicleInsuranceCtrlTest {
    
    private static testmethod void getInsuranceDetailsTest(){
        
         Vehicle_Master__c ve =  new Vehicle_Master__c();
        ve.name = 'B0017298';
        ve.Internal_No__c = 'B0017298';
        ve.Plate_Type__c = 'Private';
        insert ve;
        
        Account acc = new Account();
        //acc.RecordTypeId = Schema.SObjectType.Account.getRecordTypeInfosByDeveloperName().get('Insurance_Partner').getRecordTypeId();
        acc.Name = 'xyz32454';
        
        insert acc;
        ETVIN_Vehicle_Insurance__c etv = new ETVIN_Vehicle_Insurance__c();
        etv.Vehicle__c = ve.Id;
        etv.ETVIN_Insurance_Status__c = 'Active';
        etv.ETVIN_Request_Status__c  = 'Insurance Approved';
        etv.ETVIN_Insurance_Company__c = acc.id;
        etv.ETVIN_Effective_Date__c = system.today();
        etv.ETVIN_Expiry_Date__c =system.today()+365;
        insert etv;
        
        Correction_Cancel_Request__c cor = new Correction_Cancel_Request__c();
        cor.Comments__c = 'test';
        cor.Correction_for__c ='Chassis Number';
        cor.Insurance_Company__c = acc.id;
        cor.Vehicle_Insurance_Policy__c = etv.Id;
        cor.Vehicle_Master__c=ve.Id;
        cor.Request_Status__c='Insurance Approved';
        insert cor;
        
         ETVIN_ShowVehicleInsuranceCtrl.updateStatusForCorrectionRequest(cor.Id,'Approved');
     
         ETVIN_ShowVehicleInsuranceCtrl.updateStatusForCorrectionRequest(cor.Id,'');
    }
  
    private static testmethod void getInsuranceDetails(){
        
        test.startTest();
        ETVIN_ShowVehicleInsuranceCtrl.getInsurancePoliciyDetails();
        
        Vehicle_Master__c ve =  new Vehicle_Master__c();
        ve.name = 'B0017298';
        ve.Internal_No__c = 'B0017298';
        ve.Plate_Type__c = 'Private';
        insert ve;
        
        Account acc = new Account();
        //acc.RecordTypeId = Schema.SObjectType.Account.getRecordTypeInfosByDeveloperName().get('Insurance_Partner').getRecordTypeId();
        acc.Name = 'xyz32454';
        
        insert acc;
        
        ETVIN_Vehicle_Insurance__c etv = new ETVIN_Vehicle_Insurance__c();
        etv.Vehicle__c = ve.Id;
        etv.ETVIN_Insurance_Status__c = 'Active';
        etv.ETVIN_Request_Status__c  = 'Insurance Approved';
        etv.ETVIN_Insurance_Company__c = acc.id;
        etv.ETVIN_Effective_Date__c = system.today();
        etv.ETVIN_Expiry_Date__c =system.today()+365;
        insert etv;
        
        ETVIN_ShowVehicleInsuranceCtrl.updateStatus(etv.id,'Approved',new ETIN_Insurance_Transactions__c(ETIN_Amount__c=2000));
        
        ETVIN_ShowVehicleInsuranceCtrl.updateStatus(etv.id,'',new ETIN_Insurance_Transactions__c(ETIN_Amount__c=2000));
       
        ETVIN_ShowVehicleInsuranceCtrl.updateInsurancePoliciy(etv.Id);
        ETVIN_ShowVehicleInsuranceCtrl.getPicklistValues('case','status');
        ETVIN_ShowVehicleInsuranceCtrl.getInsuranceClaimsDetails();
        
        ETVIN_ShowVehicleInsuranceCtrl.saveTheFile(etv.Id,'test','gefdsf','.pdf');
        ETVIN_ShowVehicleInsuranceCtrl.fetchContentDocument(etv.Id);
        
        ETIN_Claim__c ec = new ETIN_Claim__c();
        ec.Claim_Amount__c = 200;
        ec.ETIN_Insurance_Partner__c = acc.Id;
        ec.ETIN_Claim_Status__c = 'New';
        ec.Vehicle_Master__c = ve.Id;
        ec.RecordTypeId =Schema.SObjectType.ETIN_Claim__c.getRecordTypeInfosByDeveloperName().get('Vehicle_Insurance').getRecordTypeId();
        insert ec;
        
        ec.ETIN_Claim_Status__c = 'Approved';
        ec.Claim_for__c = 'Scrapped Vehicle Theft';
        update ec;
        
        ETIN_Insurance_Transactions__c eit = new ETIN_Insurance_Transactions__c();
        eit.Claim__c = ec.Id;
        eit.ETIN_Amount__c = 100;
        eit.ETIN_AP_Type__c = 'Debit Note';
        insert eit;
        ETVIN_ShowVehicleInsuranceCtrl.getInsuranceInsuranceTransactions(ec.Id); 
        
        ETVIN_ShowVehicleInsuranceCtrl.getCorrectionRequestDetails('Cancellation Request');
        ETVIN_ShowVehicleInsuranceCtrl.getCancelTheftReq('Cancellation Request');
        
        
        
        
       ETVIN_ShowVehicleInsuranceCtrl.updateStatusForClaims(ec.Id,'Approved');
       
        test.stopTest();
    }
}