unpackaged/main/default/objects/Correction_Cancel_Request__c/Correction_Cancel_Request__c.object-meta.xml
<CustomObject>
    <label>Vehicle Requests</label>
    <nameField>
        <displayFormat>Req - {000000}</displayFormat>
        <label>Request Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Vehicle Requests</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/ETCAR_Car__c/ETCAR_Car__c.object-meta.xml
<CustomObject>
    <label>Car</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Car Model</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Cars</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/ETCAR_Features__c/ETCAR_Features__c.object-meta.xml
<CustomObject>
    <label>Features</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Features Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Features</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/ETIN_Claim__c/ETIN_Claim__c.object-meta.xml
<CustomObject>
    <label>Claim</label>
    <nameField>
        <displayFormat>CL-{000000}</displayFormat>
        <label>Claim Ref Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Claims</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/ETIN_Claim__c/fields/ETVIN_Vehicle_Insurance__c.field-meta.xml
<CustomField>
    <fullName>ETVIN_Vehicle_Insurance__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Vehicle Insurance</label>
    <referenceTo>ETVIN_Vehicle_Insurance__c</referenceTo>
    <relationshipLabel>Claims</relationshipLabel>
    <relationshipName>Claims</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/ETVIN_Vehicle_Insurance__c/ETVIN_Vehicle_Insurance__c.object-meta.xml
<CustomObject>
    <description>Vehicle Insurance</description>
    <label>Vehicle Insurance Policy</label>
    <nameField>
        <displayFormat>VI-{0000}</displayFormat>
        <label>Insurance Ref Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Vehicle Insurance Policies</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/HSE_Info__c/HSE_Info__c.object-meta.xml
<CustomObject>
    <label>HSE Info</label>
    <nameField>
        <displayFormat>HSE-{0000}</displayFormat>
        <label>HSE Ref. No.</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>HSE Info</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/classes/ETC_ContentDocumentsTriggerHandler.cls
public class ETC_ContentDocumentsTriggerHandler {
    /* Method : To give file access to External Users when file is inserted in system
                Give Sharing access to  files inserted for -- 'ETCAR_Car__c' & 'ETCAR_Features__c'
     */
    public static void giveFileAccesstoExternalUsers(List<ContentDocumentLink> newdocs){
        
        String carPrefix = Schema.getGlobalDescribe().get('ETCAR_Car__c').getDescribe().getKeyPrefix();
        String featPrefix = Schema.getGlobalDescribe().get('ETCAR_Features__c').getDescribe().getKeyPrefix();
        
        //Added By Janardhan for Vehicle Insurance
         String vehInsReq = Schema.getGlobalDescribe().get('Correction_Cancel_Request__c').getDescribe().getKeyPrefix();
         String vehClaim = Schema.getGlobalDescribe().get('ETIN_Claim__c').getDescribe().getKeyPrefix();
         String vehInsPolicy = Schema.getGlobalDescribe().get('ETVIN_Vehicle_Insurance__c').getDescribe().getKeyPrefix();
         String hseInfo = Schema.getGlobalDescribe().get('HSE_Info__c').getDescribe().getKeyPrefix();
        
        
        for (ContentDocumentLink cdl : newdocs) {
            if (String.valueOf(cdl.LinkedEntityId).startsWithIgnoreCase(carPrefix) || 
                String.valueOf(cdl.LinkedEntityId).startsWithIgnoreCase(featPrefix) || 
                string.valueOf(cdl.LinkedEntityId).startsWithIgnoreCase(vehInsReq) || 
                string.valueOf(cdl.LinkedEntityId).startsWithIgnoreCase(vehClaim) ||
                 string.valueOf(cdl.LinkedEntityId).startsWithIgnoreCase(vehInsPolicy)||
                string.valueOf(cdl.LinkedEntityId).startsWithIgnoreCase(hseInfo)
               ) {
                cdl.Visibility = 'AllUsers';
            }                         
        }
    }
}