unpackaged/main/default/objects/Campaign/fields/Campaign_Code__c.field-meta.xml
<CustomField>
    <fullName>Campaign_Code__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <externalId>true</externalId>
    <label>Campaign Code</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/ETSALES_Department__c/ETSALES_Department__c.object-meta.xml
<CustomObject>
    <label>GL Department</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>GL Department</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>GL Departments</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/ETSALES_Department__c/fields/Department_Code__c.field-meta.xml
<CustomField>
    <fullName>Department_Code__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Department Code</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/ETSALES_Location__c/ETSALES_Location__c.object-meta.xml
<CustomObject>
    <label>GL Location</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>GL Location</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>GL Locations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/ETSALES_Location__c/fields/Location_Code__c.field-meta.xml
<CustomField>
    <fullName>Location_Code__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Location Code</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/GL_Activity__c/GL_Activity__c.object-meta.xml
<CustomObject>
    <description>to have the oracle GL Activity in SF</description>
    <label>GL Activity</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>GL Activity</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>GL Activities</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/GL_Activity__c/fields/GL_Activity_Code__c.field-meta.xml
<CustomField>
    <fullName>GL_Activity_Code__c</fullName>
    <description>to capture the GL Activity Code</description>
    <encryptionScheme>None</encryptionScheme>
    <label>GL Activity Code</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/GL_Project__c/GL_Project__c.object-meta.xml
<CustomObject>
    <description>to create GL Project of Oracle</description>
    <label>GL Project</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>GL Project</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>GL Projects</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/GL_Project__c/fields/Project_Code__c.field-meta.xml
<CustomField>
    <fullName>Project_Code__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Project Code</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Lead/fields/Contract_Years__c.field-meta.xml
<CustomField>
    <fullName>Contract_Years__c</fullName>
    <label>Contract Years</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>ETSales_No_of_Years</valueSetName>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Lead/fields/Emirates_Moto_Campaign__c.field-meta.xml
<CustomField>
    <fullName>Emirates_Moto_Campaign__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Emirates Moto Campaign</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Lead/fields/ETSALES_Budget__c.field-meta.xml
<CustomField>
    <fullName>ETSALES_Budget__c</fullName>
    <label>Customer Budget</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

unpackaged/main/default/objects/Lead/fields/ETSALES_Lead_Rating__c.field-meta.xml
<CustomField>
    <fullName>ETSALES_Lead_Rating__c</fullName>
    <label>Prospect Rating</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Hot</fullName>
            </value>
            <value>
                <fullName>Warm</fullName>
            </value>
            <value>
                <fullName>Cold</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Lead/fields/GL_Activity__c.field-meta.xml
<CustomField>
    <fullName>GL_Activity__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>GL Activity</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Lead/fields/GL_Department__c.field-meta.xml
<CustomField>
    <fullName>GL_Department__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>GL Department</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Lead/fields/GL_Project_Code__c.field-meta.xml
<CustomField>
    <fullName>GL_Project_Code__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>GL Project Code</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Lead/fields/No_of_Used_Vehicles__c.field-meta.xml
<CustomField>
    <fullName>No_of_Used_Vehicles__c</fullName>
    <label>No. of Used Vehicles</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

unpackaged/main/default/objects/Lead/fields/Preferred_Location__c.field-meta.xml
<CustomField>
    <fullName>Preferred_Location__c</fullName>
    <label>Preferred Location</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Location</valueSetName>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Lead/fields/Request_Category__c.field-meta.xml
<CustomField>
    <fullName>Request_Category__c</fullName>
    <label>Request Category</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Passenger Transportation</fullName>
            </value>
            <value>
                <fullName>School Transportation</fullName>
            </value>
            <value>
                <fullName>Lease</fullName>
            </value>
            <value>
                <fullName>Maintenance and Technical services</fullName>
            </value>
            <value>
                <fullName>General inquiry</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Lead/fields/Sector__c.field-meta.xml
<CustomField>
    <fullName>Sector__c</fullName>
    <label>Sector</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Transport and Lease</fullName>
            </value>
            <value>
                <fullName>School</fullName>
            </value>
            <value>
                <fullName>MRO</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Lead/fields/Service_Required__c.field-meta.xml
<CustomField>
    <fullName>Service_Required__c</fullName>
    <label>Service Category</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Emirates_Moto_Service</valueSetName>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Lead/fields/Vehicle_Brand__c.field-meta.xml
<CustomField>
    <fullName>Vehicle_Brand__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Vehicle Brand</label>
    <referenceTo>Vehicle_Brand_Master__c</referenceTo>
    <relationshipLabel>Leads</relationshipLabel>
    <relationshipName>Leads</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Lead/fields/Vehicle_Brand_Pick__c.field-meta.xml
<CustomField>
    <fullName>Vehicle_Brand_Pick__c</fullName>
    <label>Vehicle Brand</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Vehicle_Brand_Master</valueSetName>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Lead/fields/Vehicle_Model_Pick__c.field-meta.xml
<CustomField>
    <fullName>Vehicle_Model_Pick__c</fullName>
    <label>Vehicle Model</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Vehicle_Brand_Pick__c</controllingField>
        <restricted>true</restricted>
        <valueSetName>Vehicle_Model_Master</valueSetName>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/User/fields/ETSALES_Employee_Zone__c.field-meta.xml
<CustomField>
    <fullName>ETSALES_Employee_Zone__c</fullName>
    <label>Employee Zone</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Zone A</fullName>
            </value>
            <value>
                <fullName>Zone B</fullName>
            </value>
            <value>
                <fullName>Zone C</fullName>
            </value>
            <value>
                <fullName>Head Office</fullName>
            </value>
            <value>
                <fullName>Technical Services</fullName>
            </value>
            <value>
                <fullName>HO</fullName>
            </value>
            <value>
                <fullName>KAM</fullName>
                <isActive>false</isActive>
                <label>KAM</label>
            </value>
            <value>
                <fullName>MRO</fullName>
                <isActive>false</isActive>
                <label>MRO</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/User/fields/ETSALES_Location__c.field-meta.xml
<CustomField>
    <fullName>ETSALES_Location__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>GL Location</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/User/fields/GL_Activity_Code__c.field-meta.xml
<CustomField>
    <fullName>GL_Activity_Code__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>GL Activity Code</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/User/fields/GL_Department_Code__c.field-meta.xml
<CustomField>
    <fullName>GL_Department_Code__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>GL Department Code</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/User/fields/GL_Location_Code__c.field-meta.xml
<CustomField>
    <fullName>GL_Location_Code__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>GL Location Code</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/User/fields/GL_Project_Code__c.field-meta.xml
<CustomField>
    <fullName>GL_Project_Code__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>GL Project Code</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/User_GL_Mapping__c/User_GL_Mapping__c.object-meta.xml
<CustomObject>
    <description>to store the GL mapping and use it where ever rrequired</description>
    <label>User GL Mapping</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>User Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>User GL Mappings</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/User_GL_Mapping__c/fields/ETSALES_GL_Location__c.field-meta.xml
<CustomField>
    <fullName>ETSALES_GL_Location__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>GL Location</label>
    <referenceTo>ETSALES_Location__c</referenceTo>
    <relationshipLabel>User GL Mappings</relationshipLabel>
    <relationshipName>User_GL_Mappings</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/User_GL_Mapping__c/fields/GL_Activity__c.field-meta.xml
<CustomField>
    <fullName>GL_Activity__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>GL Activity</label>
    <referenceTo>GL_Activity__c</referenceTo>
    <relationshipLabel>User GL Mappings</relationshipLabel>
    <relationshipName>User_GL_Mappings</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/User_GL_Mapping__c/fields/GL_Department__c.field-meta.xml
<CustomField>
    <fullName>GL_Department__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>GL Department</label>
    <referenceTo>ETSALES_Department__c</referenceTo>
    <relationshipLabel>User GL Mappings</relationshipLabel>
    <relationshipName>User_GL_Mappings</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/User_GL_Mapping__c/fields/GL_Project__c.field-meta.xml
<CustomField>
    <fullName>GL_Project__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>GL Project</label>
    <referenceTo>GL_Project__c</referenceTo>
    <relationshipLabel>User GL Mappings</relationshipLabel>
    <relationshipName>User_GL_Mappings</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/User_GL_Mapping__c/fields/User__c.field-meta.xml
<CustomField>
    <fullName>User__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>User</label>
    <referenceTo>User</referenceTo>
    <relationshipName>User_GL_Mappings</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Vehicle_Model_Master__c/Vehicle_Model_Master__c.object-meta.xml
<CustomObject>
    <label>Vehicle Model</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Model Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Vehicle Model</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Vehicle_Model_Master__c/fields/Vehicle_Brand__c.field-meta.xml
<CustomField>
    <fullName>Vehicle_Brand__c</fullName>
    <label>Vehicle Brand</label>
    <referenceTo>Vehicle_Brand_Master__c</referenceTo>
    <relationshipLabel>Vehicle Model</relationshipLabel>
    <relationshipName>Vehicle_Model</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

unpackaged/main/default/globalValueSets/Emirates_Moto_Service.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Service center</fullName>
    </customValue>
    <customValue>
        <fullName>Showroom service</fullName>
    </customValue>
    <customValue>
        <fullName>Body shop service</fullName>
    </customValue>
    <customValue>
        <fullName>Car Care</fullName>
    </customValue>
    <customValue>
        <fullName>Contract</fullName>
    </customValue>
    <customValue>
        <fullName>Electrical</fullName>
    </customValue>
    <customValue>
        <fullName>Mechanical</fullName>
    </customValue>
    <customValue>
        <fullName>Quick Service</fullName>
    </customValue>
    <masterLabel>Emirates Moto Service</masterLabel>
</GlobalValueSet>

unpackaged/main/default/globalValueSets/ETSales_No_of_Years.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>1</fullName>
    </customValue>
    <customValue>
        <fullName>2</fullName>
    </customValue>
    <customValue>
        <fullName>3</fullName>
    </customValue>
    <customValue>
        <fullName>4</fullName>
    </customValue>
    <customValue>
        <fullName>5</fullName>
    </customValue>
    <customValue>
        <fullName>6</fullName>
    </customValue>
    <customValue>
        <fullName>7</fullName>
    </customValue>
    <customValue>
        <fullName>8</fullName>
    </customValue>
    <customValue>
        <fullName>9</fullName>
    </customValue>
    <customValue>
        <fullName>10</fullName>
    </customValue>
    <masterLabel>No of Years</masterLabel>
</GlobalValueSet>

unpackaged/main/default/globalValueSets/Location.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Abu Dhabi</fullName>
    </customValue>
    <customValue>
        <fullName>Ajman</fullName>
    </customValue>
    <customValue>
        <fullName>Dubai</fullName>
    </customValue>
    <customValue>
        <fullName>Fujairah</fullName>
    </customValue>
    <customValue>
        <fullName>Ras Al Khaimah</fullName>
    </customValue>
    <customValue>
        <fullName>Sharjah</fullName>
    </customValue>
    <customValue>
        <fullName>Umm Al Quwain</fullName>
    </customValue>
    <customValue>
        <fullName>Emirates Moto Al Quoz</fullName>
    </customValue>
    <customValue>
        <fullName>Emirates Moto Profix – Sharjah</fullName>
    </customValue>
    <customValue>
        <fullName>Emirates Moto Profix – Al Quoz</fullName>
    </customValue>
    <customValue>
        <fullName>Emirates Moto Profix – RAK</fullName>
    </customValue>
    <customValue>
        <fullName>الشارقة</fullName>
        <isActive>false</isActive>
        <label>الشارقة</label>
    </customValue>
    <customValue>
        <fullName>Preferred Location</fullName>
        <isActive>false</isActive>
        <label>Preferred Location</label>
    </customValue>
    <customValue>
        <fullName>أم القيوين</fullName>
        <isActive>false</isActive>
        <label>أم القيوين</label>
    </customValue>
    <masterLabel>Location</masterLabel>
</GlobalValueSet>

unpackaged/main/default/globalValueSets/Vehicle_Brand_Master.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Alfa Romeo</fullName>
    </customValue>
    <customValue>
        <fullName>Aston Martin</fullName>
    </customValue>
    <customValue>
        <fullName>Audi</fullName>
    </customValue>
    <customValue>
        <fullName>Bentley</fullName>
    </customValue>
    <customValue>
        <fullName>BMW</fullName>
    </customValue>
    <customValue>
        <fullName>Cadillac</fullName>
    </customValue>
    <customValue>
        <fullName>Chevrolet</fullName>
    </customValue>
    <customValue>
        <fullName>Chrysler</fullName>
    </customValue>
    <customValue>
        <fullName>Citreon</fullName>
    </customValue>
    <customValue>
        <fullName>Dodge</fullName>
    </customValue>
    <customValue>
        <fullName>Ferrari</fullName>
    </customValue>
    <customValue>
        <fullName>Fiat</fullName>
    </customValue>
    <customValue>
        <fullName>Ford</fullName>
    </customValue>
    <customValue>
        <fullName>Genesis</fullName>
    </customValue>
    <customValue>
        <fullName>GMC</fullName>
    </customValue>
    <customValue>
        <fullName>Honda</fullName>
    </customValue>
    <customValue>
        <fullName>Hyundai</fullName>
    </customValue>
    <customValue>
        <fullName>Infiniti</fullName>
    </customValue>
    <customValue>
        <fullName>Jaguar</fullName>
    </customValue>
    <customValue>
        <fullName>Jeep</fullName>
    </customValue>
    <customValue>
        <fullName>Kia</fullName>
    </customValue>
    <customValue>
        <fullName>Lamborghini</fullName>
    </customValue>
    <customValue>
        <fullName>Land Rover</fullName>
    </customValue>
    <customValue>
        <fullName>Lexus</fullName>
    </customValue>
    <customValue>
        <fullName>Lincoln</fullName>
    </customValue>
    <customValue>
        <fullName>Lotus</fullName>
    </customValue>
    <customValue>
        <fullName>Maserati</fullName>
    </customValue>
    <customValue>
        <fullName>Maybach</fullName>
    </customValue>
    <customValue>
        <fullName>McLaren</fullName>
    </customValue>
    <customValue>
        <fullName>Mercedes</fullName>
    </customValue>
    <description>Please add vehicle Brand object if any new vehicles brand</description>
    <masterLabel>Vehicle Brand Master</masterLabel>
</GlobalValueSet>

unpackaged/main/default/globalValueSets/Vehicle_Model_Master.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>86</fullName>
    </customValue>
    <customValue>
        <fullName>Avalon</fullName>
    </customValue>
    <customValue>
        <fullName>Avanza</fullName>
    </customValue>
    <customValue>
        <fullName>Camry</fullName>
    </customValue>
    <customValue>
        <fullName>Corolla</fullName>
    </customValue>
    <customValue>
        <fullName>FJ Cruiser</fullName>
    </customValue>
    <customValue>
        <fullName>Fortuner</fullName>
    </customValue>
    <customValue>
        <fullName>Hiace</fullName>
    </customValue>
    <customValue>
        <fullName>Highlander</fullName>
    </customValue>
    <customValue>
        <fullName>Hilux</fullName>
    </customValue>
    <customValue>
        <fullName>Innova</fullName>
    </customValue>
    <customValue>
        <fullName>Land Cruiser</fullName>
    </customValue>
    <customValue>
        <fullName>Land Cruiser 76 series</fullName>
    </customValue>
    <customValue>
        <fullName>Prado</fullName>
    </customValue>
    <customValue>
        <fullName>Rav 4</fullName>
    </customValue>
    <customValue>
        <fullName>Sienna</fullName>
    </customValue>
    <customValue>
        <fullName>Tundra</fullName>
    </customValue>
    <customValue>
        <fullName>Yaris</fullName>
    </customValue>
    <customValue>
        <fullName>Other</fullName>
    </customValue>
    <customValue>
        <fullName>Beetle</fullName>
    </customValue>
    <customValue>
        <fullName>Passat</fullName>
    </customValue>
    <customValue>
        <fullName>Scirocco</fullName>
    </customValue>
    <customValue>
        <fullName>Teramont</fullName>
    </customValue>
    <customValue>
        <fullName>Tiguan</fullName>
    </customValue>
    <customValue>
        <fullName>Touareg</fullName>
    </customValue>
    <customValue>
        <fullName>Transporter</fullName>
    </customValue>
    <customValue>
        <fullName>C-Class</fullName>
    </customValue>
    <customValue>
        <fullName>S-Class</fullName>
    </customValue>
    <customValue>
        <fullName>V-Class</fullName>
    </customValue>
    <customValue>
        <fullName>XC60</fullName>
    </customValue>
    <customValue>
        <fullName>A1</fullName>
    </customValue>
    <masterLabel>Vehicle Model Master</masterLabel>
</GlobalValueSet>

unpackaged/main/default/classes/ETSALES_LeadTriggerHandler_Test.cls
@isTest
public class ETSALES_LeadTriggerHandler_Test {
    
    public class MockHttpResponse implements HttpCalloutMock {
        public HTTPResponse respond(HTTPRequest req) {
            HTTPResponse res = new HTTPResponse();
            res.setStatusCode(200);
            res.setBody('mock response');
            return res;
        }
    }
    
    public  static testMethod void setupdata(){
        System.Test.startTest();
        Profile userProfile = [SELECT Id FROM Profile WHERE Name='System Administrator'];
        
        GL_Activity__c  test_Activity = new GL_Activity__c(Name= 'test_Activity', GL_Activity_Code__c = '0001');
        GL_Project__c   test_Project = new GL_Project__c (Name = 'test_Project', Project_Code__c = '0002');
        ETSALES_Department__c   test_Dept = new ETSALES_Department__c (Name = 'test_Dept' , Department_Code__c = '0003');
        ETSALES_Location__c test_location  = new ETSALES_Location__c(Name = 'test_Location',Location_Code__c='0004');
        
        insert test_Activity;
        insert test_Project;
        insert test_Dept;
        insert test_location;
        
        User testUser  = new User(FirstName = 'fName', LastName = 'lName',email = 'test@123.com',GL_Activity_Code__c=test_Activity.GL_Activity_Code__c,
                                  GL_Project_Code__c=test_Project.Project_Code__c,GL_Location_Code__c=test_location.Location_Code__c,
                                  GL_Department_Code__c=test_Dept.Department_Code__c,ProfileId =userProfile.Id,ETSALES_Employee_Zone__c = 'Zone A',
                                  ETSALES_Location__c='Dubai',Username = 'fnamew46642895@test.com',Alias = 'fname',TimeZoneSidKey='GMT',LocaleSidKey='en_IE_EURO',
                                  EmailEncodingKey ='ISO-8859-1',LanguageLocaleKey ='en_US');
        insert testUser;
        
        Vehicle_Brand_Master__c vbm = new Vehicle_Brand_Master__c();
        vbm.Name = 'Audi';
        insert vbm;
        
        Vehicle_Model_Master__c vmm = new Vehicle_Model_Master__c();
        vmm.Name ='A1';
        vmm.Vehicle_Brand__c = vbm.Id;
        insert vmm;
        
        Campaign cam = new Campaign();
        cam.Name ='test Campaign';
        cam.Campaign_Code__c  ='1234';
        cam.IsActive = true;
        insert cam;
        
        Lead testLead = new Lead();
        testLead.LastName = 'LastName';
        testLead.Company = 'testCompany';
        testLead.Phone = '12345678';
        testLead.MobilePhone = '987654321';
        testLead.Email = 'testEmail@123.com';
        testLead.ETSALES_Budget__c   = 123456798;
        testLead.ETSALES_Lead_Rating__c  = 'Hot';
        testLead.Service_Required__c = 'Service center';
        testLead.OwnerId=testUser.Id;
        testLead.Request_Category__c='Maintenance and Technical services';
        testLead.Preferred_Location__c = 'Dubai';
        testLead.Vehicle_Brand_Pick__c = 'Audi'; //For Moto
        testLead.Vehicle_Model_Pick__c='A1'; //for Moto
        testLead.Emirates_Moto_Campaign__c ='test Campaign';//for Moto
        testLead.Contract_Years__c='2';
        //testLead.No_of_Used_Vehicles__c=20;
        insert testlead;
        
        User testUser1  = new User(FirstName = 'fName1', LastName = 'lName1',email = 'test1@123.com',GL_Activity_Code__c=test_Activity.GL_Activity_Code__c,
                                   GL_Project_Code__c=test_Project.Project_Code__c,GL_Location_Code__c=test_location.Location_Code__c,
                                   GL_Department_Code__c=test_Dept.Department_Code__c,ProfileId =userProfile.Id,ETSALES_Employee_Zone__c = 'Zone A',
                                   ETSALES_Location__c='Dubai',Username = 'fname1@test.com',Alias = 'fname1',TimeZoneSidKey='GMT',LocaleSidKey='en_IE_EURO',
                                   EmailEncodingKey ='ISO-8859-1',LanguageLocaleKey ='en_US');   
        insert testUser1;
        
        User_GL_Mapping__c mappingRecList = new User_GL_Mapping__c (Name = 'Test Mapping',User__c = testUser1.Id,GL_Activity__c =test_Activity.Id ,
                                                                    GL_Department__c =test_Dept.Id ,ETSALES_GL_Location__c = test_location.Id,
                                                                    GL_Project__c= test_Project.Id,Sector__c='School');
        insert mappingRecList;
        Lead leadTest = [SELECT Id,OwnerId FROM Lead where Id =:testlead.Id];
        
        leadtest.OwnerId = testUser1.Id;
        update leadTest;
        List<Id> webList = new List<Id>();
        webList.add(leadTest.Id);
        //ETSALES_LeadTriggerHandler.webtoLeadUpdationFinal(webList);
        
        Test.setMock(HttpCalloutMock.class, new MockHttpResponse());
        ETSALES_LeadTriggerHandler.webtoLeadUpdationFinal(webList);

        
        System.Test.stopTest();
    }
    
}