unpackaged/main/default/objects/Report_Exporter__c/Report_Exporter__c.object-meta.xml
<CustomObject>
    <label>Report Exporter</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Report Exporter Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Report Exporters</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Report_Exporter__c/fields/Attachment_Name__c.field-meta.xml
<CustomField>
    <fullName>Attachment_Name__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Attachment Name</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Report_Exporter__c/fields/Email_Body__c.field-meta.xml
<CustomField>
    <fullName>Email_Body__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Email Body</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

unpackaged/main/default/objects/Report_Exporter__c/fields/Email_Subject__c.field-meta.xml
<CustomField>
    <fullName>Email_Subject__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Email Subject</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Report_Exporter__c/fields/Frequency__c.field-meta.xml
<CustomField>
    <fullName>Frequency__c</fullName>
    <label>Frequency</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Weekly</fullName>
            </value>
            <value>
                <fullName>Monthly</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Report_Exporter__c/fields/Monthly_Days__c.field-meta.xml
<CustomField>
    <fullName>Monthly_Days__c</fullName>
    <label>Monthly Days</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>1</fullName>
            </value>
            <value>
                <fullName>2</fullName>
            </value>
            <value>
                <fullName>3</fullName>
            </value>
            <value>
                <fullName>4</fullName>
            </value>
            <value>
                <fullName>5</fullName>
            </value>
            <value>
                <fullName>6</fullName>
            </value>
            <value>
                <fullName>7</fullName>
            </value>
            <value>
                <fullName>8</fullName>
            </value>
            <value>
                <fullName>9</fullName>
            </value>
            <value>
                <fullName>10</fullName>
            </value>
            <value>
                <fullName>11</fullName>
            </value>
            <value>
                <fullName>12</fullName>
            </value>
            <value>
                <fullName>13</fullName>
            </value>
            <value>
                <fullName>14</fullName>
            </value>
            <value>
                <fullName>15</fullName>
            </value>
            <value>
                <fullName>16</fullName>
            </value>
            <value>
                <fullName>17</fullName>
            </value>
            <value>
                <fullName>18</fullName>
            </value>
            <value>
                <fullName>19</fullName>
            </value>
            <value>
                <fullName>20</fullName>
            </value>
            <value>
                <fullName>21</fullName>
            </value>
            <value>
                <fullName>22</fullName>
            </value>
            <value>
                <fullName>23</fullName>
            </value>
            <value>
                <fullName>24</fullName>
            </value>
            <value>
                <fullName>25</fullName>
            </value>
            <value>
                <fullName>26</fullName>
            </value>
            <value>
                <fullName>27</fullName>
            </value>
            <value>
                <fullName>28</fullName>
            </value>
            <value>
                <fullName>29</fullName>
            </value>
            <value>
                <fullName>30</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Report_Exporter__c/fields/Report_ID__c.field-meta.xml
<CustomField>
    <fullName>Report_ID__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Report ID</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Report_Exporter__c/fields/Weekly_Days__c.field-meta.xml
<CustomField>
    <fullName>Weekly_Days__c</fullName>
    <label>Weekly Days</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Sunday</fullName>
            </value>
            <value>
                <fullName>Monday</fullName>
            </value>
            <value>
                <fullName>Tuesday</fullName>
            </value>
            <value>
                <fullName>Wednesday</fullName>
            </value>
            <value>
                <fullName>Thursday</fullName>
            </value>
            <value>
                <fullName>Friday</fullName>
            </value>
            <value>
                <fullName>Saturday</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/classes/ReportExporter.cls
/* 
** Author: Gonsalvas
** Created date: 22-08-2022
** Description: To schedule and send reports to users who doesn't have any salesforce user account
** Janardhan - 13-02-2023 - Added Org wide email address with custom label
*/
global class ReportExporter implements System.Schedulable{
global void execute(SchedulableContext sc) {
    ReportExporter.rptscheduler();
    }
    
@future(callout=true) 
public static void rptscheduler()
{  
   Map <ID,Blob> attachbody=new Map <ID,Blob>();
   List<Report_Exporter__c> exportList = new List<Report_Exporter__c>{};
 exportList = [Select Id, Name, Report_ID__c, Attachment_Name__c,Email_Body__c, Email_Subject__c, Email_Recipients__c, Frequency__c, Weekly_Days__c, Monthly_Days__c from Report_Exporter__c ];
  
    ReportExporter.sendAndAttachcsv(exportList);
 }
 
 public static void sendAndAttachcsv(List<Report_Exporter__c> exportList){
   Datetime dt = DateTime.newInstance(Date.today(), Time.newInstance(0, 0, 0, 0));
   Date d = Date.today();
   Date firstDate = d.toStartOfMonth();
   Date lastDay = firstDate.addDays(Date.daysInMonth(d.year(), d.month())-1);
   List<Messaging.SingleEmailMessage> mails = new List<Messaging.SingleEmailMessage>(); 
   OrgWideEmailAddress[] owea = [SELECT Id,Address FROM OrgWideEmailAddress WHERE DisplayName =:System.Label.CICO_OrgWideEmail];

   for(Report_Exporter__c e : exportList)
    {   
         
        Messaging.EmailFileAttachment attachment = new Messaging.EmailFileAttachment();
        ApexPages.PageReference report = new ApexPages.PageReference('/servlet/PrintableViewDownloadServlet?isdtp=p1&reportId=' + e.Report_ID__c);
        blob content;
        if(Test.isRunningTest()) { 
         content = blob.valueOf('Unit.Test');
        } else {
         content = report.getContent();
        }

        // Blob content = Test.isRunningTest() ? Blob.valueOf('UNIT.TEST') : report.getContent();
        Boolean process = Test.isRunningTest() ? true : false;
       

        process = e.Frequency__c == 'Weekly' && e.Weekly_Days__c.contains(dt.format('EEEE')) ? true : process;
        system.debug('Calling_Systemweekly'+process);
        process = e.Frequency__c == 'Monthly' && (e.Monthly_Days__c == String.valueOf(d.day()) || e.Monthly_Days__c == 'last' && d == lastDay || lastDay.day() <= Integer.valueOf(e.Monthly_Days__c)) ? true : process;
        system.debug('Calling_System1'+process);
       if(process)
       {
          System.debug('Starting message processing for: ' + e.Name);
          attachment.setFileName(e.Attachment_Name__c);
          attachment.setBody(content);
          //attachment.setContentType('text/csv');
           attachment.setContentType('application/vnd.oasis.opendocument.spreadsheet');
          Messaging.SingleEmailMessage message = new Messaging.SingleEmailMessage();
          message.setFileAttachments(new Messaging.EmailFileAttachment[] {attachment});
           if ( owea != null && owea.size() > 0 ) {
               message.setOrgWideEmailAddressId(owea.get(0).Id);
           }
           
          message.setSubject(e.Email_Subject__c);
          message.setPlainTextBody(e.Email_Body__c);
          String[] emailRecipients = e.Email_Recipients__c.split(',');
          message.setToAddresses(emailRecipients);
         // Messaging.sendEmail(new Messaging.SingleEmailMessage[] {message});
          System.debug('Completed message processing for: ' + e.Name);
          mails.add(message);
        }
     }
     Messaging.sendEmail(mails);
 }

}