unpackaged/main/default/objects/ETT_Fleet_Inspection__c/ETT_Fleet_Inspection__c.object-meta.xml
<CustomObject>
    <label>Fleet Inspection</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Fleet Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Fleet Inspection</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/ETT_Fleet_Inspection__c/fields/ETT_Pattern_Master__c.field-meta.xml
<CustomField>
    <fullName>ETT_Pattern_Master__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Pattern</label>
    <referenceTo>ETT_Pattern_Master__c</referenceTo>
    <relationshipLabel>Fleet Inspection</relationshipLabel>
    <relationshipName>Fleet_Inspection</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/ETT_Fleet_Inspection__c/fields/Lead__c.field-meta.xml
<CustomField>
    <fullName>Lead__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Lead</label>
    <referenceTo>Lead</referenceTo>
    <relationshipLabel>Fleet Inspection</relationshipLabel>
    <relationshipName>Fleet_Inspection</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/ETT_Staging_Added_Service__c/ETT_Staging_Added_Service__c.object-meta.xml
<CustomObject>
    <label>Staging Added Service</label>
    <nameField>
        <displayFormat>ASN-{0000}</displayFormat>
        <label>Staging Added Service Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Staging Added Services</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/ETT_Staging_Added_Service__c/fields/ETT_Lead__c.field-meta.xml
<CustomField>
    <fullName>ETT_Lead__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Lead</label>
    <referenceTo>Lead</referenceTo>
    <relationshipLabel>Staging Added Services</relationshipLabel>
    <relationshipName>Staging_Added_Services</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/ETT_Staging_Bank_Reference__c/ETT_Staging_Bank_Reference__c.object-meta.xml
<CustomObject>
    <label>Staging Bank Reference</label>
    <nameField>
        <displayFormat>SBRN-{0000}</displayFormat>
        <label>Staging Bank Reference Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Staging Bank Reference</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/ETT_Staging_Bank_Reference__c/fields/ETT_Lead__c.field-meta.xml
<CustomField>
    <fullName>ETT_Lead__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Lead</label>
    <referenceTo>Lead</referenceTo>
    <relationshipLabel>Staging Bank Reference</relationshipLabel>
    <relationshipName>Staging_Bank_Reference</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/ETT_Staging_Contacts__c/ETT_Staging_Contacts__c.object-meta.xml
<CustomObject>
    <label>Staging Contacts</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Last Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Staging Contacts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/ETT_Staging_Contacts__c/fields/ETT_Lead__c.field-meta.xml
<CustomField>
    <fullName>ETT_Lead__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Lead</label>
    <referenceTo>Lead</referenceTo>
    <relationshipLabel>Staging Contacts</relationshipLabel>
    <relationshipName>Staging_Contacts</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/ETT_Staging_Customer_LPO__c/ETT_Staging_Customer_LPO__c.object-meta.xml
<CustomObject>
    <label>Staging Customer LPO</label>
    <nameField>
        <displayFormat>SCLPO-{0000}</displayFormat>
        <label>Staging Customer LPO Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Staging Customer LPO</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/ETT_Staging_Customer_LPO__c/fields/ETT_Lead__c.field-meta.xml
<CustomField>
    <fullName>ETT_Lead__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Lead</label>
    <referenceTo>Lead</referenceTo>
    <relationshipLabel>Staging Customer LPO</relationshipLabel>
    <relationshipName>Staging_Customer_LPO</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/ETT_Staging_Customer_Vehicle_Details__c/ETT_Staging_Customer_Vehicle_Details__c.object-meta.xml
<CustomObject>
    <label>Staging Customer Vehicle Details</label>
    <nameField>
        <displayFormat>SCVD-{0000}</displayFormat>
        <label>Staging Customer Vehicle Details Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Staging Customer Vehicle Details</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/ETT_Staging_Customer_Vehicle_Details__c/fields/ETT_Lead__c.field-meta.xml
<CustomField>
    <fullName>ETT_Lead__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Lead</label>
    <referenceTo>Lead</referenceTo>
    <relationshipLabel>Staging Customer Vehicle Details</relationshipLabel>
    <relationshipName>Staging_Customer_Vehicle_Details</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/ETT_Staging_Fleet_Inspection__c/ETT_Staging_Fleet_Inspection__c.object-meta.xml
<CustomObject>
    <label>Staging Fleet Inspection</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Fleet Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Staging Fleet Inspection</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/ETT_Staging_Fleet_Inspection__c/fields/ETT_Lead__c.field-meta.xml
<CustomField>
    <fullName>ETT_Lead__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Lead</label>
    <referenceTo>Lead</referenceTo>
    <relationshipLabel>Staging Fleet Inspection</relationshipLabel>
    <relationshipName>Staging_Fleet_Inspection</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/ETT_Staging_Fleet_Inspection__c/fields/ETT_Pattern_Master__c.field-meta.xml
<CustomField>
    <fullName>ETT_Pattern_Master__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Pattern Master</label>
    <referenceTo>ETT_Pattern_Master__c</referenceTo>
    <relationshipLabel>Staging Fleet Inspection (Pattern Master)</relationshipLabel>
    <relationshipName>Staging_Fleet_Inspection1</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/ETT_Staging_Purchase_Information__c/ETT_Staging_Purchase_Information__c.object-meta.xml
<CustomObject>
    <label>Staging Purchase Information</label>
    <nameField>
        <displayFormat>StagingPurchaseInfo-{000000}</displayFormat>
        <label>Staging Purchase Information Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Staging Purchase Informations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/ETT_Staging_Purchase_Information__c/fields/ETT_Brand_Master__c.field-meta.xml
<CustomField>
    <fullName>ETT_Brand_Master__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Brand</label>
    <lookupFilter>
        <active>true</active>
        <errorMessage>We need to Take Active  Brands only.</errorMessage>
        <filterItems>
            <field>ETT_Brand_Master__c.ETT_Status__c</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>ETT_Brand_Master__c</referenceTo>
    <relationshipLabel>Staging Purchase Informations</relationshipLabel>
    <relationshipName>Staging_Purchase_Informations</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/ETT_Staging_Purchase_Information__c/fields/ETT_Lead__c.field-meta.xml
<CustomField>
    <fullName>ETT_Lead__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Lead</label>
    <referenceTo>Lead</referenceTo>
    <relationshipLabel>Staging Purchase Informations</relationshipLabel>
    <relationshipName>Staging_Purchase_Informations</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/ETT_Staging_Purchase_Information__c/fields/ETT_Tyre_Size_Master__c.field-meta.xml
<CustomField>
    <fullName>ETT_Tyre_Size_Master__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Tyre Size</label>
    <referenceTo>ETT_Tyre_Size_Master__c</referenceTo>
    <relationshipLabel>Staging Purchase Informations</relationshipLabel>
    <relationshipName>Staging_Purchase_Informations</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/ETT_Staging_Quotation_Request__c/ETT_Staging_Quotation_Request__c.object-meta.xml
<CustomObject>
    <label>Staging Quotation Request</label>
    <nameField>
        <displayFormat>SQRN-{0000}</displayFormat>
        <label>Staging Quotation Request Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Staging Quotation Request</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/ETT_Staging_Quotation_Request__c/fields/ETT_Lead__c.field-meta.xml
<CustomField>
    <fullName>ETT_Lead__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Lead</label>
    <referenceTo>Lead</referenceTo>
    <relationshipLabel>Staging Quotation Request</relationshipLabel>
    <relationshipName>Staging_Quotation_Request</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/ETT_Staging_Scrap_Inspection__c/ETT_Staging_Scrap_Inspection__c.object-meta.xml
<CustomObject>
    <label>Staging Scrap Inspection</label>
    <nameField>
        <displayFormat>SN-{0000}</displayFormat>
        <label>Staging  Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Staging Scrap Inspections</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/ETT_Staging_Scrap_Inspection__c/fields/ETT_Lead__c.field-meta.xml
<CustomField>
    <fullName>ETT_Lead__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Lead</label>
    <referenceTo>Lead</referenceTo>
    <relationshipLabel>Staging Scrap Inspections</relationshipLabel>
    <relationshipName>Staging_Scrap_Inspections</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/ETT_Staging_Test_Tyre__c/ETT_Staging_Test_Tyre__c.object-meta.xml
<CustomObject>
    <label>Staging Test Tyre</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Customer Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Staging Test Tyres</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/ETT_Staging_Test_Tyre__c/fields/ETT_Lead__c.field-meta.xml
<CustomField>
    <fullName>ETT_Lead__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Lead</label>
    <referenceTo>Lead</referenceTo>
    <relationshipLabel>Staging Test Tyres</relationshipLabel>
    <relationshipName>Staging_Test_Tyres</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/ETT_Staging_Trade_Reference__c/ETT_Staging_Trade_Reference__c.object-meta.xml
<CustomObject>
    <label>Staging Trade Reference</label>
    <nameField>
        <displayFormat>STRN-{0000}</displayFormat>
        <label>Staging Trade Reference Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Staging Trade Reference</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/ETT_Staging_Trade_Reference__c/fields/ETT_Lead__c.field-meta.xml
<CustomField>
    <fullName>ETT_Lead__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Lead</label>
    <referenceTo>Lead</referenceTo>
    <relationshipLabel>Staging Trade Reference</relationshipLabel>
    <relationshipName>Staging_Trade_Reference</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Lead/fields/ETSALES_Lead_Rating__c.field-meta.xml
<CustomField>
    <fullName>ETSALES_Lead_Rating__c</fullName>
    <label>Prospect Rating</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Hot</fullName>
            </value>
            <value>
                <fullName>Warm</fullName>
            </value>
            <value>
                <fullName>Cold</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/classes/ETT_LeadFormController_Test.cls
@isTest
public class ETT_LeadFormController_Test {
    
    @isTest static void testMethod1(){
                Map<String,String> mapList = new  Map<String,String>();

        List<Lead> leadList =  ETT_TestFactory.createLeads();
        insert leadList;
        ETT_LeadFormController.getPickListValuesIntoList();
        ETT_LeadFormController.getLeadRecordTypeID('ET Tyre');
        ETT_LeadFormController.getDynamicPickListValuesIntoList('Lead','ETSALES_Lead_Rating__c');
        ETT_LeadFormController.getCustomerProfile(leadList[0].Id);
        List<String> moreFields = new List<String>{'LastName'};
         ETT_LeadFormController.searchRecord('Lead','ETSALES_Lead_Rating__c',moreFields,'Hot',2);
        
         List<ETT_Brand_Master__c> brandMastersList = ETT_TestFactory.createBrandMasters();
        List<ETT_Pattern_Master__c> patternMastersList = ETT_TestFactory.createPatternMasters();
        List<ETT_Staging_Contacts__c> stagingContactsList = ETT_TestFactory.createStagingContacts(leadList[0].Id);
        stagingContactsList[0].ETT_Lead__c = null;
        List<ETT_Staging_Customer_Vehicle_Details__c> createStagingCustVehicles = ETT_TestFactory.createStagingCustVehicles(leadList[0].Id);
        createStagingCustVehicles[0].ETT_Lead__c = null;
        List<ETT_Tyre_Size_Master__c> tyreMasterSizeList =  ETT_TestFactory.createTyreSizeMaster();
        insert tyreMasterSizeList;
        List<ETT_Staging_Quotation_Request__c> stagingQuoteList = ETT_TestFactory.createStagingQuoteRequests(leadList[0].Id);
        stagingQuoteList[0].ETT_Tyre_Size_Master__c = tyreMasterSizeList[0].Id;
        stagingQuoteList[0].ETT_Lead__c = null;
        List<ETT_Staging_Purchase_Information__c> stagingPurchaseList = ETT_TestFactory.createStagingPurchaseInformations(tyreMasterSizeList[0].Id,leadList[0].Id);
        List<ETT_Staging_Added_Service__c> stagingAddedList = ETT_TestFactory.createStagingAddedServices(leadList[0].Id);
        stagingAddedList[0].ETT_Lead__c = null;
        List<ETT_Staging_Customer_LPO__c> stagingCustomerLPOList = ETT_TestFactory.createStagingCustomerLPO(leadList[0].Id);
        List<ETT_Staging_Trade_Reference__c> stagingTradeReferencesList = ETT_TestFactory.createStagingTradeReferences(leadList[0].Id);
        stagingTradeReferencesList[0].ETT_Lead__c = null;
        List<ETT_Staging_Bank_Reference__c> stagingBankReferencesList = ETT_TestFactory.createStagingBankReferences(leadList[0].Id);
        stagingBankReferencesList[0].ETT_Lead__c = null;
        insert stagingContactsList;
        insert createStagingCustVehicles;
        insert stagingQuoteList;
        insert stagingPurchaseList;
        insert stagingAddedList;
        insert stagingCustomerLPOList;
        insert stagingTradeReferencesList;
        insert stagingBankReferencesList;
        
        ETT_Staging_Quotation_Request__c onn = new ETT_Staging_Quotation_Request__c();
        onn.ETT_New_Brand__c='testa';
        onn.ETT_New_Country__c='testb';
        onn.ETT_New_Pattern__c='testc';
        onn.ETT_New_Tyre_Size__c='testr';
        insert onn;
                
        Test.startTest();
        mapList.put('stgLeadJson',JSON.serialize(leadList[0]));
        mapList.put('stgContactJson',JSON.serialize(stagingContactsList));
        mapList.put('stgVehicleJson',JSON.serialize(createStagingCustVehicles));
        mapList.put('stgQuoteJson',JSON.serialize(stagingQuoteList));
        mapList.put('stgPurchaseJson',JSON.serialize(stagingPurchaseList));
        mapList.put('stgAddedServiceJson',JSON.serialize(stagingAddedList));
        mapList.put('stgCustomerLPOJson',JSON.serialize(stagingCustomerLPOList));
        mapList.put('stgTradeReferenceJson',JSON.serialize(stagingTradeReferencesList));
        mapList.put('stgBankReferenceJson',JSON.serialize(stagingBankReferencesList));
        
        
        List<Sobject> lstSobjectInfo = new List<Sobject>{stagingQuoteList[0]};
        ETT_LeadFormController.saveDML(mapList);
        Test.stopTest();
        
    }
    
    
    @isTest static void testSaveDML(){
        
        Group grp = new Group(Name = 'Inspection Card');
        insert grp;
        
        Id leadRecordTypeId = Schema.SObjectType.Lead.getRecordTypeInfosByName().get('Tyre - Cash Supplier').getRecordTypeId();
        Map<String,String> mapList = new  Map<String,String>();
        List<Lead> leadList =  ETT_TestFactory.createLeads();
        leadList[0].RecordTypeId = leadRecordTypeId;
        leadList[0].MobilePhone = '+971 254563645';
   
        
        insert leadList;
        List<ETT_Brand_Master__c> brandMastersList = ETT_TestFactory.createBrandMasters();
        List<ETT_Pattern_Master__c> patternMastersList = ETT_TestFactory.createPatternMasters();
        List<ETT_Staging_Contacts__c> stagingContactsList = ETT_TestFactory.createStagingContacts(leadList[0].Id);
        stagingContactsList[0].ETT_Lead__c = null;
        List<ETT_Staging_Customer_Vehicle_Details__c> createStagingCustVehicles = ETT_TestFactory.createStagingCustVehicles(leadList[0].Id);
        createStagingCustVehicles[0].ETT_Lead__c = null;
        List<ETT_Tyre_Size_Master__c> tyreMasterSizeList =  ETT_TestFactory.createTyreSizeMaster();
        insert tyreMasterSizeList;
        List<ETT_Staging_Quotation_Request__c> stagingQuoteList = ETT_TestFactory.createStagingQuoteRequests(leadList[0].Id);
        stagingQuoteList[0].ETT_Tyre_Size_Master__c = tyreMasterSizeList[0].Id;
        stagingQuoteList[0].ETT_Lead__c = null;
                

       

        List<ETT_Staging_Purchase_Information__c> stagingPurchaseList = ETT_TestFactory.createStagingPurchaseInformations(tyreMasterSizeList[0].Id,leadList[0].Id);
        List<ETT_Staging_Added_Service__c> stagingAddedList = ETT_TestFactory.createStagingAddedServices(leadList[0].Id);
        stagingAddedList[0].ETT_Lead__c = null;
        List<ETT_Staging_Customer_LPO__c> stagingCustomerLPOList = ETT_TestFactory.createStagingCustomerLPO(leadList[0].Id);
        List<ETT_Staging_Trade_Reference__c> stagingTradeReferencesList = ETT_TestFactory.createStagingTradeReferences(leadList[0].Id);
        stagingTradeReferencesList[0].ETT_Lead__c = null;
        List<ETT_Staging_Bank_Reference__c> stagingBankReferencesList = ETT_TestFactory.createStagingBankReferences(leadList[0].Id);
        stagingBankReferencesList[0].ETT_Lead__c = null;
        
        insert patternMastersList;
        insert brandMastersList;
        insert stagingContactsList;
        insert createStagingCustVehicles;
        insert stagingQuoteList;
        insert stagingPurchaseList;
        insert stagingAddedList;
        insert stagingCustomerLPOList;
        insert stagingTradeReferencesList;
        insert stagingBankReferencesList;
        
        List<ETT_Staging_Fleet_Inspection__c> stagingFleetInspectionsList = ETT_TestFactory.createStagingFleetInspections( leadList[0].Id,brandMastersList[0].Id,patternMastersList[0].Id, tyreMasterSizeList[0].Id);
        System.debug('Test  ' + stagingFleetInspectionsList);
        insert stagingFleetInspectionsList;
        List<ETT_FleetInspectionWrapper> lll = new List<ETT_FleetInspectionWrapper>();
        ETT_FleetInspectionWrapper l = new ETT_FleetInspectionWrapper();
        l.fileSourceType = 'Email';
        l.lstFileLoadWrapper = new List<ETT_FileUploadWrapper>();
       // l.objFleetInspection = stagingFleetInspectionsList[0];
        lll.add(l);
        List<ETT_Staging_Scrap_Inspection__c> stagingScrapInspectionsList = ETT_TestFactory.createStagingScrapInspections( leadList[0].Id,brandMastersList[0].Id,tyreMasterSizeList[0].Id);
        stagingScrapInspectionsList[0].ETT_Lead__c = null;
        insert stagingScrapInspectionsList;
        List<ETT_Staging_Test_Tyre__c> stagingTestTyresList =  ETT_TestFactory.createStagingTestTyres( leadList[0].Id,brandMastersList[0].Id);
        stagingTestTyresList[0].ETT_Lead__c = null;
        insert stagingTestTyresList;
        
  List< ETT_Vehicle_Details__c> vehicleList= new List< ETT_Vehicle_Details__c>();
        ETT_Vehicle_Details__c an=new ETT_Vehicle_Details__c();
        an.Name='test';
       an.ETT_Internal_Number__c='3456';
        vehicleList.add(an);
        insert vehicleList;
     
        ETT_Fleet_Inspection__c FleetInspection = new ETT_Fleet_Inspection__c();  
        /*FleetInspection.ETT_Account__c = acc.Id;*/
        FleetInspection.Lead__c = leadList[0].Id;
        insert FleetInspection;
        
    Fleet_Inspection_Line_Item__c FleetlineItem = new Fleet_Inspection_Line_Item__c();
        FleetlineItem.Fleet_Inspection__c = FleetInspection.id;
	//	insert FleetlineItem;
        
        Test.startTest();
        mapList.put('stgLeadJson',JSON.serialize(leadList[0]));
        mapList.put('stgContactJson',JSON.serialize(stagingContactsList));
        mapList.put('stgVehicleJson',JSON.serialize(createStagingCustVehicles));
        mapList.put('stgQuoteJson',JSON.serialize(stagingQuoteList));
        mapList.put('stgPurchaseJson',JSON.serialize(stagingPurchaseList));
        mapList.put('stgAddedServiceJson',JSON.serialize(stagingAddedList));
        mapList.put('stgCustomerLPOJson',JSON.serialize(stagingCustomerLPOList));
        mapList.put('stgTradeReferenceJson',JSON.serialize(stagingTradeReferencesList));
        mapList.put('stgBankReferenceJson',JSON.serialize(stagingBankReferencesList));
        mapList.put('stgFleetInspectionJson',JSON.serialize(stagingFleetInspectionsList));
        mapList.put('stgScrabInspectionJson',JSON.serialize(stagingScrapInspectionsList));
        mapList.put('stgTestTyreJson',JSON.serialize(stagingTestTyresList));
        
      
   
    // base64 encode the blob that contains our url param value
   

        
        List<Sobject> lstSobjectInfo = new List<Sobject>{stagingQuoteList[0]};
       
       
        
         ETT_LeadFormController.saveDML(mapList);
        
    //   ETT_LeadFormController.saveDMLForFleetInspection(mapList);
  
        
        ETT_LeadFormController.getselectOptions(leadList[0],'ETSALES_Lead_Rating__c');
        ETT_LeadFormController.processCasesInformation(lstSobjectInfo, leadList[0].Id);
      
        ETT_LeadFormController.getVehicleNumber('test');
        Test.stopTest();
        
    }
    
      @isTest static void testsaveDMLForFleetInspection(){
        
        Group grp = new Group(Name = 'Inspection Card');
        insert grp;
        
        Id leadRecordTypeId = Schema.SObjectType.Lead.getRecordTypeInfosByName().get('Tyre - Cash Supplier').getRecordTypeId();
        Map<String,String> mapList = new  Map<String,String>();
        List<Lead> leadList =  ETT_TestFactory.createLeads();
        leadList[0].RecordTypeId = leadRecordTypeId;
        leadList[0].MobilePhone = '+971 254563645';
   
        
        insert leadList;
        List<ETT_Brand_Master__c> brandMastersList = ETT_TestFactory.createBrandMasters();
        List<ETT_Pattern_Master__c> patternMastersList = ETT_TestFactory.createPatternMasters();
        List<ETT_Staging_Contacts__c> stagingContactsList = ETT_TestFactory.createStagingContacts(leadList[0].Id);
        stagingContactsList[0].ETT_Lead__c = null;
        List<ETT_Staging_Customer_Vehicle_Details__c> createStagingCustVehicles = ETT_TestFactory.createStagingCustVehicles(leadList[0].Id);
        createStagingCustVehicles[0].ETT_Lead__c = null;
        List<ETT_Tyre_Size_Master__c> tyreMasterSizeList =  ETT_TestFactory.createTyreSizeMaster();
        insert tyreMasterSizeList;
        List<ETT_Staging_Quotation_Request__c> stagingQuoteList = ETT_TestFactory.createStagingQuoteRequests(leadList[0].Id);
        stagingQuoteList[0].ETT_Tyre_Size_Master__c = tyreMasterSizeList[0].Id;
        stagingQuoteList[0].ETT_Lead__c = null;
                

       

        List<ETT_Staging_Purchase_Information__c> stagingPurchaseList = ETT_TestFactory.createStagingPurchaseInformations(tyreMasterSizeList[0].Id,leadList[0].Id);
        List<ETT_Staging_Added_Service__c> stagingAddedList = ETT_TestFactory.createStagingAddedServices(leadList[0].Id);
        stagingAddedList[0].ETT_Lead__c = null;
        List<ETT_Staging_Customer_LPO__c> stagingCustomerLPOList = ETT_TestFactory.createStagingCustomerLPO(leadList[0].Id);
        List<ETT_Staging_Trade_Reference__c> stagingTradeReferencesList = ETT_TestFactory.createStagingTradeReferences(leadList[0].Id);
        stagingTradeReferencesList[0].ETT_Lead__c = null;
        List<ETT_Staging_Bank_Reference__c> stagingBankReferencesList = ETT_TestFactory.createStagingBankReferences(leadList[0].Id);
        stagingBankReferencesList[0].ETT_Lead__c = null;
        
        insert patternMastersList;
        insert brandMastersList;
        insert stagingContactsList;
        insert createStagingCustVehicles;
        insert stagingQuoteList;
        insert stagingPurchaseList;
        insert stagingAddedList;
        insert stagingCustomerLPOList;
        insert stagingTradeReferencesList;
        insert stagingBankReferencesList;
        
        List<ETT_Staging_Fleet_Inspection__c> stagingFleetInspectionsList = ETT_TestFactory.createStagingFleetInspections( leadList[0].Id,brandMastersList[0].Id,patternMastersList[0].Id, tyreMasterSizeList[0].Id);
        System.debug('Test  ' + stagingFleetInspectionsList);
        insert stagingFleetInspectionsList;
        List<ETT_FleetInspectionWrapper> lll = new List<ETT_FleetInspectionWrapper>();
        ETT_FleetInspectionWrapper l = new ETT_FleetInspectionWrapper();
        l.fileSourceType = 'Email';
        l.lstFileLoadWrapper = new List<ETT_FileUploadWrapper>();
       // l.objFleetInspection = stagingFleetInspectionsList[0];
        lll.add(l);
        List<ETT_Staging_Scrap_Inspection__c> stagingScrapInspectionsList = ETT_TestFactory.createStagingScrapInspections( leadList[0].Id,brandMastersList[0].Id,tyreMasterSizeList[0].Id);
        stagingScrapInspectionsList[0].ETT_Lead__c = null;
        insert stagingScrapInspectionsList;
        List<ETT_Staging_Test_Tyre__c> stagingTestTyresList =  ETT_TestFactory.createStagingTestTyres( leadList[0].Id,brandMastersList[0].Id);
        stagingTestTyresList[0].ETT_Lead__c = null;
        insert stagingTestTyresList;
        
  List< ETT_Vehicle_Details__c> vehicleList= new List< ETT_Vehicle_Details__c>();
        ETT_Vehicle_Details__c an=new ETT_Vehicle_Details__c();
        an.Name='test';
       an.ETT_Internal_Number__c='3456';
        vehicleList.add(an);
        insert vehicleList;
     
        ETT_Fleet_Inspection__c FleetInspection = new ETT_Fleet_Inspection__c();  
        /*FleetInspection.ETT_Account__c = acc.Id;*/
        FleetInspection.Lead__c = leadList[0].Id;
     //   insert FleetInspection;
        
    Fleet_Inspection_Line_Item__c FleetlineItem = new Fleet_Inspection_Line_Item__c();
       // FleetlineItem.Fleet_Inspection__c = FleetInspection.id;
	//	insert FleetlineItem;
        
        Test.startTest();
        mapList.put('stgLeadJson',JSON.serialize(leadList[0]));
        mapList.put('stgContactJson',JSON.serialize(stagingContactsList));
        mapList.put('stgVehicleJson',JSON.serialize(createStagingCustVehicles));
        mapList.put('stgQuoteJson',JSON.serialize(stagingQuoteList));
        mapList.put('stgPurchaseJson',JSON.serialize(stagingPurchaseList));
        mapList.put('stgAddedServiceJson',JSON.serialize(stagingAddedList));
        mapList.put('stgCustomerLPOJson',JSON.serialize(stagingCustomerLPOList));
        mapList.put('stgTradeReferenceJson',JSON.serialize(stagingTradeReferencesList));
        mapList.put('stgBankReferenceJson',JSON.serialize(stagingBankReferencesList));
        mapList.put('stgFleetInspectionJson',JSON.serialize(FleetInspection));
        mapList.put('stgScrabInspectionJson',JSON.serialize(stagingScrapInspectionsList));
        mapList.put('stgTestTyreJson',JSON.serialize(stagingTestTyresList));
        
      
   
    // base64 encode the blob that contains our url param value
   
        Blob beforeblob = Blob.valueOf('TestFilePath');
        ETT_FileUploadWrapper fileUploadWrapper = new ETT_FileUploadWrapper();
        fileUploadWrapper.fileSourceType = 'FL';
        fileUploadWrapper.strFileName= 'Test.img';
        fileUploadWrapper.strBase64Data = EncodingUtil.base64Encode(beforeblob);
        fileUploadWrapper.strFileType= 'Image/JPEG';
        ETT_FleetInspectionWrapper fleetInspectionWrapper = new ETT_FleetInspectionWrapper();
        fleetInspectionWrapper.lstFileLoadWrapper = new List<ETT_FileUploadWrapper>{fileUploadWrapper};
        fleetInspectionWrapper.fileSourceType = 'FL' ;
        fleetInspectionWrapper.objFleetInspection = FleetlineItem;
          System.debug('fleetInspectionWrapper jspn='+JSON.serialize(fleetInspectionWrapper));
      //  List<Sobject> lstSobjectInfo = new List<Sobject>{stagingQuoteList[0]};
       List<ETT_FleetInspectionWrapper> fleetInspectionWrapperlist = new  List<ETT_FleetInspectionWrapper>();
          fleetInspectionWrapperlist.add(fleetInspectionWrapper);
        mapList.put('stgFleetInspectionLineItemJson',JSON.serialize(fleetInspectionWrapperlist));
        
      //   ETT_LeadFormController.saveDML(mapList);
        
       ETT_LeadFormController.saveDMLForFleetInspection(mapList);
                    ETT_LeadFormController.getLeadInfo(leadList[0].Id);
     
        Test.stopTest();
        
    }
}