unpackaged/main/default/objects/ETT_Fleet_Inspection__c/ETT_Fleet_Inspection__c.object-meta.xml
<CustomObject>
    <label>Fleet Inspection</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Fleet Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Fleet Inspection</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/ETT_Fleet_Inspection__c/fields/ETT_Account__c.field-meta.xml
<CustomField>
    <fullName>ETT_Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Fleet Inspection</relationshipLabel>
    <relationshipName>Fleet_Inspection</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/ETT_Fleet_Inspection__c/fields/Lead__c.field-meta.xml
<CustomField>
    <fullName>Lead__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Lead</label>
    <referenceTo>Lead</referenceTo>
    <relationshipLabel>Fleet Inspection</relationshipLabel>
    <relationshipName>Fleet_Inspection</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/classes/ETT_getPickListValues_Test.cls
@isTest public class ETT_getPickListValues_Test {
    @isTest
    
    public static void codecoverage(){
           Lead lead = new Lead();
        lead.Company = 'test';
        lead.LastName = 'dubai';
        insert lead;
        
        Account acc = new Account();
        acc.Name = 'Test account';
        insert acc;
        
        Contact cont = new Contact();
       // cont.Phone = '+971 546789765';
        cont.AccountId = acc.Id;
        cont.LastName = 'devpleena';
        insert cont;
        
        ETT_Fleet_Inspection__c FleetInspection = new ETT_Fleet_Inspection__c();
        FleetInspection.ETT_Account__c = acc.Id;
        FleetInspection.Lead__c = lead.Id;
        insert FleetInspection;
        
        getPickListValues.getDetailsOnLoad();
    }

}