unpackaged/main/default/objects/ET_Work_force__c/ET_Work_force__c.object-meta.xml
<CustomObject>
    <label>Work force Request</label>
    <nameField>
        <displayFormat>W-{0000}</displayFormat>
        <label>Work force Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Work force Requests</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

unpackaged/main/default/objects/ET_Work_force__c/fields/ET_Accountant_Category__c.field-meta.xml
<CustomField>
    <fullName>ET_Accountant_Category__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Accountant/Cashier  Category</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/ET_Work_force__c/fields/ET_Contract_Type__c.field-meta.xml
<CustomField>
    <fullName>ET_Contract_Type__c</fullName>
    <label>Contract Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>New</fullName>
            </value>
            <value>
                <fullName>Renewal</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/ET_Work_force__c/fields/ET_Coordinator_Category__c.field-meta.xml
<CustomField>
    <fullName>ET_Coordinator_Category__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Coordinator Category</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/ET_Work_force__c/fields/ET_Driver_Category__c.field-meta.xml
<CustomField>
    <fullName>ET_Driver_Category__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Driver Category</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/ET_Work_force__c/fields/ET_Nanny_Category__c.field-meta.xml
<CustomField>
    <fullName>ET_Nanny_Category__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Nanny Category</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/ET_Work_force__c/fields/ET_Other_employee_Category__c.field-meta.xml
<CustomField>
    <fullName>ET_Other_employee_Category__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Other employee Category</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/ET_Work_force__c/fields/ET_Pricing_Method__c.field-meta.xml
<CustomField>
    <fullName>ET_Pricing_Method__c</fullName>
    <label>Pricing Method</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Per Unit</fullName>
            </value>
            <value>
                <fullName>Comprehensive Price per Quotation</fullName>
            </value>
            <value>
                <fullName>Comprehensive Price per Line</fullName>
            </value>
            <value>
                <fullName>Comprehensive Price per Route</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/ET_Work_force__c/fields/ET_Service_Emirate__c.field-meta.xml
<CustomField>
    <fullName>ET_Service_Emirate__c</fullName>
    <label>Service Emirate</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Abu Dhabi</fullName>
            </value>
            <value>
                <fullName>Dubai</fullName>
            </value>
            <value>
                <fullName>Sharjah</fullName>
            </value>
            <value>
                <fullName>Ajman</fullName>
            </value>
            <value>
                <fullName>UMM Al Quawain</fullName>
            </value>
            <value>
                <fullName>Ras Al Khaimah</fullName>
            </value>
            <value>
                <fullName>Fujairah</fullName>
            </value>
            <value>
                <fullName>Abu-Dhabi</fullName>
                <isActive>false</isActive>
                <label>Abu-Dhabi</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/ET_Work_force__c/fields/ET_Special_Requirements__c.field-meta.xml
<CustomField>
    <fullName>ET_Special_Requirements__c</fullName>
    <label>Special requirements</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Yes</fullName>
            </value>
            <value>
                <fullName>No</fullName>
                <isActive>false</isActive>
                <label>No</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/ET_Work_force__c/fields/ET_Supervisor_Category__c.field-meta.xml
<CustomField>
    <fullName>ET_Supervisor_Category__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Supervisor Category</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Workforce_Master__c/Workforce_Master__c.object-meta.xml
<CustomObject>
    <label>Workforce Master</label>
    <nameField>
        <displayFormat>WFM-{0000}</displayFormat>
        <label>Workforce Master Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Workforce Masters</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Workforce_Master__c/fields/Workforce_Type__c.field-meta.xml
<CustomField>
    <fullName>Workforce_Type__c</fullName>
    <label>Workforce Type</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Workforce_Type</valueSetName>
    </valueSet>
</CustomField>

unpackaged/main/default/globalValueSets/Workforce_Type.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Accountant/Cashier</fullName>
    </customValue>
    <customValue>
        <fullName>Coordinator</fullName>
    </customValue>
    <customValue>
        <fullName>Driver</fullName>
    </customValue>
    <customValue>
        <fullName>Nanny</fullName>
    </customValue>
    <customValue>
        <fullName>Other Employee</fullName>
    </customValue>
    <customValue>
        <fullName>Supervisor</fullName>
    </customValue>
    <description>All available types of manpower</description>
    <masterLabel>Workforce Type</masterLabel>
</GlobalValueSet>

unpackaged/main/default/classes/ET_WorkforceControllerTest.cls
@isTest(seeAlldata=false)
public class ET_WorkforceControllerTest {
    public static testMethod void getPicklistvaluesTestMethod1(){
        Workforce_Master__c workforce=new Workforce_Master__c(Workforce_Type__c='Driver');
        insert workforce;
        test.startTest();
        ET_WorkforceController.getPicklistvalues('ET_Work_force__c',new List<String>{'ET_Driver_Category__c'},'Driver');
        test.stopTest();
    }
    public static testMethod void getPicklistvaluesTestMethod2(){
        Workforce_Master__c workforce=new Workforce_Master__c(Workforce_Type__c='Nanny');
        insert workforce;
        test.startTest();
        ET_WorkforceController.getPicklistvalues('ET_Work_force__c',new List<String>{'ET_Nanny_Category__c'},'Nanny');
        test.stopTest();
    }
    public static testMethod void getPicklistvaluesTestMethod3(){
        Workforce_Master__c workforce=new Workforce_Master__c(Workforce_Type__c='Coordinator');
        insert workforce;
        test.startTest();
        ET_WorkforceController.getPicklistvalues('ET_Work_force__c',new List<String>{'ET_Coordinator_Category__c'},'Coordinator');
        test.stopTest();
    }
    public static testMethod void getPicklistvaluesTestMethod4(){
        Workforce_Master__c workforce=new Workforce_Master__c(Workforce_Type__c='Supervisor');
        insert workforce;
        test.startTest();
        ET_WorkforceController.getPicklistvalues('ET_Work_force__c',new List<String>{'ET_Supervisor_Category__c'},'Supervisor');
        test.stopTest();
    }
    public static testMethod void getPicklistvaluesTestMethod5(){
        Workforce_Master__c workforce=new Workforce_Master__c(Workforce_Type__c='Accountant/Cashier');
        insert workforce;
        test.startTest();
        ET_WorkforceController.getPicklistvalues('ET_Work_force__c',new List<String>{'ET_Accountant_Category__c'},'Accountant');
        test.stopTest();
    }
 /*   public static testMethod void getPicklistvaluesTestMethod6(){
        test.startTest();
        ET_WorkforceController.getPicklistvalues('ET_Work_force__c',new List<String>{'ET_Special_Requirements__c'},'Other Employee');
        test.stopTest();
    }*/
    public static testMethod void getPicklistvaluesTestMethod7(){
        Workforce_Master__c workforce=new Workforce_Master__c(Workforce_Type__c='Other Employee');
        insert workforce;
        test.startTest();
        ET_WorkforceController.getPicklistvalues('ET_Work_force__c',new List<String>{'ET_Other_employee_Category__c'},'Other Employee');
        test.stopTest();
    }
    public static testMethod void getPicklistvaluesTestMethod8(){
        test.startTest();
        ET_WorkforceController.getPicklistvalues('ET_Work_force__c',new List<String>{'ET_Special_requirements__c'},'Other Employee');
        test.stopTest();
    }
   
    public static testMethod void getPicklistvaluesTestMethod9(){
        test.startTest();
        ET_WorkforceController.getPicklistvalues('ET_Work_force__c',new List<String>{'ET_Service_Emirate__c'},'Other Employee');
        test.stopTest();
    }
    public static testMethod void getPicklistvaluesTestMethod10(){
        test.startTest();
        ET_WorkforceController.getPicklistvalues('ET_Work_force__c',new List<String>{'ET_Pricing_Method__c'},'Other Employee');
        test.stopTest();
    }
    
    public static testMethod void getPicklistvaluesTestMethod11(){
        test.startTest();
        ET_WorkforceController.getPicklistvalues('ET_Work_force__c',new List<String>{'ET_Contract_Type__c'},'Accountant');
        test.stopTest();
    }
    public static testMethod void getPicklistvaluesTestMethod12(){
        test.startTest();
        ET_WorkforceController.getPicklistvalues('ET_Work_force__c',new List<String>{'ET_Service_Emirate__c'},'Accountant');
        test.stopTest();
    }
        
}