unpackaged/main/default/objects/ETT_Collection_Card__c/ETT_Collection_Card__c.object-meta.xml
<CustomObject>
    <description>This object is to track the vehicle information and as well as driver information with the help of google map.</description>
    <label>Collection Card</label>
    <nameField>
        <displayFormat>CC-{0000}</displayFormat>
        <label>Collection Card Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Collection Cards</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/ETT_Collection_Card__c/fields/ETT_Inspection_Done__c.field-meta.xml
<CustomField>
    <fullName>ETT_Inspection_Done__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Inspection Done</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/objects/ETT_Collection_Card__c/fields/ETT_Status__c.field-meta.xml
<CustomField>
    <fullName>ETT_Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Collection Stage</fullName>
            </value>
            <value>
                <fullName>Inspection Stage</fullName>
            </value>
            <value>
                <fullName>Job Card Stage</fullName>
            </value>
            <value>
                <fullName>Delivery Stage</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/ETT_Inspection_Card__c/ETT_Inspection_Card__c.object-meta.xml
<CustomObject>
    <description>This is for inspection for the customer who has been requested orders.</description>
    <label>Tyre Inspection Card</label>
    <nameField>
        <displayFormat>IC-{0000}</displayFormat>
        <label>Inspection Card Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Tyre Inspection Cards</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/ETT_Inspection_Card__c/fields/ETT_Collection_Card__c.field-meta.xml
<CustomField>
    <fullName>ETT_Collection_Card__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Collection Card</label>
    <referenceTo>ETT_Collection_Card__c</referenceTo>
    <relationshipName>Inspection_Cards</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/ETT_Inspection_Card__c/fields/ETT_Status__c.field-meta.xml
<CustomField>
    <fullName>ETT_Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Not Inspected</fullName>
                <default>true</default>
                <label>Not Inspected</label>
            </value>
            <value>
                <fullName>Accept</fullName>
            </value>
            <value>
                <fullName>Send Back</fullName>
            </value>
            <value>
                <fullName>Scrap</fullName>
            </value>
            <value>
                <fullName>Accepted/No Warranty</fullName>
            </value>
            <value>
                <fullName>Pending</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/classes/ETT_TyreInspectionCardTrgHandler.cls
/**
 * Created By: Janardhan Muddana
 * Created Date:25/02/2022
 * Description :
 * Test Class: ETT_TyreInspectionCardTrgHandlerTest
 * */
public class ETT_TyreInspectionCardTrgHandler {
    
    public static void InspectionConfirmationUpdate(Map<Id,ETT_Inspection_Card__c> trgNewMap,Map<Id,ETT_Inspection_Card__c> trgOldMap){
     
      set<id> CCIdSet = new set<id>();
      Map<Id,Decimal> CCIDVsTotalInsCards = new Map<Id,Decimal>();
      Map<Id,Decimal> CCIDVsNotInspCount = new Map<Id,Decimal>();
      Map<Id,Decimal> CCIDVsAcceptedCount = new Map<Id,Decimal>();
      Map<Id,Decimal> CCIDVsSendBackCount = new Map<Id,Decimal>();
      list<ETT_Collection_Card__c> cclist = new list<ETT_Collection_Card__c>();
        
        for(ETT_Inspection_Card__c ic : trgNewMap.values()){
            CCIdSet.add(ic.ETT_Collection_Card__c);
        }
      
        for(AggregateResult ar : [select count(id) CountVal,ETT_Collection_Card__c ColCard from ETT_Inspection_Card__c where ETT_Collection_Card__c =:CCIdSet group by ETT_Collection_Card__c]){
            CCIDVsTotalInsCards.put((Id)ar.get('ColCard'),(Decimal)ar.get('CountVal'));
         }
        for(AggregateResult ar : [select count(id) CountVal,ETT_Collection_Card__c ColCard from ETT_Inspection_Card__c where ETT_Collection_Card__c =:CCIdSet AND ETT_Status__c='Not Inspected' group by ETT_Collection_Card__c]){
            CCIDVsNotInspCount.put((Id)ar.get('ColCard'),(Decimal)ar.get('CountVal'));
         }
        for(AggregateResult ar : [select count(id) CountVal,ETT_Collection_Card__c ColCard from ETT_Inspection_Card__c where ETT_Collection_Card__c =:CCIdSet AND ETT_Status__c='Accept' group by ETT_Collection_Card__c]){
            CCIDVsAcceptedCount.put((Id)ar.get('ColCard'),(Decimal)ar.get('CountVal'));
         }
        for(AggregateResult ar : [select count(id) CountVal,ETT_Collection_Card__c ColCard from ETT_Inspection_Card__c where ETT_Collection_Card__c =:CCIdSet AND ETT_Status__c='Send Back' group by ETT_Collection_Card__c]){
            CCIDVsSendBackCount.put((Id)ar.get('ColCard'),(Decimal)ar.get('CountVal'));
         }
        
        for(ETT_Inspection_Card__c ic : trgNewMap.values()){
            
            if((ic.ETT_Status__c == 'Accept' || ic.ETT_Status__c == 'Send Back') && trgOldMap.get(ic.Id).ETT_Status__c=='Pending'){
                
                decimal notInspectedCount = CCIDVsNotInspCount.containskey(ic.ETT_Collection_Card__c)?CCIDVsNotInspCount.get(ic.ETT_Collection_Card__c):0;
                decimal totalCount = CCIDVsTotalInsCards.containskey(ic.ETT_Collection_Card__c)?CCIDVsTotalInsCards.get(ic.ETT_Collection_Card__c):0;
                decimal acceptCount = CCIDVsAcceptedCount.containskey(ic.ETT_Collection_Card__c)?CCIDVsAcceptedCount.get(ic.ETT_Collection_Card__c):0;
                decimal sendBackCount = CCIDVsSendBackCount.containskey(ic.ETT_Collection_Card__c)?CCIDVsSendBackCount.get(ic.ETT_Collection_Card__c):0;
                
                if(notInspectedCount == 0 && totalCount == (acceptCount+sendBackCount)){
                    
                    ETT_Collection_Card__c ccItem = new ETT_Collection_Card__c();
                    ccItem.Id =  ic.ETT_Collection_Card__c;
                    ccItem.ETT_Inspection_Done__c = true; 
                    cclist.add(ccItem);
                }    

            }
        }
        
        update cclist;
        
        
    }

}