unpackaged/main/default/objects/ETT_Collection_Card__c/ETT_Collection_Card__c.object-meta.xml
<CustomObject>
    <description>This object is to track the vehicle information and as well as driver information with the help of google map.</description>
    <label>Collection Card</label>
    <nameField>
        <displayFormat>CC-{0000}</displayFormat>
        <label>Collection Card Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Collection Cards</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/ETT_Collection_Card__c/fields/ETT_Accounts__c.field-meta.xml
<CustomField>
    <fullName>ETT_Accounts__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Collection Cards</relationshipLabel>
    <relationshipName>Collection_Cards</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/ETT_Collection_Card__c/fields/ETT_Status__c.field-meta.xml
<CustomField>
    <fullName>ETT_Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Collection Stage</fullName>
            </value>
            <value>
                <fullName>Inspection Stage</fullName>
            </value>
            <value>
                <fullName>Job Card Stage</fullName>
            </value>
            <value>
                <fullName>Delivery Stage</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/ETT_Inspection_Card__c/ETT_Inspection_Card__c.object-meta.xml
<CustomObject>
    <description>This is for inspection for the customer who has been requested orders.</description>
    <label>Tyre Inspection Card</label>
    <nameField>
        <displayFormat>IC-{0000}</displayFormat>
        <label>Inspection Card Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Tyre Inspection Cards</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/ETT_Inspection_Card__c/fields/ETT_Collection_Card__c.field-meta.xml
<CustomField>
    <fullName>ETT_Collection_Card__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Collection Card</label>
    <referenceTo>ETT_Collection_Card__c</referenceTo>
    <relationshipName>Inspection_Cards</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/ETT_Inspection_Card__c/fields/ETT_Status__c.field-meta.xml
<CustomField>
    <fullName>ETT_Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Not Inspected</fullName>
                <default>true</default>
                <label>Not Inspected</label>
            </value>
            <value>
                <fullName>Accept</fullName>
            </value>
            <value>
                <fullName>Send Back</fullName>
            </value>
            <value>
                <fullName>Scrap</fullName>
            </value>
            <value>
                <fullName>Accepted/No Warranty</fullName>
            </value>
            <value>
                <fullName>Pending</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/classes/ETT_TyreInspectionCardTrgHandlerTest.cls
@isTest
public class ETT_TyreInspectionCardTrgHandlerTest {

    private static testmethod void createInspectCard(){
        
        Account objAcc = new Account();
        objAcc.Name = 'TestAccount';
        insert objAcc;
              
        
        ETT_Collection_Card__c objCC = new ETT_Collection_Card__c();
        objCC.ETT_Accounts__c = objAcc.Id;
        //objCC.ETT_Status__c = 'New';
        objCC.RecordTypeId = Schema.SObjectType.ETT_Collection_Card__c.getRecordTypeInfosByName().get('Tyre Supplier').getRecordTypeId();
        insert objCC;
        
        
        ETT_Inspection_Card__c objIC = new ETT_Inspection_Card__c();
        objIC.RecordTypeId = Schema.SObjectType.ETT_Inspection_Card__c.getRecordTypeInfosByName().get('Tyre Supplier').getRecordTypeId();
        objIC.ETT_Collection_Card__c = objCC.Id;
        objIC.ETT_Status__c = 'Pending';
        insert objIC;
        
        objIC.ETT_Status__c = 'Accept';
        update objIC;
    }
}