unpackaged/main/default/objects/ETT_Collection_Card__c/ETT_Collection_Card__c.object-meta.xml
<CustomObject>
    <description>This object is to track the vehicle information and as well as driver information with the help of google map.</description>
    <label>Collection Card</label>
    <nameField>
        <displayFormat>CC-{0000}</displayFormat>
        <label>Collection Card Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Collection Cards</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/ETT_Collection_Card__c/fields/ETT_Account__c.field-meta.xml
<CustomField>
    <fullName>ETT_Account__c</fullName>
    <formula>ETT_Service_Appointment__r.Account.Name</formula>
    <label>Account</label>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/ETT_Collection_Card__c/fields/ETT_Accounts__c.field-meta.xml
<CustomField>
    <fullName>ETT_Accounts__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Collection Cards</relationshipLabel>
    <relationshipName>Collection_Cards</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/ETT_Collection_Card__c/fields/ETT_Opportunity__c.field-meta.xml
<CustomField>
    <fullName>ETT_Opportunity__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Collection Cards</relationshipLabel>
    <relationshipName>Collection_Cards</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/ETT_Collection_Card__c/fields/ETT_Tyre_Size__c.field-meta.xml
<CustomField>
    <fullName>ETT_Tyre_Size__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Tyre Size</label>
    <referenceTo>ETT_Tyre_Size_Master__c</referenceTo>
    <relationshipLabel>Collection Cards</relationshipLabel>
    <relationshipName>Collection_Cards</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/ETT_Collection_Card__c/fields/HasTyresWithoutPrice__c.field-meta.xml
<CustomField>
    <fullName>HasTyresWithoutPrice__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Has Tyres Without Price</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/objects/ETT_Pattern_Master__c/ETT_Pattern_Master__c.object-meta.xml
<CustomObject>
    <label>Pattern Master</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Pattern Code</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Pattern Masters</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/ETT_Pattern_Master__c/fields/ETT_Brand_Name__c.field-meta.xml
<CustomField>
    <fullName>ETT_Brand_Name__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Brand Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/ETT_Price_Master__c/ETT_Price_Master__c.object-meta.xml
<CustomObject>
    <label>Price Master</label>
    <nameField>
        <displayFormat>PMN-{0000}</displayFormat>
        <label>Price Master Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Price Masters</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/ETT_Price_Master__c/fields/ETT_Party_Name__c.field-meta.xml
<CustomField>
    <fullName>ETT_Party_Name__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Party Name</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Price Masters</relationshipLabel>
    <relationshipName>Price_Masters</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/ETT_Pricing_Information__c/ETT_Pricing_Information__c.object-meta.xml
<CustomObject>
    <label>Pricing Information</label>
    <nameField>
        <displayFormat>PI-{0000}</displayFormat>
        <label>Pricing Info Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Pricing Information</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

unpackaged/main/default/objects/ETT_Pricing_Information__c/fields/ETT_Approval_Status__c.field-meta.xml
<CustomField>
    <fullName>ETT_Approval_Status__c</fullName>
    <label>Approval Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>New</fullName>
            </value>
            <value>
                <fullName>In Progress</fullName>
            </value>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>Rejected</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/ETT_Pricing_Information__c/fields/ETT_Price__c.field-meta.xml
<CustomField>
    <fullName>ETT_Price__c</fullName>
    <label>Price</label>
    <referenceTo>ETT_Price_Master__c</referenceTo>
    <relationshipLabel>Pricing Information</relationshipLabel>
    <relationshipName>Pricing_Information</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

unpackaged/main/default/objects/ETT_Pricing_Information__c/fields/ETT_Tyre_Size__c.field-meta.xml
<CustomField>
    <fullName>ETT_Tyre_Size__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Tyre Size</label>
    <referenceTo>ETT_Tyre_Size_Master__c</referenceTo>
    <relationshipLabel>Pricing Information</relationshipLabel>
    <relationshipName>Pricing_Information</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/ETT_StagingNewTyreCollection__c/ETT_StagingNewTyreCollection__c.object-meta.xml
<CustomObject>
    <label>Staging New Tyre Collection</label>
    <nameField>
        <displayFormat>SNTC-{00000}</displayFormat>
        <label>Ref Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Staging New Tyre Collections</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/ETT_StagingNewTyreCollection__c/fields/Collection_Card__c.field-meta.xml
<CustomField>
    <fullName>Collection_Card__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Collection Card</label>
    <referenceTo>ETT_Collection_Card__c</referenceTo>
    <relationshipLabel>Staging New Tyre Collections</relationshipLabel>
    <relationshipName>Staging_New_Tyre_Collections</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/ETT_StagingNewTyreCollection__c/fields/Country_Name__c.field-meta.xml
<CustomField>
    <fullName>Country_Name__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Country Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/ETT_StagingNewTyreCollection__c/fields/Pattern_Name__c.field-meta.xml
<CustomField>
    <fullName>Pattern_Name__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Pattern Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/ETT_StagingNewTyreCollection__c/fields/Size_Name__c.field-meta.xml
<CustomField>
    <fullName>Size_Name__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Size Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/ETT_Tyre_Inventory__c/ETT_Tyre_Inventory__c.object-meta.xml
<CustomObject>
    <label>Tyre Inventory</label>
    <nameField>
        <displayFormat>TI-{0000}</displayFormat>
        <label>Tyre Inventory Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Tyre Inventory</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/ETT_Tyre_Inventory__c/fields/ETT_Account__c.field-meta.xml
<CustomField>
    <fullName>ETT_Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Tyre Inventory</relationshipLabel>
    <relationshipName>Tyre_Inventory</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/ETT_Tyre_Inventory__c/fields/ETT_Collection_Card__c.field-meta.xml
<CustomField>
    <fullName>ETT_Collection_Card__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Collection Card</label>
    <referenceTo>ETT_Collection_Card__c</referenceTo>
    <relationshipLabel>Tyre Inventory</relationshipLabel>
    <relationshipName>Tyre_Inventory</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/ETT_Tyre_Inventory__c/fields/ETT_Inventory_Status__c.field-meta.xml
<CustomField>
    <fullName>ETT_Inventory_Status__c</fullName>
    <label>Inventory Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>WIP</fullName>
            </value>
            <value>
                <fullName>Finished</fullName>
            </value>
            <value>
                <fullName>Draft</fullName>
                <default>true</default>
                <label>Draft</label>
            </value>
            <value>
                <fullName>Approved by Receptionist</fullName>
            </value>
            <value>
                <fullName>Inspected - Approved</fullName>
            </value>
            <value>
                <fullName>Inspected - Rejected</fullName>
            </value>
            <value>
                <fullName>Job Card Created</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/ETT_Tyre_Inventory__c/fields/ETT_Tyre_Master__c.field-meta.xml
<CustomField>
    <fullName>ETT_Tyre_Master__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Tyre Master</label>
    <referenceTo>ETT_Tyre_Master__c</referenceTo>
    <relationshipLabel>Tyre Inventory</relationshipLabel>
    <relationshipName>Tyre_Inventory</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/ETT_Tyre_Inventory__c/fields/ETT_Tyre_Size_Master__c.field-meta.xml
<CustomField>
    <fullName>ETT_Tyre_Size_Master__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Tyre Size</label>
    <referenceTo>ETT_Tyre_Size_Master__c</referenceTo>
    <relationshipLabel>Tyre Inventory</relationshipLabel>
    <relationshipName>Tyre_Inventory</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/ETT_Tyre_Master__c/ETT_Tyre_Master__c.object-meta.xml
<CustomObject>
    <label>Tyre Master</label>
    <nameField>
        <displayFormat>TMN-{0000}</displayFormat>
        <label>Tyre Master Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Tyre Masters</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/ETT_Tyre_Master__c/fields/ETT_Brand_Name__c.field-meta.xml
<CustomField>
    <fullName>ETT_Brand_Name__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Brand Name</label>
    <referenceTo>ETT_Brand_Master__c</referenceTo>
    <relationshipLabel>Tyre Masters</relationshipLabel>
    <relationshipName>Tyre_Masters</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/ETT_Tyre_Master__c/fields/ETT_Collection_Card__c.field-meta.xml
<CustomField>
    <fullName>ETT_Collection_Card__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Collection Card</label>
    <referenceTo>ETT_Collection_Card__c</referenceTo>
    <relationshipLabel>Tyre Masters</relationshipLabel>
    <relationshipName>Tyre_Masters</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/ETT_Tyre_Master__c/fields/ETT_Country_Name__c.field-meta.xml
<CustomField>
    <fullName>ETT_Country_Name__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Country Name</label>
    <referenceTo>ETT_Country_Master__c</referenceTo>
    <relationshipLabel>Tyre Masters</relationshipLabel>
    <relationshipName>Tyre_Masters</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/ETT_Tyre_Master__c/fields/ETT_Original_Pattern__c.field-meta.xml
<CustomField>
    <fullName>ETT_Original_Pattern__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Original Pattern</label>
    <referenceTo>ETT_Pattern_Master__c</referenceTo>
    <relationshipLabel>Tyre Masters</relationshipLabel>
    <relationshipName>Tyre_Masters</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/ETT_Tyre_Master__c/fields/ETT_Price__c.field-meta.xml
<CustomField>
    <fullName>ETT_Price__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Price</label>
    <length>250</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/ETT_Tyre_Master__c/fields/ETT_Tyre_Size__c.field-meta.xml
<CustomField>
    <fullName>ETT_Tyre_Size__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Tyre Size</label>
    <referenceTo>ETT_Tyre_Size_Master__c</referenceTo>
    <relationshipLabel>Tyre Masters</relationshipLabel>
    <relationshipName>Tyre_Masters</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/ETT_Tyre_Size_Master__c/ETT_Tyre_Size_Master__c.object-meta.xml
<CustomObject>
    <label>Tyre Size Master</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Tyre Sizes</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Tyre Size Master</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/ETT_Tyre_Size_Master__c/fields/ETT_Tyre_Size__c.field-meta.xml
<CustomField>
    <fullName>ETT_Tyre_Size__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Tyre size</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/classes/ETT_TyreCollectionDetailsInCCTest.cls
@isTest
public class ETT_TyreCollectionDetailsInCCTest {
    
    public static testmethod void tyreCollMethod(){
        test.startTest();
        Profile p = [SELECT Id FROM Profile WHERE Name='ETT_Receptionist']; 
        User recp = new User(Alias = 'standt', Email='stanRecp@testorg.com', 
                             EmailEncodingKey='UTF-8', LastName='Testing', LanguageLocaleKey='en_US', 
                             LocaleSidKey='en_US', ProfileId = p.Id, 
                             TimeZoneSidKey='America/Los_Angeles', UserName='standaRecpser@testorg.com');
        
        List<Account> accountsList = ETT_TestFactory.createAccounts('Test92J35464', 'Organization');
        insert accountsList;
        Opportunity opp = ETT_TestFactory.createOpportunity('Tyre Supplier','TestOppName', 'Qualification', system.today().adddays(20), accountsList[0].Id);
        insert opp;
        
        ETT_Collection_Card__c objCC = new ETT_Collection_Card__c();
        objCC.ETT_Accounts__c = accountsList[0].Id;
        objCC.ETT_Opportunity__c = opp.Id;
        insert objCC;
        
        ETT_Price_Master__c pm = new ETT_Price_Master__c();
        pm.ETT_Party_Name__c = accountsList[0].Id;
        insert pm;
        
        ETT_Tyre_Master__c tm =  new ETT_Tyre_Master__c();
        insert tm;
        
        
        List<Account> accountsList2 = ETT_TestFactory.createAccounts('TeJK89ame35464', 'Organization');
        insert accountsList2;
        Opportunity opp2 = ETT_TestFactory.createOpportunity('Tyre Supplier','TestOppName', 'Qualification', system.today().adddays(20), accountsList[0].Id);
        insert opp2;
        
        
        ETT_Collection_Card__c objCC2 = new ETT_Collection_Card__c();
        objCC2.ETT_Accounts__c = accountsList2[0].Id;
        objCC2.ETT_Opportunity__c = opp2.Id;
        objCC2.HasTyresWithoutPrice__c = false;
        insert objCC2;
        
        ETT_Tyre_Size_Master__c tsm = new ETT_Tyre_Size_Master__c();
        tsm.Name ='Size1967';
        insert tsm;
        
        ETT_Pattern_Master__c pat = new ETT_Pattern_Master__c();
        pat.Name ='Pat21';
        insert pat;
        
        ETT_Country_Master__c coun = new ETT_Country_Master__c();
        coun.Name ='Coun1';
        insert coun;
        
        ETT_Brand_Master__c bra = new ETT_Brand_Master__c();
        bra.Name ='Bran1';
        insert bra;
        
         ETT_Tyre_Size_Master__c tsm2 = new ETT_Tyre_Size_Master__c();
        tsm2.Name ='Size1456';
        insert tsm2;
        
        ETT_Pattern_Master__c pat2 = new ETT_Pattern_Master__c();
        pat2.Name ='Pat2178';
        insert pat2;
        
        ETT_Country_Master__c coun2 = new ETT_Country_Master__c();
        coun2.Name ='Coun198';
        insert coun2;
        
        ETT_Brand_Master__c bra2 = new ETT_Brand_Master__c();
        bra2.Name ='Bran180';
        insert bra2;
        
        
        
        ETT_Price_Master__c pm2 = new ETT_Price_Master__c();
        pm2.ETT_Party_Name__c = accountsList2[0].Id;
        insert pm2;
        
        ETT_Pricing_Information__c epi = new ETT_Pricing_Information__c();
        epi.ETT_Price__c=pm2.Id;
        epi.ETT_Approval_Status__c ='Approved';
        insert epi;
        
        ETT_Tyre_Master__c tm2 =  new ETT_Tyre_Master__c();
        tm2.ETT_Brand_Name__c=bra.id;
        tm2.ETT_Tyre_Size__c=tsm.id;
        tm2.ETT_Original_Pattern__c=pat2.id;
        tm2.ETT_Country_Name__c=coun2.id;
        insert tm2;
        
        ETT_Tyre_Inventory__c tin = new ETT_Tyre_Inventory__c();
        tin.ETT_Account__c = accountsList2[0].Id;
        tin.ETT_Collection_Card__c = objCC2.Id;
        tin.Serial_Number__c = '243254454';
        tin.ETT_Inventory_Status__c='Draft';
        
        
        ETT_StagingNewTyreCollection__c stg = new ETT_StagingNewTyreCollection__c();
        stg.Brand_Name__c = 'test';
        stg.Collection_Card__c = objCC2.Id;
        stg.Country_Name__c = 'test';
        stg.Pattern_Name__c='test';
        stg.Size_Name__c ='test';
        
        
         ETT_Tyre_Inventory__c tin2 = new ETT_Tyre_Inventory__c();
        tin2.ETT_Account__c = accountsList2[0].Id;
        tin2.ETT_Collection_Card__c = objCC2.Id;
        tin2.Serial_Number__c = '243254454';
        tin2.ETT_Inventory_Status__c='Draft';
        tin2.ETT_Brand__c = bra.Id;
        tin2.ETT_Country__c=coun.id;
        tin2.ETT_Pattern__c=pat.id;
        tin2.ETT_Tyre_Size_Master__c=tsm.Id;
       
        insert tin2;
        
        tin2.ETT_Brand__c = bra2.Id;
        tin2.ETT_Country__c=coun2.id;
        tin2.ETT_Pattern__c=pat2.id;
        tin2.ETT_Tyre_Size_Master__c=tsm2.Id; 
        update tin2;
        
        ETT_StagingNewTyreCollection__c stg2 = new ETT_StagingNewTyreCollection__c();
        stg2.Brand_Name__c = 'test';
        stg2.Collection_Card__c = objCC2.Id;
        stg2.Country_Name__c = 'test';
        stg2.Pattern_Name__c='test';
        stg2.Size_Name__c ='test';
        insert stg2;
        
        ETT_TyreCollectionDetailsInCC.getTyreInventoryDetials(objCC2.Id);
        ETT_TyreCollectionDetailsInCC.getStagTyreDetials(objCC2.Id);
        ETT_TyreCollectionDetailsInCC.getUserInfo();
        ETT_TyreCollectionDetailsInCC.getTyreMasterDetails(objCC2.Id);
        ETT_TyreCollectionDetailsInCC.getPricingConfirmDetails(objCC2.Id);
       // ETT_TyreCollectionDetailsInCC.updateCollectionCard(objCC2.Id,'ETT_Check_Out__c');
       // ETT_TyreCollectionDetailsInCC.updateTyreMasterDetails(new list<ETT_Tyre_Master__c>{tm2},objCC2.Id);
       // ETT_TyreCollectionDetailsInCC.getselectOptions('ETT_Inventory_Status__c');
       //  ETT_TyreCollectionDetailsInCC.approvalProcess(objCC2.Id);
      //  ETT_TyreCollectionDetailsInCC.insertNewStagNewTyreInven(new list<ETT_Tyre_Inventory__c>{tin},new list<ETT_StagingNewTyreCollection__c>{stg},new list<ETT_StagingNewTyreCollection__c>{stg2},new list<ETT_Tyre_Inventory__c>{tin2},objCC2.Id );
       // ETT_TyreCollectionDetailsInCC.updatePricingConfirmDetails(new list<ETT_Pricing_Information__c>{epi},objCC2.Id);
        
        
        ETT_TyreCollectionDetailsInCC.deleteRecord(objCC2.Id);
        
        test.stopTest();
    }
    public static testmethod void tyreCollMethod2(){
        test.startTest();
        Profile p = [SELECT Id FROM Profile WHERE Name='ETT_Receptionist']; 
        User recp = new User(Alias = 'standt', Email='stanRecp@testorg.com', 
                             EmailEncodingKey='UTF-8', LastName='Testing', LanguageLocaleKey='en_US', 
                             LocaleSidKey='en_US', ProfileId = p.Id, 
                             TimeZoneSidKey='America/Los_Angeles', UserName='standaRecpser@testorg.com');
        
        List<Account> accountsList = ETT_TestFactory.createAccounts('Test92J35464', 'Organization');
        insert accountsList;
        Opportunity opp = ETT_TestFactory.createOpportunity('Tyre Supplier','TestOppName', 'Qualification', system.today().adddays(20), accountsList[0].Id);
        insert opp;
        
        ETT_Collection_Card__c objCC = new ETT_Collection_Card__c();
        objCC.ETT_Accounts__c = accountsList[0].Id;
        objCC.ETT_Opportunity__c = opp.Id;
        insert objCC;
        
        ETT_Price_Master__c pm = new ETT_Price_Master__c();
        pm.ETT_Party_Name__c = accountsList[0].Id;
        insert pm;
        
        ETT_Tyre_Master__c tm =  new ETT_Tyre_Master__c();
        insert tm;
        
        
        List<Account> accountsList2 = ETT_TestFactory.createAccounts('TeJK89ame35464', 'Organization');
        insert accountsList2;
        Opportunity opp2 = ETT_TestFactory.createOpportunity('Tyre Supplier','TestOppName', 'Qualification', system.today().adddays(20), accountsList[0].Id);
        insert opp2;
        
        
        ETT_Collection_Card__c objCC2 = new ETT_Collection_Card__c();
        objCC2.ETT_Accounts__c = accountsList2[0].Id;
        objCC2.ETT_Opportunity__c = opp2.Id;
        objCC2.HasTyresWithoutPrice__c = false;
        insert objCC2;
        
        ETT_Tyre_Size_Master__c tsm = new ETT_Tyre_Size_Master__c();
        tsm.Name ='Size167';
        insert tsm;
        
        ETT_Pattern_Master__c pat = new ETT_Pattern_Master__c();
        pat.Name ='Pat21';
        insert pat;
        
        ETT_Country_Master__c coun = new ETT_Country_Master__c();
        coun.Name ='Coun1';
        insert coun;
        
        ETT_Brand_Master__c bra = new ETT_Brand_Master__c();
        bra.Name ='Bran1';
        insert bra;
        
         ETT_Tyre_Size_Master__c tsm2 = new ETT_Tyre_Size_Master__c();
        tsm2.Name ='Size134';
        insert tsm2;
        
        ETT_Pattern_Master__c pat2 = new ETT_Pattern_Master__c();
        pat2.Name ='Pat213';
        insert pat2;
        
        ETT_Country_Master__c coun2 = new ETT_Country_Master__c();
        coun2.Name ='Coun1689';
        insert coun2;
        
        ETT_Brand_Master__c bra2 = new ETT_Brand_Master__c();
        bra2.Name ='Bran178';
        insert bra2;
        
        
        
        ETT_Price_Master__c pm2 = new ETT_Price_Master__c();
        pm2.ETT_Party_Name__c = accountsList2[0].Id;
        insert pm2;
        
        ETT_Pricing_Information__c epi = new ETT_Pricing_Information__c();
        epi.ETT_Price__c=pm2.Id;
        epi.ETT_Approval_Status__c ='Approved';
        insert epi;
        
        ETT_Tyre_Master__c tm2 =  new ETT_Tyre_Master__c();
        tm2.ETT_Brand_Name__c=bra.id;
        tm2.ETT_Tyre_Size__c=tsm.id;
        tm2.ETT_Original_Pattern__c=pat2.id;
        tm2.ETT_Country_Name__c=coun2.id;
        insert tm2;
        
        ETT_Tyre_Inventory__c tin = new ETT_Tyre_Inventory__c();
        tin.ETT_Account__c = accountsList2[0].Id;
        tin.ETT_Collection_Card__c = objCC2.Id;
        tin.Serial_Number__c = '243254454';
        tin.ETT_Inventory_Status__c='Draft';
        
        
        ETT_StagingNewTyreCollection__c stg = new ETT_StagingNewTyreCollection__c();
        stg.Brand_Name__c = 'test';
        stg.Collection_Card__c = objCC2.Id;
        stg.Country_Name__c = 'test';
        stg.Pattern_Name__c='test';
        stg.Size_Name__c ='test';
        
        
         ETT_Tyre_Inventory__c tin2 = new ETT_Tyre_Inventory__c();
        tin2.ETT_Account__c = accountsList2[0].Id;
        tin2.ETT_Collection_Card__c = objCC2.Id;
        tin2.Serial_Number__c = '243254454';
        tin2.ETT_Inventory_Status__c='Draft';
        tin2.ETT_Brand__c = bra.Id;
        tin2.ETT_Country__c=coun.id;
        tin2.ETT_Pattern__c=pat.id;
        tin2.ETT_Tyre_Size_Master__c=tsm.Id;
       
        insert tin2;
        
        tin2.ETT_Brand__c = bra2.Id;
        tin2.ETT_Country__c=coun2.id;
        tin2.ETT_Pattern__c=pat2.id;
        tin2.ETT_Tyre_Size_Master__c=tsm2.Id; 
        update tin2;
        
        ETT_StagingNewTyreCollection__c stg2 = new ETT_StagingNewTyreCollection__c();
        stg2.Brand_Name__c = 'test';
        stg2.Collection_Card__c = objCC2.Id;
        stg2.Country_Name__c = 'test';
        stg2.Pattern_Name__c='test';
        stg2.Size_Name__c ='test';
        insert stg2;
        
        //ETT_TyreCollectionDetailsInCC.getTyreInventoryDetials(objCC2.Id);
        //ETT_TyreCollectionDetailsInCC.getStagTyreDetials(objCC2.Id);
       // ETT_TyreCollectionDetailsInCC.getUserInfo();
        //ETT_TyreCollectionDetailsInCC.getTyreMasterDetails(objCC2.Id);
        //ETT_TyreCollectionDetailsInCC.getPricingConfirmDetails(objCC2.Id);
        ETT_TyreCollectionDetailsInCC.updateCollectionCard(objCC2.Id,'ETT_Check_Out__c');
        ETT_TyreCollectionDetailsInCC.updateTyreMasterDetails(new list<ETT_Tyre_Master__c>{tm2},objCC2.Id);
        ETT_TyreCollectionDetailsInCC.getselectOptions('ETT_Inventory_Status__c');
         ETT_TyreCollectionDetailsInCC.approvalProcess(objCC2.Id);
        ETT_TyreCollectionDetailsInCC.insertNewStagNewTyreInven(new list<ETT_Tyre_Inventory__c>{tin},new list<ETT_StagingNewTyreCollection__c>{stg},new list<ETT_StagingNewTyreCollection__c>{stg2},new list<ETT_Tyre_Inventory__c>{tin2},objCC2.Id );
        ETT_TyreCollectionDetailsInCC.updatePricingConfirmDetails(new list<ETT_Pricing_Information__c>{epi},objCC2.Id);
        
        
        //ETT_TyreCollectionDetailsInCC.deleteRecord(objCC2.Id);
        
        test.stopTest();
    }
    
}