unpackaged/main/default/objects/ETT_Collection_Card__c/ETT_Collection_Card__c.object-meta.xml
<CustomObject>
    <description>This object is to track the vehicle information and as well as driver information with the help of google map.</description>
    <label>Collection Card</label>
    <nameField>
        <displayFormat>CC-{0000}</displayFormat>
        <label>Collection Card Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Collection Cards</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/ETT_Collection_Card__c/fields/Collection_Appointment__c.field-meta.xml
<CustomField>
    <fullName>Collection_Appointment__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Collection Appointment</label>
    <referenceTo>Tyre_Collection_Appointment__c</referenceTo>
    <relationshipLabel>Collection Cards</relationshipLabel>
    <relationshipName>Collection_Cards</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/ETT_Collection_Card__c/fields/ETT_Accounts__c.field-meta.xml
<CustomField>
    <fullName>ETT_Accounts__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Collection Cards</relationshipLabel>
    <relationshipName>Collection_Cards</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/ETT_Collection_Card__c/fields/ETT_Collection_Status__c.field-meta.xml
<CustomField>
    <fullName>ETT_Collection_Status__c</fullName>
    <label>Collection Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>New</fullName>
            </value>
            <value>
                <fullName>In Progress</fullName>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
            <value>
                <fullName>Accepted</fullName>
            </value>
            <value>
                <fullName>Rejected</fullName>
            </value>
            <value>
                <fullName>Scheduled</fullName>
            </value>
            <value>
                <fullName>Inspection Cards Created</fullName>
            </value>
            <value>
                <fullName>Inspection Completed</fullName>
            </value>
            <value>
                <fullName>Job Card Created</fullName>
            </value>
            <value>
                <fullName>Check and Report</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/ETT_Collection_Card__c/fields/ETT_Opportunity__c.field-meta.xml
<CustomField>
    <fullName>ETT_Opportunity__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Collection Cards</relationshipLabel>
    <relationshipName>Collection_Cards</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Tyre_Collection_Appointment__c/Tyre_Collection_Appointment__c.object-meta.xml
<CustomObject>
    <description>Label name is changed to accommodate same object for all tyre appointments, please note dont confuse with API name</description>
    <label>Tyre Service Appointment</label>
    <nameField>
        <displayFormat>TSA-{00000}</displayFormat>
        <label>Appointment Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Tyre Service Appointments</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Tyre_Collection_Appointment__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipName>Tyre_Collection_Appointments</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Tyre_Collection_Appointment__c/fields/Appointment_Type__c.field-meta.xml
<CustomField>
    <fullName>Appointment_Type__c</fullName>
    <label>Appointment Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Collection</fullName>
            </value>
            <value>
                <fullName>Delivery</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Tyre_Collection_Appointment__c/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipName>Tyre_Collection_Appointments</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Tyre_Collection_Appointment__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>New</fullName>
                <default>true</default>
                <label>New</label>
            </value>
            <value>
                <fullName>In Progress</fullName>
            </value>
            <value>
                <fullName>Closed</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
            <value>
                <fullName>Pending</fullName>
            </value>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>Rejected</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/classes/ETT_TyreCollApptTrgHelper.cls
/**Author:Janardhan
 * Desc: If appointment approved creating Collection cards
 * CreatedDate: 22/11/2021
 * TestClass:ETT_TyreCollApptTrgHelperTest
 * 
 * */
public class ETT_TyreCollApptTrgHelper {
    
    
    public static void createCollCard(Map<id,Tyre_Collection_Appointment__c> newMap,Map<id,Tyre_Collection_Appointment__c> oldMap)  {
        
        list<ETT_Collection_Card__c> newCollCardList = new  list<ETT_Collection_Card__c>();
        
        for(Tyre_Collection_Appointment__c tc : newMap.values()){
            
            if(tc.Status__c == 'Approved' && tc.Appointment_Type__c =='Collection' && tc.Status__c != oldMap.get(tc.Id).Status__c){
                
                ETT_Collection_Card__c objCollCard = new ETT_Collection_Card__c();
                
                objCollCard.ETT_Accounts__c = tc.Account__c;
                objCollCard.ETT_Opportunity__c = tc.Opportunity__c;
                objCollCard.Collection_Appointment__c = tc.id;
                objCollCard.ETT_Collection_Status__c = 'Scheduled';
                objCollCard.RecordTypeId = Schema.SObjectType.ETT_Collection_Card__c.getRecordTypeInfosByName().get('Tyre Supplier').getRecordTypeId(); 
				
                newCollCardList.add(objCollCard);
            }            
            
        }        
        
        if(newCollCardList.size()>0 && newCollCardList != null){
            
            insert newCollCardList;
        }
        
    }

}