unpackaged/main/default/objects/ETT_Collection_Card__c/ETT_Collection_Card__c.object-meta.xml
<CustomObject>
    <description>This object is to track the vehicle information and as well as driver information with the help of google map.</description>
    <label>Collection Card</label>
    <nameField>
        <displayFormat>CC-{0000}</displayFormat>
        <label>Collection Card Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Collection Cards</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/ETT_Collection_Card__c/fields/ETT_Inspection_Done__c.field-meta.xml
<CustomField>
    <fullName>ETT_Inspection_Done__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Inspection Done</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/objects/ETT_Work_Schedule__c/ETT_Work_Schedule__c.object-meta.xml
<CustomObject>
    <label>Work Schedule</label>
    <nameField>
        <displayFormat>SCH-{000}</displayFormat>
        <label>Work Schedule Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Work Schedule</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

unpackaged/main/default/objects/ETT_Work_Schedule__c/fields/ETT_End_time__c.field-meta.xml
<CustomField>
    <fullName>ETT_End_time__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>End time</label>
    <required>true</required>
    <type>DateTime</type>
</CustomField>

unpackaged/main/default/objects/ETT_Work_Schedule__c/fields/ETT_Technician__c.field-meta.xml
<CustomField>
    <fullName>ETT_Technician__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Technician</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Work_Schedule</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/ETT_Work_Schedule__c/fields/ETT_Work_Station__c.field-meta.xml
<CustomField>
    <fullName>ETT_Work_Station__c</fullName>
    <label>Work Station</label>
    <referenceTo>ETT_Work_Station__c</referenceTo>
    <relationshipLabel>Work Schedule</relationshipLabel>
    <relationshipName>Work_Schedule</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
    <writeRequiresMasterRead>true</writeRequiresMasterRead>
</CustomField>

unpackaged/main/default/objects/ETT_Work_Station__c/ETT_Work_Station__c.object-meta.xml
<CustomObject>
    <label>Work Station</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Work Station Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Work Stations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/ETT_Work_Station__c/fields/ETT_Station_Code__c.field-meta.xml
<CustomField>
    <fullName>ETT_Station_Code__c</fullName>
    <caseSensitive>true</caseSensitive>
    <encryptionScheme>None</encryptionScheme>
    <label>Station Code</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

unpackaged/main/default/objects/ETT_Work_Station__c/fields/ETT_Station_Type__c.field-meta.xml
<CustomField>
    <fullName>ETT_Station_Type__c</fullName>
    <label>Station Type</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>ETT_Job_Station_Type</valueSetName>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/ETT_Work_Station_Checklist__c/ETT_Work_Station_Checklist__c.object-meta.xml
<CustomObject>
    <label>Work Station Checklist</label>
    <nameField>
        <displayFormat>CL-{0000}</displayFormat>
        <label>Checklist Ref. No</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Work Station Checklists</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

unpackaged/main/default/objects/ETT_Work_Station_Checklist__c/fields/Work_Schedule__c.field-meta.xml
<CustomField>
    <fullName>Work_Schedule__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Work Schedule</label>
    <referenceTo>ETT_Work_Schedule__c</referenceTo>
    <relationshipLabel>Work Station Checklists</relationshipLabel>
    <relationshipName>Work_Station_Checklists</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/ETT_Work_Station_Checklist__c/fields/Work_Station__c.field-meta.xml
<CustomField>
    <fullName>Work_Station__c</fullName>
    <label>Work Station</label>
    <referenceTo>ETT_Work_Station__c</referenceTo>
    <relationshipLabel>Work Station Checklists</relationshipLabel>
    <relationshipName>Work_Station_Checklists</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

unpackaged/main/default/globalValueSets/ETT_Job_Station_Type.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Initial Inspection</fullName>
    </customValue>
    <customValue>
        <fullName>Buffing</fullName>
    </customValue>
    <customValue>
        <fullName>Skiving</fullName>
    </customValue>
    <customValue>
        <fullName>Repair</fullName>
    </customValue>
    <customValue>
        <fullName>Cementing</fullName>
    </customValue>
    <customValue>
        <fullName>Filling</fullName>
    </customValue>
    <customValue>
        <fullName>Thread Preparation</fullName>
    </customValue>
    <customValue>
        <fullName>Building</fullName>
    </customValue>
    <customValue>
        <fullName>Rimming &amp; Enveloping</fullName>
    </customValue>
    <customValue>
        <fullName>Curing</fullName>
    </customValue>
    <customValue>
        <fullName>Final Inspection</fullName>
    </customValue>
    <customValue>
        <fullName>Painting</fullName>
    </customValue>
    <customValue>
        <fullName>Removal of RIM Tube Flap</fullName>
    </customValue>
    <masterLabel>Job Station Type</masterLabel>
</GlobalValueSet>

unpackaged/main/default/classes/ETT_TyreWorkStationHomeCtrlTest.cls
@isTest
public class ETT_TyreWorkStationHomeCtrlTest {
    
    private static testmethod void tyreWorkStation(){
        
        List<Account> accountsList = ETT_TestFactory.createAccounts('TestAccountName', 'Tyre Customer');
        insert accountsList;
        
        Opportunity opp = ETT_TestFactory.createOpportunity('Tyre - Cash Supplier','TestOppName', 'Qualification', system.today().adddays(20), accountsList[0].Id);
        insert opp;
        
        
        List<ETT_Collection_Card__c> collectionCardsList = ETT_TestFactory.createCollectionCards(accountsList[0].Id,opp.Id);
        collectionCardsList[0].ETT_Inspection_Done__c = true;
        insert collectionCardsList;
        
        ETT_Job_Card__c jb = new ETT_Job_Card__c();
        jb.Job_Card_Status__c ='In Progress';
        jb.ETT_Stages__c ='Buffing';
        insert jb;
        
        ETT_Work_Station__c ws = new ETT_Work_Station__c();
        ws.ETT_Station_Type__c = 'Buffing';
        ws.ETT_Station_Code__c ='001';
        insert ws;
        
        ETT_Work_Schedule__c wsch = new ETT_Work_Schedule__c();
        wsch.ETT_Work_Station__c = ws.Id;
        wsch.ETT_Start_time__c = system.now();
        wsch.ETT_End_time__c = system.now()+1;
        wsch.ETT_Technician__c = userinfo.getUserId();
        insert wsch;
        
        ETT_Work_Station_Checklist__c wsc = new ETT_Work_Station_Checklist__c();
        wsc.Work_Schedule__c = wsch.Id;
        wsc.Work_Station__c = ws.Id;
        
        
        ETT_TyreWorkStationHomeCtrl.getUserDetails();
        ETT_TyreWorkStationHomeCtrl.getWorkscheduleInfo();
        ETT_TyreWorkStationHomeCtrl.getJobCardsInfo();
        ETT_TyreWorkStationHomeCtrl.createWorkStationCheckList(wsc);
    }
   private static testmethod void tyreWorkStation2(){
        
        List<Account> accountsList = ETT_TestFactory.createAccounts('TestAccountName', 'Tyre Customer');
        insert accountsList;
        
        Opportunity opp = ETT_TestFactory.createOpportunity('Tyre - Cash Supplier','TestOppName', 'Qualification', system.today().adddays(20), accountsList[0].Id);
        insert opp;
        
        
        List<ETT_Collection_Card__c> collectionCardsList = ETT_TestFactory.createCollectionCards(accountsList[0].Id,opp.Id);
        collectionCardsList[0].ETT_Inspection_Done__c = true;
        insert collectionCardsList;
        
        ETT_Job_Card__c jb = new ETT_Job_Card__c();
        jb.Job_Card_Status__c ='In Progress';
        jb.ETT_Stages__c ='Thread Preparation';
        insert jb;
       
       ETT_Job_Card__c jb1 = new ETT_Job_Card__c();
       jb1.Job_Card_Status__c ='In Progress';
       jb1.ETT_Stages__c ='Thread Preparation';
       jb1.ETT_Main_Job_Card__c =jb.id;
       insert jb1;
        
        ETT_Work_Station__c ws = new ETT_Work_Station__c();
        ws.ETT_Station_Type__c = 'Thread Preparation';
        ws.ETT_Station_Code__c ='001';
        insert ws;
        
        ETT_Work_Schedule__c wsch = new ETT_Work_Schedule__c();
        wsch.ETT_Work_Station__c = ws.Id;
        wsch.ETT_Start_time__c = system.now();
        wsch.ETT_End_time__c = system.now()+1;
        wsch.ETT_Technician__c = userinfo.getUserId();
        insert wsch;
            
      
        ETT_TyreWorkStationHomeCtrl.getJobCardsInfo();
       
    }

}