unpackaged/main/default/objects/ETT_Collection_Card__c/ETT_Collection_Card__c.object-meta.xml
<CustomObject>
    <description>This object is to track the vehicle information and as well as driver information with the help of google map.</description>
    <label>Collection Card</label>
    <nameField>
        <displayFormat>CC-{0000}</displayFormat>
        <label>Collection Card Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Collection Cards</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/ETT_Collection_Card__c/fields/ETT_Accounts__c.field-meta.xml
<CustomField>
    <fullName>ETT_Accounts__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Collection Cards</relationshipLabel>
    <relationshipName>Collection_Cards</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/classes/ETT_Collection_Card_Pdf_Controller_Test.cls
@istest 
public class ETT_Collection_Card_Pdf_Controller_Test {
    @istest public static void insertdata()
    {
        Account accoun = new Account();
      //  accoun.RecordTypeid=Schema.SObjectType.Account.getRecordTypeInfosByDeveloperName().get('Account').getRecordTypeId();
        accoun.Name = 'test corp';
        accoun.phone= '01123123';
        accoun.billingcity='London';
        accoun.billingpostalcode='SW1635HJ';
        accoun.billingcountry='United Kingdom';
        accoun.billingstreet='address 1';
        insert accoun;
        
        list<ETT_Collection_Card__c> lstcc = new list<ETT_Collection_Card__c>();
        ETT_Collection_Card__c cc = new ETT_Collection_Card__c();
        cc.ETT_Accounts__c	= accoun.id;
        lstcc.add(cc);
        insert lstcc;
        
        
        ApexPages.StandardController controlr=new ApexPages.StandardController(cc);
        ApexPages.currentPage().getParameters().put('id',cc.id);
        ETT_Collection_Card_Pdf_Controller ettcc = new ETT_Collection_Card_Pdf_Controller(controlr);
        
    }
    
}