unpackaged/main/default/objects/ETT_Collection_Card__c/ETT_Collection_Card__c.object-meta.xml
<CustomObject>
    <description>This object is to track the vehicle information and as well as driver information with the help of google map.</description>
    <label>Collection Card</label>
    <nameField>
        <displayFormat>CC-{0000}</displayFormat>
        <label>Collection Card Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Collection Cards</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/ETT_Purchase_Order__c/ETT_Purchase_Order__c.object-meta.xml
<CustomObject>
    <label>Purchase Order</label>
    <nameField>
        <displayFormat>PO-{00000}</displayFormat>
        <label>Purchase Order Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Purchase Order</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/ETT_Purchase_Order__c/fields/ETT_Collection_Card__c.field-meta.xml
<CustomField>
    <fullName>ETT_Collection_Card__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Collection Card</label>
    <referenceTo>ETT_Collection_Card__c</referenceTo>
    <relationshipLabel>Purchase Order</relationshipLabel>
    <relationshipName>Purchase_Order</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/classes/ETT_ProcessApprovelRequest.cls
public class ETT_ProcessApprovelRequest {
/*  
    public static void submitForApproval(ETT_Collection_Card__c objCollectionCard){        
        // Create an approval request for  Collection Card        
        Approval.ProcessSubmitRequest req = new Approval.ProcessSubmitRequest();          
        req.setComments('Collection Team collectcted the Collection Details');        
        req.setObjectId(objCollectionCard.id);
        // Submit the approval request for the Collection Card         
        Approval.ProcessResult result = Approval.process(req);        
    }     
*/    
    public static void submitForApproval(ETT_Purchase_Order__c objPurchaseOrder){        
        // Create an approval request for  Collection Card        
        Approval.ProcessSubmitRequest req = new Approval.ProcessSubmitRequest();          
        req.setComments('This is for Purchase Order Confirmation request');        
        req.setObjectId(objPurchaseOrder.id);
        // Submit the approval request for the Collection Card         
        Approval.ProcessResult result = Approval.process(req);        
    }   
    /**
    *Get ProcessInstanceWorkItemId using SOQL
    **/
    public static Id getWorkItemId(Id targetObjectId){
        Id workItemId = null;
        for(ProcessInstanceWorkitem workItem  : [Select p.Id from ProcessInstanceWorkitem p where p.ProcessInstance.TargetObjectId =: targetObjectId]){
            workItemId  =  workItem.Id;
        }
        return workItemId;
    }
    
    //This is for Purchase Order Confirmation request

    /**
    * This method will Approve the opportunity
    **/
    public static void approveRecord(ETT_Purchase_Order__c objPurchaseOrder){
        system.debug('****Invoke ******');
        Approval.ProcessWorkitemRequest req = new Approval.ProcessWorkitemRequest();
        req.setComments('Approving request using Purchase Order Details');
        req.setAction('Approve');        
        Id workItemId = getWorkItemId(objPurchaseOrder.id); 
        if(workItemId == null){
            //opp.addError('Error Occured in CollectionDetails');
        }
        else{
            req.setWorkitemId(workItemId);
            // Submit the request for approval
            Approval.ProcessResult result =  Approval.process(req);
        }
    }
/*
    public static void approveRecord(ETT_Collection_Card__c objCollectionCard){
        system.debug('****Invoke ******');
        Approval.ProcessWorkitemRequest req = new Approval.ProcessWorkitemRequest();
        req.setComments('Approving request using Collection Details');
        req.setAction('Approve');        
        Id workItemId = getWorkItemId(objCollectionCard.id); 
        if(workItemId == null){
            //opp.addError('Error Occured in CollectionDetails');
        }
        else{
            req.setWorkitemId(workItemId);
            // Submit the request for approval
            Approval.ProcessResult result =  Approval.process(req);
        }
    }*/

    /**
    * This method will Reject the opportunity
    **/
    /*public static void rejectRecord(ETT_Collection_Card__c objCollectionCard){
        Approval.ProcessWorkitemRequest req = new Approval.ProcessWorkitemRequest();
        req.setComments('Rejected request using HOO/FM');
        req.setAction('Reject');
        Id workItemId = getWorkItemId(objCollectionCard.id);
        if(workItemId == null){
            //opp.addError('Error Occured in Collection Details');
        }
        else{
            req.setWorkitemId(workItemId);
            // Submit the request for approval
            Approval.ProcessResult result =  Approval.process(req);
        }
    }
*/
}