unpackaged/main/default/objects/ETT_Collection_Card__c/ETT_Collection_Card__c.object-meta.xml
<CustomObject>
    <description>This object is to track the vehicle information and as well as driver information with the help of google map.</description>
    <label>Collection Card</label>
    <nameField>
        <displayFormat>CC-{0000}</displayFormat>
        <label>Collection Card Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Collection Cards</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/ETT_Collection_Card__c/fields/ETT_Accounts__c.field-meta.xml
<CustomField>
    <fullName>ETT_Accounts__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Collection Cards</relationshipLabel>
    <relationshipName>Collection_Cards</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/ETT_Collection_Card__c/fields/ETT_Inspection_Done__c.field-meta.xml
<CustomField>
    <fullName>ETT_Inspection_Done__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Inspection Done</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/objects/ETT_Collection_Card__c/fields/ETT_Status__c.field-meta.xml
<CustomField>
    <fullName>ETT_Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Collection Stage</fullName>
            </value>
            <value>
                <fullName>Inspection Stage</fullName>
            </value>
            <value>
                <fullName>Job Card Stage</fullName>
            </value>
            <value>
                <fullName>Delivery Stage</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/ETT_Collection_Card__c/fields/ETT_Work_Order__c.field-meta.xml
<CustomField>
    <fullName>ETT_Work_Order__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Tyre Collection Request</label>
    <referenceTo>WorkOrder</referenceTo>
    <relationshipLabel>Collection Cards</relationshipLabel>
    <relationshipName>Collection_Cards</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/ETT_Inspection_Card__c/ETT_Inspection_Card__c.object-meta.xml
<CustomObject>
    <description>This is for inspection for the customer who has been requested orders.</description>
    <label>Tyre Inspection Card</label>
    <nameField>
        <displayFormat>IC-{0000}</displayFormat>
        <label>Inspection Card Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Tyre Inspection Cards</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/ETT_Inspection_Card__c/fields/ETT_Collection_Card__c.field-meta.xml
<CustomField>
    <fullName>ETT_Collection_Card__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Collection Card</label>
    <referenceTo>ETT_Collection_Card__c</referenceTo>
    <relationshipName>Inspection_Cards</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/ETT_Inspection_Card__c/fields/ETT_Status__c.field-meta.xml
<CustomField>
    <fullName>ETT_Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Not Inspected</fullName>
                <default>true</default>
                <label>Not Inspected</label>
            </value>
            <value>
                <fullName>Accept</fullName>
            </value>
            <value>
                <fullName>Send Back</fullName>
            </value>
            <value>
                <fullName>Scrap</fullName>
            </value>
            <value>
                <fullName>Accepted/No Warranty</fullName>
            </value>
            <value>
                <fullName>Pending</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/ETT_Tyre_Rejection_Report__c/ETT_Tyre_Rejection_Report__c.object-meta.xml
<CustomObject>
    <label>Tyre Rejection Report</label>
    <nameField>
        <displayFormat>TRR-{0000}</displayFormat>
        <label>Tyre Rejection Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Tyre Rejection Reports</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/ETT_Tyre_Rejection_Report__c/fields/ETT_Collection_Card__c.field-meta.xml
<CustomField>
    <fullName>ETT_Collection_Card__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Collection Card</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/WorkOrderLineItem/fields/ETT_Accounts__c.field-meta.xml
<CustomField>
    <fullName>ETT_Accounts__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Work Order Line Items</relationshipLabel>
    <relationshipName>Work_Order_Line_Items</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/WorkOrderLineItem/fields/ETT_Collection_Card__c.field-meta.xml
<CustomField>
    <fullName>ETT_Collection_Card__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Collection Card</label>
    <referenceTo>ETT_Collection_Card__c</referenceTo>
    <relationshipLabel>Work Order Line Items</relationshipLabel>
    <relationshipName>Work_Order_Line_Items</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/classes/ETT_CollectionCardTriggerHandler_test.cls
@isTest
public class ETT_CollectionCardTriggerHandler_test {
    
    @isTest static void myTest(){
        
        map<Id,ETT_Collection_Card__c> mapOfNewCollectionCards = new map<Id,ETT_Collection_Card__c>();
        map<Id,ETT_Collection_Card__c> mapOfOldCollectionCards = new map<Id,ETT_Collection_Card__c>();
        List<ETT_Collection_Card__c> newList = new List<ETT_Collection_Card__c>();
            
        Account objAcc1 = new Account();
        objAcc1.Name = 'First Account';
        insert objAcc1;
        
        Account objAcc2 = new Account();
        objAcc2.Name = 'Second Account';
        insert objAcc2;
        
        /*WorkOrder objWorkOrder = new WorkOrder();
        objWorkOrder.Status = 'New';
        insert objWorkOrder;
        */
        ETT_Collection_Card__c objCC = new ETT_Collection_Card__c();
        objCC.ETT_Accounts__c = objAcc1.Id;
        objCC.ETT_Inspection_Done__c = true;
        //objCC.ETT_Work_Order__c = objWorkOrder.Id;
        insert objCC;
        
        ETT_Tyre_Rejection_Report__c objRT = new ETT_Tyre_Rejection_Report__c();
        objRT.ETT_Collection_Card__c = objCC.Name;
        insert objRT;
        
        newList.add(objCC);
        
        WorkOrderLineItem obj = new WorkOrderLineItem();
        obj.ETT_Collection_Card__c = objCC.Id;
        //insert obj;
        
        
        
        mapOfOldCollectionCards.put(objCC.Id,objCC);
        
        objCC.ETT_Accounts__c = objAcc2.Id;
        update objCC;
        
        mapOfNewCollectionCards.put(objCC.Id,objCC);
        
        
        ETT_Inspection_Card__c objInspectionCard = new ETT_Inspection_Card__c();
        objInspectionCard.ETT_Status__c = 'Accept';
        objInspectionCard.ETT_Collection_Card__c = objCC.Id;
        insert objInspectionCard;
        
        
        test.startTest();
        
        
        ETT_CollectionCardTriggerHandler.isCollectionInventoryRecursive = true;
        ETT_CollectionCardTriggerHandler.colletionCardHandlerAfterUpdate(mapOfNewCollectionCards, mapOfOldCollectionCards); 
        ETT_CollectionCardTriggerHandler.createJobCard(mapOfNewCollectionCards, mapOfOldCollectionCards);
        ETT_CollectionCardTriggerHandler.sendRejectedTyreDetails(newList);
        ETT_CollectionCardTriggerHandler.updateTyreInventoryStatus(newList, mapOfOldCollectionCards);
        ETT_CollectionCardTriggerHandler.callThisMethod();
        /*
ETT_CollectionCardTriggerHandler WorkOrder = new ETT_CollectionCardTriggerHandler();
ETT_CollectionCardTriggerHandler WorkOrderLineItem = new  ETT_CollectionCardTriggerHandler();
*/
        
        test.stopTest();
        
        
    }
    
    
}