unpackaged/main/default/objects/ETT_Collection_Card__c/ETT_Collection_Card__c.object-meta.xml
<CustomObject>
    <description>This object is to track the vehicle information and as well as driver information with the help of google map.</description>
    <label>Collection Card</label>
    <nameField>
        <displayFormat>CC-{0000}</displayFormat>
        <label>Collection Card Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Collection Cards</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/ETT_Collection_Card__c/fields/ETT_Account__c.field-meta.xml
<CustomField>
    <fullName>ETT_Account__c</fullName>
    <formula>ETT_Service_Appointment__r.Account.Name</formula>
    <label>Account</label>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/ETT_Collection_Card__c/fields/ETT_Accounts__c.field-meta.xml
<CustomField>
    <fullName>ETT_Accounts__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Collection Cards</relationshipLabel>
    <relationshipName>Collection_Cards</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/ETT_Collection_Card__c/fields/ETT_All_Tyre_Rejected__c.field-meta.xml
<CustomField>
    <fullName>ETT_All_Tyre_Rejected__c</fullName>
    <defaultValue>false</defaultValue>
    <label>All Tyre Rejected</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/objects/ETT_Collection_Card__c/fields/ETT_CCL_Created__c.field-meta.xml
<CustomField>
    <fullName>ETT_CCL_Created__c</fullName>
    <defaultValue>false</defaultValue>
    <label>CCL Created</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/objects/ETT_Collection_Card__c/fields/ETT_Check_In__c.field-meta.xml
<CustomField>
    <fullName>ETT_Check_In__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Check In</label>
    <type>DateTime</type>
</CustomField>

unpackaged/main/default/objects/ETT_Collection_Card__c/fields/ETT_Check_Out__c.field-meta.xml
<CustomField>
    <fullName>ETT_Check_Out__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Check Out</label>
    <type>DateTime</type>
</CustomField>

unpackaged/main/default/objects/ETT_Collection_Card__c/fields/ETT_Collection_Date__c.field-meta.xml
<CustomField>
    <fullName>ETT_Collection_Date__c</fullName>
    <defaultValue>Today()</defaultValue>
    <encryptionScheme>None</encryptionScheme>
    <label>Collection Date</label>
    <type>Date</type>
</CustomField>

unpackaged/main/default/objects/ETT_Collection_Card__c/fields/ETT_Collection_Status__c.field-meta.xml
<CustomField>
    <fullName>ETT_Collection_Status__c</fullName>
    <label>Collection Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>New</fullName>
            </value>
            <value>
                <fullName>In Progress</fullName>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
            <value>
                <fullName>Accepted</fullName>
            </value>
            <value>
                <fullName>Rejected</fullName>
            </value>
            <value>
                <fullName>Scheduled</fullName>
            </value>
            <value>
                <fullName>Inspection Cards Created</fullName>
            </value>
            <value>
                <fullName>Inspection Completed</fullName>
            </value>
            <value>
                <fullName>Job Card Created</fullName>
            </value>
            <value>
                <fullName>Check and Report</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/ETT_Collection_Card__c/fields/ETT_Collection_Team_Submitted__c.field-meta.xml
<CustomField>
    <fullName>ETT_Collection_Team_Submitted__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Collection Card Submitted</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/objects/ETT_Collection_Card__c/fields/ETT_Completed__c.field-meta.xml
<CustomField>
    <fullName>ETT_Completed__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Completed</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/objects/ETT_Collection_Card__c/fields/ETT_Contact__c.field-meta.xml
<CustomField>
    <fullName>ETT_Contact__c</fullName>
    <formula>ETT_Service_Appointment__r.Contact.LastName</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Contact Person Name</label>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/ETT_Collection_Card__c/fields/ETT_Create_Job_Card__c.field-meta.xml
<CustomField>
    <fullName>ETT_Create_Job_Card__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Create Job Card</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/objects/ETT_Collection_Card__c/fields/ETT_Estimation_Completed_By_Fm__c.field-meta.xml
<CustomField>
    <fullName>ETT_Estimation_Completed_By_Fm__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Estimation Completed By FM</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/objects/ETT_Collection_Card__c/fields/ETT_Estimation_Completed_By_HOO__c.field-meta.xml
<CustomField>
    <fullName>ETT_Estimation_Completed_By_HOO__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Estimation Completed By HOO</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/objects/ETT_Collection_Card__c/fields/ETT_Factory_Manager_Approved__c.field-meta.xml
<CustomField>
    <fullName>ETT_Factory_Manager_Approved__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Factory Manager Approved</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/objects/ETT_Collection_Card__c/fields/ETT_Inspection_Done__c.field-meta.xml
<CustomField>
    <fullName>ETT_Inspection_Done__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Inspection Done</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/objects/ETT_Collection_Card__c/fields/ETT_Is_Active__c.field-meta.xml
<CustomField>
    <fullName>ETT_Is_Active__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Is Active</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/objects/ETT_Collection_Card__c/fields/ETT_Job_Card_Done__c.field-meta.xml
<CustomField>
    <fullName>ETT_Job_Card_Done__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Job Card Done</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/objects/ETT_Collection_Card__c/fields/ETT_Location__c.field-meta.xml
<CustomField>
    <fullName>ETT_Location__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Location</label>
    <type>TextArea</type>
</CustomField>

unpackaged/main/default/objects/ETT_Collection_Card__c/fields/ETT_Receptionist_Acceptance__c.field-meta.xml
<CustomField>
    <fullName>ETT_Receptionist_Acceptance__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Receptionist Acceptance</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/objects/ETT_Collection_Card__c/fields/ETT_Sales_Acceptance__c.field-meta.xml
<CustomField>
    <fullName>ETT_Sales_Acceptance__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Sales Acceptance</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/objects/ETT_Collection_Card__c/fields/ETT_Status__c.field-meta.xml
<CustomField>
    <fullName>ETT_Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Collection Stage</fullName>
            </value>
            <value>
                <fullName>Inspection Stage</fullName>
            </value>
            <value>
                <fullName>Job Card Stage</fullName>
            </value>
            <value>
                <fullName>Delivery Stage</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/ETT_Collection_Card__c/fields/ETT_Submitted_For_Approval__c.field-meta.xml
<CustomField>
    <fullName>ETT_Submitted_For_Approval__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Submitted For Approval</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/objects/ETT_Delivery_Note__c/ETT_Delivery_Note__c.object-meta.xml
<CustomObject>
    <label>Delivery Note</label>
    <nameField>
        <displayFormat>DNN-{0000}</displayFormat>
        <label>Delivery Note Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Delivery Notes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/ETT_Delivery_Note__c/fields/ETT_Account__c.field-meta.xml
<CustomField>
    <fullName>ETT_Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Delivery Notes</relationshipLabel>
    <relationshipName>Delivery_Notes</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/ETT_Delivery_Note__c/fields/ETT_Collection_Card__c.field-meta.xml
<CustomField>
    <fullName>ETT_Collection_Card__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Collection Card</label>
    <referenceTo>ETT_Collection_Card__c</referenceTo>
    <relationshipLabel>Delivery Notes</relationshipLabel>
    <relationshipName>Delivery_Notes</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/ETT_Inspection_Card__c/ETT_Inspection_Card__c.object-meta.xml
<CustomObject>
    <description>This is for inspection for the customer who has been requested orders.</description>
    <label>Tyre Inspection Card</label>
    <nameField>
        <displayFormat>IC-{0000}</displayFormat>
        <label>Inspection Card Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Tyre Inspection Cards</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/ETT_Inspection_Card__c/fields/ETT_Account__c.field-meta.xml
<CustomField>
    <fullName>ETT_Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipName>Inspection_Cards</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/ETT_Inspection_Card__c/fields/ETT_Chalk_Crayon_Yellow__c.field-meta.xml
<CustomField>
    <fullName>ETT_Chalk_Crayon_Yellow__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Chalk / Crayon - Yellow</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/objects/ETT_Inspection_Card__c/fields/ETT_Collection_Card__c.field-meta.xml
<CustomField>
    <fullName>ETT_Collection_Card__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Collection Card</label>
    <referenceTo>ETT_Collection_Card__c</referenceTo>
    <relationshipName>Inspection_Cards</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/ETT_Inspection_Card__c/fields/ETT_Contact__c.field-meta.xml
<CustomField>
    <fullName>ETT_Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Tyre Inspection Cards</relationshipLabel>
    <relationshipName>Tyre_Inspection_Cards</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/ETT_Inspection_Card__c/fields/ETT_Cutting_Player__c.field-meta.xml
<CustomField>
    <fullName>ETT_Cutting_Player__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Cutting Player</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/objects/ETT_Inspection_Card__c/fields/ETT_Electrical_Prob_In_Working_Condition__c.field-meta.xml
<CustomField>
    <fullName>ETT_Electrical_Prob_In_Working_Condition__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Electrical Prob In Working Condition</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/objects/ETT_Inspection_Card__c/fields/ETT_Handheld_Drop_Light__c.field-meta.xml
<CustomField>
    <fullName>ETT_Handheld_Drop_Light__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Handheld Drop Light</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/objects/ETT_Inspection_Card__c/fields/ETT_Industrial_Vacuum_Cleaner__c.field-meta.xml
<CustomField>
    <fullName>ETT_Industrial_Vacuum_Cleaner__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Industrial Vacuum Cleaner</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/objects/ETT_Inspection_Card__c/fields/ETT_Knife__c.field-meta.xml
<CustomField>
    <fullName>ETT_Knife__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Knife</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/objects/ETT_Inspection_Card__c/fields/ETT_Nail_Remover__c.field-meta.xml
<CustomField>
    <fullName>ETT_Nail_Remover__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Nail Remover</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/objects/ETT_Inspection_Card__c/fields/ETT_Poking_Screwdriver__c.field-meta.xml
<CustomField>
    <fullName>ETT_Poking_Screwdriver__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Poking Screwdriver</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/objects/ETT_Inspection_Card__c/fields/ETT_Spiral_Cement_Tool__c.field-meta.xml
<CustomField>
    <fullName>ETT_Spiral_Cement_Tool__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Spiral Cement Tool</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/objects/ETT_Inspection_Card__c/fields/ETT_Spreader_Light_Condition__c.field-meta.xml
<CustomField>
    <fullName>ETT_Spreader_Light_Condition__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Spreader Light Condition</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/objects/ETT_Inspection_Card__c/fields/ETT_Staple_Gun__c.field-meta.xml
<CustomField>
    <fullName>ETT_Staple_Gun__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Staple Gun</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/objects/ETT_Inspection_Card__c/fields/ETT_Status__c.field-meta.xml
<CustomField>
    <fullName>ETT_Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Not Inspected</fullName>
                <default>true</default>
                <label>Not Inspected</label>
            </value>
            <value>
                <fullName>Accept</fullName>
            </value>
            <value>
                <fullName>Send Back</fullName>
            </value>
            <value>
                <fullName>Scrap</fullName>
            </value>
            <value>
                <fullName>Accepted/No Warranty</fullName>
            </value>
            <value>
                <fullName>Pending</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/classes/ETT_DeliveryNotePrintUtilityTest.cls
@isTest
public class ETT_DeliveryNotePrintUtilityTest {
    
    @isTest
    public static void testCase1(){
        Account objAcc1 = new Account();
        objAcc1.Name = 'First Account';
        insert objAcc1;
        Contact con=new Contact();
        con.LastName = 'Test';
        con.AccountId=objAcc1.id;
        insert con;
        ETT_Collection_Card__c ett_collection_card = new ETT_Collection_Card__c(
            CurrencyIsoCode = 'AED',
            ETT_Accounts__c = objAcc1.id,
            ETT_All_Tyre_Rejected__c = false,
            ETT_CCL_Created__c = false,
            ETT_Check_In__c = DateTime.newInstance(2020,12,14,7,439,26392),
            ETT_Check_Out__c = DateTime.newInstance(2020,12,14,7,440,26438),
            ETT_Collection_Date__c = Date.newInstance(2020,12,07),
            ETT_Collection_Status__c = 'Accepted',
            ETT_Collection_Team_Submitted__c = true,
            ETT_Completed__c = false,
            ETT_Create_Job_Card__c = false,
            ETT_Estimation_Completed_By_Fm__c = false,
            ETT_Estimation_Completed_By_HOO__c = false,
            ETT_Factory_Manager_Approved__c = false,
            ETT_Head_Of_Operation_Approved__c = false,
            ETT_Inspection_Done__c = true,
            ETT_Job_Card_Done__c = false,
            ETT_Location__c = 'Dubai',
            ETT_Receptionist_Acceptance__c = false,
            ETT_Sales_Acceptance__c = false,
            //ETT_Status__c = 'Send Back',
            ETT_Submitted_For_Approval__c = false,
            ETT_Is_Active__c = false);
        
        insert ett_collection_card;
        
        ETT_Inspection_Card__c ett_inspection_card = new ETT_Inspection_Card__c(
            CurrencyIsoCode = 'AED',
            ETT_Account__c = objAcc1.id,
            ETT_Chalk_Crayon_Yellow__c = true,
            ETT_Collection_Card__c = ett_collection_card.id,
            ETT_Contact__c = con.id,
            ETT_Cutting_Player__c = true,
            ETT_Electrical_Prob_In_Working_Condition__c = true,
            ETT_Handheld_Drop_Light__c = true,
            ETT_Industrial_Vacuum_Cleaner__c = true,
            ETT_Knife__c = true,
            ETT_Nail_Remover__c = true,
            ETT_Poking_Screwdriver__c = true,
            ETT_Spiral_Cement_Tool__c = true,
            ETT_Spreader_Light_Condition__c = true,
            ETT_Staple_Gun__c = true,
            ETT_Status__c = 'Send Back',
            ETT_Tyre_Life__c = '1',
            ETT_Tyre_Lift_In_Working_Condition__c = true,
            ETT_Tyre_Serial_Number__c = '1234',
            ETT_Tyre_Spreader_In_Working_Condition__c = true,
            ETT_Tyre_Tapping_Tool__c = true);
        
        insert ett_inspection_card;
        
        ETT_Delivery_Note__c ett_delivery_note = new ETT_Delivery_Note__c(
            CurrencyIsoCode = 'AED',
            ETT_Account__c = objAcc1.id,
            ETT_Is_Delivery_Appointment_Booked__c = false,
        ETT_Collection_Card__c = ett_collection_card.id,
        Approved_By__c = userinfo.getUserId());
		
        insert ett_delivery_note;
        Test.startTest();
        ETT_DeliveryNotePrintUtility.fetchDeliveryNotes(objAcc1.id);
        Test.stopTest();
    }
}