unpackaged/main/default/objects/CICO_Child_Asset__c/CICO_Child_Asset__c.object-meta.xml
<CustomObject>
    <label>Child Asset</label>
    <nameField>
        <displayFormat>CA-{000000}</displayFormat>
        <label>Asset Ref No</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Child Assets</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/CICO_Child_Asset__c/fields/Asset_Description__c.field-meta.xml
<CustomField>
    <fullName>Asset_Description__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Asset Description</label>
    <type>TextArea</type>
</CustomField>

unpackaged/main/default/objects/CICO_Child_Asset__c/fields/Check_Out__c.field-meta.xml
<CustomField>
    <fullName>Check_Out__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Check Out</label>
    <referenceTo>CICO_Check_Out__c</referenceTo>
    <relationshipLabel>Child Assets</relationshipLabel>
    <relationshipName>Child_Assets</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/CICO_Child_Asset__c/fields/Issued__c.field-meta.xml
<CustomField>
    <fullName>Issued__c</fullName>
    <defaultValue>true</defaultValue>
    <label>Issued</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/objects/CICO_Child_Asset__c/fields/Received__c.field-meta.xml
<CustomField>
    <fullName>Received__c</fullName>
    <defaultValue>true</defaultValue>
    <label>Received</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/classes/CICO_checkOutPdfCtrl.cls
public class CICO_checkOutPdfCtrl {
  
    public string markedDiagramId{get;set;}
    public String signId{get;set;}
    public list<CICO_Child_Asset__c> childAsset{get;set;} 
    
    public CICO_checkOutPdfCtrl(ApexPages.StandardController controller) {
    
        String recId = Apexpages.currentPage().getParameters().get('id');
        
        
         for(ContentDocumentLink  cd : [SELECT id,ContentDocument.Title, ContentDocument.LatestPublishedVersionId FROM ContentDocumentLink WHERE id != null AND LinkedEntityId=:recId ]){
            
            system.debug('--'+cd.ContentDocument.Title);
            
            if(cd.ContentDocument.Title.contains('MarkedDiagram')){
               
               markedDiagramId= cd.ContentDocument.LatestPublishedVersionId;
            
            }
            if(cd.ContentDocument.Title.contains('Sign')){
              signId = cd.ContentDocument.LatestPublishedVersionId;
            }
            
        }
        
       childAsset = [select id,Name,Asset_Description__c,Issued__c,Received__c from CICO_Child_Asset__c where Check_Out__c=:recId];
    }
}