unpackaged/main/default/objects/ETIN_Claim__c/ETIN_Claim__c.object-meta.xml
<CustomObject>
    <label>Claim</label>
    <nameField>
        <displayFormat>CL-{000000}</displayFormat>
        <label>Claim Ref Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Claims</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/ETIN_Claim__c/fields/Accident_Date__c.field-meta.xml
<CustomField>
    <fullName>Accident_Date__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Incident Date</label>
    <type>Date</type>
</CustomField>

unpackaged/main/default/objects/ETIN_Claim__c/fields/Child_Bill_Value__c.field-meta.xml
<CustomField>
    <fullName>Child_Bill_Value__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Child Bill Value</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

unpackaged/main/default/objects/ETIN_Claim__c/fields/Insured_Value__c.field-meta.xml
<CustomField>
    <fullName>Insured_Value__c</fullName>
    <label>Insured Value</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

unpackaged/main/default/objects/ETIN_Claim__c/fields/Purchase_Date__c.field-meta.xml
<CustomField>
    <fullName>Purchase_Date__c</fullName>
    <description>hide this field</description>
    <formula>Vehicle_Master__r.Purchase_Date__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Purchase Date</label>
    <type>Date</type>
</CustomField>

unpackaged/main/default/objects/ETIN_Claim__c/fields/Purchase_Value__c.field-meta.xml
<CustomField>
    <fullName>Purchase_Value__c</fullName>
    <description>Hide this field</description>
    <formula>Vehicle_Master__r.Purchase_Value__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Purchase Value</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

unpackaged/main/default/objects/ETIN_Claim__c/fields/VehicleMasterkey__c.field-meta.xml
<CustomField>
    <fullName>VehicleMasterkey__c</fullName>
    <formula>Vehicle_Master__r.Vehicle_Type_Desc__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>VehicleMasterkey</label>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/ETIN_Claim__c/recordTypes/Vehicle_Insurance.recordType-meta.xml
<RecordType>
    <fullName>Vehicle_Insurance</fullName>
    <active>true</active>
    <label>Vehicle Insurance</label>
</RecordType>

unpackaged/main/default/objects/Insurance_Rule_Master__c/Insurance_Rule_Master__c.object-meta.xml
<CustomObject>
    <label>Insurance Rule Master</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Insurance Rule Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Insurance Rule Master</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Insurance_Rule_Master__c/fields/AC_NonAC__c.field-meta.xml
<CustomField>
    <fullName>AC_NonAC__c</fullName>
    <label>AC/Non-AC</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>AC</fullName>
            </value>
            <value>
                <fullName>Non-Ac</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Insurance_Rule_Master__c/fields/Applied_Date__c.field-meta.xml
<CustomField>
    <fullName>Applied_Date__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Applied Date</label>
    <type>Date</type>
</CustomField>

unpackaged/main/default/objects/Insurance_Rule_Master__c/fields/Depreciation_Years__c.field-meta.xml
<CustomField>
    <fullName>Depreciation_Years__c</fullName>
    <label>Insurance Depreciation Years</label>
    <precision>2</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

unpackaged/main/default/objects/Insurance_Rule_Master__c/fields/Insurance_Floor_Value__c.field-meta.xml
<CustomField>
    <fullName>Insurance_Floor_Value__c</fullName>
    <label>Insurance Floor Value</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

unpackaged/main/default/objects/Insurance_Rule_Master__c/fields/Insurance_Limit__c.field-meta.xml
<CustomField>
    <fullName>Insurance_Limit__c</fullName>
    <label>Insurance Limit %</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Percent</type>
</CustomField>

unpackaged/main/default/objects/Insurance_Rule_Master__c/fields/Total_Loss__c.field-meta.xml
<CustomField>
    <fullName>Total_Loss__c</fullName>
    <label>Total Loss %</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

unpackaged/main/default/objects/Insurance_Rule_Master__c/fields/Type_Description__c.field-meta.xml
<CustomField>
    <fullName>Type_Description__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Type Description</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Insurance_Rule_Master__c/fields/Type_ID__c.field-meta.xml
<CustomField>
    <fullName>Type_ID__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Type ID</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/classes/ETVIN_CompensatationInsuredCalHandler.cls
/*Author -Janardhan Muddana
 *Description- this is used to calculate compenstation value and insured value for vehicle insurance
 * 
 * 
 */

public class ETVIN_CompensatationInsuredCalHandler {

    
    public static void calculateInsuredAndCompenstationVal(list<ETIN_Claim__c> trgVal, map<id,ETIN_Claim__c> newMap,map<id,ETIN_Claim__c> oldMap){
        
       set<id> claimIds = new set<id>();
       
      /* map<string,Insurance_Rule_Master__c> mapIDvsRow = new  map<string,Insurance_Rule_Master__c>();
           
        for(Insurance_Rule_Master__c rule : [select id,name,AC_NonAC__c,Applied_Date__c,Total_Loss__c,Depreciation_Years__c,Insurance_Floor_Value__c,Insurance_Limit__c,Type_Description__c,Type_ID__c from Insurance_Rule_Master__c]){
            if(rule.Type_Description__c != null)
            mapIDvsRow.put(rule.Type_Description__c.toLowercase(),rule);
        }
         
      
        Id ClaimrecordTypeId =   Schema.SObjectType.ETIN_Claim__c.getRecordTypeInfosByDeveloperName().get('Vehicle_Insurance').getRecordTypeId();
        //[select id,name,RecordTypeId,Purchase_Date__c,Accident_Date__c,Insured_Value__c,Child_Bill_Value__c,Purchase_Value__c,VehicleMasterkey__c from ETIN_Claim__c where id=:newMap.keySet() ]){
            
        for(ETIN_Claim__c cl : trgVal){
            
            
            if(ClaimrecordTypeId == cl.RecordTypeId){
                
                if(cl.Accident_Date__c!= null && cl.VehicleMasterkey__c != null && cl.Purchase_Value__c != null && cl.Purchase_Date__c != null){
                    date accidentDate = cl.Accident_Date__c;
                    date accidentYearModDate = date.newInstance(accidentDate.year(), 1, 1); //consider 1st month and 1st date at accident year
                    integer noOfmonthsAsofAccident = cl.Purchase_Date__c.monthsBetween(accidentYearModDate);
                   
                    //system.debug('--Mod'+accidentYearModDate);
                    //system.debug('--no of months'+noOfmonthsAsofAccident);
                    
                    if(mapIDvsRow.containskey(cl.VehicleMasterkey__c.toLowercase())){
                       //Insured value calculations 
                        decimal lifeOfMonths  = mapIDvsRow.get(cl.VehicleMasterkey__c.toLowercase()).Depreciation_Years__c*12;
                        system.debug('--life'+lifeOfMonths);
                        decimal monthlyInsurance = cl.Purchase_Value__c/lifeOfMonths;
                        system.debug('--monthIns'+monthlyInsurance);
                        
                         decimal remaingLifeMonths =  lifeOfMonths - noOfmonthsAsofAccident;
                         decimal childBill;
                        if(remaingLifeMonths >= 0 && monthlyInsurance != null){
                            if( cl.Child_Bill_Value__c != null){
                               childBill = cl.Child_Bill_Value__c;
                            }else {
                                childBill = 0;
                            }
                            
                            decimal insuredValue = (monthlyInsurance*remaingLifeMonths)+ childBill;
                            system.debug('-insval-'+insuredValue);
                            
                            if(insuredValue <= mapIDvsRow.get(cl.VehicleMasterkey__c.toLowercase()).Insurance_Floor_Value__c){
                                
                                 cl.Insured_Value__c = mapIDvsRow.get(cl.VehicleMasterkey__c.toLowercase()).Insurance_Floor_Value__c;
                                
                            }else {
                                
                                 cl.Insured_Value__c = insuredValue.setscale(3);
                                
                            }
                            //compenstation Calculation
                            decimal daysbwAccmodAcc = accidentYearModDate.daysBetween(cl.Accident_Date__c);
                            decimal depPercentage = mapIDvsRow.get(cl.VehicleMasterkey__c.toLowercase()).Total_Loss__c;
                            
                            system.debug('--daysbwAccmodAcc*'+daysbwAccmodAcc);
                            system.debug('--depPercentage'+depPercentage);
                           
                            decimal compenstationval = insuredValue - ((daysbwAccmodAcc/365)*insuredValue*depPercentage);
                            
                            cl.Claim_Amount__c = compenstationval.setscale(3);
                        }
                        
                        
                    }
                    
                }
                
                
            }
            
           
        }*/
         
    }
}