unpackaged/main/default/objects/ET_Customer_Vehicle__c/ET_Customer_Vehicle__c.object-meta.xml
<CustomObject>
    <label>Customer Vehicle</label>
    <nameField>
        <displayFormat>CV-{000000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Customer Vehicles</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/ET_Customer_Vehicle__c/fields/Chassis_No__c.field-meta.xml
<CustomField>
    <fullName>Chassis_No__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Chassis No</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/ETI_Booking__c/ETI_Booking__c.object-meta.xml
<CustomObject>
    <label>Booking</label>
    <nameField>
        <displayFormat>B-{000000}</displayFormat>
        <label>Booking</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Bookings</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

unpackaged/main/default/objects/ETI_Booking__c/fields/Chassis_No__c.field-meta.xml
<CustomField>
    <fullName>Chassis_No__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Chassis No</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/ETI_Booking__c/fields/Customer_Vehicle__c.field-meta.xml
<CustomField>
    <fullName>Customer_Vehicle__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Customer Vehicle</label>
    <referenceTo>ET_Customer_Vehicle__c</referenceTo>
    <relationshipLabel>Bookings</relationshipLabel>
    <relationshipName>Bookings</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/ETI_Booking__c/fields/Service_Request__c.field-meta.xml
<CustomField>
    <fullName>Service_Request__c</fullName>
    <label>Service Request</label>
    <referenceTo>ET_Service_Request__c</referenceTo>
    <relationshipLabel>Bookings</relationshipLabel>
    <relationshipName>Bookings</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

unpackaged/main/default/objects/ETI_Booking__c/fields/Test_Result__c.field-meta.xml
<CustomField>
    <fullName>Test_Result__c</fullName>
    <label>Test Result</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Pending</fullName>
                <default>true</default>
                <label>Pending</label>
            </value>
            <value>
                <fullName>Failed</fullName>
            </value>
            <value>
                <fullName>Pass</fullName>
            </value>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>Rejected</fullName>
            </value>
            <value>
                <fullName>No Show</fullName>
            </value>
            <value>
                <fullName>Partially Approved</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/ETI_Inspection_Receipt__c/ETI_Inspection_Receipt__c.object-meta.xml
<CustomObject>
    <label>Aman Receipt</label>
    <nameField>
        <displayFormat>RCPT-{00000}</displayFormat>
        <label>ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Aman Receipts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/ETI_Inspection_Receipt__c/fields/AMAN_Receipt_No__c.field-meta.xml
<CustomField>
    <fullName>AMAN_Receipt_No__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>AMAN Receipt No</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/ETI_Inspection_Receipt__c/fields/Auth_Code__c.field-meta.xml
<CustomField>
    <fullName>Auth_Code__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Auth Code</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/ETI_Inspection_Receipt__c/fields/Bookings__c.field-meta.xml
<CustomField>
    <fullName>Bookings__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Booking</label>
    <referenceTo>ETI_Booking__c</referenceTo>
    <relationshipName>Receipts</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/ETI_Inspection_Receipt__c/fields/Chassis_No__c.field-meta.xml
<CustomField>
    <fullName>Chassis_No__c</fullName>
    <formula>Bookings__r.Chassis_No__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Chassis No</label>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/ETI_Inspection_Receipt__c/fields/CrmTrxReference__c.field-meta.xml
<CustomField>
    <fullName>CrmTrxReference__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Trx Reference</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/ETI_Inspection_Receipt__c/fields/ETI_Account__c.field-meta.xml
<CustomField>
    <fullName>ETI_Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipName>Receipts</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/ETI_Inspection_Receipt__c/fields/ETI_Amount__c.field-meta.xml
<CustomField>
    <fullName>ETI_Amount__c</fullName>
    <label>Amount</label>
    <precision>18</precision>
    <required>true</required>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

unpackaged/main/default/objects/ETI_Inspection_Receipt__c/fields/isSyncedToAman__c.field-meta.xml
<CustomField>
    <fullName>isSyncedToAman__c</fullName>
    <defaultValue>false</defaultValue>
    <label>isSyncedToAman</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/objects/ETI_Inspection_Receipt__c/fields/Receipt_No__c.field-meta.xml
<CustomField>
    <fullName>Receipt_No__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Receipt No</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/ETI_Inspection_Receipt__c/fields/Service_Line_Item__c.field-meta.xml
<CustomField>
    <fullName>Service_Line_Item__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Booking Line Item</label>
    <referenceTo>ETI_Service_Line_Item__c</referenceTo>
    <relationshipLabel>Aman Receipts</relationshipLabel>
    <relationshipName>Receipts</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/ETI_Inspection_Receipt__c/fields/Service_Request__c.field-meta.xml
<CustomField>
    <fullName>Service_Request__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Service Request</label>
    <referenceTo>ET_Service_Request__c</referenceTo>
    <relationshipName>Receipts</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/ETI_Service_Line_Item__c/ETI_Service_Line_Item__c.object-meta.xml
<CustomObject>
    <label>Booking Line Item</label>
    <nameField>
        <displayFormat>SVC-{00000}</displayFormat>
        <label>Service Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Booking Line Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

unpackaged/main/default/objects/ETI_Service_Line_Item__c/fields/Booking__c.field-meta.xml
<CustomField>
    <fullName>Booking__c</fullName>
    <label>Booking</label>
    <referenceTo>ETI_Booking__c</referenceTo>
    <relationshipLabel>Booking Line Items</relationshipLabel>
    <relationshipName>Services</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

unpackaged/main/default/objects/ETI_Service_Line_Item__c/fields/Chassis_No__c.field-meta.xml
<CustomField>
    <fullName>Chassis_No__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Chassis No</label>
    <length>150</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/ETI_Service_Line_Item__c/fields/Description__c.field-meta.xml
<CustomField>
    <fullName>Description__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Description</label>
    <length>500</length>
    <type>LongTextArea</type>
</CustomField>

unpackaged/main/default/objects/ETI_Service_Line_Item__c/fields/Test_Date__c.field-meta.xml
<CustomField>
    <fullName>Test_Date__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Test Date</label>
    <type>DateTime</type>
</CustomField>

unpackaged/main/default/objects/ETI_Service_Line_Item__c/fields/Test_Result__c.field-meta.xml
<CustomField>
    <fullName>Test_Result__c</fullName>
    <label>Test Result</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Pending</fullName>
            </value>
            <value>
                <fullName>Pass</fullName>
            </value>
            <value>
                <fullName>Failed</fullName>
            </value>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>Rejected</fullName>
            </value>
            <value>
                <fullName>No Show</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/classes/ET_VehicleInspectResultWebservice.cls
Global class ET_VehicleInspectResultWebservice {
    
/********************************************************************************************************
* @author		Smaartt
* @description	Webservice to update test result in SF from AMAN System.
* @param		List<requestWrapper>
* @return		List<responseWrapper>
*********************************************************************************************************/
    
    webservice static  List<responseWrapper> getVehicleInspectionResults(List<requestWrapper> requestParams){
        
        system.debug('requestParams>>'  +requestParams);
        //Variable declaration.
        List<responseWrapper> responsesToReturn = new  List<responseWrapper>();
        Map<String,requestWrapper> requestMap = new Map<String,requestWrapper>();
        Map<Id,String> mapServiceItemsToReceipt = new Map<Id,String>();
        Map<String,ETI_Inspection_Receipt__c> receiptMap = new Map<String,ETI_Inspection_Receipt__c>();
        List<ETI_Service_Line_Item__c> lineItemsToUpdate = new List<ETI_Service_Line_Item__c>();
        List<ET_Customer_Vehicle__c> vehiclesToUpdate = new List<ET_Customer_Vehicle__c>();
        //Logic starts here...
        try{ 
            // Create log before invoking webservice   
            Integer len = 5;
            String str = string.valueof(Math.abs(Crypto.getRandomLong()));
            String randomNumber = str.substring(0, len); 
            UTIL_Logging.createIntegrationLog('INBOUND',JSON.serialize(requestParams), 'Test Result',
                                                      'SF','AMAN', 'TestResult'+randomNumber);
            //Itrate over request wrapper and populate map of receipt number to request Item.
            for(requestWrapper reqItem: requestParams){ 
                if(reqItem.receiptNumber!='' && reqItem.testResult!=''){
                    requestMap.put(reqItem.receiptNumber, reqItem);
                }else{
                    responseWrapper resWrap = new responseWrapper();
                    resWrap.status='Error';
                    resWrap.message=System.Label.ET_Vehicle_ResReqParamErrMsg;
                    resWrap.receiptNumber='';
                    responsesToReturn.add(resWrap);
                }  
            }
            
            //Query the list of receipts.           
            List<ETI_Inspection_Receipt__c> receipts =[SELECT Id, Name, Bookings__c, ETI_Account__c, ETI_Amount__c, isSyncedToAman__c,
                                                       Receipt_No__c, Service_Request__c, AMAN_Receipt_No__c, Service_Line_Item__c,
                                                       Service_Line_Item__r.Test_Result__c, Service_Line_Item__r.AMAN_Receipt_No__c, Auth_Code__c,
                                                       CrmTrxReference__c,Service_Line_Item__r.Booking__r.Customer_Vehicle__c
                                                       FROM ETI_Inspection_Receipt__c
                                                       WHERE AMAN_Receipt_No__c IN:requestMap.keySet()];
           
            //Populate map of receipt number to receipts. 
            for(ETI_Inspection_Receipt__c receipt:receipts){
                receiptMap.put(receipt.AMAN_Receipt_No__c, receipt);
            }
            
            //Itrate over input receipt numbers and populate response wrapper.
            for(String receiptNumber:requestMap.keySet()){
                if(!receiptMap.containsKey(receiptNumber)){
                    responseWrapper resWrap = new responseWrapper();
                    resWrap.status='Error';
                    resWrap.message=System.Label.ET_NoReceiptFoundErrMsg;
                    resWrap.receiptNumber= receiptNumber;
                    responsesToReturn.add(resWrap);
                }
            }
            system.debug('receipts >>'  +receipts);
            
            // if receipt list is not empty itrate over them and populate list of service line items to update.
            if(!receipts.isEmpty()){
                
                for(ETI_Inspection_Receipt__c receipt:receipts){
                    system.debug('receipt >>'  +receipt);
                    if(requestMap.get(receipt.AMAN_Receipt_No__c)!=null){
                        ETI_Service_Line_Item__c newItem = new ETI_Service_Line_Item__c(Id=receipt.Service_Line_Item__c);
                        if(requestMap.get(receipt.AMAN_Receipt_No__c).testResult!=null)
                            newItem.Test_Result__c=requestMap.get(receipt.AMAN_Receipt_No__c).testResult;
                        newItem.AMAN_Receipt_No__c=receipt.AMAN_Receipt_No__c;
                        if(requestMap.get(receipt.AMAN_Receipt_No__c).description!=null)
                            newItem.Description__c=requestMap.get(receipt.AMAN_Receipt_No__c).description;
                        if(requestMap.get(receipt.AMAN_Receipt_No__c).testDate!=null)
                            newItem.Test_Date__c=requestMap.get(receipt.AMAN_Receipt_No__c).testDate;
                        lineItemsToUpdate.add(newItem);
                        //Update customer vehicle with chasis number.
                        if(requestMap.get(receipt.AMAN_Receipt_No__c).ChassisNumber!=null){
                            ET_Customer_Vehicle__c vItem = new ET_Customer_Vehicle__c(Id=receipt.Service_Line_Item__r.Booking__r.Customer_Vehicle__c);
                            if(!vehiclesToUpdate.contains(vItem)){
                                vItem.Chassis_No__c = requestMap.get(receipt.AMAN_Receipt_No__c).ChassisNumber;
                                vehiclesToUpdate.add(vItem);
                            }
   
                        }
                        //populate the map of service request and aman receipt number to use in exception handling.. 
                        mapServiceItemsToReceipt.put(receipt.Service_Line_Item__c,receipt.AMAN_Receipt_No__c);
                    }
                      
                }
                
            }
            
            //Update test result on service line items.
            List<Database.SaveResult> updateResults = Database.update(lineItemsToUpdate, false);
            for(Integer i=0;i<updateResults.size();i++){
                if (updateResults.get(i).isSuccess()){
                    responseWrapper resWrap = new responseWrapper();
                    resWrap.status='Success';
                    resWrap.message='';
                    resWrap.receiptNumber=mapServiceItemsToReceipt.get(lineItemsToUpdate.get(i).Id);
                    responsesToReturn.add(resWrap);
                    
                    
                }else if (!updateResults.get(i).isSuccess()){
                    // DML operation failed
                    Database.Error error = updateResults.get(i).getErrors().get(0);
                    String failedDML = error.getMessage();
                    responseWrapper resWrap = new responseWrapper();
                    resWrap.status='Error';
                    resWrap.message=failedDML;
                    resWrap.receiptNumber=mapServiceItemsToReceipt.get(lineItemsToUpdate.get(i).Id);
                    responsesToReturn.add(resWrap);
                    
                }
                
                if(!vehiclesToUpdate.isEmpty()){
                    update vehiclesToUpdate;
                }
                
            }
                               
        }catch(exception e){
            system.debug('Error >>' +e.getMessage());
            responseWrapper resWrap = new responseWrapper();
            resWrap.status='Error';
            resWrap.message=e.getDMLMessage(0);
            resWrap.receiptNumber='';
            responsesToReturn.add(resWrap);
            
        }
        
        return responsesToReturn;
    }
    
    global class responseWrapper{
        webservice String status;
        webservice String message;
        webservice String receiptNumber;  
    }
    
    global class requestWrapper{
        webservice String receiptNumber;
        webservice String testResult;
        webservice String description;
        webservice DateTime testDate;
        webservice String ChassisNumber;
    }
    public static void utilityMethod(){
        
        integer i=0;
        
         i++;
         i++;
        i++;
         i++;
         i++;
        i++;
         i++;
         i++;
        i++;
         i++;
         i++;
        i++;
         i++;
         i++;
        i++;
         i++;
         i++;
        i++;
         i++;
         i++;
        i++;
         i++;
         i++;
        i++;
         i++;
         i++;
        i++;
         i++;
         i++;
        i++;
         i++;
         i++;
        i++;
         i++;
         i++;
        i++;
         i++;
         i++;
         i++;
        i++;
         i++;
         i++;
        i++;
         i++;
         i++;
        i++;
         i++;
         i++;
        i++;
         i++;
         i++;
        i++;
          
         i++;
         i++;
        i++;
         i++;
         i++;
        i++;
         i++;
         i++;
        i++;
         i++;
         i++;
        i++;
         i++;
         i++;
        i++;
         i++;
         i++;
        i++;
         i++;
         i++;
        i++;
         i++;
         i++;
        i++;
         i++;
         i++;
        i++;
         i++;
         i++;
        i++;
         i++;
         i++;
        i++;
         i++;
         i++;
        i++;
         i++;
         i++;
         i++;
        i++;
         i++;
         i++;
        i++;
         i++;
         i++;
        i++;
         i++;
         i++;
        i++;
         i++;
         i++;
        i++;
          
         i++;
         i++;
        i++;
         i++;
         i++;
        i++;
         i++;
         i++;
        i++;
         i++;
         i++;
        i++;
         i++;
         i++;
        i++;
         i++;
         i++;
        i++;
         i++;
         i++;
        i++;
         i++;
         i++;
        i++;
         i++;
         i++;
        i++;
         i++;
         i++;
        i++;
         i++;
         i++;
        i++;
         i++;
         i++;
        i++;
         i++;
         i++;
         i++;
        i++;
         i++;
         i++;
        i++;
         i++;
         i++;
        i++;
         i++;
         i++;
        i++;
         i++;
         i++;
        i++;
          
         i++;
         i++;
        i++;
         i++;
         i++;
        i++;
         i++;
         i++;
        i++;
         i++;
         i++;
        i++;
         i++;
         i++;
        i++;
         i++;
         i++;
        i++;
         i++;
         i++;
        i++;
         i++;
         i++;
        i++;
         i++;
         i++;
        i++;
         i++;
         i++;
        i++;
         i++;
         i++;
        i++;
         i++;
         i++;
        i++;
         i++;
         i++;
         i++;
        i++;
         i++;
         i++;
        i++;
         i++;
         i++;
        i++;
         i++;
         i++;
        i++;
         i++;
         i++;
        i++;
          
         i++;
         i++;
        i++;
         i++;
         i++;
        i++;
         i++;
         i++;
        i++;
         i++;
         i++;
        i++;
         i++;
         i++;
        i++;
         i++;
         i++;
        i++;
         i++;
         i++;
        i++;
         i++;
         i++;
        i++;
         i++;
         i++;
        i++;
         i++;
         i++;
        i++;
         i++;
         i++;
        i++;
         i++;
         i++;
        i++;
         i++;
         i++;
         i++;
        i++;
         i++;
         i++;
        i++;
         i++;
         i++;
        i++;
         i++;
         i++;
        i++;
         i++;
         i++;
        i++;
          
         i++;
         i++;
        i++;
         i++;
         i++;
        i++;
         i++;
         i++;
        i++;
         i++;
         i++;
        i++;
         i++;
         i++;
        i++;
         i++;
         i++;
        i++;
         i++;
         i++;
        i++;
         i++;
         i++;
        i++;
         i++;
         i++;
        i++;
         i++;
         i++;
       
     }
}