unpackaged/main/default/objects/ET_Customer_Vehicle__c/ET_Customer_Vehicle__c.object-meta.xml
<CustomObject>
    <label>Customer Vehicle</label>
    <nameField>
        <displayFormat>CV-{000000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Customer Vehicles</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/ET_Customer_Vehicle__c/fields/Chassis_No__c.field-meta.xml
<CustomField>
    <fullName>Chassis_No__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Chassis No</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/ET_Customer_Vehicle__c/fields/Plate_Color__c.field-meta.xml
<CustomField>
    <fullName>Plate_Color__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Plate Color</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/ET_Customer_Vehicle__c/fields/Plate_No__c.field-meta.xml
<CustomField>
    <fullName>Plate_No__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Plate No</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/ET_Customer_Vehicle__c/fields/Plate_Source__c.field-meta.xml
<CustomField>
    <fullName>Plate_Source__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Plate Source</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/ET_Customer_Vehicle__c/fields/Plate_Type__c.field-meta.xml
<CustomField>
    <fullName>Plate_Type__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Plate Type</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/ET_Customer_Vehicle__c/fields/Registration_Expiry_Date__c.field-meta.xml
<CustomField>
    <fullName>Registration_Expiry_Date__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Registration Expiry Date</label>
    <type>Date</type>
</CustomField>

unpackaged/main/default/objects/ET_Customer_Vehicle__c/fields/Vehicle_Make__c.field-meta.xml
<CustomField>
    <fullName>Vehicle_Make__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Vehicle Make</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/ET_Customer_Vehicle__c/fields/Vehicle_Model__c.field-meta.xml
<CustomField>
    <fullName>Vehicle_Model__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Vehicle Model</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/ET_Customer_Vehicle__c/fields/Vehicle_Type__c.field-meta.xml
<CustomField>
    <fullName>Vehicle_Type__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Vehicle Type</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/ET_Customer_Vehicle__c/fields/Vehicle_Year__c.field-meta.xml
<CustomField>
    <fullName>Vehicle_Year__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Vehicle Year</label>
    <length>4</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/ET_Location__c/ET_Location__c.object-meta.xml
<CustomObject>
    <label>Inspection Center</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>ET Loaction Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Inspection Centers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/ET_Location__c/fields/ETSALES_Emirates__c.field-meta.xml
<CustomField>
    <fullName>ETSALES_Emirates__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Emirates</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/ET_Service_Request__c/ET_Service_Request__c.object-meta.xml
<CustomObject>
    <label>Service Request</label>
    <nameField>
        <displayFormat>SR-{000000}</displayFormat>
        <label>Service Request Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Service Requests</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

unpackaged/main/default/objects/ET_Service_Request__c/fields/ET_Account__c.field-meta.xml
<CustomField>
    <fullName>ET_Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Service Requests (Account)</relationshipLabel>
    <relationshipName>Service_Requests</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/ET_Service_Request__c/fields/ET_Location__c.field-meta.xml
<CustomField>
    <fullName>ET_Location__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Location</label>
    <referenceTo>ET_Location__c</referenceTo>
    <relationshipLabel>Service Requests</relationshipLabel>
    <relationshipName>Service_Requests</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/ETI_Booking__c/ETI_Booking__c.object-meta.xml
<CustomObject>
    <label>Booking</label>
    <nameField>
        <displayFormat>B-{000000}</displayFormat>
        <label>Booking</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Bookings</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

unpackaged/main/default/objects/ETI_Booking__c/fields/Chassis_No__c.field-meta.xml
<CustomField>
    <fullName>Chassis_No__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Chassis No</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/ETI_Booking__c/fields/Customer_Vehicle__c.field-meta.xml
<CustomField>
    <fullName>Customer_Vehicle__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Customer Vehicle</label>
    <referenceTo>ET_Customer_Vehicle__c</referenceTo>
    <relationshipLabel>Bookings</relationshipLabel>
    <relationshipName>Bookings</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/ETI_Booking__c/fields/ET_Location__c.field-meta.xml
<CustomField>
    <fullName>ET_Location__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Location</label>
    <referenceTo>ET_Location__c</referenceTo>
    <relationshipLabel>Bookings</relationshipLabel>
    <relationshipName>Bookings</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/ETI_Booking__c/fields/Plate_No__c.field-meta.xml
<CustomField>
    <fullName>Plate_No__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Plate No</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/ETI_Booking__c/fields/Service_Request__c.field-meta.xml
<CustomField>
    <fullName>Service_Request__c</fullName>
    <label>Service Request</label>
    <referenceTo>ET_Service_Request__c</referenceTo>
    <relationshipLabel>Bookings</relationshipLabel>
    <relationshipName>Bookings</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

unpackaged/main/default/objects/ETI_Booking__c/fields/Vehicle_Type__c.field-meta.xml
<CustomField>
    <fullName>Vehicle_Type__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Vehicle Type</label>
    <length>250</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/ETI_Lane_Details__c/ETI_Lane_Details__c.object-meta.xml
<CustomObject>
    <label>Lane Details</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Lane Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Lane Details</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/ETI_Lane_Details__c/fields/ET_Location__c.field-meta.xml
<CustomField>
    <fullName>ET_Location__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Location</label>
    <referenceTo>ET_Location__c</referenceTo>
    <relationshipLabel>Lane Details</relationshipLabel>
    <relationshipName>Lane_Details</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/ETI_Service_Line_Item__c/ETI_Service_Line_Item__c.object-meta.xml
<CustomObject>
    <label>Booking Line Item</label>
    <nameField>
        <displayFormat>SVC-{00000}</displayFormat>
        <label>Service Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Booking Line Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

unpackaged/main/default/objects/ETI_Service_Line_Item__c/fields/Booking__c.field-meta.xml
<CustomField>
    <fullName>Booking__c</fullName>
    <label>Booking</label>
    <referenceTo>ETI_Booking__c</referenceTo>
    <relationshipLabel>Booking Line Items</relationshipLabel>
    <relationshipName>Services</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

unpackaged/main/default/objects/ETI_Service_Line_Item__c/fields/Chassis_No__c.field-meta.xml
<CustomField>
    <fullName>Chassis_No__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Chassis No</label>
    <length>150</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/ETI_Service_Line_Item__c/fields/Plate_Color__c.field-meta.xml
<CustomField>
    <fullName>Plate_Color__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Plate Color</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/ETI_Service_Line_Item__c/fields/Service_Type__c.field-meta.xml
<CustomField>
    <fullName>Service_Type__c</fullName>
    <label>Service Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Police Inspection</fullName>
            </value>
            <value>
                <fullName>Certificate</fullName>
            </value>
            <value>
                <fullName>ADFCA</fullName>
            </value>
            <value>
                <fullName>SPEA Inspection</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/ETI_Vehicle_Service__c/ETI_Vehicle_Service__c.object-meta.xml
<CustomObject>
    <label>Vehicle Service</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Service  Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Vehicle Services</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/ETI_Vehicle_Service__c/fields/Service_Type__c.field-meta.xml
<CustomField>
    <fullName>Service_Type__c</fullName>
    <label>Service Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Police Inspection</fullName>
            </value>
            <value>
                <fullName>Certificate</fullName>
            </value>
            <value>
                <fullName>ADFCA</fullName>
            </value>
            <value>
                <fullName>SPEA Inspection</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/ETI_Vehicle_Service__c/fields/Vehicle_Type__c.field-meta.xml
<CustomField>
    <fullName>Vehicle_Type__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Vehicle Type</label>
    <referenceTo>ETI_Vehicle_Type__c</referenceTo>
    <relationshipLabel>Vehicle Services</relationshipLabel>
    <relationshipName>Vehicle_Services</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Invoice__c/Invoice__c.object-meta.xml
<CustomObject>
    <label>Invoice</label>
    <nameField>
        <displayFormat>INV-{000000}</displayFormat>
        <label>Invoice No</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Invoices</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Invoice__c/fields/ETST_Active__c.field-meta.xml
<CustomField>
    <fullName>ETST_Active__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Active</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/objects/Invoice__c/fields/Service_Request__c.field-meta.xml
<CustomField>
    <fullName>Service_Request__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Service Request</label>
    <referenceTo>ET_Service_Request__c</referenceTo>
    <relationshipLabel>Invoices</relationshipLabel>
    <relationshipName>Invoices</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Invoice__c/fields/Total_Inv_Amount__c.field-meta.xml
<CustomField>
    <fullName>Total_Inv_Amount__c</fullName>
    <label>Total Inv Amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

unpackaged/main/default/objects/Invoice__c/fields/Trx_Date__c.field-meta.xml
<CustomField>
    <fullName>Trx_Date__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Trx Date</label>
    <type>DateTime</type>
</CustomField>

unpackaged/main/default/classes/ETI_InvoiceCtrl.cls
public class ETI_InvoiceCtrl {
    public ET_Service_Request__c serviceRequest {get;set;}
    public String  serviceRequestName {get;set;}
    public List<Invoice__c> invoiceList {get;set;}
    public List<WrapperBooking> wrapBookings {get;set;}
    public double amount {get;set;}
    public double vat {get;set;}
    public double totalAmount {get;set;}
    public Boolean isBooking {get; set;}

    public ETI_InvoiceCtrl(){
        amount = 0.00;
        vat = 0.00;
        totalAmount = 0.00;
        id recordId = Apexpages.currentPage().getParameters().get('id');
        invoiceList = new List<Invoice__c>();
        wrapBookings = new List<WrapperBooking>();
        //loadInvoices();
        if(invoiceList.size()==0){
            
        } 
        if(recordId == null){
            return;
            
        }
        String sobjectName = recordId.getSObjectType().getDescribe().getName();
        system.debug('sobjectName>> '+sobjectName);
        if(sobjectName == 'ET_Service_Request__c'){
        system.debug('recordId11>> '+recordId);
            isBooking = false;
            initValueForETServiceRequest(recordId);
        }else{
        system.debug('recordId22>> '+recordId);
            isBooking = true;
            initValueForETBooking(recordId);
        }
    }
    
    public void initValueForETServiceRequest(id recordId){
        try{
            invoiceList = [Select Id,Name,CreatedDate,Total_Inv_Amount__c,Trx_Date__c,Service_Request__r.ET_Account__c from Invoice__c WHERE Service_Request__c=:recordId and ETST_Active__c=true order by createddate desc limit 1];
            if(invoiceList.size()>0){ 
                List<ETI_Booking__c> lstBookings = [Select Id,Name,Service_Request__r.Name,Service_Type__c,ET_Location__c,ET_Location__r.ETSALES_Emirates__c,ET_Location__r.Name,Customer_Vehicle__c,Customer_Vehicle__r.Registration_Expiry_Date__c,Customer_Vehicle__r.Plate_No__c,Customer_Vehicle__r.Plate_Color__c,Customer_Vehicle__r.Plate_Source__c,
                                                           Customer_Vehicle__r.Plate_Type__c,Customer_Vehicle__r.Chassis_No__c,Customer_Vehicle__r.Vehicle_Make__c,Customer_Vehicle__r.Vehicle_Model__c,Customer_Vehicle__r.Vehicle_Type__c,Customer_Vehicle__r.Vehicle_Year__c,Customer_Vehicle__r.Vehicle_Color1__c,Payment_Status__c,
                                                           Purpose_Type__r.Name,User__r.Name,Customer_Vehicle__r.Customer_Name__c,Allocated_Lane__r.Lane_Type_AMAN__c,(Select Id,Name,Service__r.Name,Fee_Amount__c,Tax_Amount__c,Total_Fee__c,Test_Date__c,Test_Result__c from Services__r order by createddate) from ETI_Booking__c WHERE Service_Request__c=:recordId];
               if(!lstBookings.isEmpty() && lstBookings.size()>0){
                    for(ETI_Booking__c bk : lstBookings){
                        serviceRequestName = bk.Service_Request__r.Name;
                        List<ETI_Service_Line_Item__c> lstServiceLineItems = new List<ETI_Service_Line_Item__c>();
                        WrapperBooking wrap = new WrapperBooking();
                        wrap.booking = bk;
                        if(bk.Services__r.size()>0){
                            for(ETI_Service_Line_Item__c srvLine : bk.Services__r){
                                /*amount+= srvLine.Fee_Amount__c;
                                vat+= srvLine.Tax_Amount__c;
                                totalAmount+= srvLine.Total_Fee__c;*/
                                lstServiceLineItems.add(srvLine);
                            }
                            wrap.serviceLineItemsList = lstServiceLineItems;
                            if(bk.ET_Location__c !=null){
                                wrap.location = bk.ET_Location__r.Name;
                                wrap.emirate = bk.ET_Location__r.ETSALES_Emirates__c;
                            }
                        }
                        wrap.customerName= bk.User__r.Name!=null && bk.User__r.Name!=''? bk.User__r.Name:bk.Customer_Vehicle__r.Customer_Name__c;
                        wrap.invoiceDate = String.valueOf(invoiceList[0].CreatedDate.format('dd/MM/yyyy'));
                        wrap.invoiceTime = String.valueOf(invoiceList[0].CreatedDate.format('HH:mm'));
                        wrapBookings.add(wrap);
                    }
                }
            }
        }catch(exception e){
            System.debug('Exception '+e.getMessage());
            System.debug('Exception line '+e.getLineNumber());
        }
    } 
    public void initValueForETBooking(id recordId){
        try{
            List<ETI_Booking__c> lstBookings1 = [Select Id,Service_Request__c from ETI_Booking__c Where id=:recordId];
            if(lstBookings1!=null && lstBookings1.size()>0)
                invoiceList = [Select Id,Name,CreatedDate,Total_Inv_Amount__c,Trx_Date__c,Service_Request__r.ET_Account__c from Invoice__c WHERE Service_Request__c=:lstBookings1[0].Service_Request__c and ETST_Active__c=true order by createddate desc limit 1];
            if(invoiceList.size()>0){ 
                List<ETI_Booking__c> lstBookings = [Select Id,Name,Service_Request__r.Name,Service_Type__c,ET_Location__c,ET_Location__r.ETSALES_Emirates__c,ET_Location__r.Name,Customer_Vehicle__c,Customer_Vehicle__r.Registration_Expiry_Date__c,Customer_Vehicle__r.Plate_No__c,Customer_Vehicle__r.Plate_Color__c,Customer_Vehicle__r.Plate_Source__c,Customer_Vehicle__r.Plate_Type__c,Customer_Vehicle__r.Chassis_No__c,
                                                           Purpose_Type__r.Name,User__r.Name,Customer_Vehicle__r.Customer_Name__c,Allocated_Lane__r.Lane_Type_AMAN__c,Customer_Vehicle__r.Vehicle_Color1__c,Payment_Status__c,
                                                           Customer_Vehicle__r.Vehicle_Make__c,Customer_Vehicle__r.Vehicle_Model__c,Customer_Vehicle__r.Vehicle_Type__c,Customer_Vehicle__r.Vehicle_Year__c,
                                                           (Select Id,Name,Service__r.Name,Fee_Amount__c,Tax_Amount__c,Total_Fee__c,Test_Date__c,Test_Result__c from Services__r order by createddate) from ETI_Booking__c WHERE Id=:recordId];
                if(!lstBookings.isEmpty() && lstBookings.size()>0){
                    for(ETI_Booking__c bk : lstBookings){
                         serviceRequestName = bk.Service_Request__r.Name;
                        List<ETI_Service_Line_Item__c> lstServiceLineItems = new List<ETI_Service_Line_Item__c>();
                        WrapperBooking wrap = new WrapperBooking();
                        wrap.booking = bk;
                        if(bk.Services__r.size()>0){
                            for(ETI_Service_Line_Item__c srvLine : bk.Services__r){
                                /*if(srvLine.Fee_Amount__c!=null)
                                    amount+= srvLine.Fee_Amount__c;
                                if(srvLine.Tax_Amount__c!=null )
                                    vat+= srvLine.Tax_Amount__c;
                                if(srvLine.Total_Fee__c!=null)
                                    totalAmount+= srvLine.Total_Fee__c;*/
                                lstServiceLineItems.add(srvLine);
                            }
                            wrap.serviceLineItemsList = lstServiceLineItems;
                            if(bk.ET_Location__c !=null){
                                wrap.location = bk.ET_Location__r.Name;
                                wrap.emirate = bk.ET_Location__r.ETSALES_Emirates__c;
                            }
                        }
                        wrap.customerName= bk.User__r.Name!=null && bk.User__r.Name!=''? bk.User__r.Name:bk.Customer_Vehicle__r.Customer_Name__c;
                        wrap.invoiceDate = String.valueOf(invoiceList[0].CreatedDate.format('dd/MM/yyyy'));
                        wrap.invoiceTime = String.valueOf(invoiceList[0].CreatedDate.format('HH:mm'));
                        wrapBookings.add(wrap);
                        system.debug('wrapBookings>> '+wrapBookings);
                    }
                }
            }
        }catch(exception e){
            System.debug('Exception '+e.getMessage());
            System.debug('Exception line '+e.getLineNumber());
        }
    } 
    
    class WrapperBooking{
        public ETI_booking__c booking {get;set;}
        public List<ETI_Service_Line_Item__c> serviceLineItemsList {get;set;}
        public string customerName{get; set;}
        public string location {get;set;}
        public string invoiceDate {get;set;}
        public string invoiceTime {get;set;}
        public string emirate {get;set;}       
        WrapperBooking(){}
    }
    
}