unpackaged/main/default/objects/ET_Customer_Vehicle__c/ET_Customer_Vehicle__c.object-meta.xml
<CustomObject>
    <label>Customer Vehicle</label>
    <nameField>
        <displayFormat>CV-{000000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Customer Vehicles</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/ET_Customer_Vehicle__c/fields/Chassis_No__c.field-meta.xml
<CustomField>
    <fullName>Chassis_No__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Chassis No</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/ET_Service_Request__c/ET_Service_Request__c.object-meta.xml
<CustomObject>
    <label>Service Request</label>
    <nameField>
        <displayFormat>SR-{000000}</displayFormat>
        <label>Service Request Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Service Requests</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

unpackaged/main/default/objects/ETI_Booking__c/ETI_Booking__c.object-meta.xml
<CustomObject>
    <label>Booking</label>
    <nameField>
        <displayFormat>B-{000000}</displayFormat>
        <label>Booking</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Bookings</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

unpackaged/main/default/objects/ETI_Booking__c/fields/Booking_Status__c.field-meta.xml
<CustomField>
    <fullName>Booking_Status__c</fullName>
    <label>Booking Status</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Draft</fullName>
            </value>
            <value>
                <fullName>Booked</fullName>
            </value>
            <value>
                <fullName>Inspection Completed</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
            <value>
                <fullName>Due for Retest</fullName>
            </value>
            <value>
                <fullName>Applied for Retest</fullName>
            </value>
            <value>
                <fullName>Confirmed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/ETI_Booking__c/fields/Chassis_No__c.field-meta.xml
<CustomField>
    <fullName>Chassis_No__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Chassis No</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/ETI_Booking__c/fields/Customer_Vehicle__c.field-meta.xml
<CustomField>
    <fullName>Customer_Vehicle__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Customer Vehicle</label>
    <referenceTo>ET_Customer_Vehicle__c</referenceTo>
    <relationshipLabel>Bookings</relationshipLabel>
    <relationshipName>Bookings</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/ETI_Booking__c/fields/ETI_Schedule_Appointment__c.field-meta.xml
<CustomField>
    <fullName>ETI_Schedule_Appointment__c</fullName>
    <defaultValue>true</defaultValue>
    <label>Schedule Appointment</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/objects/ETI_Booking__c/fields/Service_Request__c.field-meta.xml
<CustomField>
    <fullName>Service_Request__c</fullName>
    <label>Service Request</label>
    <referenceTo>ET_Service_Request__c</referenceTo>
    <relationshipLabel>Bookings</relationshipLabel>
    <relationshipName>Bookings</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

unpackaged/main/default/objects/ETI_Booking__c/fields/Test_Result__c.field-meta.xml
<CustomField>
    <fullName>Test_Result__c</fullName>
    <label>Test Result</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Pending</fullName>
                <default>true</default>
                <label>Pending</label>
            </value>
            <value>
                <fullName>Failed</fullName>
            </value>
            <value>
                <fullName>Pass</fullName>
            </value>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>Rejected</fullName>
            </value>
            <value>
                <fullName>No Show</fullName>
            </value>
            <value>
                <fullName>Partially Approved</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/ETI_Inspection_Receipt__c/ETI_Inspection_Receipt__c.object-meta.xml
<CustomObject>
    <label>Aman Receipt</label>
    <nameField>
        <displayFormat>RCPT-{00000}</displayFormat>
        <label>ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Aman Receipts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/ETI_Inspection_Receipt__c/fields/AMAN_Receipt_No__c.field-meta.xml
<CustomField>
    <fullName>AMAN_Receipt_No__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>AMAN Receipt No</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/ETI_Inspection_Receipt__c/fields/Bookings__c.field-meta.xml
<CustomField>
    <fullName>Bookings__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Booking</label>
    <referenceTo>ETI_Booking__c</referenceTo>
    <relationshipName>Receipts</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/ETI_Inspection_Receipt__c/fields/Chassis_No__c.field-meta.xml
<CustomField>
    <fullName>Chassis_No__c</fullName>
    <formula>Bookings__r.Chassis_No__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Chassis No</label>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/ETI_Inspection_Receipt__c/fields/ETI_Amount__c.field-meta.xml
<CustomField>
    <fullName>ETI_Amount__c</fullName>
    <label>Amount</label>
    <precision>18</precision>
    <required>true</required>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

unpackaged/main/default/objects/ETI_Inspection_Receipt__c/fields/Service_Line_Item__c.field-meta.xml
<CustomField>
    <fullName>Service_Line_Item__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Booking Line Item</label>
    <referenceTo>ETI_Service_Line_Item__c</referenceTo>
    <relationshipLabel>Aman Receipts</relationshipLabel>
    <relationshipName>Receipts</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/ETI_Inspection_Receipt__c/fields/Service_Request__c.field-meta.xml
<CustomField>
    <fullName>Service_Request__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Service Request</label>
    <referenceTo>ET_Service_Request__c</referenceTo>
    <relationshipName>Receipts</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/ETI_Service_Line_Item__c/ETI_Service_Line_Item__c.object-meta.xml
<CustomObject>
    <label>Booking Line Item</label>
    <nameField>
        <displayFormat>SVC-{00000}</displayFormat>
        <label>Service Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Booking Line Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

unpackaged/main/default/objects/ETI_Service_Line_Item__c/fields/Booking__c.field-meta.xml
<CustomField>
    <fullName>Booking__c</fullName>
    <label>Booking</label>
    <referenceTo>ETI_Booking__c</referenceTo>
    <relationshipLabel>Booking Line Items</relationshipLabel>
    <relationshipName>Services</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

unpackaged/main/default/objects/ETI_Service_Line_Item__c/fields/Chassis_No__c.field-meta.xml
<CustomField>
    <fullName>Chassis_No__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Chassis No</label>
    <length>150</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/ETI_Service_Line_Item__c/fields/Service_Type__c.field-meta.xml
<CustomField>
    <fullName>Service_Type__c</fullName>
    <label>Service Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Police Inspection</fullName>
            </value>
            <value>
                <fullName>Certificate</fullName>
            </value>
            <value>
                <fullName>ADFCA</fullName>
            </value>
            <value>
                <fullName>SPEA Inspection</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/ETI_Service_Line_Item__c/fields/Test_Result__c.field-meta.xml
<CustomField>
    <fullName>Test_Result__c</fullName>
    <label>Test Result</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Pending</fullName>
            </value>
            <value>
                <fullName>Pass</fullName>
            </value>
            <value>
                <fullName>Failed</fullName>
            </value>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>Rejected</fullName>
            </value>
            <value>
                <fullName>No Show</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Service_Type__c/Service_Type__c.object-meta.xml
<CustomObject>
    <label>Service Type</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Service Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Service Types</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/WorkOrder/fields/Booking__c.field-meta.xml
<CustomField>
    <fullName>Booking__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Booking</label>
    <referenceTo>ETI_Booking__c</referenceTo>
    <relationshipLabel>Work Orders</relationshipLabel>
    <relationshipName>Work_Orders</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/WorkOrder/fields/ETI_Schedule_Appointment__c.field-meta.xml
<CustomField>
    <fullName>ETI_Schedule_Appointment__c</fullName>
    <defaultValue>true</defaultValue>
    <description>This field controls - whether to Auto Assign this appointment to Available Resource based on Scheduling Policy.</description>
    <label>Schedule Appointment</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/objects/WorkOrder/fields/Inspection_Status__c.field-meta.xml
<CustomField>
    <fullName>Inspection_Status__c</fullName>
    <label>Inspection Result</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Pass</fullName>
            </value>
            <value>
                <fullName>Fail</fullName>
            </value>
            <value>
                <fullName>None</fullName>
                <default>true</default>
                <label>None</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/WorkOrder/recordTypes/Inspection_Work_Order.recordType-meta.xml
<RecordType>
    <fullName>Inspection_Work_Order</fullName>
    <active>true</active>
    <description>Record Type used for Inspection</description>
    <label>Inspection Work Order</label>
</RecordType>

unpackaged/main/default/classes/ETI_workOrderTriggerTestClass.cls
/********************************************************************************************************
* @author       Smaartt
* @description  Test Class for 'ETI_workOrderTriggerHandler'
*********************************************************************************************************/
@isTest
public class ETI_workOrderTriggerTestClass {
    
    // Test Data Setup
    @testsetup static void setup(){
        
        // Customer Vehicle
        ET_Customer_Vehicle__c cv = new ET_Customer_Vehicle__c();
        cv.Chassis_No__c = 'JN6BE6CS4G9401628';
        insert cv;
        
        // Service Request
        ET_Service_Request__c req = new ET_Service_Request__c();
        insert req;
        
        // Booking
        ETI_Booking__c bkng = new ETI_Booking__c();
        
        bkng.Service_Type__c = 'SPEA Inspection';
        bkng.Customer_Vehicle__c = cv.id;
        bkng.Booking_Status__c = 'Booked';
        bkng.Service_Request__c = req.id;
        insert bkng;
        
        // Booking Line Item
        ETI_Service_Line_Item__c item = new ETI_Service_Line_Item__c();
        item.Booking__c = bkng.id;
        item.Test_Result__c = 'Pass';
        insert item;
        
        // Receipt
        ETI_Inspection_Receipt__c recpt = new 	ETI_Inspection_Receipt__c();
        
        recpt.AMAN_Receipt_No__c = '1234';
        recpt.Service_Request__c  = req.id;
        recpt.Service_Line_Item__c =item.id;
        recpt.Bookings__c = bkng.id;
        recpt.ETI_Amount__c = 123;
        insert recpt;
        
        // Create work Orders
        workOrder wo = new workOrder();
        Id recordTypeId = Schema.SObjectType.WorkOrder.getRecordTypeInfosByDeveloperName().get('Inspection_Work_Order').getRecordTypeId();
        wo.StartDate = Datetime.Now(); 
        wo.Subject = 'Inspection';
        wo.ETI_Schedule_Appointment__c = true;  
        wo.Street  = 'Alfahidhi';
        wo.City = 'Dubai';
        wo.PostalCode = '531116';
        wo.Country ='United Arab Emirates';
        wo.Inspection_Status__c = 'Pass';
        wo.Booking__c = bkng.id;
        insert wo;
        
    }
    
    
    // update work order from Pass to Fail
    @isTest static void testMethod1() {
        
        workOrder wo = [select id, Inspection_Status__c from workOrder where Subject = 'Inspection' ];
        wo.Inspection_Status__c = 'Fail';
        update wo;
        
    }
    
    @isTest static void testMethod2(){
        ETI_workOrderTriggerHandler.utility();
    }
}