unpackaged/main/default/objects/ET_Sales_Agreement__c/ET_Sales_Agreement__c.object-meta.xml
<CustomObject>
    <label>Sales Agreement</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Sales Agreement</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Sales Agreements</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/ET_Sales_Agreement__c/fields/Administration_Charges__c.field-meta.xml
<CustomField>
    <fullName>Administration_Charges__c</fullName>
    <label>Administration Charges</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

unpackaged/main/default/objects/ET_Sales_Agreement__c/fields/Contract_No__c.field-meta.xml
<CustomField>
    <fullName>Contract_No__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Contact Number</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/ET_Sales_Agreement__c/fields/Contract_Start_Date__c.field-meta.xml
<CustomField>
    <fullName>Contract_Start_Date__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Contract Start Date</label>
    <type>Date</type>
</CustomField>

unpackaged/main/default/objects/ET_Sales_Agreement__c/fields/Customer_PO_No__c.field-meta.xml
<CustomField>
    <fullName>Customer_PO_No__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Customer PO No</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/ET_Sales_Agreement__c/fields/Salesforce_Customer__c.field-meta.xml
<CustomField>
    <fullName>Salesforce_Customer__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Customer</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Sales Agreements</relationshipLabel>
    <relationshipName>Sales_Agreements</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/classes/ET_SalesAgreementTrigger_Test.cls
@isTest
public class ET_SalesAgreementTrigger_Test{
 
 public static testmethod void saleaAggrementTrg(){
 
        Account objBusinessAcct = new Account();
        objBusinessAcct.Name = 'ALDAR Academies L.L.C   Al Muna Academy';
        objBusinessAcct.Type = 'Private School';
        objBusinessAcct.RecordTypeId = Schema.SObjectType.Account.getRecordTypeInfosByName().get('Business (B2B) - School').getRecordTypeId();        
        insert objBusinessAcct;
        Contact con = new Contact();
        con.LastName = 'Last name';
        con.Email = 'noor.shaik@smaartt.com';
        insert con;
        Account objPersonAcct = new Account();
        objPersonAcct.FirstName = 'ALDAR ';
        objPersonAcct.LastName = 'Al Muna Academy';
        objPersonAcct.RecordTypeId = Schema.SObjectType.Account.getRecordTypeInfosByName().get('Person (B2C)').getRecordTypeId();        
        insert objPersonAcct;
        
        ET_Sales_Agreement__c objSalesAgr = new ET_Sales_Agreement__c();
        objSalesAgr.Name = 'Test';
        objSalesAgr.Activity__c = 'test';
        objSalesAgr.Administration_Charges__c  = 1234;
        objSalesAgr.Contract_End_Date__c = date.today().addDays(30);
        objSalesAgr.Contract_No__c = '123456789';
        objSalesAgr.Contract_Start_Date__c = date.today();
        objSalesAgr.Customer_PO_No__c = '12345';
        objSalesAgr.Salesforce_Customer__c = objPersonAcct.Id;
        insert objSalesAgr;
 }
}