unpackaged/main/default/objects/ET_Service_Request__c/ET_Service_Request__c.object-meta.xml
<CustomObject>
    <label>Service Request</label>
    <nameField>
        <displayFormat>SR-{000000}</displayFormat>
        <label>Service Request Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Service Requests</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

unpackaged/main/default/objects/ET_Service_Request__c/fields/Payment_Status__c.field-meta.xml
<CustomField>
    <fullName>Payment_Status__c</fullName>
    <label>Payment Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Not Initiated</fullName>
            </value>
            <value>
                <fullName>Payment Pending</fullName>
            </value>
            <value>
                <fullName>Payment Success</fullName>
            </value>
            <value>
                <fullName>Refund Requested</fullName>
            </value>
            <value>
                <fullName>Await3D</fullName>
            </value>
            <value>
                <fullName>Captured</fullName>
            </value>
            <value>
                <fullName>Partially Paid</fullName>
            </value>
            <value>
                <fullName>Fully Paid</fullName>
            </value>
            <value>
                <fullName>Refund Cancelled</fullName>
            </value>
            <value>
                <fullName>Failed</fullName>
            </value>
            <value>
                <fullName>Reversed</fullName>
            </value>
            <value>
                <fullName>On Premise Requested</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/ET_Service_Request__c/fields/Total_Amount__c.field-meta.xml
<CustomField>
    <fullName>Total_Amount__c</fullName>
    <label>Total Amount</label>
    <summarizedField>ETI_Booking__c.Total_Amount__c</summarizedField>
    <summaryFilterItems>
        <field>ETI_Booking__c.Booking_Status__c</field>
        <operation>notEqual</operation>
        <value>Cancelled</value>
    </summaryFilterItems>
    <summaryForeignKey>ETI_Booking__c.Service_Request__c</summaryForeignKey>
    <summaryOperation>sum</summaryOperation>
    <type>Summary</type>
</CustomField>

unpackaged/main/default/objects/ETI_Booking__c/ETI_Booking__c.object-meta.xml
<CustomObject>
    <label>Booking</label>
    <nameField>
        <displayFormat>B-{000000}</displayFormat>
        <label>Booking</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Bookings</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

unpackaged/main/default/objects/ETI_Booking__c/fields/Payment_Status__c.field-meta.xml
<CustomField>
    <fullName>Payment_Status__c</fullName>
    <formula>Text(Service_Request__r.Payment_Status__c )</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Payment Status</label>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/ETI_Booking__c/fields/Service_Request__c.field-meta.xml
<CustomField>
    <fullName>Service_Request__c</fullName>
    <label>Service Request</label>
    <referenceTo>ET_Service_Request__c</referenceTo>
    <relationshipLabel>Bookings</relationshipLabel>
    <relationshipName>Bookings</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

unpackaged/main/default/objects/ETI_Booking__c/fields/Total_Amount__c.field-meta.xml
<CustomField>
    <fullName>Total_Amount__c</fullName>
    <label>Total Amount</label>
    <summarizedField>ETI_Service_Line_Item__c.Total_Fee__c</summarizedField>
    <summaryForeignKey>ETI_Service_Line_Item__c.Booking__c</summaryForeignKey>
    <summaryOperation>sum</summaryOperation>
    <type>Summary</type>
</CustomField>

unpackaged/main/default/classes/ETI_BulkCancelBookingsBatch.cls
/*
* File Name:ETI_BulkCancelBookingsBatch
* Author : Noor Shaik
* CreatedDate : 3/5/2021
* Modification Purpose
* * 1. Noor Shaik: To Update Service Request status
* * 2.
*/
global class ETI_BulkCancelBookingsBatch implements Database.Batchable<sObject>, Schedulable, Database.AllowsCallouts, Database.Stateful{  
    
    global String queryString;
    public Set<Id> recordIds = new Set<Id>();
    public string cancellationReason;
    public Id serviceReqId;
    global ETI_BulkCancelBookingsBatch(list<Id> recIds,string cancelReason){
        if(recIds!=null && recIds.size()>0){
            recordIds.addAll(recIds);
        }
        if(cancelReason!=null)
            cancellationReason=cancelReason;
    }
    global Database.QueryLocator start(Database.BatchableContext bc){ 
        queryString='SELECT Id,Name,Service_Request__c FROM ETI_Booking__c WHERE Id IN:recordIds';
        return Database.getQueryLocator(queryString);
    }
    
    global void execute(Database.BatchableContext BC, List<ETI_Booking__c> scope){
        ETI_VehicleController.cancelBooking(new List<Id>{scope[0].Id},cancellationReason);
        if(serviceReqId==null)
            serviceReqId=scope[0].Service_Request__c;
    }
    global void finish(Database.BatchableContext BC){
        if(serviceReqId!=null){
            list<ET_Service_Request__c> serviceReqUpdate=new list<ET_Service_Request__c>();
            for(ET_Service_Request__c sr:[Select Id,Payment_Status__c From ET_Service_Request__c Where Id=:serviceReqId AND Total_Amount__c=0]){
                if(sr.Payment_Status__c!='Refund Requested'){
                    sr.Payment_Status__c='Refund Requested';
                    serviceReqUpdate.add(sr);
                }
            }
            if(!serviceReqUpdate.isEmpty())
                update serviceReqUpdate;
        }
    }  
    global void execute(SchedulableContext scon) {
        Database.executeBatch(new ETI_BulkCancelBookingsBatch(null,null));
    }
}