unpackaged/main/default/objects/ET_Service_Request__c/ET_Service_Request__c.object-meta.xml
<CustomObject>
    <label>Service Request</label>
    <nameField>
        <displayFormat>SR-{000000}</displayFormat>
        <label>Service Request Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Service Requests</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

unpackaged/main/default/objects/ET_Service_Request__c/fields/Payment_Status__c.field-meta.xml
<CustomField>
    <fullName>Payment_Status__c</fullName>
    <label>Payment Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Not Initiated</fullName>
            </value>
            <value>
                <fullName>Payment Pending</fullName>
            </value>
            <value>
                <fullName>Payment Success</fullName>
            </value>
            <value>
                <fullName>Refund Requested</fullName>
            </value>
            <value>
                <fullName>Await3D</fullName>
            </value>
            <value>
                <fullName>Captured</fullName>
            </value>
            <value>
                <fullName>Partially Paid</fullName>
            </value>
            <value>
                <fullName>Fully Paid</fullName>
            </value>
            <value>
                <fullName>Refund Cancelled</fullName>
            </value>
            <value>
                <fullName>Failed</fullName>
            </value>
            <value>
                <fullName>Reversed</fullName>
            </value>
            <value>
                <fullName>On Premise Requested</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/ET_Service_Request__c/recordTypes/Vehicle_Inspection.recordType-meta.xml
<RecordType>
    <fullName>Vehicle_Inspection</fullName>
    <active>true</active>
    <label>Vehicle Inspection</label>
</RecordType>

unpackaged/main/default/objects/ETST_Payment__c/ETST_Payment__c.object-meta.xml
<CustomObject>
    <label>Payment</label>
    <nameField>
        <displayFormat>TRN-{00000}</displayFormat>
        <label>ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Payments</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/ETST_Payment__c/fields/ET_Service_Request__c.field-meta.xml
<CustomField>
    <fullName>ET_Service_Request__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Service Request</label>
    <referenceTo>ET_Service_Request__c</referenceTo>
    <relationshipLabel>Payments</relationshipLabel>
    <relationshipName>ET_Payments</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/ETST_Payment__c/fields/ETST_Payment_State__c.field-meta.xml
<CustomField>
    <fullName>ETST_Payment_State__c</fullName>
    <defaultValue>IF( $RecordType.DeveloperName = &#39;On_Premise_Payment&#39; , &#39;SUCCESS&#39;, &#39;&#39;)</defaultValue>
    <encryptionScheme>None</encryptionScheme>
    <label>Payment State</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/classes/ETI_PaymentTriggerHandler.cls
/*
* File Name: ETI_PaymentTriggerHandler
* Author : Noor Shaik
* CreatedDate : 18/05/2021
* Modification Purpose
* * 1. Noor Shaik: Created to update Service Request Payment Status
* * 2.
*/
Public class ETI_PaymentTriggerHandler{
    //update Payment Status
    Public static void updatePaymentStatus(Map<Id, ETST_Payment__c> newMap, Map<Id,ETST_Payment__c> oldMap){
        List<ET_Service_Request__c> serviceReqUpdateList=new List<ET_Service_Request__c>();
        Set<Id> serviceRequestIds=new Set<Id>();
        try{
            for(ETST_Payment__c etb:newMap.values()){
                if((oldMap!=null && newMap.get(etb.Id).ETST_Payment_State__c != oldMap.get(etb.Id).ETST_Payment_State__c
                   && newMap.get(etb.Id).ETST_Payment_State__c =='CAPTURED') || newMap.get(etb.Id).ETST_Payment_State__c =='CAPTURED'){
                     serviceRequestIds.add(etb.ET_Service_Request__c);
                }
            }
            if(!serviceRequestIds.isEmpty()){
                Id recordTypeId = Schema.SObjectType.ET_Service_Request__c.getRecordTypeInfosByDeveloperName().get('Vehicle_Inspection').getRecordTypeId();
                for(ET_Service_Request__c sr:[Select Id,Payment_Status__c From ET_Service_Request__c Where Id IN:serviceRequestIds AND recordTypeId=:recordTypeId AND Payment_Status__c != 'Payment Success']){
                    sr.Payment_Status__c = 'Payment Success';
                    serviceReqUpdateList.add(sr);
                }
                if(!serviceReqUpdateList.isEmpty())
                    update serviceReqUpdateList;
            }
        }catch(DMLException ex){
            ETI_ServiceRequestHandler.logException(ex, 'ETI UpdatePaymentStatus');
        }   
    }
}