unpackaged/main/default/objects/ET_Service_Request__c/ET_Service_Request__c.object-meta.xml
<CustomObject>
    <label>Service Request</label>
    <nameField>
        <displayFormat>SR-{000000}</displayFormat>
        <label>Service Request Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Service Requests</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

unpackaged/main/default/objects/ET_Service_Request__c/fields/ETST_Drop_Off_To__c.field-meta.xml
<CustomField>
    <fullName>ETST_Drop_Off_To__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Drop-Off To</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/ET_Service_Request__c/fields/ETST_Is_Active__c.field-meta.xml
<CustomField>
    <fullName>ETST_Is_Active__c</fullName>
    <defaultValue>true</defaultValue>
    <label>Is Active</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/objects/ET_Service_Request__c/fields/ETST_Service_Type__c.field-meta.xml
<CustomField>
    <fullName>ETST_Service_Type__c</fullName>
    <label>Service Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Yearly</fullName>
            </value>
            <value>
                <fullName>Half Yearly</fullName>
            </value>
            <value>
                <fullName>Quarterly</fullName>
            </value>
            <value>
                <fullName>Monthly</fullName>
            </value>
            <value>
                <fullName>On-demand</fullName>
            </value>
            <value>
                <fullName>Select Dates</fullName>
            </value>
            <value>
                <fullName>One Way</fullName>
            </value>
            <value>
                <fullName>Hourly</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/ET_Service_Request__c/fields/ETST_Status__c.field-meta.xml
<CustomField>
    <fullName>ETST_Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Registered</fullName>
            </value>
            <value>
                <fullName>Under Review</fullName>
            </value>
            <value>
                <fullName>Request Rejected</fullName>
            </value>
            <value>
                <fullName>Service Confirmed</fullName>
            </value>
            <value>
                <fullName>Payment Success-In Review</fullName>
            </value>
            <value>
                <fullName>Payment success</fullName>
            </value>
            <value>
                <fullName>Payment Failed</fullName>
            </value>
            <value>
                <fullName>Request Cancelled</fullName>
            </value>
            <value>
                <fullName>Awaiting Confirmation</fullName>
            </value>
            <value>
                <fullName>Renewed</fullName>
            </value>
            <value>
                <fullName>On Hold</fullName>
            </value>
            <value>
                <fullName>Parent Cancelled</fullName>
            </value>
            <value>
                <fullName>School Changed</fullName>
            </value>
            <value>
                <fullName>Auto Deactivated</fullName>
            </value>
            <value>
                <fullName>Service Updated</fullName>
            </value>
            <value>
                <fullName>Refund Requested</fullName>
            </value>
            <value>
                <fullName>Refund Cancelled</fullName>
            </value>
            <value>
                <fullName>Location Update - Under Review</fullName>
            </value>
            <value>
                <fullName>Location Update - Rejected</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/ET_Service_Request__c/fields/ETST_Student__c.field-meta.xml
<CustomField>
    <fullName>ETST_Student__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Student</label>
    <referenceTo>ETST_Student__c</referenceTo>
    <relationshipName>ETST_Transport_Requests</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/ET_Service_Request__c/fields/ETST_Transport_Type__c.field-meta.xml
<CustomField>
    <fullName>ETST_Transport_Type__c</fullName>
    <label>Transport Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Two Way</fullName>
            </value>
            <value>
                <fullName>Pick up only</fullName>
            </value>
            <value>
                <fullName>Drop off only</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/ETST_Student__c/ETST_Student__c.object-meta.xml
<CustomObject>
    <label>Student</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Last Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Students</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

unpackaged/main/default/objects/ETST_Student__c/fields/ETST_Status__c.field-meta.xml
<CustomField>
    <fullName>ETST_Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Active</fullName>
            </value>
            <value>
                <fullName>Inactive</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/classes/ETST_UpdateServiceStatusToConfirmed.cls
public class ETST_UpdateServiceStatusToConfirmed {
  @InvocableMethod
    public static void updateServiceRequests(List<Id> serviceRequestIds) {
        
        Set<Id> studentIds = new Set<Id>();
        for(ET_Service_Request__c req: [SELECT ETST_Student__c FROM ET_Service_Request__c WHERE Id IN :serviceRequestIds]){
            studentIds.add(req.ETST_Student__c);
        }
        
        Map<Id, ET_Service_Request__c> activeRecordsMap = new Map<Id, ET_Service_Request__c>();
        for(ET_Service_Request__c req : [SELECT Name,ETST_Pick_Up_From__c,ETST_Is_Active__c,ETST_Drop_Off_To__c,ETST_Service_Type__c,ETST_Transport_Type__c,ETST_Student__c
                                         FROM ET_Service_Request__c WHERE ETST_Student__c IN :studentIds and ETST_Is_Active__c=true]){
                                             activeRecordsMap.put(req.ETST_Student__c , req);
                                         }
        
        List<ET_Service_Request__c> renewalList = new List<ET_Service_Request__c>();
        for(ET_Service_Request__c req : [SELECT Name,ETST_Pick_Up_From__c,ETST_Is_Active__c,ETST_Drop_Off_To__c,ETST_Service_Type__c,ETST_Transport_Type__c,ETST_Student__c
                                         FROM ET_Service_Request__c WHERE Id IN :serviceRequestIds]){
                                             
                                             System.debug('Active Request Transport Type: ' + activeRecordsMap.get(req.ETST_Student__c).ETST_Transport_Type__c);
                                             System.debug('Current Request Transport Type: ' + req.ETST_Transport_Type__c);
                                             System.debug('Active Request Pickup Loc: ' + activeRecordsMap.get(req.ETST_Student__c).ETST_Pick_Up_From__c);
                                             System.debug('Current Request Pickup Loc: ' + req.ETST_Pick_Up_From__c);
                                             System.debug('Active Request DropOff Loc: ' + activeRecordsMap.get(req.ETST_Student__c).ETST_Drop_Off_To__c);
                                             System.debug('Current Request DropOff Loc: ' + req.ETST_Drop_Off_To__c);
                                             
                                             if((activeRecordsMap.get(req.ETST_Student__c).ETST_Transport_Type__c != req.ETST_Transport_Type__c)||
                                                (activeRecordsMap.get(req.ETST_Student__c).ETST_Pick_Up_From__c != req.ETST_Pick_Up_From__c)||
                                                (activeRecordsMap.get(req.ETST_Student__c).ETST_Drop_Off_To__c != req.ETST_Drop_Off_To__c)){
                                                    req.ETST_Status__c = System.Label.ETST_Under_Review;
                                                    System.debug('TestStatus2:' + req.ETST_Status__c);
                                                }
                                             /*else if(((activeRecordsMap.get(req.ETST_Student__c).ETST_Transport_Type__c != req.ETST_Transport_Type__c)||
                                                (activeRecordsMap.get(req.ETST_Student__c).ETST_Pick_Up_From__c != req.ETST_Pick_Up_From__c)||
                                                (activeRecordsMap.get(req.ETST_Student__c).ETST_Drop_Off_To__c != req.ETST_Drop_Off_To__c)) && ){
                                                 
                                             }*/
                                             else{
                                                    req.ETST_Status__c = System.Label.ETST_Service_Confirmed;
                                                    System.debug('TestStatus3: ' + req.ETST_Status__c);
                                                }
                                             renewalList.add(req);                                             
                                         }
        
        if(renewalList.size()>0){
            update renewalList;
        }
        
        
    }
}