unpackaged/main/default/objects/ET_Service_Request__c/ET_Service_Request__c.object-meta.xml
<CustomObject>
    <label>Service Request</label>
    <nameField>
        <displayFormat>SR-{000000}</displayFormat>
        <label>Service Request Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Service Requests</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

unpackaged/main/default/objects/ET_Service_Request__c/fields/Payment_Status__c.field-meta.xml
<CustomField>
    <fullName>Payment_Status__c</fullName>
    <label>Payment Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Not Initiated</fullName>
            </value>
            <value>
                <fullName>Payment Pending</fullName>
            </value>
            <value>
                <fullName>Payment Success</fullName>
            </value>
            <value>
                <fullName>Refund Requested</fullName>
            </value>
            <value>
                <fullName>Await3D</fullName>
            </value>
            <value>
                <fullName>Captured</fullName>
            </value>
            <value>
                <fullName>Partially Paid</fullName>
            </value>
            <value>
                <fullName>Fully Paid</fullName>
            </value>
            <value>
                <fullName>Refund Cancelled</fullName>
            </value>
            <value>
                <fullName>Failed</fullName>
            </value>
            <value>
                <fullName>Reversed</fullName>
            </value>
            <value>
                <fullName>On Premise Requested</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/ET_Service_Request__c/recordTypes/Vehicle_Inspection.recordType-meta.xml
<RecordType>
    <fullName>Vehicle_Inspection</fullName>
    <active>true</active>
    <label>Vehicle Inspection</label>
</RecordType>

unpackaged/main/default/objects/ETI_Booking__c/ETI_Booking__c.object-meta.xml
<CustomObject>
    <label>Booking</label>
    <nameField>
        <displayFormat>B-{000000}</displayFormat>
        <label>Booking</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Bookings</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

unpackaged/main/default/objects/ETI_Booking__c/fields/Booking_Date__c.field-meta.xml
<CustomField>
    <fullName>Booking_Date__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Booking Date</label>
    <type>Date</type>
</CustomField>

unpackaged/main/default/objects/ETI_Booking__c/fields/Booking_Status__c.field-meta.xml
<CustomField>
    <fullName>Booking_Status__c</fullName>
    <label>Booking Status</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Draft</fullName>
            </value>
            <value>
                <fullName>Booked</fullName>
            </value>
            <value>
                <fullName>Inspection Completed</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
            <value>
                <fullName>Due for Retest</fullName>
            </value>
            <value>
                <fullName>Applied for Retest</fullName>
            </value>
            <value>
                <fullName>Confirmed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/ETI_Booking__c/fields/Is_Auto_Cancelled__c.field-meta.xml
<CustomField>
    <fullName>Is_Auto_Cancelled__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Is Auto Cancelled?</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/objects/ETI_Booking__c/fields/Payment_Status__c.field-meta.xml
<CustomField>
    <fullName>Payment_Status__c</fullName>
    <formula>Text(Service_Request__r.Payment_Status__c )</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Payment Status</label>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/ETI_Booking__c/fields/Service_Request__c.field-meta.xml
<CustomField>
    <fullName>Service_Request__c</fullName>
    <label>Service Request</label>
    <referenceTo>ET_Service_Request__c</referenceTo>
    <relationshipLabel>Bookings</relationshipLabel>
    <relationshipName>Bookings</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

unpackaged/main/default/classes/ETI_BookingsCancellationBatch.cls
global class ETI_BookingsCancellationBatch implements Database.Batchable<sObject>, Schedulable{  
    
    global String queryString;
    public Set<Id> recordIds = new Set<Id>();
    public List<ETI_Booking__c> lstBookingstoDelete = new List<ETI_Booking__c>();
    public string recordTypeDevelopeName = Schema.SObjectType.ET_Service_Request__c.getRecordTypeInfosByDeveloperName().get('Vehicle_Inspection').getRecordTypeId(); 
    public DateTime dt;
    public Integer offset;
    public Datetime local;
    global ETI_BookingsCancellationBatch(set<Id> recIds){
        if(recIds!=null && recIds.size()>0){
            recordIds.addAll(recIds);
        }else {
            dt=Datetime.now().addMinutes(-30);
            offset = UserInfo.getTimezone().getOffset(dt);
            local = dt.addSeconds(offset/1000);
            system.debug('dt>> '+dt+' offset>> '+offset);
            system.debug('local>> '+local);       
            for(ETI_Booking__c bkng:[SELECT Id,Name,Booking_Status__c,Service_Request__c FROM ETI_Booking__c WHERE (Booking_Status__c ='Draft' AND CreatedDate <=:local) OR (Service_Request__r.Payment_Status__c IN ('Not Initiated','Payment Pending') AND Booking_Date__c=YESTERDAY AND Booking_Status__c !='Cancelled')]){
                recordIds.add(bkng.Id);
            }
        }
    }
    global Database.QueryLocator start(Database.BatchableContext bc){ 
        system.debug('recordIds>> '+recordIds);  
        queryString='SELECT Id,Name,Booking_Status__c,Service_Request__c,Cancellation_Reason__c,Is_Auto_Cancelled__c FROM ETI_Booking__c WHERE Id=:recordIds';
        return Database.getQueryLocator(queryString);
    }
    
    global void execute(Database.BatchableContext BC, List<ETI_Booking__c> scope){
        for(ETI_Booking__c booking : scope){
            booking.Booking_Status__c='Cancelled';
            booking.Cancellation_Reason__c=label.ETI_Cancellation_Reason;
            booking.Is_Auto_Cancelled__c=true;
            lstBookingstoDelete.add(booking);
        }
        system.debug('lstBookingstoDelete***'+lstBookingstoDelete.size());
        update lstBookingstoDelete;
    }
    global void finish(Database.BatchableContext BC){
        
    }  
    global void execute(SchedulableContext scon) {
        Database.executeBatch(new ETI_BookingsCancellationBatch(null));
    }
}