unpackaged/main/default/objects/ET_Service_Request__c/ET_Service_Request__c.object-meta.xml
<CustomObject>
    <label>Service Request</label>
    <nameField>
        <displayFormat>SR-{000000}</displayFormat>
        <label>Service Request Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Service Requests</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

unpackaged/main/default/objects/ET_Service_Request__c/fields/Payment_Status__c.field-meta.xml
<CustomField>
    <fullName>Payment_Status__c</fullName>
    <label>Payment Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Not Initiated</fullName>
            </value>
            <value>
                <fullName>Payment Pending</fullName>
            </value>
            <value>
                <fullName>Payment Success</fullName>
            </value>
            <value>
                <fullName>Refund Requested</fullName>
            </value>
            <value>
                <fullName>Await3D</fullName>
            </value>
            <value>
                <fullName>Captured</fullName>
            </value>
            <value>
                <fullName>Partially Paid</fullName>
            </value>
            <value>
                <fullName>Fully Paid</fullName>
            </value>
            <value>
                <fullName>Refund Cancelled</fullName>
            </value>
            <value>
                <fullName>Failed</fullName>
            </value>
            <value>
                <fullName>Reversed</fullName>
            </value>
            <value>
                <fullName>On Premise Requested</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/ET_Service_Request__c/recordTypes/Vehicle_Inspection.recordType-meta.xml
<RecordType>
    <fullName>Vehicle_Inspection</fullName>
    <active>true</active>
    <label>Vehicle Inspection</label>
</RecordType>

unpackaged/main/default/objects/ETI_Booking__c/ETI_Booking__c.object-meta.xml
<CustomObject>
    <label>Booking</label>
    <nameField>
        <displayFormat>B-{000000}</displayFormat>
        <label>Booking</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Bookings</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

unpackaged/main/default/objects/ETI_Booking__c/fields/Booking_Status__c.field-meta.xml
<CustomField>
    <fullName>Booking_Status__c</fullName>
    <label>Booking Status</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Draft</fullName>
            </value>
            <value>
                <fullName>Booked</fullName>
            </value>
            <value>
                <fullName>Inspection Completed</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
            <value>
                <fullName>Due for Retest</fullName>
            </value>
            <value>
                <fullName>Applied for Retest</fullName>
            </value>
            <value>
                <fullName>Confirmed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/ETI_Booking__c/fields/Parent_Booking__c.field-meta.xml
<CustomField>
    <fullName>Parent_Booking__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Parent Booking</label>
    <referenceTo>ETI_Booking__c</referenceTo>
    <relationshipLabel>Bookings</relationshipLabel>
    <relationshipName>Bookings</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/ETI_Booking__c/fields/Payment_Status__c.field-meta.xml
<CustomField>
    <fullName>Payment_Status__c</fullName>
    <formula>Text(Service_Request__r.Payment_Status__c )</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Payment Status</label>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/ETI_Booking__c/fields/Service_Request__c.field-meta.xml
<CustomField>
    <fullName>Service_Request__c</fullName>
    <label>Service Request</label>
    <referenceTo>ET_Service_Request__c</referenceTo>
    <relationshipLabel>Bookings</relationshipLabel>
    <relationshipName>Bookings</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

unpackaged/main/default/classes/ETI_DraftBookingDeletionBatch.cls
global class ETI_DraftBookingDeletionBatch implements Database.Batchable<sObject>, Schedulable{  
    
    global String queryString;
    public Set<Id> recordIds = new Set<Id>();
    public Set<Id> serviceRequesIds = new Set<Id>();
    public Map<Id, Id> serReqIds = new Map<Id, Id>();   
    public Set<Id> sevReqIds = new Set<Id>();
    public List<ET_Service_Request__c> serviceReqDelete = new List<ET_Service_Request__c>();
    public List<ETI_Booking__c> lstBookingstoDelete = new List<ETI_Booking__c>();
    public string recordTypeDevelopeName = Schema.SObjectType.ET_Service_Request__c.getRecordTypeInfosByDeveloperName().get('Vehicle_Inspection').getRecordTypeId(); 
    public DateTime dt;
    public Integer offset;
    public Datetime local;
    
    global ETI_DraftBookingDeletionBatch(){
		dt=Datetime.now().addMinutes(+44);
        offset = UserInfo.getTimezone().getOffset(dt);
        local = dt.addSeconds(offset/1000);
        system.debug('dt>> '+dt+' offset>> '+offset);
        system.debug('local>> '+local);
        /*queryString='SELECT Id,Name,Booking_Status__c,Service_Request__c FROM ETI_Booking__c WHERE Booking_Status__c =\'Draft\'';
queryString+=' AND CreatedDate <=:local'; */
        // queryString='SELECT Id,Name,Booking_Status__c,Service_Request__c,ETI_Draft_Status_Date__c,ETI_Draft_Status_in_Mins__c FROM ETI_Booking__c WHERE Booking_Status__c =\'Draft\'';
        // queryString+=' AND ETI_Draft_Status_Date__c = null AND ETI_Draft_Status_in_Mins__c >15 AND Service_Request__r.Payment_Status__c =\'Not Initiated\' AND Service_Request__r.RecordTypeId=:recordTypeDevelopeName';
        
        queryString='SELECT Id,Name,(SELECT Id,Name,Booking_Status__c,CreatedDate,Service_Request__c FROM Bookings__r WHERE CreatedDate <=:local) FROM ET_Service_Request__c WHERE Payment_Status__c =\'Not Initiated\' AND RecordTypeId =:recordTypeDevelopeName AND CreatedDate <=:local';
        system.debug('queryString>> '+queryString);
    }
    
    public ETI_DraftBookingDeletionBatch(set<Id> recordIds){
        recordIds.addAll(recordIds);
        dt=Datetime.now().addMinutes(+44);
        offset = UserInfo.getTimezone().getOffset(dt);
        local = dt.addSeconds(offset/1000);
        system.debug('dt>> '+dt+' offset>> '+offset);
        system.debug('local>> '+local);
        /*queryString='SELECT Id,Name,Booking_Status__c,Service_Request__c FROM ETI_Booking__c WHERE Booking_Status__c =\'Draft\'';
queryString+=' AND CreatedDate <=:local AND Id IN:recordIds'; */
        //  queryString='SELECT Id,Name,Booking_Status__c,Service_Request__c,ETI_Draft_Status_Date__c,ETI_Draft_Status_in_Mins__c FROM ETI_Booking__c WHERE Booking_Status__c =\'Draft\'';
        //   queryString+=' AND ETI_Draft_Status_Date__c = null AND ETI_Draft_Status_in_Mins__c >15 AND Service_Request__r.Payment_Status__c =\'Not Initiated\' AND Service_Request__r.RecordTypeId=:recordTypeDevelopeName AND Service_Request__c:recordIds';
        
        queryString='SELECT Id,Name,(SELECT Id,Name,Booking_Status__c,CreatedDate,Service_Request__c FROM Bookings__r WHERE CreatedDate <=:local) FROM ET_Service_Request__c WHERE Payment_Status__c =\'Not Initiated\' AND RecordTypeId =:recordTypeDevelopeName AND CreatedDate <=:local AND Id IN:recordIds';
        system.debug('queryString>> '+queryString); 
    }   
    
    global Database.QueryLocator start(Database.BatchableContext bc){        
        return Database.getQueryLocator(queryString);
    }
    
    global void execute(Database.BatchableContext BC, List<Sobject> scope){
        Map<Id,List<ETI_Booking__c>> serviceReqBookingMap = new Map<Id,List<ETI_Booking__c>>();
        /*  for(ETI_Booking__c booking : (List<ETI_Booking__c>) scope){
if(booking.Service_Request__c !=null)
serviceRequesIds.add(booking.Service_Request__c);
}
if(!serviceRequesIds.isEmpty()){
List<ETI_Booking__c> lstBookings = [SELECT Id,Name,Booking_Status__c,Service_Request__c,ETI_Draft_Status_Date__c,ETI_Draft_Status_in_Mins__c FROM ETI_Booking__c WHERE Service_Request__c IN:serviceRequesIds];
for(ETI_Booking__c booking : lstBookings){
List<ETI_Booking__c> bookinglst = serrviceReqBookingMap.get(booking.Service_Request__c);
if(bookinglst == null)
bookinglst = new List<ETI_Booking__c>();
bookinglst.add(booking);
serrviceReqBookingMap.put(booking.Service_Request__c, bookinglst);
}
} */
        for(ET_Service_Request__c srvReq : (List<ET_Service_Request__c>) scope){
            if(srvReq.Bookings__r.size()>0){
                serviceReqBookingMap.put(srvReq.Id, srvReq.Bookings__r);
            }
        }
        List<Id> totalServiceReq = new List<Id>();
        system.debug('serviceReqBookingMap***'+serviceReqBookingMap);
        for(Id serReqId : serviceReqBookingMap.keySet()){
            for(ETI_Booking__c booking : serviceReqBookingMap.get(serReqId)){
               // if(booking.Booking_Status__c == 'Draft' && booking.ETI_Draft_Status_in_Mins__c > 15 && booking.ETI_Draft_Status_Date__c == null){
                 if(booking.Booking_Status__c == 'Draft' && booking.CreatedDate <=local){
                   // system.debug('inside if Name***'+booking.name+'**Status***'+booking.Booking_Status__c);
                    if(!lstBookingstoDelete.contains(booking)){
                        lstBookingstoDelete.add(booking);
                        serReqIds.put(serReqId, serReqId);
                    }
                } else {
                  //  system.debug('inside else Name***'+booking.name+'**Status***'+booking.Booking_Status__c);
                    if(!sevReqIds.contains(serReqId)){
                        sevReqIds.add(serReqId);
                    }
                }
            }
        }

        for(id reqId : sevReqIds){
            if(serReqIds.keyset().contains(reqId)){
                serReqIds.remove(reqId);
            }
        }
        for(id reqId : serReqIds.keySet()){
            serviceReqDelete.add(new ET_Service_Request__c(id = reqId));
        }
        system.debug('lstBookingstoDelete***'+lstBookingstoDelete.size());
        system.debug('serviceReqDelete***'+serviceReqDelete.size());     
         delete lstBookingstoDelete;
         delete serviceReqDelete;
    }
    global void finish(Database.BatchableContext BC){
        
    }  
    global void execute(SchedulableContext scon) {
        Database.executeBatch(new ETI_DraftBookingDeletionBatch());
    }
}