unpackaged/main/default/objects/ET_Service_Request__c/ET_Service_Request__c.object-meta.xml
<CustomObject>
    <label>Service Request</label>
    <nameField>
        <displayFormat>SR-{000000}</displayFormat>
        <label>Service Request Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Service Requests</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

unpackaged/main/default/objects/ET_Service_Request__c/fields/ETST_Payee__c.field-meta.xml
<CustomField>
    <fullName>ETST_Payee__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Payee</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/ET_Service_Request__c/fields/ETST_Service_Type__c.field-meta.xml
<CustomField>
    <fullName>ETST_Service_Type__c</fullName>
    <label>Service Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Yearly</fullName>
            </value>
            <value>
                <fullName>Half Yearly</fullName>
            </value>
            <value>
                <fullName>Quarterly</fullName>
            </value>
            <value>
                <fullName>Monthly</fullName>
            </value>
            <value>
                <fullName>On-demand</fullName>
            </value>
            <value>
                <fullName>Select Dates</fullName>
            </value>
            <value>
                <fullName>One Way</fullName>
            </value>
            <value>
                <fullName>Hourly</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/ETST_Payment__c/ETST_Payment__c.object-meta.xml
<CustomObject>
    <label>Payment</label>
    <nameField>
        <displayFormat>TRN-{00000}</displayFormat>
        <label>ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Payments</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/ETST_Payment__c/fields/ET_Service_Request__c.field-meta.xml
<CustomField>
    <fullName>ET_Service_Request__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Service Request</label>
    <referenceTo>ET_Service_Request__c</referenceTo>
    <relationshipLabel>Payments</relationshipLabel>
    <relationshipName>ET_Payments</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/ETST_Payment__c/fields/ETST_Amount__c.field-meta.xml
<CustomField>
    <fullName>ETST_Amount__c</fullName>
    <label>Amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

unpackaged/main/default/objects/ETST_Payment__c/fields/ETST_AuthorizationCode__c.field-meta.xml
<CustomField>
    <fullName>ETST_AuthorizationCode__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>AuthorizationCode</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/ETST_Payment__c/fields/ETST_Capture_State__c.field-meta.xml
<CustomField>
    <fullName>ETST_Capture_State__c</fullName>
    <defaultValue>IF(  $RecordType.DeveloperName = &#39;On_Premise_Payment&#39;, &#39;SUCCESS&#39;, &#39;&#39;)</defaultValue>
    <encryptionScheme>None</encryptionScheme>
    <label>Capture State</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/ETST_Payment__c/fields/ETST_Cardholder_Name__c.field-meta.xml
<CustomField>
    <fullName>ETST_Cardholder_Name__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Customer Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/ETST_Payment__c/fields/ETST_Currency__c.field-meta.xml
<CustomField>
    <fullName>ETST_Currency__c</fullName>
    <label>Currency</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>AED</fullName>
            </value>
            <value>
                <fullName>USD</fullName>
            </value>
            <value>
                <fullName>EUR</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/ETST_Payment__c/fields/ETST_Payment_Mode__c.field-meta.xml
<CustomField>
    <fullName>ETST_Payment_Mode__c</fullName>
    <label>Payment Mode</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Online</fullName>
            </value>
            <value>
                <fullName>Offline</fullName>
            </value>
            <value>
                <fullName>Cash</fullName>
            </value>
            <value>
                <fullName>Card</fullName>
            </value>
            <value>
                <fullName>Cheque</fullName>
            </value>
            <value>
                <fullName>On Premises</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/ETST_Payment__c/fields/ETST_Payment_State__c.field-meta.xml
<CustomField>
    <fullName>ETST_Payment_State__c</fullName>
    <defaultValue>IF( $RecordType.DeveloperName = &#39;On_Premise_Payment&#39; , &#39;SUCCESS&#39;, &#39;&#39;)</defaultValue>
    <encryptionScheme>None</encryptionScheme>
    <label>Payment State</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/classes/ET_SpeaReconciliationControllerBatchTest.cls
/************************************************************************************************************************
 * Name               : ET_SpeaReconciliationControllerBatchTest                                                        *
 * Description        : Apex Test Class for ET_SpeaReconciliationControllerBatch,ET_FinanceControllerCalloutBatch       *
 * Created Date       : 22/Apr/2024                                                                                     *
 * Created By         : Santosh(SMAARTT)                                                                                *
 * -----------------------------------------------------------------------------------------------                      *
 * VERSION   AUTHOR      DATE                COMMENTS                                                                   *
 * 1.0       Santosh     22/Apr/2024         Initial Draft.                                                             *
 ***********************************************************************************************************************/
@isTest
public class ET_SpeaReconciliationControllerBatchTest {
    @isTest
    static void testBatchExecution() {
        ET_Service_Request__c SRREC = new ET_Service_Request__c();
        SRREC.ETST_Service_Type__c = 'Quarterly';
        SRREC.ETST_Payee__c = 'Parent';
        Insert SRREC;
        
        List<ETST_Payment__c> testPayments = new List<ETST_Payment__c>();
        for (Integer i = 0; i < 3; i++) {
            ETST_Payment__c testPayment = new ETST_Payment__c(
                ET_Service_Request__c = SRREC.Id,
                ETST_Payment_Mode__c = 'Online',
                ETST_Amount__c = 2887.00,
                ETST_Currency__c = 'AED',
                ETST_Payment_State__c = 'CAPTURED',
                ETST_Capture_State__c = 'SUCCESS',
                ETST_AuthorizationCode__c = 'TestAuthCode' + i,
                ETST_Cardholder_Name__c = 'emirates transport'
            );
            testPayments.add(testPayment);
        }
        Insert testPayments;
        
        Test.startTest();
        ET_SpeaReconciliationControllerBatch batchInstance = new ET_SpeaReconciliationControllerBatch();
        batchInstance.givenDateTime = System.now();
        batchInstance.execute(null, testPayments);
        Database.executeBatch(batchInstance,1);
        Test.stopTest();
    }
}