unpackaged/main/default/objects/ET_Service_Request__c/ET_Service_Request__c.object-meta.xml
<CustomObject>
    <label>Service Request</label>
    <nameField>
        <displayFormat>SR-{000000}</displayFormat>
        <label>Service Request Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Service Requests</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

unpackaged/main/default/objects/ET_Service_Request__c/fields/ET_Account__c.field-meta.xml
<CustomField>
    <fullName>ET_Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Service Requests (Account)</relationshipLabel>
    <relationshipName>Service_Requests</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/ET_Service_Request__c/fields/ETST_Service_Type__c.field-meta.xml
<CustomField>
    <fullName>ETST_Service_Type__c</fullName>
    <label>Service Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Yearly</fullName>
            </value>
            <value>
                <fullName>Half Yearly</fullName>
            </value>
            <value>
                <fullName>Quarterly</fullName>
            </value>
            <value>
                <fullName>Monthly</fullName>
            </value>
            <value>
                <fullName>On-demand</fullName>
            </value>
            <value>
                <fullName>Select Dates</fullName>
            </value>
            <value>
                <fullName>One Way</fullName>
            </value>
            <value>
                <fullName>Hourly</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/ET_Service_Request__c/recordTypes/ETC_Car_Booking_Services.recordType-meta.xml
<RecordType>
    <fullName>ETC_Car_Booking_Services</fullName>
    <active>true</active>
    <label>Car Booking Services</label>
</RecordType>

unpackaged/main/default/objects/ETCAR_Service_Request_Line_Item__c/ETCAR_Service_Request_Line_Item__c.object-meta.xml
<CustomObject>
    <description>To Capture Selected Car Details</description>
    <label>Vehicle Booking</label>
    <nameField>
        <displayFormat>Item-{0000}</displayFormat>
        <label>Service Request Line Item Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Vehicle Bookings</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

unpackaged/main/default/objects/ETCAR_Service_Request_Line_Item__c/fields/ETST_Pick_Up_From__c.field-meta.xml
<CustomField>
    <fullName>ETST_Pick_Up_From__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Pickup From</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/ETCAR_Service_Request_Line_Item__c/fields/ETST_Service_Type__c.field-meta.xml
<CustomField>
    <fullName>ETST_Service_Type__c</fullName>
    <label>Service Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>One Way</fullName>
            </value>
            <value>
                <fullName>Hourly</fullName>
            </value>
            <value>
                <fullName>Rental</fullName>
            </value>
            <value>
                <fullName>Half Yearly</fullName>
                <isActive>false</isActive>
                <label>Half Yearly</label>
            </value>
            <value>
                <fullName>Monthly</fullName>
                <isActive>false</isActive>
                <label>Monthly</label>
            </value>
            <value>
                <fullName>On-Demand</fullName>
                <isActive>false</isActive>
                <label>On-Demand</label>
            </value>
            <value>
                <fullName>Quarterly</fullName>
                <isActive>false</isActive>
                <label>Quarterly</label>
            </value>
            <value>
                <fullName>Select Dates</fullName>
                <isActive>false</isActive>
                <label>Select Dates</label>
            </value>
            <value>
                <fullName>Yearly</fullName>
                <isActive>false</isActive>
                <label>Yearly</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/ETST_Payment__c/ETST_Payment__c.object-meta.xml
<CustomObject>
    <label>Payment</label>
    <nameField>
        <displayFormat>TRN-{00000}</displayFormat>
        <label>ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Payments</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/ETST_Payment__c/fields/ET_Service_Request__c.field-meta.xml
<CustomField>
    <fullName>ET_Service_Request__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Service Request</label>
    <referenceTo>ET_Service_Request__c</referenceTo>
    <relationshipLabel>Payments</relationshipLabel>
    <relationshipName>ET_Payments</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/ETST_Payment__c/fields/ETST_Amount__c.field-meta.xml
<CustomField>
    <fullName>ETST_Amount__c</fullName>
    <label>Amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

unpackaged/main/default/objects/ETST_Payment__c/fields/ETST_Payment_Mode__c.field-meta.xml
<CustomField>
    <fullName>ETST_Payment_Mode__c</fullName>
    <label>Payment Mode</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Online</fullName>
            </value>
            <value>
                <fullName>Offline</fullName>
            </value>
            <value>
                <fullName>Cash</fullName>
            </value>
            <value>
                <fullName>Card</fullName>
            </value>
            <value>
                <fullName>Cheque</fullName>
            </value>
            <value>
                <fullName>On Premises</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/ETST_Payment__c/fields/ETST_Payment_State__c.field-meta.xml
<CustomField>
    <fullName>ETST_Payment_State__c</fullName>
    <defaultValue>IF( $RecordType.DeveloperName = &#39;On_Premise_Payment&#39; , &#39;SUCCESS&#39;, &#39;&#39;)</defaultValue>
    <encryptionScheme>None</encryptionScheme>
    <label>Payment State</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/classes/ETC_UpdateItineraryDetails.cls
public class ETC_UpdateItineraryDetails {
    
    @AuraEnabled
    public static ETCAR_Service_Request_Line_Item__c getRequestDetials(String recId) {  
        
        return [ SELECT Id, Name, ETST_Pick_Up_From__c, ETST_Service_Type__c FROM ETCAR_Service_Request_Line_Item__c WHERE Id =: recId ];   
    }  
    @AuraEnabled
    public static String getAddressSet(String SearchText){
        return ETST_AddressSearchController.getAddressSet(SearchText);
    } 
    @AuraEnabled
    public static String getAddressDetailsByPlaceId(String PlaceID){
        return ETST_AddressSearchController.getAddressDetailsByPlaceId(PlaceID);
    }
    /*@AuraEnabled
    public static List<ETST_Payment__c> getPaymentHistory(Date stDate, Date enDate){
        system.debug('stDate '+stDate+' enDate '+enDate);
        String userAccountId=ETC_UtilityClass.getAccountId();
        String errStr;
        Id carServicesRecordTypeId = Schema.SObjectType.ET_Service_Request__c.getRecordTypeInfosByDeveloperName().get('ETC_Car_Booking_Services').getRecordTypeId();
        try{
            // String userAccountId=getAccountId();   
            String qryString = 'Select Id,name,ETST_Amount__c,CreatedDate,ETST_Payment_Mode__c,ET_Service_Request__r.ET_Account__r.Name,ETST_Payment_State__c FROM ETST_Payment__c where ET_Service_Request__r.ET_Account__c =:userAccountId AND (ET_Service_Request__r.RecordTypeId=:rntRecordTypeId OR ET_Service_Request__r.RecordTypeId=:carServicesRecordTypeId)';
            if(stDate!=NULL && enDate!=NULL)
                qryString += ' AND CreatedDate >=:stDate AND CreatedDate <=:enDate';
            qryString +=+' order by CreatedDate desc';
            system.debug('qryString '+qryString);
            List<ETST_Payment__c> myPayments = Database.query(qryString);
            return myPayments;
        }catch (Exception e) {
            errStr = '';// JSON.serialize(ETI_B2B_VehicleController.buildErrorResponse('getPaymentHistory', e.getMessage(), e.getStackTraceString()));
            AuraHandledException ahe = new AuraHandledException(errStr);
            ahe.setMessage(errStr);
            throw ahe;
        }
    }*/
}