unpackaged/main/default/objects/ET_Service_Request__c/ET_Service_Request__c.object-meta.xml
<CustomObject>
    <label>Service Request</label>
    <nameField>
        <displayFormat>SR-{000000}</displayFormat>
        <label>Service Request Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Service Requests</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

unpackaged/main/default/objects/ETST_Payment__c/ETST_Payment__c.object-meta.xml
<CustomObject>
    <label>Payment</label>
    <nameField>
        <displayFormat>TRN-{00000}</displayFormat>
        <label>ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Payments</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/ETST_Payment__c/fields/ET_Service_Request__c.field-meta.xml
<CustomField>
    <fullName>ET_Service_Request__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Service Request</label>
    <referenceTo>ET_Service_Request__c</referenceTo>
    <relationshipLabel>Payments</relationshipLabel>
    <relationshipName>ET_Payments</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/ETST_Payment__c/fields/ETI_IsUpdatedByBatch__c.field-meta.xml
<CustomField>
    <fullName>ETI_IsUpdatedByBatch__c</fullName>
    <defaultValue>false</defaultValue>
    <label>IsUpdatedByBatch</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/objects/ETST_Payment__c/fields/ETST_Payment_State__c.field-meta.xml
<CustomField>
    <fullName>ETST_Payment_State__c</fullName>
    <defaultValue>IF( $RecordType.DeveloperName = &#39;On_Premise_Payment&#39; , &#39;SUCCESS&#39;, &#39;&#39;)</defaultValue>
    <encryptionScheme>None</encryptionScheme>
    <label>Payment State</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/ETST_Payment__c/fields/ExternalID__c.field-meta.xml
<CustomField>
    <fullName>ExternalID__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <externalId>true</externalId>
    <label>ExternalID</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/classes/ETI_BulkPayment_AWAIT_3DS_Batch.cls
/*
* File Name:ETI_BulkPayment_AWAIT_3DS_Batch
* Author : Lahari
* CreatedDate : 09/5/2021
* Modification Purpose
* * 1. Lahari: To Update payment status
* * 2.Janardhan: Updated on 18-08-2021
*/
global class ETI_BulkPayment_AWAIT_3DS_Batch implements Database.Batchable<sObject>, Database.AllowsCallouts, Database.Stateful{  
     global String queryString;
     
    global Database.QueryLocator start(Database.BatchableContext bc){ 
        queryString='SELECT Id, ET_Service_Request__c, ETST_Payment_State__c,ExternalID__c FROM ETST_Payment__c WHERE  ((ETST_Payment_State__c=\'AWAIT_3DS\' OR ETST_Payment_State__c=null) AND ExternalId__c!=null) AND ETI_IsUpdatedByBatch__c = false';
        return Database.getQueryLocator(queryString);
    }
    
    global void execute(Database.BatchableContext BC, List<ETST_Payment__c> scope){
        System.debug('list of records ::'+scope.size());
        for(ETST_Payment__c pay : scope)
        {	
            if(!test.isRunningTest()){
            ETI_On_Premise_Payment_Ctrl.isFirstTime = true;
            ET_Payment_Controller.getPaymentStatus(pay.ExternalId__c, true);
            }
        }
        
    }
    global void finish(Database.BatchableContext BC){
       
    }  
   
}