unpackaged/main/default/objects/ET_Service_Request__c/ET_Service_Request__c.object-meta.xml
<CustomObject>
    <label>Service Request</label>
    <nameField>
        <displayFormat>SR-{000000}</displayFormat>
        <label>Service Request Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Service Requests</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

unpackaged/main/default/objects/ET_Service_Request__c/fields/ETST_Drop_Off_To__c.field-meta.xml
<CustomField>
    <fullName>ETST_Drop_Off_To__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Drop-Off To</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/ET_Service_Request__c/fields/ETST_Paid_By__c.field-meta.xml
<CustomField>
    <fullName>ETST_Paid_By__c</fullName>
    <label>Paid By</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Self</fullName>
                <default>true</default>
                <label>Self</label>
            </value>
            <value>
                <fullName>Employer</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/ET_Service_Request__c/fields/ETST_Pick_Up_End_Date__c.field-meta.xml
<CustomField>
    <fullName>ETST_Pick_Up_End_Date__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Pickup End Date</label>
    <type>Date</type>
</CustomField>

unpackaged/main/default/objects/ET_Service_Request__c/fields/ETST_Pick_Up_Start_Date__c.field-meta.xml
<CustomField>
    <fullName>ETST_Pick_Up_Start_Date__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Request Date</label>
    <type>Date</type>
</CustomField>

unpackaged/main/default/objects/ET_Service_Request__c/fields/ETST_School_Name__c.field-meta.xml
<CustomField>
    <fullName>ETST_School_Name__c</fullName>
    <formula>ETST_Student__r.ETST_School_Name__r.Name</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>School Name</label>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/ET_Service_Request__c/fields/ETST_Service_Type__c.field-meta.xml
<CustomField>
    <fullName>ETST_Service_Type__c</fullName>
    <label>Service Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Yearly</fullName>
            </value>
            <value>
                <fullName>Half Yearly</fullName>
            </value>
            <value>
                <fullName>Quarterly</fullName>
            </value>
            <value>
                <fullName>Monthly</fullName>
            </value>
            <value>
                <fullName>On-demand</fullName>
            </value>
            <value>
                <fullName>Select Dates</fullName>
            </value>
            <value>
                <fullName>One Way</fullName>
            </value>
            <value>
                <fullName>Hourly</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/ET_Service_Request__c/fields/ETST_Student__c.field-meta.xml
<CustomField>
    <fullName>ETST_Student__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Student</label>
    <referenceTo>ETST_Student__c</referenceTo>
    <relationshipName>ETST_Transport_Requests</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/ET_Service_Request__c/fields/ETST_Student_Name__c.field-meta.xml
<CustomField>
    <fullName>ETST_Student_Name__c</fullName>
    <formula>IF(ETST_Student__c !=null, (ETST_Student__r.ETST_First_Name__c+&#39; &#39;+ETST_Student__r.Name), &#39;&#39;)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Student Name</label>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/ET_Service_Request__c/fields/ETST_Transport_Type__c.field-meta.xml
<CustomField>
    <fullName>ETST_Transport_Type__c</fullName>
    <label>Transport Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Two Way</fullName>
            </value>
            <value>
                <fullName>Pick up only</fullName>
            </value>
            <value>
                <fullName>Drop off only</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/ETST_Invoice_Address__mdt/ETST_Invoice_Address__mdt.object-meta.xml
<CustomObject>
    <label>ETST Invoice Address</label>
    <pluralLabel>ETST Invoice Address</pluralLabel>
</CustomObject>

unpackaged/main/default/objects/ETST_Invoice_Address__mdt/fields/Line_1__c.field-meta.xml
<CustomField>
    <fullName>Line_1__c</fullName>
    <label>Line 1</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/ETST_Invoice_Address__mdt/fields/Line_2__c.field-meta.xml
<CustomField>
    <fullName>Line_2__c</fullName>
    <label>Line 2</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/ETST_Invoice_Address__mdt/fields/Line_3__c.field-meta.xml
<CustomField>
    <fullName>Line_3__c</fullName>
    <label>Line 3</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/ETST_Invoice_Address__mdt/fields/Line_4__c.field-meta.xml
<CustomField>
    <fullName>Line_4__c</fullName>
    <label>Line 4</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/ETST_Invoice_Address__mdt/fields/Line_5__c.field-meta.xml
<CustomField>
    <fullName>Line_5__c</fullName>
    <label>Line 5</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/ETST_Invoice_Address__mdt/fields/Line_6__c.field-meta.xml
<CustomField>
    <fullName>Line_6__c</fullName>
    <label>Line 6</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/ETST_School__c/ETST_School__c.object-meta.xml
<CustomObject>
    <label>School</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>School Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Schools</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/ETST_Student__c/ETST_Student__c.object-meta.xml
<CustomObject>
    <label>Student</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Last Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Students</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

unpackaged/main/default/objects/ETST_Student__c/fields/ETST_Account_Name__c.field-meta.xml
<CustomField>
    <fullName>ETST_Account_Name__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Parent</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Account.RecordTypeId</field>
            <operation>equals</operation>
            <value>Person (B2C)</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Students</relationshipLabel>
    <relationshipName>Students</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/ETST_Student__c/fields/ETST_School_Name__c.field-meta.xml
<CustomField>
    <fullName>ETST_School_Name__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>School Name</label>
    <referenceTo>ETST_School__c</referenceTo>
    <relationshipLabel>Students</relationshipLabel>
    <relationshipName>Students</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/ETST_Student__c/fields/Service_Request__c.field-meta.xml
<CustomField>
    <fullName>Service_Request__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Service Request</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/objects/Invoice__c/Invoice__c.object-meta.xml
<CustomObject>
    <label>Invoice</label>
    <nameField>
        <displayFormat>INV-{000000}</displayFormat>
        <label>Invoice No</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Invoices</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Invoice__c/fields/ETST_Active__c.field-meta.xml
<CustomField>
    <fullName>ETST_Active__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Active</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/objects/Invoice__c/fields/Service_Request__c.field-meta.xml
<CustomField>
    <fullName>Service_Request__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Service Request</label>
    <referenceTo>ET_Service_Request__c</referenceTo>
    <relationshipLabel>Invoices</relationshipLabel>
    <relationshipName>Invoices</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Invoice__c/fields/Total_Inv_Amount__c.field-meta.xml
<CustomField>
    <fullName>Total_Inv_Amount__c</fullName>
    <label>Total Inv Amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

unpackaged/main/default/classes/ETST_InvoiceController.cls
public class ETST_InvoiceController {
    public ET_Service_Request__c transportRequest {get;set;}
    public List<Invoice__c> invoiceList {get;set;}
    public string recordId;
    public string employerAddress {get;set;}
    public datetime dueDate {get;set;}
    public string selfAddress {get;set;}
    public string schoolName {get;set;}
    public boolean diyarschool{get;set;}
    public string address {get;set;}
    public static ETST_Invoice_Address__mdt invoiceAddress {get;set;}
    
    public ETST_InvoiceController(){
        recordId = Apexpages.currentPage().getParameters().get('id');
        system.debug('recordId-->'+recordId);
        invoiceList = new List<Invoice__c>();
        invoiceAddress = new ETST_Invoice_Address__mdt();
        diyarschool=false;
        loadInvoices();
        if(invoiceList.size()==0){
            
        } 
    }
    public void loadInvoices(){
        invoiceAddress = [SELECT Id,DeveloperName,Line_1__c,Line_2__c,Line_3__c,Line_4__c,Line_5__c,Line_6__c
                          FROM ETST_Invoice_Address__mdt WHERE DeveloperName='Invoice_Address' LIMIT 1];
        invoiceList = [Select Id,Name,CreatedDate,Total_Inv_Amount__c,Service_Request__r.ETST_Service_Type__c,Service_Request__r.ETST_Transport_Type__c,Service_Request__r.Name,
                       Service_Request__r.ETST_Pick_Up_From__c,Service_Request__r.ETST_Student_Name__c ,Service_Request__r.ETST_Drop_Off_To__c,Service_Request__r.ETST_Pick_Up_Start_Date__c,Service_Request__r.ETST_Pick_Up_End_Date__c,Service_Request__r.ETST_Paid_By__c,Service_Request__r.ETST_Student__r.ETST_Account_Name__c,Service_Request__r.ETST_Student__r.ETST_School_Name__r.Name from Invoice__c WHERE Service_Request__c=:recordId and ETST_Active__c=true limit 1];
        if(invoiceList.size()>0){ 
            dueDate = invoiceList[0].CreatedDate.addDays(5);
            schoolName = invoiceList[0].Service_Request__r.ETST_Student__r.ETST_School_Name__r.Name;
            if(schoolName!='' && schoolName!=null)
            {
            if(schoolName.contains('Diyar'))
                diyarschool=true;
            else
                diyarschool=false;
            }
            List<Account> lstAccounts = [Select Id,name,BillingStreet,BillingCity,BillingState,BillingCountry,(Select Id,Name,ET_Line_1__c,ET_Line_2__c,ET_City__c,ET_Country__c from Addresses__r WHERE ET_Is_Primary__c=true) from Account WHERE Id=:invoiceList[0].Service_Request__r.ETST_Student__r.ETST_School_Name__c limit 1];
            if(lstAccounts.size()>0){
                address = lstAccounts[0].BillingStreet+ '\n' + lstAccounts[0].BillingCity +'\n' +lstAccounts[0].BillingCountry; 
                if(invoiceList[0].Service_Request__r.ETST_Paid_By__c == 'Self'){
                    selfAddress = lstAccounts[0].BillingStreet+ '\n' + lstAccounts[0].BillingCity +'\n' +lstAccounts[0].BillingCountry; 
                }
                else if(invoiceList[0].Service_Request__r.ETST_Paid_By__c == 'Employer' && lstAccounts[0].Addresses__r.size()>0){
                    employerAddress = lstAccounts[0].Addresses__r[0].ET_Line_1__c+ '\n' + lstAccounts[0].Addresses__r[0].ET_Line_2__c + '\n' +lstAccounts[0].Addresses__r[0].ET_City__c+ '\n' +lstAccounts[0].Addresses__r[0].ET_Country__c; 
                }
            }
        }
    } 
    
}