unpackaged/main/default/objects/Account/fields/Category__c.field-meta.xml
<CustomField>
    <fullName>Category__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Category</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Account/fields/ETST_Date_of_Birth__c.field-meta.xml
<CustomField>
    <fullName>ETST_Date_of_Birth__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Date of Birth</label>
    <type>Date</type>
</CustomField>

unpackaged/main/default/objects/Account/fields/ETST_Division__c.field-meta.xml
<CustomField>
    <fullName>ETST_Division__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Division</label>
    <type>TextArea</type>
</CustomField>

unpackaged/main/default/objects/Account/fields/ETST_Emirates_Id__c.field-meta.xml
<CustomField>
    <fullName>ETST_Emirates_Id__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Emirates Id</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Account/fields/ETST_Gender__c.field-meta.xml
<CustomField>
    <fullName>ETST_Gender__c</fullName>
    <label>Gender</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Male</fullName>
            </value>
            <value>
                <fullName>Female</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Account/fields/ETST_Nationality__c.field-meta.xml
<CustomField>
    <fullName>ETST_Nationality__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Nationality</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Account/recordTypes/Business_School.recordType-meta.xml
<RecordType>
    <fullName>Business_School</fullName>
    <active>true</active>
    <label>Business (B2B) - School</label>
</RecordType>

unpackaged/main/default/objects/Case/fields/ETST_Student__c.field-meta.xml
<CustomField>
    <fullName>ETST_Student__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Student</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>ETST_Student__c.ETST_School__r.Id</field>
            <operation>equals</operation>
            <valueField>$Source.AccountId</valueField>
        </filterItems>
        <isOptional>true</isOptional>
    </lookupFilter>
    <referenceTo>ETST_Student__c</referenceTo>
    <relationshipLabel>Cases</relationshipLabel>
    <relationshipName>Cases</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Case/fields/Sales_Agreement__c.field-meta.xml
<CustomField>
    <fullName>Sales_Agreement__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Sales Agreement</label>
    <referenceTo>ET_Sales_Agreement__c</referenceTo>
    <relationshipLabel>Cases</relationshipLabel>
    <relationshipName>Cases</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/ET_Sales_Agreement__c/ET_Sales_Agreement__c.object-meta.xml
<CustomObject>
    <label>Sales Agreement</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Sales Agreement</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Sales Agreements</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/ET_Sales_Agreement__c/fields/Category__c.field-meta.xml
<CustomField>
    <fullName>Category__c</fullName>
    <label>Category</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Transportation</fullName>
            </value>
            <value>
                <fullName>School Transportation</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/ET_Sales_Agreement__c/fields/Customer_PO_No__c.field-meta.xml
<CustomField>
    <fullName>Customer_PO_No__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Customer PO No</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/ET_Sales_Agreement__c/fields/Salesforce_Customer__c.field-meta.xml
<CustomField>
    <fullName>Salesforce_Customer__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Customer</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Sales Agreements</relationshipLabel>
    <relationshipName>Sales_Agreements</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/ET_User_Files__c/ET_User_Files__c.object-meta.xml
<CustomObject>
    <label>User Files</label>
    <nameField>
        <displayFormat>UF-{000000}</displayFormat>
        <label>User Files Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>User Files</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/ET_User_Files__c/fields/Doc_Id__c.field-meta.xml
<CustomField>
    <fullName>Doc_Id__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Doc Id</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/ETST_School__c/ETST_School__c.object-meta.xml
<CustomObject>
    <label>School</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>School Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Schools</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/ETST_Student__c/ETST_Student__c.object-meta.xml
<CustomObject>
    <label>Student</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Last Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Students</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

unpackaged/main/default/objects/ETST_Student__c/fields/ETST_Date_of_Birth__c.field-meta.xml
<CustomField>
    <fullName>ETST_Date_of_Birth__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Date of Birth</label>
    <type>Date</type>
</CustomField>

unpackaged/main/default/objects/ETST_Student__c/fields/ETST_Division__c.field-meta.xml
<CustomField>
    <fullName>ETST_Division__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Division</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/ETST_Student__c/fields/ETST_Email__c.field-meta.xml
<CustomField>
    <fullName>ETST_Email__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Email</label>
    <type>Email</type>
</CustomField>

unpackaged/main/default/objects/ETST_Student__c/fields/ETST_Emirate__c.field-meta.xml
<CustomField>
    <fullName>ETST_Emirate__c</fullName>
    <label>Emirate</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Abu Dhabi</fullName>
            </value>
            <value>
                <fullName>Dubai</fullName>
            </value>
            <value>
                <fullName>Ajman</fullName>
            </value>
            <value>
                <fullName>Fujairah</fullName>
            </value>
            <value>
                <fullName>Ras al Khaimah</fullName>
            </value>
            <value>
                <fullName>Sharjah</fullName>
            </value>
            <value>
                <fullName>Umm al Quwain</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/ETST_Student__c/fields/ETST_Emirates_Id__c.field-meta.xml
<CustomField>
    <fullName>ETST_Emirates_Id__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Emirates Id</label>
    <length>100</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

unpackaged/main/default/objects/ETST_Student__c/fields/ETST_ESIS_No__c.field-meta.xml
<CustomField>
    <fullName>ETST_ESIS_No__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>ESIS No</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/ETST_Student__c/fields/ETST_Gender__c.field-meta.xml
<CustomField>
    <fullName>ETST_Gender__c</fullName>
    <label>Gender</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Male</fullName>
            </value>
            <value>
                <fullName>Female</fullName>
            </value>
            <value>
                <fullName>Other</fullName>
                <isActive>false</isActive>
                <label>Other</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/ETST_Student__c/fields/ETST_Nationality__c.field-meta.xml
<CustomField>
    <fullName>ETST_Nationality__c</fullName>
    <label>Nationality</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>ETST_Nationality</valueSetName>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/ETST_Student__c/fields/ETST_School__c.field-meta.xml
<CustomField>
    <fullName>ETST_School__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>School</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Account.RecordTypeId</field>
            <operation>equals</operation>
            <value>Business (B2B) - School</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Students (School)</relationshipLabel>
    <relationshipName>ETST_Students</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/ETST_Student__c/fields/ETST_Student_Id__c.field-meta.xml
<CustomField>
    <fullName>ETST_Student_Id__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Student Id</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/SALine_Assigned_Vehicle__c/SALine_Assigned_Vehicle__c.object-meta.xml
<CustomObject>
    <description>This is used to link vehicle with Sales Agreement Lines</description>
    <label>Assigned Vehicle</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Associated Vehicle  Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Assigned Vehicles</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/SALine_Assigned_Vehicle__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Associated Vehicles</relationshipLabel>
    <relationshipName>Associated_Vehicles</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/SALine_Assigned_Vehicle__c/fields/Assign_End_Date__c.field-meta.xml
<CustomField>
    <fullName>Assign_End_Date__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Assign End Date</label>
    <type>DateTime</type>
</CustomField>

unpackaged/main/default/objects/SALine_Assigned_Vehicle__c/fields/Sales_Agreement__c.field-meta.xml
<CustomField>
    <fullName>Sales_Agreement__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Sales Agreement</label>
    <referenceTo>ET_Sales_Agreement__c</referenceTo>
    <relationshipName>Associated_Vehicles</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/User/fields/ETST_Emirates_ID__c.field-meta.xml
<CustomField>
    <fullName>ETST_Emirates_ID__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Emirates ID</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/globalValueSets/ETST_Nationality.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Afghanistan</fullName>
    </customValue>
    <customValue>
        <fullName>Aland Islands</fullName>
    </customValue>
    <customValue>
        <fullName>Albania</fullName>
    </customValue>
    <customValue>
        <fullName>Algeria</fullName>
    </customValue>
    <customValue>
        <fullName>Andorra</fullName>
    </customValue>
    <customValue>
        <fullName>Angola</fullName>
    </customValue>
    <customValue>
        <fullName>Anguilla</fullName>
    </customValue>
    <customValue>
        <fullName>Antarctica</fullName>
    </customValue>
    <customValue>
        <fullName>Antigua and Barbuda</fullName>
    </customValue>
    <customValue>
        <fullName>Argentina</fullName>
    </customValue>
    <customValue>
        <fullName>Armenia</fullName>
    </customValue>
    <customValue>
        <fullName>Aruba</fullName>
    </customValue>
    <customValue>
        <fullName>Australia</fullName>
    </customValue>
    <customValue>
        <fullName>Austria</fullName>
    </customValue>
    <customValue>
        <fullName>Azerbaijan</fullName>
    </customValue>
    <customValue>
        <fullName>Bahamas</fullName>
    </customValue>
    <customValue>
        <fullName>Bahrain</fullName>
    </customValue>
    <customValue>
        <fullName>Bangladesh</fullName>
    </customValue>
    <customValue>
        <fullName>Barbados</fullName>
    </customValue>
    <customValue>
        <fullName>Belarus</fullName>
    </customValue>
    <customValue>
        <fullName>Belgium</fullName>
    </customValue>
    <customValue>
        <fullName>Belize</fullName>
    </customValue>
    <customValue>
        <fullName>Benin</fullName>
    </customValue>
    <customValue>
        <fullName>Bermuda</fullName>
    </customValue>
    <customValue>
        <fullName>Bhutan</fullName>
    </customValue>
    <customValue>
        <fullName>Bolivia, Plurinational State of</fullName>
    </customValue>
    <customValue>
        <fullName>Bonaire, Sint Eustatius and Saba</fullName>
    </customValue>
    <customValue>
        <fullName>Bosnia and Herzegovina</fullName>
    </customValue>
    <customValue>
        <fullName>Botswana</fullName>
    </customValue>
    <customValue>
        <fullName>Bouvet Island</fullName>
    </customValue>
    <customValue>
        <fullName>India</fullName>
    </customValue>
    <customValue>
        <fullName>United Kingdom</fullName>
    </customValue>
    <masterLabel>Nationality</masterLabel>
</GlobalValueSet>

unpackaged/main/default/classes/ET_CustomDashboardController_Test.cls
@isTest
public class ET_CustomDashboardController_Test {
    @isTest Public static void customDashboardTest(){
        Account acc = new Account();
        acc.RecordTypeid=Schema.SObjectType.Account.getRecordTypeInfosByDeveloperName().get('Business_School').getRecordTypeId();
        acc.Name = 'MINISTRY OF EDUCATION1';
        acc.phone= '01123353';
        acc.billingcity='London';
        acc.billingpostalcode='SW1635HJ';
        acc.billingcountry='United Kingdom';
        acc.billingstreet='address 1';
        insert acc;
        
        Contact c = new Contact(LastName = 'Contact Last Name', AccountId = acc.id);
        insert c; 
        
        User user = new User();
        user.ProfileID = [Select Id From Profile Where Name='Partner Community login User'].id;
        user.EmailEncodingKey = 'ISO-8859-1';
        user.LanguageLocaleKey = 'en_US';
        user.TimeZoneSidKey = 'America/New_York';
        user.LocaleSidKey = 'en_US';
        user.FirstName = 'first';
        user.LastName = 'last';
        user.Username = 'test12@uniquedomain.com';
        user.CommunityNickname = 'testUser123';
        user.Alias = 't1';
        user.Email = 'no@email.com';
        user.IsActive = true;
        user.ContactId = c.Id;
        insert user; 
        
        ET_Sales_Agreement__c etSales = new ET_Sales_Agreement__c();
        etSales.Customer_PO_No__c = 'Test';
        etSales.Salesforce_Customer__c = acc.id;
        etSales.Category__c = 'Transportation';
        insert etSales;
        
        ETST_Student__c estud = new ETST_Student__c(ETST_Email__c='abc@xyz.com',ETST_Emirate__c='Dubai',Name='test Student',
                                                    ETST_Nationality__c='India',ETST_Emirates_Id__c='784-2131-3212131-2',
                                                    ETST_ESIS_No__c='2302',ETST_Division__c='5',ETST_Gender__c='Male',ETST_School__c = acc.Id,
                                                    ETST_Student_Id__c='1223',ETST_Date_of_Birth__c=system.today()-1200);
        insert estud;
        
        SALine_Assigned_Vehicle__c vehicle=new SALine_Assigned_Vehicle__c();
        vehicle.Name='vehcle 1';
        vehicle.Account__c = acc.Id;
        vehicle.Sales_Agreement__c = etSales.Id;
        vehicle.Assign_End_Date__c =system.today();
        insert vehicle;
        
        Case cas = new Case(contactId = c.Id);
        insert cas;
        
        ET_User_Files__c newFile = new ET_User_Files__c();
        newFile.File_Name__c ='test file';
        newFile.Doc_Id__c ='123';
        insert newFile;
        
        system.runAs(user){
            Test.startTest();
            ET_CustomDashboardController.getDashboardData();
            ET_CustomDashboardController.getSpecialRequestDashboardData();
            Test.stopTest();
        }
    }
}