unpackaged/main/default/objects/Account/fields/Chassis_Number__c.field-meta.xml
<CustomField>
    <fullName>Chassis_Number__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Chassis Number</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Account/fields/ETSALES_Customer_Account_Id__c.field-meta.xml
<CustomField>
    <fullName>ETSALES_Customer_Account_Id__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <externalId>true</externalId>
    <label>Customer Oracle ID</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Account/fields/Integration_Message__c.field-meta.xml
<CustomField>
    <fullName>Integration_Message__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Integration Message</label>
    <length>100000</length>
    <type>LongTextArea</type>
</CustomField>

unpackaged/main/default/objects/ET_Oracle_REST_Endpoints__mdt/ET_Oracle_REST_Endpoints__mdt.object-meta.xml
<CustomObject>
    <description>This meta data created to store all the REST endpoint and authentication details</description>
    <label>ET_Oracle_REST_Endpoint</label>
    <pluralLabel>ET_Oracle_REST_Endpoints</pluralLabel>
</CustomObject>

unpackaged/main/default/objects/ET_Oracle_REST_Endpoints__mdt/fields/Dev_Endpoint__c.field-meta.xml
<CustomField>
    <fullName>Dev_Endpoint__c</fullName>
    <label>Dev Endpoint</label>
    <type>Url</type>
</CustomField>

unpackaged/main/default/objects/ET_Oracle_REST_Endpoints__mdt/fields/LiveEndpoint_c__c.field-meta.xml
<CustomField>
    <fullName>LiveEndpoint_c__c</fullName>
    <label>Live Endpoint</label>
    <type>Url</type>
</CustomField>

unpackaged/main/default/objects/Opportunity/fields/Chassis_Number__c.field-meta.xml
<CustomField>
    <fullName>Chassis_Number__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Chassis Number</label>
    <length>25</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Opportunity/fields/Integration_Message__c.field-meta.xml
<CustomField>
    <fullName>Integration_Message__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Integration Message</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

unpackaged/main/default/objects/Opportunity/fields/Vehicle_Internal_Number__c.field-meta.xml
<CustomField>
    <fullName>Vehicle_Internal_Number__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Vehicle Internal Number</label>
    <length>25</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Opportunity/fields/Vehicle_Mileage_number__c.field-meta.xml
<CustomField>
    <fullName>Vehicle_Mileage_number__c</fullName>
    <label>ET Vehicle Mileage</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

unpackaged/main/default/objects/Opportunity/fields/Vehicle_Plate_Number__c.field-meta.xml
<CustomField>
    <fullName>Vehicle_Plate_Number__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Vehicle Plate Number</label>
    <length>225</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/classes/MOTO_CICO_GetVehicleDetails.cls
/*
Developer Name - Srihari Koyila
Developed Date - 08 June 2023
Class Name     - MOTO_CICO_GetVehicleDetails
Class purpose  - this class contains POST method for MOTO_CICO_GetVehicleDetails .
Test Class: MOTO_IntegrationTest , Oracle_Integration_Mock

-- History --
----------------------------------------------------------------------------------------------------------------
Sr.No.  version_DevInitials     Date                Details
1.          V1.0              25/11/22           Initial Version 
2.          v2.0              13/04/23           Update response info
****************************************************************************************************************/         

public without sharing class MOTO_CICO_GetVehicleDetails{
    @AuraEnabled
    public static string GetVehicleDetails(string ChassisNumber,string recordId){
        string resVal = null;
        system.debug(ChassisNumber);
        system.debug(recordId);
        
        
        ET_Oracle_REST_Endpoints__mdt connection = ET_REST_Authorize_Helper.getSOAPEndpointFromMetadata('MOTO_GetVehicleDetails');
        Blob beforeblob = Blob.valueOf(connection.Username__c+':'+connection.Password__c);
        string paramvalue = EncodingUtil.base64Encode(beforeblob);
        try{
            Http httpProtocol = new Http();
            HttpRequest request = new HttpRequest();
            HttpResponse response = new HttpResponse();
            request.setHeader('Accept', 'application/json');
            //request.setHeader('Authorization','Basic '+paramvalue);   
            request.setMethod('GET');
            
            if(ET_REST_Authorize_Helper.runningInASandbox()){
                request.setEndpoint(connection.Dev_Endpoint__c+ChassisNumber);
                system.debug(connection.Dev_Endpoint__c);
            }else{
                request.setEndpoint(connection.LiveEndpoint_c__c+ChassisNumber);
            }  
            system.debug('request'+request);
            request.setTimeout(90000);
            request.setHeader('Content-Type', 'application/json');
            Map<String, Object> responseResult =new Map<String, Object>();
            
            response = httpProtocol.send(request);
            system.debug('GetVehicleDetails-body--'+response.getBody());
            
             list<Opportunity> accid =[select Id,Account.Id from Opportunity where Id=:recordId limit 1];
             system.debug('GetVehicleDetails-accid--'+accid);
            if(accid.size()>0){
                account acc = new account(id=accId[0].AccountId);
                Opportunity Oppnty = new Opportunity(id=recordId);

                if(response.getStatusCode() == 200){      
                 
                MOTO_GetVehicleDetailWrapper res = MOTO_GetVehicleDetailWrapper.parse(response.getBody());
                 
                    if(res.Status =='S'){
                        
                        MOTO_GetVehicleDetailWrapper.VehicleCollection veh = res.VehicleCollection;
                       
                        if(veh != null && veh.XxetVehicleMasterDetailV.size()>0){
                            MOTO_GetVehicleDetailWrapper.XxetVehicleMasterDetailV vehInfo= veh.XxetVehicleMasterDetailV[0];
                             System.debug('vehicle info>>>>>>' + vehInfo);                           
                            Oppnty.Vehicle_Internal_Number__c =(String)(vehInfo.internalNo);
                            Oppnty.Vehicle_Plate_Number__c =(String)(vehInfo.plateNumber);
                            Oppnty.Vehicle_Mileage_number__c =(Decimal)(vehInfo.odometer);
                            Oppnty.Chassis_Number__c =ChassisNumber;
                            Oppnty.Integration_Message__c = 'Private Vehicle is created successfully in ERP';
                            resVal =Oppnty.Integration_Message__c;
                            update Oppnty;
                           
                            if(vehInfo.customerNumber != null){
                                acc.AccountNumber =vehInfo.customerNumber;
                       	        acc.ETSALES_Customer_Account_Id__c =(String)(vehInfo.customerId);
                                update acc;
                            }else{
                                string accresVal='--No Account';
                                resVal +=accresVal;
                            }
                            
                            
                        }else{
                             resVal ='No Vehicle';
                        }
                        
                                               
                    }else{
                        
                       resVal ='Error in Status';
                    }
                    
                }else{                    
                   
                   resVal ='Error in response'+response.getBody();
                }
                
            }else{
                  resVal ='Error in accid';
            }
			
        }catch(Exception e){    //throw all other exception message  
            system.debug(e.getMessage());
            system.debug('---ca'+e.getCause());
            system.debug('----Line'+e.getLineNumber());
            system.debug('---Trac-'+e.getStackTraceString());
            system.debug('---Type-'+e.getTypeName());
            throw new AuraHandledException(e.getMessage());} 
        return resVal;
    }
    
    
    
    
    
}