unpackaged/main/default/objects/Account/fields/Chassis_Number__c.field-meta.xml
<CustomField>
    <fullName>Chassis_Number__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Chassis Number</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Lead/fields/Appointment_Date__c.field-meta.xml
<CustomField>
    <fullName>Appointment_Date__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Appointment Date</label>
    <type>DateTime</type>
</CustomField>

unpackaged/main/default/objects/Opportunity/fields/Appointment_Date__c.field-meta.xml
<CustomField>
    <fullName>Appointment_Date__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Appointment Date</label>
    <type>DateTime</type>
</CustomField>

unpackaged/main/default/objects/Opportunity/fields/Chassis_Number__c.field-meta.xml
<CustomField>
    <fullName>Chassis_Number__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Chassis Number</label>
    <length>25</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Opportunity/fields/Insurance_Company__c.field-meta.xml
<CustomField>
    <fullName>Insurance_Company__c</fullName>
    <label>Insurance Company’</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Oman Insurance Company</fullName>
            </value>
            <value>
                <fullName>Al Sagr National Insurance Co.</fullName>
            </value>
            <value>
                <fullName>United Fidelity Insurance Company</fullName>
            </value>
            <value>
                <fullName>Wathba Insurance</fullName>
            </value>
            <value>
                <fullName>Salama Insurance</fullName>
            </value>
            <value>
                <fullName>Al Buhaira insurance</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Opportunity/fields/Internal_No__c.field-meta.xml
<CustomField>
    <fullName>Internal_No__c</fullName>
    <formula>Vehicle_Sales_Inventory__r.ETM_Vehicle_No__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Internal No.</label>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Opportunity/fields/Vehicle_Receiving_Info__c.field-meta.xml
<CustomField>
    <fullName>Vehicle_Receiving_Info__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Vehicle Receiving form</label>
    <referenceTo>Vehicle_Receiving_Info__c</referenceTo>
    <relationshipLabel>Opportunities</relationshipLabel>
    <relationshipName>Opportunities</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Opportunity/recordTypes/Automotive_Service_CenterBodyShop.recordType-meta.xml
<RecordType>
    <fullName>Automotive_Service_CenterBodyShop</fullName>
    <active>true</active>
    <businessProcess>Automotive Service Center %26 Body Shop</businessProcess>
    <label>Automotive Service Center &amp; Body Shop</label>
</RecordType>

unpackaged/main/default/objects/Service_Estimation_Lines__c/Service_Estimation_Lines__c.object-meta.xml
<CustomObject>
    <label>Service Estimation Line</label>
    <nameField>
        <displayFormat>SEL-{00000}</displayFormat>
        <label>Ref. No.</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Service Estimation Lines</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Vehicle_Master__c/Vehicle_Master__c.object-meta.xml
<CustomObject>
    <description>Emirates Transport Oracle Vehicle Master</description>
    <label>ET Vehicle Master</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Vehicle No.</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>ET Vehicle Masters</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Vehicle_Master__c/fields/Account_Id__c.field-meta.xml
<CustomField>
    <fullName>Account_Id__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account Id</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>ET Vehicle Masters</relationshipLabel>
    <relationshipName>ET_Vehicle_Masters</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Vehicle_Master__c/fields/Chassis_No__c.field-meta.xml
<CustomField>
    <fullName>Chassis_No__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Chassis No</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Vehicle_Master__c/fields/Internal_No__c.field-meta.xml
<CustomField>
    <fullName>Internal_No__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <externalId>true</externalId>
    <label>Internal No</label>
    <length>100</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Vehicle_Receiving_Info__c/Vehicle_Receiving_Info__c.object-meta.xml
<CustomObject>
    <label>Vehicle Receiving Info</label>
    <nameField>
        <displayFormat>V-{0000}</displayFormat>
        <label>Vehicle Receiving Info</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Vehicle Receiving Infos</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Vehicle_Receiving_Info__c/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Vehicle Receiving Infos</relationshipLabel>
    <relationshipName>Vehicle_Receiving_Infos</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/X111_Point_Check__c/X111_Point_Check__c.object-meta.xml
<CustomObject>
    <label>111 Point Check</label>
    <nameField>
        <displayFormat>P-{00000}</displayFormat>
        <label>111 Points Check Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>111 Point Checks</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/X111_Point_Check__c/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>111 Point Checks</relationshipLabel>
    <relationshipName>X111_Point_Checks</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/X36_Points_Health_Check__c/X36_Points_Health_Check__c.object-meta.xml
<CustomObject>
    <label>36 Points Health Check</label>
    <nameField>
        <displayFormat>H-{0000}</displayFormat>
        <label>Health Check</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>36 Points Health Checks</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/X36_Points_Health_Check__c/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>36 Points Health Checks</relationshipLabel>
    <relationshipName>X36_Points_Health_Checks</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/classes/MOTO_VehInspectionCtrlTest.cls
/*
 Developer Name - Srihari Koyila
 Developed Date - 20 June 2023
 Test Class     - MOTO_IntegrationTest , Oracle_Integration_Mock 
****************************************************************************************************************/
@isTest
public class MOTO_VehInspectionCtrlTest {
   
     @isTest
    public static void testGetOpportunities2() {
		lead le = new lead();
        le.lastname = 'test new';
        le.RecordTypeId = Schema.SObjectType.lead.getRecordTypeInfosByDeveloperName().get('Moto_Service_Center_Body_Shop').getRecordTypeId();
        le.email ='tesr@gmail.com';
        le.MobilePhone='0558656023';
        insert le;
        Account acc = new Account();
        acc.recordTypeId = Schema.SObjectType.Account.getRecordTypeInfosByDeveloperName().get('Person_B2C').getRecordTypeId();
        acc.lastname = 'test';
        acc.PersonMobilePhone = '123456789';
        insert acc;
        Vehicle_Master__c vm = new Vehicle_Master__c();
        vm.name='12345';
        vm.Internal_No__c ='12345';
        vm.Description__c ='test';
        vm.Chassis_No__c = 'MMBJNKB509D018612';
        vm.Account_Id__c = acc.Id;
        insert vm;
        
        Opportunity opp = new Opportunity();
        opp.Name = 'New Opportunity';
        opp.AccountId=acc.Id;
        opp.RecordTypeId=Schema.SObjectType.Opportunity.getRecordTypeInfosByDeveloperName().get('Automotive_Service_CenterBodyShop').getRecordTypeId();
        opp.StageName = 'Service Booking';
        opp.Amount = 10000;
        opp.Chassis_Number__c = 'MMBJNKB509D018612';
        opp.Appointment_Date__c = Date.today().addDays(10);
        opp.CloseDate = Date.today().addDays(10);
        opp.Insurance_Company__c = 'Salama Insurance';
        opp.Insurance__c = true;
        insert opp;
        
        Opportunity oppRec = new Opportunity();
        oppRec.Name = 'New Opportunity';
        //oppRec.StageName = 'Service Booking';
        oppRec.Amount = 10000;
        oppRec.Chassis_Number__c = 'MMBJNKB509D018612';
        oppRec.Appointment_Date__c = Date.today().addDays(10);
        //oppRec.CloseDate = Date.today().addDays(10);
        oppRec.Insurance_Company__c = 'Salama Insurance';
        oppRec.Insurance__c = true;

         Test.startTest(); 
     
          MOTO_VehInspectionCtrl.testcodeCoverage();
          MOTO_VehInspectionCtrl.testcodeCoverage1();
       	  MOTO_VehInspectionCtrl.testcodeCoverage2();
          MOTO_VehInspectionCtrl.testcodeCoverage4();
          MOTO_VehInspectionCtrl.getLeads(le.email);
          MOTO_VehInspectionCtrl.getOpportunityData();
        //MOTO_VehInspectionCtrl.CreateOpportunityforInternalVehicle(vm.Internal_No__c,opp);
        //MOTO_VehInspectionCtrl.CreateOpportunityReturn(vm.Id, opp);
        MOTO_VehInspectionCtrl.updateOpportunityRecord(opp.Id, opp);
          MOTO_VehInspectionCtrl.getOpportunities(acc.PersonMobilePhone);
          MOTO_VehInspectionCtrl.getVehicle(vm.Chassis_No__c);
          MOTO_VehInspectionCtrl.saveAccountRecord(vm.Id, acc);
          MOTO_VehInspectionCtrl.getOpportunitiesFormsHome(acc.PersonMobilePhone);
        Test.stopTest();
        
    }
/*
 	@isTest
    public static void testGetOpportunities() {
         Test.startTest(); 
       
        Account acc = new Account();
        acc.recordTypeId = Schema.SObjectType.Account.getRecordTypeInfosByDeveloperName().get('Person_B2C').getRecordTypeId();
        acc.lastname = 'test';
        insert acc;
        
        Opportunity opp = new Opportunity();
        opp.Name = 'New Opportunity';
        opp.AccountId=acc.Id;
        opp.RecordTypeId=Schema.SObjectType.Opportunity.getRecordTypeInfosByDeveloperName().get('Automotive_Service_CenterBodyShop').getRecordTypeId();
        opp.StageName = 'Service Booking';
        opp.Amount = 10000;
        opp.Chassis_Number__c = 'MMBJNKB509D018612';
        opp.Appointment_Date__c = Date.today().addDays(10);
        opp.CloseDate = Date.today().addDays(10);
        opp.Insurance_Company__c = 'Salama Insurance';
        opp.Insurance__c = true;
        insert opp;
        
        Opportunity oppRec = new Opportunity();
        oppRec.Name = 'New Opportunity';
        //oppRec.StageName = 'Service Booking';
        oppRec.Amount = 10000;
        oppRec.Chassis_Number__c = 'MMBJNKB509D018612';
        oppRec.Appointment_Date__c = Date.today().addDays(10);
        //oppRec.CloseDate = Date.today().addDays(10);
        oppRec.Insurance_Company__c = 'Salama Insurance';
        oppRec.Insurance__c = true;
        
        lead le = new lead();
        le.lastname = 'test new';
        le.RecordTypeId = Schema.SObjectType.lead.getRecordTypeInfosByDeveloperName().get('Moto_Service_Center_Body_Shop').getRecordTypeId();
        le.email ='tesr@gmail.com';
        le.MobilePhone='0558656023';
        insert le;
        
        
        lead lef = new lead();
        lef.lastname = 'test new 1';
        lef.RecordTypeId = Schema.SObjectType.lead.getRecordTypeInfosByDeveloperName().get('Moto_Service_Center_Body_Shop').getRecordTypeId();
        lef.email ='tesr@gmail.com';
        lef.MobilePhone='05586560231';
        
        
        Vehicle_Master__c vm = new Vehicle_Master__c();
        vm.name='12345';
        vm.Internal_No__c ='12345';
        vm.Description__c ='test';
        insert vm;
        
        Vehicle_Receiving_Info__c veh = new Vehicle_Receiving_Info__c();
        veh.Opportunity__c = opp.id;
        insert veh;
        
        X36_Points_Health_Check__c hea = new X36_Points_Health_Check__c();
        hea.Opportunity__c = opp.id;
        
        X111_Point_Check__c pncheck = new X111_Point_Check__c();
        pncheck.Opportunity__c = opp.id;
        
       
        
        Vehicle_Receiving_Info__c vehicle = new Vehicle_Receiving_Info__c();
        vehicle.Opportunity__c = opp.id;
        List<Vehicle_Receiving_Info__c> vehicleList = new List<Vehicle_Receiving_Info__c>();
        vehicleList.add(vehicle);
        String fileData = '[{"filename":"testFile.txt","filetype":"txt","base64":"SGVsbG8gd29ybGQh"}]';
        
        //
        
        // ContentDocumentLink testLink = new ContentDocumentLink();
        // testLink.LinkedEntityId=opp.id;
        //  testLink.ShareType='V';
        // testLink.ContentDocumentId = '0698E000003HkZmQAK';
        // insert testLink;
        // testLink.LinkedEntityId = veh.Id;
        
        // update testLink;
        
        //ApexPages.StandardController stdController = new ApexPages.StandardController(veh);
        //MOTO_VehInspectionCtrl controller = new MOTO_VehInspectionCtrl(stdController);
        
        MOTO_VehInspectionCtrl.getOpportunities('055343');
        MOTO_VehInspectionCtrl.getOpportunitiesFormsHome('05545');
        MOTO_VehInspectionCtrl.getInternalNumber('123544','test','test','PlateType');
        MOTO_VehInspectionCtrl.updateOpportunityRecord(opp.Id,oppRec);
        //MOTO_VehInspectionCtrl.CreateOpportunityforInternalVehicle('12345');
        
        //MOTO_VehInspectionCtrl.saveSign('wewqeqweqwew',Opp.id);
       // MOTO_VehInspectionCtrl.saveHealthCheck(hea);
//        MOTO_VehInspectionCtrl.vehicleReceivingformSaveHandler(vehicleList,fileData);
        //MOTO_VehInspectionCtrl.addFilesToRecords(Opp.id,fileData, null);
       // MOTO_VehInspectionCtrl.save111PointsCheck(pncheck,fileData);
        //MOTO_VehInspectionCtrl.addFilesToRecords111(Opp.id,fileData, null);
        //MOTO_VehInspectionCtrl.LEADSOURCE_FIELDOptions('Account','Type');
        //MOTO_VehInspectionCtrl.convertLeadAndGetOpportunityId(new list<id>{le.Id});
       
        MOTO_VehInspectionCtrl.getPicklistValues('Account','Type');
        //MOTO_VehInspectionCtrl.saveLeadRecord(lef);
       // MOTO_VehInspectionCtrl.saveServiceestimationRecord(est);
       // MOTO_VehInspectionCtrl.saveServiceLineitem(new List<Service_Estimation_Lines__c>{Srest});
        
        MOTO_VehInspectionCtrl.uploadedDocs docs = new MOTO_VehInspectionCtrl.uploadedDocs();
        docs.filename = 'TestFile';
        docs.filetype = 'PDF';
        docs.base64 = 'SGVsbG8gd29ybGQh';
        MOTO_VehInspectionCtrl.testcodeCoverage();
        Test.stopTest();
        
    }
    @isTest
    public static void testGetOpportunities2() {
         Test.startTest(); 
        Account acc = new Account();
        acc.recordTypeId = Schema.SObjectType.Account.getRecordTypeInfosByDeveloperName().get('Person_B2C').getRecordTypeId();
        acc.lastname = 'test';
        insert acc;
        
        Opportunity opp = new Opportunity();
        opp.Name = 'New Opportunity';
        opp.AccountId=acc.Id;
        opp.RecordTypeId=Schema.SObjectType.Opportunity.getRecordTypeInfosByDeveloperName().get('Automotive_Service_CenterBodyShop').getRecordTypeId();
        opp.StageName = 'Service Booking';
        opp.Amount = 10000;
        opp.Chassis_Number__c = 'MMBJNKB509D018612';
        opp.Appointment_Date__c = Date.today().addDays(10);
        opp.CloseDate = Date.today().addDays(10);
        opp.Insurance_Company__c = 'Salama Insurance';
        opp.Insurance__c = true;
        insert opp;
        
        Opportunity oppRec = new Opportunity();
        oppRec.Name = 'New Opportunity';
        //oppRec.StageName = 'Service Booking';
        oppRec.Amount = 10000;
        oppRec.Chassis_Number__c = 'MMBJNKB509D018612';
        oppRec.Appointment_Date__c = Date.today().addDays(10);
        //oppRec.CloseDate = Date.today().addDays(10);
        oppRec.Insurance_Company__c = 'Salama Insurance';
        oppRec.Insurance__c = true;
        
        lead le = new lead();
        le.lastname = 'test new';
        le.RecordTypeId = Schema.SObjectType.lead.getRecordTypeInfosByDeveloperName().get('Moto_Service_Center_Body_Shop').getRecordTypeId();
        le.email ='tesr@gmail.com';
        le.MobilePhone='0558656023';
        insert le;
        
        
        lead lef = new lead();
        lef.lastname = 'test new 1';
        lef.RecordTypeId = Schema.SObjectType.lead.getRecordTypeInfosByDeveloperName().get('Moto_Service_Center_Body_Shop').getRecordTypeId();
        lef.email ='tesr@gmail.com';
        lef.MobilePhone='05586560231';
        
        
        Vehicle_Master__c vm = new Vehicle_Master__c();
        vm.name='12345';
        vm.Internal_No__c ='12345';
        vm.Description__c ='test';
        insert vm;
        
        Vehicle_Receiving_Info__c veh = new Vehicle_Receiving_Info__c();
        veh.Opportunity__c = opp.id;
        insert veh;
        
        X36_Points_Health_Check__c hea = new X36_Points_Health_Check__c();
        hea.Opportunity__c = opp.id;
        
        X111_Point_Check__c pncheck = new X111_Point_Check__c();
        pncheck.Opportunity__c = opp.id;
        
        
        Vehicle_Receiving_Info__c vehicle = new Vehicle_Receiving_Info__c();
        vehicle.Opportunity__c = opp.id;
        List<Vehicle_Receiving_Info__c> vehicleList = new List<Vehicle_Receiving_Info__c>();
        vehicleList.add(vehicle);
        String fileData = '[{"filename":"testFile.txt","filetype":"txt","base64":"SGVsbG8gd29ybGQh"}]';
        MOTO_VehInspectionCtrl.LIST_OF_REQUIRED_SERVICE_FIELDOptions('Account','Type');
        MOTO_VehInspectionCtrl.PAYMENTMODE_FIELDOptions('Account','Type');
        MOTO_VehInspectionCtrl.DISCOUNTAPPLICABLE_FIELDOptions('Account','Type');
        MOTO_VehInspectionCtrl.INSURANCE_COMPANY_FIELDOptions('Account','Type');
        MOTO_VehInspectionCtrl.VEHICLEMILEAGE_FIELDOptions('Account','Type');
       
       
        
        Test.stopTest();
        
    }*/











}