unpackaged/main/default/objects/Account/fields/Client_Type__c.field-meta.xml
<CustomField>
    <fullName>Client_Type__c</fullName>
    <label>Client Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Sovrin</fullName>
            </value>
            <value>
                <fullName>Government Fedral</fullName>
            </value>
            <value>
                <fullName>Semi Government Fedral</fullName>
            </value>
            <value>
                <fullName>Government Local</fullName>
            </value>
            <value>
                <fullName>Semi Government Local</fullName>
            </value>
            <value>
                <fullName>Private</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/ET_Quote_Item_SpecReq__c/ET_Quote_Item_SpecReq__c.object-meta.xml
<CustomObject>
    <label>Quote Item SpecReq</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Vehicle Quote Item SpecReq Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Quote Item SpecReqs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/ET_Quote_Item_SpecReq__c/fields/ET_Api_Name__c.field-meta.xml
<CustomField>
    <fullName>ET_Api_Name__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Api Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/ET_Quote_Item_SpecReq__c/fields/ET_Vehicle_Quote_Item__c.field-meta.xml
<CustomField>
    <fullName>ET_Vehicle_Quote_Item__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Vehicle Quote Item</label>
    <referenceTo>ET_Vehicle_Quote_Item__c</referenceTo>
    <relationshipLabel>Quote Item SpecReqs</relationshipLabel>
    <relationshipName>Vehicle_Quote_Item_SpecRequests</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/ET_Quote_Item_SpecReq__c/fields/Line_Item_Number__c.field-meta.xml
<CustomField>
    <fullName>Line_Item_Number__c</fullName>
    <label>Line Item Number</label>
    <precision>3</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

unpackaged/main/default/objects/ET_Quote_Item_SpecReq__c/fields/Quote__c.field-meta.xml
<CustomField>
    <fullName>Quote__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Quote</label>
    <referenceTo>Quote</referenceTo>
    <relationshipLabel>Quote Item SpecReqs</relationshipLabel>
    <relationshipName>Quote_Item_SpecReqs</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/ET_Quote_Item_SpecReq__c/fields/Quote_Contract_Year__c.field-meta.xml
<CustomField>
    <fullName>Quote_Contract_Year__c</fullName>
    <label>Quote Contract Year</label>
    <precision>1</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

unpackaged/main/default/objects/ET_Request_Mapping__c/ET_Request_Mapping__c.object-meta.xml
<CustomObject>
    <label>Request Mapping</label>
    <nameField>
        <displayFormat>RM-{00000}</displayFormat>
        <label>Request Mapping Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Request Mapping</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

unpackaged/main/default/objects/ET_Request_Mapping__c/fields/ET_Number_of_Vehicles__c.field-meta.xml
<CustomField>
    <fullName>ET_Number_of_Vehicles__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Number of Vehicles</label>
    <precision>5</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

unpackaged/main/default/objects/ET_Request_Mapping__c/fields/ET_Vehicle_Unique_key__c.field-meta.xml
<CustomField>
    <fullName>ET_Vehicle_Unique_key__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Vehicle Unique key</label>
    <type>TextArea</type>
</CustomField>

unpackaged/main/default/objects/ET_Vehicle_Quote_Item__c/ET_Vehicle_Quote_Item__c.object-meta.xml
<CustomObject>
    <label>Vehicle Quote Item</label>
    <nameField>
        <displayFormat>VQI-{0000}</displayFormat>
        <label>Vehicle Quote Item Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Vehicle Quote Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

unpackaged/main/default/objects/ET_Vehicle_Quote_Item__c/fields/Approval_Details__c.field-meta.xml
<CustomField>
    <fullName>Approval_Details__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Approval Details</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

unpackaged/main/default/objects/ET_Vehicle_Quote_Item__c/fields/ET_Annual_Fuel_Profit_Margin_Rate__c.field-meta.xml
<CustomField>
    <fullName>ET_Annual_Fuel_Profit_Margin_Rate__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Annual Fuel Profit Margin Rate</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

unpackaged/main/default/objects/ET_Vehicle_Quote_Item__c/fields/ET_Annual_Fuel_Profit_Value__c.field-meta.xml
<CustomField>
    <fullName>ET_Annual_Fuel_Profit_Value__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Annual Fuel Profit Value</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

unpackaged/main/default/objects/ET_Vehicle_Quote_Item__c/fields/ET_Annual_Vehicles_Profit_Margin__c.field-meta.xml
<CustomField>
    <fullName>ET_Annual_Vehicles_Profit_Margin__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Annual Vehicles Profit Margin</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

unpackaged/main/default/objects/ET_Vehicle_Quote_Item__c/fields/ET_Annual_Vehicles_Profit_Value__c.field-meta.xml
<CustomField>
    <fullName>ET_Annual_Vehicles_Profit_Value__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Annual Vehicles Profit Value</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

unpackaged/main/default/objects/ET_Vehicle_Quote_Item__c/fields/ET_Contract_Period__c.field-meta.xml
<CustomField>
    <fullName>ET_Contract_Period__c</fullName>
    <label>Contract Period (In Years)</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

unpackaged/main/default/objects/ET_Vehicle_Quote_Item__c/fields/ET_Depreciation_Reserve__c.field-meta.xml
<CustomField>
    <fullName>ET_Depreciation_Reserve__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Depreciation Reserve</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

unpackaged/main/default/objects/ET_Vehicle_Quote_Item__c/fields/ET_Fuel_Expenses__c.field-meta.xml
<CustomField>
    <fullName>ET_Fuel_Expenses__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Fuel Expenses</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

unpackaged/main/default/objects/ET_Vehicle_Quote_Item__c/fields/ET_Fuel_Reserve__c.field-meta.xml
<CustomField>
    <fullName>ET_Fuel_Reserve__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Fuel Reserve</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

unpackaged/main/default/objects/ET_Vehicle_Quote_Item__c/fields/ET_General_Reserve__c.field-meta.xml
<CustomField>
    <fullName>ET_General_Reserve__c</fullName>
    <defaultValue>0</defaultValue>
    <label>General Reserve</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

unpackaged/main/default/objects/ET_Vehicle_Quote_Item__c/fields/ET_Line_Number__c.field-meta.xml
<CustomField>
    <fullName>ET_Line_Number__c</fullName>
    <label>Line Number</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

unpackaged/main/default/objects/ET_Vehicle_Quote_Item__c/fields/ET_Maintenance_Reserve__c.field-meta.xml
<CustomField>
    <fullName>ET_Maintenance_Reserve__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Maintenance Reserve</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

unpackaged/main/default/objects/ET_Vehicle_Quote_Item__c/fields/ET_Number_of_Vehicles__c.field-meta.xml
<CustomField>
    <fullName>ET_Number_of_Vehicles__c</fullName>
    <label>Number of Vehicles</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

unpackaged/main/default/objects/ET_Vehicle_Quote_Item__c/fields/ET_Pricing_Method__c.field-meta.xml
<CustomField>
    <fullName>ET_Pricing_Method__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Pricing Method</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/ET_Vehicle_Quote_Item__c/fields/ET_Pricing_Type__c.field-meta.xml
<CustomField>
    <fullName>ET_Pricing_Type__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Pricing Type</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/ET_Vehicle_Quote_Item__c/fields/ET_Quote_Item_Type__c.field-meta.xml
<CustomField>
    <fullName>ET_Quote_Item_Type__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Quote Item Type</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/ET_Vehicle_Quote_Item__c/fields/ET_Total_Fixed_Cost__c.field-meta.xml
<CustomField>
    <fullName>ET_Total_Fixed_Cost__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Total Fixed Cost</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

unpackaged/main/default/objects/ET_Vehicle_Quote_Item__c/fields/ET_Total_Fuel_Cost__c.field-meta.xml
<CustomField>
    <fullName>ET_Total_Fuel_Cost__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Total Fuel Cost</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

unpackaged/main/default/objects/ET_Vehicle_Quote_Item__c/fields/ET_Total_Reserve_Cost__c.field-meta.xml
<CustomField>
    <fullName>ET_Total_Reserve_Cost__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Total Reserve Cost</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

unpackaged/main/default/objects/ET_Vehicle_Quote_Item__c/fields/ET_Total_Variable_Cost__c.field-meta.xml
<CustomField>
    <fullName>ET_Total_Variable_Cost__c</fullName>
    <label>Total Variable Cost</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

unpackaged/main/default/objects/ET_Vehicle_Quote_Item__c/fields/ET_Total_Vehicles_Cost__c.field-meta.xml
<CustomField>
    <fullName>ET_Total_Vehicles_Cost__c</fullName>
    <label>Total Vehicles Cost</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

unpackaged/main/default/objects/ET_Vehicle_Quote_Item__c/fields/ET_Vehicle_Current_Purchase_Price__c.field-meta.xml
<CustomField>
    <fullName>ET_Vehicle_Current_Purchase_Price__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Vehicle Current Purchase Price</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

unpackaged/main/default/objects/ET_Vehicle_Quote_Item__c/fields/ET_Vehicle_Depreciation__c.field-meta.xml
<CustomField>
    <fullName>ET_Vehicle_Depreciation__c</fullName>
    <defaultValue>&#39;0&#39;</defaultValue>
    <encryptionScheme>None</encryptionScheme>
    <label>Vehicle Depreciation</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/ET_Vehicle_Quote_Item__c/fields/ET_Vehicle_Financing__c.field-meta.xml
<CustomField>
    <fullName>ET_Vehicle_Financing__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Vehicle Financing</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

unpackaged/main/default/objects/ET_Vehicle_Quote_Item__c/fields/ET_Vehicle_Insurance__c.field-meta.xml
<CustomField>
    <fullName>ET_Vehicle_Insurance__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Vehicle Insurance</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

unpackaged/main/default/objects/ET_Vehicle_Quote_Item__c/fields/ET_Vehicle_Registration__c.field-meta.xml
<CustomField>
    <fullName>ET_Vehicle_Registration__c</fullName>
    <label>Vehicle Registration</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

unpackaged/main/default/objects/ET_Vehicle_Quote_Item__c/fields/ET_Vehicle_Repairs_and_Maintenance__c.field-meta.xml
<CustomField>
    <fullName>ET_Vehicle_Repairs_and_Maintenance__c</fullName>
    <label>Vehicle Repairs and Maintenance</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

unpackaged/main/default/objects/ET_Vehicle_Quote_Item__c/fields/ET_Vehicle_Resale_Value__c.field-meta.xml
<CustomField>
    <fullName>ET_Vehicle_Resale_Value__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Vehicle Resale Value</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/ET_Vehicle_Quote_Item__c/fields/ET_Vehicle_Unique_key__c.field-meta.xml
<CustomField>
    <fullName>ET_Vehicle_Unique_key__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Vehicle Unique key</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/ET_Vehicle_Quote_Item__c/fields/is_Target_Price_Required__c.field-meta.xml
<CustomField>
    <fullName>is_Target_Price_Required__c</fullName>
    <defaultValue>false</defaultValue>
    <description>This will be true, when Target Price is Required by Customer</description>
    <label>is Target Price Required</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/objects/ET_Vehicle_Quote_Item__c/fields/Quote__c.field-meta.xml
<CustomField>
    <fullName>Quote__c</fullName>
    <label>Quote</label>
    <referenceTo>Quote</referenceTo>
    <relationshipLabel>Vehicle Quote Items</relationshipLabel>
    <relationshipName>Quote_Calculation</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

unpackaged/main/default/objects/Quote/fields/Is_Target_Price_Required__c.field-meta.xml
<CustomField>
    <fullName>Is_Target_Price_Required__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Is Target Price Required</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/classes/ET_VehicleCalcDetailsControllerTest.cls
@isTest(SeeAllData = false)
public class ET_VehicleCalcDetailsControllerTest {
    @testSetup
    static void setup(){
        Id oppRecordTypeId = Schema.SObjectType.Opportunity.getRecordTypeInfosByDeveloperName().get('ETSALES_Leasing').getRecordTypeId();
        List<Account> accList = ET_ServiceRequestControllerUtility.createAccounts(1, null);
        accList[0].client_type__c = 'Sovrin';
        insert accList;
        List<Opportunity> oppList = ET_ServiceRequestControllerUtility.createOpportunities(1, oppRecordTypeId, accList[0].id);insert oppList;
        System.debug(oppList);
    }
    @isTest 
    static void testOtherCostCalcDetails() {
        List<Opportunity> oppList = [SELECT id,name FROM Opportunity ];
        Quote q = new Quote();
        q.name = 'Quote1' + oppList[0].name;
        q.opportunityId = oppList[0].id;
        q.Is_Target_Price_Required__c=true;
        insert q;
        ET_Quote_Item_SpecReq__c qItemSpecReq=new ET_Quote_Item_SpecReq__c();
        qItemSpecReq.Name='test';
        qItemSpecReq.ET_Api_Name__c='';
        qItemSpecReq.ET_Cost__c=100;
        qItemSpecReq.Quote__c=q.id;
        qItemSpecReq.Line_Item_Number__c=1;
        qItemSpecReq.Quote_Contract_Year__c=1;
        insert qItemSpecReq;
        ET_Vehicle_Quote_Item__c et_vehicle_quote_item = new ET_Vehicle_Quote_Item__c(
        CurrencyIsoCode = 'AED',
        Quote__c = q.id,
        ET_Annual_Fuel_Profit_Margin_Rate__c = 3.0,
        ET_Annual_Fuel_Profit_Value__c = 345.0,
        ET_Annual_Vehicles_Profit_Margin__c = 8.2,
        ET_Annual_Vehicles_Profit_Value__c = 2250.0,
        ET_Contract_Period__c = 1.0,
        ET_Depreciation_Reserve__c = 750.0,
        ET_Fuel_Expenses__c = 11500.0,
        ET_Fuel_Reserve__c = 575.0,
        ET_General_Reserve__c = 1504.0,
        ET_Line_Number__c = 1.0,
        ET_Maintenance_Reserve__c = 125.0,
        ET_Number_of_Vehicles__c = 10.0,
        ET_Price_Utilization__c = 1.0,
        ET_Pricing_Method__c = 'Per Unit',
        ET_Pricing_Type__c = 'Annual Price',
        ET_Quote_Item_Type__c = 'Vehicle',
        ET_Total_Fixed_Cost__c = 7560.0,
        ET_Total_Fuel_Cost__c = 12075.0,
        ET_Total_Reserve_Cost__c = 2379.0,
        ET_Total_Variable_Cost__c = 17500.0,
        ET_Total_Vehicles_Cost__c = 27439.0,
        ET_Vehicle_Depreciation__c = '15000.0',
        ET_Vehicle_Financing__c = 4500.0,
        ET_Vehicle_Insurance__c = 960.0,
         ET_Vehicle_Current_Purchase_Price__c= 50000.0,
        ET_Vehicle_Registration__c = 400.0,
        ET_Vehicle_Repairs_and_Maintenance__c = 2500.0,
        ET_Vehicle_Resale_Value__c = '35000.0',
        ET_Vehicle_Unique_key__c = 'Toyota_Yaris_GLX_2020',
        Approval_Details__c='test,test,test,test;');
        insert et_vehicle_quote_item;
        ET_Quote_Item_SpecReq__c quoteItemSpecReq=new ET_Quote_Item_SpecReq__c();
        quoteItemSpecReq.Name='Washing';
        quoteItemSpecReq.ET_Vehicle_Quote_Item__c=et_vehicle_quote_item.Id;
        quoteItemSpecReq.ET_Cost__c=100;
        insert quoteItemSpecReq;
        ET_Pricing_Service_Request__c sr = new ET_Pricing_Service_Request__c(Opportunity__c = oppList[0].Id, ET_PSR_IsActive__c = true,ET_Accountant_Pricing_Choice__c='test',
                                                                             ET_Coordinator_Pricing_Choice__c='test',ET_Supervisor_Pricing_Choice__c='test');
        insert sr;
        ET_Request_Mapping__c reqMapping=new ET_Request_Mapping__c();
        reqMapping.ET_Vehicle_Unique_key__c='test';
        reqMapping.ET_Number_of_Vehicles__c = 2;
        reqMapping.ET_Number_of_Accountants__c=2;
        reqMapping.ET_Number_of_Coordinators__c=2;
        reqMapping.ET_Number_of_Drivers__c=2;
        reqMapping.ET_Number_of_Nannies__c=2;
        reqMapping.ET_Number_of_Other_Employees__c=2;
        reqMapping.ET_Number_of_Supervisors__c=2;
        reqMapping.ET_Pricing_Service_Request__c=sr.id;
        insert reqMapping;
        q.ET_Pricing_Service_Request__c=sr.id;
        update q;
        Test.startTest();
        ET_VehicleCalcDetailsController.ET_getvehicleCalcDetails(q.Id);
      //  ET_VehicleCalcDetailsController.getCombinationTargetCostForEachVehcile(q.Id);
        ET_VehicleCalcDetailsController.getTargetPriceForCombination(q.Id);
        ET_VehicleCalcDetailsController.getReqMappingRecWrtoVehicleKey(q.Id);
        ET_VehicleCalcDetailsController.getTotalNumberOfMainVehicles(q.Id);
        ET_VehicleCalcDetailsController.getSubstitutionalVehiclesCost(q.Id,'test');
        ET_VehicleCalcDetailsController.getCombinationTargetCostForEachVehcile(q.Id,'test');
        ET_VehicleCalcDetailsController.getCombinationServicesMap(q.Id);
        Test.stopTest();
    }
}