unpackaged/main/default/objects/Account/fields/Client_Type__c.field-meta.xml
<CustomField>
    <fullName>Client_Type__c</fullName>
    <label>Client Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Sovrin</fullName>
            </value>
            <value>
                <fullName>Government Fedral</fullName>
            </value>
            <value>
                <fullName>Semi Government Fedral</fullName>
            </value>
            <value>
                <fullName>Government Local</fullName>
            </value>
            <value>
                <fullName>Semi Government Local</fullName>
            </value>
            <value>
                <fullName>Private</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/ET_Pricing_Service_Request__c/ET_Pricing_Service_Request__c.object-meta.xml
<CustomObject>
    <label>Pricing Service Request</label>
    <nameField>
        <displayFormat>PSR-{0000}</displayFormat>
        <label>Pricing Service Request Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Pricing Service Requests</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Opportunity/recordTypes/ETSALES_Leasing.recordType-meta.xml
<RecordType>
    <fullName>ETSALES_Leasing</fullName>
    <active>true</active>
    <businessProcess>LeaseTransportManpower</businessProcess>
    <label>Leasing/ Rental</label>
</RecordType>

unpackaged/main/default/objects/Quote/fields/ET_Pricing_Service_Request__c.field-meta.xml
<CustomField>
    <fullName>ET_Pricing_Service_Request__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Pricing Service Request</label>
    <referenceTo>ET_Pricing_Service_Request__c</referenceTo>
    <relationshipLabel>Quotes</relationshipLabel>
    <relationshipName>Quotes</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Quote/fields/ET_Type__c.field-meta.xml
<CustomField>
    <fullName>ET_Type__c</fullName>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Quote for Approval</fullName>
            </value>
            <value>
                <fullName>Total Project Summary</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Quote/fields/Is_Target_Price_Required__c.field-meta.xml
<CustomField>
    <fullName>Is_Target_Price_Required__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Is Target Price Required</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/classes/ET_Quotation_PDF_Attachment_Con_Test.cls
@isTest
public class ET_Quotation_PDF_Attachment_Con_Test {

    @testSetup
    static void setup(){
        Id oppRecordTypeId = Schema.SObjectType.Opportunity.getRecordTypeInfosByDeveloperName().get('ETSALES_Leasing').getRecordTypeId();
        List<Account> accList = ET_ServiceRequestControllerUtility.createAccounts(1, null);
        accList[0].client_type__c = 'Sovrin';
        insert accList;
        List<Opportunity> oppList = ET_ServiceRequestControllerUtility.createOpportunities(1, oppRecordTypeId, accList[0].id);insert oppList;
        System.debug(oppList);
        ET_ServiceRequestControllerUtility.createMultiplerecords();
    }
     @isTest
    public static void codecoverage()
    {
        ET_Pricing_Service_Request__c psr = [Select id from ET_Pricing_Service_Request__c Limit 1];
        List<Opportunity> oppList = [SELECT id,name FROM Opportunity];
         Quote q1 = new Quote();
        q1.name = 'Quote1' + oppList[0].name;
        q1.opportunityId = oppList[0].id;
        q1.ET_Type__c = 'Quote for Approval';
        q1.Is_Target_Price_Required__c=true;
        q1.ET_Pricing_Service_Request__c = psr.id;
        insert q1;
         Quote q2 = new Quote();
        q2.name = 'Quote1' + oppList[0].name;
        q2.opportunityId = oppList[0].id;
        q1.ET_Type__c = 'Total Project Summary';
        q2.Is_Target_Price_Required__c=true;
        q2.ET_Pricing_Service_Request__c = psr.id;
        insert q2;
        ET_Quotation_PDF_Attachment_Controller obj = new ET_Quotation_PDF_Attachment_Controller();
        obj.UpdatePDFContent(q1.id);
        String str = obj.PagePDFContentWithoutTotalSummary;
        String str1 = obj.PagePDFContentWithTotalSummary;
        String QuoteId = obj.QuoteId;
        
    }
}