unpackaged/main/default/objects/Account/fields/ET_Preferred_Location__c.field-meta.xml
<CustomField>
    <fullName>ET_Preferred_Location__c</fullName>
    <label>Preferred Location</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Abu Dhabi</fullName>
            </value>
            <value>
                <fullName>Dubai</fullName>
            </value>
            <value>
                <fullName>Ajman</fullName>
            </value>
            <value>
                <fullName>Fujairah</fullName>
            </value>
            <value>
                <fullName>Ras Al Khaimah</fullName>
            </value>
            <value>
                <fullName>Sharjah</fullName>
            </value>
            <value>
                <fullName>Umm Al Quwain</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Account/fields/ETST_Account_Type__c.field-meta.xml
<CustomField>
    <fullName>ETST_Account_Type__c</fullName>
    <label>Education Sector</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Government School</fullName>
            </value>
            <value>
                <fullName>Private School</fullName>
                <default>true</default>
                <label>Private School</label>
            </value>
            <value>
                <fullName>University</fullName>
            </value>
            <value>
                <fullName>Nursery</fullName>
            </value>
            <value>
                <fullName>Chartered School</fullName>
            </value>
            <value>
                <fullName>Ajyal School</fullName>
            </value>
            <value>
                <fullName>Institute</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Account/fields/ETST_Name_AR__c.field-meta.xml
<CustomField>
    <fullName>ETST_Name_AR__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Name AR</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/ETST_School__c/ETST_School__c.object-meta.xml
<CustomObject>
    <label>School</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>School Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Schools</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/ETST_School__c/fields/ETST_Account_Type__c.field-meta.xml
<CustomField>
    <fullName>ETST_Account_Type__c</fullName>
    <label>Account Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Government School</fullName>
            </value>
            <value>
                <fullName>Private School</fullName>
            </value>
            <value>
                <fullName>University</fullName>
            </value>
            <value>
                <fullName>Nursery</fullName>
            </value>
            <value>
                <fullName>Chartered School</fullName>
            </value>
            <value>
                <fullName>Ajyal School</fullName>
            </value>
            <value>
                <fullName>Institute</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/ETST_School__c/fields/ETST_Name_AR__c.field-meta.xml
<CustomField>
    <fullName>ETST_Name_AR__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Name AR</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/ETST_School__c/fields/ETST_School_Code__c.field-meta.xml
<CustomField>
    <fullName>ETST_School_Code__c</fullName>
    <formula>Customer__r.ETST_SchoolRefID__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>School Code</label>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/ETST_School__c/fields/ETST_School_Name_AR_City__c.field-meta.xml
<CustomField>
    <fullName>ETST_School_Name_AR_City__c</fullName>
    <formula>ETST_Name_AR__c+&quot; - &quot;+Customer__r.BillingCity+&quot; - &quot;+ Customer__r.ETST_SchoolRefID__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>School Name AR &amp; City</label>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/ETST_School__c/fields/ETST_School_Name_City__c.field-meta.xml
<CustomField>
    <fullName>ETST_School_Name_City__c</fullName>
    <formula>Name+&quot; - &quot;+Customer__r.BillingCity+&quot; - &quot;+ Customer__r.ETST_SchoolRefID__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>School Name &amp; City</label>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/ETST_School_Type__mdt/ETST_School_Type__mdt.object-meta.xml
<CustomObject>
    <label>ETST School Type</label>
    <pluralLabel>ETST School Types</pluralLabel>
</CustomObject>

unpackaged/main/default/objects/ETST_School_Type__mdt/fields/School_Type_AR__c.field-meta.xml
<CustomField>
    <fullName>School_Type_AR__c</fullName>
    <label>School Type AR</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/classes/ET_LookupController.cls
public class ET_LookupController {
    @AuraEnabled
    public static List<sObject> fetchLookUpValues(String searchKeyWord, String ObjectName, string studentType, String currentValue, string lang) {
        List<ETST_School_Type__mdt> schoolTypes = ETST_School_Type__mdt.getall().values();
        for(ETST_School_Type__mdt schType : schoolTypes){
            if(schType.School_Type_AR__c == studentType){
                studentType=schType.Label;
            }
        } 
        String searchKey = '%'+searchKeyWord+'%';   
        List<sObject> returnList = new List<sObject>();
        String sQuery;
        if(ObjectName=='User'){
            sQuery =  'select id,Name from ' +ObjectName + ' where Name LIKE:searchKey order by Name DESC LIMIT 5'; 
        }
        if(ObjectName=='ETST_School__c'){
            if(!system.Test.isRunningTest()){
                String userAccountId=[select accountId from user where id=:userInfo.getUserId()].accountId;  
                String loc=[select ET_Preferred_Location__c from Account where id=:userAccountId].ET_Preferred_Location__c;
                System.debug('loc ' + loc);
            }
            
            System.debug('studentType ' + studentType);
            System.debug('currentValue ' + currentValue);
            System.debug('searchKey ' + searchKey);
            if(lang =='ar'){
                sQuery =  'select id,Name,ETST_Name_AR__c,ETST_School_Name_AR_City__c, ETST_School_Name_City__c,ETST_School_Code__c from ' +ObjectName + ' where Name LIKE:searchKey ';
                if(studentType!=null && studentType!=''){
                    sQuery +=  ' AND ETST_Account_Type__c=:studentType ';    
                } 
                if(currentValue!=null && currentValue!=''){
                    sQuery +=  ' AND ETST_Name_AR__c!=:currentValue ';    
                }
                sQuery +=  ' order by createdDate DESC LIMIT 5';
            } else {
                sQuery =  'select id,Name,ETST_School_Name_City__c,ETST_School_Code__c from ' +ObjectName + ' where Name LIKE:searchKey ';
                if(studentType!=null && studentType!=''){
                    sQuery +=  ' AND ETST_Account_Type__c=:studentType ';    
                }
                if(currentValue!=null && currentValue!=''){
                    sQuery +=  ' AND Name!=:currentValue ';    
                }
                sQuery +=  ' order by createdDate DESC LIMIT 5';
            }
            
        }
        System.debug('sQuery ' + sQuery);
        List<sObject> lstOfRecords = Database.query(sQuery);       
        for(sObject obj: lstOfRecords) {
            returnList.add(obj);
            
        }
        system.debug('returnList***'+returnList);
        return returnList;
    }
}