unpackaged/main/default/objects/Account/fields/ETIN_Employee_Id__c.field-meta.xml
<CustomField>
    <fullName>ETIN_Employee_Id__c</fullName>
    <description>Insurance</description>
    <encryptionScheme>None</encryptionScheme>
    <externalId>true</externalId>
    <label>Employee Id</label>
    <length>50</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

unpackaged/main/default/objects/Account/recordTypes/Employee.recordType-meta.xml
<RecordType>
    <fullName>Employee</fullName>
    <active>false</active>
    <label>Employee</label>
</RecordType>

unpackaged/main/default/objects/ETDI_Booking_Request__c/ETDI_Booking_Request__c.object-meta.xml
<CustomObject>
    <label>ETDI Booking Request</label>
    <nameField>
        <displayFormat>BR-{00000}</displayFormat>
        <label>Booking Request Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>ETDI Booking Requests</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/ETDI_Booking_Request__c/fields/Branch__c.field-meta.xml
<CustomField>
    <fullName>Branch__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Branch</label>
    <referenceTo>ETDI_Branches__c</referenceTo>
    <relationshipLabel>ETDI Booking Requests</relationshipLabel>
    <relationshipName>ETDI_Booking_Requests</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/ETDI_Booking_Request__c/fields/Depot__c.field-meta.xml
<CustomField>
    <fullName>Depot__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Depot</label>
    <referenceTo>ETDI_Training_Centers__c</referenceTo>
    <relationshipLabel>ETDI Booking Requests</relationshipLabel>
    <relationshipName>ETDI_Booking_Requests</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/ETDI_Booking_Request__c/fields/Exam_Required__c.field-meta.xml
<CustomField>
    <fullName>Exam_Required__c</fullName>
    <label>Exam Required?</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Yes</fullName>
            </value>
            <value>
                <fullName>No</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/ETDI_Booking_Request__c/fields/Language__c.field-meta.xml
<CustomField>
    <fullName>Language__c</fullName>
    <label>Language</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Arabic</fullName>
            </value>
            <value>
                <fullName>English</fullName>
            </value>
            <value>
                <fullName>Pashto</fullName>
            </value>
            <value>
                <fullName>Urdu</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/ETDI_Booking_Request__c/fields/Number_of_Trainees__c.field-meta.xml
<CustomField>
    <fullName>Number_of_Trainees__c</fullName>
    <label>Number of Trainees</label>
    <summaryForeignKey>ETDI_Trainees__c.ETDI_Booking_Request__c</summaryForeignKey>
    <summaryOperation>count</summaryOperation>
    <type>Summary</type>
</CustomField>

unpackaged/main/default/objects/ETDI_Booking_Request__c/fields/Program_Name__c.field-meta.xml
<CustomField>
    <fullName>Program_Name__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Program Name</label>
    <lookupFilter>
        <active>true</active>
        <booleanFilter>(1 AND 2) OR 3</booleanFilter>
        <filterItems>
            <field>ETDI_Programs__c.Department__c</field>
            <operation>equals</operation>
            <valueField>$User.Department</valueField>
        </filterItems>
        <filterItems>
            <field>$Profile.Name</field>
            <operation>equals</operation>
            <value>Customer Community Employee</value>
        </filterItems>
        <filterItems>
            <field>$Profile.Name</field>
            <operation>notEqual</operation>
            <value>Customer Community Employee</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>ETDI_Programs__c</referenceTo>
    <relationshipLabel>ETDI Booking Requests</relationshipLabel>
    <relationshipName>ETDI_Booking_Requests</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/ETDI_Booking_Request__c/fields/Requested_Date__c.field-meta.xml
<CustomField>
    <fullName>Requested_Date__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Requested Date</label>
    <type>Date</type>
</CustomField>

unpackaged/main/default/objects/ETDI_Booking_Request__c/fields/Slot__c.field-meta.xml
<CustomField>
    <fullName>Slot__c</fullName>
    <label>Slot</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>8 Am - 10 Am</fullName>
            </value>
            <value>
                <fullName>11 Am - 12 Pm</fullName>
            </value>
            <value>
                <fullName>2 Pm - 3 Pm</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/ETDI_Booking_Request__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>New</fullName>
                <default>true</default>
                <label>New</label>
            </value>
            <value>
                <fullName>In Progress</fullName>
            </value>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>Rejected</fullName>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/ETDI_Booking_Request__c/fields/Trainer__c.field-meta.xml
<CustomField>
    <fullName>Trainer__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Trainer</label>
    <referenceTo>ETDI_Trainers__c</referenceTo>
    <relationshipLabel>ETDI Booking Requests</relationshipLabel>
    <relationshipName>ETDI_Booking_Requests</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/ETDI_Booking_Request__c/fields/Trainer_Name__c.field-meta.xml
<CustomField>
    <fullName>Trainer_Name__c</fullName>
    <formula>Trainer__r.Name</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Trainer Name</label>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/ETDI_Branches__c/ETDI_Branches__c.object-meta.xml
<CustomObject>
    <label>ETDI Branches</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Branch Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>ETDI Branches</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/ETDI_Programs__c/ETDI_Programs__c.object-meta.xml
<CustomObject>
    <label>ETDI Programs</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Program Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>ETDI Programs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/ETDI_Programs__c/fields/Department__c.field-meta.xml
<CustomField>
    <fullName>Department__c</fullName>
    <label>Department</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>HR</fullName>
            </value>
            <value>
                <fullName>DI</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/ETDI_Trainees__c/ETDI_Trainees__c.object-meta.xml
<CustomObject>
    <label>ETDI Trainees</label>
    <nameField>
        <displayFormat>TRA - {00000}</displayFormat>
        <label>Trainee Ref No.</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>ETDI Trainees</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

unpackaged/main/default/objects/ETDI_Trainees__c/fields/Attended__c.field-meta.xml
<CustomField>
    <fullName>Attended__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Attended?</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/objects/ETDI_Trainees__c/fields/Employee__c.field-meta.xml
<CustomField>
    <fullName>Employee__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Employee</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>ETDI Trainees</relationshipLabel>
    <relationshipName>ETDI_Trainees</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/ETDI_Trainees__c/fields/ETDI_Booking_Request__c.field-meta.xml
<CustomField>
    <fullName>ETDI_Booking_Request__c</fullName>
    <label>Booking Request</label>
    <referenceTo>ETDI_Booking_Request__c</referenceTo>
    <relationshipLabel>ETDI Trainees</relationshipLabel>
    <relationshipName>ETDI_Trainees</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

unpackaged/main/default/objects/ETDI_Trainees__c/fields/Practical_Marks__c.field-meta.xml
<CustomField>
    <fullName>Practical_Marks__c</fullName>
    <label>Practical Marks</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

unpackaged/main/default/objects/ETDI_Trainees__c/fields/Theoretical_Marks__c.field-meta.xml
<CustomField>
    <fullName>Theoretical_Marks__c</fullName>
    <label>Theoretical Marks</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

unpackaged/main/default/objects/ETDI_Trainer_Schedules__c/ETDI_Trainer_Schedules__c.object-meta.xml
<CustomObject>
    <label>ETDI Trainer Schedules</label>
    <nameField>
        <displayFormat>SCH-{00000}</displayFormat>
        <label>Schedule Ref No</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>ETDI Trainer Schedules</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

unpackaged/main/default/objects/ETDI_Trainer_Schedules__c/fields/Booking_Request__c.field-meta.xml
<CustomField>
    <fullName>Booking_Request__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Booking Request</label>
    <referenceTo>ETDI_Booking_Request__c</referenceTo>
    <relationshipLabel>ETDI Trainer Schedules</relationshipLabel>
    <relationshipName>ETDI_Trainer_Schedules</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/ETDI_Trainer_Schedules__c/fields/Schedule_Date_Time__c.field-meta.xml
<CustomField>
    <fullName>Schedule_Date_Time__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Schedule Date&amp;Time</label>
    <type>DateTime</type>
</CustomField>

unpackaged/main/default/objects/ETDI_Trainer_Schedules__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Booked</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
            <value>
                <fullName>Available</fullName>
            </value>
            <value>
                <fullName>Completed</fullName>
                <isActive>false</isActive>
                <label>Completed</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/ETDI_Trainer_Schedules__c/fields/Trainer__c.field-meta.xml
<CustomField>
    <fullName>Trainer__c</fullName>
    <label>Trainer</label>
    <referenceTo>ETDI_Trainers__c</referenceTo>
    <relationshipLabel>ETDI Trainer Schedules</relationshipLabel>
    <relationshipName>ETDI_Trainer_Schedules</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

unpackaged/main/default/objects/ETDI_Trainers__c/ETDI_Trainers__c.object-meta.xml
<CustomObject>
    <label>ETDI Trainers</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Trainer Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>ETDI Trainers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/ETDI_Trainers__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>ETDI Trainers</relationshipLabel>
    <relationshipName>ETDI_Trainers</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/ETDI_Trainers__c/fields/Language__c.field-meta.xml
<CustomField>
    <fullName>Language__c</fullName>
    <label>Language</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>English</fullName>
            </value>
            <value>
                <fullName>Arabic</fullName>
            </value>
            <value>
                <fullName>Urdu</fullName>
            </value>
            <value>
                <fullName>Pashto</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/ETDI_Training_Centers__c/ETDI_Training_Centers__c.object-meta.xml
<CustomObject>
    <label>ETDI Training Centers</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Depot</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>ETDI Training Centers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/classes/ETDIBookingRequest.cls
/***
Class       : ETDIBookingRequest
Author      : Sreelakshmi SK
Test class  : ETDIBookingRequestTest
CreatedDate : 
Description : Controller for ETDI components
TestClass  : 
----------------------------------------------------------------------------------------------------------------
-- History --
----------------------------------------------------------------------------------------------------------------
Sr.No.  version_DevInitials     Date      Author          Details
1.          V1.0              			          	 Initial Version 
2.        
****************************************************************************************************************/

public without sharing class ETDIBookingRequest {
    
    /*
Method      : getRelatedBRDetails
Author      : Sreelakshmi SK
CreatedDate : 16.06.2023
*/  
    
    @AuraEnabled
    public static List<ETDI_Booking_Request__c> getRelatedBRDetails(String bkreqId) {
        
        return [select id,Name,CreatedDate,Status__c,Requested_Date__c,Language__c,Trainer__c,Trainer__r.Name, Trainer_Name__c, Branch__c,Branch__r.Name, Depot__c,Depot__r.Name,Program_Name__c,Program_Name__r.Name,Exam_Required__c from ETDI_Booking_Request__c where Id=:bkreqId];
    }    
    
    /*
Method      : addTrainee
Author      : Sreelakshmi SK
CreatedDate : 16.06.2023
*/    
    
    @AuraEnabled
    public static string addTrainee(list<Account> empList,string bkreqId) {
        String retStr = 'ERROR';
        Savepoint sp = Database.setSavepoint();
        list<ETDI_Trainees__c> traineeList = new list<ETDI_Trainees__c>();
        
        for(Account emp : empList){
            ETDI_Trainees__c tr = new ETDI_Trainees__c();
            tr.Employee__c= emp.Id;
            tr.ETDI_Booking_Request__c = bkreqId;
            traineeList.add(tr);
        }
        
        if(traineeList.size()>0){
            try{
                insert traineeList;
                retStr = 'SUCCESS';
                
            }catch(Exception e) {
                Database.rollback(sp);
                
            }               
        }
        
        return retStr;
        
    }    
    
    /*
Method      : getAvailableOptions
Author      : Sreelakshmi SK
CreatedDate : 16.06.2023
*/ 
    
    @AuraEnabled
    public static List<String> getAvailableOptions(){
        List<String> AvailableOptions= new List<String>();
        Schema.DescribeFieldResult fieldResult = ETDI_Booking_Request__c.Exam_Required__c.getDescribe();
        List<Schema.PicklistEntry> ple = fieldResult.getPicklistValues();
        for( Schema.PicklistEntry pickListVal : ple){
            AvailableOptions.add(pickListVal.getLabel());
        }     
        return AvailableOptions;
    }
    
    
    
    /*
Method      : getSlotValues
Author      : Sreelakshmi SK
CreatedDate : 29.05.2023
*/ 
    
    @AuraEnabled
    public static List<String> getSlotValues(){
        List<String> pickListValuesList= new List<String>();
        Schema.DescribeFieldResult fieldResult = ETDI_Booking_Request__c.Slot__c.getDescribe();
        List<Schema.PicklistEntry> ple = fieldResult.getPicklistValues();
        for( Schema.PicklistEntry pickListVal : ple){
            pickListValuesList.add(pickListVal.getLabel());
        }     
        return pickListValuesList;
    }
    
    /*
Method      : getProgramNames
Author      : Sreelakshmi SK
CreatedDate : 22.05.2023
*/ 
    
    @AuraEnabled  
    public static List<ETDI_Programs__c> getProgramNames(){
        list<ETDI_Programs__c> ProgramList= new list<ETDI_Programs__c>();
        ProgramList=[select Name from ETDI_Programs__c];
        return ProgramList;
    }    
    
    /*
Method      : getBranches
Author      : Sreelakshmi SK
CreatedDate : 18.05.2023
*/ 
    
    @AuraEnabled  
    public static List<ETDI_Branches__c> getBranches(){
        list<ETDI_Branches__c> branchList= new list<ETDI_Branches__c>();
        //branchList=[select id,Name from ETDI_Branches__c];
        branchList=[select Name,(select Name,Capacity__c from ETDI_Training_Centers__r) from ETDI_Branches__c];
        return branchList;
    }
    
    /*
Method      : deleteFiles
Author      : Sreelakshmi SK
CreatedDate : 17.05.2023
*/        
    
    @AuraEnabled  
    public static void deleteFiles(string contentDocId){ 
        
        ContentDocument deleteContent = new ContentDocument(Id=contentDocId);
        
        try {
            delete deleteContent;
            
        }
        catch (Exception e) {
            
            throw new AuraHandledException('Something went wrong: '+ e.getMessage()); 
        }
        
    } 
    
    /*
Method      : getTraineeList
Author      : Sreelakshmi SK
CreatedDate : 27.04.2023
*/    
    @AuraEnabled
    public static List<ETDI_Trainees__c> getTraineeList(String BookingId){
        System.debug('BookingId:'+BookingId);
        return [select id,name,Employee__r.Name,ETDI_Booking_Request__c,Employee__r.ETIN_Employee_Id__c,CreatedDate,ETDI_Booking_Request__r.Exam_Required__c,Practical_Marks__c,Remarks__c,Theoretical_Marks__c from ETDI_Trainees__c where ETDI_Booking_Request__c=:BookingId order by Employee__r.ETIN_Employee_Id__c LIMIT 500];
    }  
    @AuraEnabled
    public static List<ETDI_Trainees__c> getTraineeForCertificate(String BookingId){
        System.debug('BookingId:'+BookingId);
        return [select id,name,Employee__r.Name,ETDI_Booking_Request__c,Employee__r.ETIN_Employee_Id__c,CreatedDate,ETDI_Booking_Request__r.Exam_Required__c from ETDI_Trainees__c where ETDI_Booking_Request__c=:BookingId AND Attended__c=true order by Employee__r.ETIN_Employee_Id__c LIMIT 500];
    }  
    
    @AuraEnabled
    public static void updateTraineeList(List<ETDI_Trainees__c> TraineeList,string bookingId){
        
        
        update TraineeList;
        
        system.debug('bookingId:'+bookingId);
        ETDI_Booking_Request__c bookingRequest=new ETDI_Booking_Request__c();
        bookingRequest.Id=bookingId;
        system.debug('bookingRequest.Id:'+bookingRequest.Id);
        bookingRequest.Status__c='Completed';
        bookingRequest.Completed_Date__c=date.today();
        update bookingRequest;
    }
    
    /*
Method      : getTrainerSchedules
Author      : Sreelakshmi SK
CreatedDate : 24.04.2023
*/    
    @AuraEnabled
    public static List<ETDI_Trainer_Schedules__c> getTrainerSchedules(){
        Id currentUserId=UserInfo.getUserId();
        User currentUser = [SELECT Username,email FROM User WHERE Id = :currentUserId];
        String userName = currentUser.Username;
        String email=currentUser.email;
        system.debug('email:'+email);
        return  [select id, name,Booking_Request__c,Booking_Request__r.Name,Booking_Request__r.Language__c,Booking_Request__r.Number_of_Trainees__c,Schedule_Date_Time__c,Trainer__c,Booking_Request__r.Status__c,CreatedDate from ETDI_Trainer_Schedules__c where Status__c='Booked' and Booking_Request__c!=null /*and Booking_Request__r.Status__c!='Completed'*/ and Trainer__r.Account__r.PersonEmail=:email order by name desc LIMIT 100];
    }
    
    @AuraEnabled
    public static List<ETDI_Booking_Request__c> getBRRecords() {
        Id currentUserId=UserInfo.getUserId();
        System.debug('currentUserId >>> '+currentUserId);
        return [select id,Name,CreatedDate,Status__c,Requested_Date__c,Language__c,Trainer__c,Trainer__r.Name, Trainer_Name__c, Branch__c,Branch__r.Name, Depot__c,Depot__r.Name,Program_Name__c,Program_Name__r.Name from ETDI_Booking_Request__c where OwnerId=:currentUserId order by createdDate Desc LIMIT 100];
    }
    
    @AuraEnabled
    public static list<Account> getEmployeeList(string searchKey) {
        string query = 'SELECT Id,Name,ETIN_Employee_Id__c from Account where (Name LIKE  \'%'+ searchKey +'%\' OR ETIN_Employee_Id__c LIKE  \'%'+ searchKey +'%\') AND Type= \'Employee\' limit 5';
        return Database.Query(query);
    } 
    @AuraEnabled
    public static string createBookingReq(ETDI_Booking_Request__c bkngReq,list<Account> empList,string empData) {
        String retStr = 'ERROR';       
        Savepoint sp = Database.setSavepoint();
        insert bkngReq;
        if(bkngReq.Id != null){
            list<ETDI_Trainees__c> trainessList = new list<ETDI_Trainees__c>();
            if(empData != null){
                list<empDataWrapper> empDataList = (List<empDataWrapper>) System.JSON.deserialize(empData, List<empDataWrapper>.class);
                for(empDataWrapper emp : empDataList){
                    if(emp.EmployeeNumber!= null){                    
                        ETDI_Trainees__c tr = new ETDI_Trainees__c();
                        tr.Employee__r=  new Account(ETIN_Employee_Id__c=emp.EmployeeNumber);   
                        tr.ETDI_Booking_Request__c = bkngReq.Id;
                        trainessList.add(tr);
                    }
                    
                }
            }            
            for(Account emp : empList){
                ETDI_Trainees__c tr = new ETDI_Trainees__c();
                tr.Employee__c= emp.Id;
                tr.ETDI_Booking_Request__c = bkngReq.Id;
                trainessList.add(tr);
            }
            system.debug('TraineesListSize:'+trainessList.size());
            if(trainessList.size()>0){
                try{
                    insert trainessList;
                    ETDI_Booking_Request__c etdiQuery =[select id,Name,Trainer__c,Program_Name__r.Department__c from ETDI_Booking_Request__c where Id=:bkngReq.Id];
            		system.debug(etdiQuery.Program_Name__r.Department__c);
                   
                    Approval.ProcessSubmitRequest req1 = new Approval.ProcessSubmitRequest();
                    req1.setComments('Automatically submitted for approval.');
                    req1.setObjectId(bkngReq.Id);
                    req1.setSubmitterId(UserInfo.getUserId()); 
                    req1.setProcessDefinitionNameOrId('ETDI_Booking_Request_Approval_Process');
                    req1.setSkipEntryCriteria(true);
                    Approval.ProcessResult result = Approval.process(req1);
                    
                     retStr = 'SUCCESS';
                   
                   
                }catch(Exception e) {
                    Database.rollback(sp);
                    
                }               
            }   
        }
        
        return retStr;
        
    }
    public class empDataWrapper{
        public String EmployeeName;
        public String EmployeeNumber;
        
    }
    
    
}