unpackaged/main/default/objects/Account/fields/ETIN_Employee_Id__c.field-meta.xml
<CustomField>
    <fullName>ETIN_Employee_Id__c</fullName>
    <description>Insurance</description>
    <encryptionScheme>None</encryptionScheme>
    <externalId>true</externalId>
    <label>Employee Id</label>
    <length>50</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

unpackaged/main/default/objects/Employee_Invoice_Allocation__c/Employee_Invoice_Allocation__c.object-meta.xml
<CustomObject>
    <label>Employee Invoice Allocation</label>
    <nameField>
        <displayFormat>EIA - {000000}</displayFormat>
        <label>Invoice allocation Ref Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Employee Invoice Allocations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Employee_Invoice_Allocation__c/fields/Annual_Premium__c.field-meta.xml
<CustomField>
    <fullName>Annual_Premium__c</fullName>
    <label>Annual Premium</label>
    <precision>18</precision>
    <scale>4</scale>
    <type>Currency</type>
</CustomField>

unpackaged/main/default/objects/Employee_Invoice_Allocation__c/fields/Claim_Amount__c.field-meta.xml
<CustomField>
    <fullName>Claim_Amount__c</fullName>
    <label>Claim Amount</label>
    <precision>18</precision>
    <scale>4</scale>
    <type>Currency</type>
</CustomField>

unpackaged/main/default/objects/Employee_Invoice_Allocation__c/fields/Effective_Date__c.field-meta.xml
<CustomField>
    <fullName>Effective_Date__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Effective Date</label>
    <type>Date</type>
</CustomField>

unpackaged/main/default/objects/Employee_Invoice_Allocation__c/fields/Employee__c.field-meta.xml
<CustomField>
    <fullName>Employee__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Employee</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Employee Invoice Allocations</relationshipLabel>
    <relationshipName>Employee_Invoice_Allocations</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Employee_Invoice_Allocation__c/fields/Invoice__c.field-meta.xml
<CustomField>
    <fullName>Invoice__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Invoice</label>
    <referenceTo>ETIN_Insurance_Transactions__c</referenceTo>
    <relationshipLabel>Employee Invoice Allocations</relationshipLabel>
    <relationshipName>Employee_Invoice_Allocations</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Employee_Invoice_Allocation__c/fields/Membership_Code__c.field-meta.xml
<CustomField>
    <fullName>Membership_Code__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Membership Code</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Employee_Invoice_Allocation__c/fields/Movement__c.field-meta.xml
<CustomField>
    <fullName>Movement__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Movement</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Employee_Invoice_Allocation__c/fields/Policy__c.field-meta.xml
<CustomField>
    <fullName>Policy__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Policy</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Invoice__c/Invoice__c.object-meta.xml
<CustomObject>
    <label>Invoice</label>
    <nameField>
        <displayFormat>INV-{000000}</displayFormat>
        <label>Invoice No</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Invoices</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/classes/ETIN_EmpInvoiceAllocationCtrl.cls
public class ETIN_EmpInvoiceAllocationCtrl {

    @AuraEnabled
    public static string insertData(String strfromle,string InvRecID){
        String returnresponse ='';
        set<string> EmpIds = new set<string>();
        map<string,string> empIdvsAccId = new map<string,string>();
        List<Employee_Invoice_Allocation__c> EmpAllUpdateList = new List<Employee_Invoice_Allocation__c>();
        //system.debug('strfromle = ' + strfromle);
        List<fieldWrapper> datalist = (List<fieldWrapper>)JSON.deserialize(strfromle, List<fieldWrapper>.class);
        //system.debug('datalist = ' + datalist);
        //system.debug('datalistSize = ' + datalist.size());
       for(fieldWrapper wrapper: datalist){
            
            EmpIds.add(wrapper.EmployeeId);
        }
        if(EmpIds.size()>0){
            
          
            for(Account acc : [select id,ETIN_Employee_Id__c from account where ETIN_Employee_Id__c =:EmpIds limit 50000]){
                empIdvsAccId.put(acc.ETIN_Employee_Id__c,acc.Id);
            }
            
        }
        
        for(fieldWrapper wrapper: datalist){
            
                       
            Employee_Invoice_Allocation__c al =new  Employee_Invoice_Allocation__c();
            al.Annual_Premium__c = wrapper.AnnualPremium;
            al.Claim_Amount__c = wrapper.ClaimAmount;
            al.Effective_Date__c = date.valueOf(wrapper.effectiveDate);
            al.Expiry_Date__c = date.valueOf(wrapper.expiryDate);
            al.Invoice__c = InvRecID;
            al.Membership_Code__c =wrapper.MembershipCode;
            al.Movement__c =wrapper.Movement;
            al.Policy__c=wrapper.Policy;
            if(empIdvsAccId.containsKey(wrapper.EmployeeId)){
              al.Employee__c = empIdvsAccId.get(wrapper.EmployeeId);
            }
                    
            EmpAllUpdateList.add(al);            
        }
        
        if(EmpAllUpdateList.size() > 0){
            try {
                insert EmpAllUpdateList;
                returnresponse = 'SUCCESS';
            }
            catch(Exception ex){
                returnresponse = 'ERROR';
                system.debug('-err-'+ex);
                throw new AuraHandledException('Error-- '+ ex.getMessage());  
            }
        }
        return returnresponse;
    }
    
    public class fieldWrapper{  
        public String EmployeeId; 
        public String MembershipCode;        
        public String Movement;         
        public decimal ClaimAmount;  
        public decimal AnnualPremium;
        public String effectiveDate;
        public String expiryDate;
        public String Policy;
    } 
   
}