unpackaged/main/default/objects/Account/fields/ETIN_Employee_Id__c.field-meta.xml
<CustomField>
    <fullName>ETIN_Employee_Id__c</fullName>
    <description>Insurance</description>
    <encryptionScheme>None</encryptionScheme>
    <externalId>true</externalId>
    <label>Employee Id</label>
    <length>50</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

unpackaged/main/default/objects/ETIN_Employee_Family__c/ETIN_Employee_Family__c.object-meta.xml
<CustomObject>
    <description>This object is created to hold the employee family details related to Insurance app</description>
    <label>Employee Family</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Last Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Employee Family</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

unpackaged/main/default/objects/ETIN_Employee_Family__c/fields/EID_Application_No__c.field-meta.xml
<CustomField>
    <fullName>EID_Application_No__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>EID Application No.</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/ETIN_Employee_Family__c/fields/Employee__c.field-meta.xml
<CustomField>
    <fullName>Employee__c</fullName>
    <label>Employee</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Employee Family</relationshipLabel>
    <relationshipName>Employee_Family</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

unpackaged/main/default/objects/ETIN_Employee_Family__c/fields/Place_of_Visa_Issuance__c.field-meta.xml
<CustomField>
    <fullName>Place_of_Visa_Issuance__c</fullName>
    <label>Place of Visa Issuance</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>UAE_Emirates</valueSetName>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/ETIN_Employee_Family__c/fields/Relation__c.field-meta.xml
<CustomField>
    <fullName>Relation__c</fullName>
    <label>Relation</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Spouse</fullName>
            </value>
            <value>
                <fullName>Child</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/globalValueSets/UAE_Emirates.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Abu Dhabi</fullName>
    </customValue>
    <customValue>
        <fullName>Ajman</fullName>
    </customValue>
    <customValue>
        <fullName>Dubai</fullName>
    </customValue>
    <customValue>
        <fullName>Fujairah</fullName>
    </customValue>
    <customValue>
        <fullName>Ras Al Khaimah</fullName>
    </customValue>
    <customValue>
        <fullName>Sharjah</fullName>
    </customValue>
    <customValue>
        <fullName>Umm Al Quwain</fullName>
    </customValue>
    <customValue>
        <fullName>GCC - Abu Dhabi</fullName>
    </customValue>
    <customValue>
        <fullName>GCC - Dubai and Northern Emirates</fullName>
    </customValue>
    <customValue>
        <fullName>UAE Nationality - Dubai</fullName>
    </customValue>
    <customValue>
        <fullName>UAE Nationality - Abu Dhabi</fullName>
    </customValue>
    <masterLabel>UAE Emirates</masterLabel>
</GlobalValueSet>

unpackaged/main/default/classes/ETIN_EmployeeFamilyObjValidationTest.cls
@IsTest
public class ETIN_EmployeeFamilyObjValidationTest {
    private static testmethod void createEmpFam(){
        
        Account acc = new Account();
        acc.Name = 'test';
        acc.ETIN_Employee_Id__c ='344243232';
       
        insert acc;
        
        ETIN_Employee_Family__c em = new ETIN_Employee_Family__c();
        
        em.Name = 'test3243343';
        em.EID_Application_No__c ='3423232';
        em.Employee__c = acc.Id;
        em.Relation__c ='Spouse';
        em.Place_of_Visa_Issuance__c ='Abu Dhabi';
        insert em;
        
        em.Relation__c='Child';
        update em;

    }
}