unpackaged/main/default/objects/Account/fields/ETIN_Employee_Id__c.field-meta.xml
<CustomField>
    <fullName>ETIN_Employee_Id__c</fullName>
    <description>Insurance</description>
    <encryptionScheme>None</encryptionScheme>
    <externalId>true</externalId>
    <label>Employee Id</label>
    <length>50</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

unpackaged/main/default/objects/Account/fields/ETIN_Place_of_Visa_Issuance__c.field-meta.xml
<CustomField>
    <fullName>ETIN_Place_of_Visa_Issuance__c</fullName>
    <description>Insurance</description>
    <label>Place of Visa Issuance</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>UAE_Emirates</valueSetName>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Account/fields/IsConvertedFromLead__c.field-meta.xml
<CustomField>
    <fullName>IsConvertedFromLead__c</fullName>
    <defaultValue>false</defaultValue>
    <label>IsConvertedFromLead</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/objects/Account/recordTypes/Employee.recordType-meta.xml
<RecordType>
    <fullName>Employee</fullName>
    <active>false</active>
    <label>Employee</label>
</RecordType>

unpackaged/main/default/objects/ETIN_DefaultInsurancePartners__c/ETIN_DefaultInsurancePartners__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <label>Default Insurance Partners</label>
</CustomObject>

unpackaged/main/default/objects/ETIN_DefaultInsurancePartners__c/fields/Account_ID__c.field-meta.xml
<CustomField>
    <fullName>Account_ID__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Account ID</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/ETIN_Insurance__c/ETIN_Insurance__c.object-meta.xml
<CustomObject>
    <label>Insurance</label>
    <nameField>
        <displayFormat>ETIN-{000000}</displayFormat>
        <label>Insurance Ref Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Insurances</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

unpackaged/main/default/objects/ETIN_Insurance__c/fields/Card_Number__c.field-meta.xml
<CustomField>
    <fullName>Card_Number__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Card Number</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/ETIN_Insurance__c/fields/EmployeeAcc__c.field-meta.xml
<CustomField>
    <fullName>EmployeeAcc__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Employee</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Insurances</relationshipLabel>
    <relationshipName>Insurances</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/ETIN_Insurance__c/fields/Insurance_Company__c.field-meta.xml
<CustomField>
    <fullName>Insurance_Company__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Insurance Company</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Insurance</relationshipLabel>
    <relationshipName>Insurance</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/ETIN_Insurance__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Request Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>New</fullName>
                <default>true</default>
                <label>New</label>
            </value>
            <value>
                <fullName>Pending with HR Manager</fullName>
            </value>
            <value>
                <fullName>Under Process</fullName>
            </value>
            <value>
                <fullName>Under Approval</fullName>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
            <value>
                <fullName>Pending with Zone Coordinator</fullName>
            </value>
            <value>
                <fullName>Not Eligible</fullName>
            </value>
            <value>
                <fullName>Under Investigation</fullName>
            </value>
            <value>
                <fullName>Hold</fullName>
            </value>
            <value>
                <fullName>Admin Approval Pending</fullName>
                <isActive>false</isActive>
                <label>Admin Approval Pending</label>
            </value>
            <value>
                <fullName>Admin Approved</fullName>
                <isActive>false</isActive>
                <label>Admin Approved</label>
            </value>
            <value>
                <fullName>Admin Rejected</fullName>
                <isActive>false</isActive>
                <label>Admin Rejected</label>
            </value>
            <value>
                <fullName>HR Rejected</fullName>
                <isActive>false</isActive>
                <label>HR Rejected</label>
            </value>
            <value>
                <fullName>Insurance Approved</fullName>
                <isActive>false</isActive>
                <label>Insurance Approved</label>
            </value>
            <value>
                <fullName>Insurance Pending</fullName>
                <isActive>false</isActive>
                <label>Insurance Pending</label>
            </value>
            <value>
                <fullName>Insurance Rejected</fullName>
                <isActive>false</isActive>
                <label>Insurance Rejected</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/ETIN_Insurance__c/recordTypes/Health_Insurance.recordType-meta.xml
<RecordType>
    <fullName>Health_Insurance</fullName>
    <active>true</active>
    <label>Health Insurance</label>
</RecordType>

unpackaged/main/default/globalValueSets/UAE_Emirates.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Abu Dhabi</fullName>
    </customValue>
    <customValue>
        <fullName>Ajman</fullName>
    </customValue>
    <customValue>
        <fullName>Dubai</fullName>
    </customValue>
    <customValue>
        <fullName>Fujairah</fullName>
    </customValue>
    <customValue>
        <fullName>Ras Al Khaimah</fullName>
    </customValue>
    <customValue>
        <fullName>Sharjah</fullName>
    </customValue>
    <customValue>
        <fullName>Umm Al Quwain</fullName>
    </customValue>
    <customValue>
        <fullName>GCC - Abu Dhabi</fullName>
    </customValue>
    <customValue>
        <fullName>GCC - Dubai and Northern Emirates</fullName>
    </customValue>
    <customValue>
        <fullName>UAE Nationality - Dubai</fullName>
    </customValue>
    <customValue>
        <fullName>UAE Nationality - Abu Dhabi</fullName>
    </customValue>
    <masterLabel>UAE Emirates</masterLabel>
</GlobalValueSet>

unpackaged/main/default/classes/ETIN_SendEmailToPartnerWithDocsCtrlTest.cls
@isTest
public class ETIN_SendEmailToPartnerWithDocsCtrlTest {
  
    private static testmethod void sendEmailFunction(){
        Test.startTest();
        Account acc = new Account();
        acc.Name = 'ts3232xysew';
        acc.Type = 'Employee';
        acc.ETIN_Employee_Id__c ='232232';
        acc.ETIN_Place_of_Visa_Issuance__c = 'Abu Dhabi';
        acc.IsConvertedFromLead__c = true;
        insert acc;
        
        list<ETIN_Insurance__c> insList = new List<ETIN_Insurance__c>();
        ETIN_Insurance__c et = new ETIN_Insurance__c();
        et.EmployeeAcc__c = acc.Id;
        et.Insurance_Company__c=acc.Id;
        et.Card_Number__c = '24343';
        et.Status__c ='Under Process';
        et.RecordTypeId = Schema.SObjectType.ETIN_Insurance__c.getRecordTypeInfosByDeveloperName().get('Health_Insurance').getRecordTypeId();
          
        insert et;
        insList.add(et);
        
        ContentDocument testContDoc = new ContentDocument();
        ContentVersion testContVer = new ContentVersion();
        ContentDocumentLink testContDocLink = new ContentDocumentLink(); 
        
         testContVer.Title = 'Test Document 2';
        testContVer.PathOnClient = 'SF_ELO_Code.txt';
        testContVer.VersionData = Blob.valueOf('Test Content');   
        testContVer.IsMajorVersion = true;
        insert testContVer;
        ContentVersion cvL = [SELECT Id, Title, ContentDocumentId FROM ContentVersion WHERE Id = :testContVer.Id];

        //Populate and create ContentDocumentLink
        testContDocLink.LinkedEntityId = et.Id;
        testContDocLink.ContentDocumentId = cvL.ContentDocumentId;
        insert testContDocLink;

        
        Account acc2 = new Account();
        acc2.Name = 'ts3232xy1Kl3me3434';
        acc2.Type = 'Insurance Partner';
        acc2.ETIN_Employee_Id__c ='232231';
        acc2.ETIN_Place_of_Visa_Issuance__c = 'Abu Dhabi';
        acc2.IsConvertedFromLead__c = true;
        
        insert acc2;
      
        Contact con = new Contact();
        con.LastName = 'test';
        con.AccountId =acc2.Id;
        con.Email= 'test@gmail.com';
        insert con;
        
        ETIN_DefaultInsurancePartners__c eti = new ETIN_DefaultInsurancePartners__c();
        eti.Name = 'Abu Dhabi';
        eti.Account_ID__c = acc2.Id;
        insert eti;
        
         ContentVersion cv = new ContentVersion();
        cv.Title = 'Test Document';
        cv.PathOnClient = 'TestDocument.pdf';
        cv.VersionData = Blob.valueOf('Test Content');
        cv.IsMajorVersion = true;
        Insert cv;
        
        User testUser = new User(FirstName = 'John', LastName = 'Doe', 
                             Email = 'john.doe@example.com', 
                             Username = 'john.doe@example.com',
                                 Alias= 'asara', TimeZoneSidKey= '(GMT+04:00) Gulf Standard Time (Asia/Dubai)', LocaleSidKey= '(GMT+04:00) Gulf Standard Time (Asia/Dubai)',
                                 EmailEncodingKey= 'Unicode (UTF-8)', ProfileId= '%2F00e3z000001a509', LanguageLocaleKey= 'English (United Kingdom)'
                             );
        /*Alias, TimeZoneSidKey, LocaleSidKey, EmailEncodingKey, ProfileId, LanguageLocaleKey*/
   // insert testUser;

    // Set the current user to the test user
          System.assertEquals(UserInfo.getUserId(), ETIN_SendEmailToPartnerWithDocsCtrl.currentUserDetailMethod().Id, 'got the right user');
       
        //Get Content Version
        List<ContentVersion> cvList = [SELECT Id, Title, ContentDocumentId FROM ContentVersion WHERE Id = :cv.Id];
        System.assertEquals(cvList.size(), 1);
        
        JSONGenerator gen = JSON.createGenerator(true);
        gen.writeStartArray();
        gen.writeStartObject();
        gen.writeStringField('name', 'test.csv');
        gen.writeStringField('base64Data','244322');
         gen.writeStringField('contentType', 'text/csv');
        gen.writeEndObject();
        gen.writeEndArray();
        String jsonData = gen.getAsString();
        
        
        ETIN_SendEmailToPartnerWithDocsCtrl.getInsuranceDetails('Abu Dhabi');
         ETIN_SendEmailToPartnerWithDocsCtrl.getInsuranceDetails('Dubai');
        ETIN_SendEmailToPartnerWithDocsCtrl.getEmailDetails('Abu Dhabi');
        //ETIN_SendEmailToPartnerWithDocsCtrl.getInsLibraryFiles();
        //ETIN_SendEmailToPartnerWithDocsCtrl.getreportDetails('Abu Dhabi');
        ETIN_SendEmailToPartnerWithDocsCtrl.currentUserDetailMethod();
        ETIN_SendEmailToPartnerWithDocsCtrl.sendEmailWithDocs('test@gmail.com','Subject', 'Body',insList , cvList, '["name"]', '["name"]',jsonData);
        Test.stopTest();
    }
}