unpackaged/main/default/objects/Account/fields/ETIN_Employee_Id__c.field-meta.xml
<CustomField>
    <fullName>ETIN_Employee_Id__c</fullName>
    <description>Insurance</description>
    <encryptionScheme>None</encryptionScheme>
    <externalId>true</externalId>
    <label>Employee Id</label>
    <length>50</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

unpackaged/main/default/objects/Account/recordTypes/Employee.recordType-meta.xml
<RecordType>
    <fullName>Employee</fullName>
    <active>false</active>
    <label>Employee</label>
</RecordType>

unpackaged/main/default/objects/Case/fields/ETIN_Employee_ID__c.field-meta.xml
<CustomField>
    <fullName>ETIN_Employee_ID__c</fullName>
    <formula>Account.ETIN_Employee_Id__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Employee ID</label>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Case/fields/Grade__c.field-meta.xml
<CustomField>
    <fullName>Grade__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Grade</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/CICO_Check_In__c/CICO_Check_In__c.object-meta.xml
<CustomObject>
    <label>Check In</label>
    <nameField>
        <displayFormat>CI-{000000}</displayFormat>
        <label>CI Ref No</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Check In</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

unpackaged/main/default/objects/CICO_Check_In__c/fields/Check_In_Date__c.field-meta.xml
<CustomField>
    <fullName>Check_In_Date__c</fullName>
    <defaultValue>NOW()</defaultValue>
    <encryptionScheme>None</encryptionScheme>
    <label>Check In Date</label>
    <type>DateTime</type>
</CustomField>

unpackaged/main/default/objects/CICO_Check_In__c/fields/Check_In_for__c.field-meta.xml
<CustomField>
    <fullName>Check_In_for__c</fullName>
    <label>Check In for</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>Internal Assignments</fullName>
            </value>
            <value>
                <fullName>Maintenance</fullName>
            </value>
            <value>
                <fullName>Vehicle Rental</fullName>
            </value>
            <value>
                <fullName>Vehicle Transfer</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/CICO_Check_In__c/fields/Check_in_fuel_reading__c.field-meta.xml
<CustomField>
    <fullName>Check_in_fuel_reading__c</fullName>
    <label>Check in Fuel Reading</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Percent</type>
</CustomField>

unpackaged/main/default/objects/CICO_Check_In__c/fields/Check_in_Location__c.field-meta.xml
<CustomField>
    <fullName>Check_in_Location__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Check in Location</label>
    <referenceTo>CICO_Workshop_Location__c</referenceTo>
    <relationshipLabel>Check In</relationshipLabel>
    <relationshipName>Check_In</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/CICO_Check_In__c/fields/Check_In_Status__c.field-meta.xml
<CustomField>
    <fullName>Check_In_Status__c</fullName>
    <label>Check In Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Draft</fullName>
                <default>true</default>
                <label>Draft</label>
            </value>
            <value>
                <fullName>Check In</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/CICO_Check_In__c/fields/Check_Out__c.field-meta.xml
<CustomField>
    <fullName>Check_Out__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Check Out</label>
    <referenceTo>CICO_Check_Out__c</referenceTo>
    <relationshipLabel>Check In</relationshipLabel>
    <relationshipName>Check_In</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/CICO_Check_In__c/fields/Internal_No__c.field-meta.xml
<CustomField>
    <fullName>Internal_No__c</fullName>
    <label>Internal No</label>
    <referenceTo>Vehicle_Master__c</referenceTo>
    <relationshipLabel>Check In</relationshipLabel>
    <relationshipName>Check_In</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

unpackaged/main/default/objects/CICO_Check_Out__c/CICO_Check_Out__c.object-meta.xml
<CustomObject>
    <label>Check Out</label>
    <nameField>
        <displayFormat>CO-{000000}</displayFormat>
        <label>CO Ref No</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Check Out</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

unpackaged/main/default/objects/CICO_Check_Out__c/fields/Cassette__c.field-meta.xml
<CustomField>
    <fullName>Cassette__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Cassette</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/objects/CICO_Check_Out__c/fields/Check_In__c.field-meta.xml
<CustomField>
    <fullName>Check_In__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Check In</label>
    <referenceTo>CICO_Check_In__c</referenceTo>
    <relationshipLabel>Check Out</relationshipLabel>
    <relationshipName>Check_Out</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/CICO_Check_Out__c/fields/Check_Out_fuel_reading__c.field-meta.xml
<CustomField>
    <fullName>Check_Out_fuel_reading__c</fullName>
    <label>Check Out fuel reading</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Percent</type>
</CustomField>

unpackaged/main/default/objects/CICO_Check_Out__c/fields/Check_Out_Reading__c.field-meta.xml
<CustomField>
    <fullName>Check_Out_Reading__c</fullName>
    <label>Check Out Reading(KM)</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

unpackaged/main/default/objects/CICO_Check_Out__c/fields/Internal_No__c.field-meta.xml
<CustomField>
    <fullName>Internal_No__c</fullName>
    <label>Internal No</label>
    <referenceTo>Vehicle_Master__c</referenceTo>
    <relationshipLabel>Check Out</relationshipLabel>
    <relationshipName>Check_Out</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

unpackaged/main/default/objects/CICO_Child_Asset__c/CICO_Child_Asset__c.object-meta.xml
<CustomObject>
    <label>Child Asset</label>
    <nameField>
        <displayFormat>CA-{000000}</displayFormat>
        <label>Asset Ref No</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Child Assets</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/CICO_Child_Asset__c/fields/Check_In__c.field-meta.xml
<CustomField>
    <fullName>Check_In__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Check In</label>
    <referenceTo>CICO_Check_In__c</referenceTo>
    <relationshipLabel>Child Assets</relationshipLabel>
    <relationshipName>Child_Assets</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/CICO_Child_Asset__c/fields/Check_Out__c.field-meta.xml
<CustomField>
    <fullName>Check_Out__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Check Out</label>
    <referenceTo>CICO_Check_Out__c</referenceTo>
    <relationshipLabel>Child Assets</relationshipLabel>
    <relationshipName>Child_Assets</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/CICO_Intimation__c/CICO_Intimation__c.object-meta.xml
<CustomObject>
    <description>check in check out</description>
    <label>Intimation</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Intimation ID</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Intimations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/CICO_Intimation__c/fields/Intimation_Date__c.field-meta.xml
<CustomField>
    <fullName>Intimation_Date__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Intimation Date</label>
    <type>Date</type>
</CustomField>

unpackaged/main/default/objects/CICO_Intimation__c/fields/Intimation_No__c.field-meta.xml
<CustomField>
    <fullName>Intimation_No__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <externalId>true</externalId>
    <label>Intimation No</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

unpackaged/main/default/objects/CICO_Intimation__c/fields/PO_Header_ID__c.field-meta.xml
<CustomField>
    <fullName>PO_Header_ID__c</fullName>
    <label>PO Header ID</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

unpackaged/main/default/objects/CICO_Intimation__c/fields/Vendor_ID__c.field-meta.xml
<CustomField>
    <fullName>Vendor_ID__c</fullName>
    <label>Vendor ID</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

unpackaged/main/default/objects/CICO_Intimation_Line__c/CICO_Intimation_Line__c.object-meta.xml
<CustomObject>
    <label>Intimation Line</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Intimation Line ID</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Intimation Lines</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

unpackaged/main/default/objects/CICO_Intimation_Line__c/fields/Intimation_ID__c.field-meta.xml
<CustomField>
    <fullName>Intimation_ID__c</fullName>
    <label>Intimation ID</label>
    <referenceTo>CICO_Intimation__c</referenceTo>
    <relationshipLabel>Intimation Lines</relationshipLabel>
    <relationshipName>Intimation_Lines</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

unpackaged/main/default/objects/CICO_Intimation_Line__c/fields/PO_Line_ID__c.field-meta.xml
<CustomField>
    <fullName>PO_Line_ID__c</fullName>
    <label>PO Line ID</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

unpackaged/main/default/objects/CICO_Vehicle_Spec__c/CICO_Vehicle_Spec__c.object-meta.xml
<CustomObject>
    <description>Check In Check Out</description>
    <label>Vehicles/Inspections</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Chassis No</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Vehicles/Inspections</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

unpackaged/main/default/objects/CICO_Vehicle_Spec__c/fields/Inspection_Status__c.field-meta.xml
<CustomField>
    <fullName>Inspection_Status__c</fullName>
    <label>Inspection Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>Reject</fullName>
            </value>
            <value>
                <fullName>Re-Inspect</fullName>
            </value>
            <value>
                <fullName>Pending</fullName>
                <default>true</default>
                <label>Pending</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/CICO_Vehicle_Spec__c/fields/Internal_No__c.field-meta.xml
<CustomField>
    <fullName>Internal_No__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Internal No</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/CICO_Vehicle_Spec__c/fields/Intimation_ID__c.field-meta.xml
<CustomField>
    <fullName>Intimation_ID__c</fullName>
    <formula>Intimation_Line__r.Intimation_ID__r.Name</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Intimation ID</label>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/CICO_Vehicle_Spec__c/fields/Intimation_Line__c.field-meta.xml
<CustomField>
    <fullName>Intimation_Line__c</fullName>
    <label>Intimation Line</label>
    <referenceTo>CICO_Intimation_Line__c</referenceTo>
    <relationshipName>Vehicle_Spec</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

unpackaged/main/default/objects/User/fields/ETI_Inspection_Center__c.field-meta.xml
<CustomField>
    <fullName>ETI_Inspection_Center__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Inspection Center</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/User/fields/Grade__c.field-meta.xml
<CustomField>
    <fullName>Grade__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Grade</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Vehicle_Master__c/Vehicle_Master__c.object-meta.xml
<CustomObject>
    <description>Emirates Transport Oracle Vehicle Master</description>
    <label>ET Vehicle Master</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Vehicle No.</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>ET Vehicle Masters</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Vehicle_Master__c/fields/Internal_No__c.field-meta.xml
<CustomField>
    <fullName>Internal_No__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <externalId>true</externalId>
    <label>Internal No</label>
    <length>100</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Vehicle_Master__c/fields/Plate_colour_code__c.field-meta.xml
<CustomField>
    <fullName>Plate_colour_code__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Plate colour code</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Vehicle_Master__c/fields/Plate_Number__c.field-meta.xml
<CustomField>
    <fullName>Plate_Number__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Plate Number</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Vehicle_Master__c/fields/Plate_Source__c.field-meta.xml
<CustomField>
    <fullName>Plate_Source__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Plate Source</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Vehicle_Master__c/fields/Plate_Type__c.field-meta.xml
<CustomField>
    <fullName>Plate_Type__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Plate Type</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/classes/CICO_InspectionCtrlTest.cls
@isTest
public class CICO_InspectionCtrlTest {
    
    private static testmethod void inspectionTest(){
        
        Profile p = [SELECT Id FROM Profile WHERE Name='System Administrator'];        
       
        User user1 = new User();
        user1.Username = 'stand3423@jana9334.com';
        user1.Email = 'us1@test.com';
        user1.LastName = 'LastName1';
        user1.FirstName = 'FirstName1';
        user1.Alias ='u1';
        user1.CommunityNickname ='use1';
        user1.ProfileId =p.id;
        user1.ETI_Inspection_Center__c='DXB-RL-M';
        
        user1.EmailEncodingKey='UTF-8';
        user1.LanguageLocaleKey='en_US';
        user1.LocaleSidKey='en_US';
        user1.TimeZoneSidKey='America/Los_Angeles';
        user1.Country = 'US';
        user1.Title = 'Territory Manager';
        user1.EmployeeNumber ='123456';
        user1.Grade__c='OPER-CICO';
        insert user1;
       
        Account acc = new Account();
        acc.firstName ='Jana';
        acc.lastName ='Jana';
        acc.ETIN_Employee_Id__c = '123456';
        acc.Type='Employee';
        insert acc;
           
        
        system.runAs(user1){
        
            CICO_InspectionCtrl.getUserDetails();
            CICO_InspectionCtrl.getUserLoginInfo();
             CICO_InspectionCtrl.getUserLocationInfo();
        }
        
        CICO_Intimation__c inti = new CICO_Intimation__c();
        inti.Name = '123242';
        inti.Intimation_Date__c = system.today();
        inti.Intimation_No__c='223323';
        inti.PO_Header_ID__c=1234;
        inti.Vendor_ID__c=4233;
        insert inti;
        
        CICO_Intimation_Line__c line = new CICO_Intimation_Line__c();
        line.Name ='1';
        line.Intimation_ID__c = inti.Id;
        line.PO_Line_ID__c = 12332;
        insert line;
        
        CICO_Vehicle_Spec__c veh = new CICO_Vehicle_Spec__c();
        veh.Name ='BNBNBN343DD23';
        veh.Intimation_Line__c= line.Id;
        veh.Inspection_Status__c = 'Approved';
        insert veh;
        Vehicle_Master__c vehicleMaster = new Vehicle_Master__c();
        vehicleMaster.Asset_Number__c = 'Test';
        vehicleMaster.Internal_No__c = 'D012413';
        vehicleMaster.Plate_Number__c ='1224';
        vehicleMaster.Plate_colour_code__c='AE';
        vehicleMaster.Plate_Source__c = 'Dubai';
        vehicleMaster.Plate_Type__c ='Private';
        insert vehicleMaster;
        
        String fileData = 'testfilename';
        string jsonstr='[{"strFileName":"Passport.pdf","strFileType":"application/pdf","strBase64Data":"'+fileData+'"}]';
        CICO_InspectionCtrl.getIntimationWithRelatedDetails();
       
        CICO_InspectionCtrl.addImagesToRecId(veh.Id,jsonstr);
        
        ContentDocument testContDoc = new ContentDocument();
        ContentVersion testContVer = new ContentVersion();
        ContentDocumentLink testContDocLink = new ContentDocumentLink(); 
        
        //Populate and create ContentVersion
        testContVer.Title = 'MarkedDiagram';
        testContVer.PathOnClient = 'MarkedDiagram.txt';
        testContVer.VersionData = Blob.valueOf('Test Content');   
        testContVer.IsMajorVersion = true;
        insert testContVer;
        
        id contentDocID = [select ContentDocumentId from ContentVersion where id=:testContVer.Id].ContentDocumentId;
        //Populate and create ContentDocumentLink
        testContDocLink.LinkedEntityId = veh.Id;
        testContDocLink.ContentDocumentId = contentDocID;
        
        insert testContDocLink;
        
        CICO_Workshop_Location__c  glLocation = new CICO_Workshop_Location__c();
        insert glLocation;
        
        CICO_Check_In__c checkin = new CICO_Check_In__c();
        checkin.Internal_No__c = vehicleMaster.Id;
        checkin.Check_In_Date__c = System.today().adddays(5);
        checkin.Check_In_for__c = '	Maintenance';
        checkin.Check_in_fuel_reading__c = 10;
        checkin.Check_In_Status__c='Check In';
        //checkin.Check_in_Location__c = glLocation.id;
        insert checkin;
        
        CICO_Check_Out__c Checkout = new CICO_Check_Out__c();
        Checkout.Cassette__c = true;
        Checkout.Check_Out_fuel_reading__c = 45;
        Checkout.Check_Out_Reading__c = 4999;
        Checkout.Check_Out_Location__c = glLocation.id;
        Checkout.Internal_No__c = vehicleMaster.Id;
        Checkout.Check_Out_For__c = 'Maintenance';
        Checkout.Check_Out_Status__c='Check Out';
        insert Checkout;
        
        CICO_Child_Asset__c Childasset = new CICO_Child_Asset__c();
        Childasset.Check_Out__c = Checkout.id;
        //Childasset.Check_In__c = Checkin.id;
        insert Childasset;
        
         CICO_Child_Asset__c Childasset1 = new CICO_Child_Asset__c();
        //Childasset1.Check_Out__c = Checkout.id;
        Childasset1.Check_In__c = Checkin.id;
        insert Childasset1;
        
        //test logic for vf page ctrl - CICO_InspectionPdfCtrl
        PageReference pageRef = Page.CICO_InspectionPdfPage;
        Test.setCurrentPage(pageRef);
        pageRef.getParameters().put('Id', veh.Id);
        ApexPages.StandardController sc = new ApexPages.StandardController(veh);
        CICO_InspectionPdfCtrl testpdf = new CICO_InspectionPdfCtrl(sc);
        CICO_InspectionCtrl inspCtrl = new CICO_InspectionCtrl();
        CICO_InspectionCtrl.getRecordFileDetails(veh.Id);
        CICO_InspectionCtrl.getCheckOutInfo();
        CICO_InspectionCtrl.getCheckOutDetails(vehicleMaster.Id,'Maintenance');
        CICO_InspectionCtrl.getCheckInDetails(vehicleMaster.Id,'Maintenance');
        
       CICO_InspectionCtrl.getVehicleInfo(vehicleMaster.Id);
       CICO_InspectionCtrl.getselectOptions('Case','Status');
        CICO_InspectionCtrl.getWorkshopCoord();
        CICO_InspectionCtrl.updateVehicleMaster(vehicleMaster.Id,'Car');
        CICO_InspectionCtrl.getVehicleMasterList('1224','AE','Dubai','Private');
        CICO_InspectionCtrl.deleteCheckOutChildAssets(Checkout.id);
        CICO_InspectionCtrl.deleteCheckInChildAssets(checkin.Id);
         CICO_InspectionCtrl.sendCheckOutToOracle(Checkout.id);
        CICO_InspectionCtrl.getVehicleChildAssetCustomerInfo('B002131','Vehicle Rental');
        CICO_InspectionCtrl.getVehicleChildAssetCheckIn('B002131','Vehicle Rental');
        
       CICO_InspectionCtrl.deleteFilewithVersionId(testContVer.Id);
       CICO_InspectionCtrl.getCheckInDetailsByCheckInID(checkin.Id);
       CICO_InspectionCtrl.getChildAssetDetails(Checkout.id);
       CICO_InspectionCtrl.getCheckOutDetailsByCheckOutRecId(Checkout.id);
       CICO_InspectionCtrl.deleteRecordInSF(Checkout.id);
       CICO_InspectionCtrl.getCheckInInfo();
       CICO_InspectionCtrl.getChildAssetDetailsCI(checkin.Id);
      // CICO_InspectionCtrl.getVehicleAssetType(vehicleMaster.Id);
        
        Test.startTest();
        
        Test.setMock(HttpCalloutMock.class, new CICO_Services_Mock()); 
        CICO_InspectionCheckInCreationService.createInspectionInOracle(inti.Id);
        
        CICO_InspectionCtrl.submitIntimationReq(inti.Id);
        
        //Test.setMock(HttpCalloutMock.class, new CICO_Services_Mock2());
        CICO_InspectionCtrl.sendCheckInToOracle(checkin.Id);    
      
        
        Test.stopTest(); 
        
       
    
    }
  
}