unpackaged/main/default/objects/Account/fields/ETIN_Employee_Id__c.field-meta.xml
<CustomField>
    <fullName>ETIN_Employee_Id__c</fullName>
    <description>Insurance</description>
    <encryptionScheme>None</encryptionScheme>
    <externalId>true</externalId>
    <label>Employee Id</label>
    <length>50</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

unpackaged/main/default/objects/Account/fields/ETIN_Place_of_Visa_Issuance__c.field-meta.xml
<CustomField>
    <fullName>ETIN_Place_of_Visa_Issuance__c</fullName>
    <description>Insurance</description>
    <label>Place of Visa Issuance</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>UAE_Emirates</valueSetName>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Account/recordTypes/Employee.recordType-meta.xml
<RecordType>
    <fullName>Employee</fullName>
    <active>false</active>
    <label>Employee</label>
</RecordType>

unpackaged/main/default/objects/ETIN_Insurance__c/ETIN_Insurance__c.object-meta.xml
<CustomObject>
    <label>Insurance</label>
    <nameField>
        <displayFormat>ETIN-{000000}</displayFormat>
        <label>Insurance Ref Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Insurances</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

unpackaged/main/default/objects/ETIN_Insurance__c/fields/Card_Number__c.field-meta.xml
<CustomField>
    <fullName>Card_Number__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Card Number</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/ETIN_Insurance__c/fields/EmployeeAcc__c.field-meta.xml
<CustomField>
    <fullName>EmployeeAcc__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Employee</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Insurances</relationshipLabel>
    <relationshipName>Insurances</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/ETIN_Insurance__c/fields/Insurance_Company__c.field-meta.xml
<CustomField>
    <fullName>Insurance_Company__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Insurance Company</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Insurance</relationshipLabel>
    <relationshipName>Insurance</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/ETIN_Insurance__c/fields/Insurance_Current_Status__c.field-meta.xml
<CustomField>
    <fullName>Insurance_Current_Status__c</fullName>
    <label>Insurance Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Active</fullName>
            </value>
            <value>
                <fullName>Inactive</fullName>
                <default>true</default>
                <label>Inactive</label>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
            <value>
                <fullName>Duplicate</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/ETIN_Insurance__c/fields/Insurance_Policy_Number__c.field-meta.xml
<CustomField>
    <fullName>Insurance_Policy_Number__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Insurance Policy Number</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/ETIN_Insurance__c/fields/Previous_Insurance__c.field-meta.xml
<CustomField>
    <fullName>Previous_Insurance__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Previous Insurance</label>
    <referenceTo>ETIN_Insurance__c</referenceTo>
    <relationshipLabel>Insurance</relationshipLabel>
    <relationshipName>Insurance</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/ETIN_Insurance__c/fields/Renew_Request__c.field-meta.xml
<CustomField>
    <fullName>Renew_Request__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Renewal Request?</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/objects/ETIN_Insurance__c/fields/Renew_Status__c.field-meta.xml
<CustomField>
    <fullName>Renew_Status__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Renew Status</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/objects/ETIN_Insurance__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Request Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>New</fullName>
                <default>true</default>
                <label>New</label>
            </value>
            <value>
                <fullName>Pending with HR Manager</fullName>
            </value>
            <value>
                <fullName>Under Process</fullName>
            </value>
            <value>
                <fullName>Under Approval</fullName>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
            <value>
                <fullName>Pending with Zone Coordinator</fullName>
            </value>
            <value>
                <fullName>Not Eligible</fullName>
            </value>
            <value>
                <fullName>Under Investigation</fullName>
            </value>
            <value>
                <fullName>Hold</fullName>
            </value>
            <value>
                <fullName>Admin Approval Pending</fullName>
                <isActive>false</isActive>
                <label>Admin Approval Pending</label>
            </value>
            <value>
                <fullName>Admin Approved</fullName>
                <isActive>false</isActive>
                <label>Admin Approved</label>
            </value>
            <value>
                <fullName>Admin Rejected</fullName>
                <isActive>false</isActive>
                <label>Admin Rejected</label>
            </value>
            <value>
                <fullName>HR Rejected</fullName>
                <isActive>false</isActive>
                <label>HR Rejected</label>
            </value>
            <value>
                <fullName>Insurance Approved</fullName>
                <isActive>false</isActive>
                <label>Insurance Approved</label>
            </value>
            <value>
                <fullName>Insurance Pending</fullName>
                <isActive>false</isActive>
                <label>Insurance Pending</label>
            </value>
            <value>
                <fullName>Insurance Rejected</fullName>
                <isActive>false</isActive>
                <label>Insurance Rejected</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/globalValueSets/UAE_Emirates.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Abu Dhabi</fullName>
    </customValue>
    <customValue>
        <fullName>Ajman</fullName>
    </customValue>
    <customValue>
        <fullName>Dubai</fullName>
    </customValue>
    <customValue>
        <fullName>Fujairah</fullName>
    </customValue>
    <customValue>
        <fullName>Ras Al Khaimah</fullName>
    </customValue>
    <customValue>
        <fullName>Sharjah</fullName>
    </customValue>
    <customValue>
        <fullName>Umm Al Quwain</fullName>
    </customValue>
    <customValue>
        <fullName>GCC - Abu Dhabi</fullName>
    </customValue>
    <customValue>
        <fullName>GCC - Dubai and Northern Emirates</fullName>
    </customValue>
    <customValue>
        <fullName>UAE Nationality - Dubai</fullName>
    </customValue>
    <customValue>
        <fullName>UAE Nationality - Abu Dhabi</fullName>
    </customValue>
    <masterLabel>UAE Emirates</masterLabel>
</GlobalValueSet>

unpackaged/main/default/classes/ETIN_InsuranceHelperTest.cls
@isTest
public class ETIN_InsuranceHelperTest {
    
    private static testmethod void insurnaceTrg(){
        
        Account acc = new Account();
        acc.Name = 'ts3232';
        acc.Type = 'Employee';
        acc.ETIN_Employee_Id__c ='232231';
        acc.ETIN_Place_of_Visa_Issuance__c = 'Abu Dhabi';
        insert acc;
       
        
        list<ETIN_Insurance__c> insList = new List<ETIN_Insurance__c>();
        ETIN_Insurance__c et = new ETIN_Insurance__c();
        et.EmployeeAcc__c = acc.Id;
        et.Insurance_Company__c = acc.Id;
        et.Card_Number__c = '24343';
        et.Status__c ='New';
        
        insert et;
        
        ETIN_Insurance__c et2 = new ETIN_Insurance__c();
        et2.EmployeeAcc__c = acc.Id;
        et2.Card_Number__c = '24343';
        et2.Insurance_Policy_Number__c ='2343434';   
        et2.Status__c ='New';
        et2.Insurance_Current_Status__c='Active';
        et2.Status__c ='Completed';
        et2.Renew_Request__c = true;
        et2.Renew_Status__c =false;
        et2.Previous_Insurance__c=et.Id;
        insert et2;
        
       // insList.add(et);
        
    }

}