unpackaged/main/default/objects/Account/fields/ETIN_Activity_Center__c.field-meta.xml
<CustomField>
    <fullName>ETIN_Activity_Center__c</fullName>
    <description>Employee Info</description>
    <encryptionScheme>None</encryptionScheme>
    <label>Activity Center</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Account/fields/ETIN_Activity_Center_Code__c.field-meta.xml
<CustomField>
    <fullName>ETIN_Activity_Center_Code__c</fullName>
    <description>Employee Info</description>
    <encryptionScheme>None</encryptionScheme>
    <label>Activity Center Code</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Account/fields/ETIN_Department_Code__c.field-meta.xml
<CustomField>
    <fullName>ETIN_Department_Code__c</fullName>
    <description>Employee Info</description>
    <encryptionScheme>None</encryptionScheme>
    <label>Department Code</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Account/fields/ETIN_Employee_Zone__c.field-meta.xml
<CustomField>
    <fullName>ETIN_Employee_Zone__c</fullName>
    <description>Employee Info</description>
    <encryptionScheme>None</encryptionScheme>
    <label>Employee Zone</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Account/fields/ETIN_Location__c.field-meta.xml
<CustomField>
    <fullName>ETIN_Location__c</fullName>
    <description>Employee Location - GL</description>
    <encryptionScheme>None</encryptionScheme>
    <label>Location</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Account/fields/ETIN_Location_Code__c.field-meta.xml
<CustomField>
    <fullName>ETIN_Location_Code__c</fullName>
    <description>Employee GL info</description>
    <encryptionScheme>None</encryptionScheme>
    <label>Location Code</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Account/fields/ETIN_Project__c.field-meta.xml
<CustomField>
    <fullName>ETIN_Project__c</fullName>
    <description>Employee GL info</description>
    <encryptionScheme>None</encryptionScheme>
    <label>Project</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Account/fields/ETIN_Project_Code__c.field-meta.xml
<CustomField>
    <fullName>ETIN_Project_Code__c</fullName>
    <description>Employee GL info</description>
    <encryptionScheme>None</encryptionScheme>
    <label>Project Code</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Account/fields/GL_Zone__c.field-meta.xml
<CustomField>
    <fullName>GL_Zone__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>GL Zone</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Contact/fields/Location_Code__c.field-meta.xml
<CustomField>
    <fullName>Location_Code__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Location Code</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Contact/fields/Project_Code__c.field-meta.xml
<CustomField>
    <fullName>Project_Code__c</fullName>
    <description>GL Details</description>
    <encryptionScheme>None</encryptionScheme>
    <label>Project Code</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/ETSALES_Department__c/ETSALES_Department__c.object-meta.xml
<CustomObject>
    <label>GL Department</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>GL Department</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>GL Departments</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/ETSALES_Department__c/fields/Department_Code__c.field-meta.xml
<CustomField>
    <fullName>Department_Code__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Department Code</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/ETSALES_Location__c/ETSALES_Location__c.object-meta.xml
<CustomObject>
    <label>GL Location</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>GL Location</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>GL Locations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/ETSALES_Location__c/fields/GL_Zone__c.field-meta.xml
<CustomField>
    <fullName>GL_Zone__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>GL Zone</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/ETSALES_Location__c/fields/Location_Code__c.field-meta.xml
<CustomField>
    <fullName>Location_Code__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Location Code</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/GL_Activity__c/GL_Activity__c.object-meta.xml
<CustomObject>
    <description>to have the oracle GL Activity in SF</description>
    <label>GL Activity</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>GL Activity</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>GL Activities</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/GL_Activity__c/fields/GL_Activity_Code__c.field-meta.xml
<CustomField>
    <fullName>GL_Activity_Code__c</fullName>
    <description>to capture the GL Activity Code</description>
    <encryptionScheme>None</encryptionScheme>
    <label>GL Activity Code</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/GL_Project__c/GL_Project__c.object-meta.xml
<CustomObject>
    <description>to create GL Project of Oracle</description>
    <label>GL Project</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>GL Project</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>GL Projects</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/GL_Project__c/fields/Project_Code__c.field-meta.xml
<CustomField>
    <fullName>Project_Code__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Project Code</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/GL_Zone__c/GL_Zone__c.object-meta.xml
<CustomObject>
    <label>GL Zone</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>GL Zones</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/classes/ETIN_UpdateEmployeeGLDetails.cls
/* Author: Janardhan
 * Date: 17/01/2021
 * Description: This class is created to update GL details(Activity,Dept,Location,Project) names automatically based on GL codes
 */
public class ETIN_UpdateEmployeeGLDetails {

    public static void updateGLDetails(list<Account> trgVal){ 
          
        map<string,string> GLActivityCodeVsName = new map<string,string>();
        map<string,string> GLDeptCodeVsName = new map<string,string>();
        map<string,string> GLLocCodeVsName = new map<string,string>();
        map<string,string> GLLocCodeVsZone = new map<string,string>();
        map<string,string> GLProjCodeVsName = new map<string,string>();
       
        for(GL_Activity__c act : [select id,Name,GL_Activity_Code__c from GL_Activity__c]){
             GLActivityCodeVsName.put(act.GL_Activity_Code__c,act.Name);
        }
        for(ETSALES_Department__c dept : [select id,Name,Department_Code__c from ETSALES_Department__c]){
             GLDeptCodeVsName.put(dept.Department_Code__c,dept.Name);
        }
        for(ETSALES_Location__c loc : [select id,Name,Location_Code__c,GL_Zone__c from ETSALES_Location__c]){
             GLLocCodeVsName.put(loc.Location_Code__c,loc.Name);
             GLLocCodeVsZone.put(loc.Location_Code__c,loc.GL_Zone__c);
        }
         for(GL_Project__c pro : [select id,Name,Project_Code__c from GL_Project__c]){
             GLProjCodeVsName.put(pro.Project_Code__c,pro.Name);
        }
    
         //Updating Contact GL Info
    
        for(Account vm : trgVal){
            
            vm.ETIN_Activity_Center__c = GLActivityCodeVsName.containsKey(vm.ETIN_Activity_Center_Code__c)?GLActivityCodeVsName.get(vm.ETIN_Activity_Center_Code__c):'';
            //vm.PersonDepartment = GLDeptCodeVsName.containsKey(vm.ETIN_Department_Code__c)?GLDeptCodeVsName.get(vm.ETIN_Department_Code__c):'';
            vm.ETIN_Location__c = GLLocCodeVsName.containsKey(vm.ETIN_Location_Code__c)?GLLocCodeVsName.get(vm.ETIN_Location_Code__c):'';
            vm.ETIN_Employee_Zone__c = GLLocCodeVsZone.containsKey(vm.ETIN_Location_Code__c)?GLLocCodeVsZone.get(vm.ETIN_Location_Code__c):'';
            vm.ETIN_Project__c = GLProjCodeVsName.containsKey(vm.ETIN_Project_Code__c)?GLProjCodeVsName.get(vm.ETIN_Project_Code__c):'';
            
        }
        }
    
   

}