unpackaged/main/default/objects/Account/fields/ETIN_Employee_Id__c.field-meta.xml
<CustomField>
    <fullName>ETIN_Employee_Id__c</fullName>
    <description>Insurance</description>
    <encryptionScheme>None</encryptionScheme>
    <externalId>true</externalId>
    <label>Employee Id</label>
    <length>50</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

unpackaged/main/default/objects/GI_General_Insurance_Policy__c/GI_General_Insurance_Policy__c.object-meta.xml
<CustomObject>
    <label>General Insurance Policy</label>
    <nameField>
        <displayFormat>GIP-{00000}</displayFormat>
        <label>Ref Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>General Insurance Policies</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/GI_General_Insurance_Policy__c/fields/Insurance_Type__c.field-meta.xml
<CustomField>
    <fullName>Insurance_Type__c</fullName>
    <label>Insurance Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>General_Insurance_Types</valueSetName>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/GI_General_Insurance_Policy__c/fields/Money_Policy_For__c.field-meta.xml
<CustomField>
    <fullName>Money_Policy_For__c</fullName>
    <label>Money Policy For</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Cash &amp; Transact</fullName>
            </value>
            <value>
                <fullName>Cash &amp; Save</fullName>
            </value>
            <value>
                <fullName>Cash &amp; Drawer</fullName>
            </value>
            <value>
                <fullName>Fuel Card</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/GI_General_Insurance_Policy__c/fields/Request_Type__c.field-meta.xml
<CustomField>
    <fullName>Request_Type__c</fullName>
    <label>Request Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>New</fullName>
                <default>true</default>
                <label>New</label>
            </value>
            <value>
                <fullName>Renewal</fullName>
            </value>
            <value>
                <fullName>Quotation</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/GI_General_Insurance_Request__c/GI_General_Insurance_Request__c.object-meta.xml
<CustomObject>
    <label>General Insurance Request</label>
    <nameField>
        <displayFormat>GIR-{00000}</displayFormat>
        <label>Ref Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>General Insurance Requests</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/GI_General_Insurance_Request__c/fields/Insurance_Policy__c.field-meta.xml
<CustomField>
    <fullName>Insurance_Policy__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Insurance Policy</label>
    <referenceTo>GI_General_Insurance_Policy__c</referenceTo>
    <relationshipLabel>General Insurance Requests</relationshipLabel>
    <relationshipName>General_Insurance_Requests</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/GI_General_Insurance_Request__c/fields/Request_Type__c.field-meta.xml
<CustomField>
    <fullName>Request_Type__c</fullName>
    <label>Request Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Addition</fullName>
            </value>
            <value>
                <fullName>Correction/Amendment</fullName>
            </value>
            <value>
                <fullName>Deletion</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/globalValueSets/General_Insurance_Types.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Property All Risk</fullName>
    </customValue>
    <customValue>
        <fullName>Fidility Guarantee</fullName>
    </customValue>
    <customValue>
        <fullName>Fire and Allied Perils Insurance</fullName>
    </customValue>
    <customValue>
        <fullName>Third Party Liability</fullName>
    </customValue>
    <customValue>
        <fullName>Public Liability</fullName>
    </customValue>
    <customValue>
        <fullName>Contractor&#39;s Plant &amp; Machinery</fullName>
    </customValue>
    <customValue>
        <fullName>Hauliers General Cargo</fullName>
    </customValue>
    <customValue>
        <fullName>Hauliers Petrolium</fullName>
    </customValue>
    <customValue>
        <fullName>Work Compensation (W.COMP)</fullName>
    </customValue>
    <customValue>
        <fullName>Money Policy</fullName>
    </customValue>
    <customValue>
        <fullName>Product Liability</fullName>
    </customValue>
    <customValue>
        <fullName>Professional Indemnity</fullName>
    </customValue>
    <customValue>
        <fullName>Machinery All Risks</fullName>
    </customValue>
    <customValue>
        <fullName>Aviation Contractors Liability</fullName>
    </customValue>
    <customValue>
        <fullName>Technical Inspection Center TP</fullName>
        <isActive>false</isActive>
        <label>Technical Inspection Center TP</label>
    </customValue>
    <customValue>
        <fullName>Technical Inspection Center CPM</fullName>
        <isActive>false</isActive>
        <label>Technical Inspection Center CPM</label>
    </customValue>
    <customValue>
        <fullName>Work Injuries</fullName>
        <isActive>false</isActive>
        <label>Work Injuries</label>
    </customValue>
    <customValue>
        <fullName>Third Party Liablity D &amp; N</fullName>
        <isActive>false</isActive>
        <label>Third Party Liablity D &amp; N</label>
    </customValue>
    <description>For General Insurance</description>
    <masterLabel>General Insurance Types</masterLabel>
</GlobalValueSet>

unpackaged/main/default/classes/GIN_InsuranceLinesInsertHandlerTest.cls
@isTest
public class GIN_InsuranceLinesInsertHandlerTest {
    
    public static testmethod void linesInsert(){
        
        GI_General_Insurance_Policy__c po = new GI_General_Insurance_Policy__c();
        po.Insurance_Type__c ='Money Policy';
        po.Money_Policy_For__c ='Fuel Card';
        insert po;
        
        Account acc = new Account();
        acc.Name = 'test';
        acc.ETIN_Employee_Id__c ='832183';
       
        insert acc;
        
        JSONGenerator gen = JSON.createGenerator(true);
        gen.writeStartArray();
        gen.writeStartObject();
        gen.writeStringField('FinanceNumber','832183');
        gen.writeStringField('InsuranceLimit', '2000');
        gen.writeEndObject();
        gen.writeEndArray();
        String fileData = gen.getAsString();
        
        GIN_InsuranceLinesInsertHandler.insertData(fileData, po.Id);
        GIN_InsuranceLinesInsertHandler.getInsLinesData(po.Id);
        
        JSONGenerator gen1 = JSON.createGenerator(true);
        gen1.writeStartArray();
        gen1.writeStartObject();
        gen1.writeStringField('FinanceNumber','832183');
        gen1.writeEndObject();
        gen1.writeEndArray();
        String fileData2 = gen.getAsString();
        
        GIN_InsuranceLinesInsertHandler.insertDataWorkComp(fileData2, po.Id);
        
        GI_General_Insurance_Request__c req = new GI_General_Insurance_Request__c();
        req.Insurance_Policy__c =po.Id;
        req.Request_Type__c ='Addition';
        insert req;
        
        GIN_InsuranceLinesInsertHandler.insertMoneyPolicyUnderInsReq(fileData, req.Id, 'Addition', po.Id);
        GIN_InsuranceLinesInsertHandler.getInsLinesByInsReqId(req.Id);
        
        GIN_InsuranceLinesInsertHandler.insertDataWorkCompUnderInsReq(fileData2, req.Id, 'Addition', po.Id);
        
    }
    

}