unpackaged/main/default/objects/Account/fields/ETIN_Employee_Id__c.field-meta.xml
<CustomField>
    <fullName>ETIN_Employee_Id__c</fullName>
    <description>Insurance</description>
    <encryptionScheme>None</encryptionScheme>
    <externalId>true</externalId>
    <label>Employee Id</label>
    <length>50</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

unpackaged/main/default/objects/Account/fields/ETIN_Employee_Zone__c.field-meta.xml
<CustomField>
    <fullName>ETIN_Employee_Zone__c</fullName>
    <description>Employee Info</description>
    <encryptionScheme>None</encryptionScheme>
    <label>Employee Zone</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Account/recordTypes/Employee.recordType-meta.xml
<RecordType>
    <fullName>Employee</fullName>
    <active>false</active>
    <label>Employee</label>
</RecordType>

unpackaged/main/default/objects/User/fields/ETSALES_Employee_Zone__c.field-meta.xml
<CustomField>
    <fullName>ETSALES_Employee_Zone__c</fullName>
    <label>Employee Zone</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Zone A</fullName>
            </value>
            <value>
                <fullName>Zone B</fullName>
            </value>
            <value>
                <fullName>Zone C</fullName>
            </value>
            <value>
                <fullName>Head Office</fullName>
            </value>
            <value>
                <fullName>Technical Services</fullName>
            </value>
            <value>
                <fullName>HO</fullName>
            </value>
            <value>
                <fullName>KAM</fullName>
                <isActive>false</isActive>
                <label>KAM</label>
            </value>
            <value>
                <fullName>MRO</fullName>
                <isActive>false</isActive>
                <label>MRO</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/classes/ETIN_notifyUsersOnNewEmployeeCreation.cls
public class ETIN_notifyUsersOnNewEmployeeCreation {
    
    public static void notifyInsuranceUsers(Map<Id,account> trgNewMap){
        
       //Deactiving this feature by business request-JANARDHAN
      /*  map<string,string> accIdvsZone = new map<string,string>();
        set<string> zonesSet = new set<string>();
        map<string,list<string>> zoneVsEmails = new map<string,list<string>>();
        
         for(account acc : trgNewMap.values()){
             if(acc.ETIN_Employee_Zone__c != null && acc.Type=='Employee'){
                 
               accIdvsZone.put(acc.Id,acc.ETIN_Employee_Zone__c);
               zonesSet.add(acc.ETIN_Employee_Zone__c);
             }
           
        }
        
         for(user u : [select id,name,email,ETSALES_Employee_Zone__c from user where ETSALES_Employee_Zone__c =:zonesSet AND isactive=True AND profile.Name=:System.Label.INS_ZoneCordProfileName]){
            
            if(!zoneVsEmails.containsKey(u.ETSALES_Employee_Zone__c)) {
                zoneVsEmails.put(u.ETSALES_Employee_Zone__c, new List<string>());
            }
            zoneVsEmails.get(u.ETSALES_Employee_Zone__c).add(u.email);
        }
        
       OrgWideEmailAddress[] owea = [SELECT Id,Address FROM OrgWideEmailAddress WHERE DisplayName =:System.Label.CICO_OrgWideEmail];
      EmailTemplate template = [SELECT Id,Subject,Body,HtmlValue,DeveloperName FROM EmailTemplate WHERE DeveloperName ='ETIN_newEmpCreationNotification'];
        
        
          Messaging.SingleEmailMessage[] emailList = new list<Messaging.SingleEmailMessage>(); 
             
        for(account acc : trgNewMap.values()){
            
            if(acc.ETIN_Employee_Zone__c != null && zoneVsEmails.containskey(acc.ETIN_Employee_Zone__c)){
                
                Messaging.SingleEmailMessage email = Messaging.renderStoredEmailTemplate(template.Id,null,acc.Id);
                
                email.toAddresses = zoneVsEmails.get(acc.ETIN_Employee_Zone__c);
                if ( owea != null && owea.size() > 0 ) {
                    email.setOrgWideEmailAddressId(owea.get(0).Id);
                }
                email.setSubject('New Health Insurance Request - '+acc.ETIN_Employee_Id__c);
                //email.setWhatId(acc.Id);
                //email.setTemplateId(template.Id);           
                email.setSaveAsActivity(false);
                email.setTargetObjectId(userinfo.getUserId());
                email.setTreatTargetObjectAsRecipient(false);
                
                emailList.add(email);
            }
           
        }  
        
         //send an email
        Messaging.SendEmailResult[] results = Messaging.sendEmail(emailList);
   
        */
    }

}