unpackaged/main/default/objects/Account/fields/ETSALES_Email__c.field-meta.xml
<CustomField>
    <fullName>ETSALES_Email__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Email Id</label>
    <type>Email</type>
</CustomField>

unpackaged/main/default/objects/Contact/fields/Location_Code__c.field-meta.xml
<CustomField>
    <fullName>Location_Code__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Location Code</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Contact/fields/Project_Code__c.field-meta.xml
<CustomField>
    <fullName>Project_Code__c</fullName>
    <description>GL Details</description>
    <encryptionScheme>None</encryptionScheme>
    <label>Project Code</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/ETSALES_Department__c/ETSALES_Department__c.object-meta.xml
<CustomObject>
    <label>GL Department</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>GL Department</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>GL Departments</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/ETSALES_Department__c/fields/Department_Code__c.field-meta.xml
<CustomField>
    <fullName>Department_Code__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Department Code</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/ETSALES_Location__c/ETSALES_Location__c.object-meta.xml
<CustomObject>
    <label>GL Location</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>GL Location</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>GL Locations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/ETSALES_Location__c/fields/Location_Code__c.field-meta.xml
<CustomField>
    <fullName>Location_Code__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Location Code</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/GL_Activity__c/GL_Activity__c.object-meta.xml
<CustomObject>
    <description>to have the oracle GL Activity in SF</description>
    <label>GL Activity</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>GL Activity</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>GL Activities</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/GL_Activity__c/fields/GL_Activity_Code__c.field-meta.xml
<CustomField>
    <fullName>GL_Activity_Code__c</fullName>
    <description>to capture the GL Activity Code</description>
    <encryptionScheme>None</encryptionScheme>
    <label>GL Activity Code</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/GL_Project__c/GL_Project__c.object-meta.xml
<CustomObject>
    <description>to create GL Project of Oracle</description>
    <label>GL Project</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>GL Project</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>GL Projects</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/GL_Project__c/fields/Project_Code__c.field-meta.xml
<CustomField>
    <fullName>Project_Code__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Project Code</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Opportunity/fields/Competitor__c.field-meta.xml
<CustomField>
    <fullName>Competitor__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Competitor Before ET (Current Contract)</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Opportunity/fields/Contract_Days__c.field-meta.xml
<CustomField>
    <fullName>Contract_Days__c</fullName>
    <label>Contract Days (Current Contract)</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>No_of_Days</valueSetName>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Opportunity/fields/Contract_Months__c.field-meta.xml
<CustomField>
    <fullName>Contract_Months__c</fullName>
    <label>Contract Months (Current Contract)</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>ETSales_No_of_Months</valueSetName>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Opportunity/fields/Contract_Type__c.field-meta.xml
<CustomField>
    <fullName>Contract_Type__c</fullName>
    <label>Contract Type (Current Contract)</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Standard</fullName>
            </value>
            <value>
                <fullName>Blanket Agreement</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Opportunity/fields/Contract_Weeks__c.field-meta.xml
<CustomField>
    <fullName>Contract_Weeks__c</fullName>
    <label>Contract Weeks (Current Contract)</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>ETSales_No_of_Weeks</valueSetName>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Opportunity/fields/Contract_Years__c.field-meta.xml
<CustomField>
    <fullName>Contract_Years__c</fullName>
    <label>Contract Years (Current Contract)</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>ETSales_No_of_Years</valueSetName>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Opportunity/fields/ETSALES_Customer_Budget__c.field-meta.xml
<CustomField>
    <fullName>ETSALES_Customer_Budget__c</fullName>
    <label>Customer Budget (Current Contract)</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

unpackaged/main/default/objects/Opportunity/fields/ETSALES_GL_Services__c.field-meta.xml
<CustomField>
    <fullName>ETSALES_GL_Services__c</fullName>
    <label>ET Service (Current Contract)</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>ETSALES_Service_Type_Values</valueSetName>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Opportunity/fields/GL_Activity__c.field-meta.xml
<CustomField>
    <fullName>GL_Activity__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>GL Activity</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Opportunity/fields/GL_Department__c.field-meta.xml
<CustomField>
    <fullName>GL_Department__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>GL Department</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Opportunity/fields/GL_Project__c.field-meta.xml
<CustomField>
    <fullName>GL_Project__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>GL Project</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Opportunity/fields/isPricingCreated__c.field-meta.xml
<CustomField>
    <fullName>isPricingCreated__c</fullName>
    <defaultValue>false</defaultValue>
    <label>isPricingCreated</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/objects/Opportunity/fields/No_of_Resources__c.field-meta.xml
<CustomField>
    <fullName>No_of_Resources__c</fullName>
    <label>No. of Resources (Current Contract)</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

unpackaged/main/default/objects/Opportunity/fields/No_of_Used_Vehicles__c.field-meta.xml
<CustomField>
    <fullName>No_of_Used_Vehicles__c</fullName>
    <label>No. of Used Vehicles (Current Contract)</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

unpackaged/main/default/objects/Opportunity/fields/No_of_Vehicles__c.field-meta.xml
<CustomField>
    <fullName>No_of_Vehicles__c</fullName>
    <label>No. of New Vehicles (Current Contract)</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

unpackaged/main/default/objects/User/fields/ETSALES_Location__c.field-meta.xml
<CustomField>
    <fullName>ETSALES_Location__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>GL Location</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/User/fields/GL_Activity_Code__c.field-meta.xml
<CustomField>
    <fullName>GL_Activity_Code__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>GL Activity Code</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/User_GL_Mapping__c/User_GL_Mapping__c.object-meta.xml
<CustomObject>
    <description>to store the GL mapping and use it where ever rrequired</description>
    <label>User GL Mapping</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>User Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>User GL Mappings</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/User_GL_Mapping__c/fields/ETSALES_GL_Location__c.field-meta.xml
<CustomField>
    <fullName>ETSALES_GL_Location__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>GL Location</label>
    <referenceTo>ETSALES_Location__c</referenceTo>
    <relationshipLabel>User GL Mappings</relationshipLabel>
    <relationshipName>User_GL_Mappings</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/User_GL_Mapping__c/fields/GL_Activity__c.field-meta.xml
<CustomField>
    <fullName>GL_Activity__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>GL Activity</label>
    <referenceTo>GL_Activity__c</referenceTo>
    <relationshipLabel>User GL Mappings</relationshipLabel>
    <relationshipName>User_GL_Mappings</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/User_GL_Mapping__c/fields/GL_Department__c.field-meta.xml
<CustomField>
    <fullName>GL_Department__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>GL Department</label>
    <referenceTo>ETSALES_Department__c</referenceTo>
    <relationshipLabel>User GL Mappings</relationshipLabel>
    <relationshipName>User_GL_Mappings</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/User_GL_Mapping__c/fields/GL_Project__c.field-meta.xml
<CustomField>
    <fullName>GL_Project__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>GL Project</label>
    <referenceTo>GL_Project__c</referenceTo>
    <relationshipLabel>User GL Mappings</relationshipLabel>
    <relationshipName>User_GL_Mappings</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/User_GL_Mapping__c/fields/User__c.field-meta.xml
<CustomField>
    <fullName>User__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>User</label>
    <referenceTo>User</referenceTo>
    <relationshipName>User_GL_Mappings</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/globalValueSets/ETSales_No_of_Months.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>1</fullName>
    </customValue>
    <customValue>
        <fullName>2</fullName>
    </customValue>
    <customValue>
        <fullName>3</fullName>
    </customValue>
    <customValue>
        <fullName>4</fullName>
    </customValue>
    <customValue>
        <fullName>5</fullName>
    </customValue>
    <customValue>
        <fullName>6</fullName>
    </customValue>
    <customValue>
        <fullName>7</fullName>
    </customValue>
    <customValue>
        <fullName>8</fullName>
    </customValue>
    <customValue>
        <fullName>9</fullName>
    </customValue>
    <customValue>
        <fullName>10</fullName>
    </customValue>
    <customValue>
        <fullName>11</fullName>
    </customValue>
    <customValue>
        <fullName>12</fullName>
        <isActive>false</isActive>
        <label>12</label>
    </customValue>
    <masterLabel>No of Months</masterLabel>
</GlobalValueSet>

unpackaged/main/default/globalValueSets/ETSales_No_of_Weeks.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>1</fullName>
    </customValue>
    <customValue>
        <fullName>2</fullName>
    </customValue>
    <customValue>
        <fullName>3</fullName>
    </customValue>
    <customValue>
        <fullName>4</fullName>
        <isActive>false</isActive>
        <label>4</label>
    </customValue>
    <masterLabel>No of Weeks</masterLabel>
</GlobalValueSet>

unpackaged/main/default/globalValueSets/ETSales_No_of_Years.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>1</fullName>
    </customValue>
    <customValue>
        <fullName>2</fullName>
    </customValue>
    <customValue>
        <fullName>3</fullName>
    </customValue>
    <customValue>
        <fullName>4</fullName>
    </customValue>
    <customValue>
        <fullName>5</fullName>
    </customValue>
    <customValue>
        <fullName>6</fullName>
    </customValue>
    <customValue>
        <fullName>7</fullName>
    </customValue>
    <customValue>
        <fullName>8</fullName>
    </customValue>
    <customValue>
        <fullName>9</fullName>
    </customValue>
    <customValue>
        <fullName>10</fullName>
    </customValue>
    <masterLabel>No of Years</masterLabel>
</GlobalValueSet>

unpackaged/main/default/globalValueSets/ETSALES_Service_Type_Values.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Airport drop off</fullName>
    </customValue>
    <customValue>
        <fullName>Chauffeur - Dubai</fullName>
    </customValue>
    <customValue>
        <fullName>Chauffeur - Others</fullName>
    </customValue>
    <customValue>
        <fullName>Abu Dhabi</fullName>
    </customValue>
    <customValue>
        <fullName>Documents</fullName>
    </customValue>
    <customValue>
        <fullName>Motor Cycle</fullName>
    </customValue>
    <customValue>
        <fullName>Electric Car</fullName>
    </customValue>
    <customValue>
        <fullName>Vehicle</fullName>
    </customValue>
    <customValue>
        <fullName>Government School</fullName>
    </customValue>
    <customValue>
        <fullName>Quran Studies</fullName>
    </customValue>
    <customValue>
        <fullName>Private School</fullName>
    </customValue>
    <customValue>
        <fullName>Government Executive</fullName>
    </customValue>
    <customValue>
        <fullName>Staff-Employees and Labors</fullName>
    </customValue>
    <customValue>
        <fullName>Haj &amp; Umrah</fullName>
    </customValue>
    <customValue>
        <fullName>University</fullName>
    </customValue>
    <customValue>
        <fullName>Club Members</fullName>
    </customValue>
    <customValue>
        <fullName>Vehicle Auctioning</fullName>
    </customValue>
    <customValue>
        <fullName>Sale Of Scrap Materials</fullName>
    </customValue>
    <customValue>
        <fullName>Maintenance Services - Contracted</fullName>
    </customValue>
    <customValue>
        <fullName>Maintenance Services - Non-Contracted</fullName>
    </customValue>
    <customValue>
        <fullName>Luxury Vehicles Maintenance</fullName>
    </customValue>
    <customValue>
        <fullName>Dry Wash</fullName>
    </customValue>
    <customValue>
        <fullName>Tire Rethreading and Repair</fullName>
    </customValue>
    <customValue>
        <fullName>Refurbished and used tire Sales</fullName>
    </customValue>
    <customValue>
        <fullName>Road Side Assistance</fullName>
    </customValue>
    <customValue>
        <fullName>Body-Accident Repair services</fullName>
    </customValue>
    <customValue>
        <fullName>Bus Refurbishment</fullName>
    </customValue>
    <customValue>
        <fullName>CNG Conversion Services</fullName>
    </customValue>
    <customValue>
        <fullName>Vehicle Inspection</fullName>
    </customValue>
    <customValue>
        <fullName>Heavy Equipment Maintenance</fullName>
    </customValue>
    <masterLabel>GL Service Type Values</masterLabel>
</GlobalValueSet>

unpackaged/main/default/globalValueSets/No_of_Days.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>1</fullName>
    </customValue>
    <customValue>
        <fullName>2</fullName>
    </customValue>
    <customValue>
        <fullName>3</fullName>
    </customValue>
    <customValue>
        <fullName>4</fullName>
    </customValue>
    <customValue>
        <fullName>5</fullName>
    </customValue>
    <customValue>
        <fullName>6</fullName>
    </customValue>
    <customValue>
        <fullName>7</fullName>
        <isActive>false</isActive>
        <label>7</label>
    </customValue>
    <masterLabel>No of Days</masterLabel>
</GlobalValueSet>

unpackaged/main/default/classes/ETP_OpportunityTrigger_HandlerTest.cls
@IsTest
public class ETP_OpportunityTrigger_HandlerTest {
    
    public  static testMethod void setupdata(){ 
        // create test user
        Profile p = [SELECT Id FROM Profile WHERE Name='Standard User']; 
        User u = new User(Alias = 'standt', Email='standarduser@sm.com', 
                          EmailEncodingKey='UTF-8', isActive = true, LastName='Testing', LanguageLocaleKey='en_US', 
                          LocaleSidKey='en_US', ProfileId = p.Id, 
                          TimeZoneSidKey='America/Los_Angeles', UserName='standarduser@sm.com');
        insert u;
        
        Profile userProfile = [SELECT Id FROM Profile WHERE Name='System Administrator'];
        
        GL_Activity__c	test_Activity = new GL_Activity__c(Name= 'test_Activity', GL_Activity_Code__c = '0001');
        GL_Project__c	test_Project = new GL_Project__c (Name = 'test_Project', Project_Code__c = '0002');
        ETSALES_Department__c	test_Dept = new ETSALES_Department__c (Name = 'test_Dept' , Department_Code__c = '0003');
        ETSALES_Location__c	test_location  = new ETSALES_Location__c(Name = 'test_Location',Location_Code__c='0004');
        
        insert test_Activity;
        insert test_Project;
        insert test_Dept;
        insert test_location;
        
        User_GL_Mapping__c mappingRecList = new User_GL_Mapping__c (Name = 'Test Mapping',User__c = u.Id,GL_Activity__c =test_Activity.Id ,
                                                                    GL_Department__c =test_Dept.Id ,ETSALES_GL_Location__c = test_location.Id,
                                                                    GL_Project__c= test_Project.Id);
        Insert mappingRecList;
        
        
        Id recordTypeId = Schema.SObjectType.Account.getRecordTypeInfosByName().get('Person (B2C)').getRecordTypeId();
        Account acc = new Account();
        acc.FirstName = 'test';
        acc.LastName = 'test';
        acc.PersonEmail = 'test@gmail.com';
        acc.RecordTypeId = recordTypeId;
        acc.ETSALES_Email__c = 'testAcc@gmail.com';
        insert acc;
        
        Contact con = new Contact();
        con.LastName = 'Noor';
        con.Email = Label.ETI_TargetObject_Email;
        insert con;
        
        Opportunity test_Opportunity = new Opportunity (Name = 'test Opportunity' ,AccountID = acc.Id,StageName = 'Qualification', CloseDate= System.today(),
                                                        OwnerId = u.Id,
                                                        ETSALES_GL_Services__c='Government School', 
                                                        Contract_Type__c= 'Standard',
                                                        Contract_Years__c= '1',
                                                        Contract_Months__c= '2',
                                                        Contract_Weeks__c= '2',
                                                        Contract_Days__c= '2',
                                                        Competitor__c= 'NO',
                                                        No_of_Vehicles__c= Decimal.valueOf('1'),
                                                        No_of_Used_Vehicles__c= Decimal.valueOf('1'),
                                                        No_of_Resources__c= Decimal.valueOf('1'),
                                                        isPricingCreated__c=true
                                                        
                                                        // ETSALES_Customer_Budget__c='1231AED'
                                                        
                                                       );
        insert test_Opportunity;
        Opportunity test_Opportunity1 = new Opportunity (Name = 'test Opportunity' ,AccountID = acc.Id,StageName = 'Qualification', CloseDate= System.today(),
                                                         OwnerId = u.Id,
                                                         ETSALES_GL_Services__c='Government School', 
                                                         Contract_Type__c= 'Standard',
                                                         Contract_Years__c= '1',
                                                         Contract_Months__c= '2',
                                                         Contract_Weeks__c= '2',
                                                         Contract_Days__c= '2',
                                                         Competitor__c= 'NO',
                                                         No_of_Vehicles__c= Decimal.valueOf('1'),
                                                         No_of_Used_Vehicles__c= Decimal.valueOf('1'),
                                                         No_of_Resources__c= Decimal.valueOf('1')
                                                         // ETSALES_Customer_Budget__c='1231AED'
                                                         
                                                        );
        insert test_Opportunity1;
        List<Opportunity> oppList = new List<Opportunity>();
        oppList.add(test_Opportunity);
        oppList.add(test_Opportunity1);
        
        List<string> toAddress = new List<string>(); 
        toAddress.add('element@web.com');
        toAddress.add('el@web.com');
        
        System.Test.startTest();
        // ETP_OpportunityTrigger_Handler.updateHeadOfSales(oppList);        
        ETP_OpportunityTrigger_Handler.testcodeCoverage();
        System.Test.stopTest();
    }
}