unpackaged/main/default/objects/Account/fields/ETSALES_Account_Type__c.field-meta.xml
<CustomField>
    <fullName>ETSALES_Account_Type__c</fullName>
    <label>Account Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Service</fullName>
            </value>
            <value>
                <fullName>Sports And Social Club</fullName>
            </value>
            <value>
                <fullName>Ministry And Government</fullName>
            </value>
            <value>
                <fullName>Rent</fullName>
            </value>
            <value>
                <fullName>Transport</fullName>
            </value>
            <value>
                <fullName>Contracting And Decoration</fullName>
            </value>
            <value>
                <fullName>Haj And Ommrah</fullName>
            </value>
            <value>
                <fullName>Hotel,Restaurant,Catering,Tourism,Travel</fullName>
            </value>
            <value>
                <fullName>Education</fullName>
            </value>
            <value>
                <fullName>Petrol And Gas</fullName>
            </value>
            <value>
                <fullName>Welfare Society</fullName>
            </value>
            <value>
                <fullName>Factory</fullName>
            </value>
            <value>
                <fullName>Trading And Commercial</fullName>
            </value>
            <value>
                <fullName>Model School</fullName>
            </value>
            <value>
                <fullName>Individual</fullName>
            </value>
            <value>
                <fullName>Sundary</fullName>
            </value>
            <value>
                <fullName>Leisure and Tourism</fullName>
            </value>
            <value>
                <fullName>Logistic Services</fullName>
            </value>
            <value>
                <fullName>Insurance</fullName>
            </value>
            <value>
                <fullName>Advertisement And Promotional</fullName>
            </value>
            <value>
                <fullName>Private School</fullName>
            </value>
            <value>
                <fullName>Other</fullName>
            </value>
            <value>
                <fullName>Workshop And Garage</fullName>
            </value>
            <value>
                <fullName>Real Estate</fullName>
            </value>
            <value>
                <fullName>Auction</fullName>
            </value>
            <value>
                <fullName>University And College</fullName>
            </value>
            <value>
                <fullName>MOTO</fullName>
            </value>
            <value>
                <fullName>Ajyal School</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Account/fields/ETSALES_Customer_Account_Id__c.field-meta.xml
<CustomField>
    <fullName>ETSALES_Customer_Account_Id__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <externalId>true</externalId>
    <label>Customer Oracle ID</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Account/fields/ETSALES_Payment_Term_Id__c.field-meta.xml
<CustomField>
    <fullName>ETSALES_Payment_Term_Id__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Payment Term Id</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Account/fields/ETSALES_Payment_Terms__c.field-meta.xml
<CustomField>
    <fullName>ETSALES_Payment_Terms__c</fullName>
    <label>Payment Terms</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Immediate</fullName>
            </value>
            <value>
                <fullName>15 Days</fullName>
            </value>
            <value>
                <fullName>30 NET</fullName>
            </value>
            <value>
                <fullName>30 days</fullName>
            </value>
            <value>
                <fullName>45 Days</fullName>
            </value>
            <value>
                <fullName>60 Days</fullName>
            </value>
            <value>
                <fullName>90 Days</fullName>
            </value>
            <value>
                <fullName>120 Days</fullName>
            </value>
            <value>
                <fullName>180 Days</fullName>
            </value>
            <value>
                <fullName>360 Days</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Account/fields/ETSALES_Profile_Class__c.field-meta.xml
<CustomField>
    <fullName>ETSALES_Profile_Class__c</fullName>
    <label>Profile Class</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>ETSALES_Customer_Type__c</controllingField>
        <valueSetDefinition>
            <value>
                <fullName>Default</fullName>
            </value>
            <value>
                <fullName>Federal Government</fullName>
            </value>
            <value>
                <fullName>Government</fullName>
            </value>
            <value>
                <fullName>Individual</fullName>
            </value>
            <value>
                <fullName>Ministries</fullName>
            </value>
            <value>
                <fullName>Private</fullName>
            </value>
            <value>
                <fullName>Semi Government</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Account/fields/ETSALES_TaxRegistrationNo__c.field-meta.xml
<CustomField>
    <fullName>ETSALES_TaxRegistrationNo__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Tax Registration No</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Account/fields/ETSALES_Trade_License_Expiry_Date__c.field-meta.xml
<CustomField>
    <fullName>ETSALES_Trade_License_Expiry_Date__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Trade License Expiry Date</label>
    <type>Date</type>
</CustomField>

unpackaged/main/default/objects/Account/fields/ETSALES_Trade_License_Number__c.field-meta.xml
<CustomField>
    <fullName>ETSALES_Trade_License_Number__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Trade License Number(Decree No)</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Account/fields/ETT_First_Name__c.field-meta.xml
<CustomField>
    <fullName>ETT_First_Name__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>First Name</label>
    <length>200</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Account/fields/Integration_Message__c.field-meta.xml
<CustomField>
    <fullName>Integration_Message__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Integration Message</label>
    <length>100000</length>
    <type>LongTextArea</type>
</CustomField>

unpackaged/main/default/objects/Account/fields/Integration_Status__c.field-meta.xml
<CustomField>
    <fullName>Integration_Status__c</fullName>
    <label>Integration Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Integration_Status_Value_Set</valueSetName>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Account/fields/Strategic_Account_Manager__c.field-meta.xml
<CustomField>
    <fullName>Strategic_Account_Manager__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Strategic Account Manager</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Accounts</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/ET_Oracle_REST_Endpoints__mdt/ET_Oracle_REST_Endpoints__mdt.object-meta.xml
<CustomObject>
    <description>This meta data created to store all the REST endpoint and authentication details</description>
    <label>ET_Oracle_REST_Endpoint</label>
    <pluralLabel>ET_Oracle_REST_Endpoints</pluralLabel>
</CustomObject>

unpackaged/main/default/objects/ET_Oracle_REST_Endpoints__mdt/fields/Dev_Endpoint__c.field-meta.xml
<CustomField>
    <fullName>Dev_Endpoint__c</fullName>
    <label>Dev Endpoint</label>
    <type>Url</type>
</CustomField>

unpackaged/main/default/objects/ET_Oracle_REST_Endpoints__mdt/fields/LiveEndpoint_c__c.field-meta.xml
<CustomField>
    <fullName>LiveEndpoint_c__c</fullName>
    <label>Live Endpoint</label>
    <type>Url</type>
</CustomField>

unpackaged/main/default/globalValueSets/Integration_Status_Value_Set.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>In Progress</fullName>
    </customValue>
    <customValue>
        <fullName>Success</fullName>
    </customValue>
    <customValue>
        <fullName>Failed</fullName>
    </customValue>
    <customValue>
        <fullName>Error</fullName>
    </customValue>
    <masterLabel>Integration Status Value Set</masterLabel>
</GlobalValueSet>

unpackaged/main/default/classes/MOTO_CICO_AccountInERP.cls
/*
 Developer Name - Srihari Koyila
 Developed Date - 08 June 2023
 Class Name     - MOTO_CICO_AccountInERP
 Class purpose  - this class contains Post method functions which will call the api to push the data into Oracle from salesforce.
 Test Class     - MOTO_IntegrationTest , Oracle_Integration_Mock 


        -- History --
----------------------------------------------------------------------------------------------------------------
Sr.No.  version_DevInitials     Date                Details
1.          V1.0              08 June 2023           Initial Version 
****************************************************************************************************************/
public without sharing class MOTO_CICO_AccountInERP {
    
   @AuraEnabled
    public static string sendAccToERP(string accID, String OppId) {
        system.debug('---'+accID);
        string resVal = null;
        Account accCheck = [Select id,Name, FirstName, LastName, RecordType.Name  from Account where Id =:accID];   
        Account acc = new Account();
        String Name='';
        String accRecordTypeName = ''; 
        accRecordTypeName =accCheck.RecordType.Name ;
        if(accRecordTypeName.contains('Person'))    
        {
            System.debug('Person');
            Name = accCheck.FirstName+' '+accCheck.LastName;
        }
        else
        {
            Name = accCheck.Name;
        }
        System.debug('Name>>>>>' + Name);
        string QueryString = 'Select id,Integration_Message__c,PersonMobilePhone,PersonEmail,Phone,AccountNumber,ETSALES_Customer_Account_Id__c,Industry,ETSALES_Trade_License_Number__c,ETSALES_Trade_License_Expiry_Date__c,ETSALES_TaxRegistrationNo__c,'+
            'ETSALES_Profile_Class__c,ETSALES_Payment_Terms__c ,Strategic_Account_Manager__r.Name,'+
            'ETSALES_Account_Type__c,RecordType.Name ,ETSALES_Payment_Term_Id__c,ETT_First_Name__c,'+
            'PersonTitle,LastModifiedBy.Email from Account where Id =:accID';
        acc = Database.query(QueryString);
        
        String AccountNo = acc.AccountNumber!=null?acc.AccountNumber:'';
        String CustomerName =Name!=null?Name:'';
        String PersonMobilePhone =acc.PersonMobilePhone!=null?acc.PersonMobilePhone:'';
        String PersonEmail = acc.PersonEmail!=null?acc.PersonEmail:'';
        String Phone =acc.Phone!=null?acc.Phone:'';
        String LastModifiedByEmail =acc.LastModifiedBy.Email!=null?acc.LastModifiedBy.Email:'';
        
        
        
        
        ET_Oracle_REST_Endpoints__mdt connection = ET_REST_Authorize_Helper.getSOAPEndpointFromMetadata('MOTO_CreatePersonAccount');
        Blob beforeblob = Blob.valueOf(connection.Username__c+':'+connection.Password__c);
        string paramvalue = EncodingUtil.base64Encode(beforeblob);
        
        JSONGenerator gen = JSON.createGenerator(true);
        gen.writeStartObject();
        gen.writeStringField('AccountNo',String.valueOf(AccountNo));
        gen.writeStringField('SFDC_ID',String.valueOf(acc.Id));
        gen.writeStringField('CustomerName',CustomerName);
        gen.writeStringField('PhoneCountryCode','+971');
        gen.writeStringField('Phone',String.valueOf(Phone));
        gen.writeStringField('Mobile',PersonMobilePhone.right(9));
        gen.writeStringField('MobileCountryCode','+971');
        gen.writeStringField('EMail',String.valueOf(PersonEmail)); 
      //  gen.writeStringField('USER',LastModifiedByEmail); 

        gen.writeEndObject();
        String jsonData = gen.getAsString();
        System.debug('jsonData');
        HttpRequest request = new HttpRequest();
        System.debug('body='+jsonData);
        
        if(ET_REST_Authorize_Helper.runningInASandbox()){
            request.setEndpoint(connection.Dev_Endpoint__c);
            system.debug(connection.Dev_Endpoint__c);
        }else{
            request.setEndpoint(connection.LiveEndpoint_c__c);
        }  
        request.setMethod('POST');
        request.setTimeout(120000);
        request.setHeader('Content-Type', 'application/json');
        request.setBody(jsonData);      
        request.setHeader('Authorization','Basic '+paramvalue);   
        Map<String, Object> responseResult =new Map<String, Object>();
        Http http = new Http();
        HttpResponse response = http.send(request);
        
        System.debug('response body='+response.getBody());
        if (response.getStatusCode() != 200) {
            
            System.debug('Failed ');
            
            responseResult = null;             
            acc.Integration_Message__c  ='Unable to send request to ERP';
            resVal ='Error';
        }
        else{
            if(response.getStatusCode() == 200){
                System.debug('Sucess ');
                Map<String, Object> result = (Map<String, Object>)JSON.deserializeUntyped(response.getBody());
                responseResult =result;
                system.debug('--res--'+responseResult);
                if(string.valueOf(result.get('Status')) =='E'){
                    acc.Integration_Status__c = 'Error';
                    acc.Integration_Message__c = string.valueOf(result.get('Message'));
                    update acc;  
                    resVal ='Error';
                }
            }
          
        
        if(responseResult!=null) {
            String ResponseMessage =(String)responseResult.get('Message');
            String ResponseStatus =(String)responseResult.get('Status');
            System.debug('ResponseStatus='+ResponseStatus);
            System.debug('ResponseMessage='+ResponseMessage);
            if(ResponseStatus.contains('S')){
                string  respcustomerAccountId =(String)responseResult.get('CustAccountId');
                system.debug('---'+respcustomerAccountId);
                if(respcustomerAccountId!=null){
                    acc.AccountNumber =(String)responseResult.get('AccountNo');
                    acc.ETSALES_Customer_Account_Id__c = respcustomerAccountId;
                }
                acc.Integration_Status__c = 'Success';
                acc.Integration_Message__c = 'Customer is created successfully in ERP';
                        
                update acc;
                resVal ='Success';
                
                System.debug(acc.AccountNumber);
                System.debug(OppId);
               /* if(AccountNo==null){
                    system.enqueueJob(new PrivateVehIntegration(acc.AccountNumber,OppId));
                    
                }else{
                    system.enqueueJob(new PrivateVehIntegration(AccountNo,OppId));
                    
                }*/
                 
            }
            
            
        }
       }
        return resVal;
    }
    
    
}