unpackaged/main/default/objects/Account/fields/ETSALES_Customer_Account_Id__c.field-meta.xml
<CustomField>
    <fullName>ETSALES_Customer_Account_Id__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <externalId>true</externalId>
    <label>Customer Oracle ID</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Account/fields/ETSALES_Payment_Terms__c.field-meta.xml
<CustomField>
    <fullName>ETSALES_Payment_Terms__c</fullName>
    <label>Payment Terms</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Immediate</fullName>
            </value>
            <value>
                <fullName>15 Days</fullName>
            </value>
            <value>
                <fullName>30 NET</fullName>
            </value>
            <value>
                <fullName>30 days</fullName>
            </value>
            <value>
                <fullName>45 Days</fullName>
            </value>
            <value>
                <fullName>60 Days</fullName>
            </value>
            <value>
                <fullName>90 Days</fullName>
            </value>
            <value>
                <fullName>120 Days</fullName>
            </value>
            <value>
                <fullName>180 Days</fullName>
            </value>
            <value>
                <fullName>360 Days</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Contact/fields/ETSales_Customer_Account_Id__c.field-meta.xml
<CustomField>
    <fullName>ETSales_Customer_Account_Id__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Customer Account Id</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/ETSALES_Account_Sites__c/ETSALES_Account_Sites__c.object-meta.xml
<CustomObject>
    <label>Account Site</label>
    <nameField>
        <displayFormat>Site-{0000}</displayFormat>
        <label>Account Site Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Account Sites</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

unpackaged/main/default/objects/ETSALES_Account_Sites__c/fields/ETSALES_Account__c.field-meta.xml
<CustomField>
    <fullName>ETSALES_Account__c</fullName>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Account Sites</relationshipLabel>
    <relationshipName>Operating_Unit_Address</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

unpackaged/main/default/objects/ETSALES_Account_Sites__c/fields/ETSALES_Address__c.field-meta.xml
<CustomField>
    <fullName>ETSALES_Address__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Address</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>ETSALES_Address__c.ETSALES_Account__c</field>
            <operation>equals</operation>
            <valueField>$Source.ETSALES_Account__c</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>ETSALES_Address__c</referenceTo>
    <relationshipLabel>Account Sites</relationshipLabel>
    <relationshipName>Operating_Unit_Address</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/ETSALES_Address__c/ETSALES_Address__c.object-meta.xml
<CustomObject>
    <label>Customer Address</label>
    <nameField>
        <displayFormat>Add-{0000}</displayFormat>
        <label>Address Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Addresses</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

unpackaged/main/default/objects/ETSALES_Address__c/fields/ETSALES_Account__c.field-meta.xml
<CustomField>
    <fullName>ETSALES_Account__c</fullName>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Addresses</relationshipLabel>
    <relationshipName>Addresses1</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

unpackaged/main/default/objects/ETSALES_Address__c/fields/ETSALES_Address1__c.field-meta.xml
<CustomField>
    <fullName>ETSALES_Address1__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Address1</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/ETSALES_Address__c/fields/ETSALES_Country__c.field-meta.xml
<CustomField>
    <fullName>ETSALES_Country__c</fullName>
    <label>Country</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>AD</fullName>
                <label>Andorra</label>
            </value>
            <value>
                <fullName>AE</fullName>
                <default>true</default>
                <label>United Arab Emirates</label>
            </value>
            <value>
                <fullName>AF</fullName>
                <label>Afghanistan</label>
            </value>
            <value>
                <fullName>AG</fullName>
                <label>Antigua and Barbuda</label>
            </value>
            <value>
                <fullName>AI</fullName>
                <label>Anguilla</label>
            </value>
            <value>
                <fullName>AL</fullName>
                <label>Albania</label>
            </value>
            <value>
                <fullName>AM</fullName>
                <label>Armenia</label>
            </value>
            <value>
                <fullName>AN</fullName>
                <label>Netherlands Antilles</label>
            </value>
            <value>
                <fullName>AO</fullName>
                <label>Angola</label>
            </value>
            <value>
                <fullName>AQ</fullName>
                <label>Antarctica</label>
            </value>
            <value>
                <fullName>AR</fullName>
                <label>Argentina</label>
            </value>
            <value>
                <fullName>AS</fullName>
                <label>American Samoa</label>
            </value>
            <value>
                <fullName>AT</fullName>
                <label>Austria</label>
            </value>
            <value>
                <fullName>AU</fullName>
                <label>Australia</label>
            </value>
            <value>
                <fullName>AW</fullName>
                <label>Aruba</label>
            </value>
            <value>
                <fullName>AZ</fullName>
                <label>Azerbaijan</label>
            </value>
            <value>
                <fullName>BA</fullName>
                <label>Bosnia and Herzegovina</label>
            </value>
            <value>
                <fullName>BB</fullName>
                <label>Barbados</label>
            </value>
            <value>
                <fullName>BD</fullName>
                <label>Bangladesh</label>
            </value>
            <value>
                <fullName>BE</fullName>
                <label>Belgium</label>
            </value>
            <value>
                <fullName>BF</fullName>
                <label>Burkina Faso</label>
            </value>
            <value>
                <fullName>BG</fullName>
                <label>Bulgaria</label>
            </value>
            <value>
                <fullName>BH</fullName>
                <label>Bahrain</label>
            </value>
            <value>
                <fullName>BI</fullName>
                <label>Burundi</label>
            </value>
            <value>
                <fullName>BJ</fullName>
                <label>Benin</label>
            </value>
            <value>
                <fullName>BM</fullName>
                <label>Bermuda</label>
            </value>
            <value>
                <fullName>BN</fullName>
                <label>Brunei Darussalam</label>
            </value>
            <value>
                <fullName>BO</fullName>
                <label>Bolivia</label>
            </value>
            <value>
                <fullName>BR</fullName>
                <label>Brazil</label>
            </value>
            <value>
                <fullName>BS</fullName>
                <label>Bahamas</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/ETSALES_Address__c/fields/ETSALES_Customer_Account_Id__c.field-meta.xml
<CustomField>
    <fullName>ETSALES_Customer_Account_Id__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <externalId>true</externalId>
    <label>Customer Oracle ID</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/classes/Account_SendToERP_Test.cls
@isTest
public class Account_SendToERP_Test {
   
   
    @isTest
    public static void Acc_SendToERPTest(){
        
        Test.setMock(HttpCalloutMock.class, new Oracle_Integration_Mock());
        
        Id RecordTypeId = Schema.SObjectType.Account.getRecordTypeInfosByName().get('Organization').getRecordTypeId();
        Account acc = new Account(Name='Test1');
        acc.RecordTypeId  = RecordTypeId;
        acc.ETSALES_Payment_Terms__c='15 Days';
        acc.ETSALES_Customer_Account_Id__c = '1234';
        insert acc; 
		
        Contact con = new Contact();
        con.AccountId = acc.Id;
        con.LastName ='TestCOn';
        con.Email ='test@gmail.com';
        insert con;
        ETSALES_Address__c add = new ETSALES_Address__c();
        add.ETSALES_Account__c = acc.Id;
        add.ETSALES_Address1__c = 'Test Address 1';
        add.ETSALES_Country__c = 'AE';
        insert add;
        
        ETSALES_Account_Sites__c site = new ETSALES_Account_Sites__c();
        site.ETSALES_Account__c = acc.Id;
        site.ETSALES_Address__c= add.Id;
        insert site;
        
        test.startTest();
        syncWithOracleBtnCtrl.callERPAccountIntegration(acc.Id);        
        system.enqueueJob(new Contact_SendToERP(acc.Id,'23242','23232'));        
        system.enqueueJob(new Address_SendToERPQueueableCtrl(acc.Id,'23242'));
        system.enqueueJob(new AccountSite_SendToERPQueueableCtrl(acc.Id,'23242','121344'));
        
        test.stopTest();
        
        
    }
    
    
    

}