unpackaged/main/default/objects/Account/fields/ETSALES_Customer_Type__c.field-meta.xml
<CustomField>
    <fullName>ETSALES_Customer_Type__c</fullName>
    <label>Customer Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Person</fullName>
                <label>Individual</label>
            </value>
            <value>
                <fullName>Organization</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Account/fields/ETSALES_Profile_Class__c.field-meta.xml
<CustomField>
    <fullName>ETSALES_Profile_Class__c</fullName>
    <label>Profile Class</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>ETSALES_Customer_Type__c</controllingField>
        <valueSetDefinition>
            <value>
                <fullName>Default</fullName>
            </value>
            <value>
                <fullName>Federal Government</fullName>
            </value>
            <value>
                <fullName>Government</fullName>
            </value>
            <value>
                <fullName>Individual</fullName>
            </value>
            <value>
                <fullName>Ministries</fullName>
            </value>
            <value>
                <fullName>Private</fullName>
            </value>
            <value>
                <fullName>Semi Government</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Account/fields/ETSALES_Status__c.field-meta.xml
<CustomField>
    <fullName>ETSALES_Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>A</fullName>
                <label>Active</label>
            </value>
            <value>
                <fullName>I</fullName>
                <label>Inactive</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/ET_Customer_Vehicle__c/ET_Customer_Vehicle__c.object-meta.xml
<CustomObject>
    <label>Customer Vehicle</label>
    <nameField>
        <displayFormat>CV-{000000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Customer Vehicles</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/ET_Customer_Vehicle__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Customer Vehicles</relationshipLabel>
    <relationshipName>Customer_Vehicles</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/ET_Customer_Vehicle__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <defaultValue>&quot;Active&quot;</defaultValue>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Active</fullName>
            </value>
            <value>
                <fullName>Frozen</fullName>
            </value>
            <value>
                <fullName>Inactive</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/ET_Service_Request__c/ET_Service_Request__c.object-meta.xml
<CustomObject>
    <label>Service Request</label>
    <nameField>
        <displayFormat>SR-{000000}</displayFormat>
        <label>Service Request Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Service Requests</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

unpackaged/main/default/objects/ET_Service_Request__c/fields/ET_Account__c.field-meta.xml
<CustomField>
    <fullName>ET_Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Service Requests (Account)</relationshipLabel>
    <relationshipName>Service_Requests</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/ET_Service_Request__c/fields/ETC_Service_Type__c.field-meta.xml
<CustomField>
    <fullName>ETC_Service_Type__c</fullName>
    <label>Service Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Rental Services</fullName>
            </value>
            <value>
                <fullName>Limo Services</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/ETI_Booking__c/ETI_Booking__c.object-meta.xml
<CustomObject>
    <label>Booking</label>
    <nameField>
        <displayFormat>B-{000000}</displayFormat>
        <label>Booking</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Bookings</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

unpackaged/main/default/objects/ETI_Booking__c/fields/Booking_Status__c.field-meta.xml
<CustomField>
    <fullName>Booking_Status__c</fullName>
    <label>Booking Status</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Draft</fullName>
            </value>
            <value>
                <fullName>Booked</fullName>
            </value>
            <value>
                <fullName>Inspection Completed</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
            <value>
                <fullName>Due for Retest</fullName>
            </value>
            <value>
                <fullName>Applied for Retest</fullName>
            </value>
            <value>
                <fullName>Confirmed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/ETI_Booking__c/fields/Customer_Vehicle__c.field-meta.xml
<CustomField>
    <fullName>Customer_Vehicle__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Customer Vehicle</label>
    <referenceTo>ET_Customer_Vehicle__c</referenceTo>
    <relationshipLabel>Bookings</relationshipLabel>
    <relationshipName>Bookings</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/ETI_Booking__c/fields/Service_Request__c.field-meta.xml
<CustomField>
    <fullName>Service_Request__c</fullName>
    <label>Service Request</label>
    <referenceTo>ET_Service_Request__c</referenceTo>
    <relationshipLabel>Bookings</relationshipLabel>
    <relationshipName>Bookings</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

unpackaged/main/default/objects/ETI_Booking__c/fields/User__c.field-meta.xml
<CustomField>
    <fullName>User__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Bookings</relationshipLabel>
    <relationshipName>Bookings</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/ETI_Inspection_Receipt__c/ETI_Inspection_Receipt__c.object-meta.xml
<CustomObject>
    <label>Aman Receipt</label>
    <nameField>
        <displayFormat>RCPT-{00000}</displayFormat>
        <label>ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Aman Receipts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/ETI_Inspection_Receipt__c/fields/AMAN_Receipt_No__c.field-meta.xml
<CustomField>
    <fullName>AMAN_Receipt_No__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>AMAN Receipt No</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/ETI_Inspection_Receipt__c/fields/ETI_Account__c.field-meta.xml
<CustomField>
    <fullName>ETI_Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipName>Receipts</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/ETI_Inspection_Receipt__c/fields/ETI_Amount__c.field-meta.xml
<CustomField>
    <fullName>ETI_Amount__c</fullName>
    <label>Amount</label>
    <precision>18</precision>
    <required>true</required>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

unpackaged/main/default/objects/ETI_Inspection_Receipt__c/fields/Service_Request__c.field-meta.xml
<CustomField>
    <fullName>Service_Request__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Service Request</label>
    <referenceTo>ET_Service_Request__c</referenceTo>
    <relationshipName>Receipts</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/classes/ET_InspectionReceiptCtrl_Test.cls
@isTest
public class ET_InspectionReceiptCtrl_Test {

    @TestSetup
    static void setup() {
        // Create test data as needed for your tests
        Account acc = new Account(Name = 'Test', ETSALES_Status__c = 'A',
                                  ETSALES_Customer_Type__c = 'individual', ETSALES_Profile_Class__c = 'Individual');
        insert acc;

        ET_Customer_Vehicle__c et = new ET_Customer_Vehicle__c(Status__c = 'Active', Account__c = acc.Id);
        insert et;

        ET_Service_Request__c esr = new ET_Service_Request__c(ET_Account__c = acc.Id, ETC_Service_Type__c= 'Rental Services');
        insert esr;

        ETI_Booking__c book = new ETI_Booking__c(User__c = acc.Id, 
                                                 Customer_Vehicle__c = et.Id,
                                                 Service_Request__c = esr.Id,
                                                 Booking_Status__c = 'Booked');
        insert book;

        ETI_Inspection_Receipt__c eti = new ETI_Inspection_Receipt__c();
        eti.ETI_Account__c = acc.Id; 
        eti.AMAN_Receipt_No__c = '12322';
        eti.ETI_Amount__c = 100.99;
        insert eti;
    }

    @isTest
    public static void testSearchInspectionReceipt() {
        String inspRecptFields = 'AMAN_Receipt_No__c';
        
          Account acc = new Account(Name = 'Test1', ETSALES_Status__c = 'A',
                                  ETSALES_Customer_Type__c = 'individual', ETSALES_Profile_Class__c = 'Individual');
        insert acc;
  ETI_Inspection_Receipt__c eti = new ETI_Inspection_Receipt__c();
        eti.ETI_Account__c = acc.Id; 
        eti.AMAN_Receipt_No__c = '12322';
        eti.ETI_Amount__c = 100.99;
        insert eti;
        // Create a mock response for the web service callout
        Test.setMock(HttpCalloutMock.class, new ET_InspectionReceiptMockCallout());
      
        Test.startTest();
       // String result = ET_InspectionReceiptCtrl.searchInspectionReceipt('12322', inspRecptFields);
       ET_InspectionReceiptCtrl.searchInspectionReceipt(eti.Name,'ETI_Account__c');   
        Test.stopTest();

        // Add assertions to verify the result or check database records
       // System.assertNotEquals(null, result);
    }
    
    
    

    @isTest
    public static void testSaveInspectionReceipt() {
        ETI_Inspection_Receipt__c eti = [SELECT Id FROM ETI_Inspection_Receipt__c LIMIT 1];

        if (eti != null) {
            String inspRecptFields = 'AMAN_Receipt_No__c';

            Test.startTest();
            String result = ET_InspectionReceiptCtrl.saveInspectionReceipt(eti, inspRecptFields);
            Test.stopTest();

            // Add assertions to verify the result or check database records
            System.assertNotEquals(null, result);
        } else {
            System.debug('No ETI_Inspection_Receipt__c record found for testing.');
        }
    }
    
    
    

    @isTest
    public static void testUploadFile() {
        Account testAccount = new Account(Name = 'Test Account');
        insert testAccount;
        String sampleBase64 = EncodingUtil.base64Encode(Blob.valueOf('Sample file content'));
        String contentLinkId = ET_InspectionReceiptCtrl.uploadFile(sampleBase64, 'SampleFile.txt', testAccount.Id);
        ET_InspectionReceiptCtrl.getRelatedFilesByRecordId(testAccount.Id);
        ContentDocumentLink cdl = [SELECT Id FROM ContentDocumentLink WHERE Id = :contentLinkId];
        delete testAccount;
    }
		
    
    
    
}