unpackaged/main/default/objects/Account/fields/ETSALES_Trade_License_Expiry_Date__c.field-meta.xml
<CustomField>
    <fullName>ETSALES_Trade_License_Expiry_Date__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Trade License Expiry Date</label>
    <type>Date</type>
</CustomField>

unpackaged/main/default/objects/Account/fields/ETSALES_Trade_License_Number__c.field-meta.xml
<CustomField>
    <fullName>ETSALES_Trade_License_Number__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Trade License Number(Decree No)</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Account/fields/ETST_Account_Type__c.field-meta.xml
<CustomField>
    <fullName>ETST_Account_Type__c</fullName>
    <label>Education Sector</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Government School</fullName>
            </value>
            <value>
                <fullName>Private School</fullName>
                <default>true</default>
                <label>Private School</label>
            </value>
            <value>
                <fullName>University</fullName>
            </value>
            <value>
                <fullName>Nursery</fullName>
            </value>
            <value>
                <fullName>Chartered School</fullName>
            </value>
            <value>
                <fullName>Ajyal School</fullName>
            </value>
            <value>
                <fullName>Institute</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Account/fields/ETST_Coordinator__c.field-meta.xml
<CustomField>
    <fullName>ETST_Coordinator__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Coordinator</label>
    <referenceTo>User</referenceTo>
    <relationshipName>ET_Schools</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Account/fields/ETST_SchoolRefID__c.field-meta.xml
<CustomField>
    <fullName>ETST_SchoolRefID__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>SchoolRefID</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Account/recordTypes/Business_School.recordType-meta.xml
<RecordType>
    <fullName>Business_School</fullName>
    <active>true</active>
    <label>Business (B2B) - School</label>
</RecordType>

unpackaged/main/default/classes/ETST_AccountTriggerHandler_Test.cls
@isTest
Private class ETST_AccountTriggerHandler_Test {
    Private Static TestMethod Void testAccountTrigger() {
        Id accSchoolRecordType = Schema.SObjectType.Account.getRecordTypeInfosByDeveloperName().get('Business_School').getRecordTypeId();
        Try{
            Profile p = [SELECT Id FROM Profile WHERE Name='School Coordinator']; 
            User coordinator = new User(Alias = 'cordu', Email='coordinatoruser@testorg.com', 
                                        EmailEncodingKey='UTF-8', LastName='Testing', LanguageLocaleKey='en_US', 
                                        LocaleSidKey='en_US', ProfileId = p.Id, 
                                        TimeZoneSidKey='America/Los_Angeles', UserName='coordinatoruser@testorg.com');
            insert coordinator;
            Account schoolAccount = new Account(Name='Test School',RecordTypeId=accSchoolRecordType,
                                                ETST_Account_Type__c='Private School',ETSALES_Trade_License_Number__c='11211',ETST_SchoolRefID__c='110011',
                                                ETSALES_Trade_License_Expiry_Date__c=system.today().addDays(365),ETST_Coordinator__c=coordinator.Id);
            insert schoolAccount;
            Account schoolAccount2 = new Account(Name='Test School',RecordTypeId=accSchoolRecordType,
                                                 ETST_Account_Type__c='Private School',ETSALES_Trade_License_Number__c='11211',ETST_SchoolRefID__c='110011',
                                                 ETSALES_Trade_License_Expiry_Date__c=system.today().addDays(365),ETST_Coordinator__c=coordinator.Id);
            insert schoolAccount2;
            schoolAccount2.Name = 'Test';
            update schoolAccount2;
        }Catch(Exception e){
            
        } 
    }
    @isTest
    public static void testCase1(){
        Id accSchoolRecordType = Schema.SObjectType.Account.getRecordTypeInfosByDeveloperName().get('Business_School').getRecordTypeId();
        Profile p = [SELECT Id FROM Profile WHERE Name='School Coordinator']; 
        User coordinator = new User(Alias = 'cordu', Email='coordinatoruser@testorg.com', 
                                    EmailEncodingKey='UTF-8', LastName='Testing', LanguageLocaleKey='en_US', 
                                    LocaleSidKey='en_US', ProfileId = p.Id, 
                                    TimeZoneSidKey='America/Los_Angeles', UserName='coordinatoruser@testorg.com');
        insert coordinator;
        Account schoolAccount2 = new Account(Name='Test School',RecordTypeId=accSchoolRecordType,
                                             ETST_Account_Type__c='Private School',ETSALES_Trade_License_Number__c='11211',ETST_SchoolRefID__c='110011',
                                             ETSALES_Trade_License_Expiry_Date__c=system.today().addDays(365),ETST_Coordinator__c=coordinator.Id);
        insert schoolAccount2;
        schoolAccount2.Name = 'Test';
        update schoolAccount2;
    }
}