unpackaged/main/default/objects/Account/fields/ETSALES_Email__c.field-meta.xml
<CustomField>
    <fullName>ETSALES_Email__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Email Id</label>
    <type>Email</type>
</CustomField>

unpackaged/main/default/objects/Account/recordTypes/Inspection.recordType-meta.xml
<RecordType>
    <fullName>Inspection</fullName>
    <active>true</active>
    <label>Inspection</label>
</RecordType>

unpackaged/main/default/objects/ET_Customer_Vehicle__c/ET_Customer_Vehicle__c.object-meta.xml
<CustomObject>
    <label>Customer Vehicle</label>
    <nameField>
        <displayFormat>CV-{000000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Customer Vehicles</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/ET_Customer_Vehicle__c/fields/Chassis_No__c.field-meta.xml
<CustomField>
    <fullName>Chassis_No__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Chassis No</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/ET_Customer_Vehicle__c/fields/Plate_No__c.field-meta.xml
<CustomField>
    <fullName>Plate_No__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Plate No</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/ET_Customer_Vehicle__c/fields/Registration_Type__c.field-meta.xml
<CustomField>
    <fullName>Registration_Type__c</fullName>
    <label>Registration Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Registered</fullName>
            </value>
            <value>
                <fullName>Un-Registered</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/ET_Customer_Vehicle__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <defaultValue>&quot;Active&quot;</defaultValue>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Active</fullName>
            </value>
            <value>
                <fullName>Frozen</fullName>
            </value>
            <value>
                <fullName>Inactive</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/ET_Service_Request__c/ET_Service_Request__c.object-meta.xml
<CustomObject>
    <label>Service Request</label>
    <nameField>
        <displayFormat>SR-{000000}</displayFormat>
        <label>Service Request Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Service Requests</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

unpackaged/main/default/objects/ET_Service_Request__c/fields/ET_Account__c.field-meta.xml
<CustomField>
    <fullName>ET_Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Service Requests (Account)</relationshipLabel>
    <relationshipName>Service_Requests</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/ET_Service_Request__c/fields/Payment_Status__c.field-meta.xml
<CustomField>
    <fullName>Payment_Status__c</fullName>
    <label>Payment Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Not Initiated</fullName>
            </value>
            <value>
                <fullName>Payment Pending</fullName>
            </value>
            <value>
                <fullName>Payment Success</fullName>
            </value>
            <value>
                <fullName>Refund Requested</fullName>
            </value>
            <value>
                <fullName>Await3D</fullName>
            </value>
            <value>
                <fullName>Captured</fullName>
            </value>
            <value>
                <fullName>Partially Paid</fullName>
            </value>
            <value>
                <fullName>Fully Paid</fullName>
            </value>
            <value>
                <fullName>Refund Cancelled</fullName>
            </value>
            <value>
                <fullName>Failed</fullName>
            </value>
            <value>
                <fullName>Reversed</fullName>
            </value>
            <value>
                <fullName>On Premise Requested</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/ETI_Booking__c/ETI_Booking__c.object-meta.xml
<CustomObject>
    <label>Booking</label>
    <nameField>
        <displayFormat>B-{000000}</displayFormat>
        <label>Booking</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Bookings</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

unpackaged/main/default/objects/ETI_Booking__c/fields/Chassis_No__c.field-meta.xml
<CustomField>
    <fullName>Chassis_No__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Chassis No</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/ETI_Booking__c/fields/Customer_Vehicle__c.field-meta.xml
<CustomField>
    <fullName>Customer_Vehicle__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Customer Vehicle</label>
    <referenceTo>ET_Customer_Vehicle__c</referenceTo>
    <relationshipLabel>Bookings</relationshipLabel>
    <relationshipName>Bookings</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/ETI_Booking__c/fields/Payment_Status__c.field-meta.xml
<CustomField>
    <fullName>Payment_Status__c</fullName>
    <formula>Text(Service_Request__r.Payment_Status__c )</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Payment Status</label>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/ETI_Booking__c/fields/Plate_No__c.field-meta.xml
<CustomField>
    <fullName>Plate_No__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Plate No</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/ETI_Booking__c/fields/Registration_Type__c.field-meta.xml
<CustomField>
    <fullName>Registration_Type__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Registration Type</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/ETI_Booking__c/fields/Service_Premises__c.field-meta.xml
<CustomField>
    <fullName>Service_Premises__c</fullName>
    <label>Service Premises</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Visit ET Premises</fullName>
            </value>
            <value>
                <fullName>Customer Premises</fullName>
            </value>
            <value>
                <fullName>Ocean/Island</fullName>
            </value>
            <value>
                <fullName>Home/Office Premise</fullName>
            </value>
            <value>
                <fullName>Customer Premises-B2B</fullName>
            </value>
            <value>
                <fullName>Home/Office Premise-B2B</fullName>
            </value>
            <value>
                <fullName>Ocean/Island-B2B</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/ETI_Booking__c/fields/Service_Request__c.field-meta.xml
<CustomField>
    <fullName>Service_Request__c</fullName>
    <label>Service Request</label>
    <referenceTo>ET_Service_Request__c</referenceTo>
    <relationshipLabel>Bookings</relationshipLabel>
    <relationshipName>Bookings</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

unpackaged/main/default/objects/ETI_Inspection_Receipt__c/ETI_Inspection_Receipt__c.object-meta.xml
<CustomObject>
    <label>Aman Receipt</label>
    <nameField>
        <displayFormat>RCPT-{00000}</displayFormat>
        <label>ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Aman Receipts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/ETI_Inspection_Receipt__c/fields/Chassis_No__c.field-meta.xml
<CustomField>
    <fullName>Chassis_No__c</fullName>
    <formula>Bookings__r.Chassis_No__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Chassis No</label>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/ETI_Inspection_Receipt__c/fields/Plate_No__c.field-meta.xml
<CustomField>
    <fullName>Plate_No__c</fullName>
    <formula>Bookings__r.Plate_No__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Plate No</label>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/ETI_Inspection_Receipt__c/fields/Service_Request__c.field-meta.xml
<CustomField>
    <fullName>Service_Request__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Service Request</label>
    <referenceTo>ET_Service_Request__c</referenceTo>
    <relationshipName>Receipts</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/ETI_Service_Line_Item__c/ETI_Service_Line_Item__c.object-meta.xml
<CustomObject>
    <label>Booking Line Item</label>
    <nameField>
        <displayFormat>SVC-{00000}</displayFormat>
        <label>Service Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Booking Line Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

unpackaged/main/default/objects/ETI_Service_Line_Item__c/fields/Booking__c.field-meta.xml
<CustomField>
    <fullName>Booking__c</fullName>
    <label>Booking</label>
    <referenceTo>ETI_Booking__c</referenceTo>
    <relationshipLabel>Booking Line Items</relationshipLabel>
    <relationshipName>Services</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

unpackaged/main/default/objects/ETI_Service_Line_Item__c/fields/Chassis_No__c.field-meta.xml
<CustomField>
    <fullName>Chassis_No__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Chassis No</label>
    <length>150</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/ETI_Service_Line_Item__c/fields/Service__c.field-meta.xml
<CustomField>
    <fullName>Service__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Service</label>
    <referenceTo>ETI_Vehicle_Service__c</referenceTo>
    <relationshipLabel>Booking Line Items</relationshipLabel>
    <relationshipName>Services</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/ETI_Service_Line_Item__c/fields/Service_Type__c.field-meta.xml
<CustomField>
    <fullName>Service_Type__c</fullName>
    <label>Service Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Police Inspection</fullName>
            </value>
            <value>
                <fullName>Certificate</fullName>
            </value>
            <value>
                <fullName>ADFCA</fullName>
            </value>
            <value>
                <fullName>SPEA Inspection</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/ETI_Service_Line_Item__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <defaultValue>&quot;Active&quot;</defaultValue>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Active</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/ETI_Vehicle_Service__c/ETI_Vehicle_Service__c.object-meta.xml
<CustomObject>
    <label>Vehicle Service</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Service  Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Vehicle Services</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/ETI_Vehicle_Service__c/fields/Service_Code__c.field-meta.xml
<CustomField>
    <fullName>Service_Code__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Service Code</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/ETI_Vehicle_Service__c/fields/Service_Premises__c.field-meta.xml
<CustomField>
    <fullName>Service_Premises__c</fullName>
    <label>Service Premises</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Visit ET Premises</fullName>
            </value>
            <value>
                <fullName>Home/Office Premise</fullName>
            </value>
            <value>
                <fullName>Ocean/Island</fullName>
            </value>
            <value>
                <fullName>Customer Premises</fullName>
            </value>
            <value>
                <fullName>Customer Premises-B2B</fullName>
            </value>
            <value>
                <fullName>Home/Office Premise-B2B</fullName>
            </value>
            <value>
                <fullName>Ocean/Island-B2B</fullName>
            </value>
            <value>
                <fullName>WalkIn</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/ETI_Vehicle_Service__c/fields/Service_Type__c.field-meta.xml
<CustomField>
    <fullName>Service_Type__c</fullName>
    <label>Service Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Police Inspection</fullName>
            </value>
            <value>
                <fullName>Certificate</fullName>
            </value>
            <value>
                <fullName>ADFCA</fullName>
            </value>
            <value>
                <fullName>SPEA Inspection</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/ETI_Vehicle_Service__c/recordTypes/Certificate.recordType-meta.xml
<RecordType>
    <fullName>Certificate</fullName>
    <active>true</active>
    <label>Certificate</label>
</RecordType>

unpackaged/main/default/objects/Service_Type__c/Service_Type__c.object-meta.xml
<CustomObject>
    <label>Service Type</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Service Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Service Types</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Service_Type__c/fields/Service_Code__c.field-meta.xml
<CustomField>
    <fullName>Service_Code__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Service Code</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/classes/ETI_BookingInspectionHandlerTest.cls
@IsTest
public class ETI_BookingInspectionHandlerTest {
    @testSetup
    private static  void testmethodInspection(){
        // create test user
        Profile p = [SELECT Id FROM Profile WHERE Name='Standard User']; 
        User u = new User(Alias = 'standt', Email='standarduser@sm.com', 
                EmailEncodingKey='UTF-8', isActive = true, LastName='Testing', LanguageLocaleKey='en_US', 
                LocaleSidKey='en_US', ProfileId = p.Id, 
                TimeZoneSidKey='America/Los_Angeles', UserName='standarduser@sm.com');
        insert u;
        
        
        Id recordTypeId = Schema.SObjectType.Account.getRecordTypeInfosByName().get('Person (B2C)').getRecordTypeId();
        Account acc = new Account();
        acc.FirstName = 'test';
        acc.LastName = 'test';
        acc.PersonEmail = 'test@gmail.com';
        acc.RecordTypeId = recordTypeId;
        acc.ETSALES_Email__c = 'testAcc@gmail.com';
        insert acc;
        
        Contact con = new Contact();
        con.LastName = 'Noor';
        con.Email = Label.ETI_TargetObject_Email;
        insert con;
        
        ET_Customer_Vehicle__c etcv1 = new ET_Customer_Vehicle__c();
        etcv1.OwnerId = userinfo.getUserId();
        etcv1.Chassis_No__c = 'D032B5GC000790';
        etcv1.Plate_No__c = '53215';
        etcv1.status__c = 'Active';
        etcv1.Registration_Type__c ='Registered';
        insert etcv1;
        
        Id recordTypeId2 = Schema.SObjectType.ET_Service_Request__c.getRecordTypeInfosByName().get('Vehicle Inspection').getRecordTypeId();
        ET_Service_Request__c etsr = new ET_Service_Request__c();
        etsr.Payment_Status__c = 'Not Initiated';
        etsr.RecordTypeId = recordTypeId2;
        etsr.ET_Account__c = acc.id;
        insert etsr;
       
        Attachment att = new Attachment();
        att.ParentId = etsr.Id;
        att.Name = 'Test';
        att.Body = Blob.valueOf('Test');
        insert att;
        ETI_Vehicle_Service__c vehService = new ETI_Vehicle_Service__c();
        vehService.Service_Type__c='Certificate';
        vehService.Service_Premises__c='Visit ET Premises';
        vehService.Name = 'Test';
        vehService.Service_Code__c = '01';
        insert vehService;
        EmailTemplate e = new EmailTemplate ();
        System.runAs(u){
            String Sbjct='{!ETI_Booking__c.Vehicle_Number__c}';
            string Bodyvar= '{!ETI_Booking__c.Vehicle_Number__c} {!ETI_Booking__c.Test_Result__c} {!ETI_Booking__c.Vehicle_Number__c}';
            e = new EmailTemplate (developerName = 'Test_Result_Notification', Subject=Sbjct,HtmlValue=Bodyvar,Body = Bodyvar,FolderId = u.Id, TemplateType= 'text', Name = 'test'); 
            insert e;
        }
        ETI_Booking__c etiBooking = new ETI_Booking__c();
        etiBooking.Customer_Vehicle__c = etcv1.id;
        etiBooking.Booking_Status__c = 'Confirm';
        etiBooking.Service_Request__c = etsr.id;
        etiBooking.Selected_Services__c = 'Test';
        etiBooking.Chassis_No__c = 'D032B5GC000790';
        etiBooking.Test_Result__c = 'Pass';
        etiBooking.User__c = acc.id;
        etiBooking.Is_booking_Confirmed__c = true;
        etiBooking.Service_Type__c ='Police Inspection';
        etiBooking.Booking_Date__c= date.today()-2;
   
        Test.startTest();
        insert etiBooking;
        ETI_Service_Line_Item__c etline = new ETI_Service_Line_Item__c();
        etline.Service_Name__c = 'SLA';
        etline.Test_Result__c = 'Pass';
        etline.Booking__c = etiBooking.Id;
        etline.Service__c = vehService.Id;
        etline.Description__c= 'test link result';
        insert etline;
        etiBooking.Booking_Status__c = 'Booked';
        etiBooking.Test_Result__c = 'Failed';
        //etiBooking.Is_booking_Confirmed__c = true;
        update etiBooking;
        
        //cancelReceipt
        ETI_Inspection_Receipt__c receipt =new ETI_Inspection_Receipt__c();
        receipt.ET_Status__c = 'Active';
        receipt.Bookings__c= etiBooking.Id;
        receipt.ETI_Amount__c=100;
        insert receipt;
        etiBooking.Booking_Status__c = 'Cancelled';
        update etiBooking;
        Test.stopTest();
        
    }
    @isTest
    public static void testCase2(){
        List<ETI_Booking__c> bookingList = [SELECT id , Is_booking_Confirmed__c, Test_Result__c, (Select Id, Name,Service_Name__c,Test_Result__c From Services__r) FROM ETI_Booking__c];
       
        ETI_Service_Line_Item__c etline = new ETI_Service_Line_Item__c();
        etline.Service_Name__c = 'SLA';
        etline.Test_Result__c = 'Pass';
        etline.Booking__c = bookingList[0].Id;
        etline.Service__c = [select id from ETI_Vehicle_Service__c][0].Id;
        etline.Test_Result__c = 'Failed';
        insert etline;
        Map<Id, ETI_Booking__c> newMap = new   Map<Id, ETI_Booking__c>();
        ETI_Booking__c etiBooking = bookingList[0].clone();
        etiBooking.Is_booking_Confirmed__c = false;
        bookingList[0].Is_booking_Confirmed__c = true;
        newMap.put(bookingList[0].Id,bookingList[0]);
       
        Map<Id, ETI_Booking__c> oldMap = new   Map<Id, ETI_Booking__c>();
        oldMap.put(bookingList[0].Id,etiBooking);
       
        
        //bookingList[0].Is_booking_Confirmed__c = true;
        Test.startTest();
        //ETI_BookingInspectionHandler.updateEncrypted(newMap);
        ETI_BookingInspectionHandler.SendBookingConfirmationforExternal(newMap, oldMap);
        ETI_BookingInspectionHandler.SendTestResultCustomer(newMap, oldMap);
        // update bookingList[0];
        ETI_BookingInspectionHandler.utilityMethod();
        Test.stopTest();
    }
    
    
    
}