unpackaged/main/default/objects/Account/fields/ETSALES_TaxRegistrationNo__c.field-meta.xml
<CustomField>
    <fullName>ETSALES_TaxRegistrationNo__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Tax Registration No</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Vehicle_Master__c/Vehicle_Master__c.object-meta.xml
<CustomObject>
    <description>Emirates Transport Oracle Vehicle Master</description>
    <label>ET Vehicle Master</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Vehicle No.</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>ET Vehicle Masters</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Vehicle_Master__c/fields/Internal_No__c.field-meta.xml
<CustomField>
    <fullName>Internal_No__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <externalId>true</externalId>
    <label>Internal No</label>
    <length>100</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/VRTS_Master__c/VRTS_Master__c.object-meta.xml
<CustomObject>
    <label>VRTS Master</label>
    <nameField>
        <displayFormat>VRTSM-{00000}</displayFormat>
        <label>VRTS Master Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>VRTS Masters</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/VRTS_Master__c/fields/Category_En__c.field-meta.xml
<CustomField>
    <fullName>Category_En__c</fullName>
    <label>Category En</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Internal Siren (Speaker)</fullName>
            </value>
            <value>
                <fullName>Child Detection Sensor</fullName>
            </value>
            <value>
                <fullName>Child Check Button</fullName>
            </value>
            <value>
                <fullName>Panic Button</fullName>
            </value>
            <value>
                <fullName>Temp. - Humidity</fullName>
            </value>
            <value>
                <fullName>LCD Monitor</fullName>
            </value>
            <value>
                <fullName>4 Pcs External IP Camera</fullName>
            </value>
            <value>
                <fullName>3 Pcs Internal IP Camera</fullName>
            </value>
            <value>
                <fullName>MDVR With HDD 2TB</fullName>
            </value>
            <value>
                <fullName>Bus Speed Limiter</fullName>
            </value>
            <value>
                <fullName>Stop Arm</fullName>
            </value>
            <value>
                <fullName>Electronic Destination Board</fullName>
            </value>
            <value>
                <fullName>Fire Extinguisher 6KG×2</fullName>
            </value>
            <value>
                <fullName>Emergency exit hammer</fullName>
            </value>
            <value>
                <fullName>First Aid Bag</fullName>
            </value>
            <value>
                <fullName>Automatic Fire Suppression System</fullName>
            </value>
            <value>
                <fullName>tool Cutting seat belts In case of emergency</fullName>
            </value>
            <value>
                <fullName>Automatic Fire Suppression (SUNWIN)</fullName>
            </value>
            <value>
                <fullName>Automatic Fire Suppression (Except SUNWIN)</fullName>
            </value>
            <value>
                <fullName>Cable Connections</fullName>
            </value>
            <value>
                <fullName>Second Device</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/VRTS_Master__c/fields/Sequence__c.field-meta.xml
<CustomField>
    <fullName>Sequence__c</fullName>
    <label>Sequence</label>
    <precision>18</precision>
    <scale>3</scale>
    <type>Number</type>
    <unique>true</unique>
</CustomField>

unpackaged/main/default/objects/VRTS_Master__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Comment</fullName>
            </value>
            <value>
                <fullName>Picklist</fullName>
            </value>
            <value>
                <fullName>Sub Picklist with Attachment</fullName>
            </value>
            <value>
                <fullName>Result</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/VRTS_Master__c/fields/Version__c.field-meta.xml
<CustomField>
    <fullName>Version__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Version</label>
    <length>225</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/VRTS_Observation__c/VRTS_Observation__c.object-meta.xml
<CustomObject>
    <label>VRTS Observation</label>
    <nameField>
        <displayFormat>VRTSO-{000000}</displayFormat>
        <label>VRTS Observation Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>VRTS_Observations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/VRTS_Observation__c/fields/ET_Bus_Internal_No__c.field-meta.xml
<CustomField>
    <fullName>ET_Bus_Internal_No__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Bus Internal No</label>
    <referenceTo>Vehicle_Master__c</referenceTo>
    <relationshipLabel>VRTS_Observations</relationshipLabel>
    <relationshipName>VRTS_Observations</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/VRTS_Response__c/VRTS_Response__c.object-meta.xml
<CustomObject>
    <label>VRTS Response</label>
    <nameField>
        <displayFormat>VRTSR-{00000}</displayFormat>
        <label>VRTS Response</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>VRTS Responses</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

unpackaged/main/default/objects/VRTS_Response__c/fields/Category_En__c.field-meta.xml
<CustomField>
    <fullName>Category_En__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Category En</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/VRTS_Response__c/fields/Question_En__c.field-meta.xml
<CustomField>
    <fullName>Question_En__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Question En</label>
    <length>5000</length>
    <type>LongTextArea</type>
</CustomField>

unpackaged/main/default/objects/VRTS_Response__c/fields/Sequence__c.field-meta.xml
<CustomField>
    <fullName>Sequence__c</fullName>
    <label>Sequence</label>
    <precision>18</precision>
    <scale>3</scale>
    <type>Number</type>
</CustomField>

unpackaged/main/default/objects/VRTS_Response__c/fields/VRTS_Observation__c.field-meta.xml
<CustomField>
    <fullName>VRTS_Observation__c</fullName>
    <label>VRTS Observation</label>
    <referenceTo>VRTS_Observation__c</referenceTo>
    <relationshipLabel>VRTS Responses</relationshipLabel>
    <relationshipName>VRTS_Responses</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

unpackaged/main/default/objects/VRTS_Sub_Response__c/VRTS_Sub_Response__c.object-meta.xml
<CustomObject>
    <label>VRTS Sub Response</label>
    <nameField>
        <displayFormat>VRTSS-{00000}</displayFormat>
        <label>VRTS Sub Response Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>VRTS Sub Responses</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

unpackaged/main/default/objects/VRTS_Sub_Response__c/fields/VRTS_Response__c.field-meta.xml
<CustomField>
    <fullName>VRTS_Response__c</fullName>
    <label>VRTS Response</label>
    <referenceTo>VRTS_Response__c</referenceTo>
    <relationshipLabel>VRTS Sub Responses</relationshipLabel>
    <relationshipName>VRTS_Sub_Responses</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

unpackaged/main/default/classes/ET_VRTSTEST.cls
/************************************************************************************************************************
 * Name               : ET_VRTSTEST                                                                                     *
 * Description        : Apex Test Class for ET_VRTS                                                                     *
 * Created Date       : 07/Feb/2024                                                                                     *
 * Created By         : Taj Shaik(SMAARTT)                                                                              *
 * -----------------------------------------------------------------------------------------------                      *
 * VERSION   AUTHOR      DATE                COMMENTS                                                                   *
 * 1.0       Taj Shaik   07/Feb/2024         Initial Draft.                                                             *
 ***********************************************************************************************************************/
@isTest
public class ET_VRTSTEST {
    public static testMethod void ET_VRTSTestMethod(){
        
        VRTS_Master__c TestVRTSMaster = new VRTS_Master__c(Question_En__c='Invisible Cable Connections',Category_En__c='Cable Connections',Version__c='1',Sequence__c=19.002,Type__c='Picklist');
        insert TestVRTSMaster;
        
        Vehicle_Master__c TestVehicleMaster = new Vehicle_Master__c(Name ='B0015456', Internal_No__c='B0015456');
        insert TestVehicleMaster;
        
        VRTS_Observation__c TestObservation = new VRTS_Observation__c(Name__c='Test Class Obervation',ET_Bus_Internal_No__c=TestVehicleMaster.Id);
        insert TestObservation;
        
        VRTS_Response__c TestVRTSResponse = new VRTS_Response__c(VRTS_Observation__c=TestObservation.Id,Category_En__c='Second Device',Question_En__c='Device Name');
        insert TestVRTSResponse;
        
        VRTS_Sub_Response__c TestVRTSSubResponse = new VRTS_Sub_Response__c(VRTS_Response__c=TestVRTSResponse.Id);
        insert TestVRTSSubResponse;
        
        Account a = New Account(Name = 'Test',ETSALES_TaxRegistrationNo__c='123456789123456');
        insert a;
        a = [Select OwnerID, Owner.ID From Account where ID = :a.id];
        
        blob file =Blob.valueOf('sampletext');
        Attachment objAttachment=new Attachment(); 
        objAttachment.Body= file;
        objAttachment.Name = 'test Attachment';
        objAttachment.ParentId = TestObservation.Id;
        objAttachment.OwnerId = a.Owner.ID;
        insert objAttachment;
        //Insert ContentVersion
        ContentVersion cVersion = new ContentVersion();
        cVersion.ContentLocation = 'S'; 
        cVersion.PathOnClient = objAttachment.Name;//File name with extention
        cVersion.Origin = 'H';//C-Content Origin. H-Chatter Origin.
        cVersion.OwnerId = objAttachment.OwnerId;//Owner of the file
        cVersion.Title = objAttachment.Name;//Name of the file
        cVersion.VersionData = objAttachment.Body;//File content
        Insert cVersion;
        
        sectionWrapper testSectionWrapper = new sectionWrapper();
        testSectionWrapper.secOptions = new List<optionWrapper>();
        optionWrapper testOptionWrapper = new optionWrapper();
        testOptionWrapper.recId = TestVRTSResponse.Id; // Provide an existing record Id
        testOptionWrapper.response = 'Test Response';
        testSectionWrapper.secOptions.add(testOptionWrapper);
        String sectionWrapperListStr = JSON.serialize(new List<sectionWrapper>{ testSectionWrapper });
        
        // Call the method
        test.startTest();
        ET_VRTS.getVehicleMaster_records(TestVehicleMaster.Id);
        ET_VRTS.saveObservations(TestObservation.Id, sectionWrapperListStr);
        ET_VRTS.getAllVRTSrecords(TestObservation.Id,new List<String>{'a','b','c'},new List<String>{'a','b','c'});
        ET_VRTS.createSubResp(TestVRTSResponse.Id, new List<String>{'a','b','c'});
        ET_VRTS.deleteSubResp(TestVRTSSubResponse.Id);
        ET_VRTS.getOptionList(new List<String>{'a','b','c'});
        ET_VRTS.getOption('a');
        ET_VRTS.uploadFile(file.toString(),'testAttachment',TestObservation.Id);
        ET_VRTS.createContentVersion('testAttachment','jpg');
        ET_VRTS.createContentLink(cVersion.Id,TestObservation.Id);
        ET_VRTS.getRelatedFilesByRecordId(TestObservation.Id);
        ET_VRTS.deleteFile(TestObservation.Id);
        
        test.stopTest();   
    }  
    
    public static optionsWrapper getOption(String option){
        optionsWrapper optionsWrp = New optionsWrapper();
        optionsWrp.label = option;
        optionsWrp.value = option;
        return optionsWrp;
    }
    
    Public class sectionWrapper{
        Public langWrapper name;
        Public Boolean isSkipped;
        Public List<optionWrapper> secOptions;
        Public sectionWrapper(){
            name = New langWrapper();
            isSkipped = false;
            secOptions = New List<optionWrapper>();
        }
    }
    
    Public class optionWrapper{
        Public langWrapper question;
        Public Boolean isPicklist;
        Public Boolean isSubPicklistWithAtt;
        Public Boolean isComment;
        Public Boolean isResult;
        Public Decimal sequence;
        Public List<optionsWrapper> options;
        Public String type;
        Public String version;
        Public String response;
        Public Id recId;
        Public List<subResponseWrapper> subRespWrps;
        Public optionWrapper(){
            question = New langWrapper();
            isSubPicklistWithAtt = false;
            isPicklist = false;
            isComment = false;
            isResult = false;
            //subRespWrps = New List<subResponseWrapper>();
        }
    }
    
    Public class langWrapper{
        Public String En;
        Public String Ar;
    }
    
    Public class optionsWrapper{
        Public String label;
        Public String value;
    }
    
    Public class subResponseWrapper{
        Public Id recId;
        Public List<optionsWrapper> options;
        Public String answer;
    }
}