unpackaged/main/default/objects/Account/fields/ETSALES_Customer_Account_Id__c.field-meta.xml
<CustomField>
    <fullName>ETSALES_Customer_Account_Id__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <externalId>true</externalId>
    <label>Customer Oracle ID</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Disposition_Code__c/Disposition_Code__c.object-meta.xml
<CustomObject>
    <label>Disposition Code</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Disposition Code Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Disposition Codes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Disposition_Code__c/fields/Remark__c.field-meta.xml
<CustomField>
    <fullName>Remark__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Remark</label>
    <length>225</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/ET_Oracle_REST_Endpoints__mdt/ET_Oracle_REST_Endpoints__mdt.object-meta.xml
<CustomObject>
    <description>This meta data created to store all the REST endpoint and authentication details</description>
    <label>ET_Oracle_REST_Endpoint</label>
    <pluralLabel>ET_Oracle_REST_Endpoints</pluralLabel>
</CustomObject>

unpackaged/main/default/objects/ET_Oracle_REST_Endpoints__mdt/fields/Dev_Endpoint__c.field-meta.xml
<CustomField>
    <fullName>Dev_Endpoint__c</fullName>
    <label>Dev Endpoint</label>
    <type>Url</type>
</CustomField>

unpackaged/main/default/objects/ET_Oracle_REST_Endpoints__mdt/fields/LiveEndpoint_c__c.field-meta.xml
<CustomField>
    <fullName>LiveEndpoint_c__c</fullName>
    <label>Live Endpoint</label>
    <type>Url</type>
</CustomField>

unpackaged/main/default/classes/CreateCollectorLogHandler.cls
/*********************************************************************************
Class       : CreateCollectorLogHandler
Author      : Srihari Koyila
Test Class  : CreateCollectorLogHandlerTest
Description : Get the customer amount details of collector log along this disposition codes.
--------------------------------------------------------------------
History     : 
Sr.No.  version_DevInitials     Date                Details
1        V.1                  05/01/2023           Initial Version - verified by Janardhan
*********************************************************************************/
public class CreateCollectorLogHandler {
    @auraEnabled
    public static list<Disposition_Code__c> getDispositionInfo(){
        return [select id,name,Remark__c from Disposition_Code__c];
    }
    @auraEnabled
    public static customerAmountWrapper getCustomerAmountDetails(Id accID){
        try{
            
            Account acc = [Select id,AccountNumber,ETSALES_Customer_Account_Id__c  from Account where Id =:accID];   
            if(acc.AccountNumber!=Null){
                
                ET_Oracle_REST_Endpoints__mdt connection = ET_REST_Authorize_Helper.getSOAPEndpointFromMetadata('GetCustomerAgingTransaction');
                Blob beforeblob = Blob.valueOf(connection.Username__c+':'+connection.Password__c);
                string paramvalue = EncodingUtil.base64Encode(beforeblob);
                
                Http httpProtocol = new Http();
                HttpRequest request = new HttpRequest();
                HttpResponse response = new HttpResponse();
                request.setHeader('Accept', 'application/json');
                request.setHeader('Authorization','Basic '+paramvalue); 
                request.setMethod('GET');
                
                if(ET_REST_Authorize_Helper.runningInASandbox()){
                    request.setEndpoint(connection.Dev_Endpoint__c+acc.AccountNumber);
                    system.debug(connection.Dev_Endpoint__c+acc.AccountNumber);
                }else{
                    request.setEndpoint(connection.LiveEndpoint_c__c+acc.AccountNumber);
                }  
                system.debug('request'+request);
                request.setTimeout(90000);
                request.setHeader('Content-Type', 'application/json');
                response = httpProtocol.send(request);
                
                Map<String, Object> responseResult =new Map<String, Object>();
                Map<String, Object> result = (Map<String, Object>)JSON.deserializeUntyped(response.getBody());
                
                customerAmountWrapper cswp =new customerAmountWrapper();
                if(result!=Null){
                    cswp.totalAmountOriginal=string.valueOf(result.get('totalAmountOriginal'));
                    cswp.totalReceivable=string.valueOf(result.get('totalReceivable'));
                    cswp.errorMessage=string.valueOf(result.get('message'));
                }
                return cswp;
            }
            return null;
        }
        catch(Exception e){               //throw all other exception message            
            throw new AuraHandledException(e.getMessage());}
    }
    
    Public class customerAmountWrapper{
        @AuraEnabled
        Public string totalAmountOriginal{get;set;}
        @AuraEnabled
        Public string totalReceivable{get;set;}  
        @AuraEnabled
        Public string errorMessage{get;set;}  
    }
}