unpackaged/main/default/objects/Account/fields/ETSALES_TaxRegistrationNo__c.field-meta.xml
<CustomField>
    <fullName>ETSALES_TaxRegistrationNo__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Tax Registration No</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Account/fields/GL_Zone__c.field-meta.xml
<CustomField>
    <fullName>GL_Zone__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>GL Zone</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/ETSALES_Location__c/ETSALES_Location__c.object-meta.xml
<CustomObject>
    <label>GL Location</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>GL Location</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>GL Locations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/ETSALES_Location__c/fields/GL_Zone__c.field-meta.xml
<CustomField>
    <fullName>GL_Zone__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>GL Zone</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/ETSALES_Location__c/fields/Location_Code__c.field-meta.xml
<CustomField>
    <fullName>Location_Code__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Location Code</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/ETVIN_Insurance_Policy_Numbers__c/ETVIN_Insurance_Policy_Numbers__c.object-meta.xml
<CustomObject>
    <label>Insurance Policy Number</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Policy Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Insurance Policy Number</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/ETVIN_Insurance_Policy_Numbers__c/fields/Activity_Center__c.field-meta.xml
<CustomField>
    <fullName>Activity_Center__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Activity Center</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/ETVIN_Vehicle_Insurance__c/ETVIN_Vehicle_Insurance__c.object-meta.xml
<CustomObject>
    <description>Vehicle Insurance</description>
    <label>Vehicle Insurance Policy</label>
    <nameField>
        <displayFormat>VI-{0000}</displayFormat>
        <label>Insurance Ref Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Vehicle Insurance Policies</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/ETVIN_Vehicle_Insurance__c/fields/Amount__c.field-meta.xml
<CustomField>
    <fullName>Amount__c</fullName>
    <label>Amount</label>
    <precision>18</precision>
    <scale>4</scale>
    <type>Number</type>
</CustomField>

unpackaged/main/default/objects/ETVIN_Vehicle_Insurance__c/fields/ETVIN_Insurance_Company__c.field-meta.xml
<CustomField>
    <fullName>ETVIN_Insurance_Company__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Insurance Company</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Vehicle Insurance Policies</relationshipLabel>
    <relationshipName>Vehicle_Insurances</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/ETVIN_Vehicle_Insurance__c/fields/ETVIN_Insurance_Status__c.field-meta.xml
<CustomField>
    <fullName>ETVIN_Insurance_Status__c</fullName>
    <label>Insurance Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Active</fullName>
            </value>
            <value>
                <fullName>Inactive</fullName>
                <default>true</default>
                <label>Inactive</label>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
            <value>
                <fullName>Duplicate</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/ETVIN_Vehicle_Insurance__c/fields/ETVIN_Request_Status__c.field-meta.xml
<CustomField>
    <fullName>ETVIN_Request_Status__c</fullName>
    <label>Request Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>New</fullName>
                <default>true</default>
                <label>New</label>
            </value>
            <value>
                <fullName>Insurance Approved</fullName>
            </value>
            <value>
                <fullName>Insurance Rejected</fullName>
            </value>
            <value>
                <fullName>Insurance Pending</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/ETVIN_Vehicle_Insurance__c/fields/Vehicle__c.field-meta.xml
<CustomField>
    <fullName>Vehicle__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Vehicle</label>
    <referenceTo>Vehicle_Master__c</referenceTo>
    <relationshipLabel>Vehicle Insurance Policies</relationshipLabel>
    <relationshipName>Vehicle_Insurance_Policies</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/GL_Zone__c/GL_Zone__c.object-meta.xml
<CustomObject>
    <label>GL Zone</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>GL Zones</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/User/fields/ETSALES_Employee_Zone__c.field-meta.xml
<CustomField>
    <fullName>ETSALES_Employee_Zone__c</fullName>
    <label>Employee Zone</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Zone A</fullName>
            </value>
            <value>
                <fullName>Zone B</fullName>
            </value>
            <value>
                <fullName>Zone C</fullName>
            </value>
            <value>
                <fullName>Head Office</fullName>
            </value>
            <value>
                <fullName>Technical Services</fullName>
            </value>
            <value>
                <fullName>HO</fullName>
            </value>
            <value>
                <fullName>KAM</fullName>
                <isActive>false</isActive>
                <label>KAM</label>
            </value>
            <value>
                <fullName>MRO</fullName>
                <isActive>false</isActive>
                <label>MRO</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/User/fields/ETSALES_Location__c.field-meta.xml
<CustomField>
    <fullName>ETSALES_Location__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>GL Location</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Veh_Default_Insurance_partner__c/Veh_Default_Insurance_partner__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <label>Vehicle Insurance Default Parnter</label>
</CustomObject>

unpackaged/main/default/objects/Veh_Default_Insurance_partner__c/fields/Account_ID__c.field-meta.xml
<CustomField>
    <fullName>Account_ID__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Account ID</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Vehicle__c/Vehicle__c.object-meta.xml
<CustomObject>
    <label>Pricing Vehicle Request</label>
    <nameField>
        <displayFormat>VN-{0000}</displayFormat>
        <label>Vehicle Request Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Vehicle Requests</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Vehicle_Master__c/Vehicle_Master__c.object-meta.xml
<CustomObject>
    <description>Emirates Transport Oracle Vehicle Master</description>
    <label>ET Vehicle Master</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Vehicle No.</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>ET Vehicle Masters</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Vehicle_Master__c/fields/Account_Id__c.field-meta.xml
<CustomField>
    <fullName>Account_Id__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account Id</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>ET Vehicle Masters</relationshipLabel>
    <relationshipName>ET_Vehicle_Masters</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Vehicle_Master__c/fields/Activity_Center__c.field-meta.xml
<CustomField>
    <fullName>Activity_Center__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Activity Center</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Vehicle_Master__c/fields/Activity_Center_code__c.field-meta.xml
<CustomField>
    <fullName>Activity_Center_code__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Activity Center code</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Vehicle_Master__c/fields/Department_Code__c.field-meta.xml
<CustomField>
    <fullName>Department_Code__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Department Code</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Vehicle_Master__c/fields/Internal_No__c.field-meta.xml
<CustomField>
    <fullName>Internal_No__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <externalId>true</externalId>
    <label>Internal No</label>
    <length>100</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Vehicle_Master__c/fields/Location_Code__c.field-meta.xml
<CustomField>
    <fullName>Location_Code__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Location Code</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Vehicle_Master__c/fields/Plate_Type__c.field-meta.xml
<CustomField>
    <fullName>Plate_Type__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Plate Type</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Vehicle_Master__c/fields/TC_Number__c.field-meta.xml
<CustomField>
    <fullName>TC_Number__c</fullName>
    <label>TC Number</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

unpackaged/main/default/classes/ETVIN_NewPolicyCreationTrgHandlerTest.cls
@isTest
public class ETVIN_NewPolicyCreationTrgHandlerTest {
    @isTest static void testCreateNewVehPolicy() {
        // Prepare test data
        List<Vehicle_Master__c> vehicles = new List<Vehicle_Master__c>();
        Vehicle_Master__c vm1 = new Vehicle_Master__c(TC_Number__c = 001, Amount__c = 10000, Internal_No__c='90');
        insert vm1; // Assuming DML is needed here to provide an ID
        
        vehicles.add(vm1);
        
        // Test new policy creation
        Test.startTest();
        ETVIN_NewPolicyCreationTrgHandler.createNewVehPolicy(vehicles);
        ETVIN_NewPolicyCreationTrgHandler.processVehicle(vm1);
        //ETVIN_NewPolicyCreationTrgHandler.updateExistingInsurance(vm1);
        
        Test.stopTest();
        
    }
    
    @isTest static void testUpdateExistingInsurance() {
        ETSALES_Location__c lo = new ETSALES_Location__c();
        lo.Name ='test';
        lo.Location_Code__c='123';
        lo.GL_Zone__c ='Zone A';
        insert lo;
        
        Vehicle_Master__c ve =  new Vehicle_Master__c();
        ve.name = 'B0017298';
        ve.Internal_No__c = 'B0017298';
        ve.Plate_Type__c = 'Police';
        ve.Activity_Center_code__c='123';
        ve.Department_Code__c = '123';
        ve.Project_Code__c='123';
        ve.Location_Code__c='123';
        ve.Activity_Center__c='Police';
        
        
        insert ve;
        Vehicle_Master__c ve1 =  new Vehicle_Master__c();
        ve1.name = 'B0017298';
        ve1.Internal_No__c = 'B0017298';
        ve1.Plate_Type__c = 'Police';
        ve1.Activity_Center_code__c='123';
        ve1.Department_Code__c = '123';
        ve1.Project_Code__c='123';
        ve1.Location_Code__c='123';
        ve1.Activity_Center__c='Dubai';
        
        
        insert ve1;
        
        
        Profile p = [SELECT Id FROM Profile WHERE Name=:System.Label.VIN_ZoneProfileName]; 
        User u = new User(Alias = 'standt', Email='standaxne2256@testorg.com', 
                          EmailEncodingKey='UTF-8', LastName='Testing', LanguageLocaleKey='en_US', 
                          LocaleSidKey='en_US', ProfileId = p.Id, ETSALES_Employee_Zone__c='Zone A',
                          TimeZoneSidKey='America/Los_Angeles', UserName='standaxne2256@testorg.com');
        
        System.runAs(u) {
            Account acc = new Account();
            acc.Name = 'test';
            acc.ETSALES_TaxRegistrationNo__c='234333333333333';
            insert acc;
            
            Veh_Default_Insurance_partner__c veh = new Veh_Default_Insurance_partner__c();
            veh.Name ='tet';
            veh.Account_ID__c = acc.Id;            
            insert veh;
            
            ETVIN_Insurance_Policy_Numbers__c insPolicyNum= new ETVIN_Insurance_Policy_Numbers__c();
            insPolicyNum.Name='009128TT';
            insPolicyNum.Activity_Center__c = 'Police';
            insPolicyNum.Active__c=true;
            insert insPolicyNum;
            ETVIN_Insurance_Policy_Numbers__c insPolicyNum1= new ETVIN_Insurance_Policy_Numbers__c();
            insPolicyNum1.Name='009128TT';
            insPolicyNum1.Activity_Center__c = 'Dubai';
            insPolicyNum1.Active__c=true;
            insert insPolicyNum1;
            
            ETVIN_Vehicle_Insurance__c etv = new ETVIN_Vehicle_Insurance__c();
            etv.Vehicle__c = ve.Id;
            etv.ETVIN_Insurance_Company__c= acc.id;
            etv.ETVIN_Insurance_Status__c = 'Active';
            etv.ETVIN_Request_Status__c  = 'New';
            
            insert etv;
            ETVIN_Vehicle_Insurance__c etv1 = new ETVIN_Vehicle_Insurance__c();
            etv1.Vehicle__c = ve1.Id;
            etv1.ETVIN_Insurance_Company__c= acc.id;
            etv1.ETVIN_Insurance_Status__c = 'Active';
            etv1.ETVIN_Request_Status__c  = 'New';
            
            insert etv1;
            
            // Change the TC_Number__c to simulate an update scenario
            ve.TC_Number__c = 002;
            List<Vehicle_Master__c> updatedVehicles = new List<Vehicle_Master__c>{ve};
                
                // Invoke the handler for updated records
                Test.startTest();
            ETVIN_NewPolicyCreationTrgHandler.handleAfterUpdate(updatedVehicles, new Map<Id, Vehicle_Master__c>{ve.Id => ve});
            ETVIN_NewPolicyCreationTrgHandler.processVehicle(ve);
            //ETVIN_NewPolicyCreationTrgHandler.updateExistingInsurance(ve);
            Test.stopTest();
        }
    }
    
    
    
    
}