unpackaged/main/default/objects/Account/fields/ETST_Account_Type__c.field-meta.xml
<CustomField>
    <fullName>ETST_Account_Type__c</fullName>
    <label>Education Sector</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Government School</fullName>
            </value>
            <value>
                <fullName>Private School</fullName>
                <default>true</default>
                <label>Private School</label>
            </value>
            <value>
                <fullName>University</fullName>
            </value>
            <value>
                <fullName>Nursery</fullName>
            </value>
            <value>
                <fullName>Chartered School</fullName>
            </value>
            <value>
                <fullName>Ajyal School</fullName>
            </value>
            <value>
                <fullName>Institute</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/ETST_Student__c/ETST_Student__c.object-meta.xml
<CustomObject>
    <label>Student</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Last Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Students</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

unpackaged/main/default/objects/ETST_Student__c/fields/ETST_Account_Name__c.field-meta.xml
<CustomField>
    <fullName>ETST_Account_Name__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Parent</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Account.RecordTypeId</field>
            <operation>equals</operation>
            <value>Person (B2C)</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Students</relationshipLabel>
    <relationshipName>Students</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/ETST_Student__c/fields/ETST_First_Name__c.field-meta.xml
<CustomField>
    <fullName>ETST_First_Name__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>First Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/ETST_Student__c/fields/ETST_School__c.field-meta.xml
<CustomField>
    <fullName>ETST_School__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>School</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Account.RecordTypeId</field>
            <operation>equals</operation>
            <value>Business (B2B) - School</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Students (School)</relationshipLabel>
    <relationshipName>ETST_Students</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/classes/ETST_TermsAndCondCtrl.cls
/*
Name: ETST_TermsAndCondCtrl
Test Class: ETST_TermsAndCondCtrlTest
Author: Sreelakshmi SK
Created Date: 21 Feb 2023
Description: Controller to provide student details in Student_Code_of_Conduct.vfp
*/

public class ETST_TermsAndCondCtrl {
    public list<ETST_Student__c> stdRecord{get; set;}       
    public ETST_TermsAndCondCtrl(){
        ID idtest=ApexPages.currentPage().getParameters().get('id');
        stdRecord=[select id,name,ETST_First_Name__c,ETST_Account_Name__r.name,CreatedDate,ETST_School__r.ETST_Account_Type__c from ETST_Student__c where id=:idtest];
    }
}