unpackaged/main/default/objects/Account/fields/ETST_Date_of_Birth__c.field-meta.xml
<CustomField>
    <fullName>ETST_Date_of_Birth__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Date of Birth</label>
    <type>Date</type>
</CustomField>

unpackaged/main/default/objects/Account/fields/ETST_Division__c.field-meta.xml
<CustomField>
    <fullName>ETST_Division__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Division</label>
    <type>TextArea</type>
</CustomField>

unpackaged/main/default/objects/Account/fields/ETST_Emirates_Id__c.field-meta.xml
<CustomField>
    <fullName>ETST_Emirates_Id__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Emirates Id</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Account/fields/ETST_Gender__c.field-meta.xml
<CustomField>
    <fullName>ETST_Gender__c</fullName>
    <label>Gender</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Male</fullName>
            </value>
            <value>
                <fullName>Female</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Account/fields/ETST_Grade__c.field-meta.xml
<CustomField>
    <fullName>ETST_Grade__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Grade</label>
    <type>TextArea</type>
</CustomField>

unpackaged/main/default/objects/Account/fields/ETST_Nationality__c.field-meta.xml
<CustomField>
    <fullName>ETST_Nationality__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Nationality</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Account/recordTypes/Inspection.recordType-meta.xml
<RecordType>
    <fullName>Inspection</fullName>
    <active>true</active>
    <label>Inspection</label>
</RecordType>

unpackaged/main/default/objects/ET_Customer_Vehicle__c/ET_Customer_Vehicle__c.object-meta.xml
<CustomObject>
    <label>Customer Vehicle</label>
    <nameField>
        <displayFormat>CV-{000000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Customer Vehicles</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/ET_Customer_Vehicle__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Customer Vehicles</relationshipLabel>
    <relationshipName>Customer_Vehicles</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/ET_Customer_Vehicle__c/fields/Chassis_No__c.field-meta.xml
<CustomField>
    <fullName>Chassis_No__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Chassis No</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/ET_Customer_Vehicle__c/fields/Is_Verified__c.field-meta.xml
<CustomField>
    <fullName>Is_Verified__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Is Verified with AbuDhabi Police?</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/objects/ET_Customer_Vehicle__c/fields/Plate_Color__c.field-meta.xml
<CustomField>
    <fullName>Plate_Color__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Plate Color</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/ET_Customer_Vehicle__c/fields/Plate_No__c.field-meta.xml
<CustomField>
    <fullName>Plate_No__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Plate No</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/ET_Customer_Vehicle__c/fields/Plate_Source__c.field-meta.xml
<CustomField>
    <fullName>Plate_Source__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Plate Source</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/ET_Customer_Vehicle__c/fields/Plate_Type__c.field-meta.xml
<CustomField>
    <fullName>Plate_Type__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Plate Type</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/ET_Customer_Vehicle__c/fields/Registration_Type__c.field-meta.xml
<CustomField>
    <fullName>Registration_Type__c</fullName>
    <label>Registration Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Registered</fullName>
            </value>
            <value>
                <fullName>Un-Registered</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/ET_Customer_Vehicle__c/fields/Vehicle_Type__c.field-meta.xml
<CustomField>
    <fullName>Vehicle_Type__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Vehicle Type</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/ET_Service_Request__c/ET_Service_Request__c.object-meta.xml
<CustomObject>
    <label>Service Request</label>
    <nameField>
        <displayFormat>SR-{000000}</displayFormat>
        <label>Service Request Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Service Requests</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

unpackaged/main/default/objects/ET_Service_Request__c/fields/ETST_Student__c.field-meta.xml
<CustomField>
    <fullName>ETST_Student__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Student</label>
    <referenceTo>ETST_Student__c</referenceTo>
    <relationshipName>ETST_Transport_Requests</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/ETI_Booking__c/ETI_Booking__c.object-meta.xml
<CustomObject>
    <label>Booking</label>
    <nameField>
        <displayFormat>B-{000000}</displayFormat>
        <label>Booking</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Bookings</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

unpackaged/main/default/objects/ETI_Booking__c/fields/Chassis_No__c.field-meta.xml
<CustomField>
    <fullName>Chassis_No__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Chassis No</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/ETI_Booking__c/fields/Customer_Vehicle__c.field-meta.xml
<CustomField>
    <fullName>Customer_Vehicle__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Customer Vehicle</label>
    <referenceTo>ET_Customer_Vehicle__c</referenceTo>
    <relationshipLabel>Bookings</relationshipLabel>
    <relationshipName>Bookings</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/ETI_Booking__c/fields/Plate_No__c.field-meta.xml
<CustomField>
    <fullName>Plate_No__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Plate No</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/ETI_Booking__c/fields/Registration_Type__c.field-meta.xml
<CustomField>
    <fullName>Registration_Type__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Registration Type</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/ETI_Booking__c/fields/Vehicle_Type__c.field-meta.xml
<CustomField>
    <fullName>Vehicle_Type__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Vehicle Type</label>
    <length>250</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/ETI_Booking__c/recordTypes/Internal.recordType-meta.xml
<RecordType>
    <fullName>Internal</fullName>
    <active>true</active>
    <label>Internal</label>
</RecordType>

unpackaged/main/default/objects/ETST_School__c/ETST_School__c.object-meta.xml
<CustomObject>
    <label>School</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>School Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Schools</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/ETST_School__c/fields/ETST_Grade__c.field-meta.xml
<CustomField>
    <fullName>ETST_Grade__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Grade</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/ETST_Student__c/ETST_Student__c.object-meta.xml
<CustomObject>
    <label>Student</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Last Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Students</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

unpackaged/main/default/objects/ETST_Student__c/fields/ETST_Account_Name__c.field-meta.xml
<CustomField>
    <fullName>ETST_Account_Name__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Parent</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Account.RecordTypeId</field>
            <operation>equals</operation>
            <value>Person (B2C)</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Students</relationshipLabel>
    <relationshipName>Students</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/ETST_Student__c/fields/ETST_Date_of_Birth__c.field-meta.xml
<CustomField>
    <fullName>ETST_Date_of_Birth__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Date of Birth</label>
    <type>Date</type>
</CustomField>

unpackaged/main/default/objects/ETST_Student__c/fields/ETST_Division__c.field-meta.xml
<CustomField>
    <fullName>ETST_Division__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Division</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/ETST_Student__c/fields/ETST_Emirate__c.field-meta.xml
<CustomField>
    <fullName>ETST_Emirate__c</fullName>
    <label>Emirate</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Abu Dhabi</fullName>
            </value>
            <value>
                <fullName>Dubai</fullName>
            </value>
            <value>
                <fullName>Ajman</fullName>
            </value>
            <value>
                <fullName>Fujairah</fullName>
            </value>
            <value>
                <fullName>Ras al Khaimah</fullName>
            </value>
            <value>
                <fullName>Sharjah</fullName>
            </value>
            <value>
                <fullName>Umm al Quwain</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/ETST_Student__c/fields/ETST_Emirates_Id__c.field-meta.xml
<CustomField>
    <fullName>ETST_Emirates_Id__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Emirates Id</label>
    <length>100</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

unpackaged/main/default/objects/ETST_Student__c/fields/ETST_ESIS_No__c.field-meta.xml
<CustomField>
    <fullName>ETST_ESIS_No__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>ESIS No</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/ETST_Student__c/fields/ETST_Gender__c.field-meta.xml
<CustomField>
    <fullName>ETST_Gender__c</fullName>
    <label>Gender</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Male</fullName>
            </value>
            <value>
                <fullName>Female</fullName>
            </value>
            <value>
                <fullName>Other</fullName>
                <isActive>false</isActive>
                <label>Other</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/ETST_Student__c/fields/ETST_Nationality__c.field-meta.xml
<CustomField>
    <fullName>ETST_Nationality__c</fullName>
    <label>Nationality</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>ETST_Nationality</valueSetName>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/ETST_Student__c/fields/ETST_Phone__c.field-meta.xml
<CustomField>
    <fullName>ETST_Phone__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Phone</label>
    <type>Phone</type>
</CustomField>

unpackaged/main/default/objects/ETST_Student__c/fields/ETST_School__c.field-meta.xml
<CustomField>
    <fullName>ETST_School__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>School</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Account.RecordTypeId</field>
            <operation>equals</operation>
            <value>Business (B2B) - School</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Students (School)</relationshipLabel>
    <relationshipName>ETST_Students</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/ETST_Student__c/fields/ETST_Student_Id__c.field-meta.xml
<CustomField>
    <fullName>ETST_Student_Id__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Student Id</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/globalValueSets/ETST_Nationality.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Afghanistan</fullName>
    </customValue>
    <customValue>
        <fullName>Aland Islands</fullName>
    </customValue>
    <customValue>
        <fullName>Albania</fullName>
    </customValue>
    <customValue>
        <fullName>Algeria</fullName>
    </customValue>
    <customValue>
        <fullName>Andorra</fullName>
    </customValue>
    <customValue>
        <fullName>Angola</fullName>
    </customValue>
    <customValue>
        <fullName>Anguilla</fullName>
    </customValue>
    <customValue>
        <fullName>Antarctica</fullName>
    </customValue>
    <customValue>
        <fullName>Antigua and Barbuda</fullName>
    </customValue>
    <customValue>
        <fullName>Argentina</fullName>
    </customValue>
    <customValue>
        <fullName>Armenia</fullName>
    </customValue>
    <customValue>
        <fullName>Aruba</fullName>
    </customValue>
    <customValue>
        <fullName>Australia</fullName>
    </customValue>
    <customValue>
        <fullName>Austria</fullName>
    </customValue>
    <customValue>
        <fullName>Azerbaijan</fullName>
    </customValue>
    <customValue>
        <fullName>Bahamas</fullName>
    </customValue>
    <customValue>
        <fullName>Bahrain</fullName>
    </customValue>
    <customValue>
        <fullName>Bangladesh</fullName>
    </customValue>
    <customValue>
        <fullName>Barbados</fullName>
    </customValue>
    <customValue>
        <fullName>Belarus</fullName>
    </customValue>
    <customValue>
        <fullName>Belgium</fullName>
    </customValue>
    <customValue>
        <fullName>Belize</fullName>
    </customValue>
    <customValue>
        <fullName>Benin</fullName>
    </customValue>
    <customValue>
        <fullName>Bermuda</fullName>
    </customValue>
    <customValue>
        <fullName>Bhutan</fullName>
    </customValue>
    <customValue>
        <fullName>Bolivia, Plurinational State of</fullName>
    </customValue>
    <customValue>
        <fullName>Bonaire, Sint Eustatius and Saba</fullName>
    </customValue>
    <customValue>
        <fullName>Bosnia and Herzegovina</fullName>
    </customValue>
    <customValue>
        <fullName>Botswana</fullName>
    </customValue>
    <customValue>
        <fullName>Bouvet Island</fullName>
    </customValue>
    <customValue>
        <fullName>United Arab Emirates</fullName>
    </customValue>
    <masterLabel>Nationality</masterLabel>
</GlobalValueSet>

unpackaged/main/default/classes/ETPaymentTriggerHandler_Test.cls
/*
  CreatedDate:07/28/2020
  CreatedBy:G.Krishnareddy
  Description:ETPaymentTriggerHandler/ETPaymentTriggerHelper for Test Data Preparation
*/
@isTest
public class ETPaymentTriggerHandler_Test{
  
    public static testmethod void paymentTriggerHandlerTestData(){
        
        Account objBusinessAcct = new Account();
        objBusinessAcct.Name = 'ALDAR Academies L.L.C   Al Muna Academy';
        objBusinessAcct.Type = 'Private School';
        objBusinessAcct.RecordTypeId = Schema.SObjectType.Account.getRecordTypeInfosByName().get('Business (B2B) - School').getRecordTypeId();        
        insert objBusinessAcct;
        Contact con = new Contact();
        con.LastName = 'Last name';
        con.Email = 'deepak_thomas@et.ae';
        insert con;
        Account objPersonAcct = new Account();
        objPersonAcct.FirstName = 'ALDAR ';
        objPersonAcct.LastName = 'Al Muna Academy';
        objPersonAcct.RecordTypeId = Schema.SObjectType.Account.getRecordTypeInfosByName().get('Person (B2C)').getRecordTypeId();        
        insert objPersonAcct;
        
        ETST_Student__c objStudent = new ETST_Student__c();
        objStudent.Name  = 'Test Student';
        objStudent.ETST_Emirates_Id__c = '784-2345-1234657-3';
        objStudent.ETST_Gender__c = 'Male';
        objStudent.ETST_Student_Id__c = 'std0001';
        objStudent.ETST_Nationality__c = 'United Arab Emirates';
        objStudent.ETST_Date_of_Birth__c = date.today().addYears(-28);
        objStudent.ETST_ESIS_No__c = '123';
        objStudent.ETST_Division__c = 'A';
        objStudent.ETST_Grade__c = 'A';
        objStudent.ETST_Emirate__c = 'Dubai';
        objStudent.ETST_School__c = objBusinessAcct.Id;
        objStudent.ETST_Account_Name__c = objPersonAcct.Id;
        objStudent.ETST_Phone__c = '971557858043';
        insert objStudent;
        
        ET_Customer_Vehicle__c objCustomerVehicle = new ET_Customer_Vehicle__c();
        objCustomerVehicle.Chassis_No__c = 'AIU12111';
        objCustomerVehicle.Registration_Type__c = 'Registered';
        objCustomerVehicle.Plate_No__c = '111';
        objCustomerVehicle.Plate_Color__c = 'RED';
        objCustomerVehicle.Plate_Source__c = 'ABU DHABI';
        objCustomerVehicle.Plate_Type__c = 'PRIVATE';   
        objCustomerVehicle.Vehicle_Type__c = 'HEAVY BUS MORE THAN 27 PASSENGERS';
        objCustomerVehicle.Is_Verified__c = TRUE;
        objCustomerVehicle.Account__c = objBusinessAcct.Id;
        objCustomerVehicle.Status__c = 'Active';
        objCustomerVehicle.Vehicle_Type_Code__c = '5';
        insert objCustomerVehicle;
        
            
            
        ET_Service_Request__c objServiceReq =  new ET_Service_Request__c();
        objServiceReq.ETST_Student__c = objStudent.Id;
        objServiceReq.ETST_Service_Type__c = 'Half Yearly';
        //objServiceReq.ETST_Pick_Up_Time__c = 120;
        objServiceReq.ETST_Fare_Charges__c = 1200;
        objServiceReq.ETST_Pick_Up_End_Date__c = date.today();
        objServiceReq.ETST_Pick_Up_From__c = '4 19dStreet - Bur DubaiAl Hamriya - Dubai - United Arab Emirates';
        objServiceReq.ETST_Transport_Type__c = 'Two Way';
        objServiceReq.ETST_Is_Active__c = true;
        objServiceReq.ETST_Drop_Off_To__c = '4 19dStreet - Bur DubaiAl Hamriya - Dubai - United Arab Emirates';
        insert objServiceReq;
        
        ETI_Aman_Lookup__c objAmanLKP = new ETI_Aman_Lookup__c();
        objAmanLKP.Name = 'Renewal';
        objAmanLKP.ETI_LookupType__c = 'TEST_PURPOSE';
        objAmanLKP.ETI_LookupCode__c = '2';
        insert objAmanLKP;
        
        ETI_Booking__c objbooking = new ETI_Booking__c();
        objbooking.RecordTypeId = Schema.SObjectType.ETI_Booking__c.getRecordTypeInfosByName().get('Internal').getRecordTypeId();
        objbooking.Service_Request__c = objServiceReq.Id;
        objbooking.User__c = objBusinessAcct.Id;
        objbooking.Customer_Vehicle__c = objCustomerVehicle.Id;
        objbooking.Service_Type__c = 'Police Inspection';   
        objbooking.Purpose_Type__c = objAmanLKP.Id;
        objbooking.Booking_Status__c = 'Booked';
        objbooking.Amount__c = 1300;
        insert objbooking;
        
        ETST_Payment__c objETSTPayment = new ETST_Payment__c();
        objETSTPayment.RecordTypeId = Schema.SObjectType.ETST_Payment__c.getRecordTypeInfosByName().get('On Premise Payment').getRecordTypeId();
        objETSTPayment.ETST_Amount__c = 1200;
        objETSTPayment.ET_Service_Request__c = objServiceReq.id;
        objETSTPayment.ETST_Payment_State__c = 'SUCCESS';
        //objETSTPayment.ETI_Amount__c = 1300;
        insert objETSTPayment;
        
    }
}