unpackaged/main/default/objects/Account/fields/ETST_Emirates_Id__c.field-meta.xml
<CustomField>
    <fullName>ETST_Emirates_Id__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Emirates Id</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/ETST_School__c/ETST_School__c.object-meta.xml
<CustomObject>
    <label>School</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>School Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Schools</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/ETST_School__c/fields/Customer__c.field-meta.xml
<CustomField>
    <fullName>Customer__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Customer</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Schools</relationshipLabel>
    <relationshipName>Schools</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/ETST_Student__c/ETST_Student__c.object-meta.xml
<CustomObject>
    <label>Student</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Last Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Students</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

unpackaged/main/default/objects/ETST_Student__c/fields/ETST_Emirates_Id__c.field-meta.xml
<CustomField>
    <fullName>ETST_Emirates_Id__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Emirates Id</label>
    <length>100</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

unpackaged/main/default/objects/ETST_Student__c/fields/ETST_School__c.field-meta.xml
<CustomField>
    <fullName>ETST_School__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>School</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Account.RecordTypeId</field>
            <operation>equals</operation>
            <value>Business (B2B) - School</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Students (School)</relationshipLabel>
    <relationshipName>ETST_Students</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/ETST_Student__c/fields/ETST_School_Name__c.field-meta.xml
<CustomField>
    <fullName>ETST_School_Name__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>School Name</label>
    <referenceTo>ETST_School__c</referenceTo>
    <relationshipLabel>Students</relationshipLabel>
    <relationshipName>Students</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/classes/ETST_StudentTriggerHandlerTest.cls
@isTest
public class ETST_StudentTriggerHandlerTest {
    public static testmethod void changeStudentSchoolTest(){
        
        Id RecordType = Schema.SObjectType.Account.getRecordTypeInfosByName().get('Business (B2B) - School').getRecordTypeId();
        Account customerAccount=new Account();
        customerAccount.Name='Customer';
        customerAccount.RecordTypeId=RecordType;
        insert customerAccount;
        
        Account customerAccount1=new Account();
        customerAccount1.Name='Customer1';
        customerAccount1.RecordTypeId=RecordType;
        insert customerAccount1;
        
        
        
        ETST_School__c oldSchool = new ETST_School__c();
        oldSchool.Name='OldSchool';
        oldSchool.Customer__c=customerAccount.Id;
		insert oldSchool;
        
        ETST_School__c newSchool = new ETST_School__c();
        newSchool.Name='newSchool';
        newSchool.Customer__c=customerAccount1.Id;
		insert newSchool;
        
        ETST_Student__c student=new ETST_Student__c();
        student.Name='Test Student';
        student.ETST_School_Name__c=oldSchool.Id;
        student.ETST_Emirates_Id__c='784-1234-1234567-1';
        insert student;
        
        
        Map<Id,ETST_Student__c> oldStudentMap=new Map<Id,ETST_Student__c>();
        oldStudentMap.put(student.Id,student);
        
        set<Id>schoolIds=new set<Id>();
        schoolIds.add(student.ETST_School_Name__c);
        
        Map<id,id>schoolIdVsAccountId=new Map<id,id>();
        schoolIdVsAccountId.put(oldSchool.Id,oldSchool.Customer__c);
        
        //student.ETST_School_Name__c=newSchool.Id;
        //update student;
        
        List<ETST_Student__c> updateStudentList=new List<ETST_Student__c>();
        ETST_Student__c tempStudent=new ETST_Student__c();
        tempStudent.id=student.id;
        tempStudent.ETST_School_Name__c=newSchool.Id;
        //tempStudent.ETST_School__c=schoolIdVsAccountId.get(student.ETST_School_Name__c);
        tempStudent.ETST_School__c=customerAccount1.Id;
        updateStudentList.add(tempStudent);
        
        try{
            update updateStudentList;
        }
        
        catch(exception e){}
        
        Map<Id,ETST_Student__c> newStudentMap=new Map<Id,ETST_Student__c>();
        newStudentMap.put(updateStudentList[0].Id,updateStudentList[0]);
        
        
        
        ETST_StudentTriggerHandler.changeStudentSchool(newStudentMap,oldStudentMap);
    }
}