unpackaged/main/default/objects/Account/fields/ETST_Coordinator__c.field-meta.xml
<CustomField>
    <fullName>ETST_Coordinator__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Coordinator</label>
    <referenceTo>User</referenceTo>
    <relationshipName>ET_Schools</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Account/recordTypes/Business_School.recordType-meta.xml
<RecordType>
    <fullName>Business_School</fullName>
    <active>true</active>
    <label>Business (B2B) - School</label>
</RecordType>

unpackaged/main/default/objects/ET_Service_Request__c/ET_Service_Request__c.object-meta.xml
<CustomObject>
    <label>Service Request</label>
    <nameField>
        <displayFormat>SR-{000000}</displayFormat>
        <label>Service Request Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Service Requests</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

unpackaged/main/default/objects/ET_Service_Request__c/fields/ET_Account__c.field-meta.xml
<CustomField>
    <fullName>ET_Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Service Requests (Account)</relationshipLabel>
    <relationshipName>Service_Requests</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/ET_Service_Request__c/fields/ETST_Coordinator__c.field-meta.xml
<CustomField>
    <fullName>ETST_Coordinator__c</fullName>
    <formula>ETST_Student__r.ETST_School__r.ETST_Coordinator__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Coordinator</label>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/ET_Service_Request__c/fields/ETST_School_Name__c.field-meta.xml
<CustomField>
    <fullName>ETST_School_Name__c</fullName>
    <formula>ETST_Student__r.ETST_School_Name__r.Name</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>School Name</label>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/ET_Service_Request__c/fields/ETST_Student__c.field-meta.xml
<CustomField>
    <fullName>ETST_Student__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Student</label>
    <referenceTo>ETST_Student__c</referenceTo>
    <relationshipName>ETST_Transport_Requests</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/ETST_School__c/ETST_School__c.object-meta.xml
<CustomObject>
    <label>School</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>School Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Schools</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/ETST_School__c/fields/Customer__c.field-meta.xml
<CustomField>
    <fullName>Customer__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Customer</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Schools</relationshipLabel>
    <relationshipName>Schools</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/ETST_Student__c/ETST_Student__c.object-meta.xml
<CustomObject>
    <label>Student</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Last Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Students</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

unpackaged/main/default/objects/ETST_Student__c/fields/ETST_Account_Name__c.field-meta.xml
<CustomField>
    <fullName>ETST_Account_Name__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Parent</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Account.RecordTypeId</field>
            <operation>equals</operation>
            <value>Person (B2C)</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Students</relationshipLabel>
    <relationshipName>Students</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/ETST_Student__c/fields/ETST_Coordinator__c.field-meta.xml
<CustomField>
    <fullName>ETST_Coordinator__c</fullName>
    <formula>if(ETST_School__c !=null, ETST_School__r.ETST_Coordinator__c, ETST_School_Name__r.Customer__r.ETST_Coordinator__c)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Coordinator</label>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/ETST_Student__c/fields/ETST_School__c.field-meta.xml
<CustomField>
    <fullName>ETST_School__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>School</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Account.RecordTypeId</field>
            <operation>equals</operation>
            <value>Business (B2B) - School</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Students (School)</relationshipLabel>
    <relationshipName>ETST_Students</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/ETST_Student__c/fields/ETST_School_Name__c.field-meta.xml
<CustomField>
    <fullName>ETST_School_Name__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>School Name</label>
    <referenceTo>ETST_School__c</referenceTo>
    <relationshipLabel>Students</relationshipLabel>
    <relationshipName>Students</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/ETST_Student__c/fields/Service_Request__c.field-meta.xml
<CustomField>
    <fullName>Service_Request__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Service Request</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/objects/Invoice__c/Invoice__c.object-meta.xml
<CustomObject>
    <label>Invoice</label>
    <nameField>
        <displayFormat>INV-{000000}</displayFormat>
        <label>Invoice No</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Invoices</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Invoice__c/fields/Customer__c.field-meta.xml
<CustomField>
    <fullName>Customer__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Customer</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Invoices</relationshipLabel>
    <relationshipName>Invoices</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Invoice__c/fields/ETST_Coordinator__c.field-meta.xml
<CustomField>
    <fullName>ETST_Coordinator__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Coordinator</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Invoices</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Invoice__c/fields/ETST_Type__c.field-meta.xml
<CustomField>
    <fullName>ETST_Type__c</fullName>
    <label>Pay Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Online</fullName>
            </value>
            <value>
                <fullName>On Premise</fullName>
            </value>
            <value>
                <fullName>Bank Transfer / Cash Deposit</fullName>
            </value>
            <value>
                <fullName>Cheque</fullName>
            </value>
            <value>
                <fullName>Cash</fullName>
            </value>
            <value>
                <fullName>Card</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Invoice__c/fields/Service_Request__c.field-meta.xml
<CustomField>
    <fullName>Service_Request__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Service Request</label>
    <referenceTo>ET_Service_Request__c</referenceTo>
    <relationshipLabel>Invoices</relationshipLabel>
    <relationshipName>Invoices</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/classes/ETST_ShareAccountsWithCoordinator.cls
public class ETST_ShareAccountsWithCoordinator {
    
    public static void ShareAccountsWithCoordinator(set<Id> recordIds){
        //string parentRecordTypeId = Schema.SObjectType.Account.getRecordTypeInfosByDeveloperName().get('Person_B2C').getRecordTypeId(); 
        string schoolRecordTypeId = Schema.SObjectType.Account.getRecordTypeInfosByDeveloperName().get('Business_School').getRecordTypeId(); 
        Map<Id,Id> AccUserMap=new Map<Id,Id>();
        for(account acc:[select id,etst_coordinator__c from account where id IN:recordIds and RecordTypeId=:schoolRecordTypeId]){//(RecordTypeId=:parentRecordTypeId or RecordTypeId=:schoolRecordTypeId)
            if(acc.etst_coordinator__c!=null){
                AccUserMap.put(acc.Id,acc.etst_coordinator__c);  
            }
            
        }
        system.debug('++AccUserMap++'+AccUserMap);
        if (AccUserMap.size() != null && AccUserMap.size()>0) {
            // Create new sharing object for the custom object Account.
            List<AccountShare> accshrList  = new List<AccountShare>();       
            for(Id id : AccUserMap.keyset()){
                AccountShare accshr=new AccountShare();
                // Set the ID of record being shared.
                accshr.accountId = Id;
                
                // Set the ID of user or group being granted access.
                accshr.UserOrGroupId =AccUserMap.get(Id) ;
                
                // Set the access level.
                accshr.AccountAccessLevel = 'Read';
                accshr.OpportunityAccessLevel = 'Read';
                
                // Set rowCause to 'manual' for manual sharing.
                // This line can be omitted as 'manual' is the default value for sharing objects.
                accshr.RowCause = Schema.AccountShare.RowCause.Manual;
                accshrList.add(accshr);
            }  
            
            try{
                System.debug('accshrList');
                insert accshrList;
            }catch(DMLException ex){
                System.debug('Sharing records with Coordinator failed'+ex.getMessage());
            } 
        }
    }
    
    public static void shareStudentsToCoordinator(Map<id, ETST_Student__c> newMap, Map<id, ETST_Student__c> oldMap){
        set<id> accountIds = new set<id>();
        Map<Id, Id> studentMap = new Map<Id, Id>();
        Map<Id, Id> parentMap = new Map<Id, Id>();
        List<AccountShare> parentshrList  = new List<AccountShare>();  
        List<ETST_Student__c> lstStudents = new List<ETST_Student__c>();
        for(ETST_Student__c student:[select id,ETST_Account_Name__c,ETST_School_Name__c,ETST_School_Name__r.Customer__r.ETST_Coordinator__c,ETST_School_Name__r.Customer__c,ETST_School__c,ETST_School__r.etst_coordinator__c,ETST_Coordinator__c from ETST_Student__c where Id IN:newMap.keyset()]){
            if(student.ETST_School_Name__r.Customer__c!=null){
                student.ETST_School__c = student.ETST_School_Name__r.Customer__c;
                student.OwnerId = student.ETST_School_Name__r.Customer__r.ETST_Coordinator__c;
                lstStudents.add(student);
            }
            
        }
        if(!lstStudents.isEmpty()){
            update lstStudents;
        }
        /*  for(ETST_Student__c student:[select id,ETST_Account_Name__c,ETST_School_Name__c,ETST_School_Name__r.Customer__c,ETST_School__c,ETST_School__r.etst_coordinator__c,ETST_Coordinator__c from ETST_Student__c where Id IN:lstStudents]){
if(student.ETST_Coordinator__c!=null){ 
parentMap.put(student.ETST_Account_Name__c, student.ETST_Coordinator__c);
}            
}   
for(Id parentId : parentMap.keySet()){
AccountShare accshr=new AccountShare();
accshr.accountId = parentId;
accshr.UserOrGroupId =parentMap.get(parentId) ;
accshr.AccountAccessLevel = 'Read';
accshr.OpportunityAccessLevel = 'Read';
accshr.RowCause = Schema.AccountShare.RowCause.Manual;
parentshrList.add(accshr);
} */
        try{
            if(!parentshrList.isEmpty()){
                //insert parentshrList;
            }
        }catch(DMLException ex){
            System.debug('Sharing records with Coordinator failed'+ex.getMessage());
        }
    }
    public static void populateCoordinatorandLocation(List<Invoice__c> newMap){
        Set<Id> serviceRequestIds = new Set<Id>();
        Map<Id, ET_Service_Request__c> mapServiceRequests = new Map<Id, ET_Service_Request__c>();
        for(Invoice__c inv : newMap){
            if(inv.Service_Request__c !=null && inv.ETST_Type__c !=null){
                serviceRequestIds.add(inv.Service_Request__c);
            }
        }
        if(serviceRequestIds.size()>0){
            for(ET_Service_Request__c sevReq : [Select Id,Name,ET_Account__c,ETST_Coordinator__c FROM ET_Service_Request__c WHERE Id IN:serviceRequestIds]){
                mapServiceRequests.put(sevReq.Id, sevReq);
            }
        }
        system.debug('mapServiceRequests***'+mapServiceRequests);
        if(!mapServiceRequests.isEmpty()){
            for(Invoice__c inv : newMap){
                inv.ETST_Coordinator__c =  mapServiceRequests.get(inv.Service_Request__c).ETST_Coordinator__c;
                inv.Customer__c =  mapServiceRequests.get(inv.Service_Request__c).ET_Account__c;
            }
        }
        
    } 
    /*
public static void shareServiceRequestsToCoordinator(Map<id, ET_Service_Request__c>newMap, Map<id, ET_Service_Request__c> oldMap){
Map<Id, Id> serviceRequestMap = new Map<Id, Id>();
List<ET_Service_Request__Share> serviceRequestshrList = new List<ET_Service_Request__Share>(); 
List<ETST_Student__c> lstStudents = new List<ETST_Student__c>();
for(ET_Service_Request__c service :[select id,ETST_Student__c,ETST_Student__r.ETST_Coordinator__c from ET_Service_Request__c where Id IN:newMap.keyset()]){
if(service.ETST_Student__c!=null){
serviceRequestMap.put(service.id, service.ETST_Student__r.ETST_Coordinator__c);
}

}
for(Id serviceId : serviceRequestMap.keySet()){
ET_Service_Request__Share serviceshr = new ET_Service_Request__Share();
serviceshr.parentId = serviceId;
serviceshr.UserOrGroupId = serviceRequestMap.get(serviceId);
serviceshr.AccessLevel = 'Edit';
serviceshr.RowCause = Schema.AccountShare.RowCause.Manual;
serviceRequestshrList.add(serviceshr);
}
try{
if(!serviceRequestshrList.isEmpty()){
insert serviceRequestshrList;
}
}catch(DMLException ex){
System.debug('Sharing records with Coordinator failed'+ex.getMessage());
}
}
*/
    /* public static void serviceRequestsOwnerChangeToCoordinator(Map<Id,ET_Service_Request__c> newMap){
List<ET_Service_Request__c> updateServiceRequest = new List<ET_Service_Request__c>();        

for(ET_Service_Request__c request : [select id,ETST_Coordinator__c,ownerId from ET_Service_Request__c
where id IN:newMap.keyset() ] ){
request.OwnerId = request.ETST_Coordinator__c;
updateServiceRequest.add(request);

}
try{
update updateServiceRequest;
}catch(DMLException ex){
System.debug('Sharing records with Coordinator failed'+ex.getMessage());
}         

}*/

    
    public static void shareParentAccountsToCoordinator(Map<id, ETST_Student__c> newMap, Map<id, ETST_Student__c> oldMap){
        
        Set<Id> parentShareList  = new Set<Id>();  
        Set<Id> cordinatorList = new Set<Id>();
        for(ETST_Student__c student:[SELECT id,ETST_School__c,ETST_School__r.ETST_coordinator__c,ETST_Coordinator__c,ETST_Account_Name__c  FROM ETST_Student__c WHERE Id IN:newMap.keyset()]){
            if(student.ETST_School_Name__r.Customer__c!=null){
                parentShareList.add(student.ETST_Account_Name__c);
                cordinatorList.add(student.ETST_Coordinator__c);
            }
        }
    }
    
    

}