unpackaged/main/default/objects/Account/fields/ETST_Emirates_Id__c.field-meta.xml
<CustomField>
    <fullName>ETST_Emirates_Id__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Emirates Id</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/ET_Service_Request__c/ET_Service_Request__c.object-meta.xml
<CustomObject>
    <label>Service Request</label>
    <nameField>
        <displayFormat>SR-{000000}</displayFormat>
        <label>Service Request Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Service Requests</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

unpackaged/main/default/objects/ET_Service_Request__c/fields/ETST_Is_Active__c.field-meta.xml
<CustomField>
    <fullName>ETST_Is_Active__c</fullName>
    <defaultValue>true</defaultValue>
    <label>Is Active</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/objects/ET_Service_Request__c/fields/ETST_Is_Renewed__c.field-meta.xml
<CustomField>
    <fullName>ETST_Is_Renewed__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Is Renewed</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/objects/ET_Service_Request__c/fields/ETST_Paid_By__c.field-meta.xml
<CustomField>
    <fullName>ETST_Paid_By__c</fullName>
    <label>Paid By</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Self</fullName>
                <default>true</default>
                <label>Self</label>
            </value>
            <value>
                <fullName>Employer</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/ET_Service_Request__c/fields/ETST_Pick_Up_End_Date__c.field-meta.xml
<CustomField>
    <fullName>ETST_Pick_Up_End_Date__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Pickup End Date</label>
    <type>Date</type>
</CustomField>

unpackaged/main/default/objects/ET_Service_Request__c/fields/ETST_Student__c.field-meta.xml
<CustomField>
    <fullName>ETST_Student__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Student</label>
    <referenceTo>ETST_Student__c</referenceTo>
    <relationshipName>ETST_Transport_Requests</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/ET_Service_Request__c/fields/ETST_User__c.field-meta.xml
<CustomField>
    <fullName>ETST_User__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Parent User</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Service_Requests</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/ET_Service_Request__c/fields/Payment_Status__c.field-meta.xml
<CustomField>
    <fullName>Payment_Status__c</fullName>
    <label>Payment Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Not Initiated</fullName>
            </value>
            <value>
                <fullName>Payment Pending</fullName>
            </value>
            <value>
                <fullName>Payment Success</fullName>
            </value>
            <value>
                <fullName>Refund Requested</fullName>
            </value>
            <value>
                <fullName>Await3D</fullName>
            </value>
            <value>
                <fullName>Captured</fullName>
            </value>
            <value>
                <fullName>Partially Paid</fullName>
            </value>
            <value>
                <fullName>Fully Paid</fullName>
            </value>
            <value>
                <fullName>Refund Cancelled</fullName>
            </value>
            <value>
                <fullName>Failed</fullName>
            </value>
            <value>
                <fullName>Reversed</fullName>
            </value>
            <value>
                <fullName>On Premise Requested</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/ETST_Student__c/ETST_Student__c.object-meta.xml
<CustomObject>
    <label>Student</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Last Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Students</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

unpackaged/main/default/objects/ETST_Student__c/fields/ETST_Account_Name__c.field-meta.xml
<CustomField>
    <fullName>ETST_Account_Name__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Parent</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Account.RecordTypeId</field>
            <operation>equals</operation>
            <value>Person (B2C)</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Students</relationshipLabel>
    <relationshipName>Students</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/ETST_Student__c/fields/ETST_Emirates_Id__c.field-meta.xml
<CustomField>
    <fullName>ETST_Emirates_Id__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Emirates Id</label>
    <length>100</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

unpackaged/main/default/objects/User/fields/ETST_Emirates_ID__c.field-meta.xml
<CustomField>
    <fullName>ETST_Emirates_ID__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Emirates ID</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/classes/ETST_MyServicesController_Test.cls
@isTest
public class ETST_MyServicesController_Test {
    
    @isTest static void testMyServices(){
        
        System.Test.startTest();
        
        Id devRecordTypeId = Schema.SObjectType.Account.getRecordTypeInfosByDeveloperName().get('Person_B2C').getRecordTypeId();
        Account acc = new Account(RecordTypeId=devRecordTypeId,FirstName = 'Test',LastName = 'Test',PersonEmail='test@test.com');
        insert acc;
       /* Contact con = new Contact(lastname = 'Test1', accountid = acc.Id);
        
        Profile p = [SELECT Id FROM Profile WHERE Name='System Administrator']; 
        User u = new User(Alias = 'standt', Email='standarduser@testorg.com', 
                          EmailEncodingKey='UTF-8', LastName='Testing', LanguageLocaleKey='en_US', 
                          LocaleSidKey='en_US', ProfileId = p.Id, 
                          TimeZoneSidKey='America/Los_Angeles', UserName='standardusersree@testorg.com',contactid=con.Id);*/
        ETST_Student__c stdnt = new ETST_Student__c(Name='Student',ETST_Emirates_Id__c='784-1347-1234567-1',ETST_Account_Name__c=acc.Id);
        insert stdnt;
        
        List<ET_Service_Request__c> srList = new List<ET_Service_Request__c>();
        Id srRecordTypeId = Schema.SObjectType.ET_Service_Request__c.getRecordTypeInfosByName().get('School Service Request').getRecordTypeId();
        For(Integer i=0;i<10;i++){
            ET_Service_Request__c  etreq = new ET_Service_Request__c(recordtypeId= srRecordTypeId,Payment_Status__c='Not Initiated',ETST_Student__c=stdnt.Id,ETST_Pick_Up_End_Date__c=System.today()+3,
                                                                     ETST_Paid_By__c = 'Self',ETST_Is_Renewed__c=false,ETST_Is_Active__c=true,ETST_User__c=userinfo.getUserId());
            srList.add(etreq);
        }
        insert srList;
        User u1=[select id from user where contactId=:acc.PersonContactId and isActive=true LIMIT 1];
        system.runAs(u1){
            ETST_MyServicesController.getServiceRequests();
        }
    }
}