unpackaged/main/default/objects/Account/fields/ETST_Coordinator__c.field-meta.xml
<CustomField>
    <fullName>ETST_Coordinator__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Coordinator</label>
    <referenceTo>User</referenceTo>
    <relationshipName>ET_Schools</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/ETST_School__c/ETST_School__c.object-meta.xml
<CustomObject>
    <label>School</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>School Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Schools</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/ETST_Student__c/ETST_Student__c.object-meta.xml
<CustomObject>
    <label>Student</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Last Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Students</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

unpackaged/main/default/objects/ETST_Student__c/fields/ETST_Account_Name__c.field-meta.xml
<CustomField>
    <fullName>ETST_Account_Name__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Parent</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Account.RecordTypeId</field>
            <operation>equals</operation>
            <value>Person (B2C)</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Students</relationshipLabel>
    <relationshipName>Students</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/ETST_Student__c/fields/ETST_Coordinator__c.field-meta.xml
<CustomField>
    <fullName>ETST_Coordinator__c</fullName>
    <formula>if(ETST_School__c !=null, ETST_School__r.ETST_Coordinator__c, ETST_School_Name__r.Customer__r.ETST_Coordinator__c)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Coordinator</label>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/ETST_Student__c/fields/ETST_Parent_Access_Granted__c.field-meta.xml
<CustomField>
    <fullName>ETST_Parent_Access_Granted__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Parent Access Granted</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/objects/ETST_Student__c/fields/ETST_School__c.field-meta.xml
<CustomField>
    <fullName>ETST_School__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>School</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Account.RecordTypeId</field>
            <operation>equals</operation>
            <value>Business (B2B) - School</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Students (School)</relationshipLabel>
    <relationshipName>ETST_Students</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/classes/ETST_ParentAccessToCoordinatorBatch.cls
global class ETST_ParentAccessToCoordinatorBatch implements Database.Batchable<sObject>, Schedulable{
    
    global string queryString;
    
    global Database.QueryLocator start(Database.BatchableContext bc) {
        
        queryString = 'Select Id,ETST_School__c,ETST_Account_Name__c,ETST_School__r.ETST_Coordinator__c';
        queryString += ' from ETST_Student__c WHERE ETST_Parent_Access_Granted__c= false';
        return Database.getQueryLocator(queryString);
    }
    
    global void execute(Database.BatchableContext bc, List<ETST_Student__c> scope){
        Set<Id> accIds = new Set<Id>();
        for(ETST_Student__c stdnt: scope){
            accIds.add(stdnt.ETST_Account_Name__c);  
        }
        Map<Id, set<Id>> accessMap = new map<Id, set<Id>>();
        for(AccountShare shr : [Select Id,AccountId,UserOrGroupId from AccountShare where accountId In:accIds]){
            if(!accessMap.containskey(shr.AccountId)){
                accessMap.put(shr.AccountId, new set<id>());
            }
            accessMap.get(shr.AccountId).add(shr.UserOrGroupId);
        }
        List<ETST_Student__c> studentsListToUpdate = new List<ETST_Student__c>();
        List<AccountShare> accshrList  = new List<AccountShare>();  
        for(ETST_Student__c std : scope){ 
            if(!accessMap.containskey(std.ETST_Account_Name__c) || !accessMap.get(std.ETST_Account_Name__c).contains(std.ETST_School__r.ETST_Coordinator__c)){
                AccountShare accshr=new AccountShare();
                accshr.accountId = std.ETST_Account_Name__c;
                accshr.UserOrGroupId =std.ETST_School__r.ETST_Coordinator__c;
                accshr.AccountAccessLevel = System.label.ETST_ParentAccessLevel;
                accshr.OpportunityAccessLevel = System.label.ETST_ParentAccessLevel;
                accshr.RowCause = Schema.AccountShare.RowCause.Manual;
                accshrList.add(accshr);
                std.ETST_Parent_Access_Granted__c = true;
                studentsListToUpdate.add(std);
            }
        } 
        try{
            insert accshrList;
            update studentsListToUpdate;
        }catch(DMLException ex){
            System.debug('Sharing records with Coordinator failed'+ex.getMessage());
        } 
    }
    
    global void finish(Database.BatchableContext bc){
    }    
    
    global void execute(SchedulableContext sc) {
        Database.executeBatch(new ETST_ParentAccessToCoordinatorBatch());
    }
    
}