unpackaged/main/default/objects/Account/fields/ETST_Coordinator__c.field-meta.xml
<CustomField>
    <fullName>ETST_Coordinator__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Coordinator</label>
    <referenceTo>User</referenceTo>
    <relationshipName>ET_Schools</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Account/fields/ETST_Emirates_Id__c.field-meta.xml
<CustomField>
    <fullName>ETST_Emirates_Id__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Emirates Id</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Account/recordTypes/Business_School.recordType-meta.xml
<RecordType>
    <fullName>Business_School</fullName>
    <active>true</active>
    <label>Business (B2B) - School</label>
</RecordType>

unpackaged/main/default/objects/ET_Receipt__c/ET_Receipt__c.object-meta.xml
<CustomObject>
    <label>Receipt</label>
    <nameField>
        <displayFormat>R-{000000}</displayFormat>
        <label>Receipt Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Receipts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/ET_Receipt__c/fields/ET_Amount__c.field-meta.xml
<CustomField>
    <fullName>ET_Amount__c</fullName>
    <label>Amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

unpackaged/main/default/objects/ET_Receipt__c/fields/ET_Service_Request__c.field-meta.xml
<CustomField>
    <fullName>ET_Service_Request__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Service Request</label>
    <referenceTo>ET_Service_Request__c</referenceTo>
    <relationshipLabel>Receipts</relationshipLabel>
    <relationshipName>Customer_Receipts</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/ET_Sales_Agreement__c/ET_Sales_Agreement__c.object-meta.xml
<CustomObject>
    <label>Sales Agreement</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Sales Agreement</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Sales Agreements</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/ET_Sales_Agreement__c/fields/Salesforce_Customer__c.field-meta.xml
<CustomField>
    <fullName>Salesforce_Customer__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Customer</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Sales Agreements</relationshipLabel>
    <relationshipName>Sales_Agreements</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/ET_Service_Request__c/ET_Service_Request__c.object-meta.xml
<CustomObject>
    <label>Service Request</label>
    <nameField>
        <displayFormat>SR-{000000}</displayFormat>
        <label>Service Request Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Service Requests</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

unpackaged/main/default/objects/ET_Service_Request__c/fields/ET_Sales_Agreement__c.field-meta.xml
<CustomField>
    <fullName>ET_Sales_Agreement__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Sales Agreement</label>
    <referenceTo>ET_Sales_Agreement__c</referenceTo>
    <relationshipLabel>Service Requests</relationshipLabel>
    <relationshipName>Service_Requests</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/ET_Service_Request__c/fields/ETST_Coordinator__c.field-meta.xml
<CustomField>
    <fullName>ETST_Coordinator__c</fullName>
    <formula>ETST_Student__r.ETST_School__r.ETST_Coordinator__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Coordinator</label>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/ET_Service_Request__c/fields/ETST_Fare_Charges__c.field-meta.xml
<CustomField>
    <fullName>ETST_Fare_Charges__c</fullName>
    <label>Fare Charges</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

unpackaged/main/default/objects/ET_Service_Request__c/fields/ETST_Paid_By__c.field-meta.xml
<CustomField>
    <fullName>ETST_Paid_By__c</fullName>
    <label>Paid By</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Self</fullName>
                <default>true</default>
                <label>Self</label>
            </value>
            <value>
                <fullName>Employer</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/ET_Service_Request__c/fields/ETST_Pick_Up_End_Date__c.field-meta.xml
<CustomField>
    <fullName>ETST_Pick_Up_End_Date__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Pickup End Date</label>
    <type>Date</type>
</CustomField>

unpackaged/main/default/objects/ET_Service_Request__c/fields/ETST_Pick_Up_Start_Date__c.field-meta.xml
<CustomField>
    <fullName>ETST_Pick_Up_Start_Date__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Request Date</label>
    <type>Date</type>
</CustomField>

unpackaged/main/default/objects/ET_Service_Request__c/fields/ETST_Student__c.field-meta.xml
<CustomField>
    <fullName>ETST_Student__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Student</label>
    <referenceTo>ETST_Student__c</referenceTo>
    <relationshipName>ETST_Transport_Requests</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/ET_Service_Request__c/fields/Payment_Status__c.field-meta.xml
<CustomField>
    <fullName>Payment_Status__c</fullName>
    <label>Payment Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Not Initiated</fullName>
            </value>
            <value>
                <fullName>Payment Pending</fullName>
            </value>
            <value>
                <fullName>Payment Success</fullName>
            </value>
            <value>
                <fullName>Refund Requested</fullName>
            </value>
            <value>
                <fullName>Await3D</fullName>
            </value>
            <value>
                <fullName>Captured</fullName>
            </value>
            <value>
                <fullName>Partially Paid</fullName>
            </value>
            <value>
                <fullName>Fully Paid</fullName>
            </value>
            <value>
                <fullName>Refund Cancelled</fullName>
            </value>
            <value>
                <fullName>Failed</fullName>
            </value>
            <value>
                <fullName>Reversed</fullName>
            </value>
            <value>
                <fullName>On Premise Requested</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/ET_Service_Request__c/recordTypes/ETST_School_Service_Request.recordType-meta.xml
<RecordType>
    <fullName>ETST_School_Service_Request</fullName>
    <active>true</active>
    <label>School Service Request</label>
</RecordType>

unpackaged/main/default/objects/ETST_Calendar__c/ETST_Calendar__c.object-meta.xml
<CustomObject>
    <label>Calendar</label>
    <nameField>
        <displayFormat>CADR-{00000}</displayFormat>
        <label>Calendar Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Calendars</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/ETST_Calendar__c/fields/ETST_School__c.field-meta.xml
<CustomField>
    <fullName>ETST_School__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>School</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Account.RecordTypeId</field>
            <operation>equals</operation>
            <value>Business (B2B) - School</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Calendars</relationshipLabel>
    <relationshipName>Calendars</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/ETST_Payment__c/ETST_Payment__c.object-meta.xml
<CustomObject>
    <label>Payment</label>
    <nameField>
        <displayFormat>TRN-{00000}</displayFormat>
        <label>ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Payments</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/ETST_Payment__c/fields/ET_Service_Request__c.field-meta.xml
<CustomField>
    <fullName>ET_Service_Request__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Service Request</label>
    <referenceTo>ET_Service_Request__c</referenceTo>
    <relationshipLabel>Payments</relationshipLabel>
    <relationshipName>ET_Payments</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/ETST_Payment__c/fields/ETST_Amount__c.field-meta.xml
<CustomField>
    <fullName>ETST_Amount__c</fullName>
    <label>Amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

unpackaged/main/default/objects/ETST_Payment__c/fields/ETST_Coordinator__c.field-meta.xml
<CustomField>
    <fullName>ETST_Coordinator__c</fullName>
    <formula>ET_Service_Request__r.ETST_Coordinator__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Coordinator</label>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/ETST_Payment__c/fields/ETST_Fare_Charges__c.field-meta.xml
<CustomField>
    <fullName>ETST_Fare_Charges__c</fullName>
    <formula>ET_Service_Request__r.ETST_Fare_Charges__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Fare Charges</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

unpackaged/main/default/objects/ETST_Payment__c/fields/ETST_Payment_State__c.field-meta.xml
<CustomField>
    <fullName>ETST_Payment_State__c</fullName>
    <defaultValue>IF( $RecordType.DeveloperName = &#39;On_Premise_Payment&#39; , &#39;SUCCESS&#39;, &#39;&#39;)</defaultValue>
    <encryptionScheme>None</encryptionScheme>
    <label>Payment State</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/ETST_School__c/ETST_School__c.object-meta.xml
<CustomObject>
    <label>School</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>School Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Schools</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/ETST_School__c/fields/ETST_Calendar__c.field-meta.xml
<CustomField>
    <fullName>ETST_Calendar__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Calendar</label>
    <referenceTo>ETST_Calendar__c</referenceTo>
    <relationshipLabel>Schools</relationshipLabel>
    <relationshipName>Schools</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/ETST_Student__c/ETST_Student__c.object-meta.xml
<CustomObject>
    <label>Student</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Last Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Students</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

unpackaged/main/default/objects/ETST_Student__c/fields/ETST_Account_Name__c.field-meta.xml
<CustomField>
    <fullName>ETST_Account_Name__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Parent</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Account.RecordTypeId</field>
            <operation>equals</operation>
            <value>Person (B2C)</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Students</relationshipLabel>
    <relationshipName>Students</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/ETST_Student__c/fields/ETST_Coordinator__c.field-meta.xml
<CustomField>
    <fullName>ETST_Coordinator__c</fullName>
    <formula>if(ETST_School__c !=null, ETST_School__r.ETST_Coordinator__c, ETST_School_Name__r.Customer__r.ETST_Coordinator__c)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Coordinator</label>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/ETST_Student__c/fields/ETST_Emirates_Id__c.field-meta.xml
<CustomField>
    <fullName>ETST_Emirates_Id__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Emirates Id</label>
    <length>100</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

unpackaged/main/default/objects/ETST_Student__c/fields/ETST_Parent_Access_Granted__c.field-meta.xml
<CustomField>
    <fullName>ETST_Parent_Access_Granted__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Parent Access Granted</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/objects/ETST_Student__c/fields/ETST_School__c.field-meta.xml
<CustomField>
    <fullName>ETST_School__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>School</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Account.RecordTypeId</field>
            <operation>equals</operation>
            <value>Business (B2B) - School</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Students (School)</relationshipLabel>
    <relationshipName>ETST_Students</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/User/fields/ETST_Emirates_ID__c.field-meta.xml
<CustomField>
    <fullName>ETST_Emirates_ID__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Emirates ID</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/classes/ETST_Global_Handler_Test.cls
@isTest
public class ETST_Global_Handler_Test {
    @testsetup
    public static void setUpdata(){
        
    }
    
    @isTest
    public static void testGlobalHandler(){
        List<Account> accList = new List<Account>();
        Account acc  = new Account(Name = 'Test Name');
        acc.RecordTypeId = Schema.SObjectType.Account.getRecordTypeInfosByDeveloperName().get('Business_School').getRecordTypeId();
        accList.add(acc);
        acc  = new Account(Name = '001');
        acc.RecordTypeId = Schema.SObjectType.Account.getRecordTypeInfosByDeveloperName().get('Person_B2C').getRecordTypeId(); 
        // accList.add(acc);
        insert accList;
        ET_Sales_Agreement__c etSales = new ET_Sales_Agreement__c();
        etSales.Salesforce_Customer__c = accList[0].id;
        insert etSales;
        ETST_Calendar__c etcal = new ETST_Calendar__c();
        insert etcal;
        new ET_InspectionCancellation.Output();
        new ET_InspectionCancellation.Control();
        new Et_Fee.InspectionFeeOutputDetailCollection_element();
        new Et_Fee.Output();
        new Et_Fee.Control();
        new Et_Fee.InspectionFeeOutputDetail();
        new Et_Fee.InspectionFeeInputDetail();
        
        Id devRecordTypeId = Schema.SObjectType.Account.getRecordTypeInfosByName().get('Person (B2C)').getRecordTypeId();
        Account acc1 = new Account(RecordTypeId=devRecordTypeId,FirstName = 'Test',LastName = 'Test');
        insert acc1;
        
        ETST_Student__c stdnt = new ETST_Student__c(Name='Student',ETST_Emirates_Id__c='784-1347-1234567-1',ETST_Account_Name__c=acc1.Id);
        insert stdnt;
        
        Id serviceReqRecordTypeId = Schema.SObjectType.ET_Service_Request__c.getRecordTypeInfosByDeveloperName().get('ETST_School_Service_Request').getRecordTypeId();
        ET_Service_Request__c  etreq = new ET_Service_Request__c(RecordTypeId=serviceReqRecordTypeId,Payment_Status__c='Not Initiated',ETST_Fare_Charges__c=80,ETST_Student__c=stdnt.Id,ETST_Paid_By__c = 'Self');
        insert etreq;
        
        etreq.Payment_Status__c='Partially Paid';
        etreq.ETST_Fare_Charges__c =1500;
        etreq.ETST_Pick_Up_End_Date__c = system.today();
        etreq.ETST_Pick_Up_Start_Date__c = system.today().addmonths(-2);
        update etreq;
        
        ET_Receipt__c receipt = new ET_Receipt__c();
        receipt.ET_Service_Request__c = etreq.id;
        receipt.ET_Amount__c = 100;
        insert receipt;
        
        ETST_Payment__c objETSTPayment = new ETST_Payment__c();
        objETSTPayment.RecordTypeId = Schema.SObjectType.ETST_Payment__c.getRecordTypeInfosByName().get('On Premise Payment').getRecordTypeId();
        objETSTPayment.ETST_Amount__c = 1200;
        objETSTPayment.ET_Service_Request__c = etreq.id;
        objETSTPayment.ETST_Payment_State__c = 'CAPTURED';
        insert objETSTPayment;
        
    }
    
    @isTest static void testGlobalHanlder2(){
        ETST_Global_Handler.magicmethod();
        id profileId = [Select Id from Profile where Name='School Coordinator' limit 1].Id;
        user coordinator = [Select Id,Name from User where Profileid=:profileId  and isactive=true limit 1];
        Id devRecordTypeId = Schema.SObjectType.Account.getRecordTypeInfosByName().get('Person (B2C)').getRecordTypeId();
        Account acc = new Account(RecordTypeId=devRecordTypeId,FirstName = 'Test',LastName = 'Test',PersonEmail='test@test.com',etst_coordinator__c=userinfo.getUserId());
        insert acc; 
        Id schoolRecordTypeId = Schema.SObjectType.Account.getRecordTypeInfosByName().get('Business (B2B) - School').getRecordTypeId(); 
        Account acc1 = new Account(RecordTypeId=schoolRecordTypeId,Name='Test');
        insert acc1;
        Account acc2 = new Account(RecordTypeId=schoolRecordTypeId,Name='Test1');
        insert acc2;
        delete acc2;
        ET_Sales_Agreement__c agr = new ET_Sales_Agreement__c(Salesforce_Customer__c=acc1.Id);
        insert agr;        
        ETST_Student__c stdnt = new ETST_Student__c(Name='Student',ETST_Emirates_Id__c='784-1347-1234567-1',
                                                    ETST_Account_Name__c=acc.Id,ETST_School__c=acc1.Id,ETST_Parent_Access_Granted__c=false);
        insert stdnt;
        acc1.etst_coordinator__c=coordinator.Id;
        update acc1;
        
        
    }
    
}