unpackaged/main/default/objects/Account/fields/GL_Region__c.field-meta.xml
<CustomField>
    <fullName>GL_Region__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>GL Region</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Account/fields/GL_Zone__c.field-meta.xml
<CustomField>
    <fullName>GL_Zone__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>GL Zone</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Account/fields/Location__c.field-meta.xml
<CustomField>
    <fullName>Location__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Location</label>
    <referenceTo>ET_Location__c</referenceTo>
    <relationshipLabel>Accounts</relationshipLabel>
    <relationshipName>Accounts</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Estimation__c/Estimation__c.object-meta.xml
<CustomObject>
    <label>Maintenance Estimation</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Estimation Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Estimations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Estimation__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipName>Estimations</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Estimation__c/fields/Sales_Agreement__c.field-meta.xml
<CustomField>
    <fullName>Sales_Agreement__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Sales Agreement</label>
    <referenceTo>ET_Sales_Agreement__c</referenceTo>
    <relationshipName>Estimations</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Estimation__c/fields/Service_Center__c.field-meta.xml
<CustomField>
    <fullName>Service_Center__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Service Center</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/ET_Sales_Agreement__c/ET_Sales_Agreement__c.object-meta.xml
<CustomObject>
    <label>Sales Agreement</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Sales Agreement</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Sales Agreements</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/ET_Sales_Agreement__c/fields/Administration_Charges__c.field-meta.xml
<CustomField>
    <fullName>Administration_Charges__c</fullName>
    <label>Administration Charges</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

unpackaged/main/default/objects/ET_Sales_Agreement__c/fields/Contract_No__c.field-meta.xml
<CustomField>
    <fullName>Contract_No__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Contact Number</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/ET_Sales_Agreement__c/fields/Contract_Start_Date__c.field-meta.xml
<CustomField>
    <fullName>Contract_Start_Date__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Contract Start Date</label>
    <type>Date</type>
</CustomField>

unpackaged/main/default/objects/ET_Sales_Agreement__c/fields/Contract_Status__c.field-meta.xml
<CustomField>
    <fullName>Contract_Status__c</fullName>
    <label>Contract Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>ACTIVE</fullName>
                <label>Active</label>
            </value>
            <value>
                <fullName>EXPIRED</fullName>
                <label>Expired</label>
            </value>
            <value>
                <fullName>DRAFT</fullName>
                <label>Draft</label>
            </value>
            <value>
                <fullName>TERMINATED</fullName>
                <label>Terminated</label>
            </value>
            <value>
                <fullName>CLOSED</fullName>
                <label>Closed</label>
            </value>
            <value>
                <fullName>ENTERED</fullName>
                <label>Entered</label>
            </value>
            <value>
                <fullName>AWAITING_START_DATE</fullName>
                <label>Awaiting Start Date</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/ET_Sales_Agreement__c/fields/Contract_Type__c.field-meta.xml
<CustomField>
    <fullName>Contract_Type__c</fullName>
    <label>Contract Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Rental</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/ET_Sales_Agreement__c/fields/Customer_PO_No__c.field-meta.xml
<CustomField>
    <fullName>Customer_PO_No__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Customer PO No</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/ET_Sales_Agreement__c/fields/ETSales_Emirates__c.field-meta.xml
<CustomField>
    <fullName>ETSales_Emirates__c</fullName>
    <formula>Salesforce_Customer__r.Location__r.ETSALES_Emirates__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Emirates</label>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/ET_Sales_Agreement__c/fields/ETSALES_Opportunity__c.field-meta.xml
<CustomField>
    <fullName>ETSALES_Opportunity__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Sales Agreements</relationshipLabel>
    <relationshipName>Opportunities_Sales_Agreements</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/ET_Sales_Agreement__c/fields/ETSALES_Quote__c.field-meta.xml
<CustomField>
    <fullName>ETSALES_Quote__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Quote</label>
    <referenceTo>Quote</referenceTo>
    <relationshipLabel>Sales Agreements</relationshipLabel>
    <relationshipName>Sales_Agreements</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/ET_Sales_Agreement__c/fields/GL_Activity__c.field-meta.xml
<CustomField>
    <fullName>GL_Activity__c</fullName>
    <formula>ETSALES_Opportunity__r.GL_Activity__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Activity</label>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/ET_Sales_Agreement__c/fields/GL_Department__c.field-meta.xml
<CustomField>
    <fullName>GL_Department__c</fullName>
    <formula>ETSALES_Opportunity__r.GL_Department__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Department</label>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/ET_Sales_Agreement__c/fields/GL_Location__c.field-meta.xml
<CustomField>
    <fullName>GL_Location__c</fullName>
    <formula>ETSALES_Opportunity__r.GL_Location_Lookup__r.Name</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>GL Location</label>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/ET_Sales_Agreement__c/fields/GL_Project__c.field-meta.xml
<CustomField>
    <fullName>GL_Project__c</fullName>
    <formula>ETSALES_Opportunity__r.GL_Project__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Project</label>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/ET_Sales_Agreement__c/fields/GL_Region__c.field-meta.xml
<CustomField>
    <fullName>GL_Region__c</fullName>
    <formula>ETSALES_Opportunity__r.GL_Region__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Region</label>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/ET_Sales_Agreement__c/fields/GL_Zone__c.field-meta.xml
<CustomField>
    <fullName>GL_Zone__c</fullName>
    <formula>ETSALES_Opportunity__r.GL_Zone_Lookup__r.Name</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Zone</label>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/ET_Sales_Agreement__c/fields/No_of_Months__c.field-meta.xml
<CustomField>
    <fullName>No_of_Months__c</fullName>
    <label>No of Months</label>
    <precision>18</precision>
    <scale>4</scale>
    <type>Number</type>
</CustomField>

unpackaged/main/default/objects/ET_Sales_Agreement__c/fields/Other_Charges__c.field-meta.xml
<CustomField>
    <fullName>Other_Charges__c</fullName>
    <label>Other Charges</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

unpackaged/main/default/objects/ET_Sales_Agreement__c/fields/Premature_Charges__c.field-meta.xml
<CustomField>
    <fullName>Premature_Charges__c</fullName>
    <label>Premature Charges</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

unpackaged/main/default/objects/ET_Sales_Agreement__c/fields/Salesforce_Customer__c.field-meta.xml
<CustomField>
    <fullName>Salesforce_Customer__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Customer</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Sales Agreements</relationshipLabel>
    <relationshipName>Sales_Agreements</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Invoice__c/Invoice__c.object-meta.xml
<CustomObject>
    <label>Invoice</label>
    <nameField>
        <displayFormat>INV-{000000}</displayFormat>
        <label>Invoice No</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Invoices</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Invoice__c/fields/Account_Desc__c.field-meta.xml
<CustomField>
    <fullName>Account_Desc__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Account Desc</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

unpackaged/main/default/objects/Invoice__c/fields/Activity__c.field-meta.xml
<CustomField>
    <fullName>Activity__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Activity</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Invoice__c/fields/Batch_Source__c.field-meta.xml
<CustomField>
    <fullName>Batch_Source__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Batch Source</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Invoice__c/fields/Branch_Name__c.field-meta.xml
<CustomField>
    <fullName>Branch_Name__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Branch Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Invoice__c/fields/Complete_Flag__c.field-meta.xml
<CustomField>
    <fullName>Complete_Flag__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Complete Flag</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/objects/Invoice__c/fields/Contract_Name__c.field-meta.xml
<CustomField>
    <fullName>Contract_Name__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Contract Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Invoice__c/fields/Contract_No__c.field-meta.xml
<CustomField>
    <fullName>Contract_No__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Contract No</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Invoice__c/fields/Created_By__c.field-meta.xml
<CustomField>
    <fullName>Created_By__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Created By</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Invoice__c/fields/Customer__c.field-meta.xml
<CustomField>
    <fullName>Customer__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Customer</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Invoices</relationshipLabel>
    <relationshipName>Invoices</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Invoice__c/fields/Department__c.field-meta.xml
<CustomField>
    <fullName>Department__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Department</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Invoice__c/fields/Estimation__c.field-meta.xml
<CustomField>
    <fullName>Estimation__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Estimation</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Invoice__c/fields/Project__c.field-meta.xml
<CustomField>
    <fullName>Project__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Project</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Invoice__c/fields/Sales_Agreement__c.field-meta.xml
<CustomField>
    <fullName>Sales_Agreement__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Sales Agreement</label>
    <referenceTo>ET_Sales_Agreement__c</referenceTo>
    <relationshipLabel>Invoices</relationshipLabel>
    <relationshipName>Invoices</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Invoice__c/fields/Zone__c.field-meta.xml
<CustomField>
    <fullName>Zone__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Zone</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/classes/ET_FederalB2BController.cls
public class ET_FederalB2BController {
    public class MyBusinessWrapper{
        @AuraEnabled public List<ET_Sales_Agreement__c> salesAgreementList;
        @AuraEnabled public List<Invoice__c> invoicesList;
        @AuraEnabled public List<Estimation__c> estList;
        public MyBusinessWrapper(){
            salesAgreementList = new List<ET_Sales_Agreement__c>();
            invoicesList = new List<Invoice__c>();
            estList = new List<Estimation__c>();
            
        }
    }
    @AuraEnabled
    public static schoolWrapper getDashboardData() {
        schoolWrapper dashboardWrap=new schoolWrapper();
        try{
            User u = [select id, AccountId,contactId from User where id = : userInfo.getUserId()];
            dashboardWrap.salesCount=[select count() from ET_Sales_Agreement__c 
                                      where Salesforce_Customer__c=:u.AccountId];
            dashboardWrap.invCount=[select count() from Invoice__c 
                                    where Sales_Agreement__r.Salesforce_Customer__c=:u.AccountId];
            dashboardWrap.estCount=[select count() from Estimation__c where Account__c=:u.AccountId];
            
           return   dashboardWrap;   
        }    
        catch (Exception ex) {
            System.debug(ex.getMessage());
            return null;
            
        }
    }
    
    public class schoolWrapper{ 
        @AuraEnabled public Integer salesCount=0; 
        @AuraEnabled public Integer invCount=0; 
        @AuraEnabled public Integer estCount=0; 
        
    }
    
   @AuraEnabled
    public static List<Estimation__c> getEstimationsList(){
        List<Estimation__c> estlist=new List<Estimation__c>();
        User u = [select id, AccountId,contactId from User where id = : userInfo.getUserId()];
        Account Acc=[select id,Name from Account where Id=:u.AccountId];  
         estlist= [select Id, Name,Account__r.Name,Service_Center__c
                                              from Estimation__c where Account__c=:u.AccountId]; 
         
        return estlist;
    }
    
   @AuraEnabled
    public static List<ET_Sales_Agreement__c> getSAList(){
         List<ET_Sales_Agreement__c> SAlist=new List<ET_Sales_Agreement__c>(); 
         User u = [select id, AccountId,contactId from User where id = : userInfo.getUserId()];
         Account Acc=[select id,Name from Account where Id=:u.AccountId];  
         
         SAlist=[select Id,Name,Salesforce_Customer__r.Name,  Activity__c, Administration_Charges__c,
                                             Contract_End_Date__c, Contract_No__c, Contract_Start_Date__c, Contract_Status__c, Contract_Type__c, 
                                             Customer_PO_No__c, Customer__c, ETSales_Emirates__c, No_of_Months__c, Other_Charges__c, Premature_Charges__c,
                                             Salesforce_Customer__c, Version__c, ETSALES_Quote__c, ETSALES_Opportunity__c, GL_Activity__c, 
                                             GL_Department__c, GL_Project__c, GL_Location__c, GL_Region__c, GL_Zone__c
                                             from ET_Sales_Agreement__c where Salesforce_Customer__c=:u.AccountId];
        
        return SAlist;
    }
    @AuraEnabled
    public static List<Invoice__c> getInvoiceListHelper(){
        User u = [select id, AccountId,contactId from User where id = : userInfo.getUserId()];
        
        return [select Id, Name,Sales_Agreement__r.Name, Account_Desc__c, Activity__c, Batch_Source__c, Branch_Name__c,
                                       Complete_Flag__c, Contract_End_Date__c, Contract_Name__c, Contract_Start_Date__c, Created_By__c, CreationDate__c, Ct_Reference__c,
                                       Customer_Invoice_No__c, Customer_Number__c, Customer__c, Department__c, Description__c, Dist_Account__c, ETST_Active__c,
                                       ETST_Bank_Name__c, ETST_Cheque__c, ETST_Coordinator__c, ETST_Courier_Name__c, ETST_Courier__c, ETST_Submitted_By__c,
                                       ETST_Type__c, FromDate__c, Gl_Date__c, Gl_Posted_Date__c, InternalBillNumber__c, Last_Update_By__c, Last_Update_Date__c,
                                       Location__c, Operating_Unit__c, Party_Name__c, Payment_Status__c, Project__c, Ref_Number__c, Ref_Trans_Type__c, Sales_Agreement__c,
                                       Service_Request__c, ToDate__c, Total_Inv_Amount__c, Transaction_Class__c, Transaction_Type__c, Trx_Date__c,
                                       Trx_Number__c, Voucher_Number__c, Zone__c
                                       from Invoice__c where Sales_Agreement__r.Salesforce_Customer__c=:u.AccountId];
    }
    
   

}