unpackaged/main/default/objects/Account/fields/Integration_Message__c.field-meta.xml
<CustomField>
    <fullName>Integration_Message__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Integration Message</label>
    <length>100000</length>
    <type>LongTextArea</type>
</CustomField>

unpackaged/main/default/objects/Account/fields/Integration_Status__c.field-meta.xml
<CustomField>
    <fullName>Integration_Status__c</fullName>
    <label>Integration Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Integration_Status_Value_Set</valueSetName>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Arkani_API_Credentials__mdt/Arkani_API_Credentials__mdt.object-meta.xml
<CustomObject>
    <label>Arkani API Credential</label>
    <pluralLabel>Arkani API Credentials</pluralLabel>
</CustomObject>

unpackaged/main/default/objects/ETSALES_Account_Sites__c/ETSALES_Account_Sites__c.object-meta.xml
<CustomObject>
    <label>Account Site</label>
    <nameField>
        <displayFormat>Site-{0000}</displayFormat>
        <label>Account Site Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Account Sites</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

unpackaged/main/default/objects/ETSALES_Account_Sites__c/fields/ETSALES_Address__c.field-meta.xml
<CustomField>
    <fullName>ETSALES_Address__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Address</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>ETSALES_Address__c.ETSALES_Account__c</field>
            <operation>equals</operation>
            <valueField>$Source.ETSALES_Account__c</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>ETSALES_Address__c</referenceTo>
    <relationshipLabel>Account Sites</relationshipLabel>
    <relationshipName>Operating_Unit_Address</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/ETSALES_Account_Sites__c/fields/ETSALES_Business_Purpose__c.field-meta.xml
<CustomField>
    <fullName>ETSALES_Business_Purpose__c</fullName>
    <label>Business Purpose</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>BILL_TO</fullName>
                <default>true</default>
                <label>Bill To</label>
            </value>
            <value>
                <fullName>SHIP_TO</fullName>
                <label>Ship To</label>
            </value>
            <value>
                <fullName>INV</fullName>
            </value>
            <value>
                <fullName>CREDIT_CONTACT</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/ETSALES_Account_Sites__c/fields/ETSALES_Overall_Credit_Limit__c.field-meta.xml
<CustomField>
    <fullName>ETSALES_Overall_Credit_Limit__c</fullName>
    <label>Overall Credit Limit</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

unpackaged/main/default/objects/ETSALES_Account_Sites__c/fields/ETSALES_Party_Site_Id__c.field-meta.xml
<CustomField>
    <fullName>ETSALES_Party_Site_Id__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Party Site Id</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/ETSALES_Account_Sites__c/fields/ETSALES_Party_Site_Number__c.field-meta.xml
<CustomField>
    <fullName>ETSALES_Party_Site_Number__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Party Site Number</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/ETSALES_Account_Sites__c/fields/ETSALES_Site_Profile_Class__c.field-meta.xml
<CustomField>
    <fullName>ETSALES_Site_Profile_Class__c</fullName>
    <label>Site Profile Class</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Individual</fullName>
            </value>
            <value>
                <fullName>Private</fullName>
            </value>
            <value>
                <fullName>Government</fullName>
            </value>
            <value>
                <fullName>DEFAULT</fullName>
            </value>
            <value>
                <fullName>Ministries</fullName>
            </value>
            <value>
                <fullName>Semi Government</fullName>
            </value>
            <value>
                <fullName>Federal Government</fullName>
            </value>
            <value>
                <fullName>Student</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/ETSALES_Account_Sites__c/fields/ETSALES_Site_Use_Id__c.field-meta.xml
<CustomField>
    <fullName>ETSALES_Site_Use_Id__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <externalId>true</externalId>
    <label>Site Use Id</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/ETSALES_Account_Sites__c/fields/Location_ID__c.field-meta.xml
<CustomField>
    <fullName>Location_ID__c</fullName>
    <formula>ETSALES_Address__r.ETSALES_Location_ID__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Location ID</label>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/ETSALES_Account_Sites__c/fields/Operation_Manager__c.field-meta.xml
<CustomField>
    <fullName>Operation_Manager__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Operation Manager</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Account_Sites</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/ETSALES_Account_Sites__c/fields/Oracle_Account_ID__c.field-meta.xml
<CustomField>
    <fullName>Oracle_Account_ID__c</fullName>
    <formula>ETSALES_Account__r.ETSALES_Customer_Account_Id__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Oracle Account ID</label>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/ETSALES_Account_Sites__c/fields/Organization_ID__c.field-meta.xml
<CustomField>
    <fullName>Organization_ID__c</fullName>
    <formula>Text( ETSALES_Operating_unit__r.ETSALES_Organization_Id__c )</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Organization ID</label>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/ETSALES_Address__c/ETSALES_Address__c.object-meta.xml
<CustomObject>
    <label>Customer Address</label>
    <nameField>
        <displayFormat>Add-{0000}</displayFormat>
        <label>Address Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Addresses</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

unpackaged/main/default/objects/ETSALES_Address__c/fields/ETSALES_Party_Site_Id__c.field-meta.xml
<CustomField>
    <fullName>ETSALES_Party_Site_Id__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Party Site Id</label>
    <length>200</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/ETSALES_Address__c/fields/ETSALES_Party_Site_Number__c.field-meta.xml
<CustomField>
    <fullName>ETSALES_Party_Site_Number__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <externalId>true</externalId>
    <label>Party Site Number</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/ETSALES_Address__c/fields/Integration_Message__c.field-meta.xml
<CustomField>
    <fullName>Integration_Message__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Integration Message</label>
    <length>130000</length>
    <type>LongTextArea</type>
</CustomField>

unpackaged/main/default/objects/ETSALES_Address__c/fields/Integration_Status__c.field-meta.xml
<CustomField>
    <fullName>Integration_Status__c</fullName>
    <label>Integration Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Success</fullName>
            </value>
            <value>
                <fullName>Failed</fullName>
            </value>
            <value>
                <fullName>In Progress</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/globalValueSets/Integration_Status_Value_Set.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>In Progress</fullName>
    </customValue>
    <customValue>
        <fullName>Success</fullName>
    </customValue>
    <customValue>
        <fullName>Failed</fullName>
    </customValue>
    <customValue>
        <fullName>Error</fullName>
    </customValue>
    <masterLabel>Integration Status Value Set</masterLabel>
</GlobalValueSet>

unpackaged/main/default/classes/Account_Site_Syn_from_Batch.cls
global class Account_Site_Syn_from_Batch implements Database.Batchable<sObject>,   Database.AllowsCallouts {

 public Set<Id> addressIds  ;  
 public  Account_Site_Syn_from_Batch(Set<Id> addressIds)
 {
     this.addressIds = addressIds;
 }
 public String query  = 'Select id,Organization_ID__c,Location_ID__c,Oracle_Account_ID__c,ETSALES_Business_Purpose__c,'+
  			            'ETSALES_Site_Profile_Class__c,Operation_Manager__c,ETSALES_Overall_Credit_Limit__c,'+
              			'ETSALES_Party_Site_Id__c,ETSALES_Party_Site_Number__c from ETSALES_Account_Sites__c '+
             			 'where ETSALES_Address__c IN:addressIds AND  '+
                         '(ETSALES_Party_Site_Number__c=null OR ETSALES_Site_Use_Id__c=null )';
    global Database.QueryLocator start(Database.BatchableContext BC) {
     //   addressIds = new Set<Id>();
    return Database.getQueryLocator(query);
 }

     global void execute(Database.BatchableContext BC, List<ETSALES_Account_Sites__c> records) {         
        String endpoint;        

        for (ETSALES_Account_Sites__c siteObj: records){
         try {                  
        System.debug('Inside accountsite function');
            String OracleIntegrationMessage = '';                   
            
            String CustAccountId = (siteObj.Oracle_Account_ID__c!=null)?(''+siteObj.Oracle_Account_ID__c+''):null;
            String Org_id = (siteObj.Organization_ID__c!=null)?(''+siteObj.Organization_ID__c+''):null;
            String LocationId =(siteObj.Location_ID__c!=null)?(''+siteObj.Location_ID__c+''):null;
            String BusinessPurpose = (siteObj.ETSALES_Business_Purpose__c!=null)?('"'+siteObj.ETSALES_Business_Purpose__c+'"'):null;
            String ProfileClass = null;
            String AccountManager =null;       
            String PaymentTerm =null;       
            String CreditLimit = (siteObj.ETSALES_Overall_Credit_Limit__c!=null)?(''+siteObj.ETSALES_Overall_Credit_Limit__c+''):null;
            String PaymentTermId =null;           
            String SiteUseId = null;           
            
            String SFDC_ID = (siteObj.id!=null)?('"'+siteObj.id+'"'):null;
            
            
            
            String body ='';
            
            HttpRequest request = new HttpRequest();
            
            body = '{"CustAccountId":'+CustAccountId+',"Org_id":'+Org_id+','+
                '"LocationId":'+LocationId+','+'"BusinessPurpose":'+BusinessPurpose+','+
                '"ProfileClass":'+ProfileClass+','+'"AccountManager":'+AccountManager+','+
                '"PaymentTerm":'+PaymentTerm+','+'"CreditLimit":'+CreditLimit+','+
                '"PaymentTermId":'+PaymentTermId+','+'"SiteUseId":'+SiteUseId+','+'"SFDC_ID":'+SFDC_ID+ '}';
            
            
            System.debug('body='+body);
            
            
            request= Oracle_Integration_Services.createRequest('POST', '/soa-infra/resources/SalesForceIntegration/ArkanCustomerAPI/ArkanCustomerApiRest/Site');		
            request.setBody(body);  
            request.setTimeout(120000);
               Arkani_API_Credentials__mdt	credentialsMetadata=[Select Password__c,UserName__c from Arkani_API_Credentials__mdt where DeveloperName = 'Arkani_Credential'];                 
            //String Username = 'Salesforce';
            //String password = 'salesforce123';
                String Username = credentialsMetadata.UserName__c;
              String password = credentialsMetadata.Password__c;    
            
            String combined = Username+':'+password;
            Blob beforeblob = Blob.valueOf(combined);
            
            string base64Key = EncodingUtil.base64Encode(beforeblob);
            System.debug('paramvalue='+base64Key);
            String AuthroizationValue = 'Basic '+base64Key;
            request.setHeader('Authorization', AuthroizationValue);   
            Map<String, Object> responseResult =new Map<String, Object>();
            Http http = new Http();
            HttpResponse response = http.send(request);
            
            System.debug('response body='+response.getBody());
            if (response.getStatusCode() != 200) {
                
                System.debug('Failed ');
                responseResult = null;             
                
            }
            else{
                if(response.getStatusCode() == 200){
                    System.debug('Sucess ');
                    Map<String, Object> result = (Map<String, Object>)JSON.deserializeUntyped(response.getBody());
                    responseResult =result;
                }
                
            }
            if(responseResult!=null)
            {
                String ResponseMessage =(String)responseResult.get('Message');
                String ResponseStatus =(String)responseResult.get('Status');
                System.debug('ResponseStatus='+ResponseStatus);
                System.debug('ResponseMessage='+ResponseMessage);
                if(ResponseStatus.contains('S'))
                {
                    OracleIntegrationMessage = ResponseMessage;
                    if(ResponseMessage==null||ResponseMessage=='')
                    {
                        OracleIntegrationMessage = 'Customer Account Site is successfully integrated with Oracle.';
                    }
                    Integer respSiteUseId =0;       
                    Integer respPartySiteNumber =0;   
                    try{
                         respSiteUseId =(Integer)responseResult.get('SiteUseId');    
                    }catch(Exception e){}
                        try{
                       respPartySiteNumber =(Integer)responseResult.get('PartySiteNumber');    
                    }catch(Exception e){}
                   
                    if(respSiteUseId!=0||respPartySiteNumber!=0)
                    {
                   
                        siteObj.ETSALES_Site_Use_Id__c	 = String.valueOf(respSiteUseId);  
                        siteObj.ETSALES_Party_Site_Number__c = String.valueOf(respPartySiteNumber);  
                        siteObj.Integration_Status__c = 'Success';
                        //   update acc;
                    }
                    else
                    {
                        siteObj.Integration_Status__c = 'Failed';
                         OracleIntegrationMessage = 'Unable to retrieve SiteUseId and PartySiteNumber from Response.';
                    }
                    
                }
                else
                {
                    siteObj.Integration_Status__c = 'Failed';
                    OracleIntegrationMessage = ResponseMessage;
                }
                
            }
            else{
                Integer statuscode = response.getStatusCode();
                String ErrorMessage = 'Status Code = '+statuscode+' ,'+ 'Error Message = '+response.getBody();
                OracleIntegrationMessage = ErrorMessage;
                siteObj.Integration_Status__c = 'Failed';
            }
            
            
            if(OracleIntegrationMessage!='')
            {
                //   System.debug('acc.Integration_Message__c='+siteObj.Integration_Message__c);
                System.debug('acc.ETSALES_Party_Site_Id__c='+siteObj.ETSALES_Party_Site_Id__c);
                System.debug('acc.ETSALES_Party_Site_Number__c='+siteObj.ETSALES_Party_Site_Number__c);
                System.debug('acc.Integration_Satus__c='+siteObj.Integration_Status__c);
                
                siteObj.Integration_Message__c = OracleIntegrationMessage;
                update siteObj;
                System.debug('update successgull='+siteObj);
            }          
          }
          catch (Exception e) {         
            System.debug('Error:' + e.getMessage() + 'LN:' + e.getLineNumber() );           
          }
       }
    }   

    global void finish(Database.BatchableContext BC){    
        System.debug('finsh block of Account Site');
    }

}