unpackaged/main/default/objects/Account/fields/Integration_Message__c.field-meta.xml
<CustomField>
    <fullName>Integration_Message__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Integration Message</label>
    <length>100000</length>
    <type>LongTextArea</type>
</CustomField>

unpackaged/main/default/objects/Account/fields/Integration_Status__c.field-meta.xml
<CustomField>
    <fullName>Integration_Status__c</fullName>
    <label>Integration Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Integration_Status_Value_Set</valueSetName>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Arkani_API_Credentials__mdt/Arkani_API_Credentials__mdt.object-meta.xml
<CustomObject>
    <label>Arkani API Credential</label>
    <pluralLabel>Arkani API Credentials</pluralLabel>
</CustomObject>

unpackaged/main/default/objects/ETSALES_Address__c/ETSALES_Address__c.object-meta.xml
<CustomObject>
    <label>Customer Address</label>
    <nameField>
        <displayFormat>Add-{0000}</displayFormat>
        <label>Address Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Addresses</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

unpackaged/main/default/objects/ETSALES_Address__c/fields/ETSALES_Account__c.field-meta.xml
<CustomField>
    <fullName>ETSALES_Account__c</fullName>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Addresses</relationshipLabel>
    <relationshipName>Addresses1</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

unpackaged/main/default/objects/ETSALES_Address__c/fields/ETSALES_Address1__c.field-meta.xml
<CustomField>
    <fullName>ETSALES_Address1__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Address1</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/ETSALES_Address__c/fields/ETSALES_Address2__c.field-meta.xml
<CustomField>
    <fullName>ETSALES_Address2__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Address2</label>
    <length>200</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/ETSALES_Address__c/fields/ETSALES_Address3__c.field-meta.xml
<CustomField>
    <fullName>ETSALES_Address3__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Address3</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/ETSALES_Address__c/fields/ETSALES_Address4__c.field-meta.xml
<CustomField>
    <fullName>ETSALES_Address4__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Address4</label>
    <length>200</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/ETSALES_Address__c/fields/ETSALES_City__c.field-meta.xml
<CustomField>
    <fullName>ETSALES_City__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>City</label>
    <length>200</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/ETSALES_Address__c/fields/ETSALES_Country__c.field-meta.xml
<CustomField>
    <fullName>ETSALES_Country__c</fullName>
    <label>Country</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>AD</fullName>
                <label>Andorra</label>
            </value>
            <value>
                <fullName>AE</fullName>
                <default>true</default>
                <label>United Arab Emirates</label>
            </value>
            <value>
                <fullName>AF</fullName>
                <label>Afghanistan</label>
            </value>
            <value>
                <fullName>AG</fullName>
                <label>Antigua and Barbuda</label>
            </value>
            <value>
                <fullName>AI</fullName>
                <label>Anguilla</label>
            </value>
            <value>
                <fullName>AL</fullName>
                <label>Albania</label>
            </value>
            <value>
                <fullName>AM</fullName>
                <label>Armenia</label>
            </value>
            <value>
                <fullName>AN</fullName>
                <label>Netherlands Antilles</label>
            </value>
            <value>
                <fullName>AO</fullName>
                <label>Angola</label>
            </value>
            <value>
                <fullName>AQ</fullName>
                <label>Antarctica</label>
            </value>
            <value>
                <fullName>AR</fullName>
                <label>Argentina</label>
            </value>
            <value>
                <fullName>AS</fullName>
                <label>American Samoa</label>
            </value>
            <value>
                <fullName>AT</fullName>
                <label>Austria</label>
            </value>
            <value>
                <fullName>AU</fullName>
                <label>Australia</label>
            </value>
            <value>
                <fullName>AW</fullName>
                <label>Aruba</label>
            </value>
            <value>
                <fullName>AZ</fullName>
                <label>Azerbaijan</label>
            </value>
            <value>
                <fullName>BA</fullName>
                <label>Bosnia and Herzegovina</label>
            </value>
            <value>
                <fullName>BB</fullName>
                <label>Barbados</label>
            </value>
            <value>
                <fullName>BD</fullName>
                <label>Bangladesh</label>
            </value>
            <value>
                <fullName>BE</fullName>
                <label>Belgium</label>
            </value>
            <value>
                <fullName>BF</fullName>
                <label>Burkina Faso</label>
            </value>
            <value>
                <fullName>BG</fullName>
                <label>Bulgaria</label>
            </value>
            <value>
                <fullName>BH</fullName>
                <label>Bahrain</label>
            </value>
            <value>
                <fullName>BI</fullName>
                <label>Burundi</label>
            </value>
            <value>
                <fullName>BJ</fullName>
                <label>Benin</label>
            </value>
            <value>
                <fullName>BM</fullName>
                <label>Bermuda</label>
            </value>
            <value>
                <fullName>BN</fullName>
                <label>Brunei Darussalam</label>
            </value>
            <value>
                <fullName>BO</fullName>
                <label>Bolivia</label>
            </value>
            <value>
                <fullName>BR</fullName>
                <label>Brazil</label>
            </value>
            <value>
                <fullName>BS</fullName>
                <label>Bahamas</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/ETSALES_Address__c/fields/ETSALES_Location_ID__c.field-meta.xml
<CustomField>
    <fullName>ETSALES_Location_ID__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Location ID</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/ETSALES_Address__c/fields/ETSALES_State__c.field-meta.xml
<CustomField>
    <fullName>ETSALES_State__c</fullName>
    <label>State</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>DUBAI</fullName>
            </value>
            <value>
                <fullName>ABU DHABI</fullName>
            </value>
            <value>
                <fullName>SHARJAH</fullName>
            </value>
            <value>
                <fullName>RAS AL KHAIMAH</fullName>
            </value>
            <value>
                <fullName>FUJAIRAH</fullName>
            </value>
            <value>
                <fullName>UMM AL QUWAIN</fullName>
                <label>Umm Al Quwain</label>
            </value>
            <value>
                <fullName>AJMAN</fullName>
                <label>Ajman</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/ETSALES_Address__c/fields/Integration_Message__c.field-meta.xml
<CustomField>
    <fullName>Integration_Message__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Integration Message</label>
    <length>130000</length>
    <type>LongTextArea</type>
</CustomField>

unpackaged/main/default/objects/ETSALES_Address__c/fields/Integration_Status__c.field-meta.xml
<CustomField>
    <fullName>Integration_Status__c</fullName>
    <label>Integration Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Success</fullName>
            </value>
            <value>
                <fullName>Failed</fullName>
            </value>
            <value>
                <fullName>In Progress</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/ETSALES_Address__c/fields/Postal_code__c.field-meta.xml
<CustomField>
    <fullName>Postal_code__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Postal code</label>
    <length>200</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Integration_Log__c/Integration_Log__c.object-meta.xml
<CustomObject>
    <description>This object is used for logging all web service calls made into salesforce from external systems.</description>
    <label>Integration Log</label>
    <nameField>
        <displayFormat>INT-{000000}</displayFormat>
        <label>Integration Log Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Integration Logs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Integration_Log__c/fields/Integration_Type__c.field-meta.xml
<CustomField>
    <fullName>Integration_Type__c</fullName>
    <label>Integration Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>INBOUND</fullName>
            </value>
            <value>
                <fullName>OUTBOUND</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Integration_Log__c/fields/Json_Response__c.field-meta.xml
<CustomField>
    <fullName>Json_Response__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Json Response</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

unpackaged/main/default/objects/Integration_Log__c/fields/Process_Name__c.field-meta.xml
<CustomField>
    <fullName>Process_Name__c</fullName>
    <description>The name of the process (if required) which results in a web service invocation (in bound or outbound)</description>
    <encryptionScheme>None</encryptionScheme>
    <label>Process Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Integration_Log__c/fields/Source_System__c.field-meta.xml
<CustomField>
    <fullName>Source_System__c</fullName>
    <description>Name  of the source system that is making the inbound web service call to salesforce.</description>
    <encryptionScheme>None</encryptionScheme>
    <label>Source System</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Integration_Log__c/fields/Target_System__c.field-meta.xml
<CustomField>
    <fullName>Target_System__c</fullName>
    <description>The name of the target system for any outbound calls from salesforce.</description>
    <encryptionScheme>None</encryptionScheme>
    <label>Target System</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Integration_Log__c/recordTypes/OUTBOUND.recordType-meta.xml
<RecordType>
    <fullName>OUTBOUND</fullName>
    <active>true</active>
    <description>Record Type for any outbound web service calls</description>
    <label>OUTBOUND</label>
</RecordType>

unpackaged/main/default/globalValueSets/Integration_Status_Value_Set.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>In Progress</fullName>
    </customValue>
    <customValue>
        <fullName>Success</fullName>
    </customValue>
    <customValue>
        <fullName>Failed</fullName>
    </customValue>
    <customValue>
        <fullName>Error</fullName>
    </customValue>
    <masterLabel>Integration Status Value Set</masterLabel>
</GlobalValueSet>

unpackaged/main/default/classes/Address_SendToERPQueueableCtrl.cls
/**
Author: Janardhan Muddana
Test Class: Account_SendToERP_Test
----------------------------------------------------------------------------------------------------------------
            -- History --
----------------------------------------------------------------------------------------------------------------
Sr.No.  version_DevInitials     Date     Author           Details
1.          V1.0                         Janardhan	    Initial Version 
2.          v2.0			17/04/2023   Janardhan    	logic is implemented to handle mutiple addresss
****************************************************************************************************************/

public class Address_SendToERPQueueableCtrl implements Queueable,Database.AllowsCallouts{
    
    public Id accID;
    public string ERPAccId;
    
    public Address_SendToERPQueueableCtrl(Id AccountId,string ERPAccId){
        this.accID=AccountId;
        this.ERPAccId = ERPAccId;
    }
    
    
    public void execute(QueueableContext con){        
        
        List<ETSALES_Address__c> addressObjList = [Select id,ETSALES_Address1__c,ETSALES_Address2__c,
                                                   ETSALES_Address3__c,ETSALES_Address4__c,ETSALES_City__c,ETSALES_Country__c,Oracle_Account_ID__c,
                                                   ETSALES_Location_ID__c,Postal_code__c,ETSALES_State__c,Integration_Message__c,Integration_Status__c
                                                   from ETSALES_Address__c where ETSALES_Account__c =:accID];  
      
        for(ETSALES_Address__c addr : addressObjList){
            
            String CountryName=''; 
            if(addr.ETSALES_Country__c!=null) {
                String CountryCode = addr.ETSALES_Country__c;
                
                Schema.sObjectType objType = ETSALES_Address__c.getSObjectType();
                Schema.DescribeSObjectResult objDescribe = objType.getDescribe();
                map < String, Schema.SObjectField > fieldMap = objDescribe.fields.getMap();
                list < Schema.PicklistEntry > values = fieldMap.get('ETSALES_Country__c').getDescribe().getPickListValues();
                
                for (Schema.PicklistEntry a: values) {
                    if(a.getValue()==CountryCode)
                    {
                        CountryName = a.getLabel();
                        break;
                    }                    
                }                
            }   
            createAddressInERP(accID,ERPAccId,addr.ETSALES_Address1__c,addr.ETSALES_Address2__c,addr.ETSALES_Address3__c,addr.ETSALES_Address4__c,addr.ETSALES_City__c,addr.ETSALES_State__c,addr.Postal_code__c,CountryName,addr.id,addr.ETSALES_Location_ID__c);
            
        }
       
    }
    
    @Future(callout=true)
    public static void createAddressInERP(string accID,string ERPAccId,string Add1,string Add2,string Add3,string Add4,string cityVal,string stateVal,string psCode,string countryName,string addId,string locId){       
             
            
            String CustAccountId = ERPAccId;//(addressObj[0].Oracle_Account_ID__c!=null)?(''+addressObj[0].Oracle_Account_ID__c+''):null;
            String Address1 = (Add1!=null)?('"'+Add1+'"'):null;
            String Address2 =(Add2!=null)?('"'+Add2+'"'):null;
            String Address3 = (Add3!=null)?('"'+Add3+'"'):null;
            String Address4 = (Add4!=null)?('"'+Add4+'"'):null;
            String City = (cityVal!=null)?('"'+cityVal+'"'):null;       
            String State = (stateVal!=null)?('"'+stateVal+'"'):null;       
            String PostalCode = (psCode!=null)?('"'+psCode+'"'):null;
            String Country = (countryName!='')?('"'+countryName+'"'):null;       
            String SFDC_ID = (addId!=null)?('"'+addId+'"'):null;
            String LocationId = locId!=null ?('"'+locId+'"'):null;
            
            
            String body ='';
            
            ETSALES_Address__c addUpdate = new ETSALES_Address__c();
            addUpdate.Id = addId;
            HttpRequest request = new HttpRequest();
            
            body = '{"CustAccountId":'+CustAccountId+',"Address1":'+Address1+','+
                '"Address2":'+Address2+','+'"Address3":'+Address3+','+
                '"Address4":'+Address4+','+'"City":'+City+','+
                '"State":'+State+','+'"PostalCode":'+PostalCode+','+
                '"Country":'+Country+','+'"SFDC_ID":'+SFDC_ID+','+
                '"LocationId":'+LocationId+ '}';
            
            
            System.debug('body='+body);
            
            request.setEndpoint(Label.ETSOA_End_Point +'/soa-infra/resources/SalesForceIntegration/ArkanCustomerAPI/ArkanCustomerApiRest/Location');
            request.setMethod('POST');
            request.setTimeout(120000);
            request.setHeader('Content-Type', 'application/json');
            request.setBody(body);  
            
            Arkani_API_Credentials__mdt	credentialsMetadata=[Select Password__c,UserName__c from Arkani_API_Credentials__mdt where DeveloperName = 'Arkani_Credential'];                 
            String Username = credentialsMetadata.UserName__c;
            String password = credentialsMetadata.Password__c;    
            
            String combined = Username+':'+password;
            Blob beforeblob = Blob.valueOf(combined);
            
            string base64Key = EncodingUtil.base64Encode(beforeblob);
            System.debug('paramvalue='+base64Key);
            String AuthroizationValue = 'Basic '+base64Key;
            request.setHeader('Authorization', AuthroizationValue);   
            Map<String, Object> responseResult =new Map<String, Object>();
            Http http = new Http();
            HttpResponse response = http.send(request);
            
            System.debug('response body='+response.getBody());
            if (response.getStatusCode() != 200) {
                
                System.debug('Failed ');
                Integration_Log__c log = new Integration_Log__c();
                log.Process_Name__c	='Send Account Site to ERP';
                log.Integration_Type__c ='OUTBOUND';
                log.Source_System__c ='Salesforce';
                log.Target_System__c ='Oracle';
                log.Json_Response__c =response.getBody();
                insert log;
                responseResult = null;             
                addUpdate.Integration_Status__c ='Failed';
            }
            else{
                if(response.getStatusCode() == 200){
                    System.debug('Sucess ');
                    Map<String, Object> result = (Map<String, Object>)JSON.deserializeUntyped(response.getBody());
                    responseResult =result;
                    system.debug('--res--'+result);
                }
                
            }
            if(responseResult!=null)
            {
                String ResponseMessage =(String)responseResult.get('Message');
                String ResponseStatus =(String)responseResult.get('Status');
                System.debug('ResponseStatus='+ResponseStatus);
                System.debug('ResponseMessage='+ResponseMessage);
                if(ResponseStatus.contains('S'))
                {
                    
                    addUpdate.ETSALES_Location_ID__c =(String)responseResult.get('LocationId');      
                    addUpdate.Integration_Status__c ='Success';
                    if(!test.isRunningTest())
                        system.enqueueJob(new AccountSite_SendToERPQueueableCtrl(accID,ERPAccId,addUpdate.ETSALES_Location_ID__c)); 
                }
            }
           
            update addUpdate;
        }
      
}