unpackaged/main/default/objects/Account/fields/Integration_Message__c.field-meta.xml
<CustomField>
    <fullName>Integration_Message__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Integration Message</label>
    <length>100000</length>
    <type>LongTextArea</type>
</CustomField>

unpackaged/main/default/objects/Account/fields/Integration_Status__c.field-meta.xml
<CustomField>
    <fullName>Integration_Status__c</fullName>
    <label>Integration Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Integration_Status_Value_Set</valueSetName>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/CICO_Workshop_Location__c/CICO_Workshop_Location__c.object-meta.xml
<CustomObject>
    <label>ET Workshop Location</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Location Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>ET Workshop Location</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/CICO_Workshop_Location__c/fields/Location_Code__c.field-meta.xml
<CustomField>
    <fullName>Location_Code__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Location Code</label>
    <length>25</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/ET_Customer_Vehicle__c/ET_Customer_Vehicle__c.object-meta.xml
<CustomObject>
    <label>Customer Vehicle</label>
    <nameField>
        <displayFormat>CV-{000000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Customer Vehicles</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/ET_Customer_Vehicle__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Customer Vehicles</relationshipLabel>
    <relationshipName>Customer_Vehicles</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/ET_Customer_Vehicle__c/fields/Integration_Message__c.field-meta.xml
<CustomField>
    <fullName>Integration_Message__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Integration Message</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

unpackaged/main/default/objects/ET_Customer_Vehicle__c/fields/Internal_No__c.field-meta.xml
<CustomField>
    <fullName>Internal_No__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <externalId>true</externalId>
    <label>Internal No</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/ET_Oracle_REST_Endpoints__mdt/ET_Oracle_REST_Endpoints__mdt.object-meta.xml
<CustomObject>
    <description>This meta data created to store all the REST endpoint and authentication details</description>
    <label>ET_Oracle_REST_Endpoint</label>
    <pluralLabel>ET_Oracle_REST_Endpoints</pluralLabel>
</CustomObject>

unpackaged/main/default/objects/ET_Oracle_REST_Endpoints__mdt/fields/Dev_Endpoint__c.field-meta.xml
<CustomField>
    <fullName>Dev_Endpoint__c</fullName>
    <label>Dev Endpoint</label>
    <type>Url</type>
</CustomField>

unpackaged/main/default/objects/ET_Oracle_REST_Endpoints__mdt/fields/LiveEndpoint_c__c.field-meta.xml
<CustomField>
    <fullName>LiveEndpoint_c__c</fullName>
    <label>Live Endpoint</label>
    <type>Url</type>
</CustomField>

unpackaged/main/default/objects/Fleet_Service_Request__c/Fleet_Service_Request__c.object-meta.xml
<CustomObject>
    <label>Fleet Service Request</label>
    <nameField>
        <displayFormat>FSR - {00000}</displayFormat>
        <label>Request Ref. No.</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Fleet Service Requests</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Fleet_Service_Request__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Fleet Service Requests</relationshipLabel>
    <relationshipName>Fleet_Service_Requests</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Fleet_Service_Request__c/fields/Customer_Vehicle__c.field-meta.xml
<CustomField>
    <fullName>Customer_Vehicle__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Customer Vehicle</label>
    <referenceTo>ET_Customer_Vehicle__c</referenceTo>
    <relationshipLabel>Fleet Service Requests</relationshipLabel>
    <relationshipName>Fleet_Service_Requests</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Fleet_Service_Request__c/fields/Integration_Message__c.field-meta.xml
<CustomField>
    <fullName>Integration_Message__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Integration Message</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Fleet_Service_Request__c/fields/Integration_Status__c.field-meta.xml
<CustomField>
    <fullName>Integration_Status__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Integration Status</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Fleet_Service_Request__c/fields/Odometer_Km__c.field-meta.xml
<CustomField>
    <fullName>Odometer_Km__c</fullName>
    <label>Odometer Km</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

unpackaged/main/default/objects/Fleet_Service_Request__c/fields/Service_Number__c.field-meta.xml
<CustomField>
    <fullName>Service_Number__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <externalId>true</externalId>
    <label>Service Number</label>
    <length>250</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Fleet_Service_Request__c/fields/Workshop_Location__c.field-meta.xml
<CustomField>
    <fullName>Workshop_Location__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Workshop Location</label>
    <referenceTo>CICO_Workshop_Location__c</referenceTo>
    <relationshipLabel>Fleet Service Requests</relationshipLabel>
    <relationshipName>Fleet_Service_Requests</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/globalValueSets/Integration_Status_Value_Set.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>In Progress</fullName>
    </customValue>
    <customValue>
        <fullName>Success</fullName>
    </customValue>
    <customValue>
        <fullName>Failed</fullName>
    </customValue>
    <customValue>
        <fullName>Error</fullName>
    </customValue>
    <masterLabel>Integration Status Value Set</masterLabel>
</GlobalValueSet>

unpackaged/main/default/classes/fleetServiceRequestHandler.cls
/***
Class       : fleetServiceRequestHandler
Author      : Janardhan Muddana
Description : create fleet service request in oracle
TestClass  : fleetServiceRequestHandlerTest
----------------------------------------------------------------------------------------------------------------
            -- History --
----------------------------------------------------------------------------------------------------------------
Sr.No.  version_DevInitials     Date                Details
1.          V1.0              27/03/23           Initial Version 
****************************************************************************************************************/

public class fleetServiceRequestHandler {
    public static void processServiceRequest(list<Fleet_Service_Request__c> trgNew){
        System.debug('IN processServiceRequest');
        for(Fleet_Service_Request__c fsr : [select id,name,Customer_Vehicle__r.Internal_No__c,Workshop_Location__r.Location_Code__c,Odometer_Km__c,Description__c,Account__r.AccountNumber from Fleet_Service_Request__c where Id=:trgNew ]){
            string interNo = fsr.Customer_Vehicle__r.Internal_No__c!=null?string.valueOf(fsr.Customer_Vehicle__r.Internal_No__c):null;
            string wrkshp = fsr.Workshop_Location__r.Location_Code__c!=null?string.valueOf(fsr.Workshop_Location__r.Location_Code__c):null;
            string customerNo = fsr.Account__r.AccountNumber!=null?string.valueOf(fsr.Account__r.AccountNumber):null;
            string Odometer = string.valueOf(fsr.Odometer_Km__c);
            string recId = string.valueOf(fsr.id);
            System.debug('interNo>>>>>' + interNo);
            System.debug('wrkshp>>>>' + wrkshp);
            System.debug('customerNo>>>>' + customerNo);
            System.debug('Odometer>>>>>>' + Odometer);
            System.debug('recId>>>>>' + recId);
            fleetServiceRequestHandler.createServiceReqInOracle(recId,interNo,wrkshp,fsr.Description__c,Odometer,customerNo,fsr.Name);
        }
        
    }
    @future(callout = true) 
    public static void createServiceReqInOracle(String recId,String interNo,String wrkshp,String Descr,String Odometer,String customer,string Name){
        System.debug('IN processServiceRequest');
        ET_Oracle_REST_Endpoints__mdt connection = ET_REST_Authorize_Helper.getSOAPEndpointFromMetadata('CreateFleetServiceRequest');
        Blob beforeblob = Blob.valueOf(connection.Username__c+':'+connection.Password__c);
        string paramvalue = EncodingUtil.base64Encode(beforeblob);
        
        JSONGenerator gen = JSON.createGenerator(true);
        gen.writeStartObject();
        gen.writeStringField('InternalNumber',interNo);
        gen.writeStringField('Workshop',wrkshp);
        gen.writeStringField('Reference',Name);
        gen.writeStringField('Description',Descr);
        gen.writeStringField('ServiceType', 'Minor Service');
        gen.writeStringField('OdometerReading',Odometer);
        gen.writeStringField('CustomerNumber',customer);    
        gen.writeEndObject();
        
        String jsonData = gen.getAsString();
        System.debug('jsonData>>>>>>>>');
        HttpRequest request = new HttpRequest();
        System.debug('body=>>>>>>>>>'+jsonData);
        
        if(ET_REST_Authorize_Helper.runningInASandbox()){
            request.setEndpoint(connection.Dev_Endpoint__c);
            system.debug(connection.Dev_Endpoint__c);
        }else{
            request.setEndpoint(connection.LiveEndpoint_c__c);
        }  
        request.setMethod('POST');
        request.setTimeout(120000);
        request.setHeader('Content-Type', 'application/json');
        request.setBody(jsonData);      
        request.setHeader('Authorization','Basic '+paramvalue);   
        Http http = new Http();
        HttpResponse response = http.send(request);
        Map<String, Object> result = (Map<String, Object>)JSON.deserializeUntyped(response.getBody());
        System.debug('result=>>>>>>>>>'+result);
        Fleet_Service_Request__c fsr = new Fleet_Service_Request__c();
        fsr.Id = recId;
        System.debug('response.getStatusCode=>>>>>>>>>'+response.getStatusCode());
        if (response.getStatusCode() == 200) {
            System.debug('result Status=>>>>>>>>>'+string.valueOf(result.get('Status')));
            if(string.valueOf(result.get('Status')) =='S'){
               fsr.Integration_Status__c ='Success'; 
                fsr.Service_Number__c = string.valueOf(result.get('ServiceNumber'));
            }else{
                fsr.Integration_Status__c ='Error';  
                fsr.Service_Number__c = string.valueOf(result.get('Message'));
            }
            fsr.Integration_Message__c =string.valueOf(result.get('Message'));
            
            System.debug('Update in 200 fsr=>>>>>>>>>'+fsr);
            update fsr;
        }
        else{
            fsr.Integration_Message__c =string.valueOf(result.get('Message'));
            fsr.Integration_Status__c ='Error';
            System.debug('Update in NOt 200 fsr=>>>>>>>>>'+fsr);
            update fsr;
        }
        
            
    }

}