unpackaged/main/default/objects/Account/fields/IsConvertedFromLead__c.field-meta.xml
<CustomField>
    <fullName>IsConvertedFromLead__c</fullName>
    <defaultValue>false</defaultValue>
    <label>IsConvertedFromLead</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/objects/ET_Pricing_Service_Request__c/ET_Pricing_Service_Request__c.object-meta.xml
<CustomObject>
    <label>Pricing Service Request</label>
    <nameField>
        <displayFormat>PSR-{0000}</displayFormat>
        <label>Pricing Service Request Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Pricing Service Requests</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

unpackaged/main/default/objects/ET_Pricing_Service_Request__c/fields/ET_Service_Request_Common_Data__c.field-meta.xml
<CustomField>
    <fullName>ET_Service_Request_Common_Data__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Service Request Common Data</label>
    <referenceTo>ET_Service_Request_Common_Data__c</referenceTo>
    <relationshipLabel>Pricing Service Requests</relationshipLabel>
    <relationshipName>Pricing_Service_Requests</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/ET_Service_Request_Common_Data__c/ET_Service_Request_Common_Data__c.object-meta.xml
<CustomObject>
    <label>Service Request Common Data</label>
    <nameField>
        <displayFormat>SRCD-{0000}</displayFormat>
        <label>Service Request Common Data Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Service Requests Common Data</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/ET_Service_Request_Common_Data__c/fields/ET_Common_Data_Type__c.field-meta.xml
<CustomField>
    <fullName>ET_Common_Data_Type__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Common Data Type</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/ET_Service_Request_Common_Data__c/fields/ET_Contract_Period__c.field-meta.xml
<CustomField>
    <fullName>ET_Contract_Period__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Contract Period</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/ET_Service_Request_Common_Data__c/fields/ET_Contract_Type__c.field-meta.xml
<CustomField>
    <fullName>ET_Contract_Type__c</fullName>
    <label>Contract Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>New</fullName>
            </value>
            <value>
                <fullName>Renewal</fullName>
            </value>
            <value>
                <fullName>Multiple</fullName>
                <isActive>false</isActive>
                <label>Multiple</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/ET_Service_Request_Common_Data__c/fields/ET_Pricing_Method__c.field-meta.xml
<CustomField>
    <fullName>ET_Pricing_Method__c</fullName>
    <label>Pricing Method</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Per Unit</fullName>
            </value>
            <value>
                <fullName>Comprehensive Price per Quotation</fullName>
            </value>
            <value>
                <fullName>Comprehensive Price per Route</fullName>
                <isActive>false</isActive>
                <label>Comprehensive Price per Route</label>
            </value>
            <value>
                <fullName>Multiple</fullName>
                <isActive>false</isActive>
                <label>Multiple</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/ET_Service_Request_Common_Data__c/fields/ET_Pricing_Type__c.field-meta.xml
<CustomField>
    <fullName>ET_Pricing_Type__c</fullName>
    <label>Pricing Type</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>ET_Pricing_Method__c</controllingField>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Annual Price</fullName>
            </value>
            <value>
                <fullName>Monthly Price</fullName>
            </value>
            <value>
                <fullName>Per student</fullName>
            </value>
            <value>
                <fullName>Per route</fullName>
            </value>
            <value>
                <fullName>Per KM</fullName>
            </value>
            <value>
                <fullName>Per ton</fullName>
            </value>
            <value>
                <fullName>Multiple</fullName>
                <isActive>false</isActive>
                <label>Multiple</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/ET_Service_Request_Common_Data__c/fields/ET_Service_Emirate__c.field-meta.xml
<CustomField>
    <fullName>ET_Service_Emirate__c</fullName>
    <label>Service Emirate</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Abu Dhabi</fullName>
            </value>
            <value>
                <fullName>Dubai</fullName>
            </value>
            <value>
                <fullName>Sharjah</fullName>
            </value>
            <value>
                <fullName>Ajman</fullName>
            </value>
            <value>
                <fullName>UMM Al Quawain</fullName>
            </value>
            <value>
                <fullName>Ras Al Khaimah</fullName>
            </value>
            <value>
                <fullName>Fujairah</fullName>
            </value>
            <value>
                <fullName>Multiple</fullName>
            </value>
            <value>
                <fullName>Abu-Dhabi</fullName>
                <isActive>false</isActive>
                <label>Abu-Dhabi</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/ET_Service_Request_Common_Data__c/fields/ET_Working_Days_Per_Week__c.field-meta.xml
<CustomField>
    <fullName>ET_Working_Days_Per_Week__c</fullName>
    <label>Working Days Per Week</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>1</fullName>
            </value>
            <value>
                <fullName>2</fullName>
            </value>
            <value>
                <fullName>3</fullName>
            </value>
            <value>
                <fullName>4</fullName>
            </value>
            <value>
                <fullName>5</fullName>
            </value>
            <value>
                <fullName>6</fullName>
            </value>
            <value>
                <fullName>7</fullName>
            </value>
            <value>
                <fullName>Multiple</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/ET_Service_Request_Common_Data__c/fields/ET_Working_Months_Per_Year__c.field-meta.xml
<CustomField>
    <fullName>ET_Working_Months_Per_Year__c</fullName>
    <label>Working Months Per Year</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>1</fullName>
            </value>
            <value>
                <fullName>2</fullName>
            </value>
            <value>
                <fullName>3</fullName>
            </value>
            <value>
                <fullName>4</fullName>
            </value>
            <value>
                <fullName>5</fullName>
            </value>
            <value>
                <fullName>6</fullName>
            </value>
            <value>
                <fullName>7</fullName>
            </value>
            <value>
                <fullName>8</fullName>
            </value>
            <value>
                <fullName>9</fullName>
            </value>
            <value>
                <fullName>10</fullName>
            </value>
            <value>
                <fullName>11</fullName>
            </value>
            <value>
                <fullName>12</fullName>
            </value>
            <value>
                <fullName>Multiple</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Opportunity/fields/ETSALES_Approval_Status__c.field-meta.xml
<CustomField>
    <fullName>ETSALES_Approval_Status__c</fullName>
    <label>Approval Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Submitted For Approval</fullName>
            </value>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>Rejected</fullName>
            </value>
            <value>
                <fullName>Rejected by Pricing Team</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Opportunity/fields/ETSALES_GL_Services__c.field-meta.xml
<CustomField>
    <fullName>ETSALES_GL_Services__c</fullName>
    <label>ET Service (Current Contract)</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>ETSALES_Service_Type_Values</valueSetName>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Opportunity/fields/ETSALES_GNG_Approval_Status_Date__c.field-meta.xml
<CustomField>
    <fullName>ETSALES_GNG_Approval_Status_Date__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Go-No-Go Approval Received Date</label>
    <type>DateTime</type>
</CustomField>

unpackaged/main/default/objects/Vehicle__c/Vehicle__c.object-meta.xml
<CustomObject>
    <label>Pricing Vehicle Request</label>
    <nameField>
        <displayFormat>VN-{0000}</displayFormat>
        <label>Vehicle Request Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Vehicle Requests</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Vehicle__c/fields/ET_Contract_Period__c.field-meta.xml
<CustomField>
    <fullName>ET_Contract_Period__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Contract Period</label>
    <type>TextArea</type>
</CustomField>

unpackaged/main/default/objects/Vehicle__c/fields/ET_Contract_Type__c.field-meta.xml
<CustomField>
    <fullName>ET_Contract_Type__c</fullName>
    <label>Contract Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>New</fullName>
            </value>
            <value>
                <fullName>Renewal</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Vehicle__c/fields/ET_Price_Utilization__c.field-meta.xml
<CustomField>
    <fullName>ET_Price_Utilization__c</fullName>
    <label>Price Utilization</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

unpackaged/main/default/objects/Vehicle__c/fields/ET_Pricing_Method__c.field-meta.xml
<CustomField>
    <fullName>ET_Pricing_Method__c</fullName>
    <label>Pricing Method</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Per Unit</fullName>
            </value>
            <value>
                <fullName>Comprehensive Price per Quotation</fullName>
            </value>
            <value>
                <fullName>Comprehensive Price per Route</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Vehicle__c/fields/ET_Pricing_Type__c.field-meta.xml
<CustomField>
    <fullName>ET_Pricing_Type__c</fullName>
    <label>Pricing Type</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>ET_Pricing_Method__c</controllingField>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Annual Price</fullName>
            </value>
            <value>
                <fullName>Monthly Price</fullName>
            </value>
            <value>
                <fullName>Per student</fullName>
            </value>
            <value>
                <fullName>Per route</fullName>
            </value>
            <value>
                <fullName>Per KM</fullName>
            </value>
            <value>
                <fullName>Per ton</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Vehicle__c/fields/ET_Service_Emirate__c.field-meta.xml
<CustomField>
    <fullName>ET_Service_Emirate__c</fullName>
    <label>Service Emirate</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Abu Dhabi</fullName>
            </value>
            <value>
                <fullName>Dubai</fullName>
            </value>
            <value>
                <fullName>Sharjah</fullName>
            </value>
            <value>
                <fullName>Ajman</fullName>
            </value>
            <value>
                <fullName>UMM Al Quawain</fullName>
            </value>
            <value>
                <fullName>Ras Al Khaimah</fullName>
            </value>
            <value>
                <fullName>Fujairah</fullName>
            </value>
            <value>
                <fullName>Abu-Dhabi</fullName>
                <isActive>false</isActive>
                <label>Abu-Dhabi</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Vehicle__c/fields/ET_Service_Request_Common_Data__c.field-meta.xml
<CustomField>
    <fullName>ET_Service_Request_Common_Data__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Service Request Common Data</label>
    <referenceTo>ET_Service_Request_Common_Data__c</referenceTo>
    <relationshipName>Vehicle_Requests</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Vehicle__c/fields/ET_Working_Days_Per_Week__c.field-meta.xml
<CustomField>
    <fullName>ET_Working_Days_Per_Week__c</fullName>
    <label>Working Days Per Week</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

unpackaged/main/default/objects/Vehicle__c/fields/ET_Working_Months_Per_Year__c.field-meta.xml
<CustomField>
    <fullName>ET_Working_Months_Per_Year__c</fullName>
    <label>Working Months Per Year</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

unpackaged/main/default/globalValueSets/ETSALES_Service_Type_Values.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Airport drop off</fullName>
    </customValue>
    <customValue>
        <fullName>Chauffeur - Dubai</fullName>
    </customValue>
    <customValue>
        <fullName>Chauffeur - Others</fullName>
    </customValue>
    <customValue>
        <fullName>Abu Dhabi</fullName>
    </customValue>
    <customValue>
        <fullName>Documents</fullName>
    </customValue>
    <customValue>
        <fullName>Motor Cycle</fullName>
    </customValue>
    <customValue>
        <fullName>Electric Car</fullName>
    </customValue>
    <customValue>
        <fullName>Vehicle</fullName>
    </customValue>
    <customValue>
        <fullName>Government School</fullName>
    </customValue>
    <customValue>
        <fullName>Quran Studies</fullName>
    </customValue>
    <customValue>
        <fullName>Private School</fullName>
    </customValue>
    <customValue>
        <fullName>Government Executive</fullName>
    </customValue>
    <customValue>
        <fullName>Staff-Employees and Labors</fullName>
    </customValue>
    <customValue>
        <fullName>Haj &amp; Umrah</fullName>
    </customValue>
    <customValue>
        <fullName>University</fullName>
    </customValue>
    <customValue>
        <fullName>Club Members</fullName>
    </customValue>
    <customValue>
        <fullName>Vehicle Auctioning</fullName>
    </customValue>
    <customValue>
        <fullName>Sale Of Scrap Materials</fullName>
    </customValue>
    <customValue>
        <fullName>Maintenance Services - Contracted</fullName>
    </customValue>
    <customValue>
        <fullName>Maintenance Services - Non-Contracted</fullName>
    </customValue>
    <customValue>
        <fullName>Luxury Vehicles Maintenance</fullName>
    </customValue>
    <customValue>
        <fullName>Dry Wash</fullName>
    </customValue>
    <customValue>
        <fullName>Tire Rethreading and Repair</fullName>
    </customValue>
    <customValue>
        <fullName>Refurbished and used tire Sales</fullName>
    </customValue>
    <customValue>
        <fullName>Road Side Assistance</fullName>
    </customValue>
    <customValue>
        <fullName>Body-Accident Repair services</fullName>
    </customValue>
    <customValue>
        <fullName>Bus Refurbishment</fullName>
    </customValue>
    <customValue>
        <fullName>CNG Conversion Services</fullName>
    </customValue>
    <customValue>
        <fullName>Vehicle Inspection</fullName>
    </customValue>
    <customValue>
        <fullName>Heavy Equipment Maintenance</fullName>
    </customValue>
    <masterLabel>GL Service Type Values</masterLabel>
</GlobalValueSet>

unpackaged/main/default/classes/ET_PricingUtilityClassTest.cls
@isTest
public class ET_PricingUtilityClassTest {
    Public static testmethod void codeCoverage(){
        Account acc = new Account();
        acc.Name = 'Test Account';
        acc.IsConvertedFromLead__c = true;
        insert acc;
        Opportunity opp = new Opportunity();
        opp.Name = 'Test Account';
        opp.StageName = 'Qualification';
        opp.CloseDate = System.today()+8;
        opp.ETSALES_GNG_Approval_Status_Date__c = System.today()+8;
        opp.ETSALES_Approval_Status__c = 'Approved';
        opp.ETSALES_GL_Services__c = 'Private School';
        insert opp;
        ET_Service_Request_Common_Data__c et_service_request_common_data = new ET_Service_Request_Common_Data__c(
            CurrencyIsoCode = 'AED',
            ET_Common_Data_Type__c = 'All Tab',
            ET_Contract_Period__c = '1 Yr,2 Yrs,3 Yrs,4 Yrs,5 Yrs,6 Yrs,7 Yrs,8 Yrs',
            ET_Contract_Type__c = 'New',
            ET_Price_Utilization__c = 1.0,
            ET_Pricing_Method__c = 'Per Unit',
            ET_Pricing_Type__c = 'Annual Price',
            ET_Service_Emirate__c = 'Dubai',
            ET_Working_Days_Per_Week__c = '7',
            ET_Working_Months_Per_Year__c = '12');
        insert et_service_request_common_data;
        
        ET_Pricing_Service_Request__c sr = new ET_Pricing_Service_Request__c(Opportunity__c = opp.Id, ET_PSR_IsActive__c = true, 
                                                                             ET_Service_Request_Common_Data__c = ET_Service_Request_Common_Data.id);
        try{
           insert sr; 
        }
        catch(exception e){}
        Vehicle__c vehical = new Vehicle__c();
        vehical.ET_Pricing_Service_Request__c = sr.Id;
        try{
          insert vehical;   
        }
        catch(exception e){}
        Quote q = new Quote();
        q.name = 'Quote1' + opp.name;
        q.opportunityId = opp.id;
        q.Is_Target_Price_Required__c=true;
        insert q;
        
        // insert Total project quote summary..
        Quote q2 = new Quote();
        q2.name = 'Quote1' + opp.name;
        q2.opportunityId = opp.id;
        q2.Is_Target_Price_Required__c=true;
        q2.ET_Type__c ='Total Project Summary';
        insert q2;
        Test.startTest();
        ET_PricingUtilityClass.getVehicleRequestMap(sr.Id);
        ET_PricingUtilityClass.getWorkforceRequestMap(sr.Id);
        ET_PricingUtilityClass.getVehicleQuoteItemLst(q.Id);
        ET_PricingUtilityClass.getWorkforceQuoteItemLst(q.Id,'Test');
        ET_PricingUtilityClass.getWorkforceQuoteItemLstWithQutId(q.Id);
        ET_PricingUtilityClass.getVehicleMasterData();
        ET_PricingUtilityClass.getFinanceCalculationsRecords(q.Id);
        ET_PricingUtilityClass.getTotalProjectQuoteId(q2.Id);
        
        Test.stopTest();
    }
}