unpackaged/main/default/objects/Account/fields/Location__c.field-meta.xml
<CustomField>
    <fullName>Location__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Location</label>
    <referenceTo>ET_Location__c</referenceTo>
    <relationshipLabel>Accounts</relationshipLabel>
    <relationshipName>Accounts</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Case/fields/Location__c.field-meta.xml
<CustomField>
    <fullName>Location__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Location</label>
    <referenceTo>ET_Location__c</referenceTo>
    <relationshipLabel>Cases</relationshipLabel>
    <relationshipName>Cases</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Case/recordTypes/Asked_to_print_a_new_card_for_students.recordType-meta.xml
<RecordType>
    <fullName>Asked_to_print_a_new_card_for_students</fullName>
    <active>true</active>
    <businessProcess>Request for printing a new card - Students</businessProcess>
    <label>Printing New Card - Student</label>
</RecordType>

unpackaged/main/default/objects/ET_Location__c/ET_Location__c.object-meta.xml
<CustomObject>
    <label>Inspection Center</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>ET Loaction Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Inspection Centers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/ET_Location__c/fields/Latitude__c.field-meta.xml
<CustomField>
    <fullName>Latitude__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Latitude</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/ET_Location__c/fields/Longitude__c.field-meta.xml
<CustomField>
    <fullName>Longitude__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Longitude</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/ET_Location__c/fields/Operations_Queue_Id__c.field-meta.xml
<CustomField>
    <fullName>Operations_Queue_Id__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Operations Queue Id</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/classes/ETServ_CaseProcessHandlerTest.cls
@isTest
private class ETServ_CaseProcessHandlerTest {



   private static testMethod void doTest() {
   
   ETServ_CaseProcessHandler.utilityMethod();
         /*List<Id> clist = new List<Id>();
        ET_Location__c loc = new ET_Location__c();
        loc.Name = 'Test location';
        loc.Latitude__c = '23.2';
        loc.Longitude__c = '23.2';
        loc.Operations_Queue_Id__c=System.Label.ET_Services_Omni_Channel_Queue;
        insert loc;
         ET_Location__c loc2 = new ET_Location__c();
        loc2.Name = 'Test location2';
        loc2.Latitude__c = '23.2';
        loc2.Longitude__c = '23.2';
         insert loc2;
        Account acc = new Account(name = 'test acc',Location__c=loc.id);
         Account acc2 = new Account(name = 'test acc2',Location__c=loc2.id);
       
        Id recordtypid =Schema.SObjectType.Case.getRecordTypeInfosByDeveloperName().get('Asked_to_print_a_new_card_for_students').getRecordTypeId();
        System.Test.startTest();
        Case cs = new Case(Status= 'New',
                     Accountid=acc.id,
                     Location__c=loc.id,
                    Recordtypeid =recordtypid
                    );
        insert cs;
         Case cs2 = new Case(Status= 'New',
                     Accountid=acc2.id,
                     Location__c=loc2.id,
                    Recordtypeid =recordtypid
                    
                    );
        insert cs2;
        clist.add(cs.id);
        clist.add(cs2.id);
ETServ_CaseProcessHandler.caseProcess(clist);
        System.Test.stopTest();*/

     

    }
}