unpackaged/main/default/objects/Account/fields/Party_Type__c.field-meta.xml
<CustomField>
    <fullName>Party_Type__c</fullName>
    <label>Party Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Supplier</fullName>
            </value>
            <value>
                <fullName>Internal Project</fullName>
            </value>
            <value>
                <fullName>Customer</fullName>
            </value>
            <value>
                <fullName>Internal Private Project</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/ETT_Collection_Card__c/ETT_Collection_Card__c.object-meta.xml
<CustomObject>
    <description>This object is to track the vehicle information and as well as driver information with the help of google map.</description>
    <label>Collection Card</label>
    <nameField>
        <displayFormat>CC-{0000}</displayFormat>
        <label>Collection Card Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Collection Cards</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/ETT_Collection_Card__c/fields/ETT_Account__c.field-meta.xml
<CustomField>
    <fullName>ETT_Account__c</fullName>
    <formula>ETT_Service_Appointment__r.Account.Name</formula>
    <label>Account</label>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/ETT_Collection_Card__c/fields/ETT_Accounts__c.field-meta.xml
<CustomField>
    <fullName>ETT_Accounts__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Collection Cards</relationshipLabel>
    <relationshipName>Collection_Cards</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/ETT_Collection_Card__c/fields/ETT_Brand__c.field-meta.xml
<CustomField>
    <fullName>ETT_Brand__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Brand</label>
    <referenceTo>ETT_Brand_Master__c</referenceTo>
    <relationshipLabel>Collection Cards</relationshipLabel>
    <relationshipName>Collection_Cards</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/ETT_Collection_Card__c/fields/ETT_Collection_Date__c.field-meta.xml
<CustomField>
    <fullName>ETT_Collection_Date__c</fullName>
    <defaultValue>Today()</defaultValue>
    <encryptionScheme>None</encryptionScheme>
    <label>Collection Date</label>
    <type>Date</type>
</CustomField>

unpackaged/main/default/objects/ETT_Collection_Card__c/fields/ETT_Tyre_Size__c.field-meta.xml
<CustomField>
    <fullName>ETT_Tyre_Size__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Tyre Size</label>
    <referenceTo>ETT_Tyre_Size_Master__c</referenceTo>
    <relationshipLabel>Collection Cards</relationshipLabel>
    <relationshipName>Collection_Cards</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/ETT_Inspection_Card__c/ETT_Inspection_Card__c.object-meta.xml
<CustomObject>
    <description>This is for inspection for the customer who has been requested orders.</description>
    <label>Tyre Inspection Card</label>
    <nameField>
        <displayFormat>IC-{0000}</displayFormat>
        <label>Inspection Card Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Tyre Inspection Cards</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/ETT_Inspection_Card__c/fields/ETT_Account__c.field-meta.xml
<CustomField>
    <fullName>ETT_Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipName>Inspection_Cards</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/ETT_Inspection_Card__c/fields/ETT_Brand__c.field-meta.xml
<CustomField>
    <fullName>ETT_Brand__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Brand</label>
    <referenceTo>ETT_Brand_Master__c</referenceTo>
    <relationshipName>Inspection_Cards</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/ETT_Inspection_Card__c/fields/ETT_Collection_Card__c.field-meta.xml
<CustomField>
    <fullName>ETT_Collection_Card__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Collection Card</label>
    <referenceTo>ETT_Collection_Card__c</referenceTo>
    <relationshipName>Inspection_Cards</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/ETT_Inspection_Card__c/fields/ETT_Tyre_Size__c.field-meta.xml
<CustomField>
    <fullName>ETT_Tyre_Size__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Tyre Size</label>
    <referenceTo>ETT_Tyre_Size_Master__c</referenceTo>
    <relationshipName>Inspection_Cards</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/ETT_Job_Card__c/fields/ETT_Job_Type__c.field-meta.xml
<CustomField>
    <fullName>ETT_Job_Type__c</fullName>
    <formula>ETT_Inspection_Card__r.RecordType.Name</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Job Type</label>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/ETT_Tools_Material_Usage__c/ETT_Tools_Material_Usage__c.object-meta.xml
<CustomObject>
    <label>Tools/Material Usage</label>
    <nameField>
        <displayFormat>USAGE-{0000000}</displayFormat>
        <label>Tools/Material Usage Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Tools/Material Usage</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

unpackaged/main/default/objects/ETT_Tools_Material_Usage__c/fields/ETT_Job_Card__c.field-meta.xml
<CustomField>
    <fullName>ETT_Job_Card__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Job Card</label>
    <referenceTo>ETT_Job_Card__c</referenceTo>
    <relationshipLabel>Tools/Material Usage</relationshipLabel>
    <relationshipName>Tools_Material_Usage</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/ETT_Tyre_Master__c/ETT_Tyre_Master__c.object-meta.xml
<CustomObject>
    <label>Tyre Master</label>
    <nameField>
        <displayFormat>TMN-{0000}</displayFormat>
        <label>Tyre Master Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Tyre Masters</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/ETT_Tyre_Master__c/fields/ETT_Brand__c.field-meta.xml
<CustomField>
    <fullName>ETT_Brand__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Brand</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/ETT_Tyre_Master__c/fields/ETT_Collection_Card__c.field-meta.xml
<CustomField>
    <fullName>ETT_Collection_Card__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Collection Card</label>
    <referenceTo>ETT_Collection_Card__c</referenceTo>
    <relationshipLabel>Tyre Masters</relationshipLabel>
    <relationshipName>Tyre_Masters</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/ETT_Tyre_Master__c/fields/ETT_Load_Index__c.field-meta.xml
<CustomField>
    <fullName>ETT_Load_Index__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Load Index</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/ETT_Tyre_Master__c/fields/ETT_Original_Pattern__c.field-meta.xml
<CustomField>
    <fullName>ETT_Original_Pattern__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Original Pattern</label>
    <referenceTo>ETT_Pattern_Master__c</referenceTo>
    <relationshipLabel>Tyre Masters</relationshipLabel>
    <relationshipName>Tyre_Masters</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/ETT_Tyre_Master__c/fields/ETT_Ply_Rate__c.field-meta.xml
<CustomField>
    <fullName>ETT_Ply_Rate__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Ply Rate</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/ETT_Tyre_Master__c/fields/ETT_Tyre_Size__c.field-meta.xml
<CustomField>
    <fullName>ETT_Tyre_Size__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Tyre Size</label>
    <referenceTo>ETT_Tyre_Size_Master__c</referenceTo>
    <relationshipLabel>Tyre Masters</relationshipLabel>
    <relationshipName>Tyre_Masters</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/ETT_Tyre_Size_Master__c/ETT_Tyre_Size_Master__c.object-meta.xml
<CustomObject>
    <label>Tyre Size Master</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Tyre Sizes</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Tyre Size Master</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/ETT_Tyre_Size_Master__c/fields/ETT_Tyre_Size__c.field-meta.xml
<CustomField>
    <fullName>ETT_Tyre_Size__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Tyre size</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/WorkOrderLineItem/fields/ETT_Account__c.field-meta.xml
<CustomField>
    <fullName>ETT_Account__c</fullName>
    <formula>WorkOrder.Account.Name</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Account</label>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/WorkOrderLineItem/fields/ETT_Accounts__c.field-meta.xml
<CustomField>
    <fullName>ETT_Accounts__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Work Order Line Items</relationshipLabel>
    <relationshipName>Work_Order_Line_Items</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/WorkOrderLineItem/fields/ETT_Brand__c.field-meta.xml
<CustomField>
    <fullName>ETT_Brand__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Brand</label>
    <referenceTo>ETT_Brand_Master__c</referenceTo>
    <relationshipLabel>Work Order Line Items</relationshipLabel>
    <relationshipName>Work_Order_Line_Items</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/WorkOrderLineItem/fields/ETT_Collection_Card__c.field-meta.xml
<CustomField>
    <fullName>ETT_Collection_Card__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Collection Card</label>
    <referenceTo>ETT_Collection_Card__c</referenceTo>
    <relationshipLabel>Work Order Line Items</relationshipLabel>
    <relationshipName>Work_Order_Line_Items</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/WorkOrderLineItem/fields/ETT_Job_Type__c.field-meta.xml
<CustomField>
    <fullName>ETT_Job_Type__c</fullName>
    <label>Job Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Retread</fullName>
                <default>true</default>
                <label>Retread</label>
            </value>
            <value>
                <fullName>Repair</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/WorkOrderLineItem/fields/ETT_Ply_Rate__c.field-meta.xml
<CustomField>
    <fullName>ETT_Ply_Rate__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Ply Rate</label>
    <length>200</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/WorkOrderLineItem/fields/ETT_Tyre_Master__c.field-meta.xml
<CustomField>
    <fullName>ETT_Tyre_Master__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Tyre Master</label>
    <referenceTo>ETT_Tyre_Master__c</referenceTo>
    <relationshipLabel>Work Order Line Items</relationshipLabel>
    <relationshipName>Work_Order_Line_Items</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/WorkOrderLineItem/fields/ETT_Tyre_Serial_Number__c.field-meta.xml
<CustomField>
    <fullName>ETT_Tyre_Serial_Number__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Tyre Serial Number</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/WorkOrderLineItem/fields/ETT_Tyre_Size__c.field-meta.xml
<CustomField>
    <fullName>ETT_Tyre_Size__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Tyre Size</label>
    <referenceTo>ETT_Tyre_Size_Master__c</referenceTo>
    <relationshipLabel>Work Order Line Items</relationshipLabel>
    <relationshipName>Work_Order_Line_Items</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/classes/ETT_JobCardCloseCtrl.cls
/***
 * Author: Janardhan
 * CreatedDate: 09/11/21
 * Desc:
 * Test Class: ETT_JobCardCloseCtrlTest
 * 
 * */

public class ETT_JobCardCloseCtrl {

    @AuraEnabled
    public static ETT_Job_Card__c getJobCardRealtedDetails(string jobCardId){
        
        return [Select Id,Name,ETT_Overall_Status__c,ETT_Stages__c,ETT_Tyre_Master__c,ETT_Job_Type__c,ETT_Inspection_Card__c,ETT_Inspection_Card__r.ETT_Collection_Card__c,Collection_Card__r.ETT_Accounts__r.Name,Collection_Card__r.ETT_Accounts__r.Party_Type__c,ETT_Inspection_Card__r.ETT_Account__r.Name,ETT_Inspection_Card__r.ETT_Account__r.Party_Type__c,ETT_Inspection_Card__r.ETT_Collection_Card__r.ETT_Collection_Date__c,
                ETT_Inspection_Card__r.ETT_Brand__r.Name, ETT_Inspection_Card__r.ETT_Tyre_Size__r.Name,ETT_Inspection_Card__r.ETT_Tyre_Serial_Number__c,ETT_Inspection_Card__r.ETT_Account__c,ETT_Tyre_Master__r.ETT_Original_Pattern__r.Name,ETT_Tyre_Master__r.ETT_Ply_Rate__c,ETT_Tyre_Master__r.ETT_Load_Index__c,
                ETT_Tyre_Master__r.ETT_Speed_Index__c from ETT_Job_Card__c where id=:jobCardId];
    }
    
    @AuraEnabled
    public static string getJobTypeValue(string insCardId){
        
        ETT_Inspection_Card__c ins = [select id,ETT_Tyre_Serial_Number__c,ETT_Collection_Card__c from ETT_Inspection_Card__c where id=:insCardId];
        
        WorkOrderLineItem workLine = [select id,ETT_Job_Type__c from WorkOrderLineItem where ETT_Tyre_Serial_Number__c=:ins.ETT_Tyre_Serial_Number__c AND ETT_Collection_Card__c=:ins.ETT_Collection_Card__c];
        
        return workLine.ETT_Job_Type__c;
    }
    
    @AuraEnabled
    public static List<String> getselectOptions(string objObject, string fld) { 
      
     List < String > allOpts = new list <String> ();
        
      DescribeSObjectResult objResult = Schema.getGlobalDescribe().get(objObject).getDescribe();
      DescribeFieldResult fieldResult = objResult.fields.getMap().get(fld).getDescribe();
     
        list < Schema.PicklistEntry > values =fieldResult.getPicklistValues();
      
        for (Schema.PicklistEntry a: values) {
            allOpts.add(a.getValue());
        }
        //allOpts.sort();
      
        return allOpts;
    } 
    
     @AuraEnabled
    public static list<ETT_Tools_Material_Usage__c> getAllUsedItems(string JobCardId){
        
        return [select id,ETT_Job_Stage__c,ETT_Tools_Material_Allocation__c,ETT_Tools_Material_Allocation__r.ETT_Tools_Master__c,ETT_Usage_Value__c,ETT_Tools_Material_Allocation__r.ETT_Tools_Master__r.ETT_Unique_Code__c,
                ETT_Tools_Material_Allocation__r.ETT_Tools_Master__r.ETT_Individual_Unit_Value__c,ETT_Tools_Material_Allocation__r.ETT_Tools_Master__r.ETT_Item_Description__c,ETT_Tools_Material_Allocation__r.ETT_Tools_Master__r.UOM__c,ETT_Tools_Material_Allocation__r.ETT_Tools_Master__r.ETT_Main_Stock_Units__c from ETT_Tools_Material_Usage__c where ETT_Job_Card__c=:JobCardId ];
    }
    
      @AuraEnabled
    public static ETT_Tools_Master__c getToolMasterInfo(string toolMasId){
        return [SELECT Id,ETT_Unique_Code__c,ETT_Individual_Unit_Value__c,ETT_Item_Description__c,UOM__c,ETT_Main_Stock_Units__c from ETT_Tools_Master__c where id=:toolMasId];
    }
    
   @AuraEnabled
    public static void createJCcloseLinesUnderJC(list<ETT_Job_Card_Close_Lines__c> JCcloseLines,string JCCloseId){
        system.debug('--'+JCcloseLines);
        if(JCcloseLines!= null && JCcloseLines.size()>0){
            for(ETT_Job_Card_Close_Lines__c line :JCcloseLines){
                
                line.Job_Card_Close__c = JCCloseId;
            }
            
            
             try {
                 insert JCcloseLines;
             }
            catch (Exception e) {
                
                throw new AuraHandledException(e.getMessage());    
            }
        }
       
    }

}