unpackaged/main/default/objects/Account/fields/Party_Type__c.field-meta.xml
<CustomField>
    <fullName>Party_Type__c</fullName>
    <label>Party Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Supplier</fullName>
            </value>
            <value>
                <fullName>Internal Project</fullName>
            </value>
            <value>
                <fullName>Customer</fullName>
            </value>
            <value>
                <fullName>Internal Private Project</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/ETT_Brand_Master__c/ETT_Brand_Master__c.object-meta.xml
<CustomObject>
    <label>Brand Master</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Brand Master Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Brand Masters</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/ETT_Brand_Master__c/fields/ETT_Status__c.field-meta.xml
<CustomField>
    <fullName>ETT_Status__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Status</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/objects/ETT_Collection_Card__c/ETT_Collection_Card__c.object-meta.xml
<CustomObject>
    <description>This object is to track the vehicle information and as well as driver information with the help of google map.</description>
    <label>Collection Card</label>
    <nameField>
        <displayFormat>CC-{0000}</displayFormat>
        <label>Collection Card Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Collection Cards</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/ETT_Collection_Card__c/fields/ETT_Account__c.field-meta.xml
<CustomField>
    <fullName>ETT_Account__c</fullName>
    <formula>ETT_Service_Appointment__r.Account.Name</formula>
    <label>Account</label>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/ETT_Collection_Card__c/fields/ETT_Brand__c.field-meta.xml
<CustomField>
    <fullName>ETT_Brand__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Brand</label>
    <referenceTo>ETT_Brand_Master__c</referenceTo>
    <relationshipLabel>Collection Cards</relationshipLabel>
    <relationshipName>Collection_Cards</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/ETT_Collection_Card__c/fields/ETT_Inspection_Done__c.field-meta.xml
<CustomField>
    <fullName>ETT_Inspection_Done__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Inspection Done</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/objects/ETT_Collection_Card__c/fields/ETT_Pattern__c.field-meta.xml
<CustomField>
    <fullName>ETT_Pattern__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Pattern</label>
    <referenceTo>ETT_Pattern_Master__c</referenceTo>
    <relationshipLabel>Collection Cards</relationshipLabel>
    <relationshipName>Collection_Cards</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/ETT_Collection_Card__c/fields/ETT_Phone__c.field-meta.xml
<CustomField>
    <fullName>ETT_Phone__c</fullName>
    <formula>ETT_Accounts__r.Phone</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Phone</label>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/ETT_Collection_Card__c/fields/ETT_Service_Appointment__c.field-meta.xml
<CustomField>
    <fullName>ETT_Service_Appointment__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Service Appointment</label>
    <referenceTo>ServiceAppointment</referenceTo>
    <relationshipLabel>Collection Cards</relationshipLabel>
    <relationshipName>Collection_Cards</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/ETT_Collection_Card__c/fields/ETT_Status__c.field-meta.xml
<CustomField>
    <fullName>ETT_Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Collection Stage</fullName>
            </value>
            <value>
                <fullName>Inspection Stage</fullName>
            </value>
            <value>
                <fullName>Job Card Stage</fullName>
            </value>
            <value>
                <fullName>Delivery Stage</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/ETT_Collection_Card__c/fields/ETT_Tyre_Size__c.field-meta.xml
<CustomField>
    <fullName>ETT_Tyre_Size__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Tyre Size</label>
    <referenceTo>ETT_Tyre_Size_Master__c</referenceTo>
    <relationshipLabel>Collection Cards</relationshipLabel>
    <relationshipName>Collection_Cards</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/ETT_Collection_Card__c/fields/ETT_Vehicle_Detail__c.field-meta.xml
<CustomField>
    <fullName>ETT_Vehicle_Detail__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Vehicle Detail</label>
    <referenceTo>ETT_Vehicle_Details__c</referenceTo>
    <relationshipLabel>Collection Cards</relationshipLabel>
    <relationshipName>Collection_Cards</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/ETT_Delivery_Line_Item__c/ETT_Delivery_Line_Item__c.object-meta.xml
<CustomObject>
    <label>Delivery Line Item</label>
    <nameField>
        <displayFormat>DLN-{0000}</displayFormat>
        <label>Delivery Line Item Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Delivery Line Items</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/ETT_Delivery_Line_Item__c/fields/ETT_Collection_Card__c.field-meta.xml
<CustomField>
    <fullName>ETT_Collection_Card__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Collection Card</label>
    <referenceTo>ETT_Collection_Card__c</referenceTo>
    <relationshipLabel>Delivery Line Items</relationshipLabel>
    <relationshipName>Delivery_Line_Items</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/ETT_Delivery_Line_Item__c/fields/ETT_Inspection_Card__c.field-meta.xml
<CustomField>
    <fullName>ETT_Inspection_Card__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Tyre Inspection Card</label>
    <referenceTo>ETT_Inspection_Card__c</referenceTo>
    <relationshipLabel>Delivery Line Items</relationshipLabel>
    <relationshipName>Delivery_Line_Items</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/ETT_Delivery_Line_Item__c/fields/ETT_Tyre_Size__c.field-meta.xml
<CustomField>
    <fullName>ETT_Tyre_Size__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Tyre Size</label>
    <referenceTo>ETT_Tyre_Size_Master__c</referenceTo>
    <relationshipLabel>Delivery Line Items</relationshipLabel>
    <relationshipName>Delivery_Line_Items</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/ETT_Delivery_Note__c/ETT_Delivery_Note__c.object-meta.xml
<CustomObject>
    <label>Delivery Note</label>
    <nameField>
        <displayFormat>DNN-{0000}</displayFormat>
        <label>Delivery Note Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Delivery Notes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/ETT_Delivery_Note__c/fields/ETT_Account__c.field-meta.xml
<CustomField>
    <fullName>ETT_Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Delivery Notes</relationshipLabel>
    <relationshipName>Delivery_Notes</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/ETT_Delivery_Note__c/fields/ETT_Collection_Card__c.field-meta.xml
<CustomField>
    <fullName>ETT_Collection_Card__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Collection Card</label>
    <referenceTo>ETT_Collection_Card__c</referenceTo>
    <relationshipLabel>Delivery Notes</relationshipLabel>
    <relationshipName>Delivery_Notes</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/ETT_Delivery_Note__c/fields/ETT_Service_Appointment__c.field-meta.xml
<CustomField>
    <fullName>ETT_Service_Appointment__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Service Appointment</label>
    <referenceTo>ServiceAppointment</referenceTo>
    <relationshipLabel>Delivery Notes</relationshipLabel>
    <relationshipName>Delivery_Notes</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/ETT_Delivery_Note__c/fields/ETT_Tyre_Size__c.field-meta.xml
<CustomField>
    <fullName>ETT_Tyre_Size__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Tyre Size</label>
    <referenceTo>ETT_Tyre_Size_Master__c</referenceTo>
    <relationshipLabel>Delivery Notes</relationshipLabel>
    <relationshipName>Delivery_Notes</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/ETT_Inspection_Card__c/ETT_Inspection_Card__c.object-meta.xml
<CustomObject>
    <description>This is for inspection for the customer who has been requested orders.</description>
    <label>Tyre Inspection Card</label>
    <nameField>
        <displayFormat>IC-{0000}</displayFormat>
        <label>Inspection Card Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Tyre Inspection Cards</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/ETT_Inspection_Card__c/fields/ETT_Account__c.field-meta.xml
<CustomField>
    <fullName>ETT_Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipName>Inspection_Cards</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/ETT_Inspection_Card__c/fields/ETT_Brand__c.field-meta.xml
<CustomField>
    <fullName>ETT_Brand__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Brand</label>
    <referenceTo>ETT_Brand_Master__c</referenceTo>
    <relationshipName>Inspection_Cards</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/ETT_Inspection_Card__c/fields/ETT_Collection_Card__c.field-meta.xml
<CustomField>
    <fullName>ETT_Collection_Card__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Collection Card</label>
    <referenceTo>ETT_Collection_Card__c</referenceTo>
    <relationshipName>Inspection_Cards</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/ETT_Inspection_Card__c/fields/ETT_Pattern__c.field-meta.xml
<CustomField>
    <fullName>ETT_Pattern__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Pattern</label>
    <referenceTo>ETT_Pattern_Master__c</referenceTo>
    <relationshipLabel>Tyre Inspection Cards</relationshipLabel>
    <relationshipName>Inspection_Cards1</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/ETT_Inspection_Card__c/fields/ETT_Service_Appointment__c.field-meta.xml
<CustomField>
    <fullName>ETT_Service_Appointment__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Service Appointment</label>
    <referenceTo>ServiceAppointment</referenceTo>
    <relationshipName>Inspection_Cards</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/ETT_Inspection_Card__c/fields/ETT_Status__c.field-meta.xml
<CustomField>
    <fullName>ETT_Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Not Inspected</fullName>
                <default>true</default>
                <label>Not Inspected</label>
            </value>
            <value>
                <fullName>Accept</fullName>
            </value>
            <value>
                <fullName>Send Back</fullName>
            </value>
            <value>
                <fullName>Scrap</fullName>
            </value>
            <value>
                <fullName>Accepted/No Warranty</fullName>
            </value>
            <value>
                <fullName>Pending</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/ETT_Inspection_Card__c/fields/ETT_Tyre_Size__c.field-meta.xml
<CustomField>
    <fullName>ETT_Tyre_Size__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Tyre Size</label>
    <referenceTo>ETT_Tyre_Size_Master__c</referenceTo>
    <relationshipName>Inspection_Cards</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/ETT_Job_Card__c/fields/Customer__c.field-meta.xml
<CustomField>
    <fullName>Customer__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Customer</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Job Cards</relationshipLabel>
    <relationshipName>Job_Cards</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/ETT_Tyre_Size_Master__c/ETT_Tyre_Size_Master__c.object-meta.xml
<CustomObject>
    <label>Tyre Size Master</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Tyre Sizes</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Tyre Size Master</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/ETT_Tyre_Size_Master__c/fields/ETT_Tyre_Size__c.field-meta.xml
<CustomField>
    <fullName>ETT_Tyre_Size__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Tyre size</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/classes/ETT_DeliveryNoteController.cls
public class ETT_DeliveryNoteController {
    
    @AuraEnabled 
    public static user fetchUser(){
      User oUser = [select id,Name,TimeZoneSidKey,Username,Alias,Country,Email,FirstName,LastName,IsActive,IsPortalEnabled 
                 FROM User Where id =: userInfo.getUserId()];
        return oUser;
    }
    
    @AuraEnabled        
    public static List<ETT_Inspection_Card__c> getJobCardIntoList(Id accountId){
        
        Set<Id> collectionCardIdsSet = new Set<Id>();
        Set<Id> inspectionCardIdsSet = new Set<Id>();        
        Id ccId;
        List<ETT_Inspection_Card__c> lstInspectionnCard = [SELECT Id, ETT_Collection_Card__c,ETT_Status__c,(select Id,ETT_Job_Stages__c from Job_Cards__r where (ETT_Job_Stages__c='Painting' and ETT_Painting_End_Time__c!=null) or ETT_Failed_Stage__c!='')
                                                           FROM ETT_Inspection_Card__c where ETT_Account__c = :accountId and 
                                                           Id not in (SELECT ETT_Inspection_Card__c FROM ETT_Delivery_Line_Item__c) and 
                                                           ETT_Collection_Card__r.ETT_Inspection_Done__c=true];
        
        System.debug('lstInspectionnCard: '+lstInspectionnCard);
        
        if(lstInspectionnCard!=null && lstInspectionnCard.size()>0){
            for(ETT_Inspection_Card__c IC:lstInspectionnCard){
                
                if(IC.ETT_Status__c=='Send Back' || (IC.Job_Cards__r.size()>0)) {
                    collectionCardIdsSet.add(IC.ETT_Collection_Card__c);
                    inspectionCardIdsSet.add(IC.Id);
                }
            }
        }
        System.debug('collectionCardIdsSet: '+collectionCardIdsSet);

        List<ETT_Delivery_Line_Item__c> lstDeliveryLineItems = [SELECT Id, ETT_Collection_Card__c, ETT_Collection_Card__r.ETT_Service_Appointment__c, ETT_Collection_Card__r.ETT_Phone__c ,ETT_Collection_Card__r.ETT_Vehicle_Detail__r.name FROM ETT_Delivery_Line_Item__c where ETT_Collection_Card__c in :collectionCardIdsSet];
         
        if(collectionCardIdsSet.isEmpty()){
            throw new AuraHandledException('There is no Delivery Note Pending for this account');            
        }
        /*
        if(lstDeliveryLineItems!=null && lstDeliveryLineItems.size() > 0){
            throw new AuraHandledException('There is no Delivery Note Pending for this account');
        }
        */
        return [select Id,Name,ETT_Account__r.Party_Type__c,ETT_Tyre_Size__c,ETT_Tyre_Size__r.Name,ETT_Brand__c,ETT_Brand__r.Name,ETT_Pattern__c,
                ETT_Pattern__r.Name,ETT_Tyre_Serial_Number__c,ETT_Status__c,ETT_Collection_Card__r.Name,ETT_Collection_Card__c,ETT_Collection_Card__r.ETT_Phone__c ,ETT_Collection_Card__r.ETT_Vehicle_Detail__r.name,ETT_Collection_Card__r.ETT_Service_Appointment__c,
                (select Id,ETT_Job_Stages__c,ETT_Failed_Stage__c,ETT_Failed_Reason__c from Job_Cards__r where ETT_Job_Stages__c!='Painting') 
                From ETT_Inspection_Card__c where Id in :inspectionCardIdsSet];
        
    }
    
    
    
    @AuraEnabled        
    public static List<ETT_Inspection_Card__c> getJobCardIntoListForPrint(Id accountId){
        return [select Id,ETT_Tyre_Size__c,ETT_Tyre_Size__r.Name,ETT_Brand__c,ETT_Brand__r.Name,ETT_Pattern__c,
                ETT_Pattern__r.Name,ETT_Tyre_Serial_Number__c,ETT_Status__c,ETT_Collection_Card__r.Name,ETT_Collection_Card__r.ETT_Service_Appointment__c,
                (select Id,ETT_Job_Stages__c,ETT_Failed_Stage__c,ETT_Failed_Reason__c from Job_Cards__r where ETT_Job_Stages__c!='Painting') 
                From ETT_Inspection_Card__c where ETT_Account__c = :accountId and ETT_Status__c='Send Back'];
    }
    
    @AuraEnabled  
    public static String submitDeliveryNote(map<string,string> mapOfObjects){
        system.debug('*****mapOfObjects*******'+mapOfObjects);
        
        ETT_Delivery_Note__c objDeliveryNote;
        list<ETT_Delivery_Line_Item__c> lstDeliveryLineItem; 
        
        if(mapOfObjects.containskey('deliveryNoteJson')){
            objDeliveryNote = (ETT_Delivery_Note__c) JSON.deserialize(mapOfObjects.get('deliveryNoteJson'),Type.forname('ETT_Delivery_Note__c'));
        }
        if(mapOfObjects.containskey('deliveryLineItemJson')){
            lstDeliveryLineItem =  (list<ETT_Delivery_Line_Item__c>)JSON.deserialize(mapOfObjects.get('deliveryLineItemJson'),Type.forname('list<ETT_Delivery_Line_Item__c>'));
        }
        
        if(objDeliveryNote!=null){
            
            try{
                Id customerRecordTypeId = Schema.SObjectType.ETT_Delivery_Note__c .getRecordTypeInfosByName().get('Tyre - Customer').getRecordTypeId();
                Id supplierRecordTypeId = Schema.SObjectType.ETT_Delivery_Note__c .getRecordTypeInfosByName().get('Tyre - Supplier').getRecordTypeId();
                System.debug('objDeliveryNote: '+objDeliveryNote);
                if(objDeliveryNote.ETT_Casing__c == 'Supplier Casing'){
                    objDeliveryNote.RecordTypeId = supplierRecordTypeId;
                }
                else  if(objDeliveryNote.ETT_Casing__c == 'Customer Casing')
                {
                    objDeliveryNote.RecordTypeId = customerRecordTypeId;                    
                }
                insert objDeliveryNote;
                System.debug('objDeliveryNote.Id: '+objDeliveryNote.Id);
            }Catch(Exception ex){
                system.debug('******Exception Cause *****'+ex.getMessage());
                throw new AuraHandledException(ex.getMessage());
            }
            
            if(objDeliveryNote.Id!=null){
                
                list<Sobject> lstSobjectInformation = new list<Sobject>();
                list<Sobject> lstUpdateSobjectInformation = new list<Sobject>();
                
                if(lstDeliveryLineItem!=null && lstDeliveryLineItem.size()>0){
                    for(ETT_Delivery_Line_Item__c objDeliveryLineItem :lstDeliveryLineItem){
                   
                        if(objDeliveryLineItem.ETT_Delivery_Note__c==null){
                            objDeliveryLineItem.ETT_Delivery_Note__c = objDeliveryNote.Id;
                        }
                        
                        if(objDeliveryLineItem.Id!=null){
                            lstUpdateSobjectInformation.add((Sobject)objDeliveryLineItem);
                        }else{
                            lstSobjectInformation.add((Sobject)objDeliveryLineItem);
                        }
                        
                    }     
                 }
                
                if(lstSobjectInformation!=null && lstSobjectInformation.size()>0){
                    try{
                        System.debug(lstSobjectInformation);
                        insert lstSobjectInformation;
                        return objDeliveryNote.Id;
                    }Catch(Exception ex){
                        system.debug('***Exception Cause *****'+ex.getMessage());
                        throw new AuraHandledException(ex.getMessage());
                    }
                }
                
                if(lstUpdateSobjectInformation!=null && lstUpdateSobjectInformation.size()>0){
                    try{
                        update lstUpdateSobjectInformation;
                        return objDeliveryNote.Id;
                    }Catch(Exception ex){
                        system.debug('***Exception Cause *****'+ex.getMessage());
                        throw new AuraHandledException(ex.getMessage());
                    }
                }else if(objDeliveryNote!=null && objDeliveryNote.Id!=null){
                    return objDeliveryNote.Id;
                }
                
                
            }
            
        }
        return '';
    }
    
    @AuraEnabled 
    public static String getPhoneFromAccount(id accountId){
      Account acc = [Select id,Phone from Account where id =:accountId];
       String phonenumber = '';
        if(acc.Phone!=null)
        {
           phonenumber = String.valueOf(acc.Phone); 
        }
         
        
        return phonenumber;
    }
    
}