unpackaged/main/default/objects/Account/recordTypes/Inspection.recordType-meta.xml
<RecordType>
    <fullName>Inspection</fullName>
    <active>true</active>
    <label>Inspection</label>
</RecordType>

unpackaged/main/default/objects/ET_Customer_Vehicle__c/ET_Customer_Vehicle__c.object-meta.xml
<CustomObject>
    <label>Customer Vehicle</label>
    <nameField>
        <displayFormat>CV-{000000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Customer Vehicles</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/ET_Customer_Vehicle__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Customer Vehicles</relationshipLabel>
    <relationshipName>Customer_Vehicles</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/ET_Customer_Vehicle__c/fields/Chassis_No__c.field-meta.xml
<CustomField>
    <fullName>Chassis_No__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Chassis No</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/ET_Customer_Vehicle__c/fields/Plate_Color__c.field-meta.xml
<CustomField>
    <fullName>Plate_Color__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Plate Color</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/ET_Customer_Vehicle__c/fields/Plate_No__c.field-meta.xml
<CustomField>
    <fullName>Plate_No__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Plate No</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/ET_Location__c/ET_Location__c.object-meta.xml
<CustomObject>
    <label>Inspection Center</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>ET Loaction Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Inspection Centers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/ET_Location__c/fields/ETSALES_Emirates__c.field-meta.xml
<CustomField>
    <fullName>ETSALES_Emirates__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Emirates</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/ET_Service_Request__c/ET_Service_Request__c.object-meta.xml
<CustomObject>
    <label>Service Request</label>
    <nameField>
        <displayFormat>SR-{000000}</displayFormat>
        <label>Service Request Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Service Requests</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

unpackaged/main/default/objects/ET_Service_Request__c/fields/ET_Account__c.field-meta.xml
<CustomField>
    <fullName>ET_Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Service Requests (Account)</relationshipLabel>
    <relationshipName>Service_Requests</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/ET_Service_Request__c/fields/ET_Location__c.field-meta.xml
<CustomField>
    <fullName>ET_Location__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Location</label>
    <referenceTo>ET_Location__c</referenceTo>
    <relationshipLabel>Service Requests</relationshipLabel>
    <relationshipName>Service_Requests</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/ETI_Booking__c/ETI_Booking__c.object-meta.xml
<CustomObject>
    <label>Booking</label>
    <nameField>
        <displayFormat>B-{000000}</displayFormat>
        <label>Booking</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Bookings</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

unpackaged/main/default/objects/ETI_Booking__c/fields/Booking_Date__c.field-meta.xml
<CustomField>
    <fullName>Booking_Date__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Booking Date</label>
    <type>Date</type>
</CustomField>

unpackaged/main/default/objects/ETI_Booking__c/fields/Booking_Status__c.field-meta.xml
<CustomField>
    <fullName>Booking_Status__c</fullName>
    <label>Booking Status</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Draft</fullName>
            </value>
            <value>
                <fullName>Booked</fullName>
            </value>
            <value>
                <fullName>Inspection Completed</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
            <value>
                <fullName>Due for Retest</fullName>
            </value>
            <value>
                <fullName>Applied for Retest</fullName>
            </value>
            <value>
                <fullName>Confirmed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/ETI_Booking__c/fields/Chassis_No__c.field-meta.xml
<CustomField>
    <fullName>Chassis_No__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Chassis No</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/ETI_Booking__c/fields/Customer_Vehicle__c.field-meta.xml
<CustomField>
    <fullName>Customer_Vehicle__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Customer Vehicle</label>
    <referenceTo>ET_Customer_Vehicle__c</referenceTo>
    <relationshipLabel>Bookings</relationshipLabel>
    <relationshipName>Bookings</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/ETI_Booking__c/fields/ET_Location__c.field-meta.xml
<CustomField>
    <fullName>ET_Location__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Location</label>
    <referenceTo>ET_Location__c</referenceTo>
    <relationshipLabel>Bookings</relationshipLabel>
    <relationshipName>Bookings</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/ETI_Booking__c/fields/Plate_No__c.field-meta.xml
<CustomField>
    <fullName>Plate_No__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Plate No</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/ETI_Booking__c/fields/Service_Request__c.field-meta.xml
<CustomField>
    <fullName>Service_Request__c</fullName>
    <label>Service Request</label>
    <referenceTo>ET_Service_Request__c</referenceTo>
    <relationshipLabel>Bookings</relationshipLabel>
    <relationshipName>Bookings</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

unpackaged/main/default/objects/ETI_Booking__c/fields/Test_Result__c.field-meta.xml
<CustomField>
    <fullName>Test_Result__c</fullName>
    <label>Test Result</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Pending</fullName>
                <default>true</default>
                <label>Pending</label>
            </value>
            <value>
                <fullName>Failed</fullName>
            </value>
            <value>
                <fullName>Pass</fullName>
            </value>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>Rejected</fullName>
            </value>
            <value>
                <fullName>No Show</fullName>
            </value>
            <value>
                <fullName>Partially Approved</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/ETI_Service_Line_Item__c/ETI_Service_Line_Item__c.object-meta.xml
<CustomObject>
    <label>Booking Line Item</label>
    <nameField>
        <displayFormat>SVC-{00000}</displayFormat>
        <label>Service Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Booking Line Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

unpackaged/main/default/objects/ETI_Service_Line_Item__c/fields/Booking__c.field-meta.xml
<CustomField>
    <fullName>Booking__c</fullName>
    <label>Booking</label>
    <referenceTo>ETI_Booking__c</referenceTo>
    <relationshipLabel>Booking Line Items</relationshipLabel>
    <relationshipName>Services</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

unpackaged/main/default/objects/ETI_Service_Line_Item__c/fields/Chassis_No__c.field-meta.xml
<CustomField>
    <fullName>Chassis_No__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Chassis No</label>
    <length>150</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/ETI_Service_Line_Item__c/fields/Plate_Color__c.field-meta.xml
<CustomField>
    <fullName>Plate_Color__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Plate Color</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/ETI_Service_Line_Item__c/fields/Service_Type__c.field-meta.xml
<CustomField>
    <fullName>Service_Type__c</fullName>
    <label>Service Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Police Inspection</fullName>
            </value>
            <value>
                <fullName>Certificate</fullName>
            </value>
            <value>
                <fullName>ADFCA</fullName>
            </value>
            <value>
                <fullName>SPEA Inspection</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/ETI_Service_Line_Item__c/fields/Test_Date__c.field-meta.xml
<CustomField>
    <fullName>Test_Date__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Test Date</label>
    <type>DateTime</type>
</CustomField>

unpackaged/main/default/objects/ETI_Service_Line_Item__c/fields/Test_Result__c.field-meta.xml
<CustomField>
    <fullName>Test_Result__c</fullName>
    <label>Test Result</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Pending</fullName>
            </value>
            <value>
                <fullName>Pass</fullName>
            </value>
            <value>
                <fullName>Failed</fullName>
            </value>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>Rejected</fullName>
            </value>
            <value>
                <fullName>No Show</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Service_Type__c/Service_Type__c.object-meta.xml
<CustomObject>
    <label>Service Type</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Service Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Service Types</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/classes/ETI_ServiceLineItemHandlerTest.cls
@isTest
public class ETI_ServiceLineItemHandlerTest {
    private static testmethod void testmethodInspection(){
        Set<Id> vSetSLIIds = new Set<Id>();
        Account acc = new Account();
        acc.Name = 'Test Account';
        insert acc;
        
        ET_Service_Request__c serviceRequest = new ET_Service_Request__c();
        serviceRequest.ET_Account__c = acc.Id;
        insert serviceRequest;
        
        ET_Location__c locationObj = new ET_Location__c();
        locationObj.Name = 'Abu Dhabi';
        insert locationObj;
        
        ET_Customer_Vehicle__c customerVehicle = new ET_Customer_Vehicle__c();
        customerVehicle.Account__c = acc.Id;
        customerVehicle.Chassis_No__c = '43235';
        customerVehicle.Plate_Color__c='red';
        customerVehicle.Plate_No__c='4512';
        insert customerVehicle;
        
        List<ETI_Booking__c>  bookinlist = new List<ETI_Booking__c>();
        ETI_Booking__c objBooking = new ETI_Booking__c();
        objBooking.ET_Location__c = locationObj.Id;
        objBooking.Service_Request__c = serviceRequest.Id;
        objBooking.Booking_Date__c = Date.valueOf('2020-07-21');
        objBooking.Service_Type__c = 'Police Inspection';
        objBooking.ET_Location__c=locationObj.ETSALES_Emirates__c;
        objBooking.Customer_Vehicle__c = customerVehicle.Id;
        objBooking.Booking_Status__c = 'Booked';
        objBooking.Plate_No__c=customerVehicle.Plate_No__c;
        objBooking.Plate_Color__c=customerVehicle.Plate_Color__c;
        objBooking.Chassis_No__c=customerVehicle.Chassis_No__c;
        insert objBooking;
        objBooking.Test_Result__c='Pass';
        update objBooking;
        
        List<ETI_Service_Line_Item__c> newList = new List<ETI_Service_Line_Item__c> ();
        ETI_Service_Line_Item__c serviceline = new ETI_Service_Line_Item__c();
        serviceline.Booking__c=objBooking.Id;
        serviceline.Test_Result__c='Pass';
        serviceline.Test_Date__c=datetime.newInstance(2021, 9, 15, 12, 30, 0);
        insert serviceline;
        vSetSLIIds.add(serviceline.Id);
        
        serviceline.Test_Result__c='Fail';
        update serviceline;
        serviceline.Test_Result__c='Pass';
        update serviceline;
        serviceline.Test_Result__c='No';
        update serviceline;
    }
}