unpackaged/main/default/objects/Account/recordTypes/Inspection.recordType-meta.xml
<RecordType>
    <fullName>Inspection</fullName>
    <active>true</active>
    <label>Inspection</label>
</RecordType>

unpackaged/main/default/objects/ET_Customer_Vehicle__c/ET_Customer_Vehicle__c.object-meta.xml
<CustomObject>
    <label>Customer Vehicle</label>
    <nameField>
        <displayFormat>CV-{000000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Customer Vehicles</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/ET_Customer_Vehicle__c/fields/Chassis_No__c.field-meta.xml
<CustomField>
    <fullName>Chassis_No__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Chassis No</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/ET_Customer_Vehicle__c/fields/Plate_No__c.field-meta.xml
<CustomField>
    <fullName>Plate_No__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Plate No</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/ET_Customer_Vehicle__c/fields/Registration_Type__c.field-meta.xml
<CustomField>
    <fullName>Registration_Type__c</fullName>
    <label>Registration Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Registered</fullName>
            </value>
            <value>
                <fullName>Un-Registered</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/ET_Customer_Vehicle__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <defaultValue>&quot;Active&quot;</defaultValue>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Active</fullName>
            </value>
            <value>
                <fullName>Frozen</fullName>
            </value>
            <value>
                <fullName>Inactive</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/ET_Service_Request__c/ET_Service_Request__c.object-meta.xml
<CustomObject>
    <label>Service Request</label>
    <nameField>
        <displayFormat>SR-{000000}</displayFormat>
        <label>Service Request Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Service Requests</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

unpackaged/main/default/objects/ET_Service_Request__c/fields/ET_Account__c.field-meta.xml
<CustomField>
    <fullName>ET_Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Service Requests (Account)</relationshipLabel>
    <relationshipName>Service_Requests</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/ET_Service_Request__c/fields/Payment_Status__c.field-meta.xml
<CustomField>
    <fullName>Payment_Status__c</fullName>
    <label>Payment Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Not Initiated</fullName>
            </value>
            <value>
                <fullName>Payment Pending</fullName>
            </value>
            <value>
                <fullName>Payment Success</fullName>
            </value>
            <value>
                <fullName>Refund Requested</fullName>
            </value>
            <value>
                <fullName>Await3D</fullName>
            </value>
            <value>
                <fullName>Captured</fullName>
            </value>
            <value>
                <fullName>Partially Paid</fullName>
            </value>
            <value>
                <fullName>Fully Paid</fullName>
            </value>
            <value>
                <fullName>Refund Cancelled</fullName>
            </value>
            <value>
                <fullName>Failed</fullName>
            </value>
            <value>
                <fullName>Reversed</fullName>
            </value>
            <value>
                <fullName>On Premise Requested</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/ETI_Booking__c/ETI_Booking__c.object-meta.xml
<CustomObject>
    <label>Booking</label>
    <nameField>
        <displayFormat>B-{000000}</displayFormat>
        <label>Booking</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Bookings</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

unpackaged/main/default/objects/ETI_Booking__c/fields/Booking_Status__c.field-meta.xml
<CustomField>
    <fullName>Booking_Status__c</fullName>
    <label>Booking Status</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Draft</fullName>
            </value>
            <value>
                <fullName>Booked</fullName>
            </value>
            <value>
                <fullName>Inspection Completed</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
            <value>
                <fullName>Due for Retest</fullName>
            </value>
            <value>
                <fullName>Applied for Retest</fullName>
            </value>
            <value>
                <fullName>Confirmed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/ETI_Booking__c/fields/Chassis_No__c.field-meta.xml
<CustomField>
    <fullName>Chassis_No__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Chassis No</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/ETI_Booking__c/fields/Customer_Vehicle__c.field-meta.xml
<CustomField>
    <fullName>Customer_Vehicle__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Customer Vehicle</label>
    <referenceTo>ET_Customer_Vehicle__c</referenceTo>
    <relationshipLabel>Bookings</relationshipLabel>
    <relationshipName>Bookings</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/ETI_Booking__c/fields/Payment_Status__c.field-meta.xml
<CustomField>
    <fullName>Payment_Status__c</fullName>
    <formula>Text(Service_Request__r.Payment_Status__c )</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Payment Status</label>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/ETI_Booking__c/fields/Plate_No__c.field-meta.xml
<CustomField>
    <fullName>Plate_No__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Plate No</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/ETI_Booking__c/fields/Registration_Type__c.field-meta.xml
<CustomField>
    <fullName>Registration_Type__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Registration Type</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/ETI_Booking__c/fields/Service_Request__c.field-meta.xml
<CustomField>
    <fullName>Service_Request__c</fullName>
    <label>Service Request</label>
    <referenceTo>ET_Service_Request__c</referenceTo>
    <relationshipLabel>Bookings</relationshipLabel>
    <relationshipName>Bookings</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

unpackaged/main/default/classes/ETI_DraftBookingDeletionBatchTest.cls
@isTest
public class ETI_DraftBookingDeletionBatchTest {
    
    private static testmethod void testmethodInspection(){
        
        ET_Customer_Vehicle__c ObjCustomerVehicle = new ET_Customer_Vehicle__c();
        ObjCustomerVehicle.OwnerId = UserInfo.getUserId();
        ObjCustomerVehicle.Chassis_No__c = 'D032B5GC000790';
        ObjCustomerVehicle.Plate_No__c = '';
        ObjCustomerVehicle.status__c = 'Active';
        ObjCustomerVehicle.Registration_Type__c ='Registered';
        insert ObjCustomerVehicle;
        
        Id recordTypeId = Schema.SObjectType.Account.getRecordTypeInfosByName().get('Person (B2C)').getRecordTypeId();
        Account acc = new Account();
        acc.FirstName = 'test';
        acc.LastName = 'test';
        acc.PersonEmail = 'test@gmail.com';
        acc.RecordTypeId = recordTypeId;
        
        insert acc;
        
        
         Contact con = new Contact();
        con.LastName = 'Noor';
        con.Email = Label.ETI_TargetObject_Email;
        insert con;
        
        
        Id recordTypeId2 = Schema.SObjectType.ET_Service_Request__c.getRecordTypeInfosByName().get('Vehicle Inspection').getRecordTypeId();
        
        ET_Service_Request__c objServiceRequest = new ET_Service_Request__c();
        objServiceRequest.Payment_Status__c = 'Not Initiated';
        objServiceRequest.RecordTypeId = recordTypeId2;
        objServiceRequest.ET_Account__c = acc.id;
        insert objServiceRequest;
        
        ETI_Booking__c objBooking = new ETI_Booking__c();
        objBooking.Booking_Status__c = 'Draft';
        objBooking.Service_Request__c = objServiceRequest.Id;
        objBooking.Customer_Vehicle__c = ObjCustomerVehicle.Id;
        insert objBooking;
        
        ETI_DraftBookingDeletionBatch etbb = new ETI_DraftBookingDeletionBatch();
        
        test.startTest();
        
        Database.executeBatch(etbb);
        
        Test.stopTest();
    }
    
}