unpackaged/main/default/objects/ET_Oracle_REST_Endpoints__mdt/ET_Oracle_REST_Endpoints__mdt.object-meta.xml
<CustomObject>
    <description>This meta data created to store all the REST endpoint and authentication details</description>
    <label>ET_Oracle_REST_Endpoint</label>
    <pluralLabel>ET_Oracle_REST_Endpoints</pluralLabel>
</CustomObject>

unpackaged/main/default/objects/ET_Oracle_REST_Endpoints__mdt/fields/Dev_Endpoint__c.field-meta.xml
<CustomField>
    <fullName>Dev_Endpoint__c</fullName>
    <label>Dev Endpoint</label>
    <type>Url</type>
</CustomField>

unpackaged/main/default/objects/ET_Oracle_REST_Endpoints__mdt/fields/LiveEndpoint_c__c.field-meta.xml
<CustomField>
    <fullName>LiveEndpoint_c__c</fullName>
    <label>Live Endpoint</label>
    <type>Url</type>
</CustomField>

unpackaged/main/default/classes/ET_REST_Authorize_Helper.cls
/*
* File Name:ET_REST_Authorize_Helper
* Author : Smaartt
* CreatedDate : 30/05/2021
* Modification Purpose
* * 1. Janardhan: Utility class to available for all the Check in check out services
*/
public class ET_REST_Authorize_Helper {
    
     public static ET_Oracle_REST_Endpoints__mdt getSOAPEndpointFromMetadata(string DeveloperName){
       
        return [SELECT Id,Dev_Endpoint__c,LiveEndpoint_c__c,Password__c,Username__c FROM ET_Oracle_REST_Endpoints__mdt where DeveloperName=:DeveloperName];
    }
    
    public static boolean runningInASandbox(){
        return [SELECT IsSandbox FROM Organization LIMIT 1].IsSandbox;
    }
    
  

}