unpackaged/main/default/objects/Lead/fields/Appointment_Date__c.field-meta.xml
<CustomField>
    <fullName>Appointment_Date__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Appointment Date</label>
    <type>DateTime</type>
</CustomField>

unpackaged/main/default/objects/Lead/fields/Appointment_Status__c.field-meta.xml
<CustomField>
    <fullName>Appointment_Status__c</fullName>
    <label>Appointment Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Confirmed</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
            <value>
                <fullName>Rescheduled</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Lead/fields/Mobile_Number__c.field-meta.xml
<CustomField>
    <fullName>Mobile_Number__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Mobile Number</label>
    <type>Phone</type>
</CustomField>

unpackaged/main/default/classes/Moto_Lead_Appointment_Reminder_Test.cls
@isTest
public class Moto_Lead_Appointment_Reminder_Test {
    
    public static testMethod void testschedule() {
        Test.StartTest();
        lead le =new lead();
        le.LastName = 'test';
        le.Email ='test@gmail.com';
        le.LeadSource='Website';
        le.RecordTypeId = Schema.SObjectType.Lead.getRecordTypeInfosByName().get('Automotive Dealership - Vehicle Inquiry/Trade-In').getRecordTypeId();
        le.Mobile_Number__c ='+971558656023';
        le.Appointment_Date__c = system.now();
        le.Appointment_Status__c='Confirmed';
        insert le;   
        Test.setMock(HttpCalloutMock.class, new Moto_SMS_MockHttpResponseGenerator());
        Moto_Lead_Appointment_Reminder_Handler testsche = new Moto_Lead_Appointment_Reminder_Handler();
        String sch = '0 0 23 * * ?';
        system.schedule('Test status Check', sch, testsche );
        Test.stopTest();
    }
}