unpackaged/main/default/objects/Lead/fields/Appointment_Date__c.field-meta.xml
<CustomField>
    <fullName>Appointment_Date__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Appointment Date</label>
    <type>DateTime</type>
</CustomField>

unpackaged/main/default/objects/Lead/fields/Appointment_Status__c.field-meta.xml
<CustomField>
    <fullName>Appointment_Status__c</fullName>
    <label>Appointment Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Confirmed</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
            <value>
                <fullName>Rescheduled</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Lead/fields/Moto_msg_DateTime__c.field-meta.xml
<CustomField>
    <fullName>Moto_msg_DateTime__c</fullName>
    <formula>CASE(WEEKDAY(DATEVALUE(Appointment_Date__c )),
1,&#39;Sunday&#39;,
2,&#39;Monday&#39;,
3,&#39;Tuesday&#39;,
4,&#39;Wednesday&#39;,
5,&#39;Thursday&#39;,
6,&#39;Friday&#39;,
7,&#39;Saturday&#39;,
&#39;&#39;
)+&quot;, &quot;+CASE(MONTH(DATEVALUE(Appointment_Date__c)),
1, &quot;January&quot;,
2, &quot;February&quot;,
3, &quot;March&quot;, 
4, &quot;April&quot;, 
5, &quot;May&quot;, 
6, &quot;June&quot;,
7, &quot;July&quot;,
8, &quot;August&quot;,
9, &quot;September&quot;,
10, &quot;October&quot;,
11, &quot;November&quot;,
12, &quot;December&quot;,
&quot;None&quot;)+&quot; &quot;+Text(DAY(DATEVALUE(Appointment_Date__c)))+&quot;, &quot;+Moto_Time__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Moto Custom Date</label>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Lead/fields/Moto_Time__c.field-meta.xml
<CustomField>
    <fullName>Moto_Time__c</fullName>
    <formula>IF(HOUR( TIMEVALUE(Appointment_Date__c+(4/24))) == 0,&#39;12:&#39;+IF(MINUTE(TIMEVALUE(Appointment_Date__c))&lt;10,&#39;0&#39;+TEXT(MINUTE(TIMEVALUE(Appointment_Date__c))),TEXT(MINUTE(TIMEVALUE(Appointment_Date__c)))),If(HOUR( TIMEVALUE(Appointment_Date__c+(4/24))) &lt;=12, LEFT(Text(TIMEVALUE( Appointment_Date__c+(4/24))),5),LEFT(Text(TIMEVALUE( Appointment_Date__c -(8/24))),5) ))+&#39; &#39;+IF(HOUR(TIMEVALUE(Appointment_Date__c+(4/24))) &gt;=12,&#39;PM&#39;,&#39;AM&#39;)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Moto Time</label>
    <type>Text</type>
</CustomField>

unpackaged/main/default/classes/Moto_Lead_Appointment_Reminder_Handler.cls
/**
* Author: Janardhan Muddana
* CreatedDate: 19/07/2022
* Desc: this is used to send sms/eamil msg to customer using smsshastra api at 9 AM on appointment date
* TestClass:Moto_Lead_Appointment_Reminder_Test
* */
global class Moto_Lead_Appointment_Reminder_Handler Implements Schedulable{
    
    global void execute(SchedulableContext sc){
        sendReminder();
    }
    public static void sendReminder(){
        Messaging.SingleEmailMessage[] emailList = new list<Messaging.SingleEmailMessage>();
        EmailTemplate template = [SELECT Id,Subject,DeveloperName, Body FROM EmailTemplate WHERE DeveloperName ='Lead_Appointment_Reminder'];
        list<OrgWideEmailAddress> owea = [SELECT Id, Address, DisplayName FROM OrgWideEmailAddress WHERE Address=:system.label.Moto_OrgWideEmail];
        
        for(lead le : [select id,name,MobilePhone,email,Appointment_Date__c,Moto_Time__c,Moto_msg_DateTime__c from lead where Appointment_Date__c=Today AND (Appointment_Status__c='Confirmed' OR Appointment_Status__c='Rescheduled')]){
            
            string composedMsg = 'Dear '+le.Name+', this is a friendly reminder for your appointment today at  '+le.Moto_Time__c+'.  Here\'s the link to your branch bit.ly/3PKHKZH and we look forward to seeing you';
            
            if(le.MobilePhone != null && le.MobilePhone.length() >= 9 ){
                system.debug('SMSAPI');
                sendSMSAPI(le.MobilePhone,composedMsg,system.label.Moto_SMS_SenderID);
            }  
            //SendEmail Msg
            
            Messaging.SingleEmailMessage email = Messaging.renderStoredEmailTemplate(template.Id,null,le.Id);
            email.toAddresses = new list<string>{le.email};
                if ( owea != null && owea.size() > 0 ) {
                    email.setOrgWideEmailAddressId(owea.get(0).Id);
                }              
            email.setSaveAsActivity(false);             
            email.setWhatId(le.Id);
            
            emailList.add(email);
        }
        Messaging.SendEmailResult[] results = Messaging.sendEmail(emailList);
    }
    @future(callout = true)
    public static void sendSMSAPI(String mobNumber,String msg,String SenderId){
        
        string mobile = '';
        string finalmsg = msg.replace(' ','%20');   
        
        //Check Mobile Number Format
        mobile = mobNumber.replaceAll('[A-Za-z]', '');//remove any alphabets
        mobile = '971'+mobNumber.right(9);//It works for UAE Country only
        
        HttpRequest request = new HttpRequest();
        request.setEndpoint(system.label.Moto_SMS_EndpointURL+'senderid='+SenderId+'&mobileno='+mobile+'&msgtext='+finalmsg+'&priority=High&CountryCode=ALL');
        request.setMethod('GET');
        
        Http http = new Http();
        HttpResponse response = http.send(request);
        system.debug(response);
        
    }
    
}