unpackaged/main/default/objects/Lead/fields/ETSALES_Lead_Rating__c.field-meta.xml
<CustomField>
    <fullName>ETSALES_Lead_Rating__c</fullName>
    <label>Prospect Rating</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Hot</fullName>
            </value>
            <value>
                <fullName>Warm</fullName>
            </value>
            <value>
                <fullName>Cold</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Lead/fields/ETSALES_Lead_Type__c.field-meta.xml
<CustomField>
    <fullName>ETSALES_Lead_Type__c</fullName>
    <label>Prospect Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Prospect_Type</valueSetName>
    </valueSet>
</CustomField>

unpackaged/main/default/globalValueSets/Prospect_Type.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>General Prospect</fullName>
    </customValue>
    <customValue>
        <fullName>Marketing Lead</fullName>
    </customValue>
    <customValue>
        <fullName>Existing Customer Request</fullName>
    </customValue>
    <customValue>
        <fullName>Customer Penetration</fullName>
    </customValue>
    <customValue>
        <fullName>Other</fullName>
    </customValue>
    <customValue>
        <fullName>Tender</fullName>
    </customValue>
    <customValue>
        <fullName>Project</fullName>
    </customValue>
    <customValue>
        <fullName>Enquiry</fullName>
        <default>true</default>
        <label>Enquiry</label>
    </customValue>
    <customValue>
        <fullName>Joint Buyer</fullName>
        <isActive>false</isActive>
        <label>Joint Buyer</label>
    </customValue>
    <customValue>
        <fullName>Business Introducer</fullName>
        <isActive>false</isActive>
        <label>Business Introducer</label>
    </customValue>
    <customValue>
        <fullName>Client</fullName>
        <isActive>false</isActive>
        <label>Client</label>
    </customValue>
    <masterLabel>Prospect Type</masterLabel>
</GlobalValueSet>

unpackaged/main/default/classes/ETSALES_SocialPostTriggerHandler_Test.cls
@isTest
public class ETSALES_SocialPostTriggerHandler_Test {
    
    private static testmethod void testUpdateLeadRecordType(){
        
        Lead ld = new Lead();
        ld.LastName = 'TestLname';
        ld.FirstName='TestFname';
        ld.Email = 'Testmail@gmail.com';
        ld.MobilePhone = '123456789';
        ld.ETSALES_Lead_Type__c='Enquiry';
        ld.ETSALES_Lead_Rating__c='Hot';
        insert ld;
        
        SocialPost sp = new SocialPost();
        sp.Name = 'Test Post';
        sp.TopicProfileName = 'emiratesmoto';
        sp.WhoId = ld.Id;
        insert sp;
        
    }
}