unpackaged/main/default/objects/Lead/fields/Preferred_Location__c.field-meta.xml
<CustomField>
    <fullName>Preferred_Location__c</fullName>
    <label>Preferred Location</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Location</valueSetName>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Lead/fields/Request_Category__c.field-meta.xml
<CustomField>
    <fullName>Request_Category__c</fullName>
    <label>Request Category</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Passenger Transportation</fullName>
            </value>
            <value>
                <fullName>School Transportation</fullName>
            </value>
            <value>
                <fullName>Lease</fullName>
            </value>
            <value>
                <fullName>Maintenance and Technical services</fullName>
            </value>
            <value>
                <fullName>General inquiry</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/globalValueSets/Location.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Abu Dhabi</fullName>
    </customValue>
    <customValue>
        <fullName>Ajman</fullName>
    </customValue>
    <customValue>
        <fullName>Dubai</fullName>
    </customValue>
    <customValue>
        <fullName>Fujairah</fullName>
    </customValue>
    <customValue>
        <fullName>Ras Al Khaimah</fullName>
    </customValue>
    <customValue>
        <fullName>Sharjah</fullName>
    </customValue>
    <customValue>
        <fullName>Umm Al Quwain</fullName>
    </customValue>
    <customValue>
        <fullName>Emirates Moto Al Quoz</fullName>
    </customValue>
    <customValue>
        <fullName>Emirates Moto Profix – Sharjah</fullName>
    </customValue>
    <customValue>
        <fullName>Emirates Moto Profix – Al Quoz</fullName>
    </customValue>
    <customValue>
        <fullName>Emirates Moto Profix – RAK</fullName>
    </customValue>
    <customValue>
        <fullName>الشارقة</fullName>
        <isActive>false</isActive>
        <label>الشارقة</label>
    </customValue>
    <customValue>
        <fullName>Preferred Location</fullName>
        <isActive>false</isActive>
        <label>Preferred Location</label>
    </customValue>
    <customValue>
        <fullName>أم القيوين</fullName>
        <isActive>false</isActive>
        <label>أم القيوين</label>
    </customValue>
    <masterLabel>Location</masterLabel>
</GlobalValueSet>

unpackaged/main/default/classes/LeadTriggerHandler_Test.cls
@isTest
private class LeadTriggerHandler_Test {
    
    @isTest private static void method1(){
        Id recordTypeId = Schema.SObjectType.Lead.getRecordTypeInfosByDeveloperName().get('New_Business').getRecordTypeId(); 
        Lead l = new Lead(FirstName='Test First Name',MobilePhone = '971500000000',LastName='Test LastName', recordTypeId=recordTypeId, Request_Category__c ='General Inquiry', Preferred_Location__c = 'Dubai');
        Test.startTest();
        insert l;
        l.LeadSource = 'Website';
        update l;
        Test.stopTest();
     }
}