unpackaged/main/default/objects/ET_Quote_Item_SpecReq__c/ET_Quote_Item_SpecReq__c.object-meta.xml
<CustomObject>
    <label>Quote Item SpecReq</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Vehicle Quote Item SpecReq Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Quote Item SpecReqs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/ET_Quote_Item_SpecReq__c/fields/Line_Item_Number__c.field-meta.xml
<CustomField>
    <fullName>Line_Item_Number__c</fullName>
    <label>Line Item Number</label>
    <precision>3</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

unpackaged/main/default/objects/ET_Quote_Item_SpecReq__c/fields/Quote__c.field-meta.xml
<CustomField>
    <fullName>Quote__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Quote</label>
    <referenceTo>Quote</referenceTo>
    <relationshipLabel>Quote Item SpecReqs</relationshipLabel>
    <relationshipName>Quote_Item_SpecReqs</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/ET_Quote_Item_SpecReq__c/fields/Quote_Contract_Year__c.field-meta.xml
<CustomField>
    <fullName>Quote_Contract_Year__c</fullName>
    <label>Quote Contract Year</label>
    <precision>1</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

unpackaged/main/default/classes/ET_OtherCostCalcDetailsController.cls
public without sharing class ET_OtherCostCalcDetailsController {

    @AuraEnabled
    public static String ET_getotherCostCalcDetail(String quoteId){
        List<ET_Quote_Item_SpecReq__c> quoteItemList = [Select Name, ET_Cost__c, Line_Item_Number__c,Quote_Contract_Year__c from ET_Quote_Item_SpecReq__c where Quote__c =:quoteId Order by Quote_Contract_Year__c ASC, Line_Item_Number__c ASC];
        system.debug('xquoteItemList: '+quoteItemList);
        if(quoteItemList != null){
        	return JSON.serialize(quoteItemList,true);
        }else{
            return null;
        }
    }
}