unpackaged/main/default/objects/Case/fields/Assigned_To__c.field-meta.xml
<CustomField>
    <fullName>Assigned_To__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Assigned To</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Assigned_To</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Case/fields/Case_Types__c.field-meta.xml
<CustomField>
    <fullName>Case_Types__c</fullName>
    <label>Case Types</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Cancel Service</fullName>
            </value>
            <value>
                <fullName>Complaint and Follow up</fullName>
            </value>
            <value>
                <fullName>Follow up</fullName>
            </value>
            <value>
                <fullName>Get Services</fullName>
            </value>
            <value>
                <fullName>Inquires and Notices</fullName>
            </value>
            <value>
                <fullName>Notice</fullName>
            </value>
            <value>
                <fullName>Thankyou and appreciation</fullName>
            </value>
            <value>
                <fullName>Update Information</fullName>
            </value>
            <value>
                <fullName>Human Resource</fullName>
            </value>
            <value>
                <fullName>Services</fullName>
            </value>
            <value>
                <fullName>Online and Financial Services</fullName>
            </value>
            <value>
                <fullName>Request</fullName>
            </value>
            <value>
                <fullName>Quality and Compliance</fullName>
            </value>
            <value>
                <fullName>Traffic Violation</fullName>
            </value>
            <value>
                <fullName>Internal Issues</fullName>
            </value>
            <value>
                <fullName>Theft and Missing</fullName>
            </value>
            <value>
                <fullName>Safety Issue</fullName>
            </value>
            <value>
                <fullName>Accident/Emergency</fullName>
            </value>
            <value>
                <fullName>Request for Awareness Session</fullName>
            </value>
            <value>
                <fullName>Request for New Bus/Supervisors/Teachers Transfer</fullName>
            </value>
            <value>
                <fullName>Requests for New Trips Activities and Events</fullName>
            </value>
            <value>
                <fullName>Printing New Card - Student</fullName>
            </value>
            <value>
                <fullName>Printing New Card - Drivers &amp; Transportation Supervisors</fullName>
            </value>
            <value>
                <fullName>Evaluation of Schools/Services</fullName>
            </value>
            <value>
                <fullName>Others</fullName>
            </value>
            <value>
                <fullName>Bus is not on time</fullName>
            </value>
            <value>
                <fullName>Change the Bus stop as my kid is too young to reach the stop</fullName>
            </value>
            <value>
                <fullName>Bus didn&#39;t pick my kid</fullName>
            </value>
            <value>
                <fullName>My kid was bullied</fullName>
            </value>
            <value>
                <fullName>Driver behavior is bad</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Case/fields/CCM_Remarks__c.field-meta.xml
<CustomField>
    <fullName>CCM_Remarks__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>CCM Remarks</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

unpackaged/main/default/objects/Case/fields/Requestor__c.field-meta.xml
<CustomField>
    <fullName>Requestor__c</fullName>
    <label>Requestor</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Parent/Guardian</fullName>
            </value>
            <value>
                <fullName>Public Schools</fullName>
            </value>
            <value>
                <fullName>Staffs</fullName>
            </value>
            <value>
                <fullName>Ministries</fullName>
            </value>
            <value>
                <fullName>Private Schools</fullName>
            </value>
            <value>
                <fullName>ET staff</fullName>
            </value>
            <value>
                <fullName>Municipality/RTA/DoT</fullName>
            </value>
            <value>
                <fullName>Police</fullName>
            </value>
            <value>
                <fullName>General Public</fullName>
            </value>
            <value>
                <fullName>Private School Parents</fullName>
            </value>
            <value>
                <fullName>Customer</fullName>
            </value>
            <value>
                <fullName>Insurance Company</fullName>
            </value>
            <value>
                <fullName>AD Police</fullName>
            </value>
            <value>
                <fullName>ADFCA</fullName>
            </value>
            <value>
                <fullName>FUJAIRAH Police</fullName>
            </value>
            <value>
                <fullName>Hotels/Event team</fullName>
            </value>
            <value>
                <fullName>Dubai Police</fullName>
            </value>
            <value>
                <fullName>Sharjah Police</fullName>
            </value>
            <value>
                <fullName>Ajman Police</fullName>
            </value>
            <value>
                <fullName>Others</fullName>
            </value>
            <value>
                <fullName>Private</fullName>
            </value>
            <value>
                <fullName>Government</fullName>
            </value>
            <value>
                <fullName>Technical Service</fullName>
            </value>
            <value>
                <fullName>MUSADA</fullName>
            </value>
            <value>
                <fullName>Dry Wash Unite</fullName>
            </value>
            <value>
                <fullName>Watania</fullName>
            </value>
            <value>
                <fullName>CNG</fullName>
            </value>
            <value>
                <fullName>IT</fullName>
            </value>
            <value>
                <fullName>Finance</fullName>
            </value>
            <value>
                <fullName>HR</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Case/recordTypes/School_Transport.recordType-meta.xml
<RecordType>
    <fullName>School_Transport</fullName>
    <active>true</active>
    <businessProcess>Services</businessProcess>
    <label>School Transport</label>
</RecordType>

unpackaged/main/default/objects/Case/recordTypes/Services.recordType-meta.xml
<RecordType>
    <fullName>Services</fullName>
    <active>true</active>
    <businessProcess>Services</businessProcess>
    <description>الخدمات</description>
    <label>Services</label>
</RecordType>

unpackaged/main/default/objects/Contact/fields/ETSALES_Mob_Country_Code__c.field-meta.xml
<CustomField>
    <fullName>ETSALES_Mob_Country_Code__c</fullName>
    <label>Mob Country Code</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>ISD_Country_Code</valueSetName>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Contact/recordTypes/ETSALES_B2B_Contact.recordType-meta.xml
<RecordType>
    <fullName>ETSALES_B2B_Contact</fullName>
    <active>true</active>
    <label>B2B Contact</label>
</RecordType>

unpackaged/main/default/globalValueSets/ISD_Country_Code.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Aland Islands(+358)</fullName>
    </customValue>
    <customValue>
        <fullName>Albania(+355)</fullName>
    </customValue>
    <customValue>
        <fullName>Algeria(+213)</fullName>
    </customValue>
    <customValue>
        <fullName>American Samoa(+1-684)</fullName>
    </customValue>
    <customValue>
        <fullName>Angola(+244)</fullName>
    </customValue>
    <customValue>
        <fullName>Anguilla(+1-264)</fullName>
    </customValue>
    <customValue>
        <fullName>Antarctica(+672)</fullName>
    </customValue>
    <customValue>
        <fullName>Antigua and Barbuda(+1-268)</fullName>
    </customValue>
    <customValue>
        <fullName>Argentina(+54)</fullName>
    </customValue>
    <customValue>
        <fullName>Armenia(+374)</fullName>
    </customValue>
    <customValue>
        <fullName>Aruba(+297)</fullName>
    </customValue>
    <customValue>
        <fullName>Australia(+61)</fullName>
    </customValue>
    <customValue>
        <fullName>Austria(+43)</fullName>
    </customValue>
    <customValue>
        <fullName>Azerbaijan(+994)</fullName>
    </customValue>
    <customValue>
        <fullName>Bahamas(+1-242)</fullName>
    </customValue>
    <customValue>
        <fullName>Bahrain(+973)</fullName>
    </customValue>
    <customValue>
        <fullName>Bangladesh(+880)</fullName>
    </customValue>
    <customValue>
        <fullName>Barbados(+1-246)</fullName>
    </customValue>
    <customValue>
        <fullName>Belarus(+375)</fullName>
    </customValue>
    <customValue>
        <fullName>Belgium(+32)</fullName>
    </customValue>
    <customValue>
        <fullName>Belize(+501)</fullName>
    </customValue>
    <customValue>
        <fullName>Benin(+229)</fullName>
    </customValue>
    <customValue>
        <fullName>Bermuda(+1-441)</fullName>
    </customValue>
    <customValue>
        <fullName>Bhutan(+975)</fullName>
    </customValue>
    <customValue>
        <fullName>Bolivia(+591)</fullName>
    </customValue>
    <customValue>
        <fullName>Bosnia and Herzegovina(+387)</fullName>
    </customValue>
    <customValue>
        <fullName>Botswana(+267)</fullName>
    </customValue>
    <customValue>
        <fullName>Bouvet Island(+47)</fullName>
    </customValue>
    <customValue>
        <fullName>Brazil(+55)</fullName>
    </customValue>
    <customValue>
        <fullName>British Indian Ocean Territory(+246)</fullName>
    </customValue>
    <customValue>
        <fullName>UAE(+971)</fullName>
        <default>true</default>
        <label>UAE(+971)</label>
    </customValue>
    <masterLabel>ISD Country Code</masterLabel>
</GlobalValueSet>

unpackaged/main/default/classes/CaseTrigger_SMS_HandlerTest.cls
@isTest
public class CaseTrigger_SMS_HandlerTest {
     @isTest public static void DataSetUp(){
        Account accoun = new Account();
        accoun.Name = 'test corp';
        accoun.phone= '01123123';
        accoun.billingcity='London';
        accoun.billingpostalcode='SW1635HJ';
        accoun.billingcountry='United Kingdom';
        accoun.billingstreet='address 1';
        insert accoun;
    
    
        Contact c = new Contact();
        c.AccountId = accoun.ID;
        c.ETSALES_Mob_Country_Code__c = 'UAE(+971)';
        c.MobilePhone = '88887778'; 
        c.FirstName = 'test';
        c.LastName = 'test';
        c.email = 'test@test.com';
        c.RecordTypeid=Schema.SObjectType.Contact.getRecordTypeInfosByDeveloperName().get('ETSALES_B2B_Contact').getRecordTypeId(); 
        c.birthdate = Date.newInstance(1992, 04, 12);
        insert c;
    
        Profile prof = [select id from profile where name ='System Administrator'];
        User user = new User();
        user.firstName = 'test1';
        user.lastName = 'test2';
      //  user.contactid=c.id;
        user.profileId = prof.id;
        user.username = 'test1@uichangeset.com';
        user.email = 'test@test.com';
        user.Alias='test';
        user.TimeZoneSidKey='Asia/Dubai';
        user.LocaleSidKey='en_IE_EURO';
        user.EmailEncodingKey='ISO-8859-1';
        user.LanguageLocaleKey='en_US';
        insert user;
        User user2 = new User();
        user2.firstName = 'test1';
        user2.lastName = 'test02';
      //  user.contactid=c.id;
        user2.profileId = prof.id;
        user2.username = 'test2@uichangeset.com';
        user2.email = 'test@test.com';
        user2.Alias='test';
        user2.TimeZoneSidKey='Asia/Dubai';
        user2.LocaleSidKey='en_IE_EURO';
        user2.EmailEncodingKey='ISO-8859-1';
        user2.LanguageLocaleKey='en_US';
        insert user2;
        List<case> cslist= new List<Case>();
         List<case> csListFinal= new List<Case>();
        for(Integer i=0;i<5;i++){
        Case cs= new Case();
        cs.Accountid=accoun.id;
        cs.ContactId = c.Id;
        cs.Recordtypeid=Schema.SObjectType.Case.getRecordTypeInfosByDeveloperName().get('School_Transport').getRecordTypeId();
        
        if(i<3){
        cs.status='New';
        cs.Case_Types__c='Request for Awareness Session';
        cs.Requestor__c='Parent/Guardian';
         cs.Assigned_To__c=user2.id;
        }
        else if(i>3 && i<5){
        cs.status='Submitted for ADEC';
        cs.Case_Types__c='Evaluation of Schools/Services';
        cs.Requestor__c='Parent/Guardian';
        
        }
        else{
        
        cs.status='On Hold';
        cs.Case_Types__c='Request for New Bus/Supervisors/Teachers Transfer';
        cs.Requestor__c='Parent/Guardian';
        
        }
        cs.Origin = 'Phone Call';
        cslist.add(cs);
        }
         Test.startTest();
        Test.setMock(WebServiceMock.class, new SendSMSCalloutMock());
        insert cslist;
        cslist[1].Priority = 'Normal - close withen 2 working days';
        update cslist[1];
        cslist[2].status = 'Solution Completed';
        cslist[2].Solution__c = 'Closed';
        cslist[2].CCM_Remarks__c = 'Closed';
        update cslist[2];
        ET_SendSMS_API_Paramter.Control obj = new  ET_SendSMS_API_Paramter.Control();
        Test.stopTest();
        
    }
    
     
}