unpackaged/main/default/objects/Case/fields/Case_Types__c.field-meta.xml
<CustomField>
    <fullName>Case_Types__c</fullName>
    <label>Case Types</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Cancel Service</fullName>
            </value>
            <value>
                <fullName>Complaint and Follow up</fullName>
            </value>
            <value>
                <fullName>Follow up</fullName>
            </value>
            <value>
                <fullName>Get Services</fullName>
            </value>
            <value>
                <fullName>Inquires and Notices</fullName>
            </value>
            <value>
                <fullName>Notice</fullName>
            </value>
            <value>
                <fullName>Thankyou and appreciation</fullName>
            </value>
            <value>
                <fullName>Update Information</fullName>
            </value>
            <value>
                <fullName>Human Resource</fullName>
            </value>
            <value>
                <fullName>Services</fullName>
            </value>
            <value>
                <fullName>Online and Financial Services</fullName>
            </value>
            <value>
                <fullName>Request</fullName>
            </value>
            <value>
                <fullName>Quality and Compliance</fullName>
            </value>
            <value>
                <fullName>Traffic Violation</fullName>
            </value>
            <value>
                <fullName>Internal Issues</fullName>
            </value>
            <value>
                <fullName>Theft and Missing</fullName>
            </value>
            <value>
                <fullName>Safety Issue</fullName>
            </value>
            <value>
                <fullName>Accident/Emergency</fullName>
            </value>
            <value>
                <fullName>Request for Awareness Session</fullName>
            </value>
            <value>
                <fullName>Request for New Bus/Supervisors/Teachers Transfer</fullName>
            </value>
            <value>
                <fullName>Requests for New Trips Activities and Events</fullName>
            </value>
            <value>
                <fullName>Printing New Card - Student</fullName>
            </value>
            <value>
                <fullName>Printing New Card - Drivers &amp; Transportation Supervisors</fullName>
            </value>
            <value>
                <fullName>Evaluation of Schools/Services</fullName>
            </value>
            <value>
                <fullName>Others</fullName>
            </value>
            <value>
                <fullName>Bus is not on time</fullName>
            </value>
            <value>
                <fullName>Change the Bus stop as my kid is too young to reach the stop</fullName>
            </value>
            <value>
                <fullName>Bus didn&#39;t pick my kid</fullName>
            </value>
            <value>
                <fullName>My kid was bullied</fullName>
            </value>
            <value>
                <fullName>Driver behavior is bad</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Case/fields/CCM_Remarks__c.field-meta.xml
<CustomField>
    <fullName>CCM_Remarks__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>CCM Remarks</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

unpackaged/main/default/objects/Case/fields/Requestor__c.field-meta.xml
<CustomField>
    <fullName>Requestor__c</fullName>
    <label>Requestor</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Parent/Guardian</fullName>
            </value>
            <value>
                <fullName>Public Schools</fullName>
            </value>
            <value>
                <fullName>Staffs</fullName>
            </value>
            <value>
                <fullName>Ministries</fullName>
            </value>
            <value>
                <fullName>Private Schools</fullName>
            </value>
            <value>
                <fullName>ET staff</fullName>
            </value>
            <value>
                <fullName>Municipality/RTA/DoT</fullName>
            </value>
            <value>
                <fullName>Police</fullName>
            </value>
            <value>
                <fullName>General Public</fullName>
            </value>
            <value>
                <fullName>Private School Parents</fullName>
            </value>
            <value>
                <fullName>Customer</fullName>
            </value>
            <value>
                <fullName>Insurance Company</fullName>
            </value>
            <value>
                <fullName>AD Police</fullName>
            </value>
            <value>
                <fullName>ADFCA</fullName>
            </value>
            <value>
                <fullName>FUJAIRAH Police</fullName>
            </value>
            <value>
                <fullName>Hotels/Event team</fullName>
            </value>
            <value>
                <fullName>Dubai Police</fullName>
            </value>
            <value>
                <fullName>Sharjah Police</fullName>
            </value>
            <value>
                <fullName>Ajman Police</fullName>
            </value>
            <value>
                <fullName>Others</fullName>
            </value>
            <value>
                <fullName>Private</fullName>
            </value>
            <value>
                <fullName>Government</fullName>
            </value>
            <value>
                <fullName>Technical Service</fullName>
            </value>
            <value>
                <fullName>MUSADA</fullName>
            </value>
            <value>
                <fullName>Dry Wash Unite</fullName>
            </value>
            <value>
                <fullName>Watania</fullName>
            </value>
            <value>
                <fullName>CNG</fullName>
            </value>
            <value>
                <fullName>IT</fullName>
            </value>
            <value>
                <fullName>Finance</fullName>
            </value>
            <value>
                <fullName>HR</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Case/recordTypes/ETST_Ministry_of_Education.recordType-meta.xml
<RecordType>
    <fullName>ETST_Ministry_of_Education</fullName>
    <active>true</active>
    <businessProcess>Ministry of Education</businessProcess>
    <label>Ministry of Education</label>
</RecordType>

unpackaged/main/default/objects/Case/recordTypes/Services.recordType-meta.xml
<RecordType>
    <fullName>Services</fullName>
    <active>true</active>
    <businessProcess>Services</businessProcess>
    <description>الخدمات</description>
    <label>Services</label>
</RecordType>

unpackaged/main/default/objects/Contact/recordTypes/ETSALES_B2B_Contact.recordType-meta.xml
<RecordType>
    <fullName>ETSALES_B2B_Contact</fullName>
    <active>true</active>
    <label>B2B Contact</label>
</RecordType>

unpackaged/main/default/classes/SS_TicketingSystem_Controller_Test.cls
@isTest
public class SS_TicketingSystem_Controller_Test{
    
    @isTest public static void  insertnewdata(){
        
        UserRole userrole = [Select Id, DeveloperName From UserRole Where DeveloperName = 'ET_HQ_Head_of_Service' Limit 1];
         UserRole userrole2 = [Select Id, DeveloperName From UserRole Where DeveloperName = 'ADECPartnerUser' Limit 1];
       
        Id partnerprof = [select id from profile where name='Partner Community Login User'].id;
        Id adminprof = [select id from profile where name='System Administrator'].id;
        
      
            User useradmin = new User();
            useradmin.firstName = 'test02';
            useradmin.lastName = 'test03';
            useradmin.UserRoleId =userrole.Id;
            useradmin.profileId = adminprof;
            useradmin.username = 'test02@uichangeset.com';
            useradmin.email = 'test@test.com';
            useradmin.Alias='test';
            useradmin.TimeZoneSidKey='Asia/Dubai';
            useradmin.LocaleSidKey='en_IE_EURO';
            useradmin.EmailEncodingKey='ISO-8859-1';
            useradmin.LanguageLocaleKey='en_US';
            insert useradmin;
        system.debug('############'+useradmin);
        System.runAs(useradmin){
             system.debug('######'+userInfo.getuserId());
           
            Account accoun = new Account();
            accoun.RecordTypeid=Schema.SObjectType.Account.getRecordTypeInfosByDeveloperName().get('Account').getRecordTypeId();
            accoun.Name = 'test corp';
            accoun.phone= '01123123';
            accoun.billingcity='London';
            accoun.billingpostalcode='SW1635HJ';
            accoun.billingcountry='United Kingdom';
            accoun.billingstreet='address 1';
            accoun.OwnerId=useradmin.id;
            insert accoun;
            system.debug('######'+accoun.ownerID);
            
            Contact c = new Contact();
            c.AccountId = accoun.Id;
            c.FirstName = 'test';
            c.LastName = 'test';
            c.email = 'test@test.com';
            c.RecordTypeid=Schema.SObjectType.Contact.getRecordTypeInfosByDeveloperName().get('ETSALES_B2B_Contact').getRecordTypeId(); 
            c.birthdate = Date.newInstance(1992, 04, 12);
            insert c;
            system.debug('######'+c);
            
            /* User user2 = new User();
            user2.firstName = 'test1';
            user2.lastName = 'test2';
            user2.contactId=contactId;
            user2.PortalRole ='Manager';
            user2.profileId = partnerprof;
            user2.username = 'test1@uichangeset.com';
            user2.email = 'test@test.com';
            user2.Alias='test';
            user2.TimeZoneSidKey='Asia/Dubai';
            user2.LocaleSidKey='en_IE_EURO';
            user2.EmailEncodingKey='ISO-8859-1';
            user2.LanguageLocaleKey='en_US';
            insert user2;
            */
            
            List<case> cslist= new List<Case>();
            for(Integer i=0;i<10;i++){
                Case cs= new Case();
                cs.Accountid=accoun.id;
                cs.Recordtypeid=Schema.SObjectType.Case.getRecordTypeInfosByDeveloperName().get('ETST_Ministry_of_Education').getRecordTypeId();
                cs.contactid=c.id;
                if(i<5){
                    cs.status='New';
                    cs.Case_Types__c='Request for Awareness Session';
                    cs.Requestor__c='Parent/Guardian';
                    cs.CCM_Remarks__c='Test';
                    cs.Solution__c='Test';
                }
                else if(i>4 && i<8){
                    cs.status='Submitted for ADEC';
                    cs.Case_Types__c='Evaluation of Schools/Services';
                    cs.Requestor__c='Parent/Guardian';
                    
                }
                else{
                    
                    cs.status='On Hold';
                    cs.Case_Types__c='Request for New Bus/Supervisors/Teachers Transfer';
                    cs.Requestor__c='Parent/Guardian';
                    
                }
                cslist.add(cs);
            }
            insert cslist;
            
            CaseComment cment= new CaseComment();
            cment.CommentBody='Test class case created';
            cment.parentId=cslist[0].id;
            insert cment;
            
          
            String response ;
            String responseticket ;
            String responsecommenthistory;
            String responseComment;
           
            response=SS_TicketingSystem_Controller.getDashboardData();
            responseticket=SS_TicketingSystem_Controller.getTicketDetails('New');
            responseticket=SS_TicketingSystem_Controller.getTicketDetails('On Hold');
            responseticket=SS_TicketingSystem_Controller.getTicketDetails('Submitted for ADEC');
            //    responseComment=SS_TicketingSystem_Controller.manageTicket(cslist[0].id,'Test case','Closed');
            responseComment=SS_TicketingSystem_Controller.manageTicket(cslist[0].id,'Test case','Reopen');
            responsecommenthistory=SS_TicketingSystem_Controller.getCommentsHistory(cslist[0].id);
            system.assertequals(responseComment,'Success');
            }
          
        }
    
    
}