unpackaged/main/default/objects/Case/fields/Status_Category__c.field-meta.xml
<CustomField>
    <fullName>Status_Category__c</fullName>
    <label>Next Activity</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Pending with Department Of School Activities</fullName>
            </value>
            <value>
                <fullName>Pending with School Transportation Manager</fullName>
            </value>
            <value>
                <fullName>Pending with Department Of School Services</fullName>
            </value>
            <value>
                <fullName>Pending with Personnel Management</fullName>
            </value>
            <value>
                <fullName>Pending with Special Education</fullName>
            </value>
            <value>
                <fullName>Pending with Statistics Coordinator</fullName>
            </value>
            <value>
                <fullName>Pending with Branch Manager</fullName>
            </value>
            <value>
                <fullName>Pending with Routes Efficient and Design Director</fullName>
            </value>
            <value>
                <fullName>Pending with First Transport Specialist</fullName>
            </value>
            <value>
                <fullName>Pending with Head of Safety Unit</fullName>
            </value>
            <value>
                <fullName>Pending with Students Safety Specialist</fullName>
            </value>
            <value>
                <fullName>Pending with Safety and Health Specialist</fullName>
            </value>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>Rejected</fullName>
            </value>
            <value>
                <fullName>Pending with Main School</fullName>
            </value>
            <value>
                <fullName>Pending Hemam for Inclusive Education services</fullName>
            </value>
            <value>
                <fullName>Pending with Inclusive Education Department in ESE</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/ESE_Department__c/ESE_Department__c.object-meta.xml
<CustomObject>
    <label>ESE Department</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>ESE Department Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>ESE Departments</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

unpackaged/main/default/objects/ESE_Department__c/fields/Category__c.field-meta.xml
<CustomField>
    <fullName>Category__c</fullName>
    <label>Category Value</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Pending with Department Of School Activities</fullName>
            </value>
            <value>
                <fullName>Pending with Department Of School Services</fullName>
            </value>
            <value>
                <fullName>Pending Hemam for Inclusive Education services</fullName>
            </value>
            <value>
                <fullName>Pending with Inclusive Education Department in ESE</fullName>
            </value>
            <value>
                <fullName>Pending with MOE-Extra-Curricular Activities</fullName>
            </value>
            <value>
                <fullName>pending with Operation Supervisors</fullName>
            </value>
            <value>
                <fullName>Pending with MOE - Personnel Affairs</fullName>
            </value>
            <value>
                <fullName>Pending with Personnel Management</fullName>
            </value>
            <value>
                <fullName>Pending with Branch Manager</fullName>
            </value>
            <value>
                <fullName>Pending with Routes Efficient and Design Director</fullName>
            </value>
            <value>
                <fullName>Pending with Head of Safety Unit</fullName>
            </value>
            <value>
                <fullName>Pending with Operation Manager</fullName>
            </value>
            <value>
                <fullName>Pending with Resource Planner</fullName>
            </value>
            <value>
                <fullName>Pending with ET Department</fullName>
            </value>
            <value>
                <fullName>Rejected</fullName>
            </value>
            <value>
                <fullName>Approved</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/ESE_Department__c/fields/School_Name__c.field-meta.xml
<CustomField>
    <fullName>School_Name__c</fullName>
    <label>School Name</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>ESE Departments</relationshipLabel>
    <relationshipName>ESE_Departments</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

unpackaged/main/default/objects/ESE_User__c/ESE_User__c.object-meta.xml
<CustomObject>
    <label>ESE User</label>
    <nameField>
        <displayFormat>U-{00000}</displayFormat>
        <label>ESE User Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>ESE Users</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

unpackaged/main/default/objects/ESE_User__c/fields/School_Department__c.field-meta.xml
<CustomField>
    <fullName>School_Department__c</fullName>
    <label>School Department</label>
    <referenceTo>ESE_Department__c</referenceTo>
    <relationshipLabel>ESE Users</relationshipLabel>
    <relationshipName>ESE_Users</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

unpackaged/main/default/objects/ESE_User__c/fields/User__c.field-meta.xml
<CustomField>
    <fullName>User__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>User</label>
    <referenceTo>User</referenceTo>
    <relationshipLabel>ESE Users</relationshipLabel>
    <relationshipName>ESE_Users</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/classes/caseSharingHandler.cls
/**************************************************************************************************
* Name               : caseSharingHandler                                                           
* Description        : ESE PORTAL School Maping to User                                                          
* Created Date       : 15/03/2023                                                                
* Created By         : Akash Yellure   
*Trigger Name        : CaseTrigger
* ----------------------------------------------------------------------------------------------- 
* VERSION     Created by                    DATE                                                                    
* 1.0        Akash Yellure                 15/03/2023                                                                
**************************************************************************************************/ 
public class caseSharingHandler {
    
    public static void eseCaseSharing (Map<id,case> trgNewMap){ 
        
        //This list is for adding newly created cases
        List<CaseShare> caShareList = new List<CaseShare>();
        Set<String> eseCatogory = new Set<String>();
        Set<String> schSet  = new  Set<String>();
        
        Map<String,List<ESE_User__c>> schoolVsDptMap  = new Map<String,List<ESE_User__c>>();
        
        //  List<case> caselist = [Select id, RecordType.Name,AccountId,Status_Category__c  from case where id =:trgNewMap.keySet()];
        
        for(case cs :trgNewMap.values() ) {
            // eseDept.add(cs.RecordType.Name);
            schSet.add(cs.AccountId);
            eseCatogory.add(cs.Status_Category__c);
        }
        List<ESE_User__c> eUser =[select id,Name , User__r.Name,School_Department__r.School_Name__c ,School_Department__r.Category__c from ESE_User__c];
        
        System.debug('Catogory'+eseCatogory);
        
        
        for(ESE_User__c us : [select id,Name , User__c,School_Department__r.School_Name__c ,School_Department__r.Category__c from ESE_User__c Where School_Department__r.Category__c =:eseCatogory  And School_Department__r.School_Name__c =: schSet ] ){
            System.debug('data'+us);
            if(!schoolVsDptMap.containskey(us.School_Department__r.Category__c)){
                system.debug('ION3');
                schoolVsDptMap.put(us.School_Department__r.Category__c,new List<ESE_User__c>());
            } 
            schoolVsDptMap.get(us.School_Department__r.Category__c).add(us);
        }
        
        for(case cs :trgNewMap.values() ){
            
            if(schoolVsDptMap.containskey(cs.Status_Category__c)){
                SYSTEM.debug('ION4');
                
                for(ESE_User__c edu :schoolVsDptMap.get(cs.Status_Category__c)){  
                    if(cs.AccountId==edu.School_Department__r.School_Name__c && cs.Status_Category__c==edu.School_Department__r.Category__c){
                        System.debug('ION5');
                        CaseShare caShare = new CaseShare();
                        caShare.caseID=cs.Id;
                        caShare.CaseAccessLevel='edit';
                        caShare.RowCause='Manual';
                        caShare.UserOrGroupId=edu.User__c;
                        caShareList.add(caShare);
                        
                    }
                    
                }
                
            }
            
            
        }
        if( caShareList != null && caShareList.size() != 0 ) {
            try {
                Database.SaveResult[] caShareLi = Database.insert(caShareList,false);
                System.debug('result'+caShareLi);
                
            }catch( Exception e ) {
                System.debug('Error::::::'+e.getMessage());
            }
        }
        
        System.debug('test'+caShareList);
      
        
    }
    
    //This Method To Update and assigned to other User
    public static void eseCaseSharingAfterUpdateCase(Map<Id,case> trgOldMap,Map<ID,case>trgNewMap){
      List<CaseShare> caShareList = new List<CaseShare>();
        Set<String> eseCatogory = new Set<String>();
        Set<String> schSet  = new  Set<String>();
        Map<String,List<ESE_User__c>> schoolVsDptMap  = new Map<String,List<ESE_User__c>>();
        
        for(case cs :trgNewMap.values() ) {
            // eseDept.add(cs.RecordType.Name);
            if(cs.Status_Category__c!=trgOldMap.get(cs.ID).Status_Category__c){
                schSet.add(cs.AccountId);
                eseCatogory.add(cs.Status_Category__c);
            }
            
        }
        
        
        for(ESE_User__c us : [select id,Name , User__c,School_Department__r.School_Name__c ,School_Department__r.Category__c from ESE_User__c Where School_Department__r.Category__c =:eseCatogory  And School_Department__r.School_Name__c =: schSet ] ){
            if(!schoolVsDptMap.containskey(us.School_Department__r.Category__c)){
                system.debug('ION3');
                schoolVsDptMap.put(us.School_Department__r.Category__c,new List<ESE_User__c>());
            } 
            schoolVsDptMap.get(us.School_Department__r.Category__c).add(us);
        }
        for(case cs :trgNewMap.values() ){
            
            if(schoolVsDptMap.containskey(cs.Status_Category__c) && cs.Status_Category__c!=trgOldMap.get(cs.ID).Status_Category__c ){
                SYSTEM.debug('ION4');
                
                for(ESE_User__c edu :schoolVsDptMap.get(cs.Status_Category__c)){  
                    if(cs.AccountId==edu.School_Department__r.School_Name__c && cs.Status_Category__c==edu.School_Department__r.Category__c){
                        System.debug('ION5');
                        CaseShare caShare = new CaseShare();
                        caShare.caseID=cs.Id;
                        caShare.CaseAccessLevel='edit';
                        caShare.RowCause='Manual';
                        caShare.UserOrGroupId=edu.User__c;
                        caShareList.add(caShare);
                        
                    }
                    
                }
                
            }
            
            
        }
        if( caShareList != null && caShareList.size() != 0 ) {
            try {
                Database.SaveResult[] caShareLi = Database.insert(caShareList,false);
            }catch( Exception e ) {
                System.debug('Error::::::'+e.getMessage());
            }
        }
    
    
    }
}