unpackaged/main/default/objects/Case/fields/Survey_Responded__c.field-meta.xml
<CustomField>
    <fullName>Survey_Responded__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Survey Responded?</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/objects/Survey__c/Survey__c.object-meta.xml
<CustomObject>
    <label>Survey</label>
    <nameField>
        <displayFormat>S-{0000}</displayFormat>
        <label>Survey Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Surveys</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/classes/surveyPageControllerTest.cls
/***
Class       : surveyPageController
Author      : Sreelakshmi SK
Description : Test class for surveyPageController
Created on  : 11 May 23
***/

@isTest
public class surveyPageControllerTest {
    public static testmethod void createSurveyRecTest(){
        Survey__c surveyRecord=new Survey__c();
        
        insert surveyRecord;
        Case caseRecord= new Case();
        caseRecord.Id=caseRecord.Id;
        caseRecord.Survey_Responded__c=true;
        
        try
        {
            surveyPageController.createSurveyRec(surveyRecord,caseRecord);
        }
        catch(exception e)
        {
        }         
    }
    
    public static testmethod void getSurveyRecordTest(){
        Case newCase= new Case();
        insert newCase;
        
        surveyPageController.utilityMethod();
        surveyPageController.getSurveyRecord(newCase.id);
    }
}