unpackaged/main/default/objects/ETT_Price_Master__c/ETT_Price_Master__c.object-meta.xml
<CustomObject>
    <label>Price Master</label>
    <nameField>
        <displayFormat>PMN-{0000}</displayFormat>
        <label>Price Master Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Price Masters</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/ETT_Price_Master__c/fields/ETT_Party_Name__c.field-meta.xml
<CustomField>
    <fullName>ETT_Party_Name__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Party Name</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Price Masters</relationshipLabel>
    <relationshipName>Price_Masters</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/ETT_Pricing_Information__c/ETT_Pricing_Information__c.object-meta.xml
<CustomObject>
    <label>Pricing Information</label>
    <nameField>
        <displayFormat>PI-{0000}</displayFormat>
        <label>Pricing Info Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Pricing Information</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

unpackaged/main/default/objects/ETT_Pricing_Information__c/fields/ETT_Approval_Status__c.field-meta.xml
<CustomField>
    <fullName>ETT_Approval_Status__c</fullName>
    <label>Approval Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>New</fullName>
            </value>
            <value>
                <fullName>In Progress</fullName>
            </value>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>Rejected</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/ETT_Pricing_Information__c/fields/ETT_Price__c.field-meta.xml
<CustomField>
    <fullName>ETT_Price__c</fullName>
    <label>Price</label>
    <referenceTo>ETT_Price_Master__c</referenceTo>
    <relationshipLabel>Pricing Information</relationshipLabel>
    <relationshipName>Pricing_Information</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

unpackaged/main/default/objects/ETT_Pricing_Information__c/fields/ETT_Tyre_Size__c.field-meta.xml
<CustomField>
    <fullName>ETT_Tyre_Size__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Tyre Size</label>
    <referenceTo>ETT_Tyre_Size_Master__c</referenceTo>
    <relationshipLabel>Pricing Information</relationshipLabel>
    <relationshipName>Pricing_Information</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/ETT_Staging_Quotation_Request__c/ETT_Staging_Quotation_Request__c.object-meta.xml
<CustomObject>
    <label>Staging Quotation Request</label>
    <nameField>
        <displayFormat>SQRN-{0000}</displayFormat>
        <label>Staging Quotation Request Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Staging Quotation Request</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/ETT_Staging_Quotation_Request__c/fields/Approver_Status__c.field-meta.xml
<CustomField>
    <fullName>Approver_Status__c</fullName>
    <label>Approver Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>Rejected</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/ETT_Staging_Quotation_Request__c/fields/ETT_Tyre_Size_Master__c.field-meta.xml
<CustomField>
    <fullName>ETT_Tyre_Size_Master__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Tyre Size</label>
    <referenceTo>ETT_Tyre_Size_Master__c</referenceTo>
    <relationshipLabel>Staging Quotation Request</relationshipLabel>
    <relationshipName>Staging_Quotation_Request</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/ETT_Tyre_Master__c/ETT_Tyre_Master__c.object-meta.xml
<CustomObject>
    <label>Tyre Master</label>
    <nameField>
        <displayFormat>TMN-{0000}</displayFormat>
        <label>Tyre Master Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Tyre Masters</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/ETT_Tyre_Master__c/fields/ETT_Price__c.field-meta.xml
<CustomField>
    <fullName>ETT_Price__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Price</label>
    <length>250</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/ETT_Tyre_Master__c/fields/ETT_Tyre_Size__c.field-meta.xml
<CustomField>
    <fullName>ETT_Tyre_Size__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Tyre Size</label>
    <referenceTo>ETT_Tyre_Size_Master__c</referenceTo>
    <relationshipLabel>Tyre Masters</relationshipLabel>
    <relationshipName>Tyre_Masters</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/ETT_Tyre_Master__c/fields/RecordTypes__c.field-meta.xml
<CustomField>
    <fullName>RecordTypes__c</fullName>
    <label>RecordTypes</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Approve</fullName>
            </value>
            <value>
                <fullName>Reject</fullName>
            </value>
            <value>
                <fullName>Draft</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/ETT_Tyre_Size_Master__c/ETT_Tyre_Size_Master__c.object-meta.xml
<CustomObject>
    <label>Tyre Size Master</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Tyre Sizes</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Tyre Size Master</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/ETT_Tyre_Size_Master__c/fields/ETT_Tyre_Size__c.field-meta.xml
<CustomField>
    <fullName>ETT_Tyre_Size__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Tyre size</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/classes/ETT_PriceConfirmationCtrlTest.cls
@isTest
public class ETT_PriceConfirmationCtrlTest {
    
    private static testmethod void priceTest(){
        
         List<Account> accountsList = ETT_TestFactory.createAccounts('TJ89ntName34434', 'Organization');
        insert accountsList;
        Opportunity opp = ETT_TestFactory.createOpportunity('Tyre Supplier','TestOppName3434', 'Qualification', system.today().adddays(20), accountsList[0].Id);
        insert opp;
        
        ETT_Price_Master__c pm2 = new ETT_Price_Master__c();
        pm2.ETT_Party_Name__c = accountsList[0].Id;
        insert pm2;
        
          ETT_Tyre_Size_Master__c tsm = new ETT_Tyre_Size_Master__c();
        tsm.Name ='Size1JKIk';
        insert tsm;
        
        ETT_Pricing_Information__c epi = new ETT_Pricing_Information__c();
        epi.ETT_Price__c=pm2.Id;
        epi.ETT_Tyre_Size__c=tsm.Id;
        epi.ETT_Approval_Status__c ='Approved';
        insert epi;
        
        ETT_Tyre_Master__c em = new ETT_Tyre_Master__c();
        em.RecordTypes__c ='Approve';
        em.ETT_Status__c = true;
        insert em;
        
        ETT_Staging_Quotation_Request__c stq = new ETT_Staging_Quotation_Request__c();
        stq.Approver_Status__c= 'Approved';
        insert stq;
        
        Approval.ProcessSubmitRequest req1 = new Approval.ProcessSubmitRequest();
                req1.setComments('Receptionist request');
                req1.setObjectId(opp.Id);
                              
        Approval.ProcessResult result = Approval.process(req1);
        
        ETT_PriceConfirmationCtrl.getAllStagQuotReq(opp.Id);
        ETT_PriceConfirmationCtrl.getLoggedUserInfo();
        ETT_PriceConfirmationCtrl.getselectOptions(opp, 'StageName');
        ETT_PriceConfirmationCtrl.getTyreMasterDetails(opp.Id);
        string priceChangeval ='[{"tyreSize":"12R22.5","NewRepairPrice":12,"OldRepairPrice":12,"NewSelProPrice":"13","OldSelProPrice":12,"NewSelHotPrice":12,"OldSelHotPrice":12,"NewRetProPrice":0,"OldRetProPrice":0,"NewRetHotPrice":0,"OldRetHotPrice":0,"reason":""}]';
        ETT_PriceConfirmationCtrl.updateStgQuotCreatePriceMas(opp.Id,new list<ETT_Staging_Quotation_Request__c>{stq},priceChangeval);
        ETT_PriceConfirmationCtrl.handleNewTyreDetails(opp.Id, new list<ETT_Tyre_Master__c>{em});
    }

}