unpackaged/main/default/objects/ET_Terms_and_Conditions__c/ET_Terms_and_Conditions__c.object-meta.xml
<CustomObject>
    <label>Terms and Conditions</label>
    <nameField>
        <displayFormat>TC-{0000}</displayFormat>
        <label>Terms and Conditions Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Terms and Conditions</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

unpackaged/main/default/objects/ET_Terms_and_Conditions__c/fields/ET_Condition__c.field-meta.xml
<CustomField>
    <fullName>ET_Condition__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Condition</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

unpackaged/main/default/objects/ET_Terms_and_Conditions__c/fields/ET_Service_Name__c.field-meta.xml
<CustomField>
    <fullName>ET_Service_Name__c</fullName>
    <label>Service Name</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Vehicle Inspection</fullName>
            </value>
            <value>
                <fullName>School</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/ET_Terms_and_Conditions__c/fields/Footer_Text__c.field-meta.xml
<CustomField>
    <fullName>Footer_Text__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Footer Text</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

unpackaged/main/default/objects/ET_Terms_and_Conditions__c/fields/Header_Line__c.field-meta.xml
<CustomField>
    <fullName>Header_Line__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Header Line</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

unpackaged/main/default/objects/ET_Terms_and_Conditions__c/fields/Place_of_Visisbility__c.field-meta.xml
<CustomField>
    <fullName>Place_of_Visisbility__c</fullName>
    <label>Place of Visisbility</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Vehicle Registration</fullName>
            </value>
            <value>
                <fullName>Vehicle Unregistered</fullName>
            </value>
            <value>
                <fullName>Payment Page</fullName>
            </value>
            <value>
                <fullName>School Payment</fullName>
            </value>
            <value>
                <fullName>Add Child</fullName>
            </value>
            <value>
                <fullName>Book Service</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/classes/ETI_TermAndConditions_Ctrl.cls
public class ETI_TermAndConditions_Ctrl {
    public String variant;
    public List<ET_Terms_and_Conditions__c> termsAndConditionsList {get; set;}
    public ETI_TermAndConditions_Ctrl(){
        variant = ApexPages.currentPage().getParameters().get('variant');
        variant =  setVariant(variant);
        getETI_Terms_and_Conditions();
    }
    public string setVariant(String type){
        switch on type {
            when 'Registered' { 
                return 'Vehicle Registration';
            }   
            when 'Un-Registered' {
                return 'Vehicle Unregistered';
            }
            when 'Payment' {
                return 'Payment Page';
            }
            when else { 
                return '';
            }
        }
    }
    public void getETI_Terms_and_Conditions(){
        System.debug(variant);
        termsAndConditionsList = [SELECT Id,ET_Condition__c,Place_of_Visisbility__c,Header_Line__c,Footer_Text__c  
                                  FROM ET_Terms_and_Conditions__c WHERE Place_of_Visisbility__c = :variant order by Order__c];
    }
    @AuraEnabled
    public static List<ET_Terms_and_Conditions__c> getTermsandConditions(String Visisbility){
        System.debug(Visisbility);
        list<ET_Terms_and_Conditions__c> termsAndConditionsList=new list<ET_Terms_and_Conditions__c>();
        if(Visisbility!=null && Visisbility!=''){
            termsAndConditionsList = [SELECT Id,ET_Condition__c,ET_Service_Name__c,Place_of_Visisbility__c,Header_Line__c,Footer_Text__c  
                                             FROM ET_Terms_and_Conditions__c WHERE Place_of_Visisbility__c = :Visisbility AND ET_Service_Name__c='Vehicle Inspection' order by Order__c];
        }
        return termsAndConditionsList;  
    }
    
}