unpackaged/main/default/objects/ET_Terms_and_Conditions__c/ET_Terms_and_Conditions__c.object-meta.xml
<CustomObject>
    <label>Terms and Conditions</label>
    <nameField>
        <displayFormat>TC-{0000}</displayFormat>
        <label>Terms and Conditions Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Terms and Conditions</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

unpackaged/main/default/objects/ET_Terms_and_Conditions__c/fields/ET_Condition__c.field-meta.xml
<CustomField>
    <fullName>ET_Condition__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Condition</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

unpackaged/main/default/objects/ET_Terms_and_Conditions__c/fields/ET_Service_Name__c.field-meta.xml
<CustomField>
    <fullName>ET_Service_Name__c</fullName>
    <label>Service Name</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Vehicle Inspection</fullName>
            </value>
            <value>
                <fullName>School</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/ET_Terms_and_Conditions__c/fields/Place_of_Visisbility__c.field-meta.xml
<CustomField>
    <fullName>Place_of_Visisbility__c</fullName>
    <label>Place of Visisbility</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Vehicle Registration</fullName>
            </value>
            <value>
                <fullName>Vehicle Unregistered</fullName>
            </value>
            <value>
                <fullName>Payment Page</fullName>
            </value>
            <value>
                <fullName>School Payment</fullName>
            </value>
            <value>
                <fullName>Add Child</fullName>
            </value>
            <value>
                <fullName>Book Service</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/classes/ETI_TermAndConditions_CtrlTest.cls
@isTest
public class ETI_TermAndConditions_CtrlTest {
    private static testmethod void testmethodInspection(){
        ETI_TermAndConditions_Ctrl et = new ETI_TermAndConditions_Ctrl();
        et.getETI_Terms_and_Conditions();
        ET_Terms_and_Conditions__c term=new ET_Terms_and_Conditions__c();
        term.ET_Condition__c='test';
        term.ET_Service_Name__c='Vehicle Inspection';
        term.Place_of_Visisbility__c ='Vehicle Registration';
        insert term;
        ETI_TermAndConditions_Ctrl.getTermsandConditions('Vehicle Registration');
    }
}