unpackaged/main/default/objects/ETST_Scheduled_Trips__c/ETST_Scheduled_Trips__c.object-meta.xml
<CustomObject>
    <label>Scheduled Trips</label>
    <nameField>
        <displayFormat>ST-{000000}</displayFormat>
        <label>Scheduled Trips Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Scheduled Trips</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

unpackaged/main/default/objects/ETST_Scheduled_Trips__c/fields/ETST_Bus_Number__c.field-meta.xml
<CustomField>
    <fullName>ETST_Bus_Number__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Bus Number</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/ETST_Scheduled_Trips__c/fields/ETST_Date__c.field-meta.xml
<CustomField>
    <fullName>ETST_Date__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Date</label>
    <type>Date</type>
</CustomField>

unpackaged/main/default/objects/ETST_Scheduled_Trips__c/fields/ETST_Direction__c.field-meta.xml
<CustomField>
    <fullName>ETST_Direction__c</fullName>
    <label>Direction</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>School To Home</fullName>
            </value>
            <value>
                <fullName>Home To School</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/ETST_Scheduled_Trips__c/fields/ETST_Driver__c.field-meta.xml
<CustomField>
    <fullName>ETST_Driver__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Driver</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/ETST_Scheduled_Trips__c/fields/ETST_Schedule_drop_off_time__c.field-meta.xml
<CustomField>
    <fullName>ETST_Schedule_drop_off_time__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Schedule drop off time</label>
    <type>DateTime</type>
</CustomField>

unpackaged/main/default/objects/ETST_Scheduled_Trips__c/fields/ETST_Schedule_pickup_time__c.field-meta.xml
<CustomField>
    <fullName>ETST_Schedule_pickup_time__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Schedule pickup time</label>
    <type>DateTime</type>
</CustomField>

unpackaged/main/default/objects/ETST_Scheduled_Trips__c/fields/ETST_Student__c.field-meta.xml
<CustomField>
    <fullName>ETST_Student__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Student</label>
    <referenceTo>ETST_Student__c</referenceTo>
    <relationshipLabel>Scheduled Trips</relationshipLabel>
    <relationshipName>Scheduled_Trips</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/ETST_Student__c/ETST_Student__c.object-meta.xml
<CustomObject>
    <label>Student</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Last Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Students</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

unpackaged/main/default/classes/ETSTStudentDetails.cls
public class ETSTStudentDetails {
	@AuraEnabled
    public static List<ETST_Scheduled_Trips__c> getStudentTripDetails(String studentId) {
        return [SELECT Id, Name, ETST_Student__c, ETST_Date__c, ETST_Direction__c, ETST_Schedule_pickup_time__c, 
                ETST_Schedule_drop_off_time__c, ETST_Bus_Number__c, ETST_Driver__c FROM ETST_Scheduled_Trips__c
                WHERE ETST_Student__c =:studentId];
    }
}