unpackaged/main/default/objects/ETT_Pattern_Master__c/ETT_Pattern_Master__c.object-meta.xml
<CustomObject>
    <label>Pattern Master</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Pattern Code</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Pattern Masters</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/ETT_Tyre_Inventory__c/ETT_Tyre_Inventory__c.object-meta.xml
<CustomObject>
    <label>Tyre Inventory</label>
    <nameField>
        <displayFormat>TI-{0000}</displayFormat>
        <label>Tyre Inventory Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Tyre Inventory</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/ETT_Tyre_Inventory__c/fields/ETT_Job_Card__c.field-meta.xml
<CustomField>
    <fullName>ETT_Job_Card__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Job Card</label>
    <referenceTo>ETT_Job_Card__c</referenceTo>
    <relationshipLabel>Tyre Inventory</relationshipLabel>
    <relationshipName>Tyre_Inventory</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/ETT_Tyre_Inventory__c/fields/ETT_Pattern__c.field-meta.xml
<CustomField>
    <fullName>ETT_Pattern__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Pattern</label>
    <referenceTo>ETT_Pattern_Master__c</referenceTo>
    <relationshipLabel>Tyre Inventory</relationshipLabel>
    <relationshipName>Tyre_Inventory</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/ETT_Tyre_Inventory__c/fields/ETT_Tyre_Size_Master__c.field-meta.xml
<CustomField>
    <fullName>ETT_Tyre_Size_Master__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Tyre Size</label>
    <referenceTo>ETT_Tyre_Size_Master__c</referenceTo>
    <relationshipLabel>Tyre Inventory</relationshipLabel>
    <relationshipName>Tyre_Inventory</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/ETT_Tyre_Size_Master__c/ETT_Tyre_Size_Master__c.object-meta.xml
<CustomObject>
    <label>Tyre Size Master</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Tyre Sizes</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Tyre Size Master</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/ETT_Work_Schedule__c/ETT_Work_Schedule__c.object-meta.xml
<CustomObject>
    <label>Work Schedule</label>
    <nameField>
        <displayFormat>SCH-{000}</displayFormat>
        <label>Work Schedule Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Work Schedule</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

unpackaged/main/default/objects/ETT_Work_Schedule__c/fields/ETT_End_time__c.field-meta.xml
<CustomField>
    <fullName>ETT_End_time__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>End time</label>
    <required>true</required>
    <type>DateTime</type>
</CustomField>

unpackaged/main/default/objects/ETT_Work_Schedule__c/fields/ETT_Technician__c.field-meta.xml
<CustomField>
    <fullName>ETT_Technician__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Technician</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Work_Schedule</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/ETT_Work_Schedule__c/fields/ETT_Work_Station__c.field-meta.xml
<CustomField>
    <fullName>ETT_Work_Station__c</fullName>
    <label>Work Station</label>
    <referenceTo>ETT_Work_Station__c</referenceTo>
    <relationshipLabel>Work Schedule</relationshipLabel>
    <relationshipName>Work_Schedule</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
    <writeRequiresMasterRead>true</writeRequiresMasterRead>
</CustomField>

unpackaged/main/default/objects/ETT_Work_Station__c/ETT_Work_Station__c.object-meta.xml
<CustomObject>
    <label>Work Station</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Work Station Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Work Stations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/ETT_Work_Station__c/fields/ETT_Station_Code__c.field-meta.xml
<CustomField>
    <fullName>ETT_Station_Code__c</fullName>
    <caseSensitive>true</caseSensitive>
    <encryptionScheme>None</encryptionScheme>
    <label>Station Code</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

unpackaged/main/default/objects/ETT_Work_Station__c/fields/ETT_Station_Type__c.field-meta.xml
<CustomField>
    <fullName>ETT_Station_Type__c</fullName>
    <label>Station Type</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>ETT_Job_Station_Type</valueSetName>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/ETT_Work_Station_Checklist__c/ETT_Work_Station_Checklist__c.object-meta.xml
<CustomObject>
    <label>Work Station Checklist</label>
    <nameField>
        <displayFormat>CL-{0000}</displayFormat>
        <label>Checklist Ref. No</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Work Station Checklists</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

unpackaged/main/default/globalValueSets/ETT_Job_Station_Type.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Initial Inspection</fullName>
    </customValue>
    <customValue>
        <fullName>Buffing</fullName>
    </customValue>
    <customValue>
        <fullName>Skiving</fullName>
    </customValue>
    <customValue>
        <fullName>Repair</fullName>
    </customValue>
    <customValue>
        <fullName>Cementing</fullName>
    </customValue>
    <customValue>
        <fullName>Filling</fullName>
    </customValue>
    <customValue>
        <fullName>Thread Preparation</fullName>
    </customValue>
    <customValue>
        <fullName>Building</fullName>
    </customValue>
    <customValue>
        <fullName>Rimming &amp; Enveloping</fullName>
    </customValue>
    <customValue>
        <fullName>Curing</fullName>
    </customValue>
    <customValue>
        <fullName>Final Inspection</fullName>
    </customValue>
    <customValue>
        <fullName>Painting</fullName>
    </customValue>
    <customValue>
        <fullName>Removal of RIM Tube Flap</fullName>
    </customValue>
    <masterLabel>Job Station Type</masterLabel>
</GlobalValueSet>

unpackaged/main/default/classes/ETT_TyreWorkStationHomeCtrl.cls
/**
 * Author:Janardhan
 * CreatedDate:14/12/2021
 * TestClass: ETT_TyreWorkStationHomeCtrlTest
 * */
public class ETT_TyreWorkStationHomeCtrl {
    
    @auraEnabled
    public static user getUserDetails(){
        
        return [select id,FirstName,LastName from user where Id=:userInfo.getUserId()];
    }
    
    @auraEnabled
    public static ETT_Work_Schedule__c getWorkscheduleInfo(){
        
        list<ETT_Work_Schedule__c> workSchList = [Select Id,Name,ETT_Technician__c,ETT_Technician__r.Name,ETT_Work_Station__c,ETT_Work_Station__r.ETT_Station_Code__c,ETT_Work_Station__r.Name,ETT_Work_Station__r.ETT_Station_Type__c from ETT_Work_Schedule__c where
                                                  ETT_Technician__c=:Userinfo.getUserId() and ETT_End_time__c>=:System.NOW() AND ETT_Start_time__c<=:System.NOW()];
        
        if(workSchList.size()>0){
            return workSchList[0];
        }else{
            return null;
        }
    }
      @auraEnabled
    public static list<ETT_Job_Card__c> getJobCardsInfo(){
        
        list<ETT_Work_Schedule__c> workSchList = [Select Id,Name,ETT_Technician__c,ETT_Technician__r.Name,ETT_Work_Station__c,ETT_Work_Station__r.ETT_Station_Code__c,ETT_Work_Station__r.Name,ETT_Work_Station__r.ETT_Station_Type__c from ETT_Work_Schedule__c where
                                                  ETT_Technician__c=:Userinfo.getUserId() and ETT_End_time__c>=:System.NOW() AND ETT_Start_time__c<=:System.NOW()];
        
        if(workSchList.size()>0){
            
            if(workSchList[0].ETT_Work_Station__r.ETT_Station_Type__c=='Filling'){
                //Show records only if Filling Summer halt time greaterthan 25 min/Winter 30 mins
                return [select id,Name,ETT_Previous_Job_Stage__c,Tyre_Inventory__c,createdDate,ETT_Priority__c,Tyre_Inventory__r.Serial_Number__c,Tyre_Inventory__r.ETT_Tyre_Size_Master__r.Name,Tyre_Inventory__r.ETT_Pattern__r.Name from ETT_Job_Card__c where ETT_Stages__c=:workSchList[0].ETT_Work_Station__r.ETT_Station_Type__c AND Tyre_Inventory__c != null AND ETT_Overall_Status__c!='Rejected' AND (Filling_Summer_Halt_Time__c > 25 OR Filling_Winter_Halt_Time__c > 30) Order by ETT_Priority__c DESC];
                
            }else if(workSchList[0].ETT_Work_Station__r.ETT_Station_Type__c=='Building'){
                //Show records only if building halt time greaterthan 15 min
                return [select id,Name,ETT_Previous_Job_Stage__c,Tyre_Inventory__c,createdDate,ETT_Priority__c,Tyre_Inventory__r.Serial_Number__c,Tyre_Inventory__r.ETT_Tyre_Size_Master__r.Name,Tyre_Inventory__r.ETT_Pattern__r.Name from ETT_Job_Card__c where ETT_Stages__c=:workSchList[0].ETT_Work_Station__r.ETT_Station_Type__c AND Tyre_Inventory__c != null AND ETT_Overall_Status__c!='Rejected' AND Building_Halt_Time__c>15 Order by ETT_Priority__c DESC];
                
            }else if(workSchList[0].ETT_Work_Station__r.ETT_Station_Type__c=='Thread Preparation'){
                
                 return [select id,Name,ETT_Previous_Job_Stage__c,ETT_Main_Job_Card__r.Name,Tyre_Inventory__c,createdDate,ETT_Priority__c,Tyre_Inventory__r.Serial_Number__c,Tyre_Inventory__r.ETT_Tyre_Size_Master__r.Name,Tyre_Inventory__r.ETT_Pattern__r.Name from ETT_Job_Card__c where ETT_Stages__c=:workSchList[0].ETT_Work_Station__r.ETT_Station_Type__c AND ETT_Main_Job_Card__c!=null AND Tyre_Inventory__c != null AND ETT_Overall_Status__c!='Rejected' AND ETT_Thread_Preparation_Status__c!='Accepted'  Order by ETT_Priority__c DESC];
                
            }else {
                
                return [select id,Name,ETT_Previous_Job_Stage__c,Tyre_Inventory__c,createdDate,ETT_Priority__c,Tyre_Inventory__r.Serial_Number__c,Tyre_Inventory__r.ETT_Tyre_Size_Master__r.Name,Tyre_Inventory__r.ETT_Pattern__r.Name from ETT_Job_Card__c where ETT_Stages__c=:workSchList[0].ETT_Work_Station__r.ETT_Station_Type__c AND Tyre_Inventory__c != null AND (ETT_Overall_Status__c!='Rejected' AND ETT_Overall_Status__c!='Accepted') Order by ETT_Priority__c DESC];
                
            }
        }else{
            return null;
        }

       
    }
   @auraEnabled
    public static void createWorkStationCheckList(ETT_Work_Station_Checklist__c wscl){
        
        try{
            insert wscl;
        }catch(Exception e) {
            system.debug('----'+e.getMessage()); 
            throw new AuraHandledException(e.getMessage());    
        }
    }

}