unpackaged/main/default/objects/ERP_Vehicle_Activity_Setting__mdt/ERP_Vehicle_Activity_Setting__mdt.object-meta.xml
<CustomObject>
    <label>ERP Vehicle Activity Setting</label>
    <pluralLabel>ERP Vehicle Activity Settings</pluralLabel>
</CustomObject>

unpackaged/main/default/objects/ERP_Vehicle_Activity_Setting__mdt/fields/Activity_Name__c.field-meta.xml
<CustomField>
    <fullName>Activity_Name__c</fullName>
    <label>Activity Name</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/ET_ERP_Vehicle__c/ET_ERP_Vehicle__c.object-meta.xml
<CustomObject>
    <label>ET Vehicle</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Internal No</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>ET Vehicles</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/ET_ERP_Vehicle__c/fields/ET_Activity_Center__c.field-meta.xml
<CustomField>
    <fullName>ET_Activity_Center__c</fullName>
    <label>Activity Center</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Abu Dhabi Transport and leasing</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/ET_ERP_Vehicle__c/fields/ET_Activity_Center_Code__c.field-meta.xml
<CustomField>
    <fullName>ET_Activity_Center_Code__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Activity Center Code</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/ET_ERP_Vehicle__c/fields/ET_Actual_Mileage__c.field-meta.xml
<CustomField>
    <fullName>ET_Actual_Mileage__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Actual Mileage</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/ET_ERP_Vehicle__c/fields/ET_Asset_Op_Status__c.field-meta.xml
<CustomField>
    <fullName>ET_Asset_Op_Status__c</fullName>
    <label>Asset Op Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Ready To Assign</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/ET_ERP_Vehicle__c/fields/ET_Asset_Type__c.field-meta.xml
<CustomField>
    <fullName>ET_Asset_Type__c</fullName>
    <label>Asset Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Light</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/ET_ERP_Vehicle__c/fields/ET_Axle_Info__c.field-meta.xml
<CustomField>
    <fullName>ET_Axle_Info__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Axle Info</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/ET_ERP_Vehicle__c/fields/ET_Battery_Type__c.field-meta.xml
<CustomField>
    <fullName>ET_Battery_Type__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Battery Type</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/ET_ERP_Vehicle__c/fields/ET_Classification__c.field-meta.xml
<CustomField>
    <fullName>ET_Classification__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Classification</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/ET_ERP_Vehicle__c/fields/ET_Description__c.field-meta.xml
<CustomField>
    <fullName>ET_Description__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Description</label>
    <type>TextArea</type>
</CustomField>

unpackaged/main/default/objects/ET_ERP_Vehicle__c/fields/ET_Family__c.field-meta.xml
<CustomField>
    <fullName>ET_Family__c</fullName>
    <label>Family</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>HI ACE</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/ET_ERP_Vehicle__c/fields/ET_Fleet_Type__c.field-meta.xml
<CustomField>
    <fullName>ET_Fleet_Type__c</fullName>
    <label>Fleet Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Vehicle</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/ET_ERP_Vehicle__c/fields/ET_Fuel_Tank_Capacity__c.field-meta.xml
<CustomField>
    <fullName>ET_Fuel_Tank_Capacity__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Fuel Tank Capacity</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/ET_ERP_Vehicle__c/fields/ET_Fuel_Type__c.field-meta.xml
<CustomField>
    <fullName>ET_Fuel_Type__c</fullName>
    <label>Fuel Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>PETROL</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/ET_ERP_Vehicle__c/fields/ET_Location__c.field-meta.xml
<CustomField>
    <fullName>ET_Location__c</fullName>
    <label>Location</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Mosafah 1</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/ET_ERP_Vehicle__c/fields/ET_Make__c.field-meta.xml
<CustomField>
    <fullName>ET_Make__c</fullName>
    <label>Make</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>TOYOTA</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/ET_ERP_Vehicle__c/fields/ET_Manufacture_Mileage__c.field-meta.xml
<CustomField>
    <fullName>ET_Manufacture_Mileage__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Manufacture Mileage</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/ET_ERP_Vehicle__c/fields/ET_Manufacture_Name__c.field-meta.xml
<CustomField>
    <fullName>ET_Manufacture_Name__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Manufacture Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/ET_ERP_Vehicle__c/fields/ET_Model__c.field-meta.xml
<CustomField>
    <fullName>ET_Model__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Model</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/ET_ERP_Vehicle__c/fields/ET_No_Of_Seats__c.field-meta.xml
<CustomField>
    <fullName>ET_No_Of_Seats__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>No Of Seats</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/ET_ERP_Vehicle__c/fields/ET_Number_Of_Battery__c.field-meta.xml
<CustomField>
    <fullName>ET_Number_Of_Battery__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Number Of Battery</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/ET_ERP_Vehicle__c/fields/ET_Number_Of_Tyres__c.field-meta.xml
<CustomField>
    <fullName>ET_Number_Of_Tyres__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Number Of Tyres</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/ET_ERP_Vehicle__c/fields/ET_Parking__c.field-meta.xml
<CustomField>
    <fullName>ET_Parking__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Parking</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/ET_ERP_Vehicle__c/fields/ET_Plate_Colour__c.field-meta.xml
<CustomField>
    <fullName>ET_Plate_Colour__c</fullName>
    <label>Plate Colour</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>SIXTH CATEGORY</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/ET_ERP_Vehicle__c/fields/ET_Plate_Issue__c.field-meta.xml
<CustomField>
    <fullName>ET_Plate_Issue__c</fullName>
    <label>Plate Issue</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>ABU DHABI</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/ET_ERP_Vehicle__c/fields/ET_Plate_Number__c.field-meta.xml
<CustomField>
    <fullName>ET_Plate_Number__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Plate Number</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/ET_ERP_Vehicle__c/fields/ET_Plate_Type__c.field-meta.xml
<CustomField>
    <fullName>ET_Plate_Type__c</fullName>
    <label>Plate Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>PRIVATE</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/ET_ERP_Vehicle__c/fields/ET_Registration_Date__c.field-meta.xml
<CustomField>
    <fullName>ET_Registration_Date__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Registration Date</label>
    <type>DateTime</type>
</CustomField>

unpackaged/main/default/objects/ET_ERP_Vehicle__c/fields/ET_Registrration_Renewal_Date__c.field-meta.xml
<CustomField>
    <fullName>ET_Registrration_Renewal_Date__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Registrration Renewal Date</label>
    <type>DateTime</type>
</CustomField>

unpackaged/main/default/objects/ET_ERP_Vehicle__c/fields/ET_Sector__c.field-meta.xml
<CustomField>
    <fullName>ET_Sector__c</fullName>
    <label>Sector</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>None</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/ET_ERP_Vehicle__c/fields/ET_Seg_Activity_Center__c.field-meta.xml
<CustomField>
    <fullName>ET_Seg_Activity_Center__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Seg Activity Center</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/ET_ERP_Vehicle__c/fields/ET_segActivityCenterCode__c.field-meta.xml
<CustomField>
    <fullName>ET_segActivityCenterCode__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Seg Activity Center Code</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/ET_ERP_Vehicle__c/fields/ET_Type__c.field-meta.xml
<CustomField>
    <fullName>ET_Type__c</fullName>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>AC</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/ET_ERP_Vehicle__c/fields/ET_Tyre_Pressure_Info__c.field-meta.xml
<CustomField>
    <fullName>ET_Tyre_Pressure_Info__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Tyre Pressure Info</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/ET_ERP_Vehicle__c/fields/ET_Tyre_Type__c.field-meta.xml
<CustomField>
    <fullName>ET_Tyre_Type__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Tyre Type</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/ET_ERP_Vehicle__c/fields/ET_Usage_Type__c.field-meta.xml
<CustomField>
    <fullName>ET_Usage_Type__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Usage Type</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/ET_ERP_Vehicle__c/fields/ET_Vehicle_Make_Country__c.field-meta.xml
<CustomField>
    <fullName>ET_Vehicle_Make_Country__c</fullName>
    <label>Vehicle Make Country</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Canada</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/ET_ERP_Vehicle__c/fields/ET_Vehicle_Mode__c.field-meta.xml
<CustomField>
    <fullName>ET_Vehicle_Mode__c</fullName>
    <label>Vehicle Mode</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>CORP</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/ET_ERP_Vehicle__c/fields/ET_Vehicle_Status__c.field-meta.xml
<CustomField>
    <fullName>ET_Vehicle_Status__c</fullName>
    <label>Vehicle Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Ready To Assign</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/ET_ERP_Vehicle__c/fields/ET_Vehicle_SubType__c.field-meta.xml
<CustomField>
    <fullName>ET_Vehicle_SubType__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Vehicle SubType</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/ET_ERP_Vehicle__c/fields/ET_Workhop_Location__c.field-meta.xml
<CustomField>
    <fullName>ET_Workhop_Location__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Workhop Location</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/ET_ERP_Vehicle__c/fields/External_ID__c.field-meta.xml
<CustomField>
    <fullName>External_ID__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <externalId>true</externalId>
    <label>External ID</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/classes/ET_ERPVehiclesServiceSchedule.cls
/*
* File Name:ET_ERPVehiclesServiceSchedule
* Author : Sagar Kambli
* CreatedDate :  20 May 20200
* Modification Purpose
* * 1. Sagar: Schedulable class to load all ERP Vehicles Values.
* * 2.
*/ 
global class ET_ERPVehiclesServiceSchedule implements Schedulable,Database.AllowsCallouts {
     
    
    public static ET_ERPVehicle.Output  vehicleResult {get;set;}
    
    global void execute(SchedulableContext SC) {
        Set<String> activityValues = new Set<String>();
        for(ERP_Vehicle_Activity_Setting__mdt activityMetadata: [SELECT Id, Activity_Name__c FROM ERP_Vehicle_Activity_Setting__mdt]){
            activityValues.add(activityMetadata.Activity_Name__c);
        }
        if(activityValues.size()>0){
            for(string activityType:activityValues){
                for(ERP_Vehicle_Mode_Setting__mdt vehicleMode : [SELECT Id, Label from ERP_Vehicle_Mode_Setting__mdt]){
                    if(activityType!=null && vehicleMode.Label!=null){
                        ETI_Batch_Vehicle_Service job = new ETI_Batch_Vehicle_Service(activityType,vehicleMode.Label);
                        Database.executeBatch(job,200);    
                    }
                } 
            }
        }   
    }
    
   
   //perform mapping for Vehicle Master
   public static List<ET_ERP_Vehicle__c> doVehicleMapping(List<ET_ERPVehicle.XxetVehicleMasterDetMv> vehicleData){
      List<ET_ERP_Vehicle__c> vehiclesToInsert = new List<ET_ERP_Vehicle__c>();
       if(vehicleData!=null && vehicleData.size() > 0){
           for(ET_ERPVehicle.XxetVehicleMasterDetMv row:vehicleData){
               ET_ERP_Vehicle__c vehicle = new ET_ERP_Vehicle__c();
               vehicle.Name = row.internalNo;
               vehicle.External_ID__c = row.internalNo;
               vehicle.ET_Vehicle_Mode__c=row.vehMode;
               //vehicle.ET_Fleet_Type__c=row.fleetType;
               vehicle.ET_Description__c=row.description;
               //vehicle.ET_Activity_Center__c=row.activityCenter;
               //vehicle.ET_Activity_Center_Code__c=row.activityCenterCode;
               vehicle.ET_Seg_Activity_Center__c=row.segActivityCenter;
               //vehicle.ET_segActivityCenterCode__c=row.segActivityCenterCode;
               //vehicle.ET_Sector__c=row.sector;
               vehicle.ET_Location__c=row.location;
               //vehicle.ET_Parking__c=row.parking;
               //vehicle.ET_Workhop_Location__c=row.workhopLocation;
               vehicle.ET_Vehicle_Status__c=row.vehicleStatus;
               //vehicle.ET_Asset_Op_Status__c=row.assetOpStatus;
               //vehicle.ET_Usage_Type__c=row.usageType;
               //vehicle.ET_Classification__c=row.classification;
               vehicle.ET_Plate_Number__c=row.plateNumber;
               vehicle.ET_Plate_Colour__c=row.plateColour;
               vehicle.ET_Plate_Type__c=row.plateType;
               vehicle.ET_Plate_Issue__c=row.plateIssue;
               //system.debug('registrationDate: '+row.registrationDate);
               if(row.registrationDate!=null){
                   String registrationDate = ''+row.registrationDate;  
                   vehicle.ET_Registration_Date__c = Datetime.valueOFGMT(registrationDate);
               }
               
               if(row.regRenewalDate!=null){
                   String regRenewalDate = ''+row.regRenewalDate;  
                   vehicle.ET_Registrration_Renewal_Date__c=Datetime.valueOFGMT(regRenewalDate);
               }

               //vehicle.ET_Asset_Type__c=row.assetType;
               //vehicle.ET_Manufacture_Name__c=row.manufaturerName;
               vehicle.ET_Vehicle_Type__c=row.mainType;
               vehicle.ET_Vehicle_SubType__c=row.subType;
               vehicle.ET_Make__c=row.make;
               //vehicle.ET_Vehicle_Make_Country__c=row.countryOfMake;
               vehicle.ET_Model__c=row.model;
               /*vehicle.ET_Family__c=row.family;
               vehicle.ET_Tyre_Type__c=row.tyreType;
               vehicle.ET_Number_Of_Tyres__c=row.numberOfTyres;
               vehicle.ET_Tyre_Pressure_Info__c=row.tyrePressureInfo;
               vehicle.ET_Axle_Info__c=row.axleInfo;
               vehicle.ET_Battery_Type__c=row.batteryType;
               vehicle.ET_Number_Of_Battery__c=row.numberOfBattery;
               vehicle.ET_Fuel_Type__c=row.fuelType;
               vehicle.ET_Fuel_Tank_Capacity__c=row.fuelTankCapacity;
               vehicle.ET_Manufacture_Mileage__c=row.manufacMileage;
               vehicle.ET_Actual_Mileage__c=row.actualMileage;
               vehicle.ET_No_Of_Seats__c=row.numberOfSeats;
               vehicle.ET_Type__c=row.acNonAc;*/
               vehicle.ET_Chassis_No__c=row.chassisNumber;
               vehicle.ET_Engine_Number__c=row.engineNumber;
               //vehicle.ET_Engine_Capacity__c=row.engineCapacity;
               //vehicle.ET_No_Of_Cylinder__c=row.numberOfCylinder;
               //vehicle.ET_Vehicle_Color__c=row.vehicleColor;
               //vehicle.et=row.meterMeasurements;
               //vehicle.et=row.odometer;
               /*vehicle.ET_Family_Details__c=row.familyDetails;
               vehicle.ET_Vehicle_Life__c=row.vehicleLife;
               vehicle.ET_Vehicle_Category__c=row.vehicleCategory;
               vehicle.ET_Transmission_Type__c=row.transmissionType;
               vehicle.ET_Horse_Power__c=row.horsePower;
               vehicle.ET_Green_Vehicle__c=row.greenVehicle;
               vehicle.ET_Serial_Number__c=row.serialNumber;
               vehicle.ET_Crub_Weight__c=Decimal.valueOf(row.crubWeight);
               vehicle.ET_Gross_Weight__c=Decimal.valueOf(row.grossWeight);
               vehicle.ET_Customer_Name__c=row.customerName;*/
               vehicle.ET_Contract_No__c=row.contractNo;               
               vehiclesToInsert.add(vehicle);
           }
       }
      return vehiclesToInsert;
   }
    
}