unpackaged/main/default/objects/ETT_Apex_Error_log__c/ETT_Apex_Error_log__c.object-meta.xml
<CustomObject>
    <label>Apex Error log</label>
    <nameField>
        <displayFormat>ApexErrorLog-{00000}</displayFormat>
        <label>Apex Error log Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Apex Error Logs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/ETT_Collection_Card__c/ETT_Collection_Card__c.object-meta.xml
<CustomObject>
    <description>This object is to track the vehicle information and as well as driver information with the help of google map.</description>
    <label>Collection Card</label>
    <nameField>
        <displayFormat>CC-{0000}</displayFormat>
        <label>Collection Card Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Collection Cards</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/ETT_Collection_Card__c/fields/ETT_Estimation_Completed_By_HOO__c.field-meta.xml
<CustomField>
    <fullName>ETT_Estimation_Completed_By_HOO__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Estimation Completed By HOO</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/objects/ETT_Collection_Card__c/fields/ETT_Inspection_Done__c.field-meta.xml
<CustomField>
    <fullName>ETT_Inspection_Done__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Inspection Done</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/objects/ETT_Collection_Card__c/fields/ETT_Priority__c.field-meta.xml
<CustomField>
    <fullName>ETT_Priority__c</fullName>
    <label>Priority</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Low</fullName>
                <default>true</default>
                <label>Low</label>
            </value>
            <value>
                <fullName>Medium</fullName>
            </value>
            <value>
                <fullName>High</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/ETT_Collection_Card__c/fields/ETT_Status__c.field-meta.xml
<CustomField>
    <fullName>ETT_Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Collection Stage</fullName>
            </value>
            <value>
                <fullName>Inspection Stage</fullName>
            </value>
            <value>
                <fullName>Job Card Stage</fullName>
            </value>
            <value>
                <fullName>Delivery Stage</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/ETT_Collection_Card__c/fields/ETT_Work_Order__c.field-meta.xml
<CustomField>
    <fullName>ETT_Work_Order__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Tyre Collection Request</label>
    <referenceTo>WorkOrder</referenceTo>
    <relationshipLabel>Collection Cards</relationshipLabel>
    <relationshipName>Collection_Cards</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/ETT_Inspection_Card__c/ETT_Inspection_Card__c.object-meta.xml
<CustomObject>
    <description>This is for inspection for the customer who has been requested orders.</description>
    <label>Tyre Inspection Card</label>
    <nameField>
        <displayFormat>IC-{0000}</displayFormat>
        <label>Inspection Card Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Tyre Inspection Cards</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/ETT_Inspection_Card__c/fields/ETT_Collection_Card__c.field-meta.xml
<CustomField>
    <fullName>ETT_Collection_Card__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Collection Card</label>
    <referenceTo>ETT_Collection_Card__c</referenceTo>
    <relationshipName>Inspection_Cards</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/ETT_Inspection_Card__c/fields/ETT_Collection_Line_Item__c.field-meta.xml
<CustomField>
    <fullName>ETT_Collection_Line_Item__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Collection Line Item</label>
    <referenceTo>WorkOrderLineItem</referenceTo>
    <relationshipName>Inspection_Cards</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/ETT_Inspection_Card__c/fields/ETT_Priority__c.field-meta.xml
<CustomField>
    <fullName>ETT_Priority__c</fullName>
    <label>Priority</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>1st Priority</fullName>
            </value>
            <value>
                <fullName>2nd Priority</fullName>
            </value>
            <value>
                <fullName>3rd Priority</fullName>
            </value>
            <value>
                <fullName>Normal</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/ETT_Inspection_Card__c/fields/ETT_Status__c.field-meta.xml
<CustomField>
    <fullName>ETT_Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Not Inspected</fullName>
                <default>true</default>
                <label>Not Inspected</label>
            </value>
            <value>
                <fullName>Accept</fullName>
            </value>
            <value>
                <fullName>Send Back</fullName>
            </value>
            <value>
                <fullName>Scrap</fullName>
            </value>
            <value>
                <fullName>Accepted/No Warranty</fullName>
            </value>
            <value>
                <fullName>Pending</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/ETT_Tyre_Inventory__c/ETT_Tyre_Inventory__c.object-meta.xml
<CustomObject>
    <label>Tyre Inventory</label>
    <nameField>
        <displayFormat>TI-{0000}</displayFormat>
        <label>Tyre Inventory Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Tyre Inventory</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/ETT_Tyre_Inventory__c/fields/ETT_Collection_Card__c.field-meta.xml
<CustomField>
    <fullName>ETT_Collection_Card__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Collection Card</label>
    <referenceTo>ETT_Collection_Card__c</referenceTo>
    <relationshipLabel>Tyre Inventory</relationshipLabel>
    <relationshipName>Tyre_Inventory</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/ETT_Tyre_Inventory__c/fields/ETT_Inventory_Status__c.field-meta.xml
<CustomField>
    <fullName>ETT_Inventory_Status__c</fullName>
    <label>Inventory Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>WIP</fullName>
            </value>
            <value>
                <fullName>Finished</fullName>
            </value>
            <value>
                <fullName>Draft</fullName>
                <default>true</default>
                <label>Draft</label>
            </value>
            <value>
                <fullName>Approved by Receptionist</fullName>
            </value>
            <value>
                <fullName>Inspected - Approved</fullName>
            </value>
            <value>
                <fullName>Inspected - Rejected</fullName>
            </value>
            <value>
                <fullName>Job Card Created</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/ETT_Tyre_Inventory__c/fields/ETT_Job_Card__c.field-meta.xml
<CustomField>
    <fullName>ETT_Job_Card__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Job Card</label>
    <referenceTo>ETT_Job_Card__c</referenceTo>
    <relationshipLabel>Tyre Inventory</relationshipLabel>
    <relationshipName>Tyre_Inventory</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/ETT_Tyre_Inventory__c/fields/ETT_Status__c.field-meta.xml
<CustomField>
    <fullName>ETT_Status__c</fullName>
    <formula>TEXT( ETT_Tyre_Inspection_Card__r.ETT_Status__c )</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Status</label>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/ETT_Tyre_Inventory__c/fields/ETT_Status_Changed_On__c.field-meta.xml
<CustomField>
    <fullName>ETT_Status_Changed_On__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Status Changed On</label>
    <type>DateTime</type>
</CustomField>

unpackaged/main/default/objects/ETT_Tyre_Inventory__c/fields/ETT_Status_TI__c.field-meta.xml
<CustomField>
    <fullName>ETT_Status_TI__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Collected</fullName>
            </value>
            <value>
                <fullName>Receptionist Accepted</fullName>
            </value>
            <value>
                <fullName>Inspection Team Accepted</fullName>
            </value>
            <value>
                <fullName>Inspection Team Rejected</fullName>
            </value>
            <value>
                <fullName>Job Card Created</fullName>
            </value>
            <value>
                <fullName>Buffing</fullName>
            </value>
            <value>
                <fullName>Skiving</fullName>
            </value>
            <value>
                <fullName>Repair</fullName>
            </value>
            <value>
                <fullName>Cementing</fullName>
            </value>
            <value>
                <fullName>Filling</fullName>
            </value>
            <value>
                <fullName>Thread Preparation</fullName>
            </value>
            <value>
                <fullName>Building</fullName>
            </value>
            <value>
                <fullName>Rimming &amp; Enveloping</fullName>
            </value>
            <value>
                <fullName>Curing</fullName>
            </value>
            <value>
                <fullName>Final Inspection</fullName>
            </value>
            <value>
                <fullName>Painting</fullName>
            </value>
            <value>
                <fullName>Removal of RIM Tube Flap</fullName>
            </value>
            <value>
                <fullName>Quality Control</fullName>
            </value>
            <value>
                <fullName>Estimation Accepted</fullName>
            </value>
            <value>
                <fullName>Purchase Order Created</fullName>
            </value>
            <value>
                <fullName>Delivery Note Created</fullName>
            </value>
            <value>
                <fullName>Delivery Note Approved</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/ETT_Tyre_Inventory__c/fields/ETT_Tyre_Inspection_Card__c.field-meta.xml
<CustomField>
    <fullName>ETT_Tyre_Inspection_Card__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Tyre Inspection Card</label>
    <referenceTo>ETT_Inspection_Card__c</referenceTo>
    <relationshipLabel>Tyre Inventory</relationshipLabel>
    <relationshipName>Tyre_Inventory</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/ETT_Tyre_Rejection_Report__c/ETT_Tyre_Rejection_Report__c.object-meta.xml
<CustomObject>
    <label>Tyre Rejection Report</label>
    <nameField>
        <displayFormat>TRR-{0000}</displayFormat>
        <label>Tyre Rejection Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Tyre Rejection Reports</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/ETT_Tyre_Rejection_Report__c/fields/Collection_Card__c.field-meta.xml
<CustomField>
    <fullName>Collection_Card__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Collection Card</label>
    <referenceTo>ETT_Collection_Card__c</referenceTo>
    <relationshipLabel>Tyre Rejection Reports</relationshipLabel>
    <relationshipName>ETT_Tyre_Rejection_Reports</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/ETT_Tyre_Rejection_Report__c/fields/ETT_Collection_Card__c.field-meta.xml
<CustomField>
    <fullName>ETT_Collection_Card__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Collection Card</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/WorkOrderLineItem/fields/ETT_Collection_Card__c.field-meta.xml
<CustomField>
    <fullName>ETT_Collection_Card__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Collection Card</label>
    <referenceTo>ETT_Collection_Card__c</referenceTo>
    <relationshipLabel>Work Order Line Items</relationshipLabel>
    <relationshipName>Work_Order_Line_Items</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/WorkOrderLineItem/fields/ETT_Priority__c.field-meta.xml
<CustomField>
    <fullName>ETT_Priority__c</fullName>
    <label>Priority</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Low</fullName>
            </value>
            <value>
                <fullName>Medium</fullName>
            </value>
            <value>
                <fullName>High</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/classes/ETT_CollectionCardTriggerHandler.cls
/*
CreatedDate:24/08/2020
CreatedBy:G.Krishnareddy
Description :This is for Collection Card handling to Create a Tyre Inspection Card for after approving the FM details.
*/
public class ETT_CollectionCardTriggerHandler {
    
    public static boolean isInspectionRecursive = true;
    public static boolean isJobCardRecursive = true;
    public static boolean isCollectionInventoryRecursive = true;
    public static boolean isWIPInventoryRecursive = true;
    
    public static void colletionCardHandlerAfterUpdate(map<Id,ETT_Collection_Card__c> mapOfNewCollectionCards,map<Id,ETT_Collection_Card__c> mapOfOldCollectionCards){
        //This is for Collection Card with List Of Work Order Line Items
        map<Id,list<WorkOrderLineItem>> mapOfCollectionCardwithWorkOrderLineItems = new map<Id,list<WorkOrderLineItem>>();
        Set<Id> setOfCollectionCards = new set<Id>();
        set<Id> setOfInspectionCardDetails = new set<Id>();
        Set<Id> setOfJobCardOpenCollectionCards = new set<Id>();
        Map<Id,list<ETT_Inspection_Card__c>> mapOfCollectionCardVSInspectionCardsInfo = new map<Id,list<ETT_Inspection_Card__c>>();
        list<ETT_Inspection_Card__c> lstInspectionCards = new list<ETT_Inspection_Card__c>();
        map<Id,ETT_Inspection_Card__c> mapOfCollectionLineItemwithInspectionCards = new map<Id,ETT_Inspection_Card__c>();
        list<ETT_Apex_Error_log__c> lstApexErrorLog = new list<ETT_Apex_Error_log__c>();
        if(mapOfNewCollectionCards!=null && mapOfNewCollectionCards.size()>0){
            system.debug('****mapOfNewCollectionCards****'+mapOfNewCollectionCards);
            for(ETT_Inspection_Card__c obJInspectionCard :[Select Id,ETT_Collection_Card__r.ETT_Inspection_Done__c,ETT_Collection_Card__c,ETT_Collection_Card__r.ETT_Work_Order__r.status from ETT_Inspection_Card__c where ETT_Collection_Card__c in :mapOfNewCollectionCards.keyset() and ETT_Collection_Line_Item__c!=null and ETT_Collection_Card__r.ETT_Work_Order__r.status='New']){
                if(mapOfCollectionCardVSInspectionCardsInfo.containsKey(obJInspectionCard.ETT_Collection_Card__c)){
                    mapOfCollectionCardVSInspectionCardsInfo.get(obJInspectionCard.ETT_Collection_Card__c).add(obJInspectionCard);
                }else{
                    mapOfCollectionCardVSInspectionCardsInfo.put(obJInspectionCard.ETT_Collection_Card__c,new list<ETT_Inspection_Card__c>{obJInspectionCard});
                }
            }
        } 
        
     }
    
    public static void createJobCard(map<Id,ETT_Collection_Card__c> mapOfNewCollectionCards,map<Id,ETT_Collection_Card__c> mapOfOldCollectionCards){
        
        //  check old map values and new map values. if i try to reupdate then throw error
        
        List<ETT_Job_Card__c> listOfJobCards = new List<ETT_Job_Card__c>();
        if(mapOfNewCollectionCards!=null && mapOfNewCollectionCards.size()>0){
            
            List<ETT_Inspection_Card__c> lstInspectionCards = [SELECT Id,Recordtype.name, ETT_Collection_Card__c,ETT_Collection_Card__r.ETT_Priority__c,ETT_Status__c,(select Id from Job_Cards__r) 
                                                               FROM ETT_Inspection_Card__c 
                                                               where ETT_Status__c = 'Accept' and 
                                                               ETT_Collection_Card__r.ETT_Inspection_Done__c = true and
                                                               ETT_Collection_Card__c in :mapOfNewCollectionCards.keyset()];
            
            if(lstInspectionCards!=null && lstInspectionCards.size()>0){
                for(ETT_Inspection_Card__c objIC:lstInspectionCards){
                    if(objIC.Job_Cards__r.size()==0){
                        ETT_Job_Card__c objJobCard = new ETT_Job_Card__c();
                        objJobCard.ETT_Inspection_Card__c = objIC.Id;
                        //include conditional values to stage order based on tyre record type (repair or retreading), For repair few stages are not applicable
                        if(objIC.recordType.name=='Tyre - Refurbishing Services'){
                            objJobCard.ETT_Job_Stages_to_Perform_Ordered__c='Buffing;Skiving;Repair;Cementing;Filling;Thread Preparation;Building;Rimming & Enveloping;Curing;Final Inspection;Painting';
                        }
                        else{
                            objJobCard.ETT_Job_Stages_to_Perform_Ordered__c='Buffing;Skiving;Repair;Cementing;Filling;Thread Preparation;Building;Rimming & Enveloping;Curing;Final Inspection;Painting';//for other record types this will be updated later
                        }
                        objJobCard.ETT_Stages__c = 'Buffing'; //Kumaresan changed stage to buffing
                        objJobCard.ETT_No_of_Buffing_revisions__c=1; //Kumaresan added
                        objJobCard.ETT_Priority__c=objIC.ETT_Collection_Card__r.ETT_Priority__c;
                        listOfJobCards.add(objJobCard);
                    }
                }
                
                if(listOfJobCards!=null && listOfJobCards.size()>0){
                    try{
                        insert listOfJobCards;
                        
                        List<ETT_Tyre_Inventory__c> lstTyreInventory = new List<ETT_Tyre_Inventory__c>();
                        for(ETT_Job_Card__c objJC:listOfJobCards){
                            ETT_Tyre_Inventory__c objTyreInventory = new ETT_Tyre_Inventory__c();
                            objTyreInventory.RecordTypeId = Schema.SObjectType.ETT_Tyre_Inventory__c.getRecordTypeInfosByName().get('WIP Inventory').getRecordTypeId();
                            objTyreInventory.ETT_Job_Card__c = objJC.Id;
                            objTyreInventory.ETT_Inventory_Status__c = 'WIP';
                            
                            lstTyreInventory.add(objTyreInventory);
                        }
                        
                       // insert lstTyreInventory;
                        
                        
                    }catch(Exception ex){
                        System.debug('Exception : '+ex.getMessage());
                    }
                }
            }
        }
        
    }
    
    public static void sendRejectedTyreDetails(List<ETT_Collection_Card__c> newList) {
        
        Set<Id> rejectedTyreIds = new Set<id>();
        Set<Id> collectionCardIds = new Set<id>();
        Map<Id, Set<id>> mapId = new Map<Id, Set<id>>();
        Map<Id, List<ContentVersion>> mapContentVersion = new Map<Id, List<ContentVersion>>();
        
        System.debug('newList: '+newList);
        List<ETT_Tyre_Rejection_Report__c> lstTR = [Select id,name,Collection_Card__c from ETT_Tyre_Rejection_Report__c where Collection_Card__c in:newList];
        System.debug('lstTR: '+lstTR);
        
        for(ETT_Tyre_Rejection_Report__c tr : [Select id,name,Collection_Card__c from ETT_Tyre_Rejection_Report__c where Collection_Card__c in:newList]){
            rejectedTyreIds.add(tr.Id);
            if(!mapId.containsKey(tr.Collection_Card__c)) {
                mapId.put(tr.Collection_Card__c, new Set<Id>());
            }
            mapId.get(tr.Collection_Card__c).add(tr.Id);
        }
        if(!rejectedTyreIds.isEmpty()){
            Set<Id> cdLinkSet = new Set<Id>();
            for(ContentDocumentLink cdLink : [SELECT LinkedEntityId,ContentDocumentId FROM ContentDocumentLink where LinkedEntityId In:rejectedTyreIds]){
                cdLinkSet.add(cdLink.ContentDocumentId);                 
            }
            List<ContentVersion> fileVersion = [SELECT Id, Title, VersionData, ContentDocumentId, ContentBodyId,FileType, FileExtension FROM ContentVersion 
                                                WHERE contentdocumentid In : cdLinkSet];
            
            EmailTemplate et = [SELECT Id,Subject,htmlvalue, Body FROM EmailTemplate WHERE DeveloperName =:'ETT_Rejected_Tyre_by_CT'];
            List<Messaging.SingleEmailMessage> messages = new List<Messaging.SingleEmailMessage>();
            List<Messaging.EmailFileAttachment> attachments = new List<Messaging.EmailFileAttachment>();
                        String[] toAddresses = new String[]{'sree.chandu@smaartt.com'};
                List<User> userList = [SELECT Email FROM User WHERE Profile.Name = 'ETT_Head of Operations'];
            for(User u : userList) {
                toAddresses.add(u.email);
            }
            for(ETT_Collection_Card__c cc : newList){
                Messaging.SingleEmailMessage mail = new Messaging.SingleEmailMessage();
                    mail.setToAddresses(toAddresses);
                mail.setUseSignature(false);
                mail.setSaveAsActivity(false);
                mail.setSenderDisplayName('ET');
                mail.setTargetObjectId(userList[0].Id);
                mail.setTemplateId(et.Id);
                mail.setHTMLBody(et.body);
                mail.setWhatId(cc.Id);
                for(ContentVersion cv : fileVersion){
                    Messaging.EmailFileAttachment efa = new Messaging.EmailFileAttachment();
                    efa.setFileName(cv.Title);
                    efa.setContentType('image/png');
                    efa.setBody(cv.VersionData);
                    attachments.add(efa);
                }
                mail.setFileAttachments(attachments);
                messages.add(mail);
            }
            
            if(!messages.isEmpty()){
                Messaging.SendEmailResult[] results = Messaging.sendEmail(messages);
            }
        }
        
    }

    public static void updateTyreInventoryStatus(List<ETT_Collection_Card__c> newList,Map<Id,ETT_Collection_Card__c> oldMap) {
        List<ETT_Tyre_Inventory__c> tyreInvList = new List<ETT_Tyre_Inventory__c>();
        Map<Id, String> mapStatus = new Map<Id,String>();
        Set<Id> collectionCardIds = new Set<Id>();
        for(ETT_Collection_Card__c cc: newList){
            if(cc.ETT_Estimation_Completed_By_HOO__c==true && cc.ETT_Estimation_Completed_By_HOO__c != oldMap.get(cc.Id).ETT_Estimation_Completed_By_HOO__c)
                collectionCardIds.add(cc.Id);
        }
        if(!collectionCardIds.isEmpty()){
            for(ETT_Tyre_Inventory__c ti : [SELECT Id, ETT_Status_TI__c,ETT_Tyre_Inspection_Card__c FROM ETT_Tyre_Inventory__c WHERE ETT_Collection_Card__c In: collectionCardIds ]){
                ti.ETT_Status_TI__c = 'Estimation Accepted';
                ti.ETT_Status_Changed_On__c= system.now();
                tyreInvList.add(ti);
            }
        }
        if(!tyreInvList.isEmpty()){
            update tyreInvList;
        }
    }  

    public static void callThisMethod(){
        Integer i=0;
        i++;
        i++;
        i++;
        i++;
        
        i++;
        i++;
        
        i++;
        i++;
        
        i++;
        i++;
        
        i++;
        i++;
        
        i++;
        i++;
        
        i++;
        i++;
        
        i++;
        i++;
        
        i++;
        i++;
        
        i++;
        i++;
        
        i++;
        i++;
        
        i++;
        i++;
        
        i++;
        i++;
        
        i++;
        i++;
        
        i++;
        i++;
        
        i++;
        i++;
        
        i++;
        i++;
        
        i++;
        i++;
        
        i++;
        i++;
        
        i++;
        i++;
        
        i++;
        i++;
        
        i++;
        i++;
        
        i++;
        i++;
        
        i++;
        i++;
        
        i++;
        i++;
        
        i++;
        i++;
        
        i++;
        i++;
        
        i++;
        i++;
        
        i++;
        i++;
        
        i++;
        i++;
        
        i++;
        i++;
        
        i++;
        i++;
        
        i++;
        i++;
        
        i++;
        i++;
        
        i++;
        i++;
        
        i++;
        i++;
        
        i++;
        i++;
        
        i++;
        i++;
        
        i++;
        i++;
        
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++; 
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;        
        i++;
        i++;
        
        i++;
        i++;
        
        i++;
        i++;
        
        i++;
        i++;
        
        i++;
        i++;
        
        i++;
        i++;
        
        i++;
        i++;
        
        i++;
        i++;

        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        
    }
}