unpackaged/main/default/objects/CICO_Intimation_Line__c/CICO_Intimation_Line__c.object-meta.xml
<CustomObject>
    <label>Intimation Line</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Intimation Line ID</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Intimation Lines</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

unpackaged/main/default/objects/CICO_Vehicle_Spec__c/CICO_Vehicle_Spec__c.object-meta.xml
<CustomObject>
    <description>Check In Check Out</description>
    <label>Vehicles/Inspections</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Chassis No</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Vehicles/Inspections</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

unpackaged/main/default/objects/CICO_Vehicle_Spec__c/fields/Actual_Receive_Date__c.field-meta.xml
<CustomField>
    <fullName>Actual_Receive_Date__c</fullName>
    <description>Name changed from Actual receive date to Actual Inspection Date</description>
    <encryptionScheme>None</encryptionScheme>
    <label>Actual Inspection Date</label>
    <type>Date</type>
</CustomField>

unpackaged/main/default/objects/CICO_Vehicle_Spec__c/fields/Inspected__c.field-meta.xml
<CustomField>
    <fullName>Inspected__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Inspected?</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/objects/CICO_Vehicle_Spec__c/fields/Intimation_Line__c.field-meta.xml
<CustomField>
    <fullName>Intimation_Line__c</fullName>
    <label>Intimation Line</label>
    <referenceTo>CICO_Intimation_Line__c</referenceTo>
    <relationshipName>Vehicle_Spec</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

unpackaged/main/default/objects/CICO_Vehicle_Spec__c/fields/Penalty__c.field-meta.xml
<CustomField>
    <fullName>Penalty__c</fullName>
    <label>Penalty ?</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Yes</fullName>
            </value>
            <value>
                <fullName>No</fullName>
                <default>true</default>
                <label>No</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/CICO_Vehicle_Spec__c/fields/Shipped_Date__c.field-meta.xml
<CustomField>
    <fullName>Shipped_Date__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Shipped Date</label>
    <type>Date</type>
</CustomField>

unpackaged/main/default/objects/CICO_Vehicle_Spec__c/fields/Sup_Doc_Date__c.field-meta.xml
<CustomField>
    <fullName>Sup_Doc_Date__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Sup Doc Date</label>
    <type>Date</type>
</CustomField>

unpackaged/main/default/objects/CICO_Vehicle_Spec__c/fields/Sup_Doc_No__c.field-meta.xml
<CustomField>
    <fullName>Sup_Doc_No__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Sup Doc No</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/CICO_Vehicle_Spec__c/fields/Sup_Doc_Type__c.field-meta.xml
<CustomField>
    <fullName>Sup_Doc_Type__c</fullName>
    <label>Sup Doc Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Invoice Number</fullName>
            </value>
            <value>
                <fullName>Delivery Note</fullName>
                <default>true</default>
                <label>Delivery Note</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/classes/CICO_vehicleShipmentsTrgHandler.cls
public class CICO_vehicleShipmentsTrgHandler {
    
    public static void updateShipmentDetails(list<CICO_Vehicle_Spec__c> trgNew,map<id,CICO_Vehicle_Spec__c> trgOld){
        
        map<Id,Date> intiLineIdVsShipDate = new  map<Id,Date>();
        map<Id,Date> intiLineIdVsActRecvDate = new  map<Id,Date>();
        map<Id,string> intiLineIdVsSupDocType = new  map<Id,string>();
        map<Id,string> intiLineIdVsSupDocNo = new  map<Id,string>();
        map<Id,Date> intiLineIdVsSupDocDate = new  map<Id,Date>();
        map<Id,string> intiLineIdVsPenality = new  map<Id,string>();
        set<Id> intimationLineIDs = new set<Id>();
        
        list<CICO_Vehicle_Spec__c> shipmentDetailsUpdate = new list<CICO_Vehicle_Spec__c>();
        
        for(CICO_Vehicle_Spec__c cv : trgNew){
            if(cv.Intimation_Line__c != null)
            intimationLineIDs.add(cv.Intimation_Line__c);
            
            if(cv.Shipped_Date__c != null)
            intiLineIdVsShipDate.put(cv.Intimation_Line__c,cv.Shipped_Date__c);
            
            if(cv.Actual_Receive_Date__c != null)
            intiLineIdVsActRecvDate.put(cv.Intimation_Line__c,cv.Actual_Receive_Date__c);
            
             if(cv.Sup_Doc_Type__c != null)
            intiLineIdVsSupDocType.put(cv.Intimation_Line__c,cv.Sup_Doc_Type__c);
            
            if(cv.Sup_Doc_No__c != null)
            intiLineIdVsSupDocNo.put(cv.Intimation_Line__c,cv.Sup_Doc_No__c);
            
            if(cv.Sup_Doc_Date__c != null)
            intiLineIdVsSupDocDate.put(cv.Intimation_Line__c,cv.Sup_Doc_Date__c);
            
            if(cv.Penalty__c != null)
            intiLineIdVsPenality.put(cv.Intimation_Line__c,cv.Penalty__c);
            
        }
        
        for(CICO_Intimation_Line__c lines : [select id, (select id,Intimation_Line__c,Shipped_Date__c,Actual_Receive_Date__c,Sup_Doc_Type__c,Sup_Doc_No__c,Sup_Doc_Date__c,Penalty__c from Vehicle_Spec__r where Inspected__c =false) from CICO_Intimation_Line__c where id=:intimationLineIDs]){
             
            for(CICO_Vehicle_Spec__c cvs : lines.Vehicle_Spec__r){
                
                if(intiLineIdVsShipDate.containsKey(cvs.Intimation_Line__c))
                cvs.Shipped_Date__c = intiLineIdVsShipDate.get(cvs.Intimation_Line__c);
                
                if(intiLineIdVsActRecvDate.containsKey(cvs.Intimation_Line__c))
                cvs.Actual_Receive_Date__c = intiLineIdVsActRecvDate.get(cvs.Intimation_Line__c);
                
                if(intiLineIdVsSupDocType.containsKey(cvs.Intimation_Line__c))
                cvs.Sup_Doc_Type__c = intiLineIdVsSupDocType.get(cvs.Intimation_Line__c);
                
                 if(intiLineIdVsSupDocNo.containsKey(cvs.Intimation_Line__c))
                cvs.Sup_Doc_No__c = intiLineIdVsSupDocNo.get(cvs.Intimation_Line__c);
                
                 if(intiLineIdVsSupDocDate.containsKey(cvs.Intimation_Line__c))
                cvs.Sup_Doc_Date__c = intiLineIdVsSupDocDate.get(cvs.Intimation_Line__c);
                
                 if(intiLineIdVsPenality.containsKey(cvs.Intimation_Line__c))
                cvs.Penalty__c = intiLineIdVsPenality.get(cvs.Intimation_Line__c);
                
                shipmentDetailsUpdate.add(cvs);
            }
            
        }
        
        try{
            update shipmentDetailsUpdate;
            
        }catch(Exception e) {
            System.debug('An exception occurred: ' + e.getMessage());
        }
        
            
            
    }

}