unpackaged/main/default/objects/Maintenance_Questionnaire__c/Maintenance_Questionnaire__c.object-meta.xml
<CustomObject>
    <label>Maintenance Questionnaire</label>
    <nameField>
        <displayFormat>MQ-{0000}</displayFormat>
        <label>Maintenance Questionnaire Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Maintenance Questionnaires</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Maintenance_Request__c/Maintenance_Request__c.object-meta.xml
<CustomObject>
    <label>Maintenance Request</label>
    <nameField>
        <displayFormat>MR-{0000}</displayFormat>
        <label>Maintenance Request Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Maintenance Requests</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Maintenance_Request__c/fields/Maintenance_Questionnaire__c.field-meta.xml
<CustomField>
    <fullName>Maintenance_Questionnaire__c</fullName>
    <label>Maintenance Questionnaire</label>
    <referenceTo>Maintenance_Questionnaire__c</referenceTo>
    <relationshipLabel>Maintenance Requests</relationshipLabel>
    <relationshipName>Maintenance_Requests</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

unpackaged/main/default/objects/Maintenance_Request__c/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <label>Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Maintenance Requests</relationshipLabel>
    <relationshipName>Maintenance_Requests</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

unpackaged/main/default/classes/ET_CreateMaintainanceController.cls
public class ET_CreateMaintainanceController {
    
    @AuraEnabled
    public static Boolean createMaintenanceRequestRecord(List<Maintenance_Request__c> maintenanceRequestList,String opportunityId,Maintenance_Questionnaire__c maintenanceQuestionnaire ){
        Boolean returnValue = true ;
        system.debug('maintenanceRequestList = '+maintenanceRequestList);
        system.debug('opportunityId = '+opportunityId);
        system.debug('maintenanceQuestionnaire = '+maintenanceQuestionnaire);
        try{
            insert maintenanceQuestionnaire;
            
            for(Maintenance_Request__c mr :maintenanceRequestList){
                mr.Opportunity__c = opportunityId;
                mr.Maintenance_Questionnaire__c = maintenanceQuestionnaire.Id;
            }
            system.debug('maintenanceRequestList after opp and Questionnaire update = '+maintenanceRequestList);
            insert maintenanceRequestList;
        }catch(Exception e){
            system.debug('maintenanceRequest Error = '+e.getMessage());
            returnValue= false;
        }
        return returnValue;
    }
    
}