unpackaged/main/default/objects/Contact/fields/ETIN_Insurance_Card_Number__c.field-meta.xml
<CustomField>
    <fullName>ETIN_Insurance_Card_Number__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Insurance Card Number</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

unpackaged/main/default/objects/Contact/recordTypes/ET_Employees.recordType-meta.xml
<RecordType>
    <fullName>ET_Employees</fullName>
    <active>true</active>
    <label>ET Employees</label>
</RecordType>

unpackaged/main/default/objects/Contact/recordTypes/ETIN_Employee_Family.recordType-meta.xml
<RecordType>
    <fullName>ETIN_Employee_Family</fullName>
    <active>true</active>
    <label>Employee Family</label>
</RecordType>

unpackaged/main/default/objects/ETIN_DefaultInsurancePartners__c/ETIN_DefaultInsurancePartners__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <label>Default Insurance Partners</label>
</CustomObject>

unpackaged/main/default/objects/ETIN_DefaultInsurancePartners__c/fields/Account_ID__c.field-meta.xml
<CustomField>
    <fullName>Account_ID__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Account ID</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/ETIN_Insurance__c/ETIN_Insurance__c.object-meta.xml
<CustomObject>
    <label>Insurance</label>
    <nameField>
        <displayFormat>ETIN-{000000}</displayFormat>
        <label>Insurance Ref Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Insurances</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

unpackaged/main/default/objects/ETIN_Insurance__c/fields/Card_Number__c.field-meta.xml
<CustomField>
    <fullName>Card_Number__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Card Number</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/ETIN_Insurance__c/fields/EmployeeAcc__c.field-meta.xml
<CustomField>
    <fullName>EmployeeAcc__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Employee</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Insurances</relationshipLabel>
    <relationshipName>Insurances</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/ETIN_Insurance__c/fields/Insurance_Company_Email__c.field-meta.xml
<CustomField>
    <fullName>Insurance_Company_Email__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Insurance Company Email</label>
    <type>Email</type>
</CustomField>

unpackaged/main/default/objects/ETIN_Insurance__c/fields/Insurance_Current_Status__c.field-meta.xml
<CustomField>
    <fullName>Insurance_Current_Status__c</fullName>
    <label>Insurance Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Active</fullName>
            </value>
            <value>
                <fullName>Inactive</fullName>
                <default>true</default>
                <label>Inactive</label>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
            <value>
                <fullName>Duplicate</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/ETIN_Insurance__c/fields/Insurance_Policy_Number__c.field-meta.xml
<CustomField>
    <fullName>Insurance_Policy_Number__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Insurance Policy Number</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/ETIN_Insurance__c/fields/Renew_Request__c.field-meta.xml
<CustomField>
    <fullName>Renew_Request__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Renewal Request?</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/objects/ETIN_Insurance__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Request Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>New</fullName>
                <default>true</default>
                <label>New</label>
            </value>
            <value>
                <fullName>Pending with HR Manager</fullName>
            </value>
            <value>
                <fullName>Under Process</fullName>
            </value>
            <value>
                <fullName>Under Approval</fullName>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
            <value>
                <fullName>Pending with Zone Coordinator</fullName>
            </value>
            <value>
                <fullName>Not Eligible</fullName>
            </value>
            <value>
                <fullName>Under Investigation</fullName>
            </value>
            <value>
                <fullName>Hold</fullName>
            </value>
            <value>
                <fullName>Admin Approval Pending</fullName>
                <isActive>false</isActive>
                <label>Admin Approval Pending</label>
            </value>
            <value>
                <fullName>Admin Approved</fullName>
                <isActive>false</isActive>
                <label>Admin Approved</label>
            </value>
            <value>
                <fullName>Admin Rejected</fullName>
                <isActive>false</isActive>
                <label>Admin Rejected</label>
            </value>
            <value>
                <fullName>HR Rejected</fullName>
                <isActive>false</isActive>
                <label>HR Rejected</label>
            </value>
            <value>
                <fullName>Insurance Approved</fullName>
                <isActive>false</isActive>
                <label>Insurance Approved</label>
            </value>
            <value>
                <fullName>Insurance Pending</fullName>
                <isActive>false</isActive>
                <label>Insurance Pending</label>
            </value>
            <value>
                <fullName>Insurance Rejected</fullName>
                <isActive>false</isActive>
                <label>Insurance Rejected</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/ETIN_Insurance__c/recordTypes/Health_Insurance.recordType-meta.xml
<RecordType>
    <fullName>Health_Insurance</fullName>
    <active>true</active>
    <label>Health Insurance</label>
</RecordType>

unpackaged/main/default/classes/ETIN_InsuranceAdminControllerTest.cls
@IsTest (SeeAllData=true)
public class ETIN_InsuranceAdminControllerTest {
    
    private static testmethod void getInsuranceDetails(){
        ETIN_InsuranceAdminController.getInsuranceDetails('test', 'test', 'test', 'test', 'test', 'test','');
    }
    
    private static testmethod void getEmployeeDetails(){
        ETIN_InsuranceAdminController.getEmployeeDetails('test', 'test', 'test', 'test','Abu Dhabi');
        ETIN_InsuranceAdminController.getEmployeeFamilyDetails('test', 'test', 'test');
    }
    
    private static testmethod void getRecordTypeId(){
        ETIN_InsuranceAdminController.getRecordTypeId('ETIN_Insurance__c', 'Health_Insurance');
    }
    
    private static testmethod void getselectOptions(){
        
        ETIN_InsuranceAdminController.getselectOptions('Case', 'Status');     
    }
    private static testmethod void commonMethod(){
        
         Id empRecTypeId = Schema.SObjectType.contact.getRecordTypeInfosByDeveloperName().get('ET_Employees').getRecordTypeId();
        Id empRecTypeId2 = Schema.SObjectType.contact.getRecordTypeInfosByDeveloperName().get('ETIN_Employee_Family').getRecordTypeId();
        
        ETIN_InsuranceAdminController.getAttachments('');
        ETIN_InsuranceAdminController.getPartnerAccList();
        Account acc = new account();
        acc.Name = 'test34231';
        
        insert acc;
        
        Contact co = new contact();
        co.AccountId = acc.Id;
        co.LastName = 'lastname';
        co.RecordTypeId = empRecTypeId2;
        co.ETIN_Insurance_Card_Number__c = '213';
        insert co;
        
         Id insHealthRecID  = Schema.SObjectType.ETIN_Insurance__c.getRecordTypeInfosByDeveloperName().get('Health_Insurance').getRecordTypeId();
        ETIN_Insurance__c et = new ETIN_Insurance__c();
        et.Insurance_Policy_Number__c = '133323';
        et.Insurance_Current_Status__c = 'Active';
        et.Insurance_Company_Email__c='test@gmail.com';
        et.Card_Number__c = '112121212';
        et.EmployeeAcc__c = acc.Id;
        et.Renew_Request__c = false;
        et.Status__c='Completed';
        et.Insurance_Current_Status__c ='Active';
        et.RecordTypeId =insHealthRecID;
        
        insert et;
        
        ETIN_InsuranceAdminController.singleRecRenewPrcss(et.Id);
        
        //ETIN_InsuranceAdminController.getImageContent('');   
        ETIN_InsuranceAdminController.getAttachments('');
        // ETIN_InsuranceAdminController.deleteAttachment('');
       
        
        ETIN_InsuranceAdminController.singleRecRenewPrcss(et.Id);
        
        ETIN_InsuranceAdminController.getRenewalButtonSettings();
        ETIN_InsuranceAdminController.getInsMasterDetails();
        ETIN_InsuranceAdminController.getDocumentMasterDetails('Dubai');
        ETIN_InsuranceAdminController.getInsClaimDetails();
                ETIN_InsuranceAdminController.fetchUser();
        
        
        
         //
        Test.startTest();
          //  ETIN_InsuranceAdminController.callBatchClsHealthRenewPrcs(acc.id, '');
       /* ETIN_BulkHealthApprovalBatchCls etb = new ETIN_BulkHealthApprovalBatchCls(acc.Id,'');
        database.executeBatch(etb,1);*/
        
        ContentVersion cv = new ContentVersion();
        cv.Title = 'Test Document';
        cv.PathOnClient = 'TestDocument.pdf';
        cv.VersionData = Blob.valueOf('Test Content');
        cv.IsMajorVersion = true;
        Insert cv;
        
        //Get Content Version
        List<ContentVersion> cvList = [SELECT Id, Title, ContentDocumentId FROM ContentVersion WHERE Id = :cv.Id];
        System.assertEquals(cvList.size(), 1);
        
        //Get Content Documents
        List<ContentDocument> cdList = [SELECT Id, Title, LatestPublishedVersionId FROM ContentDocument];
        
        
        ETIN_InsuranceAdminController.getImageContent(cvList[0].ContentDocumentId);
        
        //ETIN_InsuranceAdminController.deleteAttachment(cdList[0].Id);
        
        ETIN_DefaultInsurancePartners__c isp = new ETIN_DefaultInsurancePartners__c();
        isp.Name = 'test';
        isp.Account_ID__c ='test';
        insert isp;
        ETIN_InsuranceAdminController.getDefaultInsPartners();
        Test.stopTest();

    }
    
}