unpackaged/main/default/objects/Contact/fields/ETVIN_Insurance_Portal_User__c.field-meta.xml
<CustomField>
    <fullName>ETVIN_Insurance_Portal_User__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Insurance Portal User</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/objects/Correction_Cancel_Request__c/Correction_Cancel_Request__c.object-meta.xml
<CustomObject>
    <label>Vehicle Requests</label>
    <nameField>
        <displayFormat>Req - {000000}</displayFormat>
        <label>Request Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Vehicle Requests</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Correction_Cancel_Request__c/fields/Insurance_Cancellation_Letter__c.field-meta.xml
<CustomField>
    <fullName>Insurance_Cancellation_Letter__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Insurance Cancellation Letter</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/objects/Correction_Cancel_Request__c/fields/Insurance_Company__c.field-meta.xml
<CustomField>
    <fullName>Insurance_Company__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Insurance Company</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Vehicle Requests</relationshipLabel>
    <relationshipName>Correction_Cancel_Requests</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Correction_Cancel_Request__c/fields/Journey_Status__c.field-meta.xml
<CustomField>
    <fullName>Journey_Status__c</fullName>
    <label>Journey Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Created</fullName>
                <default>true</default>
                <label>Created</label>
            </value>
            <value>
                <fullName>Police Report Attached</fullName>
            </value>
            <value>
                <fullName>1.Insurance Pending</fullName>
            </value>
            <value>
                <fullName>Prove Theft Report Attached</fullName>
            </value>
            <value>
                <fullName>Compensation/Claim Created</fullName>
            </value>
            <value>
                <fullName>NOC</fullName>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
            <value>
                <fullName>2.Insurance Pending</fullName>
                <isActive>false</isActive>
                <label>2.Insurance Pending</label>
            </value>
            <value>
                <fullName>PRO Notified</fullName>
                <isActive>false</isActive>
                <label>PRO Notified</label>
            </value>
            <value>
                <fullName>Reminder Email Sent</fullName>
                <isActive>false</isActive>
                <label>Reminder Email Sent</label>
            </value>
            <value>
                <fullName>Review</fullName>
                <isActive>false</isActive>
                <label>Review</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Correction_Cancel_Request__c/fields/Plate_Number__c.field-meta.xml
<CustomField>
    <fullName>Plate_Number__c</fullName>
    <formula>Vehicle_Master__r.Plate_Number__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Regd No.</label>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Correction_Cancel_Request__c/fields/Police_Report__c.field-meta.xml
<CustomField>
    <fullName>Police_Report__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Police Report</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/objects/Correction_Cancel_Request__c/fields/Prove_Theft_certificate__c.field-meta.xml
<CustomField>
    <fullName>Prove_Theft_certificate__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Prove Theft certificate</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/objects/Correction_Cancel_Request__c/fields/Reason_for_Cancellation__c.field-meta.xml
<CustomField>
    <fullName>Reason_for_Cancellation__c</fullName>
    <label>Reason for Cancellation</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Vehicle Theft</fullName>
            </value>
            <value>
                <fullName>Scrapped Vehicle Theft</fullName>
            </value>
            <value>
                <fullName>Vehicle Sold</fullName>
            </value>
            <value>
                <fullName>Scrapped Vehicle</fullName>
                <isActive>false</isActive>
                <label>Scrapped Vehicle</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Correction_Cancel_Request__c/fields/Transfer_Profession_Certificate__c.field-meta.xml
<CustomField>
    <fullName>Transfer_Profession_Certificate__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Transfer Profession Certificate</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/objects/Correction_Cancel_Request__c/fields/Vehicle_Insurance_Policy__c.field-meta.xml
<CustomField>
    <fullName>Vehicle_Insurance_Policy__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Vehicle Insurance Policy</label>
    <referenceTo>ETVIN_Vehicle_Insurance__c</referenceTo>
    <relationshipLabel>Vehicle Requests</relationshipLabel>
    <relationshipName>Correction_Cancel_Requests</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Correction_Cancel_Request__c/fields/Vehicle_Interanal_Number__c.field-meta.xml
<CustomField>
    <fullName>Vehicle_Interanal_Number__c</fullName>
    <formula>Vehicle_Master__r.Internal_No__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Vehicle Interanal Number</label>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Correction_Cancel_Request__c/fields/Vehicle_Master__c.field-meta.xml
<CustomField>
    <fullName>Vehicle_Master__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Vehicle</label>
    <referenceTo>Vehicle_Master__c</referenceTo>
    <relationshipName>Correction_Cancel_Requests</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Correction_Cancel_Request__c/fields/Vehicle_Theft_Date__c.field-meta.xml
<CustomField>
    <fullName>Vehicle_Theft_Date__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Vehicle Theft Date</label>
    <type>Date</type>
</CustomField>

unpackaged/main/default/objects/Correction_Cancel_Request__c/recordTypes/Vehicle_Theft_Request.recordType-meta.xml
<RecordType>
    <fullName>Vehicle_Theft_Request</fullName>
    <active>true</active>
    <label>Vehicle Theft Request</label>
</RecordType>

unpackaged/main/default/objects/ETIN_Claim__c/ETIN_Claim__c.object-meta.xml
<CustomObject>
    <label>Claim</label>
    <nameField>
        <displayFormat>CL-{000000}</displayFormat>
        <label>Claim Ref Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Claims</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/ETIN_Claim__c/fields/Accident_Date__c.field-meta.xml
<CustomField>
    <fullName>Accident_Date__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Incident Date</label>
    <type>Date</type>
</CustomField>

unpackaged/main/default/objects/ETIN_Claim__c/fields/Cancel_Request__c.field-meta.xml
<CustomField>
    <fullName>Cancel_Request__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Cancel Request</label>
    <referenceTo>Correction_Cancel_Request__c</referenceTo>
    <relationshipLabel>Claims</relationshipLabel>
    <relationshipName>Claims</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/ETIN_Claim__c/fields/Claim_for__c.field-meta.xml
<CustomField>
    <fullName>Claim_for__c</fullName>
    <label>Claim for</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Vehicle Theft</fullName>
            </value>
            <value>
                <fullName>Accident</fullName>
            </value>
            <value>
                <fullName>Scrapped Vehicle</fullName>
            </value>
            <value>
                <fullName>Scrapped Vehicle Theft</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/ETIN_Claim__c/fields/ETIN_Claim_Status__c.field-meta.xml
<CustomField>
    <fullName>ETIN_Claim_Status__c</fullName>
    <label>Claim Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>New</fullName>
                <default>true</default>
                <label>New</label>
            </value>
            <value>
                <fullName>Under Process</fullName>
            </value>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>Rejected</fullName>
            </value>
            <value>
                <fullName>Pending with Zone Coordinator</fullName>
            </value>
            <value>
                <fullName>Under Approval</fullName>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
            <value>
                <fullName>Pending</fullName>
            </value>
            <value>
                <fullName>Admin Approval Pending</fullName>
                <isActive>false</isActive>
                <label>Admin Approval Pending</label>
            </value>
            <value>
                <fullName>Admin Approved</fullName>
                <isActive>false</isActive>
                <label>Admin Approved</label>
            </value>
            <value>
                <fullName>Admin Rejected</fullName>
                <isActive>false</isActive>
                <label>Admin Rejected</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/ETIN_Claim__c/fields/ETIN_Insurance_Partner__c.field-meta.xml
<CustomField>
    <fullName>ETIN_Insurance_Partner__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Insurance Partner</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Claim</relationshipLabel>
    <relationshipName>Claim</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/ETIN_Claim__c/fields/ETVIN_Vehicle_Insurance__c.field-meta.xml
<CustomField>
    <fullName>ETVIN_Vehicle_Insurance__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Vehicle Insurance</label>
    <referenceTo>ETVIN_Vehicle_Insurance__c</referenceTo>
    <relationshipLabel>Claims</relationshipLabel>
    <relationshipName>Claims</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/ETIN_Claim__c/fields/Plate_Number__c.field-meta.xml
<CustomField>
    <fullName>Plate_Number__c</fullName>
    <formula>Vehicle_Master__r.Plate_Number__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Plate Number</label>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/ETIN_Claim__c/fields/Vehicle_Master__c.field-meta.xml
<CustomField>
    <fullName>Vehicle_Master__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Vehicle</label>
    <referenceTo>Vehicle_Master__c</referenceTo>
    <relationshipLabel>Claims</relationshipLabel>
    <relationshipName>Claims</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/ETIN_Claim__c/recordTypes/Vehicle_Insurance.recordType-meta.xml
<RecordType>
    <fullName>Vehicle_Insurance</fullName>
    <active>true</active>
    <label>Vehicle Insurance</label>
</RecordType>

unpackaged/main/default/objects/ETVIN_Vehicle_Insurance__c/ETVIN_Vehicle_Insurance__c.object-meta.xml
<CustomObject>
    <description>Vehicle Insurance</description>
    <label>Vehicle Insurance Policy</label>
    <nameField>
        <displayFormat>VI-{0000}</displayFormat>
        <label>Insurance Ref Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Vehicle Insurance Policies</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Vehicle_Master__c/Vehicle_Master__c.object-meta.xml
<CustomObject>
    <description>Emirates Transport Oracle Vehicle Master</description>
    <label>ET Vehicle Master</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Vehicle No.</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>ET Vehicle Masters</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Vehicle_Master__c/fields/Plate_Number__c.field-meta.xml
<CustomField>
    <fullName>Plate_Number__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Plate Number</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/VehicleInsEmailNotification__c/VehicleInsEmailNotification__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <label>VehicleInsEmailNotification</label>
</CustomObject>

unpackaged/main/default/classes/ETVIN_Corr_Can_Req_Trg_Handler.cls
/*
* File Name:ETVIN_Corr_Can_Req_Trg_Handler
* Author : Janardhan Muddana
* CreatedDate : 11/2/2020
* Modification Purpose
* * 1. Janardhan Muddana: Created for Send notifications
* * 2.
*/
public class ETVIN_Corr_Can_Req_Trg_Handler {
    
    public static void creatingclaim(list<Correction_Cancel_Request__c> trigNew ,Map<Id, Correction_Cancel_Request__c> oldMap){
        system.debug('sendNotificationafterupdate');
        list<ETIN_Claim__c> claimCreateList1 = new list<ETIN_Claim__c>();
        for(Correction_Cancel_Request__c crrs : trigNew){
             system.debug('afterupdateinsideforloop');
            if(crrs.Journey_Status__c == 'Compensation/Claim Created' && crrs.Journey_Status__c!=oldMap.get(crrs.id).Journey_Status__c){
               
             ETIN_Claim__c cl = new ETIN_Claim__c();
                 cl.Claim_for__c = crrs.Reason_for_Cancellation__c;
                 cl.Claim_Amount__c = 100;
                 cl.ETIN_Insurance_Partner__c = crrs.Insurance_Company__c;
                 cl.ETVIN_Vehicle_Insurance__c = crrs.Vehicle_Insurance_Policy__c;
                 cl.Vehicle_Master__c = crrs.Vehicle_Master__c;
                 cl.ETIN_Claim_Status__c = 'New';
                 cl.Accident_Date__c = crrs.Vehicle_Theft_Date__c;
                 cl.Cancel_Request__c = crrs.Id;
               
                 cl.RecordTypeId = SObjectType.ETIN_Claim__c.getRecordTypeInfosByDeveloperName().get('Vehicle_Insurance').getRecordTypeId();
                 
                 claimCreateList1.add(cl);
                insert claimCreateList1;
             system.debug('afterupdateimsideifend');
                
            }
            
             
        }
        
        
        
    }
  
   public static void sendNotification(list<Correction_Cancel_Request__c> trgNew ,Map<Id, Correction_Cancel_Request__c> oldMap){
       system.debug('sendNotification');
        
      EmailTemplate emailTemplate = [select Id, Body,HtmlValue  from EmailTemplate where DeveloperName = 'Vehicle_PoliceReport_Notification'];
      EmailTemplate emailTemplate1 = [select Id, Body,HtmlValue  from EmailTemplate where DeveloperName = 'Vehicle_ProveTheft_Notification'];
       set<id> accountIds = new set<id>();
       map<id,list<string>> accidVsConEmails = new map<id,list<string>>();
       list<ETIN_Claim__c> claimCreateList = new list<ETIN_Claim__c>();
        
        Messaging.SingleEmailMessage[] emailList = new list<Messaging.SingleEmailMessage>();
       /*  
        for(Correction_Cancel_Request__c crr : trgNew){
            
            accountIds.add(crr.Insurance_Company__c);
        }
        for(contact con : [select id,AccountId,email from contact where ETVIN_Insurance_Portal_User__c = true AND AccountId=:accountIds]){
            if(!accidVsConEmails.containsKey(con.AccountId)) {
                accidVsConEmails.put(con.AccountId,new list<string>{con.Email});          
            }else{
                
                accidVsConEmails.get(con.AccountId).add(con.Email); 
            }
           
        }
        */
        //system.debug('--emails--'+accidVsConEmails);
        
        for(Correction_Cancel_Request__c crr : trgNew){
            
            if(crr.Police_Report__c == True && oldMap.get(crr.Id).Police_Report__c != crr.Police_Report__c){
                
              /*  String htmlBody = emailTemplate.HtmlValue; 
                Messaging.SingleEmailMessage email = new Messaging.SingleEmailMessage();
                email.setToAddresses(accidVsConEmails.get(crr.Insurance_Company__c));
                email.setSaveAsActivity(false);
                email.setSubject('Police Report');
                email.setTargetObjectId(UserInfo.getUserId());//
                email.setTemplateId(emailTemplate.Id);
                htmlBody = htmlBody.replace('{!Correction_Cancel_Request__c.Id}', crr.Id);
          
               email.setHtmlBody(htmlBody);
                
                emailList.add(email);*/
                
               //update journey status
               crr.Journey_Status__c = 'Police Report Attached';
               
              
            }
            
             if(crr.Prove_Theft_certificate__c == True && oldMap.get(crr.Id).Prove_Theft_certificate__c != crr.Prove_Theft_certificate__c){
               
                /*  String htmlBody = emailTemplate1.HtmlValue; 
                 Messaging.SingleEmailMessage email = new Messaging.SingleEmailMessage();
                 email.setToAddresses(accidVsConEmails.get(crr.Insurance_Company__c));
                 email.setSaveAsActivity(false);
                 email.setSubject('Prove Theft Certificate');
                 email.setTargetObjectId(UserInfo.getUserId());//
                 email.setTemplateId(emailTemplate1.Id);
                 htmlBody = htmlBody.replace('{!Correction_Cancel_Request__c.Id}', crr.Id);
                 
                 email.setHtmlBody(htmlBody);
                 
                 emailList.add(email);
                                   */
               //update journey status
               crr.Journey_Status__c = 'Prove Theft Report Attached';
               //Creating Claim 
              
                 system.debug('Creating Claim ');
                 
                 
             }
            if(crr.Transfer_Profession_Certificate__c == True && oldMap.get(crr.Id).Transfer_Profession_Certificate__c != crr.Transfer_Profession_Certificate__c){
              
               /*   Messaging.SingleEmailMessage email = new Messaging.SingleEmailMessage();
                 email.setToAddresses(accidVsConEmails.get(crr.Insurance_Company__c));
                 email.setSaveAsActivity(false);
                 email.setTargetObjectId(UserInfo.getUserId());//
                String htmlBody = '<p>Hi Team,</p>';
                htmlBody+=   '<p>Transfer profession certificate added to the cancellation request, please click on below link to access the request.</p>' ;
                htmlBody+=   System.label.ETVIN_partnerPortalUrl+'?recordId='+ crr.id +'&tab=Cancellation';
                
                htmlBody+=   '<p>Thank you and best regards,</p>';
                htmlBody+=   '<p>Insurance Team</p>';
                email.setSubject('Transfer Profession Certificate');
                  
                 
                 email.setHtmlBody(htmlBody);
                 
                 emailList.add(email);
            */
             }

             if(crr.Insurance_Cancellation_Letter__c == True && oldMap.get(crr.Id).Insurance_Cancellation_Letter__c != crr.Insurance_Cancellation_Letter__c){
              
                /* Messaging.SingleEmailMessage email = new Messaging.SingleEmailMessage();
                 email.setToAddresses(accidVsConEmails.get(crr.Insurance_Company__c));
                 email.setSaveAsActivity(false);
                 email.setTargetObjectId(UserInfo.getUserId());//
                String htmlBody = '<p>Hi Team,</p>';
                htmlBody+=   '<p>Insurance cancellation letter added to the cancellation request, please click on below link to access the request.</p>' ;
                htmlBody+=   System.label.ETVIN_partnerPortalUrl+'?recordId='+ crr.id +'&tab=Cancellation';
                
                htmlBody+=   '<p>Thank you and best regards,</p>';
                htmlBody+=   '<p>Insurance Team</p>';
                email.setSubject('Insurance Cancellation Letter');
                  
                 
                 email.setHtmlBody(htmlBody);
                 
                 emailList.add(email);*/
            
             }
        }  
       
        
        Messaging.SendEmailResult[] results = Messaging.sendEmail(emailList); 
        
        if(claimCreateList.size()>0)
        Database.SaveResult[] insertResults = Database.insert(claimCreateList,false);
        
    }
    
   /* public static void sendNotificationToPRO(list<Correction_Cancel_Request__c> trgNew){
        
      string ProEmail = [select id,Email__c  from VehicleInsEmailNotification__c where Label__c='PRO'].Email__c; 
        
        Messaging.SingleEmailMessage[] emailList = new list<Messaging.SingleEmailMessage>();
        Id recordTypeId =  Schema.SObjectType.Correction_Cancel_Request__c.getRecordTypeInfosByDeveloperName().get('Vehicle_Theft_Request').getRecordTypeId();
        
        if(ProEmail != null )
        for(Correction_Cancel_Request__c cr : trgNew){
            
            if(recordTypeId == cr.RecordTypeId){
             Messaging.SingleEmailMessage email = new Messaging.SingleEmailMessage();
                 email.setToAddresses(new String[] {ProEmail});
                 email.setSaveAsActivity(false);
                 email.setTargetObjectId(UserInfo.getUserId());
                String htmlBody = '<p>Dear Pro,</p>';
                htmlBody+=   '<p>Please find the below thefted vehicle details.</p>' ;
                htmlBody+= '<p> VIN Number -'+cr.Vehicle_Interanal_Number__c+'</p>';
                htmlBody+= '<p> Plate Number -'+cr.Plate_Number__c+'</p>';
               
                htmlBody+=   '<p>Thank you and best regards,</p>';
                htmlBody+=   '<p>Insurance Team</p>';
                email.setSubject('New Vehicle Theft Request');
                email.setHtmlBody(htmlBody);
            
                emailList.add(email);
            //update journey status
            cr.Journey_Status__c = 'PRO Notified';
            }
        }
          Messaging.SendEmailResult[] results = Messaging.sendEmail(emailList);    
      
    } */
    
}