unpackaged/main/default/objects/Contact/fields/Location_Code__c.field-meta.xml
<CustomField>
    <fullName>Location_Code__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Location Code</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/ET_Customer_Vehicle__c/ET_Customer_Vehicle__c.object-meta.xml
<CustomObject>
    <label>Customer Vehicle</label>
    <nameField>
        <displayFormat>CV-{000000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Customer Vehicles</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/ET_Customer_Vehicle__c/fields/Chassis_No__c.field-meta.xml
<CustomField>
    <fullName>Chassis_No__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Chassis No</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/ET_Customer_Vehicle__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <defaultValue>&quot;Active&quot;</defaultValue>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Active</fullName>
            </value>
            <value>
                <fullName>Frozen</fullName>
            </value>
            <value>
                <fullName>Inactive</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/ET_Customer_Vehicle__c/recordTypes/Vehicle_Inspection.recordType-meta.xml
<RecordType>
    <fullName>Vehicle_Inspection</fullName>
    <active>true</active>
    <label>Vehicle Inspection</label>
</RecordType>

unpackaged/main/default/objects/ET_Location__c/ET_Location__c.object-meta.xml
<CustomObject>
    <label>Inspection Center</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>ET Loaction Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Inspection Centers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/ET_Location__c/fields/Location_Code__c.field-meta.xml
<CustomField>
    <fullName>Location_Code__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Location Code</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/ET_Location__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Active</fullName>
            </value>
            <value>
                <fullName>InActive</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/ET_Service_Request__c/ET_Service_Request__c.object-meta.xml
<CustomObject>
    <label>Service Request</label>
    <nameField>
        <displayFormat>SR-{000000}</displayFormat>
        <label>Service Request Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Service Requests</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

unpackaged/main/default/objects/ET_Service_Request__c/fields/ET_Account__c.field-meta.xml
<CustomField>
    <fullName>ET_Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Service Requests (Account)</relationshipLabel>
    <relationshipName>Service_Requests</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/ET_Service_Request__c/fields/ET_Location__c.field-meta.xml
<CustomField>
    <fullName>ET_Location__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Location</label>
    <referenceTo>ET_Location__c</referenceTo>
    <relationshipLabel>Service Requests</relationshipLabel>
    <relationshipName>Service_Requests</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/ET_Service_Request__c/fields/ETI_Payment_Type__c.field-meta.xml
<CustomField>
    <fullName>ETI_Payment_Type__c</fullName>
    <label>Payment Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>On Premises</fullName>
            </value>
            <value>
                <fullName>Online</fullName>
            </value>
            <value>
                <fullName>Card</fullName>
            </value>
            <value>
                <fullName>Cash</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/ET_Service_Request__c/fields/Payment_Status__c.field-meta.xml
<CustomField>
    <fullName>Payment_Status__c</fullName>
    <label>Payment Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Not Initiated</fullName>
            </value>
            <value>
                <fullName>Payment Pending</fullName>
            </value>
            <value>
                <fullName>Payment Success</fullName>
            </value>
            <value>
                <fullName>Refund Requested</fullName>
            </value>
            <value>
                <fullName>Await3D</fullName>
            </value>
            <value>
                <fullName>Captured</fullName>
            </value>
            <value>
                <fullName>Partially Paid</fullName>
            </value>
            <value>
                <fullName>Fully Paid</fullName>
            </value>
            <value>
                <fullName>Refund Cancelled</fullName>
            </value>
            <value>
                <fullName>Failed</fullName>
            </value>
            <value>
                <fullName>Reversed</fullName>
            </value>
            <value>
                <fullName>On Premise Requested</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/ET_Service_Request__c/recordTypes/Vehicle_Inspection.recordType-meta.xml
<RecordType>
    <fullName>Vehicle_Inspection</fullName>
    <active>true</active>
    <label>Vehicle Inspection</label>
</RecordType>

unpackaged/main/default/objects/ETI_Booking__c/ETI_Booking__c.object-meta.xml
<CustomObject>
    <label>Booking</label>
    <nameField>
        <displayFormat>B-{000000}</displayFormat>
        <label>Booking</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Bookings</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

unpackaged/main/default/objects/ETI_Booking__c/fields/Booking_Status__c.field-meta.xml
<CustomField>
    <fullName>Booking_Status__c</fullName>
    <label>Booking Status</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Draft</fullName>
            </value>
            <value>
                <fullName>Booked</fullName>
            </value>
            <value>
                <fullName>Inspection Completed</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
            <value>
                <fullName>Due for Retest</fullName>
            </value>
            <value>
                <fullName>Applied for Retest</fullName>
            </value>
            <value>
                <fullName>Confirmed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/ETI_Booking__c/fields/Chassis_No__c.field-meta.xml
<CustomField>
    <fullName>Chassis_No__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Chassis No</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/ETI_Booking__c/fields/Customer_Vehicle__c.field-meta.xml
<CustomField>
    <fullName>Customer_Vehicle__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Customer Vehicle</label>
    <referenceTo>ET_Customer_Vehicle__c</referenceTo>
    <relationshipLabel>Bookings</relationshipLabel>
    <relationshipName>Bookings</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/ETI_Booking__c/fields/ET_Location__c.field-meta.xml
<CustomField>
    <fullName>ET_Location__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Location</label>
    <referenceTo>ET_Location__c</referenceTo>
    <relationshipLabel>Bookings</relationshipLabel>
    <relationshipName>Bookings</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/ETI_Booking__c/fields/Payment_Status__c.field-meta.xml
<CustomField>
    <fullName>Payment_Status__c</fullName>
    <formula>Text(Service_Request__r.Payment_Status__c )</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Payment Status</label>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/ETI_Booking__c/fields/Selected_Services__c.field-meta.xml
<CustomField>
    <fullName>Selected_Services__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Selected Services</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

unpackaged/main/default/objects/ETI_Booking__c/fields/Service_Request__c.field-meta.xml
<CustomField>
    <fullName>Service_Request__c</fullName>
    <label>Service Request</label>
    <referenceTo>ET_Service_Request__c</referenceTo>
    <relationshipLabel>Bookings</relationshipLabel>
    <relationshipName>Bookings</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

unpackaged/main/default/objects/ETI_Booking__c/fields/Vehicle_Number__c.field-meta.xml
<CustomField>
    <fullName>Vehicle_Number__c</fullName>
    <formula>Customer_Vehicle__r.Plate_No__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Vehicle Number</label>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/ETI_Booking__c/recordTypes/External.recordType-meta.xml
<RecordType>
    <fullName>External</fullName>
    <active>true</active>
    <label>External</label>
</RecordType>

unpackaged/main/default/objects/ETI_Booking__c/recordTypes/Internal.recordType-meta.xml
<RecordType>
    <fullName>Internal</fullName>
    <active>true</active>
    <label>Internal</label>
</RecordType>

unpackaged/main/default/objects/ETI_Service_Line_Item__c/ETI_Service_Line_Item__c.object-meta.xml
<CustomObject>
    <label>Booking Line Item</label>
    <nameField>
        <displayFormat>SVC-{00000}</displayFormat>
        <label>Service Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Booking Line Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

unpackaged/main/default/objects/ETI_Service_Line_Item__c/fields/Booking__c.field-meta.xml
<CustomField>
    <fullName>Booking__c</fullName>
    <label>Booking</label>
    <referenceTo>ETI_Booking__c</referenceTo>
    <relationshipLabel>Booking Line Items</relationshipLabel>
    <relationshipName>Services</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

unpackaged/main/default/objects/ETI_Service_Line_Item__c/fields/Chassis_No__c.field-meta.xml
<CustomField>
    <fullName>Chassis_No__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Chassis No</label>
    <length>150</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/ETI_Service_Line_Item__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <defaultValue>&quot;Active&quot;</defaultValue>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Active</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Invoice__c/Invoice__c.object-meta.xml
<CustomObject>
    <label>Invoice</label>
    <nameField>
        <displayFormat>INV-{000000}</displayFormat>
        <label>Invoice No</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Invoices</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Invoice__c/fields/Customer__c.field-meta.xml
<CustomField>
    <fullName>Customer__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Customer</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Invoices</relationshipLabel>
    <relationshipName>Invoices</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Invoice__c/fields/Customer_Number__c.field-meta.xml
<CustomField>
    <fullName>Customer_Number__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Customer Number</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Invoice__c/fields/ETST_Active__c.field-meta.xml
<CustomField>
    <fullName>ETST_Active__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Active</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/objects/Invoice__c/fields/FromDate__c.field-meta.xml
<CustomField>
    <fullName>FromDate__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>FromDate</label>
    <type>DateTime</type>
</CustomField>

unpackaged/main/default/objects/Invoice__c/fields/Payment_Status__c.field-meta.xml
<CustomField>
    <fullName>Payment_Status__c</fullName>
    <label>Payment Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Paid</fullName>
            </value>
            <value>
                <fullName>Partly Paid</fullName>
            </value>
            <value>
                <fullName>Not Paid</fullName>
            </value>
            <value>
                <fullName>Captured</fullName>
                <label>Payment Success</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Invoice__c/fields/Service_Request__c.field-meta.xml
<CustomField>
    <fullName>Service_Request__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Service Request</label>
    <referenceTo>ET_Service_Request__c</referenceTo>
    <relationshipLabel>Invoices</relationshipLabel>
    <relationshipName>Invoices</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Invoice__c/fields/Total_Inv_Amount__c.field-meta.xml
<CustomField>
    <fullName>Total_Inv_Amount__c</fullName>
    <label>Total Inv Amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

unpackaged/main/default/objects/Invoice__c/recordTypes/Vehicle_Inspection.recordType-meta.xml
<RecordType>
    <fullName>Vehicle_Inspection</fullName>
    <active>true</active>
    <label>Vehicle Inspection</label>
</RecordType>

unpackaged/main/default/classes/ETI_ServiceRequestHandlerTest.cls
@IsTest
public class ETI_ServiceRequestHandlerTest {
    @isTest
    public static void testmethodInspection1(){
        ETI_TestUtilityClass.testUserCreation();
        System.runAs(ETI_TestUtilityClass.objUser){
            ETI_TestUtilityClass.testAccountCreation();
            ETI_TestUtilityClass.testCustomerVehicle();
            ETI_TestUtilityClass.testServiceRequest();
            ETI_TestUtilityClass.testBookings();
        }
        Test.startTest();
            Id bkngExtRecordTypeId = Schema.SObjectType.ETI_Booking__c.getRecordTypeInfosByDeveloperName().get('External').getRecordTypeId();
            ETI_TestUtilityClass.bookingList[0].recordTypeId =bkngExtRecordTypeId;
            update ETI_TestUtilityClass.bookingList[0];
            ETI_TestUtilityClass.objServiceReq.Payment_Status__c ='Payment Success';
            update ETI_TestUtilityClass.objServiceReq;
            ET_Location__c location=new ET_Location__c(Name='Al Ain Inspection Centre',Status__c='Active',Location_Code__c='04023');
            insert location;
            ETI_TestUtilityClass.bookingList[0].ET_Location__c=location.Id;
            update ETI_TestUtilityClass.bookingList[0];
            ETI_TestUtilityClass.objServiceReq.Payment_Status__c =system.label.ETI_ServiceRequest_Payment_Status;
            update ETI_TestUtilityClass.objServiceReq;
        
        Test.stopTest();
    }
   
    @isTest
    public static void testmethodInspection2(){
        Id recordTypeId = Schema.SObjectType.ET_Service_Request__c.getRecordTypeInfosByDeveloperName().get('Vehicle_Inspection').getRecordTypeId();
        ETI_TestUtilityClass.testUserCreation();
        ETI_TestUtilityClass.testAccountCreation();
        ETI_TestUtilityClass.testCustomerVehicle();
        ETI_TestUtilityClass.testServiceRequest();
        Id invRecordTypeId = Schema.SObjectType.Invoice__c.getRecordTypeInfosByDeveloperName().get('Vehicle_Inspection').getRecordTypeId();
        Invoice__c objInvoice1 = new Invoice__c(recordTypeId=invRecordTypeId,fromDate__c=Date.today(),Service_Request__c=ETI_TestUtilityClass.objServiceReq.Id,
                                    Customer__c=ETI_TestUtilityClass.objServiceReq.ET_Account__c,Total_Inv_Amount__c=100,
                                    Customer_Number__c=ETI_TestUtilityClass.objServiceReq.ET_Account__r.PersonMobilePhone,Payment_Status__c=ETI_TestUtilityClass.objServiceReq.Payment_Status__c,ETST_Active__c=true);
        insert objInvoice1;
        system.debug('Invoices>> '+objInvoice1);
        //ETI_TestUtilityClass.tesInvoice();
        ETI_TestUtilityClass.testBookings();
        ETI_TestUtilityClass.testVehicleService();
        ETI_TestUtilityClass.testBookingItems();
        Profile p = [SELECT Id FROM Profile WHERE Name='System Administrator']; 
        User objUser1 = new User(Alias = 'standt', Email='standarduser1@sm.com', 
                            EmailEncodingKey='UTF-8', isActive = true, LastName='Testing', LanguageLocaleKey='en_US', 
                            LocaleSidKey='en_US', ProfileId = p.Id, 
                            TimeZoneSidKey='America/Los_Angeles', UserName='standarduser1@sm.com');
        insert objUser1;
        EmailTemplate objTemplate = new EmailTemplate();
        System.runAs(objUser1){
            String Sbjct='{!ETI_Booking__c.Vehicle_Number__c}';
            string Bodyvar= '{!emailContent}';
            objTemplate = new EmailTemplate(developerName = 'Booking_Confirmation', Subject=Sbjct,HtmlValue=Bodyvar,Body = Bodyvar,FolderId = objUser1.Id, TemplateType= 'text', Name = 'test');
            insert objTemplate;
        }
        Test.startTest();
        ETI_ServiceRequestHandler.sendEmailNotification(new Set<Id> {ETI_TestUtilityClass.objServiceReq.Id});
        
        //B2C Receipt
        ET_Service_Request__c serviceReq1= new ET_Service_Request__c(Payment_Status__c = 'Not Initiated',RecordTypeId = recordTypeId,ET_Account__c = ETI_TestUtilityClass.objAccount.id,
                                                                    ETI_Payment_Type__c='Online');
        insert serviceReq1;
        Id bkngIntRecordTypeId = Schema.SObjectType.ETI_Booking__c.getRecordTypeInfosByDeveloperName().get('Internal').getRecordTypeId();
        ETI_Booking__c booking=new ETI_Booking__c(Customer_Vehicle__c = ETI_TestUtilityClass.objVehicle.id,Booking_Status__c = 'Booked',Service_Request__c = serviceReq1.id,
                                           Selected_Services__c = 'Test',Chassis_No__c = 'D032B5GC000790',Test_Result__c = 'Pass',recordTypeId=bkngIntRecordTypeId,
                                           User__c = ETI_TestUtilityClass.objAccount.id,Is_booking_Confirmed__c = true,Service_Type__c ='Police Inspection',Booking_Date__c= date.today()-2);
        insert booking;
        ETI_Service_Line_Item__c item=new ETI_Service_Line_Item__c(Service_Name__c = 'SLA',Test_Result__c = 'Pass',Booking__c = ETI_TestUtilityClass.bookingList[0].Id,
                                                                Service__c = ETI_TestUtilityClass.objVehService.Id,Description__c= 'test link result',Total_Fee__c=100);
        insert item;
        ETI_ServiceRequestHandler.sendEmailNotification(new Set<Id> {ETI_TestUtilityClass.objServiceReq.Id,serviceReq1.Id});
        
        //B2B EmailNotification
        id B2BRecordtypeId = Schema.getGlobalDescribe().get('Account').getDescribe().getRecordTypeInfosByDeveloperName().get(Label.ETI_Business_B2B_Inspection).getRecordTypeId();
        Id p1 = [select id from profile where name='OneET Business Partner Login User'].id;
        String Sbjct='{!ETI_Booking__c.Vehicle_Number__c}';
        string Bodyvar= '{!emailContent}';
        EmailTemplate objTemplate1 = new EmailTemplate();
        System.runAs(ETI_TestUtilityClass.objUser){
            objTemplate1 = new EmailTemplate(developerName = 'Booking_Confirmation', Subject=Sbjct,HtmlValue=Bodyvar,Body = Bodyvar,FolderId = ETI_TestUtilityClass.objUser.Id, TemplateType= 'text', Name = 'test');
            insert objTemplate1;
        }
        Account acc = new Account(name ='noor test1',RecordTypeId=B2BRecordtypeId,ETI_Emirates__c='Abu Dhabi',ETSALES_Email__c = 'testAcc1@gmail.com') ;
        insert acc; 
        Contact con = new Contact(LastName ='testCon',AccountId = acc.Id,email='test123@sm1.com');
        insert con;  
        User user = new User(alias = 'test123', email='test123@sm1.com',
                emailencodingkey='UTF-8', lastname='Testing', languagelocalekey='en_US',
                localesidkey='en_US', profileid = p1, country='United States',IsActive =true,
                ContactId = con.Id,
                timezonesidkey='America/Los_Angeles', username='test123@sm1.com');
       
        insert user;
        system.runAs(user) {
            ET_Service_Request__c serviceReq= new ET_Service_Request__c(Payment_Status__c = 'Not Initiated',RecordTypeId = recordTypeId,ET_Account__c = acc.id,
                                                                    ETI_Payment_Type__c='Online');
            insert serviceReq;
            Invoice__c objInvoice2 = new Invoice__c(recordTypeId=invRecordTypeId,fromDate__c=Date.today(),Service_Request__c=serviceReq.Id,
                                        Customer__c=serviceReq.ET_Account__c,Total_Inv_Amount__c=100,Payment_Status__c=serviceReq.Payment_Status__c,ETST_Active__c=true);
            insert objInvoice2;
            system.debug('Invoices>> '+objInvoice2);
            ETI_ServiceRequestHandler.sendEmailNotification(new Set<Id> {serviceReq.Id});
            
            //B2B Receipt
            ET_Customer_Vehicle__c objVehicle = new ET_Customer_Vehicle__c(OwnerId = user.Id,Chassis_No__c = 'D032B5GC000790',Plate_No__c = '53215',
                                                status__c = 'Active',Registration_Type__c ='Registered');
            insert objVehicle;
            ET_Service_Request__c serviceReq2= new ET_Service_Request__c(Payment_Status__c = 'Not Initiated',RecordTypeId = recordTypeId,ET_Account__c = acc.id,
                                                                        ETI_Payment_Type__c='Online');
            insert serviceReq2;
            ETI_Booking__c booking1=new ETI_Booking__c(Customer_Vehicle__c = objVehicle.id,Booking_Status__c = 'Booked',Service_Request__c = serviceReq2.id,
                                               Selected_Services__c = 'Test',Chassis_No__c = 'D032B5GC000790',Test_Result__c = 'Pass',recordTypeId=bkngIntRecordTypeId,
                                               User__c = acc.id,Is_booking_Confirmed__c = true,Service_Type__c ='Police Inspection',Booking_Date__c= date.today()-2);
            insert booking1;
            ETI_Service_Line_Item__c item1=new ETI_Service_Line_Item__c(Service_Name__c = 'SLA',Test_Result__c = 'Pass',Booking__c = booking1.Id,
                                                                    Service__c = ETI_TestUtilityClass.objVehService.Id,Description__c= 'test link result',Total_Fee__c=100);
            insert item1;
            ETI_ServiceRequestHandler.sendEmailNotification(new Set<Id> {serviceReq.Id,serviceReq2.Id});

        }
        Test.stopTest();
       
    }
    
    
}