unpackaged/main/default/objects/ET_Receipt__c/ET_Receipt__c.object-meta.xml
<CustomObject>
    <label>Receipt</label>
    <nameField>
        <displayFormat>R-{000000}</displayFormat>
        <label>Receipt Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Receipts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/ET_Receipt__c/fields/ET_Amount__c.field-meta.xml
<CustomField>
    <fullName>ET_Amount__c</fullName>
    <label>Amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

unpackaged/main/default/objects/ET_Receipt__c/fields/ET_Service_Request__c.field-meta.xml
<CustomField>
    <fullName>ET_Service_Request__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Service Request</label>
    <referenceTo>ET_Service_Request__c</referenceTo>
    <relationshipLabel>Receipts</relationshipLabel>
    <relationshipName>Customer_Receipts</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/ET_Receipt__c/recordTypes/ET_Car_Services.recordType-meta.xml
<RecordType>
    <fullName>ET_Car_Services</fullName>
    <active>true</active>
    <label>ET Car Services</label>
</RecordType>

unpackaged/main/default/objects/ET_Service_Request__c/ET_Service_Request__c.object-meta.xml
<CustomObject>
    <label>Service Request</label>
    <nameField>
        <displayFormat>SR-{000000}</displayFormat>
        <label>Service Request Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Service Requests</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

unpackaged/main/default/objects/ET_Service_Request__c/fields/ETC_Payment_Status__c.field-meta.xml
<CustomField>
    <fullName>ETC_Payment_Status__c</fullName>
    <label>Payment Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Not Initiated</fullName>
                <default>true</default>
                <label>Not Initiated</label>
            </value>
            <value>
                <fullName>Await3D</fullName>
            </value>
            <value>
                <fullName>Captured</fullName>
            </value>
            <value>
                <fullName>Partially Paid</fullName>
            </value>
            <value>
                <fullName>Payment Success</fullName>
            </value>
            <value>
                <fullName>Refund Requested</fullName>
            </value>
            <value>
                <fullName>Refund Cancelled</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
            <value>
                <fullName>Failed</fullName>
            </value>
            <value>
                <fullName>Reversed</fullName>
            </value>
            <value>
                <fullName>On Premise Requested</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/ET_Service_Request__c/fields/ETC_Send_Payment_Link__c.field-meta.xml
<CustomField>
    <fullName>ETC_Send_Payment_Link__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Send Payment Link</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/objects/ET_Service_Request__c/fields/ETST_Service_Type__c.field-meta.xml
<CustomField>
    <fullName>ETST_Service_Type__c</fullName>
    <label>Service Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Yearly</fullName>
            </value>
            <value>
                <fullName>Half Yearly</fullName>
            </value>
            <value>
                <fullName>Quarterly</fullName>
            </value>
            <value>
                <fullName>Monthly</fullName>
            </value>
            <value>
                <fullName>On-demand</fullName>
            </value>
            <value>
                <fullName>Select Dates</fullName>
            </value>
            <value>
                <fullName>One Way</fullName>
            </value>
            <value>
                <fullName>Hourly</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/ETCAR_Car__c/ETCAR_Car__c.object-meta.xml
<CustomObject>
    <label>Car</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Car Model</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Cars</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/ETCAR_Service_Request_Line_Item__c/ETCAR_Service_Request_Line_Item__c.object-meta.xml
<CustomObject>
    <description>To Capture Selected Car Details</description>
    <label>Vehicle Booking</label>
    <nameField>
        <displayFormat>Item-{0000}</displayFormat>
        <label>Service Request Line Item Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Vehicle Bookings</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

unpackaged/main/default/objects/ETCAR_Service_Request_Line_Item__c/fields/ETC_Duration__c.field-meta.xml
<CustomField>
    <fullName>ETC_Duration__c</fullName>
    <label>Order Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>3 Hours</fullName>
            </value>
            <value>
                <fullName>5 Hours</fullName>
            </value>
            <value>
                <fullName>8 Hours</fullName>
            </value>
            <value>
                <fullName>10 Hours</fullName>
            </value>
            <value>
                <fullName>Fixed Trip</fullName>
            </value>
            <value>
                <fullName>Transfer</fullName>
            </value>
            <value>
                <fullName>Package : 10 Hours</fullName>
                <isActive>false</isActive>
                <label>Package : 10 Hours</label>
            </value>
            <value>
                <fullName>Package : 3 Hours</fullName>
                <isActive>false</isActive>
                <label>Package : 3 Hours</label>
            </value>
            <value>
                <fullName>Package : 5 Hours</fullName>
                <isActive>false</isActive>
                <label>Package : 5 Hours</label>
            </value>
            <value>
                <fullName>Package : 8 Hours</fullName>
                <isActive>false</isActive>
                <label>Package : 8 Hours</label>
            </value>
            <value>
                <fullName>Zone Fare : Fixed Trip</fullName>
                <isActive>false</isActive>
                <label>Zone Fare : Fixed Trip</label>
            </value>
            <value>
                <fullName>Zone Fare : Transfer</fullName>
                <isActive>false</isActive>
                <label>Zone Fare : Transfer</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/ETCAR_Service_Request_Line_Item__c/fields/ETST_Service_Type__c.field-meta.xml
<CustomField>
    <fullName>ETST_Service_Type__c</fullName>
    <label>Service Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>One Way</fullName>
            </value>
            <value>
                <fullName>Hourly</fullName>
            </value>
            <value>
                <fullName>Rental</fullName>
            </value>
            <value>
                <fullName>Half Yearly</fullName>
                <isActive>false</isActive>
                <label>Half Yearly</label>
            </value>
            <value>
                <fullName>Monthly</fullName>
                <isActive>false</isActive>
                <label>Monthly</label>
            </value>
            <value>
                <fullName>On-Demand</fullName>
                <isActive>false</isActive>
                <label>On-Demand</label>
            </value>
            <value>
                <fullName>Quarterly</fullName>
                <isActive>false</isActive>
                <label>Quarterly</label>
            </value>
            <value>
                <fullName>Select Dates</fullName>
                <isActive>false</isActive>
                <label>Select Dates</label>
            </value>
            <value>
                <fullName>Yearly</fullName>
                <isActive>false</isActive>
                <label>Yearly</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/classes/ETC_ServiceRequestHandler_Test.cls
@isTest
public class ETC_ServiceRequestHandler_Test {
    
    @isTest public static void serviceReqTest(){
         List<ET_Service_Request__c> reqList = ETC_TestDataFactory.createServiceRequests(3);
        insert reqList;
        List<ETCAR_Car__c> carsList = ETC_TestDataFactory.createCars(3, 'SUV');
        insert carsList;
        List<ETCAR_Service_Request_Line_Item__c> vBkngList = ETC_TestDataFactory.createVehicleBookings(3, reqList[1].Id,carsList[0].Id);
        vBkngList[0].ETST_Service_Type__c = 'One Way';
        vBkngList[1].ETST_Service_Type__c = 'Hourly';
        vBkngList[1].ETC_Duration__c = '3 Hours';
        insert vBkngList;
        Test.startTest();
        reqList[0].ETC_Send_Payment_Link__c = true;
        update reqList[0];
        reqList[1].ETC_Payment_Status__c = 'Payment Success';
        update reqList[1];
        reqList[2].ETC_Payment_Status__c = 'Refund Requested';
        update reqList[2];
        ET_Receipt__c recpt = new ET_Receipt__c();
        recpt.RecordTypeId = Schema.SObjectType.ET_Receipt__c.getRecordTypeInfosByDeveloperName().get('ET_Car_Services').getRecordTypeId(); 
        recpt.ET_Service_Request__c = reqList[0].id;
        recpt.ET_Amount__c =100.0;
        insert recpt;
        
        ETC_ServiceRequestHandler.updatePostServicePayment(reqList[0].id);
        Test.stopTest();
       
        
    }
}