unpackaged/main/default/objects/ET_Receipt__c/ET_Receipt__c.object-meta.xml
<CustomObject>
    <label>Receipt</label>
    <nameField>
        <displayFormat>R-{000000}</displayFormat>
        <label>Receipt Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Receipts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/ET_Receipt__c/fields/ET_Service_Request__c.field-meta.xml
<CustomField>
    <fullName>ET_Service_Request__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Service Request</label>
    <referenceTo>ET_Service_Request__c</referenceTo>
    <relationshipLabel>Receipts</relationshipLabel>
    <relationshipName>Customer_Receipts</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/ET_Service_Request__c/ET_Service_Request__c.object-meta.xml
<CustomObject>
    <label>Service Request</label>
    <nameField>
        <displayFormat>SR-{000000}</displayFormat>
        <label>Service Request Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Service Requests</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

unpackaged/main/default/classes/ETST_ReceiptPageControllerTest.cls
/***
Class       : ETST_ReceiptPageontrollerTest
Author      : Sreelakshmi SK
CreatedDate : 19.05.2023
Description : 
***/
@IsTest
public class ETST_ReceiptPageControllerTest {
    @IsTest
    static void testLoadInvoices() {
        // Create test data
        ET_Service_Request__c serviceRequest = new ET_Service_Request__c();
        insert serviceRequest;
        
        ET_Receipt__c receipt = new ET_Receipt__c(
            ET_Service_Request__c = serviceRequest.Id
        );
        insert receipt;
        
        // Create an instance of the controller
        ETST_ReceiptPageController controller = new ETST_ReceiptPageController();
        controller.recordId = serviceRequest.Id;
        
        // Call the loadInvoices method
        Test.startTest();
        controller.loadInvoices();
        Test.stopTest();
        
        // Assert the results
        List<ET_Receipt__c> receiptList = controller.receiptList;
    }
    
    @IsTest
    static void testConstructorWithNoReceipts() {
        // Create test data
        ET_Service_Request__c serviceRequest = new ET_Service_Request__c();
        insert serviceRequest;
        
        // Create an instance of the controller
        ETST_ReceiptPageController controller = new ETST_ReceiptPageController();
        controller.recordId = serviceRequest.Id;
        
        // Assert that receiptList is empty
        List<ET_Receipt__c> receiptList = controller.receiptList;
        System.assertEquals(0, receiptList.size());
    }
}