unpackaged/main/default/objects/ET_Receipt__c/ET_Receipt__c.object-meta.xml
<CustomObject>
    <label>Receipt</label>
    <nameField>
        <displayFormat>R-{000000}</displayFormat>
        <label>Receipt Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Receipts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/ET_Receipt__c/fields/ET_Amount__c.field-meta.xml
<CustomField>
    <fullName>ET_Amount__c</fullName>
    <label>Amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

unpackaged/main/default/objects/ET_Receipt__c/fields/ET_Service_Request__c.field-meta.xml
<CustomField>
    <fullName>ET_Service_Request__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Service Request</label>
    <referenceTo>ET_Service_Request__c</referenceTo>
    <relationshipLabel>Receipts</relationshipLabel>
    <relationshipName>Customer_Receipts</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/ET_Receipt__c/fields/ETST_Student_Name__c.field-meta.xml
<CustomField>
    <fullName>ETST_Student_Name__c</fullName>
    <formula>ET_Service_Request__r.ETST_Student_Name__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Student Name</label>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/ET_Receipt__c/fields/Payment_Mode__c.field-meta.xml
<CustomField>
    <fullName>Payment_Mode__c</fullName>
    <label>Payment Mode</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Online</fullName>
            </value>
            <value>
                <fullName>Cheque</fullName>
            </value>
            <value>
                <fullName>Cash</fullName>
            </value>
            <value>
                <fullName>Bank Transfer/Cash Deposit</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/ET_Service_Request__c/ET_Service_Request__c.object-meta.xml
<CustomObject>
    <label>Service Request</label>
    <nameField>
        <displayFormat>SR-{000000}</displayFormat>
        <label>Service Request Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Service Requests</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

unpackaged/main/default/objects/ET_Service_Request__c/fields/ETST_Drop_Off_To__c.field-meta.xml
<CustomField>
    <fullName>ETST_Drop_Off_To__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Drop-Off To</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/ET_Service_Request__c/fields/ETST_Paid_By__c.field-meta.xml
<CustomField>
    <fullName>ETST_Paid_By__c</fullName>
    <label>Paid By</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Self</fullName>
                <default>true</default>
                <label>Self</label>
            </value>
            <value>
                <fullName>Employer</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/ET_Service_Request__c/fields/ETST_Pick_Up_End_Date__c.field-meta.xml
<CustomField>
    <fullName>ETST_Pick_Up_End_Date__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Pickup End Date</label>
    <type>Date</type>
</CustomField>

unpackaged/main/default/objects/ET_Service_Request__c/fields/ETST_Pick_Up_Start_Date__c.field-meta.xml
<CustomField>
    <fullName>ETST_Pick_Up_Start_Date__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Request Date</label>
    <type>Date</type>
</CustomField>

unpackaged/main/default/objects/ET_Service_Request__c/fields/ETST_Service_Type__c.field-meta.xml
<CustomField>
    <fullName>ETST_Service_Type__c</fullName>
    <label>Service Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Yearly</fullName>
            </value>
            <value>
                <fullName>Half Yearly</fullName>
            </value>
            <value>
                <fullName>Quarterly</fullName>
            </value>
            <value>
                <fullName>Monthly</fullName>
            </value>
            <value>
                <fullName>On-demand</fullName>
            </value>
            <value>
                <fullName>Select Dates</fullName>
            </value>
            <value>
                <fullName>One Way</fullName>
            </value>
            <value>
                <fullName>Hourly</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/ET_Service_Request__c/fields/ETST_Student__c.field-meta.xml
<CustomField>
    <fullName>ETST_Student__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Student</label>
    <referenceTo>ETST_Student__c</referenceTo>
    <relationshipName>ETST_Transport_Requests</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/ET_Service_Request__c/fields/ETST_Student_Name__c.field-meta.xml
<CustomField>
    <fullName>ETST_Student_Name__c</fullName>
    <formula>IF(ETST_Student__c !=null, (ETST_Student__r.ETST_First_Name__c+&#39; &#39;+ETST_Student__r.Name), &#39;&#39;)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Student Name</label>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/ET_Service_Request__c/fields/ETST_Transport_Type__c.field-meta.xml
<CustomField>
    <fullName>ETST_Transport_Type__c</fullName>
    <label>Transport Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Two Way</fullName>
            </value>
            <value>
                <fullName>Pick up only</fullName>
            </value>
            <value>
                <fullName>Drop off only</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/ETST_Student__c/ETST_Student__c.object-meta.xml
<CustomObject>
    <label>Student</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Last Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Students</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

unpackaged/main/default/objects/ETST_Student__c/fields/ETST_Account_Name__c.field-meta.xml
<CustomField>
    <fullName>ETST_Account_Name__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Parent</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Account.RecordTypeId</field>
            <operation>equals</operation>
            <value>Person (B2C)</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Students</relationshipLabel>
    <relationshipName>Students</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/ETST_Student__c/fields/ETST_School__c.field-meta.xml
<CustomField>
    <fullName>ETST_School__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>School</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Account.RecordTypeId</field>
            <operation>equals</operation>
            <value>Business (B2B) - School</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Students (School)</relationshipLabel>
    <relationshipName>ETST_Students</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/classes/ETST_ReceiptPageController.cls
public class ETST_ReceiptPageController {
    public ET_Service_Request__c serviceRequest {get;set;}
    public List<ET_Receipt__c> receiptList {get;set;}
    public string recordId;
    
    public ETST_ReceiptPageController(){
        recordId = Apexpages.currentPage().getParameters().get('id');
        system.debug('recordId-->'+recordId);
        receiptList = new List<ET_Receipt__c>();
        loadInvoices();
        if(receiptList.size()==0){
            
        } 
    }
    public void loadInvoices(){
        // Changed where condition to Id=:recordId --- Sreelakshmi SK 15/5/23
        receiptList = [Select Id,Name,CreatedDate,ET_Amount__c,Payment_Mode__c,ET_Service_Request__r.ETST_Student_Name__c,ET_Service_Request__r.ETST_Student__r.ETST_School__r.Name,ET_Service_Request__r.ETST_Service_Type__c,ET_Service_Request__r.ETST_Transport_Type__c,
                       ET_Service_Request__r.ETST_Pick_Up_From__c,ET_Service_Request__r.ETST_Drop_Off_To__c,ET_Service_Request__r.ETST_Pick_Up_Start_Date__c,ET_Service_Request__r.ETST_Pick_Up_End_Date__c,
                       ET_Service_Request__r.ETST_Paid_By__c,ET_Service_Request__r.ETST_Student__r.ETST_Account_Name__c FROM ET_Receipt__c WHERE Id=:recordId /*ET_Service_Request__c=:recordId*/ limit 1];
    } 
    
}