unpackaged/main/default/objects/ETSALES_Check_List_Lines__c/ETSALES_Check_List_Lines__c.object-meta.xml
<CustomObject>
    <label>Check List Lines</label>
    <nameField>
        <displayFormat>CH-{0000}</displayFormat>
        <label>Check List Lines Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Check List Lines</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/ETSALES_Check_List_Lines__c/fields/ETSALES_AddChecklist__c.field-meta.xml
<CustomField>
    <fullName>ETSALES_AddChecklist__c</fullName>
    <defaultValue>false</defaultValue>
    <description>to add the checklist through custom UI</description>
    <label>AddChecklist</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/objects/ETSALES_Check_List_Lines__c/fields/ETSALES_Assign_To__c.field-meta.xml
<CustomField>
    <fullName>ETSALES_Assign_To__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Assign To</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Check_List_Lines</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/ETSALES_Check_List_Lines__c/fields/ETSALES_Checklist__c.field-meta.xml
<CustomField>
    <fullName>ETSALES_Checklist__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Checklist</label>
    <referenceTo>ETSALES_checklist__c</referenceTo>
    <relationshipLabel>Check List Lines</relationshipLabel>
    <relationshipName>Check_List_Lines</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/ETSALES_Check_List_Lines__c/fields/ETSALES_Required__c.field-meta.xml
<CustomField>
    <fullName>ETSALES_Required__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Required</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/objects/ETSALES_Check_List_Lines__c/fields/ETSALES_Status__c.field-meta.xml
<CustomField>
    <fullName>ETSALES_Status__c</fullName>
    <label>Status</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Available</fullName>
                <default>true</default>
                <label>Available</label>
            </value>
            <value>
                <fullName>Requested</fullName>
            </value>
            <value>
                <fullName>None</fullName>
                <isActive>false</isActive>
                <label>None</label>
            </value>
            <value>
                <fullName>Unavailable</fullName>
                <isActive>false</isActive>
                <label>Unavailable</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/ETSALES_Check_List_Lines__c/fields/ETSALES_Tender__c.field-meta.xml
<CustomField>
    <fullName>ETSALES_Tender__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Tender</label>
    <referenceTo>ETSALES_Tender__c</referenceTo>
    <relationshipLabel>Check List Lines</relationshipLabel>
    <relationshipName>Check_List_Lines</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/ETSALES_checklist__c/ETSALES_checklist__c.object-meta.xml
<CustomObject>
    <label>Checklist</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Checklist Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Checklists</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/ETSALES_checklist__c/fields/ETSALES_Active__c.field-meta.xml
<CustomField>
    <fullName>ETSALES_Active__c</fullName>
    <defaultValue>true</defaultValue>
    <label>Active</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/objects/ETSALES_Tender__c/ETSALES_Tender__c.object-meta.xml
<CustomObject>
    <description>Custom Object Created for storing ETSALES Tenders.</description>
    <label>Tender</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Tender Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Tenders</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

unpackaged/main/default/classes/ETSALES_TenderCheckListController.cls
public class ETSALES_TenderCheckListController {
    @auraEnabled
    public List<User> userList {get;set;}
    @auraEnabled
    public List<String> statusList {get;set;}
    @auraEnabled
    public List<ETSALES_checklist__c> checklist{get;set;}
    
    @auraEnabled
    public static ETSALES_TenderCheckListController handleCheckList(String tenderId){
        ETSALES_TenderCheckListController lexObj = new ETSALES_TenderCheckListController();
        List<ETSALES_Tender__c> currentTender = [SELECT Id, Name, 
                                                 (SELECT Id,ETSALES_Tender__c,ETSALES_Checklist__c  FROM Check_List_Lines__r WHERE ETSALES_Tender__c =:tenderId)
                                                 FROM ETSALES_Tender__c WHERE Id =:tenderId];
        Set<Id> addedCheckListSet = new Set<Id>();
        for(ETSALES_Tender__c tenderItem : currentTender){
            for(ETSALES_Check_List_Lines__c lineItem : tenderItem.Check_List_Lines__r){
                addedCheckListSet.add(lineItem.ETSALES_Checklist__c);
            }
        }if(!addedCheckListSet.isEmpty()){
            lexObj.checklist =  [SELECT Id, Name,ETSALES_Active__c FROM ETSALES_checklist__c where ETSALES_Active__c = True AND Id Not IN: addedCheckListSet];
        }else{
            lexObj.checklist =  [SELECT Id, Name,ETSALES_Active__c FROM ETSALES_checklist__c where ETSALES_Active__c = True];
        }
        
        // check if existing checkList lines are there in tender and if there - show them to user for updating
        // if no existing CheckList Lines - give user option to add new Details
        List<User> userList = [SELECT Id,Name from User WHERE isActive = TRUE];
        lexObj.userList = userList;
        
        Schema.DescribeFieldResult statusVal = ETSALES_Check_List_Lines__c.ETSALES_Status__c.getDescribe();
        List<Schema.PicklistEntry> ple = statusVal.getPicklistValues();
        List<String> tempList = new List<String>();
        for( Schema.PicklistEntry pickListVal : ple){
            
            tempList.add(pickListVal.getLabel());
            
        }
        lexObj.statusList = tempList;
        
        system.debug(JSON.serializePretty(lexObj));
        return lexObj;
        
        
    }
    
    @auraEnabled
    public static String saveCheckList(List<ETSALES_Check_List_Lines__c> checkListItems , String tenderId){
        String response;
        List<ETSALES_Check_List_Lines__c> lstCheckList = new List<ETSALES_Check_List_Lines__c> ();
        
        system.debug('=====checkListItems========='+checkListItems);
        if(!checkListItems.isEmpty()){
            for(ETSALES_Check_List_Lines__c newItem: checkListItems ){
                ETSALES_Check_List_Lines__c instanceItem = new ETSALES_Check_List_Lines__c();
                system.debug('---------------------for loop---------------------------------');
                instanceItem.ETSALES_Checklist__c= newItem.Id;
                instanceItem.ETSALES_Tender__c = tenderId;
                instanceItem.ETSALES_Assign_To__c = newItem.ETSALES_Assign_To__c;
                instanceItem.ETSALES_AddChecklist__c = newItem.ETSALES_AddChecklist__c;
                instanceItem.ETSALES_Required__c = newItem.ETSALES_Required__c;
                instanceItem.ETSALES_Status__c = newItem.ETSALES_Status__c;
                
                lstCheckList.add(instanceItem);
            }
        }
        
        try{
            system.debug('-------list to insert-------'+lstCheckList);
            insert lstCheckList;
            //throw new AuraHandledException('Error in Creating Check list for Tender: Duplicate Detected');
        }
        catch(exception e){
            system.debug('Error Message=>'+e.getMessage());
            String error = e.getMessage();
            if(error.contains('DUPLICATES_DETECTED')){
                system.debug('Duplicate Detected');
                throw new AuraHandledException('Error in Creating Check list for Tender: Duplicate Detected');
                
            }
            
        }
        return response = 'Success' ;
    } 
}