unpackaged/main/default/objects/ETSALES_Department__c/ETSALES_Department__c.object-meta.xml
<CustomObject>
    <label>GL Department</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>GL Department</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>GL Departments</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/ETSALES_Department__c/fields/Department_Code__c.field-meta.xml
<CustomField>
    <fullName>Department_Code__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Department Code</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/ETSALES_Location__c/ETSALES_Location__c.object-meta.xml
<CustomObject>
    <label>GL Location</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>GL Location</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>GL Locations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/ETSALES_Location__c/fields/Location_Code__c.field-meta.xml
<CustomField>
    <fullName>Location_Code__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Location Code</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/GL_Activity__c/GL_Activity__c.object-meta.xml
<CustomObject>
    <description>to have the oracle GL Activity in SF</description>
    <label>GL Activity</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>GL Activity</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>GL Activities</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/GL_Activity__c/fields/GL_Activity_Code__c.field-meta.xml
<CustomField>
    <fullName>GL_Activity_Code__c</fullName>
    <description>to capture the GL Activity Code</description>
    <encryptionScheme>None</encryptionScheme>
    <label>GL Activity Code</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/GL_Project__c/GL_Project__c.object-meta.xml
<CustomObject>
    <description>to create GL Project of Oracle</description>
    <label>GL Project</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>GL Project</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>GL Projects</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/GL_Project__c/fields/Project_Code__c.field-meta.xml
<CustomField>
    <fullName>Project_Code__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Project Code</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/User/fields/ETSALES_Location__c.field-meta.xml
<CustomField>
    <fullName>ETSALES_Location__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>GL Location</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/User/fields/GL_Activity_Code__c.field-meta.xml
<CustomField>
    <fullName>GL_Activity_Code__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>GL Activity Code</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/User/fields/GL_Department_Code__c.field-meta.xml
<CustomField>
    <fullName>GL_Department_Code__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>GL Department Code</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/User/fields/GL_Location_Code__c.field-meta.xml
<CustomField>
    <fullName>GL_Location_Code__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>GL Location Code</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/User/fields/GL_Project_Code__c.field-meta.xml
<CustomField>
    <fullName>GL_Project_Code__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>GL Project Code</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/User_GL_Mapping__c/User_GL_Mapping__c.object-meta.xml
<CustomObject>
    <description>to store the GL mapping and use it where ever rrequired</description>
    <label>User GL Mapping</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>User Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>User GL Mappings</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/User_GL_Mapping__c/fields/ETSALES_GL_Location__c.field-meta.xml
<CustomField>
    <fullName>ETSALES_GL_Location__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>GL Location</label>
    <referenceTo>ETSALES_Location__c</referenceTo>
    <relationshipLabel>User GL Mappings</relationshipLabel>
    <relationshipName>User_GL_Mappings</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/User_GL_Mapping__c/fields/GL_Activity__c.field-meta.xml
<CustomField>
    <fullName>GL_Activity__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>GL Activity</label>
    <referenceTo>GL_Activity__c</referenceTo>
    <relationshipLabel>User GL Mappings</relationshipLabel>
    <relationshipName>User_GL_Mappings</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/User_GL_Mapping__c/fields/GL_Department__c.field-meta.xml
<CustomField>
    <fullName>GL_Department__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>GL Department</label>
    <referenceTo>ETSALES_Department__c</referenceTo>
    <relationshipLabel>User GL Mappings</relationshipLabel>
    <relationshipName>User_GL_Mappings</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/User_GL_Mapping__c/fields/GL_Project__c.field-meta.xml
<CustomField>
    <fullName>GL_Project__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>GL Project</label>
    <referenceTo>GL_Project__c</referenceTo>
    <relationshipLabel>User GL Mappings</relationshipLabel>
    <relationshipName>User_GL_Mappings</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/User_GL_Mapping__c/fields/User__c.field-meta.xml
<CustomField>
    <fullName>User__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>User</label>
    <referenceTo>User</referenceTo>
    <relationshipName>User_GL_Mappings</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/classes/ETSALES_User_Trigger_Handler.cls
public class ETSALES_User_Trigger_Handler {
    

    @future
    public static void userMappingInsert(Set<Id> updateList){
        
        Map< String, GL_Activity__c> activityMap = new Map< String, GL_Activity__c>();
        Map< String, GL_Project__c> projectMap = new Map< String, GL_Project__c>();
        Map< String, ETSALES_Department__c> departmentMap = new Map< String, ETSALES_Department__c>();
        Map< String, ETSALES_Location__c> locationMap = new Map< String, ETSALES_Location__c>();
        
        // GL Activity
        for(GL_Activity__c activityItem : [SELECT Id,GL_Activity_Code__c,Name FROM GL_Activity__c]){
            activityMap.put(activityItem.GL_Activity_Code__c,activityItem);
        }
        // GL Project
        for(GL_Project__c projectItem : [SELECT Id,Project_Code__c,Name FROM GL_Project__c ]){
            projectMap.put(projectItem.Project_Code__c,projectItem);
        }
        // GL Department
        for(ETSALES_Department__c depItem : [SELECT Id,Department_Code__c,Name FROM ETSALES_Department__c]){
            departmentMap.put(depItem.Department_Code__c, depItem);
        }
        // GL Location
        for(ETSALES_Location__c locItem : [SELECT Id,Location_Code__c,Name FROM ETSALES_Location__c]){
            locationMap.put(locItem.Location_Code__c,locItem);
        }
        
        ETSALES_User_Trigger_Handler instance = new ETSALES_User_Trigger_Handler();
        
        List<User_GL_Mapping__c> glCodeList = new List<User_GL_Mapping__c>();
        
        for(User uItem : [SELECT Id, FirstName, LastName,GL_Activity_Code__c,GL_Department_Code__c,GL_Location_Code__c,GL_Project_Code__c,
                          Profile.UserLicense.Name FROM User where Id In:updateList]){
            if(uItem.Profile.UserLicense.Name == 'Salesforce'){
                
            User_GL_Mapping__c glMapping = new User_GL_Mapping__c();
            glMapping.User__c = uItem.Id;
            glMapping.Name = uItem.FirstName+ ' '+uItem.LastName;
            if(activityMap.containsKey(uItem.GL_Activity_Code__c)){
                
                glMapping.GL_Activity__c = activityMap.get(uItem.GL_Activity_Code__c).Id;
                system.debug('Activity Name----->'+activityMap.get(uItem.GL_Activity_Code__c).Name);
            }
            if(departmentMap.containsKey(uItem.GL_Department_Code__c)){
                
                glMapping.GL_Department__c = departmentMap.get(uItem.GL_Department_Code__c).Id;
                system.debug('Department Name----->'+departmentMap.get(uItem.GL_Department_Code__c).Name);
            }
            if(locationMap.containsKey(uItem.GL_Location_Code__c)){
                
                glMapping.ETSALES_GL_Location__c = locationMap.get(uItem.GL_Location_Code__c).Id;
                system.debug('Location Name----->'+locationMap.get(uItem.GL_Location_Code__c).Name);
            }
            if(projectMap.containsKey(uItem.GL_Project_Code__c)){
                
                glMapping.GL_Project__c = projectMap.get(uItem.GL_Project_Code__c).Id;
                system.debug('Project Name----->'+projectMap.get(uItem.GL_Project_Code__c).Name);
            }
            glCodeList.add(glMapping);
                          }
        }
        if(!glCodeList.isEmpty()){
            system.debug('Insertion Of GL Mapping------->'+glCodeList);
            insert glCodeList;
        }
    }
    public static void userActivityCodeUpdate(list<User> updateList, Map<Id,User> oldMap){
        system.debug('Activity Update---->'+updateList);
        List<User_GL_Mapping__c> mappingUpdate = new List<User_GL_Mapping__c>();
        Map< String, GL_Activity__c> activityMap = new Map< String, GL_Activity__c>();
        List<User_GL_Mapping__c> mappingRecList = [SELECT Id,Name,User__c,GL_Activity__c FROM User_GL_Mapping__c WHERE User__c IN: updateList ];
        // GL Activity
        for(GL_Activity__c activityItem : [SELECT Id,GL_Activity_Code__c FROM GL_Activity__c]){
            activityMap.put(activityItem.GL_Activity_Code__c,activityItem);
            
        }
        for(User uItem : updateList){
            if(uItem.GL_Activity_Code__c != OldMap.get(uItem.Id).GL_Activity_Code__c){
                for(User_GL_Mapping__c glMap : mappingRecList){
                    if(uItem.Id == glMap.User__c){
                        glMap.GL_Activity__c = activityMap.get(uItem.GL_Activity_Code__c).Id;
                        system.debug('glMap.GL_Activity__c'+uItem.GL_Activity_Code__c);
                        mappingUpdate.add(glMap);
                    }
                }
            }
            
            system.debug('Update List--------->'+mappingRecList);
            
        }
        if(!mappingUpdate.isEmpty()){
            update mappingUpdate;
        }
    }
    // Department update
    public static void userDeptCodeUpdate(list<User> updateList, Map<Id,User> oldMap){
        List<User_GL_Mapping__c> mappingUpdate = new List<User_GL_Mapping__c>();
        
        Map< String, ETSALES_Department__c> departmentMap = new Map< String, ETSALES_Department__c>();
        for(ETSALES_Department__c depItem : [SELECT Id,Department_Code__c FROM ETSALES_Department__c]){
            departmentMap.put(depItem.Department_Code__c, depItem);
            
        }
        List<User_GL_Mapping__c> mappingRecList = [SELECT Id,Name,User__c,GL_Department__c FROM User_GL_Mapping__c WHERE User__c IN: updateList ];
        
        for(User uItem : updateList){
            if(uItem.GL_Department_Code__c != oldMap.get(uItem.Id).GL_Department_Code__c){
                for(User_GL_Mapping__c glMap : mappingRecList){
                    if(uItem.Id == glMap.User__c){
                        glMap.GL_Department__c = departmentMap.get(uItem.GL_Department_Code__c).Id;
                        system.debug('glMap.GL_Department__c'+uItem.GL_Department_Code__c);
                        mappingUpdate.add(glMap);
                    }
                }
                
            }
            
        }
        if(!mappingUpdate.isEmpty()){
            update mappingUpdate;
        }
    }
    // Location update
    public static void userLocactionCodeUpdate(list<User> updateList,Map<Id,User> oldMap){
        List<User_GL_Mapping__c> mappingUpdate = new List<User_GL_Mapping__c>();
        Map< String, ETSALES_Location__c> locationMap = new Map< String, ETSALES_Location__c>();
        for(ETSALES_Location__c locItem : [SELECT Id,Location_Code__c FROM ETSALES_Location__c]){
            locationMap.put(locItem.Location_Code__c,locItem);
            
        }
        
        List<User_GL_Mapping__c> mappingRecList = [SELECT Id,Name,User__c,ETSALES_GL_Location__c FROM User_GL_Mapping__c WHERE User__c IN: updateList ];
        // GL Department
        for(User uItem : updateList){
            if(uItem.GL_Location_Code__c != OldMap.get(uItem.Id).GL_Location_Code__c){
                for(User_GL_Mapping__c glMap : mappingRecList){
                    if(uItem.Id == glMap.User__c){
                        glMap.ETSALES_GL_Location__c = locationMap.get(uItem.GL_Location_Code__c).Id;
                        system.debug('glMap.ETSALES_GL_Location__cc'+uItem.GL_Location_Code__c);
                        mappingUpdate.add(glMap);
                        
                    }
                }
            }
            
            
        }
        if(!mappingUpdate.isEmpty()){
            update mappingUpdate;
        }
    }
    // Project update
    public static void userProjectCodeUpdate(list<User> updateList, Map<Id,User> oldMap){
        List<User_GL_Mapping__c> mappingUpdate = new List<User_GL_Mapping__c>();
        Map< String, GL_Project__c> projectMap = new Map< String, GL_Project__c>();
        for(GL_Project__c projectItem : [SELECT Id,Project_Code__c,Name FROM GL_Project__c ]){
            projectMap.put(projectItem.Project_Code__c,projectItem);
            
        }
        List<User_GL_Mapping__c> mappingRecList = [SELECT Id,Name,User__c,GL_Project__c FROM User_GL_Mapping__c WHERE User__c IN: updateList ];
        // GL Department
        for(User uItem : updateList){
            if(uItem.GL_Project_Code__c != OldMap.get(uItem.Id).GL_Project_Code__c){
                for(User_GL_Mapping__c glMap : mappingRecList){
                    if(uItem.Id == glMap.User__c){
                        if(projectMap.containsKey(uItem.GL_Project_Code__c)){
                            glMap.GL_Project__c = projectMap.get(uItem.GL_Project_Code__c).Id;
                            system.debug('glMap.GL_Project__c'+uItem.GL_Project_Code__c);
                            mappingUpdate.add(glMap);
                        }
                    }
                }
            }    
        }
        if(!mappingUpdate.isEmpty()){
            update mappingUpdate;
        }
    }
}