unpackaged/main/default/objects/ETSALES_Department__c/ETSALES_Department__c.object-meta.xml
<CustomObject>
    <label>GL Department</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>GL Department</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>GL Departments</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/ETSALES_Department__c/fields/Department_Code__c.field-meta.xml
<CustomField>
    <fullName>Department_Code__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Department Code</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/ETSALES_Location__c/ETSALES_Location__c.object-meta.xml
<CustomObject>
    <label>GL Location</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>GL Location</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>GL Locations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/ETSALES_Location__c/fields/GL_Zone__c.field-meta.xml
<CustomField>
    <fullName>GL_Zone__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>GL Zone</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/ETSALES_Location__c/fields/Location_Code__c.field-meta.xml
<CustomField>
    <fullName>Location_Code__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Location Code</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/GL_Activity__c/GL_Activity__c.object-meta.xml
<CustomObject>
    <description>to have the oracle GL Activity in SF</description>
    <label>GL Activity</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>GL Activity</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>GL Activities</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/GL_Activity__c/fields/GL_Activity_Code__c.field-meta.xml
<CustomField>
    <fullName>GL_Activity_Code__c</fullName>
    <description>to capture the GL Activity Code</description>
    <encryptionScheme>None</encryptionScheme>
    <label>GL Activity Code</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/GL_Project__c/GL_Project__c.object-meta.xml
<CustomObject>
    <description>to create GL Project of Oracle</description>
    <label>GL Project</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>GL Project</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>GL Projects</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/GL_Project__c/fields/Project_Code__c.field-meta.xml
<CustomField>
    <fullName>Project_Code__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Project Code</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/GL_Zone__c/GL_Zone__c.object-meta.xml
<CustomObject>
    <label>GL Zone</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>GL Zones</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Vehicle_Master__c/Vehicle_Master__c.object-meta.xml
<CustomObject>
    <description>Emirates Transport Oracle Vehicle Master</description>
    <label>ET Vehicle Master</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Vehicle No.</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>ET Vehicle Masters</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Vehicle_Master__c/fields/Activity_Center_code__c.field-meta.xml
<CustomField>
    <fullName>Activity_Center_code__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Activity Center code</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Vehicle_Master__c/fields/Department_Code__c.field-meta.xml
<CustomField>
    <fullName>Department_Code__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Department Code</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Vehicle_Master__c/fields/Internal_No__c.field-meta.xml
<CustomField>
    <fullName>Internal_No__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <externalId>true</externalId>
    <label>Internal No</label>
    <length>100</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Vehicle_Master__c/fields/Location_Code__c.field-meta.xml
<CustomField>
    <fullName>Location_Code__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Location Code</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Vehicle_Master__c/fields/Plate_Type__c.field-meta.xml
<CustomField>
    <fullName>Plate_Type__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Plate Type</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/classes/ETVIN_VehicleMasterTrgHandlerTest.cls
@isTest(seeAllData=true)
public class ETVIN_VehicleMasterTrgHandlerTest {
    private static testmethod void vehicleMaster(){
    
        Vehicle_Master__c ve =  new Vehicle_Master__c();
        ve.name = 'B0017298';
        ve.Internal_No__c = 'B0017298';
        ve.Plate_Type__c = 'Private';
        ve.Activity_Center_code__c='123';
        ve.Department_Code__c = '123';
        ve.Project_Code__c='123';
        ve.Location_Code__c='123';
              
        insert ve;

        GL_Activity__c ac = new GL_Activity__c();
        ac.Name ='test';
        ac.GL_Activity_Code__c = '123';
        insert ac;
        ETSALES_Department__c de = new ETSALES_Department__c();
        de.Name = 'test';
        de.Department_Code__c = '123';
        insert de;
        ETSALES_Location__c lo = new ETSALES_Location__c();
        lo.Name ='test';
        lo.Location_Code__c='123';
        lo.GL_Zone__c ='Zone A';
        insert lo;
        GL_Project__c pr = new GL_Project__c();
        pr.Name = 'test';
        pr.Project_Code__c='123';
        insert pr;
    }       
    
}