unpackaged/main/default/objects/ETVIN_VehicleInvoiceAllocation__c/ETVIN_VehicleInvoiceAllocation__c.object-meta.xml
<CustomObject>
    <description>Vehicle Insurance</description>
    <label>Vehicle Invoice Allocations</label>
    <nameField>
        <displayFormat>VIA-{0000000}</displayFormat>
        <label>Ref Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Vehicle Invoice Allocations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/ETVIN_VehicleInvoiceAllocation__c/fields/Insurance_Invoices__c.field-meta.xml
<CustomField>
    <fullName>Insurance_Invoices__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Insurance Invoices</label>
    <referenceTo>ETIN_Insurance_Transactions__c</referenceTo>
    <relationshipLabel>Vehicle Invoice Allocations</relationshipLabel>
    <relationshipName>Vehicle_Invoice_Allocations</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/ETVIN_VehicleInvoiceAllocation__c/fields/Invoice_Type__c.field-meta.xml
<CustomField>
    <fullName>Invoice_Type__c</fullName>
    <label>Invoice Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Debit</fullName>
            </value>
            <value>
                <fullName>Credit</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/ETVIN_VehicleInvoiceAllocation__c/fields/Vehicle__c.field-meta.xml
<CustomField>
    <fullName>Vehicle__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Vehicle</label>
    <referenceTo>Vehicle_Master__c</referenceTo>
    <relationshipLabel>Vehicle Invoice Allocations</relationshipLabel>
    <relationshipName>Vehicle_Invoice_Allocations</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Vehicle__c/Vehicle__c.object-meta.xml
<CustomObject>
    <label>Pricing Vehicle Request</label>
    <nameField>
        <displayFormat>VN-{0000}</displayFormat>
        <label>Vehicle Request Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Vehicle Requests</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Vehicle_Master__c/Vehicle_Master__c.object-meta.xml
<CustomObject>
    <description>Emirates Transport Oracle Vehicle Master</description>
    <label>ET Vehicle Master</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Vehicle No.</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>ET Vehicle Masters</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/classes/ETVIN_VehicleAllocationUploadCtrl.cls
/* Author:Janardhan Muddana
 *  
 */
public class ETVIN_VehicleAllocationUploadCtrl {

      @AuraEnabled
    public static string insertData(String strfromle,string InvRecID){
        
      String returnresponse ='';
        set<string> vehIds = new set<string>();
        map<string,string> empIdvsAccId = new map<string,string>();
        List<ETVIN_VehicleInvoiceAllocation__c> VehUpdateList = new List<ETVIN_VehicleInvoiceAllocation__c>();
        system.debug('strfromle = ' + strfromle);
        List<fieldWrapper> datalist = (List<fieldWrapper>)JSON.deserialize(strfromle, List<fieldWrapper>.class);
       system.debug('datalist = ' + datalist);
        //system.debug('datalistSize = ' + datalist.size());
       for(fieldWrapper wrapper: datalist){
            
            vehIds.add(wrapper.VehicleInternalNumber);
        }
        if(vehIds.size()>0){
            
          
            for(Vehicle_Master__c ve : [select id,Name from Vehicle_Master__c where Name =:vehIds limit 50000]){
                empIdvsAccId.put(ve.Name,ve.Id);
            }
            
        }
        
        for(fieldWrapper wrapper: datalist){
            
                       
            ETVIN_VehicleInvoiceAllocation__c al =new  ETVIN_VehicleInvoiceAllocation__c();
            al.Amount__c = wrapper.Amount;
            al.Invoice_Type__c=wrapper.InvoiceType;
            al.Insurance_Invoices__c = InvRecID;
            
           
            if(empIdvsAccId.containsKey(wrapper.VehicleInternalNumber)){
              al.Vehicle__c = empIdvsAccId.get(wrapper.VehicleInternalNumber);
            }
                    
            VehUpdateList.add(al);            
        }
        
        if(VehUpdateList.size() > 0){
            try {
                insert VehUpdateList;
                returnresponse = 'SUCCESS';
            }
            catch(Exception ex){
                returnresponse = 'ERROR';
                system.debug('-err-'+ex);
                throw new AuraHandledException('Error-- '+ ex.getMessage());  
            }
        }
        return returnresponse;
    }
    
    public class fieldWrapper{  
        public String VehicleInternalNumber; 
        public decimal Amount;  
        public String InvoiceType;
        
    } 
   
}