unpackaged/main/default/objects/Notification__c/Notification__c.object-meta.xml
<CustomObject>
    <description>Send notifications Parents</description>
    <label>Notification</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Notification header</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Notifications</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Notification__c/fields/Notification_body__c.field-meta.xml
<CustomField>
    <fullName>Notification_body__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Notification body</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Notification__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Student Behavior</fullName>
            </value>
            <value>
                <fullName>Student Attendance</fullName>
            </value>
            <value>
                <fullName>Pick up</fullName>
            </value>
            <value>
                <fullName>Drop off</fullName>
            </value>
            <value>
                <fullName>The student is absent</fullName>
            </value>
            <value>
                <fullName>The students caught the wrong bus</fullName>
            </value>
            <value>
                <fullName>The student landed at the wrong place</fullName>
            </value>
            <value>
                <fullName>Student is returned to school</fullName>
            </value>
            <value>
                <fullName>Students absence for each trip</fullName>
            </value>
            <value>
                <fullName>students absence for period of time</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/classes/NotificationHandler_Test.cls
@isTest
public class NotificationHandler_Test {
    
    public static testMethod void testmethodNew(){
        
        Notification__c notification = new Notification__c();
        notification.Name='test';
        notification.Notification_body__c='test body';
        notification.Type__c='Student Attendance';
        insert notification;
        
         List<Notification__c> str = new List<Notification__c>();
        str.add(notification);
        
       /*
        insert p;
        
          */
        
        Test.startTest();
           NotificationHandler.SendNotifiaction(str);
        
        Test.stopTest();
            
        }
}