unpackaged/main/default/objects/ETT_Work_Schedule__c/ETT_Work_Schedule__c.object-meta.xml
<CustomObject>
    <label>Work Schedule</label>
    <nameField>
        <displayFormat>SCH-{000}</displayFormat>
        <label>Work Schedule Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Work Schedule</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

unpackaged/main/default/objects/ETT_Work_Schedule__c/fields/ETT_End_time__c.field-meta.xml
<CustomField>
    <fullName>ETT_End_time__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>End time</label>
    <required>true</required>
    <type>DateTime</type>
</CustomField>

unpackaged/main/default/objects/ETT_Work_Schedule__c/fields/ETT_Technician__c.field-meta.xml
<CustomField>
    <fullName>ETT_Technician__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Technician</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Work_Schedule</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/ETT_Work_Schedule__c/fields/ETT_Work_Station__c.field-meta.xml
<CustomField>
    <fullName>ETT_Work_Station__c</fullName>
    <label>Work Station</label>
    <referenceTo>ETT_Work_Station__c</referenceTo>
    <relationshipLabel>Work Schedule</relationshipLabel>
    <relationshipName>Work_Schedule</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
    <writeRequiresMasterRead>true</writeRequiresMasterRead>
</CustomField>

unpackaged/main/default/objects/ETT_Work_Station__c/ETT_Work_Station__c.object-meta.xml
<CustomObject>
    <label>Work Station</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Work Station Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Work Stations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/ETT_Work_Station__c/fields/ETT_Station_Code__c.field-meta.xml
<CustomField>
    <fullName>ETT_Station_Code__c</fullName>
    <caseSensitive>true</caseSensitive>
    <encryptionScheme>None</encryptionScheme>
    <label>Station Code</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

unpackaged/main/default/objects/ETT_Work_Station__c/fields/ETT_Station_Type__c.field-meta.xml
<CustomField>
    <fullName>ETT_Station_Type__c</fullName>
    <label>Station Type</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>ETT_Job_Station_Type</valueSetName>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/ETT_Work_Station_Checklist__c/ETT_Work_Station_Checklist__c.object-meta.xml
<CustomObject>
    <label>Work Station Checklist</label>
    <nameField>
        <displayFormat>CL-{0000}</displayFormat>
        <label>Checklist Ref. No</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Work Station Checklists</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

unpackaged/main/default/objects/ETT_Work_Station_Checklist__c/fields/Chamber_Motor_Condition__c.field-meta.xml
<CustomField>
    <fullName>Chamber_Motor_Condition__c</fullName>
    <label>Chamber Motor Condition</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>NotGood_Good</valueSetName>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/ETT_Work_Station_Checklist__c/fields/Control_Panel_Board_Condition__c.field-meta.xml
<CustomField>
    <fullName>Control_Panel_Board_Condition__c</fullName>
    <label>Control Panel Board Condition</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>NotGood_Good</valueSetName>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/ETT_Work_Station_Checklist__c/fields/Digital_Screen_Condition__c.field-meta.xml
<CustomField>
    <fullName>Digital_Screen_Condition__c</fullName>
    <label>Digital Screen Condition</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>NotGood_Good</valueSetName>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/ETT_Work_Station_Checklist__c/fields/Door_Safety_Lock_Condition__c.field-meta.xml
<CustomField>
    <fullName>Door_Safety_Lock_Condition__c</fullName>
    <label>Door Safety Lock Condition</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>NotGood_Good</valueSetName>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/ETT_Work_Station_Checklist__c/fields/Gaugs_Vacuum_Pressure_Condition__c.field-meta.xml
<CustomField>
    <fullName>Gaugs_Vacuum_Pressure_Condition__c</fullName>
    <label>Gaugs Vacuum Pressure Condition</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>NotGood_Good</valueSetName>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/ETT_Work_Station_Checklist__c/fields/Work_Schedule__c.field-meta.xml
<CustomField>
    <fullName>Work_Schedule__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Work Schedule</label>
    <referenceTo>ETT_Work_Schedule__c</referenceTo>
    <relationshipLabel>Work Station Checklists</relationshipLabel>
    <relationshipName>Work_Station_Checklists</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/ETT_Work_Station_Checklist__c/fields/Work_Station__c.field-meta.xml
<CustomField>
    <fullName>Work_Station__c</fullName>
    <label>Work Station</label>
    <referenceTo>ETT_Work_Station__c</referenceTo>
    <relationshipLabel>Work Station Checklists</relationshipLabel>
    <relationshipName>Work_Station_Checklists</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

unpackaged/main/default/objects/ETT_Work_Station_Checklist__c/fields/x13_Inflation_Pressure__c.field-meta.xml
<CustomField>
    <fullName>x13_Inflation_Pressure__c</fullName>
    <label>13 Inflation Pressure</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>NotGood_Good</valueSetName>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/ETT_Work_Station_Checklist__c/fields/X13_Pressure_Cable_Condition__c.field-meta.xml
<CustomField>
    <fullName>X13_Pressure_Cable_Condition__c</fullName>
    <label>13 Pressure Cable Condition</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>NotGood_Good</valueSetName>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/ETT_Work_Station_Checklist__c/fields/X13_Vacuum_Pressure_Valve_Condition__c.field-meta.xml
<CustomField>
    <fullName>X13_Vacuum_Pressure_Valve_Condition__c</fullName>
    <label>13 Vacuum Pressure Valve Condition</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>NotGood_Good</valueSetName>
    </valueSet>
</CustomField>

unpackaged/main/default/globalValueSets/ETT_Job_Station_Type.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Initial Inspection</fullName>
    </customValue>
    <customValue>
        <fullName>Buffing</fullName>
    </customValue>
    <customValue>
        <fullName>Skiving</fullName>
    </customValue>
    <customValue>
        <fullName>Repair</fullName>
    </customValue>
    <customValue>
        <fullName>Cementing</fullName>
    </customValue>
    <customValue>
        <fullName>Filling</fullName>
    </customValue>
    <customValue>
        <fullName>Thread Preparation</fullName>
    </customValue>
    <customValue>
        <fullName>Building</fullName>
    </customValue>
    <customValue>
        <fullName>Rimming &amp; Enveloping</fullName>
    </customValue>
    <customValue>
        <fullName>Curing</fullName>
    </customValue>
    <customValue>
        <fullName>Final Inspection</fullName>
    </customValue>
    <customValue>
        <fullName>Painting</fullName>
    </customValue>
    <customValue>
        <fullName>Removal of RIM Tube Flap</fullName>
    </customValue>
    <masterLabel>Job Station Type</masterLabel>
</GlobalValueSet>

unpackaged/main/default/globalValueSets/NotGood_Good.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Not Good</fullName>
    </customValue>
    <customValue>
        <fullName>Good</fullName>
    </customValue>
    <customValue>
        <fullName>NA</fullName>
        <default>true</default>
        <label>NA</label>
    </customValue>
    <masterLabel>NotGood_Good</masterLabel>
</GlobalValueSet>

unpackaged/main/default/classes/ETT_workStationCheckListHelperTest.cls
@isTest
public class ETT_workStationCheckListHelperTest {
    
    public static testmethod void notifyUserTest(){
        
        ETT_Work_Station__c ws = new ETT_Work_Station__c();
        ws.ETT_Station_Type__c ='Curing';
        ws.ETT_Station_Code__c='CUR001';
        insert ws;
        
        ETT_Work_Schedule__c wsc = new ETT_Work_Schedule__c();
        wsc.ETT_Start_time__c = system.today();
        wsc.ETT_End_time__c =  system.today()+2;
        wsc.ETT_Work_Station__c = ws.Id;
        wsc.ETT_Technician__c = userinfo.getUserId();
        insert wsc;
        
        ETT_Work_Station_Checklist__c ch = new ETT_Work_Station_Checklist__c();
        ch.Work_Schedule__c = wsc.Id;
        ch.Work_Station__c = ws.Id;
        ch.Door_Safety_Lock_Condition__c ='Not Good';
        ch.x13_Inflation_Pressure__c = 'Not Good';
        ch.X13_Pressure_Cable_Condition__c = 'Not Good';
        ch.X13_Vacuum_Pressure_Valve_Condition__c='Not Good';
        ch.Digital_Screen_Condition__c ='Not Good';
        ch.Control_Panel_Board_Condition__c ='Not Good';
        ch.Chamber_Motor_Condition__c ='Not Good';
        ch.Gaugs_Vacuum_Pressure_Condition__c ='Not Good';
        insert ch;
    }

}