unpackaged/main/default/objects/ETT_Job_Card_Close__c/ETT_Job_Card_Close__c.object-meta.xml
<CustomObject>
    <label>Job Card Close</label>
    <nameField>
        <displayFormat>JCC-{000000}</displayFormat>
        <label>Job Card Close Ref. No.</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Job Card Close</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

unpackaged/main/default/objects/ETT_Job_Card_Close_Lines__c/ETT_Job_Card_Close_Lines__c.object-meta.xml
<CustomObject>
    <label>Job Card Close Lines</label>
    <nameField>
        <displayFormat>JCCL-{00000}</displayFormat>
        <label>Job Card Close Lines</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Job Card Close Lines</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

unpackaged/main/default/objects/ETT_Job_Card_Close_Lines__c/fields/Issued_Quantity__c.field-meta.xml
<CustomField>
    <fullName>Issued_Quantity__c</fullName>
    <label>Issued Quantity</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

unpackaged/main/default/objects/ETT_Tools_Master__c/ETT_Tools_Master__c.object-meta.xml
<CustomObject>
    <label>Tools &amp; Materials Master</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Product Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Tools &amp; Materials Master</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/ETT_Tools_Master__c/fields/ETT_Allocated_Units__c.field-meta.xml
<CustomField>
    <fullName>ETT_Allocated_Units__c</fullName>
    <label>Factory Stock Units</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

unpackaged/main/default/classes/ETT_JobCardCloseTrgHelper.cls
/* Author: Janardhan
 * Class: ETT_JobCardCloseTrgHelper
 * CreatedDate: 14/11/2021
 * Desc:
 * TestClass:ETT_JobCardCloseTrgHelperTest
 * */
public class ETT_JobCardCloseTrgHelper {
    
    public static void updateToolsItemMaster(Map<id,ETT_Job_Card_Close__c> trgNewMap,Map<id,ETT_Job_Card_Close__c> trgOldMap){
        
        set<Id> approvedJobCardIds = new set<Id>();
        Map<Id,Decimal> toolMasIDVsIssuedQty = new  Map<Id,Decimal>();
        List<ETT_Tools_Master__c> updatedToolsMaster = new  List<ETT_Tools_Master__c>();
        
        for(ETT_Job_Card_Close__c jc : trgNewMap.values()){
            
            if(jc.Status__c != trgOldMap.get(jc.Id).Status__c && jc.Status__c == 'Approved'){
                
                approvedJobCardIds.add(jc.Id);
            }
        }
        
        for(ETT_Job_Card_Close_Lines__c jcl : [select id,Item_Name__c,Issued_Quantity__c from ETT_Job_Card_Close_Lines__c where Issued_Quantity__c!=null AND Job_Card_Close__c=:approvedJobCardIds]){
            
            if(!toolMasIDVsIssuedQty.containsKey(jcl.Item_Name__c) ){
                toolMasIDVsIssuedQty.put(jcl.Item_Name__c,jcl.Issued_Quantity__c);
            }else{
               if(jcl.Issued_Quantity__c!=null)
               toolMasIDVsIssuedQty.put(jcl.Item_Name__c,toolMasIDVsIssuedQty.get(jcl.Item_Name__c)+jcl.Issued_Quantity__c);
            }
            
        }
        
        for(ETT_Tools_Master__c tool : [select id,ETT_Allocated_Units__c from ETT_Tools_Master__c where Id=:toolMasIDVsIssuedQty.keyset()]){
            
            tool.ETT_Allocated_Units__c = tool.ETT_Allocated_Units__c - toolMasIDVsIssuedQty.get(tool.id);
            
            updatedToolsMaster.add(tool);
        }
        
        update updatedToolsMaster;
        
    }

}