unpackaged/main/default/objects/ETT_Brand_Master__c/ETT_Brand_Master__c.object-meta.xml
<CustomObject>
    <label>Brand Master</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Brand Master Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Brand Masters</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/ETT_Brand_Master__c/fields/ETT_Status__c.field-meta.xml
<CustomField>
    <fullName>ETT_Status__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Status</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/objects/ETT_Collection_Card__c/ETT_Collection_Card__c.object-meta.xml
<CustomObject>
    <description>This object is to track the vehicle information and as well as driver information with the help of google map.</description>
    <label>Collection Card</label>
    <nameField>
        <displayFormat>CC-{0000}</displayFormat>
        <label>Collection Card Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Collection Cards</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/ETT_Collection_Card__c/fields/ETT_Inspection_Done__c.field-meta.xml
<CustomField>
    <fullName>ETT_Inspection_Done__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Inspection Done</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/objects/ETT_Collection_Card__c/fields/ETT_Status__c.field-meta.xml
<CustomField>
    <fullName>ETT_Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Collection Stage</fullName>
            </value>
            <value>
                <fullName>Inspection Stage</fullName>
            </value>
            <value>
                <fullName>Job Card Stage</fullName>
            </value>
            <value>
                <fullName>Delivery Stage</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/ETT_Delivery_Line_Item__c/ETT_Delivery_Line_Item__c.object-meta.xml
<CustomObject>
    <label>Delivery Line Item</label>
    <nameField>
        <displayFormat>DLN-{0000}</displayFormat>
        <label>Delivery Line Item Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Delivery Line Items</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/ETT_Delivery_Line_Item__c/fields/ETT_Brand_Master__c.field-meta.xml
<CustomField>
    <fullName>ETT_Brand_Master__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Brand Master</label>
    <referenceTo>ETT_Brand_Master__c</referenceTo>
    <relationshipLabel>Delivery Line Items</relationshipLabel>
    <relationshipName>Delivery_Line_Items</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/ETT_Delivery_Line_Item__c/fields/ETT_Collection_Card__c.field-meta.xml
<CustomField>
    <fullName>ETT_Collection_Card__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Collection Card</label>
    <referenceTo>ETT_Collection_Card__c</referenceTo>
    <relationshipLabel>Delivery Line Items</relationshipLabel>
    <relationshipName>Delivery_Line_Items</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/ETT_Delivery_Line_Item__c/fields/ETT_Delivery_Note__c.field-meta.xml
<CustomField>
    <fullName>ETT_Delivery_Note__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Delivery Note</label>
    <referenceTo>ETT_Delivery_Note__c</referenceTo>
    <relationshipLabel>Delivery Line Items</relationshipLabel>
    <relationshipName>Delivery_Line_Items</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/ETT_Delivery_Line_Item__c/fields/ETT_Inspection_Card__c.field-meta.xml
<CustomField>
    <fullName>ETT_Inspection_Card__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Tyre Inspection Card</label>
    <referenceTo>ETT_Inspection_Card__c</referenceTo>
    <relationshipLabel>Delivery Line Items</relationshipLabel>
    <relationshipName>Delivery_Line_Items</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/ETT_Delivery_Note__c/ETT_Delivery_Note__c.object-meta.xml
<CustomObject>
    <label>Delivery Note</label>
    <nameField>
        <displayFormat>DNN-{0000}</displayFormat>
        <label>Delivery Note Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Delivery Notes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/ETT_Delivery_Note__c/fields/ETT_Casing__c.field-meta.xml
<CustomField>
    <fullName>ETT_Casing__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Casing</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/ETT_Delivery_Note__c/fields/ETT_Collection_Card__c.field-meta.xml
<CustomField>
    <fullName>ETT_Collection_Card__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Collection Card</label>
    <referenceTo>ETT_Collection_Card__c</referenceTo>
    <relationshipLabel>Delivery Notes</relationshipLabel>
    <relationshipName>Delivery_Notes</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/ETT_Estimate_Quotation__c/ETT_Estimate_Quotation__c.object-meta.xml
<CustomObject>
    <label>Estimation&#39;s</label>
    <nameField>
        <displayFormat>QN-{00000}</displayFormat>
        <label>Estimate Quotation Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Estimation&#39;s</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/ETT_Estimate_Quotation__c/fields/ETT_Collection_Card__c.field-meta.xml
<CustomField>
    <fullName>ETT_Collection_Card__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Collection Card</label>
    <referenceTo>ETT_Collection_Card__c</referenceTo>
    <relationshipLabel>Estimation&#39;s</relationshipLabel>
    <relationshipName>Estimation_s</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/ETT_Inspection_Card__c/ETT_Inspection_Card__c.object-meta.xml
<CustomObject>
    <description>This is for inspection for the customer who has been requested orders.</description>
    <label>Tyre Inspection Card</label>
    <nameField>
        <displayFormat>IC-{0000}</displayFormat>
        <label>Inspection Card Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Tyre Inspection Cards</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/ETT_Inspection_Card__c/fields/ETT_Collection_Card__c.field-meta.xml
<CustomField>
    <fullName>ETT_Collection_Card__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Collection Card</label>
    <referenceTo>ETT_Collection_Card__c</referenceTo>
    <relationshipName>Inspection_Cards</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/ETT_Inspection_Card__c/fields/ETT_Estimate_Quotation__c.field-meta.xml
<CustomField>
    <fullName>ETT_Estimate_Quotation__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Estimate Quotation</label>
    <referenceTo>ETT_Estimate_Quotation__c</referenceTo>
    <relationshipName>Inspection_Cards</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/ETT_Inspection_Card__c/fields/ETT_Status__c.field-meta.xml
<CustomField>
    <fullName>ETT_Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Not Inspected</fullName>
                <default>true</default>
                <label>Not Inspected</label>
            </value>
            <value>
                <fullName>Accept</fullName>
            </value>
            <value>
                <fullName>Send Back</fullName>
            </value>
            <value>
                <fullName>Scrap</fullName>
            </value>
            <value>
                <fullName>Accepted/No Warranty</fullName>
            </value>
            <value>
                <fullName>Pending</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/ETT_Tyre_Size_Master__c/ETT_Tyre_Size_Master__c.object-meta.xml
<CustomObject>
    <label>Tyre Size Master</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Tyre Sizes</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Tyre Size Master</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/classes/ETT_DeliveryNoteController_Test.cls
@isTest
public class ETT_DeliveryNoteController_Test {
    
    @isTest public static void testFetchUser(){
        
        ETT_DeliveryNoteController.fetchUser();
    }
    
    @isTest public static void testGetJobCardIntoList(){
        
        Map<String,String> mapList = new  Map<String,String>();
       /* List<Account> accountsList = ETT_TestFactory.createAccounts('TestAccountName', 'Tyre Customer');
        insert accountsList;*/
        Account objAcc1 = new Account();
        objAcc1.Name = 'First Account';
        insert objAcc1;
        Opportunity opp = ETT_TestFactory.createOpportunity('Tyre - Cash Supplier','TestOppName', 'Qualification', system.today().adddays(20), objAcc1.Id);
        insert opp;
        List<ETT_Brand_Master__c> brandMastersList = ETT_TestFactory.createBrandMasters();
        insert brandMastersList;
        List<ETT_Tyre_Size_Master__c> tyreMasterSizeList =  ETT_TestFactory.createTyreSizeMaster();
        insert tyreMasterSizeList;
        List<ETT_Collection_Card__c> collectionCardsList = ETT_TestFactory.createCollectionCards(objAcc1.Id,opp.Id);
        collectionCardsList[0].ETT_Inspection_Done__c = true;
        insert collectionCardsList;
        List<ETT_Inspection_Card__c> inspectionsCardsList = ETT_TestFactory.createInspectionCards('Tyre - Cash Supplier',objAcc1.Id,brandMastersList[0].Id,collectionCardsList[0].Id,tyreMasterSizeList[0].Id);
        inspectionsCardsList[0].ETT_Status__c ='Send Back';
        insert inspectionsCardsList;
        List<ETT_Estimate_Quotation__c>  estimateQuotationsList = ETT_TestFactory.createEstimateQuotations(collectionCardsList[0].Id,inspectionsCardsList[0].Id,tyreMasterSizeList[0].Id);
        insert estimateQuotationsList;
        List<ETT_Delivery_Note__c> deliveryNotesList = ETT_TestFactory.createDeliveryNotes('Tyre - Customer',objAcc1.Id,estimateQuotationsList[0].Id,tyreMasterSizeList[0].Id,brandMastersList[0].Id );
        insert deliveryNotesList[2];
        List<ETT_Delivery_Line_Item__c> deliveryLineItemsList = ETT_TestFactory.createDeliveryLineItems(4,collectionCardsList[0].Id,inspectionsCardsList[0].Id,tyreMasterSizeList[0].Id,brandMastersList[0].Id);
        deliveryLineItemsList[2].ETT_Delivery_Note__c = deliveryNotesList[2].id;
        
        
        ETT_DeliveryNoteController.getJobCardIntoList(objAcc1.Id);
        ETT_DeliveryNoteController.getJobCardIntoListForPrint(objAcc1.Id);
        insert deliveryLineItemsList[2];
        mapList.put('deliveryNoteJson', JSON.serialize(deliveryNotesList[0]));
        mapList.put('deliveryLineItemJson', JSON.serialize(deliveryLineItemsList));
        ETT_DeliveryNoteController.submitDeliveryNote(mapList);
        
    }
    
    @isTest public static void testGetJobCardIntoList1(){
        
        Map<String,String> mapList = new  Map<String,String>();
       /* List<Account> accountsList = ETT_TestFactory.createAccounts('TestAccountName', 'Tyre Customer');
        insert accountsList;*/
        Account objAcc1 = new Account();
        objAcc1.Name = 'First Account';
        insert objAcc1;
        Opportunity opp = ETT_TestFactory.createOpportunity('Tyre - Cash Supplier','TestOppName', 'Qualification', system.today().adddays(20), objAcc1.Id);
        insert opp;
        List<ETT_Brand_Master__c> brandMastersList = ETT_TestFactory.createBrandMasters();
        insert brandMastersList;
        List<ETT_Tyre_Size_Master__c> tyreMasterSizeList =  ETT_TestFactory.createTyreSizeMaster();
        insert tyreMasterSizeList;
        List<ETT_Collection_Card__c> collectionCardsList = ETT_TestFactory.createCollectionCards(objAcc1.Id,opp.Id);
        collectionCardsList[0].ETT_Inspection_Done__c = true;
        insert collectionCardsList;
        List<ETT_Inspection_Card__c> inspectionsCardsList = ETT_TestFactory.createInspectionCards('Tyre - Cash Supplier',objAcc1.Id,brandMastersList[0].Id,collectionCardsList[0].Id,tyreMasterSizeList[0].Id);
        inspectionsCardsList[0].ETT_Status__c ='Send Back';
        insert inspectionsCardsList;
        List<ETT_Estimate_Quotation__c>  estimateQuotationsList = ETT_TestFactory.createEstimateQuotations(collectionCardsList[0].Id,inspectionsCardsList[0].Id,tyreMasterSizeList[0].Id);
        insert estimateQuotationsList;
        List<ETT_Delivery_Note__c> deliveryNotesList = ETT_TestFactory.createDeliveryNotes('Tyre - Customer',objAcc1.Id,estimateQuotationsList[0].Id,tyreMasterSizeList[0].Id,brandMastersList[0].Id );
        insert deliveryNotesList[2];
        deliveryNotesList[0].ETT_Casing__c = 'Supplier Casing';
        List<ETT_Delivery_Line_Item__c> deliveryLineItemsList = ETT_TestFactory.createDeliveryLineItems(1,collectionCardsList[0].Id,inspectionsCardsList[0].Id,tyreMasterSizeList[0].Id,brandMastersList[0].Id);
        deliveryLineItemsList[0].ETT_Delivery_Note__c = deliveryNotesList[2].id;
        insert deliveryLineItemsList[0];
        try{
            ETT_DeliveryNoteController.getJobCardIntoList(objAcc1.Id);
            ETT_DeliveryNoteController.getJobCardIntoListForPrint(objAcc1.Id);
        }catch(exception e){
            system.debug('excep '+e); 
        }
        mapList.put('deliveryNoteJson', JSON.serialize(deliveryNotesList[0]));
       
        mapList.put('deliveryLineItemJson', JSON.serialize(deliveryLineItemsList));
        ETT_DeliveryNoteController.submitDeliveryNote(mapList);
        deliveryNotesList[0].ETT_Casing__c = 'Customer Casing';
        mapList.put('deliveryNoteJson', JSON.serialize(deliveryNotesList[0]));
       // ETT_DeliveryNoteController.submitDeliveryNote(mapList);
        
         mapList.put('deliveryLineItemJson', JSON.serialize(deliveryLineItemsList = ETT_TestFactory.createDeliveryLineItems(1,collectionCardsList[0].Id,inspectionsCardsList[0].Id,tyreMasterSizeList[0].Id,brandMastersList[0].Id)));
        ETT_DeliveryNoteController.submitDeliveryNote(mapList);
        
    }
    
}