unpackaged/main/default/objects/ETT_Brand_Master__c/ETT_Brand_Master__c.object-meta.xml
<CustomObject>
    <label>Brand Master</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Brand Master Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Brand Masters</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/ETT_Country_Master__c/ETT_Country_Master__c.object-meta.xml
<CustomObject>
    <label>Country Master</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Country Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Country Masters</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/ETT_Pattern_Master__c/ETT_Pattern_Master__c.object-meta.xml
<CustomObject>
    <label>Pattern Master</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Pattern Code</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Pattern Masters</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/ETT_Price_Master__c/ETT_Price_Master__c.object-meta.xml
<CustomObject>
    <label>Price Master</label>
    <nameField>
        <displayFormat>PMN-{0000}</displayFormat>
        <label>Price Master Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Price Masters</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/ETT_Price_Master__c/fields/ETT_Party_Name__c.field-meta.xml
<CustomField>
    <fullName>ETT_Party_Name__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Party Name</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Price Masters</relationshipLabel>
    <relationshipName>Price_Masters</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/ETT_Pricing_Information__c/ETT_Pricing_Information__c.object-meta.xml
<CustomObject>
    <label>Pricing Information</label>
    <nameField>
        <displayFormat>PI-{0000}</displayFormat>
        <label>Pricing Info Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Pricing Information</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

unpackaged/main/default/objects/ETT_Pricing_Information__c/fields/ETT_Approval_Status__c.field-meta.xml
<CustomField>
    <fullName>ETT_Approval_Status__c</fullName>
    <label>Approval Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>New</fullName>
            </value>
            <value>
                <fullName>In Progress</fullName>
            </value>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>Rejected</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/ETT_Pricing_Information__c/fields/ETT_Brand__c.field-meta.xml
<CustomField>
    <fullName>ETT_Brand__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Brand</label>
    <referenceTo>ETT_Brand_Master__c</referenceTo>
    <relationshipLabel>Pricing Information</relationshipLabel>
    <relationshipName>Pricing_Information</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/ETT_Pricing_Information__c/fields/ETT_Country_of_Origin__c.field-meta.xml
<CustomField>
    <fullName>ETT_Country_of_Origin__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Country of Origin</label>
    <referenceTo>ETT_Country_Master__c</referenceTo>
    <relationshipLabel>Pricing Information</relationshipLabel>
    <relationshipName>Pricing_Information</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/ETT_Pricing_Information__c/fields/ETT_Pattern__c.field-meta.xml
<CustomField>
    <fullName>ETT_Pattern__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Pattern</label>
    <referenceTo>ETT_Pattern_Master__c</referenceTo>
    <relationshipLabel>Pricing Information</relationshipLabel>
    <relationshipName>Pricing_Information</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/ETT_Pricing_Information__c/fields/ETT_Price__c.field-meta.xml
<CustomField>
    <fullName>ETT_Price__c</fullName>
    <label>Price</label>
    <referenceTo>ETT_Price_Master__c</referenceTo>
    <relationshipLabel>Pricing Information</relationshipLabel>
    <relationshipName>Pricing_Information</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

unpackaged/main/default/objects/ETT_Pricing_Information__c/fields/ETT_Tyre_Size__c.field-meta.xml
<CustomField>
    <fullName>ETT_Tyre_Size__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Tyre Size</label>
    <referenceTo>ETT_Tyre_Size_Master__c</referenceTo>
    <relationshipLabel>Pricing Information</relationshipLabel>
    <relationshipName>Pricing_Information</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/ETT_Tyre_Size_Master__c/ETT_Tyre_Size_Master__c.object-meta.xml
<CustomObject>
    <label>Tyre Size Master</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Tyre Sizes</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Tyre Size Master</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/ETT_Tyre_Size_Master__c/fields/ETT_Tyre_Size__c.field-meta.xml
<CustomField>
    <fullName>ETT_Tyre_Size__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Tyre size</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/classes/ETT_PricingInfoTrgHelperTest.cls
@isTest
public class ETT_PricingInfoTrgHelperTest {

    public static testmethod void testDuplicate(){
        List<Account> accountsList = ETT_TestFactory.createAccounts('TJ89ntName34434', 'Organization');
        insert accountsList;
        
        ETT_Price_Master__c pm2 = new ETT_Price_Master__c();
        pm2.ETT_Party_Name__c = accountsList[0].Id;
        insert pm2;
        
          ETT_Tyre_Size_Master__c tsm = new ETT_Tyre_Size_Master__c();
        tsm.Name ='Size1';
        insert tsm;
        
        ETT_Pattern_Master__c pat = new ETT_Pattern_Master__c();
        pat.Name ='Pat21';
        insert pat;
        
        ETT_Country_Master__c coun = new ETT_Country_Master__c();
        coun.Name ='Coun1';
        insert coun;
        
        ETT_Brand_Master__c bra = new ETT_Brand_Master__c();
        bra.Name ='Bran1';
        insert bra;
        
        ETT_Pricing_Information__c epi = new ETT_Pricing_Information__c();
        epi.ETT_Price__c=pm2.Id;
        epi.ETT_Tyre_Size__c=tsm.Id;
        epi.ETT_Brand__c=bra.Id;
        epi.ETT_Country_of_Origin__c=coun.Id;
        epi.ETT_Pattern__c=pat.Id;
        epi.ETT_Approval_Status__c ='Approved';
        insert epi;
        
    }
}