unpackaged/main/default/objects/ETT_Brand_Master__c/ETT_Brand_Master__c.object-meta.xml
<CustomObject>
    <label>Brand Master</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Brand Master Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Brand Masters</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/ETT_Brand_Master__c/fields/ETT_Brand_Code__c.field-meta.xml
<CustomField>
    <fullName>ETT_Brand_Code__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Brand Code</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/ETT_Brand_Master__c/fields/ETT_Status__c.field-meta.xml
<CustomField>
    <fullName>ETT_Status__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Status</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/objects/ETT_Country_Master__c/ETT_Country_Master__c.object-meta.xml
<CustomObject>
    <label>Country Master</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Country Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Country Masters</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/ETT_Country_Master__c/fields/ETT_Country_Code__c.field-meta.xml
<CustomField>
    <fullName>ETT_Country_Code__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Country Code</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/ETT_Pattern_Master__c/ETT_Pattern_Master__c.object-meta.xml
<CustomObject>
    <label>Pattern Master</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Pattern Code</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Pattern Masters</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/ETT_Pattern_Master__c/fields/ETT_Brand_Name__c.field-meta.xml
<CustomField>
    <fullName>ETT_Brand_Name__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Brand Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/ETT_Tyre_Master__c/ETT_Tyre_Master__c.object-meta.xml
<CustomObject>
    <label>Tyre Master</label>
    <nameField>
        <displayFormat>TMN-{0000}</displayFormat>
        <label>Tyre Master Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Tyre Masters</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/ETT_Tyre_Master__c/fields/ETT_Actual_Width__c.field-meta.xml
<CustomField>
    <fullName>ETT_Actual_Width__c</fullName>
    <label>Width</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

unpackaged/main/default/objects/ETT_Tyre_Master__c/fields/ETT_Bead_Adjustment__c.field-meta.xml
<CustomField>
    <fullName>ETT_Bead_Adjustment__c</fullName>
    <label>Bead Adjustment</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

unpackaged/main/default/objects/ETT_Tyre_Master__c/fields/ETT_Brand_Name__c.field-meta.xml
<CustomField>
    <fullName>ETT_Brand_Name__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Brand Name</label>
    <referenceTo>ETT_Brand_Master__c</referenceTo>
    <relationshipLabel>Tyre Masters</relationshipLabel>
    <relationshipName>Tyre_Masters</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/ETT_Tyre_Master__c/fields/ETT_Country_Name__c.field-meta.xml
<CustomField>
    <fullName>ETT_Country_Name__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Country Name</label>
    <referenceTo>ETT_Country_Master__c</referenceTo>
    <relationshipLabel>Tyre Masters</relationshipLabel>
    <relationshipName>Tyre_Masters</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/ETT_Tyre_Master__c/fields/ETT_Country_Status__c.field-meta.xml
<CustomField>
    <fullName>ETT_Country_Status__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Country Status</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/objects/ETT_Tyre_Master__c/fields/ETT_Item_Code_Refurbished__c.field-meta.xml
<CustomField>
    <fullName>ETT_Item_Code_Refurbished__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Item Code Refurbished</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/ETT_Tyre_Master__c/fields/ETT_Item_Code_Scrap__c.field-meta.xml
<CustomField>
    <fullName>ETT_Item_Code_Scrap__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Item Code Scrap</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/ETT_Tyre_Master__c/fields/ETT_Item_Code_Used__c.field-meta.xml
<CustomField>
    <fullName>ETT_Item_Code_Used__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Item Code Used</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/ETT_Tyre_Master__c/fields/ETT_Length__c.field-meta.xml
<CustomField>
    <fullName>ETT_Length__c</fullName>
    <label>Length</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

unpackaged/main/default/objects/ETT_Tyre_Master__c/fields/ETT_Load_Index__c.field-meta.xml
<CustomField>
    <fullName>ETT_Load_Index__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Load Index</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/ETT_Tyre_Master__c/fields/ETT_Original_Pattern__c.field-meta.xml
<CustomField>
    <fullName>ETT_Original_Pattern__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Original Pattern</label>
    <referenceTo>ETT_Pattern_Master__c</referenceTo>
    <relationshipLabel>Tyre Masters</relationshipLabel>
    <relationshipName>Tyre_Masters</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/ETT_Tyre_Master__c/fields/ETT_Ply_Rate__c.field-meta.xml
<CustomField>
    <fullName>ETT_Ply_Rate__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Ply Rate</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/ETT_Tyre_Master__c/fields/ETT_Rim_Size__c.field-meta.xml
<CustomField>
    <fullName>ETT_Rim_Size__c</fullName>
    <label>Rim Size</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

unpackaged/main/default/objects/ETT_Tyre_Master__c/fields/ETT_Speed_Index__c.field-meta.xml
<CustomField>
    <fullName>ETT_Speed_Index__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Speed Index</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/ETT_Tyre_Master__c/fields/ETT_Tyre_Radiues__c.field-meta.xml
<CustomField>
    <fullName>ETT_Tyre_Radiues__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Tyre Radiues</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/ETT_Tyre_Master__c/fields/ETT_Tyre_Size__c.field-meta.xml
<CustomField>
    <fullName>ETT_Tyre_Size__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Tyre Size</label>
    <referenceTo>ETT_Tyre_Size_Master__c</referenceTo>
    <relationshipLabel>Tyre Masters</relationshipLabel>
    <relationshipName>Tyre_Masters</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/ETT_Tyre_Master__c/fields/ETT_Tyre_Status__c.field-meta.xml
<CustomField>
    <fullName>ETT_Tyre_Status__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Tyre Status</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/objects/ETT_Tyre_Master__c/fields/ETT_Vehicle_Type__c.field-meta.xml
<CustomField>
    <fullName>ETT_Vehicle_Type__c</fullName>
    <label>Vehicle Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Bus</fullName>
            </value>
            <value>
                <fullName>Bus Truck</fullName>
            </value>
            <value>
                <fullName>Light</fullName>
            </value>
            <value>
                <fullName>Light Truck</fullName>
            </value>
            <value>
                <fullName>Flap</fullName>
            </value>
            <value>
                <fullName>Industrial Tyres</fullName>
            </value>
            <value>
                <fullName>Truck</fullName>
            </value>
            <value>
                <fullName>Tube</fullName>
            </value>
            <value>
                <fullName>OTR Tyre</fullName>
            </value>
            <value>
                <fullName>Passengers</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/ETT_Tyre_Size_Master__c/ETT_Tyre_Size_Master__c.object-meta.xml
<CustomObject>
    <label>Tyre Size Master</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Tyre Sizes</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Tyre Size Master</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/ETT_Tyre_Size_Master__c/fields/ETT_Tyre_Size__c.field-meta.xml
<CustomField>
    <fullName>ETT_Tyre_Size__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Tyre size</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Lead/fields/ETSALES_Lead_Rating__c.field-meta.xml
<CustomField>
    <fullName>ETSALES_Lead_Rating__c</fullName>
    <label>Prospect Rating</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Hot</fullName>
            </value>
            <value>
                <fullName>Warm</fullName>
            </value>
            <value>
                <fullName>Cold</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/classes/ETT_DynamicLookupController_Test.cls
@isTest
public class ETT_DynamicLookupController_Test {
    
    @isTest static void getResultsTest(){
        List<Lead> leadList =  ETT_TestFactory.createLeads();
        insert leadList;
        ETT_DynamicLookupController.getResults('Lead', 'ETSALES_Lead_Rating__c', 'Hot');
    }
    
    @isTest static void getFilteredResultsTest(){
        
        List<Lead> leadList =  ETT_TestFactory.createLeads();
        insert leadList;
        List<ETT_Brand_Master__c> brandMastersList = ETT_TestFactory.createBrandMasters();
        List<ETT_Pattern_Master__c> patternMastersList = ETT_TestFactory.createPatternMasters();
        List<ETT_Tyre_Size_Master__c> tyreMasterSizeList =  ETT_TestFactory.createTyreSizeMaster();
        ETT_Country_Master__c cntry = ETT_TestFactory.createCountries('TestCountry');
        patternMastersList[0].ETT_Status__c = true;
        patternMastersList[0].Name = 'Test Record';
        insert cntry;
        brandMastersList[0].name = 'Test Record';
        system.debug('tyreMasterSizeList '+tyreMasterSizeList[0]);
        insert patternMastersList;
      

        //tyreMasterSizeList[0].ETT_Original_Pattern__c = patternMastersList[0].id;
         insert tyreMasterSizeList;
        insert brandMastersList;
        List<ETT_Tyre_Master__c> tyreMastersList = ETT_TestFactory.createTyreMasters('Draft', patternMastersList[0].Id,cntry.Id,tyreMasterSizeList[0].Id,brandMastersList[0].Id);
        insert tyreMastersList[0];
        system.debug('brand'+[select id,name from ETT_Pattern_Master__c where Name LIKE '%%']);
        system.debug('res '+[SELECT Id, ETT_Tyre_Size__r.ETT_Status__c From ETT_Tyre_Master__c]);
        
        ETT_Tyre_Master__c ett_tyre_master = new ETT_Tyre_Master__c(
            CurrencyIsoCode = 'AED',
            ETT_Actual_Width__c = 210.0,
            ETT_Bead_Adjustment__c = 2.0,
            ETT_Brand_Code__c = 'ALT',
            ETT_Brand_Name__c = brandMastersList[0].id,
            ETT_Country_Code__c = 'IND',
            ETT_Country_Name__c = cntry.id,
            ETT_Country_Status__c = false,
            ETT_Item_Code_Refurbished__c = 'TR-10.00-20-ALT',
            ETT_Item_Code_Scrap__c = 'TS-10.00-20-ALT',
            ETT_Item_Code_Used__c = 'TU-10.00-20-ALT',
            ETT_Length__c = 3.2,
            ETT_Load_Index__c = '146/142',
            ETT_Original_Pattern__c = patternMastersList[0].id,
            ETT_Ply_Rate__c = '16',
            ETT_Rim_Size__c = 20.0,
            ETT_Speed_Index__c = 'J',
            ETT_Status__c = false,
            ETT_Tyre_Radiues__c = '24',
            ETT_Tyre_Size__c = tyreMasterSizeList[0].id,
            ETT_Tyre_Status__c = false,
            ETT_Vehicle_Type__c = 'Bus');
        insert ett_tyre_master;
        system.debug('tyreMastersList '+tyreMastersList);
        ETT_DynamicLookupController.getFilteredResults('ETT_Tyre_Size_Master__c', 'ETT_Tyre_Size__c', '', '', '', '', '');
        ETT_DynamicLookupController.getFilteredResults('ETT_Country_Master__c', 'ETT_Country_Name__c', '', '', '', '', '');
        ETT_DynamicLookupController.getFilteredResults('ETT_Brand_Master__c', 'ETT_Brand_Name__c', '', '', '', '', '');
        ETT_DynamicLookupController.getFilteredResults('ETT_Pattern_Master__c', 'ETT_Original_Pattern__c', 'test', 'Test', '', '', '');
        
    }
}