unpackaged/main/default/objects/ETIN_Insurance__c/ETIN_Insurance__c.object-meta.xml
<CustomObject>
    <label>Insurance</label>
    <nameField>
        <displayFormat>ETIN-{000000}</displayFormat>
        <label>Insurance Ref Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Insurances</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

unpackaged/main/default/objects/ETIN_Insurance__c/fields/Card_Number__c.field-meta.xml
<CustomField>
    <fullName>Card_Number__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Card Number</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/ETIN_Insurance__c/fields/EmployeeAcc__c.field-meta.xml
<CustomField>
    <fullName>EmployeeAcc__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Employee</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Insurances</relationshipLabel>
    <relationshipName>Insurances</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/ETIN_Insurance__c/fields/Insurance_Company_Email__c.field-meta.xml
<CustomField>
    <fullName>Insurance_Company_Email__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Insurance Company Email</label>
    <type>Email</type>
</CustomField>

unpackaged/main/default/objects/ETIN_Insurance__c/fields/Insurance_Current_Status__c.field-meta.xml
<CustomField>
    <fullName>Insurance_Current_Status__c</fullName>
    <label>Insurance Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Active</fullName>
            </value>
            <value>
                <fullName>Inactive</fullName>
                <default>true</default>
                <label>Inactive</label>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
            <value>
                <fullName>Duplicate</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/ETIN_Insurance__c/fields/Insurance_Policy_Number__c.field-meta.xml
<CustomField>
    <fullName>Insurance_Policy_Number__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Insurance Policy Number</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/ETIN_Insurance__c/fields/Renew_Request__c.field-meta.xml
<CustomField>
    <fullName>Renew_Request__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Renewal Request?</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/objects/ETIN_Insurance__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Request Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>New</fullName>
                <default>true</default>
                <label>New</label>
            </value>
            <value>
                <fullName>Pending with HR Manager</fullName>
            </value>
            <value>
                <fullName>Under Process</fullName>
            </value>
            <value>
                <fullName>Under Approval</fullName>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
            <value>
                <fullName>Pending with Zone Coordinator</fullName>
            </value>
            <value>
                <fullName>Not Eligible</fullName>
            </value>
            <value>
                <fullName>Under Investigation</fullName>
            </value>
            <value>
                <fullName>Hold</fullName>
            </value>
            <value>
                <fullName>Admin Approval Pending</fullName>
                <isActive>false</isActive>
                <label>Admin Approval Pending</label>
            </value>
            <value>
                <fullName>Admin Approved</fullName>
                <isActive>false</isActive>
                <label>Admin Approved</label>
            </value>
            <value>
                <fullName>Admin Rejected</fullName>
                <isActive>false</isActive>
                <label>Admin Rejected</label>
            </value>
            <value>
                <fullName>HR Rejected</fullName>
                <isActive>false</isActive>
                <label>HR Rejected</label>
            </value>
            <value>
                <fullName>Insurance Approved</fullName>
                <isActive>false</isActive>
                <label>Insurance Approved</label>
            </value>
            <value>
                <fullName>Insurance Pending</fullName>
                <isActive>false</isActive>
                <label>Insurance Pending</label>
            </value>
            <value>
                <fullName>Insurance Rejected</fullName>
                <isActive>false</isActive>
                <label>Insurance Rejected</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/ETIN_Insurance__c/recordTypes/Health_Insurance.recordType-meta.xml
<RecordType>
    <fullName>Health_Insurance</fullName>
    <active>true</active>
    <label>Health Insurance</label>
</RecordType>

unpackaged/main/default/classes/ETIN_ZoneRenewalReqCtrlTest.cls
@isTest
public class ETIN_ZoneRenewalReqCtrlTest {
 
    
    private static testmethod void RenewlMethod(){
        Test.startTest(); 
        Profile profile1 = [Select Id from Profile where name = 'System Administrator'];
        
        User u = new User(
            
            ProfileId = profile1.Id,
            Username = 'testtermsc@kaplan.com',
            Alias = 'batman',
            Email='testterms@kaplan.com',
            EmailEncodingKey='UTF-8',
            Firstname='Bruce',
            Lastname='Wayne',
            LanguageLocaleKey='en_US',
            LocaleSidKey='en_US',
            TimeZoneSidKey='America/Chicago');
        insert u;
        user u2 = [select id from user where Username = 'testtermsc@kaplan.com' ];
        System.runas(u) {
            
            ETIN_ZoneRenewalReqCtrl.getInsuranceDetails();
            ETIN_ZoneRenewalReqCtrl.getInsuranceAdminDetails();
            ETIN_ZoneRenewalReqCtrl.getInsuranceAdminDetails();
            ETIN_ZoneRenewalReqCtrl.fetchUser();
            
            Account acc = new account();
            acc.Name = 'test343';
            
            insert acc;
            
           Account acc1 = new account();
            acc1.Name = 'test5453';
            
            insert acc1;
        
            
            List<ETIN_Insurance__c> InsList = new List<ETIN_Insurance__c>();
            List<id> idList = new List<id>();
            
            Id insHealthRecID  = Schema.SObjectType.ETIN_Insurance__c.getRecordTypeInfosByDeveloperName().get('Health_Insurance').getRecordTypeId();
            ETIN_Insurance__c et = new ETIN_Insurance__c();
            et.Insurance_Policy_Number__c = '133323';
            et.Insurance_Current_Status__c = 'Active';
            et.Insurance_Company_Email__c='test@gmail.com';
            et.Card_Number__c = '112121212';
            et.EmployeeAcc__c = acc.Id;
            et.Renew_Request__c = false;
            et.Insurance_Current_Status__c ='Active';
            et.RecordTypeId =insHealthRecID;
            et.OwnerId = u2.Id;
            
            insert et;
            
            idList.add(et.id);
            
            ETIN_Insurance__c et1 = new ETIN_Insurance__c();
            et1.Insurance_Policy_Number__c = '133323';
            et1.Insurance_Current_Status__c = 'Active';
            et1.Insurance_Company_Email__c='test@gmail.com';
            et1.Card_Number__c = '112121212';
            et1.EmployeeAcc__c = acc1.Id;
            et1.Renew_Request__c = false;
            et1.Insurance_Current_Status__c ='Active';
            et1.RecordTypeId =insHealthRecID;
            et1.Status__c = 'Pending with Zone Coordinator';
            et1.OwnerId = u2.Id; 
            insert et1; 
            idList.add(et1.id);
            list<ETIN_Insurance__c> listofIns = [select id,OwnerId,CreatedById from ETIN_Insurance__c where id=:idList ]; 
            // InsList.add(et);
            // InsList.add(et1);
            
            ETIN_ZoneRenewalReqCtrl.submitToZoneHRManager(idList);
            ETIN_ZoneRenewalReqCtrl.submitToInsuranceAdmin(listofIns);
            ETIN_ZoneRenewalReqCtrl.submitToZoneCoord(listofIns);
            ETIN_ZoneRenewalReqCtrl.ApprovedByAdminMethod(listofIns);
            ETIN_ZoneRenewalReqCtrl.RejectedByAdminMethod(listofIns);
        }
        
        Test.stopTest();
    }
    
    
}