unpackaged/main/default/objects/ETDI_Booking_Request__c/ETDI_Booking_Request__c.object-meta.xml
<CustomObject>
    <label>ETDI Booking Request</label>
    <nameField>
        <displayFormat>BR-{00000}</displayFormat>
        <label>Booking Request Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>ETDI Booking Requests</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/ETDI_Booking_Request__c/fields/Language__c.field-meta.xml
<CustomField>
    <fullName>Language__c</fullName>
    <label>Language</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Arabic</fullName>
            </value>
            <value>
                <fullName>English</fullName>
            </value>
            <value>
                <fullName>Pashto</fullName>
            </value>
            <value>
                <fullName>Urdu</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/ETDI_Trainees__c/ETDI_Trainees__c.object-meta.xml
<CustomObject>
    <label>ETDI Trainees</label>
    <nameField>
        <displayFormat>TRA - {00000}</displayFormat>
        <label>Trainee Ref No.</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>ETDI Trainees</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

unpackaged/main/default/objects/ETDI_Trainees__c/fields/ETDI_Booking_Request__c.field-meta.xml
<CustomField>
    <fullName>ETDI_Booking_Request__c</fullName>
    <label>Booking Request</label>
    <referenceTo>ETDI_Booking_Request__c</referenceTo>
    <relationshipLabel>ETDI Trainees</relationshipLabel>
    <relationshipName>ETDI_Trainees</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

unpackaged/main/default/classes/TraineeCertificatePdfController_Test.cls
/*
 * Class		: TraineeCertificatePdfController_Test
 * Description  : Test class for TraineeCertificatePdfController
 * Author		: Sreelakshmi SK
 * Date			: 19/6/23
*/

@isTest
public class TraineeCertificatePdfController_Test {
    
    @isTest
    public static void testTraineeCertificatePdfController() {
        ETDI_Booking_Request__c bkreq = new ETDI_Booking_Request__c();
        bkreq.Language__c='English';
        insert bkreq;
        ETDI_Trainees__c trainee = new ETDI_Trainees__c();
        trainee.ETDI_Booking_Request__c=bkreq.id;
        insert trainee;
        list<ETDI_Trainees__c>traineeList=new list<ETDI_Trainees__c>();
        traineeList.add(trainee);
        PageReference pageRef = Page.Trainee_Certificate;
        pageRef.getParameters().put('id', trainee.Id);
        Test.setCurrentPage(pageRef);
        ApexPages.StandardController standardController = new ApexPages.StandardController(trainee);
        TraineeCertificatePdfController controller = new TraineeCertificatePdfController(standardController);
       
    }
    
    @isTest
    public static void testTraineeRecordGetterSetter() {
        ETDI_Booking_Request__c bkreq = new ETDI_Booking_Request__c();
        bkreq.Language__c='English';
        insert bkreq;
        ETDI_Trainees__c trainee = new ETDI_Trainees__c();
        trainee.ETDI_Booking_Request__c=bkreq.id;
        insert trainee;
        List<ETDI_Trainees__c> trainees = new List<ETDI_Trainees__c>();
        trainees.add(trainee);
        TraineeCertificatePdfController controller = new TraineeCertificatePdfController(null);
        controller.TraineeRecord = trainees;
        List<ETDI_Trainees__c> retrievedTrainees = controller.TraineeRecord;
    }

}