unpackaged/main/default/objects/ETT_Staging_Quotation_Request__c/ETT_Staging_Quotation_Request__c.object-meta.xml
<CustomObject>
    <label>Staging Quotation Request</label>
    <nameField>
        <displayFormat>SQRN-{0000}</displayFormat>
        <label>Staging Quotation Request Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Staging Quotation Request</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/ETT_Staging_Quotation_Request__c/fields/ETT_Approve_Stage__c.field-meta.xml
<CustomField>
    <fullName>ETT_Approve_Stage__c</fullName>
    <label>Approve Stage</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>New</fullName>
                <default>true</default>
                <label>New</label>
            </value>
            <value>
                <fullName>Pending for Sale Team Approval</fullName>
            </value>
            <value>
                <fullName>Pending for FM Approval</fullName>
            </value>
            <value>
                <fullName>Pending for HOO Approval</fullName>
            </value>
            <value>
                <fullName>Qualified</fullName>
            </value>
            <value>
                <fullName>Rejected</fullName>
            </value>
            <value>
                <fullName>Resubmit</fullName>
            </value>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>Recall</fullName>
                <isActive>false</isActive>
                <label>Recall</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/ETT_Staging_Quotation_Request__c/fields/ETT_FM_Price_Acceptance__c.field-meta.xml
<CustomField>
    <fullName>ETT_FM_Price_Acceptance__c</fullName>
    <defaultValue>false</defaultValue>
    <label>FM Price Acceptance</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/objects/ETT_Staging_Quotation_Request__c/fields/ETT_HOO_Price_Acceptance__c.field-meta.xml
<CustomField>
    <fullName>ETT_HOO_Price_Acceptance__c</fullName>
    <defaultValue>false</defaultValue>
    <label>HOO Price Acceptance</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/objects/ETT_Staging_Quotation_Request__c/fields/ETT_Lead__c.field-meta.xml
<CustomField>
    <fullName>ETT_Lead__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Lead</label>
    <referenceTo>Lead</referenceTo>
    <relationshipLabel>Staging Quotation Request</relationshipLabel>
    <relationshipName>Staging_Quotation_Request</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/ETT_Staging_Quotation_Request__c/fields/ETT_Purchase_Price__c.field-meta.xml
<CustomField>
    <fullName>ETT_Purchase_Price__c</fullName>
    <label>Purchase Price</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

unpackaged/main/default/objects/ETT_Staging_Quotation_Request__c/fields/ETT_Tyre_Life__c.field-meta.xml
<CustomField>
    <fullName>ETT_Tyre_Life__c</fullName>
    <label>Tyre Life</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>New</fullName>
            </value>
            <value>
                <fullName>Retread 1</fullName>
            </value>
            <value>
                <fullName>Retread 2</fullName>
            </value>
            <value>
                <fullName>Retread 3</fullName>
            </value>
            <value>
                <fullName>Retread 4</fullName>
            </value>
            <value>
                <fullName>Retread 5</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Lead/fields/Duplicate_Lead__c.field-meta.xml
<CustomField>
    <fullName>Duplicate_Lead__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Mark it as Duplicate lead when it matches  - Existing Account or  Contact.</description>
    <label>Duplicate Lead</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/objects/Lead/fields/ETSALES_Country_Code_Company__c.field-meta.xml
<CustomField>
    <fullName>ETSALES_Country_Code_Company__c</fullName>
    <label>Ph Country Code</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>ISD_Country_Code</valueSetName>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Lead/fields/ETSALES_ISD_Country_Code_Contact__c.field-meta.xml
<CustomField>
    <fullName>ETSALES_ISD_Country_Code_Contact__c</fullName>
    <label>Mob Country Code</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Aland Islands(+358)</fullName>
            </value>
            <value>
                <fullName>Albania(+355)</fullName>
            </value>
            <value>
                <fullName>Algeria(+213)</fullName>
            </value>
            <value>
                <fullName>American Samoa(+1-684)</fullName>
            </value>
            <value>
                <fullName>Angola(+244)</fullName>
            </value>
            <value>
                <fullName>Anguilla(+1-264)</fullName>
            </value>
            <value>
                <fullName>Antarctica(+672)</fullName>
            </value>
            <value>
                <fullName>Antigua and Barbuda(+1-268)</fullName>
            </value>
            <value>
                <fullName>Argentina(+54)</fullName>
            </value>
            <value>
                <fullName>Armenia(+374)</fullName>
            </value>
            <value>
                <fullName>Aruba(+297)</fullName>
            </value>
            <value>
                <fullName>Australia(+61)</fullName>
            </value>
            <value>
                <fullName>Austria(+43)</fullName>
            </value>
            <value>
                <fullName>Azerbaijan(+994)</fullName>
            </value>
            <value>
                <fullName>Bahamas(+1-242)</fullName>
            </value>
            <value>
                <fullName>Bahrain(+973)</fullName>
            </value>
            <value>
                <fullName>Bangladesh(+880)</fullName>
            </value>
            <value>
                <fullName>Barbados(+1-246)</fullName>
            </value>
            <value>
                <fullName>Belarus(+375)</fullName>
            </value>
            <value>
                <fullName>Belgium(+32)</fullName>
            </value>
            <value>
                <fullName>Belize(+501)</fullName>
            </value>
            <value>
                <fullName>Benin(+229)</fullName>
            </value>
            <value>
                <fullName>Bermuda(+1-441)</fullName>
            </value>
            <value>
                <fullName>Bhutan(+975)</fullName>
            </value>
            <value>
                <fullName>Bolivia(+591)</fullName>
            </value>
            <value>
                <fullName>Bosnia and Herzegovina(+387)</fullName>
            </value>
            <value>
                <fullName>Botswana(+267)</fullName>
            </value>
            <value>
                <fullName>Bouvet Island(+47)</fullName>
            </value>
            <value>
                <fullName>Brazil(+55)</fullName>
            </value>
            <value>
                <fullName>British Indian Ocean Territory(+246)</fullName>
            </value>
            <value>
                <fullName>UAE(+971)</fullName>
                <default>true</default>
                <label>UAE(+971)</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Lead/fields/ETSALES_Lead_Created__c.field-meta.xml
<CustomField>
    <fullName>ETSALES_Lead_Created__c</fullName>
    <defaultValue>true</defaultValue>
    <label>Lead Created</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/objects/Lead/fields/ETT_Chamber_of_Comm_Cert_Expiry_Date__c.field-meta.xml
<CustomField>
    <fullName>ETT_Chamber_of_Comm_Cert_Expiry_Date__c</fullName>
    <description>Customer chamber of commerce certificate expiry date</description>
    <encryptionScheme>None</encryptionScheme>
    <label>Chamber of Comm. Cert Expiry Date</label>
    <type>Date</type>
</CustomField>

unpackaged/main/default/objects/Lead/fields/ETT_Emirates_Id__c.field-meta.xml
<CustomField>
    <fullName>ETT_Emirates_Id__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Emirates Id</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Lead/fields/ETT_Final_Rejection__c.field-meta.xml
<CustomField>
    <fullName>ETT_Final_Rejection__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Final Rejection</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/objects/Lead/fields/ETT_Fleet_Inspection_Required__c.field-meta.xml
<CustomField>
    <fullName>ETT_Fleet_Inspection_Required__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Fleet inspection required for the customer</description>
    <label>Fleet Inspection Required</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/objects/Lead/fields/ETT_Government__c.field-meta.xml
<CustomField>
    <fullName>ETT_Government__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Customer Legal Status - Government</description>
    <label>Government</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/objects/Lead/fields/ETT_isSupplierConvert__c.field-meta.xml
<CustomField>
    <fullName>ETT_isSupplierConvert__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Is Auto Convert ?</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/objects/Lead/fields/ETT_Lead_Approval_Stage__c.field-meta.xml
<CustomField>
    <fullName>ETT_Lead_Approval_Stage__c</fullName>
    <label>Lead Approval Stage</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>New</fullName>
                <default>true</default>
                <label>New</label>
            </value>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>Rejected</fullName>
            </value>
            <value>
                <fullName>Recall</fullName>
            </value>
            <value>
                <fullName>Pending for Approval</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Lead/fields/ETT_LLC__c.field-meta.xml
<CustomField>
    <fullName>ETT_LLC__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Customer Legal Status - LLC</description>
    <label>LLC</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/objects/Lead/fields/ETT_Party_Type__c.field-meta.xml
<CustomField>
    <fullName>ETT_Party_Type__c</fullName>
    <label>Party Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Customer</fullName>
            </value>
            <value>
                <fullName>Internal Private Project</fullName>
            </value>
            <value>
                <fullName>Internal Project</fullName>
            </value>
            <value>
                <fullName>Supplier</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Lead/fields/ETT_Payment_Type__c.field-meta.xml
<CustomField>
    <fullName>ETT_Payment_Type__c</fullName>
    <label>Payment Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Credit</fullName>
            </value>
            <value>
                <fullName>Cash</fullName>
                <default>true</default>
                <label>Cash</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Lead/fields/ETT_Scrap_Inspection_Required__c.field-meta.xml
<CustomField>
    <fullName>ETT_Scrap_Inspection_Required__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Scrap inspection required by the customer</description>
    <label>Scrap Inspection Required</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/objects/Lead/fields/ETT_Test_Tyre_Required__c.field-meta.xml
<CustomField>
    <fullName>ETT_Test_Tyre_Required__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Test Tyre Required</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/objects/Lead/fields/ETT_Trade_License_Number__c.field-meta.xml
<CustomField>
    <fullName>ETT_Trade_License_Number__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Trade License Number</label>
    <length>15</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Lead/fields/ETT_Trade_Licenses_Expiry_Date__c.field-meta.xml
<CustomField>
    <fullName>ETT_Trade_Licenses_Expiry_Date__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Trade Licenses Expiry Date</label>
    <type>Date</type>
</CustomField>

unpackaged/main/default/objects/Lead/fields/ETT_VAT_TRN__c.field-meta.xml
<CustomField>
    <fullName>ETT_VAT_TRN__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>TRN</label>
    <length>15</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/globalValueSets/ISD_Country_Code.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Aland Islands(+358)</fullName>
    </customValue>
    <customValue>
        <fullName>Albania(+355)</fullName>
    </customValue>
    <customValue>
        <fullName>Algeria(+213)</fullName>
    </customValue>
    <customValue>
        <fullName>American Samoa(+1-684)</fullName>
    </customValue>
    <customValue>
        <fullName>Angola(+244)</fullName>
    </customValue>
    <customValue>
        <fullName>Anguilla(+1-264)</fullName>
    </customValue>
    <customValue>
        <fullName>Antarctica(+672)</fullName>
    </customValue>
    <customValue>
        <fullName>Antigua and Barbuda(+1-268)</fullName>
    </customValue>
    <customValue>
        <fullName>Argentina(+54)</fullName>
    </customValue>
    <customValue>
        <fullName>Armenia(+374)</fullName>
    </customValue>
    <customValue>
        <fullName>Aruba(+297)</fullName>
    </customValue>
    <customValue>
        <fullName>Australia(+61)</fullName>
    </customValue>
    <customValue>
        <fullName>Austria(+43)</fullName>
    </customValue>
    <customValue>
        <fullName>Azerbaijan(+994)</fullName>
    </customValue>
    <customValue>
        <fullName>Bahamas(+1-242)</fullName>
    </customValue>
    <customValue>
        <fullName>Bahrain(+973)</fullName>
    </customValue>
    <customValue>
        <fullName>Bangladesh(+880)</fullName>
    </customValue>
    <customValue>
        <fullName>Barbados(+1-246)</fullName>
    </customValue>
    <customValue>
        <fullName>Belarus(+375)</fullName>
    </customValue>
    <customValue>
        <fullName>Belgium(+32)</fullName>
    </customValue>
    <customValue>
        <fullName>Belize(+501)</fullName>
    </customValue>
    <customValue>
        <fullName>Benin(+229)</fullName>
    </customValue>
    <customValue>
        <fullName>Bermuda(+1-441)</fullName>
    </customValue>
    <customValue>
        <fullName>Bhutan(+975)</fullName>
    </customValue>
    <customValue>
        <fullName>Bolivia(+591)</fullName>
    </customValue>
    <customValue>
        <fullName>Bosnia and Herzegovina(+387)</fullName>
    </customValue>
    <customValue>
        <fullName>Botswana(+267)</fullName>
    </customValue>
    <customValue>
        <fullName>Bouvet Island(+47)</fullName>
    </customValue>
    <customValue>
        <fullName>Brazil(+55)</fullName>
    </customValue>
    <customValue>
        <fullName>British Indian Ocean Territory(+246)</fullName>
    </customValue>
    <customValue>
        <fullName>UAE(+971)</fullName>
        <default>true</default>
        <label>UAE(+971)</label>
    </customValue>
    <masterLabel>ISD Country Code</masterLabel>
</GlobalValueSet>

unpackaged/main/default/classes/ETT_LeadConvertProcessControllerTest.cls
@isTest
public class ETT_LeadConvertProcessControllerTest {
    
    @isTest
    public static void testForleadConvertProcessTestCase1(){
        Id devRecordTypeId = Schema.SObjectType.lead.getRecordTypeInfosByName().get('Tyre - Refurbishing Services').getRecordTypeId();
        Lead obj = new Lead(
            recordtypeId = devRecordTypeId,
            LastName = 'Aadil',
            Company = 'supcshtst thirtytwo',
            Street = 'Dubai',
            Phone = '+971 256364545',
            MobilePhone = '+971 254563645',
            Status = 'New',
            CurrencyIsoCode = 'AED',
            HasOptedOutOfEmail = false,
            IsUnreadByOwner = false,
            DoNotCall = false,
            HasOptedOutOfFax = false,
            pi__Needs_Score_Synced__c = false,
            pi__pardot_hard_bounced__c = false,
            et4ae5__HasOptedOutOfMobile__c = false,
            et4ae5__Mobile_Country_Code__c = 'US',
            Duplicate_Lead__c = false,
            ETSALES_Country_Code_Company__c = 'UAE(+971)',
            ETSALES_ISD_Country_Code_Contact__c = 'UAE(+971)',
            ETSALES_Lead_Created__c = true,
            ETT_Fleet_Inspection_Required__c = false,
            ETT_Government__c = false,
            ETT_LLC__c = false,
            ETT_Lead_Approval_Stage__c = 'New',
            ETT_Party_Type__c = 'Supplier',
            ETT_Payment_Type__c = 'Cash',
            ETT_Scrap_Inspection_Required__c = false,
            ETT_Test_Tyre_Required__c = false,
            ETT_Trade_License_Number__c = '567876546789767',
            ETT_Trade_Licenses_Expiry_Date__c = System.today()+8,
            ETT_Chamber_of_Comm_Cert_Expiry_Date__c= System.today()+8,
            ETT_VAT_TRN__c = '657656343743322',
            ETT_isSupplierConvert__c = false,
            ETT_Final_Rejection__c = false);
        
        insert obj;
        
        obj.Status = 'Qualified';
        update obj;
        
        ETT_Staging_Quotation_Request__c ett_staging_quotation_request = new ETT_Staging_Quotation_Request__c(
            
            CurrencyIsoCode = 'AED',
            ETT_Accept_Quotation__c = false,
            ETT_Approve_Stage__c = 'Rejected',
            ETT_IS_Approved__c = false,
            ETT_Lead__c = obj.id,
            ETT_Max_Range__c = 175.0,
            ETT_Min_Range__c = 140.0,
            ETT_Purchase_Price__c = 0.0,
            ETT_Quantity__c = 1.0,
            ETT_Tyre_Life__c = 'New',
            ETT_HOO_Price_Acceptance__c = false,
            ETT_FM_Price_Acceptance__c = false);
        
        insert ett_staging_quotation_request;
        PageReference pageRef = Page.ETT_LeadConvertPage;
        Test.setCurrentPage(pageRef);
        
        pageRef.getParameters().put('Id', String.valueOf(obj.Id));
        ApexPages.StandardController sc = new ApexPages.StandardController(obj);
        Test.startTest();
        ETT_LeadConvertProcessController ettLeadInstance = new ETT_LeadConvertProcessController(sc);
        Pagereference pgr = ettLeadInstance.leadConvertProcess();
        Test.stopTest();
        System.assert(pgr != null);
        System.assertEquals('Hello', 'Hello');
    }
    
    @isTest
    public static void testForleadConvertProcessTestCase2(){
        Id devRecordTypeId = Schema.SObjectType.lead.getRecordTypeInfosByName().get('Tyre - Cash Supplier').getRecordTypeId();
        Lead obj = new Lead(
            recordtypeId = devRecordTypeId,
            LastName = 'Aadil',
            Company = 'supcshtst thirtytwo',
            Street = 'Dubai',
            Phone = '+971 256364545',
            MobilePhone = '+971 254563645',
            Status = 'New',
            CurrencyIsoCode = 'AED',
            HasOptedOutOfEmail = false,
            IsUnreadByOwner = false,
            DoNotCall = false,
            HasOptedOutOfFax = false,
            pi__Needs_Score_Synced__c = false,
            pi__pardot_hard_bounced__c = false,
            et4ae5__HasOptedOutOfMobile__c = false,
            et4ae5__Mobile_Country_Code__c = 'US',
            Duplicate_Lead__c = false,
            ETSALES_Country_Code_Company__c = 'UAE(+971)',
            ETSALES_ISD_Country_Code_Contact__c = 'UAE(+971)',
            ETSALES_Lead_Created__c = true,
            ETT_Fleet_Inspection_Required__c = false,
            ETT_Government__c = false,
            ETT_LLC__c = false,
            ETT_Lead_Approval_Stage__c = 'New',
            ETT_Party_Type__c = 'Supplier',
            ETT_Payment_Type__c = 'Cash',
            ETT_Scrap_Inspection_Required__c = false,
            ETT_Test_Tyre_Required__c = false,
            ETT_Trade_License_Number__c = '567876546789767',
            ETT_Trade_Licenses_Expiry_Date__c = System.today()+8,
            ETT_Chamber_of_Comm_Cert_Expiry_Date__c= System.today()+8,
            ETT_VAT_TRN__c = '657656343743322',
            ETT_isSupplierConvert__c = false,
            ETT_Final_Rejection__c = false);
        
        insert obj;
        obj.Status = 'Qualified';
        update obj;
        
        PageReference pageRef = Page.ETT_LeadConvertPage;
        Test.setCurrentPage(pageRef);
        
        pageRef.getParameters().put('Id', String.valueOf(obj.Id));
        ApexPages.StandardController sc = new ApexPages.StandardController(obj);
        Test.startTest();
        ETT_LeadConvertProcessController ettLeadInstance = new ETT_LeadConvertProcessController(sc);
        Pagereference pgr = ettLeadInstance.leadConvertProcess();
        Test.stopTest();
        System.assert(pgr != null);
    }
    @isTest
    public static void testForleadConvertProcessTestCase3(){
        Id devRecordTypeId = Schema.SObjectType.lead.getRecordTypeInfosByName().get('Tyre Cash Individual').getRecordTypeId();
        Lead obj = new Lead(
            recordtypeId = devRecordTypeId,
            LastName = 'Aadil',
            ETT_Emirates_Id__c = '784-1254-8547845-4',
            Company = 'supcshtst thirtytwo',
            Street = 'Dubai',
            Phone = '+971 256364545',
            MobilePhone = '+971 254563645',
            Status = 'New',
            CurrencyIsoCode = 'AED',
            HasOptedOutOfEmail = false,
            IsUnreadByOwner = false,
            DoNotCall = false,
            HasOptedOutOfFax = false,
            pi__Needs_Score_Synced__c = false,
            pi__pardot_hard_bounced__c = false,
            et4ae5__HasOptedOutOfMobile__c = false,
            et4ae5__Mobile_Country_Code__c = 'US',
            Duplicate_Lead__c = false,
            ETSALES_Country_Code_Company__c = 'UAE(+971)',
            ETSALES_ISD_Country_Code_Contact__c = 'UAE(+971)',
            ETSALES_Lead_Created__c = true,
            ETT_Fleet_Inspection_Required__c = false,
            ETT_Government__c = false,
            ETT_LLC__c = false,
            ETT_Lead_Approval_Stage__c = 'New',
            ETT_Party_Type__c = 'Supplier',
            ETT_Payment_Type__c = 'Cash',
            ETT_Scrap_Inspection_Required__c = false,
            ETT_Test_Tyre_Required__c = false,
            ETT_Trade_License_Number__c = '567876546789767',
            ETT_Trade_Licenses_Expiry_Date__c = System.today()+8,
            ETT_Chamber_of_Comm_Cert_Expiry_Date__c= System.today()+8,
            ETT_VAT_TRN__c = '657656343743322',
            ETT_isSupplierConvert__c = false,
            ETT_Final_Rejection__c = false);
        
        insert obj;
obj.Status = 'Qualified';
update obj;
        
        PageReference pageRef = Page.ETT_LeadConvertPage;
        Test.setCurrentPage(pageRef);
        
        pageRef.getParameters().put('Id', String.valueOf(obj.Id));
        ApexPages.StandardController sc = new ApexPages.StandardController(obj);
        Test.startTest();
        ETT_LeadConvertProcessController ettLeadInstance = new ETT_LeadConvertProcessController(sc);
        Pagereference pgr = ettLeadInstance.leadConvertProcess();
        Test.stopTest();
        System.assert(pgr != null);
    }
    @isTest
    public static void testForleadConvertProcessTestCase4(){
        Id devRecordTypeId = Schema.SObjectType.lead.getRecordTypeInfosByName().get('Tyre - Credit/B2B Supplier').getRecordTypeId();
        Lead obj = new Lead(
            recordtypeId = devRecordTypeId,
            LastName = 'Aadil',
            Company = 'supcshtst thirtytwo',
            Street = 'Dubai',
            Phone = '+971 256364545',
            MobilePhone = '+971 254563645',
            Status = 'New',
            CurrencyIsoCode = 'AED',
            HasOptedOutOfEmail = false,
            IsUnreadByOwner = false,
            DoNotCall = false,
            HasOptedOutOfFax = false,
            pi__Needs_Score_Synced__c = false,
            pi__pardot_hard_bounced__c = false,
            et4ae5__HasOptedOutOfMobile__c = false,
            et4ae5__Mobile_Country_Code__c = 'US',
            Duplicate_Lead__c = false,
            ETSALES_Country_Code_Company__c = 'UAE(+971)',
            ETSALES_ISD_Country_Code_Contact__c = 'UAE(+971)',
            ETSALES_Lead_Created__c = true,
            ETT_Fleet_Inspection_Required__c = false,
            ETT_Government__c = false,
            ETT_LLC__c = false,
            ETT_Lead_Approval_Stage__c = 'New',
            ETT_Party_Type__c = 'Supplier',
            ETT_Payment_Type__c = 'Cash',
            ETT_Scrap_Inspection_Required__c = false,
            ETT_Test_Tyre_Required__c = false,
            ETT_Trade_License_Number__c = '567876546789767',
            ETT_Trade_Licenses_Expiry_Date__c = System.today()+8,
            ETT_Chamber_of_Comm_Cert_Expiry_Date__c= System.today()+8,
            ETT_VAT_TRN__c = '657656343743322',
            ETT_isSupplierConvert__c = false,
            ETT_Final_Rejection__c = false);
        
        insert obj;
        obj.Status = 'Qualified';
        update obj;
        
        PageReference pageRef = Page.ETT_LeadConvertPage;
        Test.setCurrentPage(pageRef);
        
        pageRef.getParameters().put('Id', String.valueOf(obj.Id));
        ApexPages.StandardController sc = new ApexPages.StandardController(obj);
        Test.startTest();
        ETT_LeadConvertProcessController ettLeadInstance = new ETT_LeadConvertProcessController(sc);
        Pagereference pgr = ettLeadInstance.leadConvertProcess();
        Test.stopTest();
        System.assert(pgr != null);
    }
}