unpackaged/main/default/objects/ETST_Payment__c/ETST_Payment__c.object-meta.xml
<CustomObject>
    <label>Payment</label>
    <nameField>
        <displayFormat>TRN-{00000}</displayFormat>
        <label>ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Payments</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/ETST_Payment__c/fields/ETI_IsUpdatedByBatch__c.field-meta.xml
<CustomField>
    <fullName>ETI_IsUpdatedByBatch__c</fullName>
    <defaultValue>false</defaultValue>
    <label>IsUpdatedByBatch</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/objects/ETST_Payment__c/fields/ETST_Payment_State__c.field-meta.xml
<CustomField>
    <fullName>ETST_Payment_State__c</fullName>
    <defaultValue>IF( $RecordType.DeveloperName = &#39;On_Premise_Payment&#39; , &#39;SUCCESS&#39;, &#39;&#39;)</defaultValue>
    <encryptionScheme>None</encryptionScheme>
    <label>Payment State</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/ETST_Payment__c/fields/ExternalID__c.field-meta.xml
<CustomField>
    <fullName>ExternalID__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <externalId>true</externalId>
    <label>ExternalID</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/classes/ETI_BulkPayment_AWAIT_3DS_BatchTest.cls
@isTest
public class ETI_BulkPayment_AWAIT_3DS_BatchTest {
    
    
    public static testmethod void AwaitBatch(){
        
        ETST_Payment__c et = new ETST_Payment__c();
        et.ETST_Payment_State__c ='AWAIT_3DS';
        et.ETI_IsUpdatedByBatch__c =false;
        et.ExternalId__c ='0000';
        
        insert et;
        test.startTest();
        ETI_BulkPayment_AWAIT_3DS_Batch ba = new ETI_BulkPayment_AWAIT_3DS_Batch();
        Database.executeBatch(ba,1);
        
        test.stopTest();
    }
    

}