unpackaged/main/default/objects/ETVIN_Vehicle_Insurance__c/ETVIN_Vehicle_Insurance__c.object-meta.xml
<CustomObject>
    <description>Vehicle Insurance</description>
    <label>Vehicle Insurance Policy</label>
    <nameField>
        <displayFormat>VI-{0000}</displayFormat>
        <label>Insurance Ref Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Vehicle Insurance Policies</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/ETVIN_Vehicle_Insurance__c/fields/Amount__c.field-meta.xml
<CustomField>
    <fullName>Amount__c</fullName>
    <label>Amount</label>
    <precision>18</precision>
    <scale>4</scale>
    <type>Number</type>
</CustomField>

unpackaged/main/default/objects/ETVIN_Vehicle_Insurance__c/fields/ETVIN_Insurance_Company__c.field-meta.xml
<CustomField>
    <fullName>ETVIN_Insurance_Company__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Insurance Company</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Vehicle Insurance Policies</relationshipLabel>
    <relationshipName>Vehicle_Insurances</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/ETVIN_Vehicle_Insurance__c/fields/ETVIN_TCF_No__c.field-meta.xml
<CustomField>
    <fullName>ETVIN_TCF_No__c</fullName>
    <label>TCF No</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

unpackaged/main/default/objects/ETVIN_Vehicle_Insurance__c/fields/Vehicle__c.field-meta.xml
<CustomField>
    <fullName>Vehicle__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Vehicle</label>
    <referenceTo>Vehicle_Master__c</referenceTo>
    <relationshipLabel>Vehicle Insurance Policies</relationshipLabel>
    <relationshipName>Vehicle_Insurance_Policies</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Vehicle__c/Vehicle__c.object-meta.xml
<CustomObject>
    <label>Pricing Vehicle Request</label>
    <nameField>
        <displayFormat>VN-{0000}</displayFormat>
        <label>Vehicle Request Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Vehicle Requests</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Vehicle_Master__c/Vehicle_Master__c.object-meta.xml
<CustomObject>
    <description>Emirates Transport Oracle Vehicle Master</description>
    <label>ET Vehicle Master</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Vehicle No.</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>ET Vehicle Masters</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Vehicle_Master__c/fields/TC_Number__c.field-meta.xml
<CustomField>
    <fullName>TC_Number__c</fullName>
    <label>TC Number</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

unpackaged/main/default/classes/ETVIN_NewPolicyCreationTrgHandler.cls
/***
Class       : ETVIN_NewPolicyCreationTrgHandler
Author      : 
Description : 
TestClass  : ETVIN_NewPolicyCreationTrgHandlerTest
----------------------------------------------------------------------------------------------------------------
-- History --
----------------------------------------------------------------------------------------------------------------
Sr.No.  version_DevInitials        Date          updated by             Details							

****************************************************************************************************************/
public class ETVIN_NewPolicyCreationTrgHandler {
    
    public static void createNewVehPolicy(list<Vehicle_Master__c> trgVal){
        list<ETVIN_Vehicle_Insurance__c> newIns  = new list<ETVIN_Vehicle_Insurance__c>();
        for(Vehicle_Master__c vm: trgVal){
            ETVIN_Vehicle_Insurance__c vi = new ETVIN_Vehicle_Insurance__c();
            vi.Vehicle__c = vm.Id;
            vi.ETVIN_TCF_No__c = vm.TC_Number__c;
            vi.Amount__c = vm.Amount__c;
            newIns.add(vi);          
        }
        if(newIns != null && newIns.size()>0){
            try {
                insert newIns;
            }
            catch (Exception e) {
                
                system.debug('Something went wrong: '+ e.getMessage());    
            }
        } 
    }
    
    //Added by Arunsarathy on 05.03.2024
    public static void handleAfterUpdate(List<Vehicle_Master__c> newVehicles, Map<Id, Vehicle_Master__c> oldMap) {
        Map<Id, Boolean> alreadyProcessedMap = new Map<Id, Boolean>();
        
        for (Vehicle_Master__c vehicle : newVehicles) {
            Vehicle_Master__c oldVehicle = oldMap.get(vehicle.Id);
            
            if (vehicle.TC_Number__c != null && (oldVehicle == null || oldVehicle.TC_Number__c != vehicle.TC_Number__c)) {
                // Check if trigger has already executed for this record
                if (!alreadyProcessedMap.containsKey(vehicle.Id)) {
                    alreadyProcessedMap.put(vehicle.Id, true);
                    processVehicle(vehicle);
                }
            }
        }
    }

    // Method to process each vehicle
    public static void processVehicle(Vehicle_Master__c vehicle) {
        // Check if a related ETVIN_Vehicle_Insurance__c record already exists
        Integer existingInsuranceCount = [SELECT COUNT() FROM ETVIN_Vehicle_Insurance__c WHERE Vehicle__c = :vehicle.Id];
        if (existingInsuranceCount == 0) {
            // Call method to create a new ETVIN_Vehicle_Insurance__c record if condition is met
            createNewVehPolicy(new List<Vehicle_Master__c>{vehicle});
        } else {
            // Update the TC_Number__c field in the existing ETVIN_Vehicle_Insurance__c record
            updateExistingInsurance(vehicle);
        }
    }

    // Method to update existing ETVIN_Vehicle_Insurance__c record
    public static void updateExistingInsurance(Vehicle_Master__c vehicle) {
        ETVIN_Vehicle_Insurance__c existingInsurance = [SELECT Id, ETVIN_TCF_No__c, ETVIN_Insurance_Company__c FROM ETVIN_Vehicle_Insurance__c WHERE Vehicle__c = :vehicle.Id LIMIT 1];
        if(existingInsurance.ETVIN_Insurance_Company__c != null){ 
        existingInsurance.ETVIN_TCF_No__c = vehicle.TC_Number__c;
        }
        update existingInsurance;
    }
    //changes end by Arunsarathy
}