unpackaged/main/default/objects/AssignedResource/fields/ETT_Vehicle_Detail__c.field-meta.xml
<CustomField>
    <fullName>ETT_Vehicle_Detail__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Vehicle Detail</label>
    <referenceTo>ETT_Vehicle_Details__c</referenceTo>
    <relationshipLabel>Assigned Resources</relationshipLabel>
    <relationshipName>Assigned_Resources</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/ETT_Collection_Card__c/ETT_Collection_Card__c.object-meta.xml
<CustomObject>
    <description>This object is to track the vehicle information and as well as driver information with the help of google map.</description>
    <label>Collection Card</label>
    <nameField>
        <displayFormat>CC-{0000}</displayFormat>
        <label>Collection Card Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Collection Cards</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/ETT_Collection_Card__c/fields/ETT_Account__c.field-meta.xml
<CustomField>
    <fullName>ETT_Account__c</fullName>
    <formula>ETT_Service_Appointment__r.Account.Name</formula>
    <label>Account</label>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/ETT_Collection_Card__c/fields/ETT_Accounts__c.field-meta.xml
<CustomField>
    <fullName>ETT_Accounts__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Collection Cards</relationshipLabel>
    <relationshipName>Collection_Cards</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/ETT_Collection_Card__c/fields/ETT_Collection_Status__c.field-meta.xml
<CustomField>
    <fullName>ETT_Collection_Status__c</fullName>
    <label>Collection Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>New</fullName>
            </value>
            <value>
                <fullName>In Progress</fullName>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
            <value>
                <fullName>Accepted</fullName>
            </value>
            <value>
                <fullName>Rejected</fullName>
            </value>
            <value>
                <fullName>Scheduled</fullName>
            </value>
            <value>
                <fullName>Inspection Cards Created</fullName>
            </value>
            <value>
                <fullName>Inspection Completed</fullName>
            </value>
            <value>
                <fullName>Job Card Created</fullName>
            </value>
            <value>
                <fullName>Check and Report</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/ETT_Collection_Card__c/fields/ETT_Driver__c.field-meta.xml
<CustomField>
    <fullName>ETT_Driver__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Driver</label>
    <referenceTo>ServiceResource</referenceTo>
    <relationshipLabel>Collection Cards (Driver)</relationshipLabel>
    <relationshipName>Collection_Cards1</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/ETT_Collection_Card__c/fields/ETT_Inspection_Done__c.field-meta.xml
<CustomField>
    <fullName>ETT_Inspection_Done__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Inspection Done</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/objects/ETT_Collection_Card__c/fields/ETT_Opportunity__c.field-meta.xml
<CustomField>
    <fullName>ETT_Opportunity__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Collection Cards</relationshipLabel>
    <relationshipName>Collection_Cards</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/ETT_Collection_Card__c/fields/ETT_Service_Appointment__c.field-meta.xml
<CustomField>
    <fullName>ETT_Service_Appointment__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Service Appointment</label>
    <referenceTo>ServiceAppointment</referenceTo>
    <relationshipLabel>Collection Cards</relationshipLabel>
    <relationshipName>Collection_Cards</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/ETT_Collection_Card__c/fields/ETT_Status__c.field-meta.xml
<CustomField>
    <fullName>ETT_Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Collection Stage</fullName>
            </value>
            <value>
                <fullName>Inspection Stage</fullName>
            </value>
            <value>
                <fullName>Job Card Stage</fullName>
            </value>
            <value>
                <fullName>Delivery Stage</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/ETT_Collection_Card__c/fields/ETT_Vehicle_Detail__c.field-meta.xml
<CustomField>
    <fullName>ETT_Vehicle_Detail__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Vehicle Detail</label>
    <referenceTo>ETT_Vehicle_Details__c</referenceTo>
    <relationshipLabel>Collection Cards</relationshipLabel>
    <relationshipName>Collection_Cards</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/ETT_Delivery_Line_Item__c/ETT_Delivery_Line_Item__c.object-meta.xml
<CustomObject>
    <label>Delivery Line Item</label>
    <nameField>
        <displayFormat>DLN-{0000}</displayFormat>
        <label>Delivery Line Item Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Delivery Line Items</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/ETT_Delivery_Line_Item__c/fields/ETT_Collection_Card__c.field-meta.xml
<CustomField>
    <fullName>ETT_Collection_Card__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Collection Card</label>
    <referenceTo>ETT_Collection_Card__c</referenceTo>
    <relationshipLabel>Delivery Line Items</relationshipLabel>
    <relationshipName>Delivery_Line_Items</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/ETT_Delivery_Line_Item__c/fields/ETT_Delivery_Note__c.field-meta.xml
<CustomField>
    <fullName>ETT_Delivery_Note__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Delivery Note</label>
    <referenceTo>ETT_Delivery_Note__c</referenceTo>
    <relationshipLabel>Delivery Line Items</relationshipLabel>
    <relationshipName>Delivery_Line_Items</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/ETT_Delivery_Line_Item__c/fields/ETT_Inspection_Card__c.field-meta.xml
<CustomField>
    <fullName>ETT_Inspection_Card__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Tyre Inspection Card</label>
    <referenceTo>ETT_Inspection_Card__c</referenceTo>
    <relationshipLabel>Delivery Line Items</relationshipLabel>
    <relationshipName>Delivery_Line_Items</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/ETT_Delivery_Note__c/ETT_Delivery_Note__c.object-meta.xml
<CustomObject>
    <label>Delivery Note</label>
    <nameField>
        <displayFormat>DNN-{0000}</displayFormat>
        <label>Delivery Note Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Delivery Notes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/ETT_Delivery_Note__c/fields/ETT_Account__c.field-meta.xml
<CustomField>
    <fullName>ETT_Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Delivery Notes</relationshipLabel>
    <relationshipName>Delivery_Notes</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/ETT_Delivery_Note__c/fields/ETT_Collection_Card__c.field-meta.xml
<CustomField>
    <fullName>ETT_Collection_Card__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Collection Card</label>
    <referenceTo>ETT_Collection_Card__c</referenceTo>
    <relationshipLabel>Delivery Notes</relationshipLabel>
    <relationshipName>Delivery_Notes</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/ETT_Delivery_Note__c/fields/ETT_Is_Delivery_Appointment_Booked__c.field-meta.xml
<CustomField>
    <fullName>ETT_Is_Delivery_Appointment_Booked__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Is Delivery Appointment Booked</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/objects/ETT_Delivery_Note__c/fields/ETT_Service_Appointment__c.field-meta.xml
<CustomField>
    <fullName>ETT_Service_Appointment__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Service Appointment</label>
    <referenceTo>ServiceAppointment</referenceTo>
    <relationshipLabel>Delivery Notes</relationshipLabel>
    <relationshipName>Delivery_Notes</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/ETT_Driver__c/ETT_Driver__c.object-meta.xml
<CustomObject>
    <label>Driver</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>First Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Drivers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/ETT_Driver__c/fields/ETT_Collection_Card__c.field-meta.xml
<CustomField>
    <fullName>ETT_Collection_Card__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Collection Card</label>
    <referenceTo>ETT_Collection_Card__c</referenceTo>
    <relationshipLabel>Drivers</relationshipLabel>
    <relationshipName>Drivers</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/ETT_Inspection_Card__c/ETT_Inspection_Card__c.object-meta.xml
<CustomObject>
    <description>This is for inspection for the customer who has been requested orders.</description>
    <label>Tyre Inspection Card</label>
    <nameField>
        <displayFormat>IC-{0000}</displayFormat>
        <label>Inspection Card Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Tyre Inspection Cards</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/ETT_Inspection_Card__c/fields/ETT_Account__c.field-meta.xml
<CustomField>
    <fullName>ETT_Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipName>Inspection_Cards</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/ETT_Inspection_Card__c/fields/ETT_Collection_Card__c.field-meta.xml
<CustomField>
    <fullName>ETT_Collection_Card__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Collection Card</label>
    <referenceTo>ETT_Collection_Card__c</referenceTo>
    <relationshipName>Inspection_Cards</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/ETT_Inspection_Card__c/fields/ETT_Service_Appointment__c.field-meta.xml
<CustomField>
    <fullName>ETT_Service_Appointment__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Service Appointment</label>
    <referenceTo>ServiceAppointment</referenceTo>
    <relationshipName>Inspection_Cards</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/ETT_Inspection_Card__c/fields/ETT_Status__c.field-meta.xml
<CustomField>
    <fullName>ETT_Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Not Inspected</fullName>
                <default>true</default>
                <label>Not Inspected</label>
            </value>
            <value>
                <fullName>Accept</fullName>
            </value>
            <value>
                <fullName>Send Back</fullName>
            </value>
            <value>
                <fullName>Scrap</fullName>
            </value>
            <value>
                <fullName>Accepted/No Warranty</fullName>
            </value>
            <value>
                <fullName>Pending</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/ServiceAppointment/fields/ETT_Account__c.field-meta.xml
<CustomField>
    <fullName>ETT_Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account - Delete</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Service Appointments</relationshipLabel>
    <relationshipName>Service_Appointments</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/ServiceAppointment/fields/ETT_Delivery_Note__c.field-meta.xml
<CustomField>
    <fullName>ETT_Delivery_Note__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Delivery Note</label>
    <referenceTo>ETT_Delivery_Note__c</referenceTo>
    <relationshipLabel>Service Appointments</relationshipLabel>
    <relationshipName>Service_Appointments</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/ServiceAppointment/fields/ETT_Inspection_Card__c.field-meta.xml
<CustomField>
    <fullName>ETT_Inspection_Card__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Inspection Card</label>
    <referenceTo>ETT_Inspection_Card__c</referenceTo>
    <relationshipLabel>Service Appointments</relationshipLabel>
    <relationshipName>Service_Appointments</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/ServiceAppointment/fields/ETT_Opportunity__c.field-meta.xml
<CustomField>
    <fullName>ETT_Opportunity__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Service Appointments</relationshipLabel>
    <relationshipName>Service_Appointments</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/WorkOrder/fields/ETT_Opportunity__c.field-meta.xml
<CustomField>
    <fullName>ETT_Opportunity__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Work Orders</relationshipLabel>
    <relationshipName>Work_Orders</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/classes/ETT_DeliveryAppointmentController.cls
public class ETT_DeliveryAppointmentController {
    
    public Opportunity oppObj;
    public WorkOrder objWorkOrder{get;set;}
    public ServiceAppointment objServiceAppointment{get;set;}
    public AssignedResource objAssignedResource{get;set;}
    public boolean isSkipAppointment{get;set;}
    public boolean isDeliveryAppointment{get;set;}
    public Contact objContact{get;set;}
    public WorkType objWorkType{get;set;}
    public string DeliveryNote{get;set;}
    public string DeliveryNoteId{get;set;}
    public boolean isDeliveryAptBooked{get;set;}
    //public map<string,string> getMapFieldLabel{get;set;}
    public map<String,String> getMapFieldLabel {get;set;}
                    
    //Constructor to Prepare the Objects intiation
    public ETT_DeliveryAppointmentController(ApexPages.StandardController controller){
        
        getMapFieldLabel = new map<String,String>();
        
        //isSkipAppointment = false;
        oppObj = (Opportunity)controller.getRecord();
        System.debug(oppObj);
        
        objWorkOrder = new WorkOrder();
        objServiceAppointment = new ServiceAppointment();
        objAssignedResource = new AssignedResource();
        objWorkType = new WorkType();
        objContact = [select Id,LastName from Contact where AccountId=:oppObj.AccountId limit 1];
        list<WorkType> lstWorkTypes = [select id,Name from workType where RecordType.Name='Tyre - Cash Supplier' Order by Name Desc];
        if(lstWorkTypes!=null && lstWorkTypes.size()>0){
            for(WorkType objExistingWorkType :lstWorkTypes){
                if(objWorkType.Name!=''){ 
                    objWorkType = objExistingWorkType;
                }
            }
        }    
        
        //added by shweta
        Set<Id> collectionCardIdsSet = new Set<Id>();
        Set<Id> deliveryNoteIdsSet = new Set<Id>();        
        
        Id ccId, dnId;
        List<AggregateResult> lstCollectionCard = [SELECT count(Id) countofInspections, ETT_Collection_Card__c collectionCard,ETT_Status__c ettStatus
                                                   FROM ETT_Inspection_Card__c where ETT_Account__c = :oppObj.AccountId and ETT_Collection_Card__r.ETT_Inspection_Done__c=true group by ETT_Collection_Card__c,ETT_Status__c];
        
        if(lstCollectionCard!= null && lstCollectionCard.size() > 0){ 
            for(AggregateResult agg:lstCollectionCard){ 
                ccId = (Id)agg.get('collectionCard'); 
                collectionCardIdsSet.add(ccId);
            }
            System.debug('collectionCardIdsSet: '+collectionCardIdsSet);
            
            List<AggregateResult> objDLI = [SELECT count(Id) cid, ETT_Delivery_Note__c FROM ETT_Delivery_Line_Item__c where ETT_Collection_Card__c in :collectionCardIdsSet group by ETT_Delivery_Note__c];
            System.debug('objDLI: '+objDLI);
            
            for(AggregateResult agg:objDLI){ 
                dnId = (Id)agg.get('ETT_Delivery_Note__c'); 
                deliveryNoteIdsSet.add(dnId);
            }
            
            
            List<ETT_Delivery_Note__c> lstDeliveryNote = [SELECT Id, Name, ETT_Is_Delivery_Appointment_Booked__c FROM ETT_Delivery_Note__c where ETT_Is_Delivery_Appointment_Booked__c=false and Id in :deliveryNoteIdsSet];

            
           
            
            System.debug('lstDeliveryNote: '+lstDeliveryNote);
            for(ETT_Delivery_Note__c dn:lstDeliveryNote){
                DeliveryNote = dn.Name;
                DeliveryNoteId = dn.Id;
                getMapFieldLabel.put(dn.Id, dn.Name);
            }
            if(DeliveryNoteId==null){
                isDeliveryAptBooked = true;
                ApexPages.addmessage(new ApexPages.message(ApexPages.severity.ERROR,'Delivery Appointment is already booked for Delivery Note'));
            }
            /*
            ETT_Delivery_Line_Item__c objDLI = [SELECT Id, ETT_Collection_Card__c,ETT_Delivery_Note__r.Name FROM ETT_Delivery_Line_Item__c where ETT_Collection_Card__c in :collectionCardIdsSet limit 1];
            DeliveryNote = objDLI.ETT_Delivery_Note__r.Name;
            DeliveryNoteId = objDLI.ETT_Delivery_Note__c;
            
            ServiceAppointment objServiceAppointment = [SELECT Id, ETT_Delivery_Note__c FROM ServiceAppointment where ETT_Delivery_Note__c=:DeliveryNoteId];
            if(objServiceAppointment!=null){
                isDeliveryAptBooked = true;
                ApexPages.addmessage(new ApexPages.message(ApexPages.severity.ERROR,'Delivery Appointment is already booked for Delivery Note '+DeliveryNote));
            }
            */
        }

    }
    
    public void deliveryWorkType(){
        if(isDeliveryAppointment){
             WorkType objExistingWorkType = [select id,Name from workType where RecordType.Name='Tyre - Cash Supplier' and Name='Tyre Delivery'];
             objWorkType = objExistingWorkType;     
        }else{
             WorkType objExistingWorkType = [select id,Name from workType where RecordType.Name='Tyre - Cash Supplier' and Name='Tyre Collection'];
             objWorkType = objExistingWorkType;
        }
       
    }
   
    public void skipAppointment(){
        if(isSkipAppointment)
        isSkipAppointment = false;else
         isSkipAppointment = true;   
    }   
    
    public String selectedPriority{get;set;}
    
    public List<SelectOption> getpriorityOptions() {
        List<SelectOption> priorityOptions = new List<SelectOption>();
        priorityOptions.add(new SelectOption('Supplier Collection','Supplier Collection'));
        priorityOptions.add(new SelectOption('ET Delivery','ET Delivery'));
        return priorityOptions;
    }
    
    /*
    This logic has been to Create a Work Order and Service Appointment and Service Resource based
    Calender avilable dates.
    */
    
    
    public PageReference serviceAppointmentRedirect(){
        
        List<RecordType> lstRecordTypes = [SELECT Id, Name, SobjectType FROM RecordType where SobjectType='Opportunity' and Id=:oppObj.RecordTypeId];

        if(lstRecordTypes[0].Name=='Tyre - Cash Supplier'){
            list<AssignedResource> lstAssinedResources =[select Id,ETT_Vehicle_Detail__c,ServiceResource.Name,ETT_Vehicle_Detail__r.Name,ServiceAppointment.AppointmentNumber,ServiceAppointment.earliestStartTime,ServiceAppointment.DueDate from AssignedResource where 
                                                         ServiceResourceId=:objAssignedResource.serviceResourceId and ETT_Vehicle_Detail__c!=null 
                                                         and ServiceAppointment.RecordType.Name in ('Tyre - Cash Supplier','Tyre - Credit/B2B Supplier','Tyre - Refurbishing Services','Tyre - Return Appointment') and 
                                                         ServiceAppointment.earliestStartTime>=:objServiceAppointment.earliestStartTime and ServiceAppointment.duedate<=:objServiceAppointment.DueDate and
                                                         ServiceAppointment.status not in ('Completed','Canceled')
                                                        ];
            system.debug('****lstAssinedResources*****'+lstAssinedResources);
            if(lstAssinedResources!=null && lstAssinedResources.size()>0){
                for(AssignedResource objAssignResource :lstAssinedResources){
                    if(objAssignResource.ETT_Vehicle_Detail__c==objAssignedResource.ETT_Vehicle_Detail__c){
                        apexpages.addMessage(new ApexPages.message(Apexpages.Severity.Error,'The Appointment slot is already booked'));
                    }else{
                        apexpages.addMessage(new ApexPages.message(Apexpages.Severity.Error,'The Appointment slot is already booked'));
                    }
                }
                return null;
            }
            if(objWorkOrder!=null){
                list<WorkType> lstWorkTypes = [select id,Name,RecordType.Name from workType where RecordType.Name in ('Tyre - Cash Supplier') and Name='Tyre Collection'];
                
                
                if(lstWorkTypes!=null && lstWorkTypes.size()>0){
                    if(lstWorkTypes[0].Name=='Tyre Collection'){
                        objWorkOrder.WorkTypeId = lstWorkTypes[0].Id;
                    }
                }    
                list<Contact> lstContact = [select Id,Account.Phone,Account.BillingStreet from contact where AccountId=:oppObj.AccountId limit 1];        
                objWorkOrder.AccountId = oppObj.AccountId;
                if(lstContact!=null && lstContact.size()>0){
                    objWorkOrder.ContactId = lstContact[0].Id;
                }
                objWorkOrder.ETT_Opportunity__c = oppObj.Id;
                objWorkOrder.RecordTypeId = objWorkOrder.RecordTypeId = Schema.SObjectType.WorkOrder.getRecordTypeInfosByName().get('Tyre - Cash Supplier').getRecordTypeId();    
                
                try{
                    insert objWorkOrder;
                } Catch(Exception ex){
                    apexpages.addMessage(new ApexPages.message(Apexpages.Severity.Error,ex.getMessage()));
                }
                System.debug('selectedPriority: '+selectedPriority);
                // insert objWorkOrder;
                if(objServiceAppointment!=null){

                    System.debug('selectedPriority: '+selectedPriority);
                    
                    objServiceAppointment.RecordTypeId = Schema.SObjectType.ServiceAppointment.getRecordTypeInfosByName().get('Tyre - Cash Supplier').getRecordTypeId();  
                    objServiceAppointment.SchedStartTime = objServiceAppointment.EarliestStartTime;
                    objServiceAppointment.SchedEndTime = objServiceAppointment.DueDate; 
                    objServiceAppointment.ParentRecordId = objWorkOrder.Id;
                    objServiceAppointment.ETT_Opportunity__c = oppObj.Id;
                    //objServiceAppointment.Delivery__c = objServiceAppointment.Delivery__c; //selectedPriority;
                    system.debug('****objServiceAppointment****'+objServiceAppointment);
                }
                
                try{
                    insert objServiceAppointment;
                    system.debug('****objServiceAppointment****'+objServiceAppointment);
                } Catch(Exception ex){
                    apexpages.addMessage(new ApexPages.message(Apexpages.Severity.Error,ex.getMessage()));
                }
                
                if(objAssignedResource!=null){
                    objAssignedResource.ServiceAppointmentId = objServiceAppointment.Id;
                    try{
                        insert  objAssignedResource;
                        system.debug('******objAssignedResource******'+objAssignedResource);
                    }Catch(Exception ex){
                        apexpages.addMessage(new ApexPages.message(Apexpages.Severity.Error,ex.getMessage()));
                    }
                    ETT_Collection_Card__c objCollectionCard = new ETT_Collection_Card__c();
                    objCollectionCard.ETT_Accounts__c = oppObj.AccountId;
                    objCollectionCard.ETT_Collection_Status__c = 'New';
                    objCollectionCard.ETT_Driver__c = objAssignedResource.ServiceResourceId;
                    objCollectionCard.ETT_Service_Appointment__c = objServiceAppointment.Id;
                    objCollectionCard.ETT_Vehicle_Detail__c = objAssignedResource.ETT_Vehicle_Detail__c;
                    objCollectionCard.ETT_Work_Order__c = objWorkOrder.Id;
                    objCollectionCard.RecordTypeId = Schema.SObjectType.ETT_Collection_Card__c.getRecordTypeInfosByName().get('Tyre - Cash Supplier').getRecordTypeId(); 
                    if(lstContact!=null && lstContact.size()>0){
                        objCollectionCard.ETT_Location__c = lstContact[0].Account.BillingStreet;
                    }
                    
                    try{
                        insert objCollectionCard; 
                    }
                    Catch(Exception ex){
                        apexpages.addMessage(new ApexPages.message(Apexpages.Severity.Error,ex.getMessage()));
                    }
                }
            }       
            
        }
        
        if(lstRecordTypes[0].Name=='Tyre Refurbishing Services'){
            list<AssignedResource> lstAssinedResources =[select Id,ETT_Vehicle_Detail__c,ServiceResource.Name,ETT_Vehicle_Detail__r.Name,ServiceAppointment.AppointmentNumber,ServiceAppointment.earliestStartTime,ServiceAppointment.DueDate from AssignedResource where 
                                                         ServiceResourceId=:objAssignedResource.serviceResourceId and ETT_Vehicle_Detail__c!=null 
                                                         and ServiceAppointment.RecordType.Name in ('Tyre Refurbishing Services','Tyre - Cash Supplier','Tyre - Credit/B2B Supplier','Tyre - Return Appointment') and 
                                                         ServiceAppointment.earliestStartTime>=:objServiceAppointment.earliestStartTime and ServiceAppointment.duedate<=:objServiceAppointment.DueDate and
                                                         ServiceAppointment.status not in ('Completed','Canceled')
                                                        ];
            system.debug('****lstAssinedResources*****'+lstAssinedResources);
            if(lstAssinedResources!=null && lstAssinedResources.size()>0){
                for(AssignedResource objAssignResource :lstAssinedResources){
                    if(objAssignResource.ETT_Vehicle_Detail__c==objAssignedResource.ETT_Vehicle_Detail__c){
                        apexpages.addMessage(new ApexPages.message(Apexpages.Severity.Error,'The Appointment slot is already booked'));
                    }else{
                        apexpages.addMessage(new ApexPages.message(Apexpages.Severity.Error,'The Appointment slot is already booked'));
                    }
                }
                return null;
            }
            if(objWorkOrder!=null){
                list<WorkType> lstWorkTypes = [select id,Name,RecordType.Name from workType where RecordType.Name in ('Tyre Refurbishing Services') and Name='Tyre Collection'];
                
                
                if(lstWorkTypes!=null && lstWorkTypes.size()>0){
                    if(lstWorkTypes[0].Name=='Tyre Collection'){
                        objWorkOrder.WorkTypeId = lstWorkTypes[0].Id;
                    }
                }    
                list<Contact> lstContact = [select Id,Account.Phone,Account.BillingStreet from contact where AccountId=:oppObj.AccountId limit 1];        
                objWorkOrder.AccountId = oppObj.AccountId;
                if(lstContact!=null && lstContact.size()>0){
                    objWorkOrder.ContactId = lstContact[0].Id;
                }
                objWorkOrder.ETT_Opportunity__c = oppObj.Id;
                objWorkOrder.RecordTypeId = objWorkOrder.RecordTypeId = Schema.SObjectType.WorkOrder.getRecordTypeInfosByName().get('Tyre - Refurbishing Services').getRecordTypeId();    
                
                try{
                    insert objWorkOrder;
                } Catch(Exception ex){
                    apexpages.addMessage(new ApexPages.message(Apexpages.Severity.Error,ex.getMessage()));
                }
                // insert objWorkOrder;
                if(objServiceAppointment!=null){
                    objServiceAppointment.RecordTypeId = Schema.SObjectType.ServiceAppointment.getRecordTypeInfosByName().get('Tyre - Refurbishing Services').getRecordTypeId();  
                    objServiceAppointment.SchedStartTime = objServiceAppointment.EarliestStartTime;
                    objServiceAppointment.SchedEndTime = objServiceAppointment.DueDate; 
                    objServiceAppointment.ParentRecordId = objWorkOrder.Id;
                    objServiceAppointment.ETT_Opportunity__c = oppObj.Id;
                    system.debug('****objServiceAppointment****'+objServiceAppointment);
                }
                
                try{
                    insert objServiceAppointment;
                    system.debug('****objServiceAppointment****'+objServiceAppointment);
                } Catch(Exception ex){
                    apexpages.addMessage(new ApexPages.message(Apexpages.Severity.Error,ex.getMessage()));
                }
                
                if(objAssignedResource!=null){
                    objAssignedResource.ServiceAppointmentId = objServiceAppointment.Id;
                    try{
                        insert  objAssignedResource;
                        system.debug('******objAssignedResource******'+objAssignedResource);
                    }Catch(Exception ex){
                        apexpages.addMessage(new ApexPages.message(Apexpages.Severity.Error,ex.getMessage()));
                    }
                    ETT_Collection_Card__c objCollectionCard = new ETT_Collection_Card__c();
                    objCollectionCard.ETT_Accounts__c = oppObj.AccountId;
                    objCollectionCard.ETT_Collection_Status__c = 'New';
                    objCollectionCard.ETT_Driver__c = objAssignedResource.ServiceResourceId;
                    objCollectionCard.ETT_Service_Appointment__c = objServiceAppointment.Id;
                    objCollectionCard.ETT_Vehicle_Detail__c = objAssignedResource.ETT_Vehicle_Detail__c;
                    objCollectionCard.ETT_Work_Order__c = objWorkOrder.Id;
                    objCollectionCard.RecordTypeId = Schema.SObjectType.ETT_Collection_Card__c.getRecordTypeInfosByName().get('Tyre - Refurbishing Services').getRecordTypeId(); 
                    if(lstContact!=null && lstContact.size()>0){
                        objCollectionCard.ETT_Location__c = lstContact[0].Account.BillingStreet;
                    }
                    
                    try{
                        insert objCollectionCard; 
                    }
                    Catch(Exception ex){
                        apexpages.addMessage(new ApexPages.message(Apexpages.Severity.Error,ex.getMessage()));
                    }
                }
            }       
            
        }
 
        if(lstRecordTypes[0].Name=='Tyre - Credit/B2B Supplier'){
            list<AssignedResource> lstAssinedResources =[select Id,ETT_Vehicle_Detail__c,ServiceResource.Name,ETT_Vehicle_Detail__r.Name,ServiceAppointment.AppointmentNumber,ServiceAppointment.earliestStartTime,ServiceAppointment.DueDate from AssignedResource where 
                                                         ServiceResourceId=:objAssignedResource.serviceResourceId and ETT_Vehicle_Detail__c!=null 
                                                         and ServiceAppointment.RecordType.Name in ('Tyre Refurbishing Services','Tyre - Cash Supplier','Tyre - Credit/B2B Supplier','Tyre - Return Appointment') and 
                                                         ServiceAppointment.earliestStartTime>=:objServiceAppointment.earliestStartTime and ServiceAppointment.duedate<=:objServiceAppointment.DueDate and
                                                         ServiceAppointment.status not in ('Completed','Canceled')
                                                        ];
            system.debug('****lstAssinedResources*****'+lstAssinedResources);
            if(lstAssinedResources!=null && lstAssinedResources.size()>0){
                for(AssignedResource objAssignResource :lstAssinedResources){
                    if(objAssignResource.ETT_Vehicle_Detail__c==objAssignedResource.ETT_Vehicle_Detail__c){
                        apexpages.addMessage(new ApexPages.message(Apexpages.Severity.Error,'The Appointment slot is already booked'));
                    }else{
                        apexpages.addMessage(new ApexPages.message(Apexpages.Severity.Error,'The Appointment slot is already booked'));
                    }
                }
                return null;
            }
            if(objWorkOrder!=null){
                list<WorkType> lstWorkTypes = [select id,Name,RecordType.Name from workType where RecordType.Name in ('Tyre - Credit/B2B Supplier') and Name='Tyre Collection'];
                
                
                if(lstWorkTypes!=null && lstWorkTypes.size()>0){
                    if(lstWorkTypes[0].Name=='Tyre Collection'){
                        objWorkOrder.WorkTypeId = lstWorkTypes[0].Id;
                    }
                }    
                list<Contact> lstContact = [select Id,Account.Phone,Account.BillingStreet from contact where AccountId=:oppObj.AccountId limit 1];        
                objWorkOrder.AccountId = oppObj.AccountId;
                if(lstContact!=null && lstContact.size()>0){
                    objWorkOrder.ContactId = lstContact[0].Id;
                }
                objWorkOrder.ETT_Opportunity__c = oppObj.Id;
                objWorkOrder.RecordTypeId = objWorkOrder.RecordTypeId = Schema.SObjectType.WorkOrder.getRecordTypeInfosByName().get('Tyre - Credit/B2B Supplier').getRecordTypeId();    
                
                try{
                    insert objWorkOrder;
                } Catch(Exception ex){
                    apexpages.addMessage(new ApexPages.message(Apexpages.Severity.Error,ex.getMessage()));
                }
                // insert objWorkOrder;
                if(objServiceAppointment!=null){
                    objServiceAppointment.RecordTypeId = Schema.SObjectType.ServiceAppointment.getRecordTypeInfosByName().get('Tyre - Credit/B2B Supplier').getRecordTypeId();  
                    objServiceAppointment.SchedStartTime = objServiceAppointment.EarliestStartTime;
                    objServiceAppointment.SchedEndTime = objServiceAppointment.DueDate; 
                    objServiceAppointment.ParentRecordId = objWorkOrder.Id;
                    objServiceAppointment.ETT_Opportunity__c = oppObj.Id;
                    system.debug('****objServiceAppointment****'+objServiceAppointment);
                }
                
                try{
                    insert objServiceAppointment;
                    system.debug('****objServiceAppointment****'+objServiceAppointment);
                } Catch(Exception ex){
                    apexpages.addMessage(new ApexPages.message(Apexpages.Severity.Error,ex.getMessage()));
                }
                
                if(objAssignedResource!=null){
                    objAssignedResource.ServiceAppointmentId = objServiceAppointment.Id;
                    try{
                        insert  objAssignedResource;
                        system.debug('******objAssignedResource******'+objAssignedResource);
                    }Catch(Exception ex){
                        apexpages.addMessage(new ApexPages.message(Apexpages.Severity.Error,ex.getMessage()));
                    }
                    ETT_Collection_Card__c objCollectionCard = new ETT_Collection_Card__c();
                    objCollectionCard.ETT_Accounts__c = oppObj.AccountId;
                    objCollectionCard.ETT_Collection_Status__c = 'New';
                    objCollectionCard.ETT_Driver__c = objAssignedResource.ServiceResourceId;
                    objCollectionCard.ETT_Service_Appointment__c = objServiceAppointment.Id;
                    objCollectionCard.ETT_Vehicle_Detail__c = objAssignedResource.ETT_Vehicle_Detail__c;
                    objCollectionCard.ETT_Work_Order__c = objWorkOrder.Id;
                    objCollectionCard.RecordTypeId = Schema.SObjectType.ETT_Collection_Card__c.getRecordTypeInfosByName().get('Tyre - Credit/B2B Supplier').getRecordTypeId(); 
                    if(lstContact!=null && lstContact.size()>0){
                        objCollectionCard.ETT_Location__c = lstContact[0].Account.BillingStreet;
                    }
                    
                    try{
                        insert objCollectionCard; 
                    }
                    Catch(Exception ex){
                        apexpages.addMessage(new ApexPages.message(Apexpages.Severity.Error,ex.getMessage()));
                    }
                }
            }       
            
        }        
    
        return new Pagereference('/'+oppObj.Id);
    }
    
    public PageReference deliveryAppointmentRedirect(){
        
        List<RecordType> lstRecordTypes = [SELECT Id, Name, SobjectType FROM RecordType where SobjectType='Opportunity' and Id=:oppObj.RecordTypeId];
        
        if(lstRecordTypes[0].Name=='Tyre - Cash Supplier'){
            list<AssignedResource> lstAssinedResources = [select Id,ETT_Vehicle_Detail__c,ServiceResource.Name,ETT_Vehicle_Detail__r.Name,ServiceAppointment.AppointmentNumber,ServiceAppointment.earliestStartTime,ServiceAppointment.DueDate from AssignedResource where 
                                                          ServiceResourceId=:objAssignedResource.serviceResourceId and ETT_Vehicle_Detail__c!=null 
                                                          and ServiceAppointment.RecordType.Name in ('Tyre Refurbishing Services','Tyre - Cash Supplier','Tyre - Credit/B2B Supplier','Tyre - Return Appointment') and 
                                                          ServiceAppointment.earliestStartTime>=:objServiceAppointment.earliestStartTime and ServiceAppointment.duedate<=:objServiceAppointment.DueDate and
                                                          ServiceAppointment.status not in ('Completed','Canceled')
                                                         ];
            
            system.debug('****lstAssinedResources*****'+lstAssinedResources);
            if(lstAssinedResources!=null && lstAssinedResources.size()>0){
                for(AssignedResource objAssignResource :lstAssinedResources){
                    if(objAssignResource.ETT_Vehicle_Detail__c==objAssignedResource.ETT_Vehicle_Detail__c){
                        apexpages.addMessage(new ApexPages.message(Apexpages.Severity.Error,'The Appointment slot is already booked'));
                    }else{
                        apexpages.addMessage(new ApexPages.message(Apexpages.Severity.Error,'The Appointment slot is already booked'));
                    }
                }
                return null;
            }
            if(objWorkOrder!=null){
                list<WorkType> lstWorkTypes = [select id,Name,RecordType.Name from workType where RecordType.Name in ('Tyre - Cash Supplier') and Name='Tyre Collection'];
                
                
                if(lstWorkTypes!=null && lstWorkTypes.size()>0){
                    if(lstWorkTypes[0].Name=='Tyre Collection'){
                        objWorkOrder.WorkTypeId = lstWorkTypes[0].Id;
                    }
                }    
                list<Contact> lstContact = [select Id,Account.Phone,Account.BillingStreet from contact where AccountId=:oppObj.AccountId limit 1];        
                objWorkOrder.AccountId = oppObj.AccountId;
                if(lstContact!=null && lstContact.size()>0){
                    objWorkOrder.ContactId = lstContact[0].Id;
                }
                objWorkOrder.ETT_Opportunity__c = oppObj.Id;
                objWorkOrder.RecordTypeId = objWorkOrder.RecordTypeId = Schema.SObjectType.WorkOrder.getRecordTypeInfosByName().get('Tyre - Cash Supplier').getRecordTypeId();    
                
                try{
                    insert objWorkOrder;
                } Catch(Exception ex){
                    apexpages.addMessage(new ApexPages.message(Apexpages.Severity.Error,ex.getMessage()));
                }
                // insert objWorkOrder;
                if(objServiceAppointment!=null){
                    objServiceAppointment.RecordTypeId = Schema.SObjectType.ServiceAppointment.getRecordTypeInfosByName().get('Tyre - Return Appointment').getRecordTypeId();  
                    objServiceAppointment.SchedStartTime = objServiceAppointment.EarliestStartTime;
                    objServiceAppointment.SchedEndTime = objServiceAppointment.DueDate; 
                    //objServiceAppointment.ParentRecordId = objWorkOrder.Id;
                    objServiceAppointment.ETT_Opportunity__c = oppObj.Id;
                    objServiceAppointment.ETT_Delivery_Note__c = DeliveryNoteId;
                    system.debug('****objServiceAppointment****'+objServiceAppointment);
                }
                
                try{
                    insert objServiceAppointment;
                    system.debug('****objServiceAppointment****'+objServiceAppointment);
                } Catch(Exception ex){
                    apexpages.addMessage(new ApexPages.message(Apexpages.Severity.Error,ex.getMessage()));
                }
                
                if(objAssignedResource!=null){
                    objAssignedResource.ServiceAppointmentId = objServiceAppointment.Id;
                    try{
                        insert  objAssignedResource;
                        system.debug('******objAssignedResource******'+objAssignedResource);
                    }Catch(Exception ex){
                        apexpages.addMessage(new ApexPages.message(Apexpages.Severity.Error,ex.getMessage()));
                    }
                }
                /*
                
                ETT_Delivery_Note__c objDNote = [SELECT Id, Name, ETT_Is_Delivery_Appointment_Booked__c FROM ETT_Delivery_Note__c where Id=:DeliveryNoteId];            

                if(DeliveryNoteId != null){
                    objDNote.ETT_Is_Delivery_Appointment_Booked__c = true;
                    try{
                        update objDNote;
                    }catch(Exception ex){
                        apexpages.addMessage(new ApexPages.message(Apexpages.Severity.Error,ex.getMessage()));
                    }
                }
                */
                
                
            }       
            
        }
        
        if(lstRecordTypes[0].Name=='Tyre Refurbishing Services'){
            list<AssignedResource> lstAssinedResources = [select Id,ETT_Vehicle_Detail__c,ServiceResource.Name,ETT_Vehicle_Detail__r.Name,ServiceAppointment.AppointmentNumber,ServiceAppointment.earliestStartTime,ServiceAppointment.DueDate from AssignedResource where 
                                                          ServiceResourceId=:objAssignedResource.serviceResourceId and ETT_Vehicle_Detail__c!=null 
                                                          and ServiceAppointment.RecordType.Name in ('Tyre Refurbishing Services','Tyre - Cash Supplier','Tyre - Credit/B2B Supplier','Tyre - Return Appointment') and 
                                                          ServiceAppointment.earliestStartTime>=:objServiceAppointment.earliestStartTime and ServiceAppointment.duedate<=:objServiceAppointment.DueDate and
                                                          ServiceAppointment.status not in ('Completed','Canceled')
                                                         ];
            
            system.debug('****lstAssinedResources*****'+lstAssinedResources);
            if(lstAssinedResources!=null && lstAssinedResources.size()>0){
                for(AssignedResource objAssignResource :lstAssinedResources){
                    if(objAssignResource.ETT_Vehicle_Detail__c==objAssignedResource.ETT_Vehicle_Detail__c){
                        apexpages.addMessage(new ApexPages.message(Apexpages.Severity.Error,'The Appointment slot is already booked'));
                    }else{
                        apexpages.addMessage(new ApexPages.message(Apexpages.Severity.Error,'The Appointment slot is already booked'));
                    }
                }
                return null;
            }
            if(objWorkOrder!=null){
                list<WorkType> lstWorkTypes = [select id,Name,RecordType.Name from workType where RecordType.Name in ('Tyre Refurbishing Services') and Name='Tyre Collection'];
                
                
                if(lstWorkTypes!=null && lstWorkTypes.size()>0){
                    if(lstWorkTypes[0].Name=='Tyre Collection'){
                        objWorkOrder.WorkTypeId = lstWorkTypes[0].Id;
                    }
                }    
                list<Contact> lstContact = [select Id,Account.Phone,Account.BillingStreet from contact where AccountId=:oppObj.AccountId limit 1];        
                objWorkOrder.AccountId = oppObj.AccountId;
                if(lstContact!=null && lstContact.size()>0){
                    objWorkOrder.ContactId = lstContact[0].Id;
                }
                objWorkOrder.ETT_Opportunity__c = oppObj.Id;
                objWorkOrder.RecordTypeId = objWorkOrder.RecordTypeId = Schema.SObjectType.WorkOrder.getRecordTypeInfosByName().get('Tyre - Refurbishing Services').getRecordTypeId();    
                
                try{
                    insert objWorkOrder;
                } Catch(Exception ex){
                    apexpages.addMessage(new ApexPages.message(Apexpages.Severity.Error,ex.getMessage()));
                }
                // insert objWorkOrder;
                if(objServiceAppointment!=null){
                    objServiceAppointment.RecordTypeId = Schema.SObjectType.ServiceAppointment.getRecordTypeInfosByName().get('Tyre - Return Appointment').getRecordTypeId();  
                    objServiceAppointment.SchedStartTime = objServiceAppointment.EarliestStartTime;
                    objServiceAppointment.SchedEndTime = objServiceAppointment.DueDate; 
                    //objServiceAppointment.ParentRecordId = objWorkOrder.Id;
                    objServiceAppointment.ETT_Opportunity__c = oppObj.Id;
                    objServiceAppointment.ETT_Delivery_Note__c = DeliveryNoteId;
                    system.debug('****objServiceAppointment****'+objServiceAppointment);
                }
                
                try{
                    insert objServiceAppointment;
                    system.debug('****objServiceAppointment****'+objServiceAppointment);
                } Catch(Exception ex){
                    apexpages.addMessage(new ApexPages.message(Apexpages.Severity.Error,ex.getMessage()));
                }
                
                if(objAssignedResource!=null){
                    objAssignedResource.ServiceAppointmentId = objServiceAppointment.Id;
                    try{
                        insert  objAssignedResource;
                        system.debug('******objAssignedResource******'+objAssignedResource);
                    }Catch(Exception ex){
                        apexpages.addMessage(new ApexPages.message(Apexpages.Severity.Error,ex.getMessage()));
                    }
                }
                
                
                ETT_Delivery_Note__c objDNote = [SELECT Id, Name, ETT_Is_Delivery_Appointment_Booked__c FROM ETT_Delivery_Note__c where Id=:DeliveryNoteId];            

                if(DeliveryNoteId != null){
                    objDNote.ETT_Is_Delivery_Appointment_Booked__c = true;
                    try{
                        update objDNote;
                    }catch(Exception ex){
                        apexpages.addMessage(new ApexPages.message(Apexpages.Severity.Error,ex.getMessage()));
                    }
                }
                
                
                
            }       
            
        }
        
        return new Pagereference('/'+oppObj.Id);
    }
    
    @RemoteAction
    public static list<AssignedResourceWrapper> lstAssignedResources(){
        list<AssignedResourceWrapper> lstAssignedWrapper = new list<AssignedResourceWrapper>();
        for(AssignedResource objAssinedResources :[select Id,ServiceResource.Name,ETT_Vehicle_Detail__r.Name,ServiceAppointment.AppointmentNumber,ServiceAppointment.earliestStartTime,ServiceAppointment.DueDate from AssignedResource where ETT_Vehicle_Detail__c!=null 
                                                   and ServiceAppointment.RecordType.Name in ('Tyre - Cash Supplier','Tyre - Refurbishing Services','Tyre - Credit/B2B Supplier','Tyre - Return Appointment')  and ServiceAppointment.status not in ('Completed','Canceled','None')
                                                  ]){
                                                      AssignedResourceWrapper objAssinedResourceWrap     = new AssignedResourceWrapper();
                                                      objAssinedResourceWrap.strServiceResourceName      =  objAssinedResources.ServiceResource.Name;
                                                      objAssinedResourceWrap.strVehicleName              =  objAssinedResources.ETT_Vehicle_Detail__r.Name;
                                                      objAssinedResourceWrap.strServiceAppointmentNumber =  objAssinedResources.ServiceAppointment.AppointmentNumber;
                                                      objAssinedResourceWrap.startTime                   =  objAssinedResources.ServiceAppointment.earliestStartTime;
                                                      objAssinedResourceWrap.endTime                     =  objAssinedResources.ServiceAppointment.DueDate; 
                                                      lstAssignedWrapper.add(objAssinedResourceWrap);
                                                  }
        return lstAssignedWrapper;
    }
    
    public class AssignedResourceWrapper{
        public  string strServiceResourceName;
        public  string strVehicleName;
        public  string strServiceAppointmentNumber;
        public  DateTime startTime;
        public  DateTime endTime;
    }
    
    @AuraEnabled
    public static void uploadSignedDeliveryNote(map<string,string> mapofStageJsonList,Id DeliveryAppointmentId){
        
        list<ETT_FileUploadWrapper> lstFileUploadWrapper;
        
        if(mapofStageJsonList.containskey('filesToUpload')){
            lstFileUploadWrapper =  (list<ETT_FileUploadWrapper>)JSON.deserialize(mapofStageJsonList.get('filesToUpload'),Type.forname('list<ETT_FileUploadWrapper>'));
        }
        
        
        if(lstFileUploadWrapper!=null && lstFileUploadWrapper.size()>0){
            list<ContentVersion> lstContentVesions = new list<ContentVersion>();
            list<ContentDocumentLink> lstContentDocumentLinks = new list<ContentDocumentLink>();
            list<Attachment> lstAttachments = new list<Attachment>();           
            for(ETT_FileUploadWrapper objFileUploadWrapper :lstFileUploadWrapper){
                Attachment objAttachment=new Attachment();      
                objAttachment.Name=objFileUploadWrapper.strFileName;
                Blob bodyBlob=EncodingUtil.base64Decode(objFileUploadWrapper.strBase64Data);
                objAttachment.body=bodyBlob;
                objAttachment.parentId= DeliveryAppointmentId; 
                lstAttachments.add(objAttachment);
            }
            
            try{ 
              insert lstAttachments;  
              system.debug('***lstAttachments*****'+lstAttachments);
            }Catch(Exception ex){
                system.debug('****Exception Cause ****'+ex.getMessage());
            }
           
        }
        
    }
    
}