unpackaged/main/default/objects/ET_Pricing_Service_Request__c/ET_Pricing_Service_Request__c.object-meta.xml
<CustomObject>
    <label>Pricing Service Request</label>
    <nameField>
        <displayFormat>PSR-{0000}</displayFormat>
        <label>Pricing Service Request Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Pricing Service Requests</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

unpackaged/main/default/objects/ET_Pricing_Service_Request__c/fields/ET_PSR_IsActive__c.field-meta.xml
<CustomField>
    <fullName>ET_PSR_IsActive__c</fullName>
    <defaultValue>false</defaultValue>
    <label>IsActive</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/objects/ET_Pricing_Service_Request__c/fields/ET_Service_Request_Common_Data__c.field-meta.xml
<CustomField>
    <fullName>ET_Service_Request_Common_Data__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Service Request Common Data</label>
    <referenceTo>ET_Service_Request_Common_Data__c</referenceTo>
    <relationshipLabel>Pricing Service Requests</relationshipLabel>
    <relationshipName>Pricing_Service_Requests</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/ET_Pricing_Service_Request__c/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <label>Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Pricing Service Requests</relationshipLabel>
    <relationshipName>Pricing_Service_Requests</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

unpackaged/main/default/objects/ET_Service_Request_Common_Data__c/ET_Service_Request_Common_Data__c.object-meta.xml
<CustomObject>
    <label>Service Request Common Data</label>
    <nameField>
        <displayFormat>SRCD-{0000}</displayFormat>
        <label>Service Request Common Data Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Service Requests Common Data</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/ET_Service_Request_Common_Data__c/fields/ET_Contract_Period__c.field-meta.xml
<CustomField>
    <fullName>ET_Contract_Period__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Contract Period</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Opportunity/fields/ETSALES_GL_Services__c.field-meta.xml
<CustomField>
    <fullName>ETSALES_GL_Services__c</fullName>
    <label>ET Service (Current Contract)</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>ETSALES_Service_Type_Values</valueSetName>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Opportunity/fields/Vehicle__c.field-meta.xml
<CustomField>
    <fullName>Vehicle__c</fullName>
    <label>Vehicle</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Vehicle</valueSetName>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Vehicle__c/Vehicle__c.object-meta.xml
<CustomObject>
    <label>Pricing Vehicle Request</label>
    <nameField>
        <displayFormat>VN-{0000}</displayFormat>
        <label>Vehicle Request Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Vehicle Requests</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Vehicle__c/fields/ET_Contract_Period__c.field-meta.xml
<CustomField>
    <fullName>ET_Contract_Period__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Contract Period</label>
    <type>TextArea</type>
</CustomField>

unpackaged/main/default/objects/Vehicle__c/fields/ET_Pricing_Service_Request__c.field-meta.xml
<CustomField>
    <fullName>ET_Pricing_Service_Request__c</fullName>
    <label>Pricing Service Request</label>
    <referenceTo>ET_Pricing_Service_Request__c</referenceTo>
    <relationshipLabel>Vehicle Requests</relationshipLabel>
    <relationshipName>Vehicle_Requests</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

unpackaged/main/default/objects/Vehicle__c/fields/ET_Service_Request_Common_Data__c.field-meta.xml
<CustomField>
    <fullName>ET_Service_Request_Common_Data__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Service Request Common Data</label>
    <referenceTo>ET_Service_Request_Common_Data__c</referenceTo>
    <relationshipName>Vehicle_Requests</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/globalValueSets/ETSALES_Service_Type_Values.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Airport drop off</fullName>
    </customValue>
    <customValue>
        <fullName>Chauffeur - Dubai</fullName>
    </customValue>
    <customValue>
        <fullName>Chauffeur - Others</fullName>
    </customValue>
    <customValue>
        <fullName>Abu Dhabi</fullName>
    </customValue>
    <customValue>
        <fullName>Documents</fullName>
    </customValue>
    <customValue>
        <fullName>Motor Cycle</fullName>
    </customValue>
    <customValue>
        <fullName>Electric Car</fullName>
    </customValue>
    <customValue>
        <fullName>Vehicle</fullName>
    </customValue>
    <customValue>
        <fullName>Government School</fullName>
    </customValue>
    <customValue>
        <fullName>Quran Studies</fullName>
    </customValue>
    <customValue>
        <fullName>Private School</fullName>
    </customValue>
    <customValue>
        <fullName>Government Executive</fullName>
    </customValue>
    <customValue>
        <fullName>Staff-Employees and Labors</fullName>
    </customValue>
    <customValue>
        <fullName>Haj &amp; Umrah</fullName>
    </customValue>
    <customValue>
        <fullName>University</fullName>
    </customValue>
    <customValue>
        <fullName>Club Members</fullName>
    </customValue>
    <customValue>
        <fullName>Vehicle Auctioning</fullName>
    </customValue>
    <customValue>
        <fullName>Sale Of Scrap Materials</fullName>
    </customValue>
    <customValue>
        <fullName>Maintenance Services - Contracted</fullName>
    </customValue>
    <customValue>
        <fullName>Maintenance Services - Non-Contracted</fullName>
    </customValue>
    <customValue>
        <fullName>Luxury Vehicles Maintenance</fullName>
    </customValue>
    <customValue>
        <fullName>Dry Wash</fullName>
    </customValue>
    <customValue>
        <fullName>Tire Rethreading and Repair</fullName>
    </customValue>
    <customValue>
        <fullName>Refurbished and used tire Sales</fullName>
    </customValue>
    <customValue>
        <fullName>Road Side Assistance</fullName>
    </customValue>
    <customValue>
        <fullName>Body-Accident Repair services</fullName>
    </customValue>
    <customValue>
        <fullName>Bus Refurbishment</fullName>
    </customValue>
    <customValue>
        <fullName>CNG Conversion Services</fullName>
    </customValue>
    <customValue>
        <fullName>Vehicle Inspection</fullName>
    </customValue>
    <customValue>
        <fullName>Heavy Equipment Maintenance</fullName>
    </customValue>
    <masterLabel>GL Service Type Values</masterLabel>
</GlobalValueSet>

unpackaged/main/default/globalValueSets/Vehicle.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Alfa Romeo</fullName>
    </customValue>
    <customValue>
        <fullName>Aston Martin</fullName>
    </customValue>
    <customValue>
        <fullName>Audi</fullName>
    </customValue>
    <customValue>
        <fullName>Bentley</fullName>
    </customValue>
    <customValue>
        <fullName>BMW</fullName>
    </customValue>
    <customValue>
        <fullName>Cadillac</fullName>
    </customValue>
    <customValue>
        <fullName>Caterham</fullName>
    </customValue>
    <customValue>
        <fullName>Chevrolet</fullName>
    </customValue>
    <customValue>
        <fullName>Chrysler</fullName>
    </customValue>
    <customValue>
        <fullName>Citroen</fullName>
    </customValue>
    <customValue>
        <fullName>Dodge</fullName>
    </customValue>
    <customValue>
        <fullName>Ferrari</fullName>
    </customValue>
    <customValue>
        <fullName>Fiat</fullName>
    </customValue>
    <customValue>
        <fullName>Ford</fullName>
    </customValue>
    <customValue>
        <fullName>Genesis</fullName>
    </customValue>
    <customValue>
        <fullName>GMC</fullName>
    </customValue>
    <customValue>
        <fullName>Honda</fullName>
    </customValue>
    <customValue>
        <fullName>Hummer</fullName>
    </customValue>
    <customValue>
        <fullName>Hyundai</fullName>
    </customValue>
    <customValue>
        <fullName>Infiniti</fullName>
    </customValue>
    <customValue>
        <fullName>Jaguar</fullName>
    </customValue>
    <customValue>
        <fullName>Jeep</fullName>
    </customValue>
    <customValue>
        <fullName>Kia</fullName>
    </customValue>
    <customValue>
        <fullName>Lamborghini</fullName>
    </customValue>
    <customValue>
        <fullName>Land Rover</fullName>
    </customValue>
    <customValue>
        <fullName>Lexus</fullName>
    </customValue>
    <customValue>
        <fullName>Lincoln</fullName>
    </customValue>
    <customValue>
        <fullName>Lotus</fullName>
    </customValue>
    <customValue>
        <fullName>Maserati</fullName>
    </customValue>
    <customValue>
        <fullName>Maybach</fullName>
    </customValue>
    <masterLabel>Vehicle</masterLabel>
</GlobalValueSet>

unpackaged/main/default/classes/ETSALES_GONOGOControllerTest.cls
@isTest
public class ETSALES_GONOGOControllerTest {
    static testMethod void insertNewOpportunity(){
        test.startTest();
        Account acc= new Account();
        acc.name='Test Account';
        Insert acc;

        Id oppRecordType = Schema.SObjectType.Opportunity.getRecordTypeInfosByName().get('Leasing').getRecordTypeId();
        Opportunity opp = new Opportunity();
        opp.RecordTypeId = oppRecordType;
        opp.Name = 'Test Opportunity';
        opp.AccountId = acc.Id;
        opp.Type = 'New Business';
        opp.CloseDate = Date.today()+2;
        //opp.StageName = 'Negotiation';
        opp.StageName = 'Decision';
        opp.ETSALES_GL_Services__c = 'Motor Cycle';
        Insert opp;
        
        ET_Service_Request_Common_Data__c srcd = New ET_Service_Request_Common_Data__c(ET_Contract_Period__c='12');
        insert srcd;
        
        ET_Pricing_Service_Request__c prReq= new ET_Pricing_Service_Request__c();
        prReq.Opportunity__c = opp.Id;
        prReq.ET_PSR_IsActive__c=true;
        prReq.ET_Service_Request_Common_Data__c = srcd.Id;
        Insert prReq;
        
        Vehicle__c vehicle = new Vehicle__c();
        vehicle.ET_Pricing_Service_Request__c =prReq.Id;
        Insert vehicle;
        
        /*
        User testUser = new User();
        testUser.Lastname = 'testUser';
        testUser.Username ='testUser@123.com';
        testUser.Email='testUser@123.com';
        insert testUser;
        */
        
        ETSALES_GONOGOController.AccountContactListWrapper oppInfo = ETSALES_GONOGOController.getOppAccountVehicleDetails(opp.Id);
        ETSALES_GONOGOController.submitForOppApproval(opp.Id);
        ETSALES_GONOGOController.getOpportunityDetails(opp.Id);
        delete prReq;
        ETSALES_GONOGOController.submitForOppApproval(opp.Id);
        Id oppRecordType1 = Schema.SObjectType.Opportunity.getRecordTypeInfosByName().get('Driving School- B2B').getRecordTypeId();
        opp.RecordTypeId = oppRecordType1;
        update opp;
        ETSALES_GONOGOController.submitForOppApproval(opp.Id);
        test.stopTest();
    }
}