unpackaged/main/default/objects/ETT_Delivery_Note__c/ETT_Delivery_Note__c.object-meta.xml
<CustomObject>
    <label>Delivery Note</label>
    <nameField>
        <displayFormat>DNN-{0000}</displayFormat>
        <label>Delivery Note Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Delivery Notes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/ETT_Delivery_Note__c/fields/DN_Status__c.field-meta.xml
<CustomField>
    <fullName>DN_Status__c</fullName>
    <label>DN Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>New</fullName>
                <default>true</default>
                <label>New</label>
            </value>
            <value>
                <fullName>In Progress</fullName>
            </value>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>Rejected</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/ETT_Delivery_Note__c/fields/ETT_Account__c.field-meta.xml
<CustomField>
    <fullName>ETT_Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Delivery Notes</relationshipLabel>
    <relationshipName>Delivery_Notes</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/ETT_Delivery_Note__c/fields/ETT_Date__c.field-meta.xml
<CustomField>
    <fullName>ETT_Date__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Date</label>
    <type>DateTime</type>
</CustomField>

unpackaged/main/default/objects/ETT_Delivery_Note__c/fields/Tyre_Service_Appointment__c.field-meta.xml
<CustomField>
    <fullName>Tyre_Service_Appointment__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Tyre Service Appointment</label>
    <referenceTo>Tyre_Collection_Appointment__c</referenceTo>
    <relationshipLabel>Delivery Notes</relationshipLabel>
    <relationshipName>Delivery_Notes</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Tyre_Collection_Appointment__c/Tyre_Collection_Appointment__c.object-meta.xml
<CustomObject>
    <description>Label name is changed to accommodate same object for all tyre appointments, please note dont confuse with API name</description>
    <label>Tyre Service Appointment</label>
    <nameField>
        <displayFormat>TSA-{00000}</displayFormat>
        <label>Appointment Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Tyre Service Appointments</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Tyre_Collection_Appointment__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipName>Tyre_Collection_Appointments</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/classes/ETT_addDNToServiceApt.cls
/**
 * Author:Janardhan
 * CreatedDate:13/12/2021
 * TestClass: ETT_addDNToServiceAptTest
 * */
public without sharing class  ETT_addDNToServiceApt {

    @auraEnabled
    public static list<ETT_Delivery_Note__c> getDNDetails(string recordId){
        
        Id accId = [select id,Account__c from Tyre_Collection_Appointment__c where id=:recordId].Account__c;
        
        return [select id,name,ETT_Date__c from ETT_Delivery_Note__c where ETT_Account__c=:accId AND Tyre_Service_Appointment__c=null AND DN_Status__c='Approved' ORDER BY NAME DESC];
    }
    
    @auraEnabled
    public static void updateDNDetails(list<ETT_Delivery_Note__c> dnList){
        
        if(dnList.size()>0 && dnList != null){
            
            try{
                 update dnList;
            }catch(Exception e){
                throw new AuraHandledException(e.getMessage());   
            }
           
        }
    }
        
}