unpackaged/main/default/objects/ET_Refund__c/ET_Refund__c.object-meta.xml
<CustomObject>
    <label>Refund</label>
    <nameField>
        <displayFormat>REF-{00000}</displayFormat>
        <label>Refund Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Refunds</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

unpackaged/main/default/objects/ET_Refund__c/fields/ET_Refund_Amount__c.field-meta.xml
<CustomField>
    <fullName>ET_Refund_Amount__c</fullName>
    <label>Refund Amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

unpackaged/main/default/objects/ET_Refund__c/fields/ET_Service_Request__c.field-meta.xml
<CustomField>
    <fullName>ET_Service_Request__c</fullName>
    <label>Service Request</label>
    <referenceTo>ET_Service_Request__c</referenceTo>
    <relationshipLabel>Refunds</relationshipLabel>
    <relationshipName>ET_Refunds</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

unpackaged/main/default/objects/ET_Refund__c/recordTypes/ETST_School_Refund_Record_Type.recordType-meta.xml
<RecordType>
    <fullName>ETST_School_Refund_Record_Type</fullName>
    <active>true</active>
    <label>School Refund Record Type</label>
</RecordType>

unpackaged/main/default/objects/ET_Service_Request__c/ET_Service_Request__c.object-meta.xml
<CustomObject>
    <label>Service Request</label>
    <nameField>
        <displayFormat>SR-{000000}</displayFormat>
        <label>Service Request Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Service Requests</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

unpackaged/main/default/objects/ET_Service_Request__c/fields/ETST_Paid_By__c.field-meta.xml
<CustomField>
    <fullName>ETST_Paid_By__c</fullName>
    <label>Paid By</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Self</fullName>
                <default>true</default>
                <label>Self</label>
            </value>
            <value>
                <fullName>Employer</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/ET_Service_Request__c/fields/Payment_Status__c.field-meta.xml
<CustomField>
    <fullName>Payment_Status__c</fullName>
    <label>Payment Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Not Initiated</fullName>
            </value>
            <value>
                <fullName>Payment Pending</fullName>
            </value>
            <value>
                <fullName>Payment Success</fullName>
            </value>
            <value>
                <fullName>Refund Requested</fullName>
            </value>
            <value>
                <fullName>Await3D</fullName>
            </value>
            <value>
                <fullName>Captured</fullName>
            </value>
            <value>
                <fullName>Partially Paid</fullName>
            </value>
            <value>
                <fullName>Fully Paid</fullName>
            </value>
            <value>
                <fullName>Refund Cancelled</fullName>
            </value>
            <value>
                <fullName>Failed</fullName>
            </value>
            <value>
                <fullName>Reversed</fullName>
            </value>
            <value>
                <fullName>On Premise Requested</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/classes/ETST_RefundRequestController_Test.cls
@isTest
public class ETST_RefundRequestController_Test {
    @isTest
    static void testRefund() {
         ET_Service_Request__c  etreq = new ET_Service_Request__c(Payment_Status__c='Not Initiated',ETST_Paid_By__c = 'Self');
        insert etreq;
        
        ET_Refund__c refund = new ET_Refund__c();
        refund.RecordTypeId = Schema.SObjectType.ET_Refund__c.getRecordTypeInfosByDeveloperName().get('ETST_School_Refund_Record_Type').getRecordTypeId();
        refund.ET_Refund_Amount__c = 100;
        refund.ET_Service_Request__c = etreq.Id;
        insert refund;
        ETST_RefundRequestController.getRefundRequests('REF','Name','asc');
    }
}