unpackaged/main/default/objects/ET_Refund__c/ET_Refund__c.object-meta.xml
<CustomObject>
    <label>Refund</label>
    <nameField>
        <displayFormat>REF-{00000}</displayFormat>
        <label>Refund Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Refunds</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

unpackaged/main/default/objects/ET_Refund__c/fields/ET_Authorization_Code__c.field-meta.xml
<CustomField>
    <fullName>ET_Authorization_Code__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Authorization Code</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/ET_Refund__c/fields/ET_Payment__c.field-meta.xml
<CustomField>
    <fullName>ET_Payment__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Payment</label>
    <referenceTo>ETST_Payment__c</referenceTo>
    <relationshipLabel>Refunds</relationshipLabel>
    <relationshipName>Refunds</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/ET_Refund__c/fields/ET_Refund_Amount__c.field-meta.xml
<CustomField>
    <fullName>ET_Refund_Amount__c</fullName>
    <label>Refund Amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

unpackaged/main/default/objects/ET_Refund__c/fields/ET_Refund_Status__c.field-meta.xml
<CustomField>
    <fullName>ET_Refund_Status__c</fullName>
    <label>Refund Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Requested</fullName>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
            <value>
                <fullName>Failed</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
            <value>
                <fullName>Rejected</fullName>
            </value>
            <value>
                <fullName>Process Refund NextDay</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/ET_Refund__c/fields/ET_Service_Request__c.field-meta.xml
<CustomField>
    <fullName>ET_Service_Request__c</fullName>
    <label>Service Request</label>
    <referenceTo>ET_Service_Request__c</referenceTo>
    <relationshipLabel>Refunds</relationshipLabel>
    <relationshipName>ET_Refunds</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

unpackaged/main/default/objects/ET_Refund__c/recordTypes/Car_Services_Refund_Record_Type.recordType-meta.xml
<RecordType>
    <fullName>Car_Services_Refund_Record_Type</fullName>
    <active>true</active>
    <label>Car Services Refund Record Type</label>
</RecordType>

unpackaged/main/default/objects/ET_Service_Request__c/ET_Service_Request__c.object-meta.xml
<CustomObject>
    <label>Service Request</label>
    <nameField>
        <displayFormat>SR-{000000}</displayFormat>
        <label>Service Request Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Service Requests</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

unpackaged/main/default/objects/ET_Service_Request__c/fields/ETC_Billing_Total__c.field-meta.xml
<CustomField>
    <fullName>ETC_Billing_Total__c</fullName>
    <label>Billing Total(With VAT)</label>
    <summarizedField>ETCAR_Service_Request_Line_Item__c.Total_Booking_Cost_With_Vat__c</summarizedField>
    <summaryFilterItems>
        <field>ETCAR_Service_Request_Line_Item__c.ETCAR_Status__c</field>
        <operation>notEqual</operation>
        <value>Cancelled</value>
    </summaryFilterItems>
    <summaryForeignKey>ETCAR_Service_Request_Line_Item__c.ETCAR_Service_Request__c</summaryForeignKey>
    <summaryOperation>sum</summaryOperation>
    <type>Summary</type>
</CustomField>

unpackaged/main/default/objects/ET_Service_Request__c/fields/ETCAR_Pick_UP_Date_Time__c.field-meta.xml
<CustomField>
    <fullName>ETCAR_Pick_UP_Date_Time__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Pick UP Date Time</label>
    <type>DateTime</type>
</CustomField>

unpackaged/main/default/objects/ET_Service_Request__c/fields/ETCAR_Status__c.field-meta.xml
<CustomField>
    <fullName>ETCAR_Status__c</fullName>
    <label>Booking Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Draft</fullName>
                <default>true</default>
                <label>Draft</label>
            </value>
            <value>
                <fullName>Booking Confirmed</fullName>
            </value>
            <value>
                <fullName>Vehicle Delivered</fullName>
            </value>
            <value>
                <fullName>Vehicle Collected</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
            <value>
                <fullName>Closed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/ET_Service_Request__c/fields/ETST_Service_Type__c.field-meta.xml
<CustomField>
    <fullName>ETST_Service_Type__c</fullName>
    <label>Service Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Yearly</fullName>
            </value>
            <value>
                <fullName>Half Yearly</fullName>
            </value>
            <value>
                <fullName>Quarterly</fullName>
            </value>
            <value>
                <fullName>Monthly</fullName>
            </value>
            <value>
                <fullName>On-demand</fullName>
            </value>
            <value>
                <fullName>Select Dates</fullName>
            </value>
            <value>
                <fullName>One Way</fullName>
            </value>
            <value>
                <fullName>Hourly</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/ETC_Limo_Refund_Settings__c/ETC_Limo_Refund_Settings__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <label>ETC Limo Refund Settings</label>
</CustomObject>

unpackaged/main/default/objects/ETC_Limo_Refund_Settings__c/fields/ETC_From__c.field-meta.xml
<CustomField>
    <fullName>ETC_From__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>From</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/ETC_Limo_Refund_Settings__c/fields/ETC_Percentage__c.field-meta.xml
<CustomField>
    <fullName>ETC_Percentage__c</fullName>
    <label>Percentage</label>
    <precision>5</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

unpackaged/main/default/objects/ETC_Limo_Refund_Settings__c/fields/ETC_To__c.field-meta.xml
<CustomField>
    <fullName>ETC_To__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>To</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/ETC_Rental_Settings__c/ETC_Rental_Settings__c.object-meta.xml
<CustomObject>
    <label>Rental Settings</label>
    <nameField>
        <displayFormat>R-{0000}</displayFormat>
        <label>Rental Settings Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Rental Settings</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/ETC_Rental_Settings__c/fields/ETC_hours_before_booking_date__c.field-meta.xml
<CustomField>
    <fullName>ETC_hours_before_booking_date__c</fullName>
    <description>Difference Hours Between Booking Time and Cancelled Time</description>
    <label>Hours before booking date</label>
    <precision>3</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

unpackaged/main/default/objects/ETC_Rental_Settings__c/fields/ETC_Policy__c.field-meta.xml
<CustomField>
    <fullName>ETC_Policy__c</fullName>
    <label>Policy</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Cancellation</fullName>
            </value>
            <value>
                <fullName>Modify Booking</fullName>
            </value>
            <value>
                <fullName>Flat Refund</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/ETC_Rental_Settings__c/fields/ETC_Refund_Percentage__c.field-meta.xml
<CustomField>
    <fullName>ETC_Refund_Percentage__c</fullName>
    <label>Refund Percentage</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Percent</type>
</CustomField>

unpackaged/main/default/objects/ETCAR_Service_Request_Line_Item__c/ETCAR_Service_Request_Line_Item__c.object-meta.xml
<CustomObject>
    <description>To Capture Selected Car Details</description>
    <label>Vehicle Booking</label>
    <nameField>
        <displayFormat>Item-{0000}</displayFormat>
        <label>Service Request Line Item Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Vehicle Bookings</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

unpackaged/main/default/objects/ETCAR_Service_Request_Line_Item__c/fields/ETCAR_Pick_UP_Date_Time__c.field-meta.xml
<CustomField>
    <fullName>ETCAR_Pick_UP_Date_Time__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Pick UP Date Time</label>
    <type>DateTime</type>
</CustomField>

unpackaged/main/default/objects/ETCAR_Service_Request_Line_Item__c/fields/ETCAR_Service_Request__c.field-meta.xml
<CustomField>
    <fullName>ETCAR_Service_Request__c</fullName>
    <label>Service Request</label>
    <referenceTo>ET_Service_Request__c</referenceTo>
    <relationshipName>Service_Request_Line_Items</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

unpackaged/main/default/objects/ETCAR_Service_Request_Line_Item__c/fields/ETCAR_Status__c.field-meta.xml
<CustomField>
    <fullName>ETCAR_Status__c</fullName>
    <label>Booking Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Draft</fullName>
                <default>true</default>
                <label>Draft</label>
            </value>
            <value>
                <fullName>In Progress</fullName>
            </value>
            <value>
                <fullName>Booking Confirmed</fullName>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/ETCAR_Service_Request_Line_Item__c/fields/ETST_Service_Type__c.field-meta.xml
<CustomField>
    <fullName>ETST_Service_Type__c</fullName>
    <label>Service Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>One Way</fullName>
            </value>
            <value>
                <fullName>Hourly</fullName>
            </value>
            <value>
                <fullName>Rental</fullName>
            </value>
            <value>
                <fullName>Half Yearly</fullName>
                <isActive>false</isActive>
                <label>Half Yearly</label>
            </value>
            <value>
                <fullName>Monthly</fullName>
                <isActive>false</isActive>
                <label>Monthly</label>
            </value>
            <value>
                <fullName>On-Demand</fullName>
                <isActive>false</isActive>
                <label>On-Demand</label>
            </value>
            <value>
                <fullName>Quarterly</fullName>
                <isActive>false</isActive>
                <label>Quarterly</label>
            </value>
            <value>
                <fullName>Select Dates</fullName>
                <isActive>false</isActive>
                <label>Select Dates</label>
            </value>
            <value>
                <fullName>Yearly</fullName>
                <isActive>false</isActive>
                <label>Yearly</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/ETCAR_Service_Request_Line_Item__c/fields/Total_Booking_Cost_With_Vat__c.field-meta.xml
<CustomField>
    <fullName>Total_Booking_Cost_With_Vat__c</fullName>
    <formula>(ETC_Features_Price__c  +  ETCAR_Price__c)*1.05</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Total Booking Cost (With Vat)</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

unpackaged/main/default/objects/ETST_Payment__c/ETST_Payment__c.object-meta.xml
<CustomObject>
    <label>Payment</label>
    <nameField>
        <displayFormat>TRN-{00000}</displayFormat>
        <label>ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Payments</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/ETST_Payment__c/fields/ET_Service_Request__c.field-meta.xml
<CustomField>
    <fullName>ET_Service_Request__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Service Request</label>
    <referenceTo>ET_Service_Request__c</referenceTo>
    <relationshipLabel>Payments</relationshipLabel>
    <relationshipName>ET_Payments</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/ETST_Payment__c/fields/ETST_Capture_State__c.field-meta.xml
<CustomField>
    <fullName>ETST_Capture_State__c</fullName>
    <defaultValue>IF(  $RecordType.DeveloperName = &#39;On_Premise_Payment&#39;, &#39;SUCCESS&#39;, &#39;&#39;)</defaultValue>
    <encryptionScheme>None</encryptionScheme>
    <label>Capture State</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/ETST_Payment__c/fields/ETST_Payment_State__c.field-meta.xml
<CustomField>
    <fullName>ETST_Payment_State__c</fullName>
    <defaultValue>IF( $RecordType.DeveloperName = &#39;On_Premise_Payment&#39; , &#39;SUCCESS&#39;, &#39;&#39;)</defaultValue>
    <encryptionScheme>None</encryptionScheme>
    <label>Payment State</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/classes/ETC_RefundController.cls
public class ETC_RefundController {
    
    /*  @InvocableMethod
public static List <ET_Service_Request__c> execute (List<ET_Service_Request__c> requestList) {
system.debug('refund ctrl');
List<ETC_Rental_Settings__c> cancellationMatrix = new List<ETC_Rental_Settings__c> ([SELECT Id,ETC_Policy__c ,ETC_Refund_Percentage__c ,ETC_hours_before_booking_date__c 
FROM ETC_Rental_Settings__c WHERE ETC_Policy__c ='Cancellation' order by ETC_hours_before_booking_date__c desc ]);

Map<Id, ET_Refund__c> refundMap = new Map<Id, ET_Refund__c>();
List<ET_Refund__c> refundList = new List<ET_Refund__c>();
Id recordTypeId = Schema.SObjectType.ET_Refund__c.getRecordTypeInfosByDeveloperName().get('Car_Services_Refund_Record_Type').getRecordTypeId();
for(ET_Service_Request__c req : requestList){
ET_Refund__c refund=new ET_Refund__c();
refund.RecordTypeId = recordTypeId;
refund.ET_Service_Request__c = req.Id;
}

return null;    
} */
    
    @AuraEnabled
    public static List<ETCAR_Service_Request_Line_Item__c> getVehicleBookings(String recId) {
        List<ETCAR_Service_Request_Line_Item__c> vehBookingsList =
            [SELECT Id, Name,ETCAR_Service_Request__c,ETST_Service_Type__c,Total_Booking_Cost_With_Vat__c FROM ETCAR_Service_Request_Line_Item__c WHERE ETCAR_Service_Request__c =:recId AND ETCAR_Status__c =: 'Booking Confirmed' ];
        system.debug('list '+vehBookingsList);
        return vehBookingsList;
    }
    
    @AuraEnabled
    public static Map<string,decimal> calculateRefundAmount(list<string> vehBkngs){
        Map<string,decimal> refunds = new Map<string,decimal>();
        List<ETC_Limo_Refund_Settings__c> refundSettings = [select ETC_From__c,ETC_To__C, ETC_Percentage__c from ETC_Limo_Refund_Settings__c];
        List<ETCAR_Service_Request_Line_Item__c> vehBookingsList =[SELECT Id, Name,ETCAR_Service_Request__c,ETST_Service_Type__c,Total_Booking_Cost_With_Vat__c,ETCAR_Pick_UP_Date_Time__c FROM ETCAR_Service_Request_Line_Item__c WHERE id=:vehBkngs];
        decimal total=0;
        for(ETCAR_Service_Request_Line_Item__c lt :vehBookingsList ){            
            decimal decHours = ((lt.ETCAR_Pick_UP_Date_Time__c.getTime())/1000/60/60) - ((system.now().getTime())/1000/60/60);
            system.debug('dechrs '+decHours);
            decimal refundper = 0;
            /*  if(decHours>24){
                refundper=1;
                }else if(decHours>5){
                refundper=0.5;
            } */
            for(ETC_Limo_Refund_Settings__c s:refundSettings){
                if(decHours>=decimal.valueof(s.ETC_From__c) && (s.ETC_To__C==null || decHours<=decimal.valueof(s.ETC_To__C)) ){
                    refundper=s.ETC_Percentage__c;
                    break;
                } 
            }
            
            total+=refundper*lt.Total_Booking_Cost_With_Vat__c;
            refunds.put(lt.id,refundper*lt.Total_Booking_Cost_With_Vat__c);            
        }
        refunds.put('total',total);   
        system.debug('list '+refunds);
        return refunds;
    }
    
    @AuraEnabled
    public static void createRefund(list<ETCAR_Service_Request_Line_Item__c> lineItems){
        string requestId =lineItems[0].ETCAR_Service_Request__c;
        List<ETST_Payment__c> payments = [Select Id,Name,CreatedDate From ETST_Payment__c Where ET_Service_Request__c=:requestId and  ETST_Payment_State__c='CAPTURED' AND ETST_Capture_State__c='SUCCESS' order by createdDate desc limit 1];
        if(payments.size()>0){
            Id recordTypeId = Schema.SObjectType.ET_Refund__c.getRecordTypeInfosByDeveloperName().get('Car_Services_Refund_Record_Type').getRecordTypeId();
            list<string> itemIds =new list<string>();
            for(ETCAR_Service_Request_Line_Item__c item:lineItems){
                item.ETCAR_Status__c = 'Cancelled';
                itemIds.add(item.id);
            }
            Map<string,decimal> refunds =calculateRefundAmount(itemIds);
            ET_Refund__c refund=new ET_Refund__c();
            refund.RecordTypeId = recordTypeId;
            refund.ET_Service_Request__c = requestId;
            refund.ET_Refund_Amount__c = refunds.get('total');
            refund.ET_Payment__c=payments[0].Id; 
            if( refund.ET_Refund_Amount__c == 0){
                refund.ET_Refund_Status__c='Completed';
                insert refund;
                update lineItems;
            }else{
                if(payments[0].createddate.isSameDay(system.now())){
                    refund.ET_Refund_Status__c='Process Refund NextDay'; 
                    insert refund;
                    update lineItems;
                    
                    Integer hur = payments[0].createddate.hour();
                    Date nextDay=Date.today()+1;
                    integer dd=nextDay.day();
                    integer mm=nextDay.month(); 
                    // insert refund;
                    String refundTime = '0 0 '+hur+' '+dd+' '+mm+' ?';
                    ETC_CallRefundServiceScheduled SC = new ETC_CallRefundServiceScheduled(new set<Id>{refund.Id}); 
                    System.schedule('ETC CallRefundServiceScheduled '+refund.Name, refundTime, SC);
                } else{
                    ET_Common_Util.ETPaymentResponse response=ET_Payment_Controller.createRefundRequest(payments[0].Id,refund.ET_Refund_Amount__c);
                    system.debug('response>> '+response);
                    ET_common_util.cls_authResponse authResponse = new ET_common_util.cls_authResponse();
                    system.debug('authResponse>> '+authResponse);
                    if(response!=null && response.authResponse!=null){
                        authResponse = response.authResponse;
                        if(authResponse.authorizationCode!=null && authResponse.authorizationCode!='')
                            refund.ET_Authorization_Code__c=authResponse.authorizationCode;
                        if(authResponse.success == 'true'){
                            refund.ET_Refund_Status__c='Completed';
                        }else {
                            refund.ET_Refund_Status__c='Failed';
                        }
                    }
                    insert refund;
                    update lineItems;
                } 
            }
        }
    }
    /*
public static void createFlatRefundRequest(Set<Id> flatRefundIds){

List<ETC_Rental_Settings__c> flatPercentage = [SELECT Id,ETC_Policy__c,ETC_Refund_Percentage__c FROM ETC_Rental_Settings__c WHERE ETC_Policy__c ='Flat Refund' limit 1];
Id recordTypeId = Schema.SObjectType.ET_Refund__c.getRecordTypeInfosByDeveloperName().get('Car_Services_Refund_Record_Type').getRecordTypeId();
List<ET_Refund__c> refundList = new List<ET_Refund__c>();
List<ETCAR_Service_Request_Line_Item__c> vehBkngList = new List<ETCAR_Service_Request_Line_Item__c>();
for(ET_Service_Request__c req : [SELECT Id, Name,ETC_Billing_Total__c,ETC_Booking_Confirmed_Amount__c, (SELECT Id,ETCAR_Status__c FROM Service_Request_Line_Items__r ),(Select Id,Name,CreatedDate From ET_Payments__r Where  ETST_Payment_State__c='CAPTURED' AND ETST_Capture_State__c='SUCCESS' order by createdDate desc limit 1)
FROM ET_Service_Request__c WHERE Id In: flatRefundIds]){
for(ETCAR_Service_Request_Line_Item__c vBkng : req.Service_Request_Line_Items__r){
if(vBkng.ETCAR_Status__c != 'Cancelled'){
vBkng.ETCAR_Status__c = 'Cancelled';
vehBkngList.add(vBkng);
}
}
system.debug('loop');
ET_Refund__c refund=new ET_Refund__c();
refund.RecordTypeId = recordTypeId;
refund.ET_Service_Request__c = req.Id;
refund.ET_Refund_Amount__c = (req.ETC_Booking_Confirmed_Amount__c*flatPercentage[0].ETC_Refund_Percentage__c)/100;
if(req.ET_Payments__r.size()>0) refund.ET_Payment__c=req.ET_Payments__r[0].Id;
Date paymentDate =date.newinstance(req.ET_Payments__r[0].CreatedDate.year(), req.ET_Payments__r[0].CreatedDate.month(), req.ET_Payments__r[0].CreatedDate.day());
Integer hur = req.ET_Payments__r[0].CreatedDate.hour();   
system.debug('paymentdate'+paymentDate);
if(paymentDate!=Date.today()){
if(req.ET_Payments__r.size()>0){
ET_Common_Util.ETPaymentResponse response=ET_Payment_Controller.createRefundRequest(req.ET_Payments__r[0].Id,refund.ET_Refund_Amount__c);
system.debug('response>> '+response);
ET_common_util.cls_authResponse authResponse = new ET_common_util.cls_authResponse();
if(response!=null && response.authResponse!=null){
system.debug('authResponse>> '+authResponse);
authResponse = response.authResponse;
if(authResponse.authorizationCode!=null && authResponse.authorizationCode!='')
refund.ET_Authorization_Code__c=authResponse.authorizationCode;
if(authResponse.success == 'true'){
refund.ET_Refund_Status__c='Completed';
}else {
refund.ET_Refund_Status__c='Failed';
}
}else {
refund.ET_Refund_Status__c='Failed';
}
}
}else {
system.debug('paymentDate>> '+paymentDate);
Date nextDay=Date.today()+1;
system.debug('nextDay>> '+nextDay);
system.debug('hur>> '+hur);
if(paymentDate==Date.today()){
string result;
result='S';
if(result=='S'){
refund.ET_Refund_Status__c='Process Refund NextDay';
integer dd=nextDay.day();
integer mm=nextDay.month();
//String sched3am = '0 0 3 '+dd+' '+mm+' ?'; //Next Day, 3AM
String sched3am = '0 0 '+hur+' '+dd+' '+mm+' ?'; //After 24 hours
//  ETI_CallRefundServiceScheduled SC = new ETI_CallRefundServiceScheduled(new set<Id>{refund.Id}); 
//  System.schedule('ETI CallRefundServiceScheduled - Next Day '+booking.Name, sched3am, SC);
//  return refund;
}
}
} 
refundList.add(refund);
}

if(refundList.size()>0) insert refundList;
if(vehBkngList.size()>0) update vehBkngList;

} */
    
    
    @future(callout=true)
    public static void callRefundRequest(Set<Id> refundIds) {
        List<ET_Refund__c> listRefund = new List<ET_Refund__c>();
        try{
            if(!refundIds.isEmpty()){
                for(ET_Refund__c refund:[SELECT Id,Name,ETI_Booking__c,ET_Refund_Amount__c,ET_Refund_Status__c,ET_Payment__c FROM ET_Refund__c WHERE Id=:refundIds AND ET_Payment__r.CreatedDate!=TODAY]){
                    listRefund.add(refund);
                }
                if(!listRefund.isEmpty()){
                    if(listRefund[0].ET_Refund_Amount__c!=0){
                        ET_Common_Util.ETPaymentResponse response=ET_Payment_Controller.createRefundRequest(listRefund[0].ET_Payment__c,listRefund[0].ET_Refund_Amount__c);
                        system.debug('response>> '+response);
                        ET_common_util.cls_authResponse authResponse = new ET_common_util.cls_authResponse();
                        if(response!=null && response.authResponse!=null){
                            system.debug('authResponse>> '+authResponse);
                            authResponse = response.authResponse;
                            if(authResponse.authorizationCode!=null && authResponse.authorizationCode!='')
                                listRefund[0].ET_Authorization_Code__c=authResponse.authorizationCode;
                            if(authResponse.success == 'true'){
                                listRefund[0].ET_Refund_Status__c='Completed';
                            }else {
                                listRefund[0].ET_Refund_Status__c='Failed';
                            }
                        }else {
                            listRefund[0].ET_Refund_Status__c='Failed';
                        }
                    }
                    update listRefund;
                }
            }
        }catch(Exception ex) {
            UTIL_Logging.ExceptionLog exLog = new UTIL_Logging.ExceptionLog(ex, 'ETC_CallRefundServiceScheduled', 'CallRefundServiceScheduled', '', UTIL_Logging.DEBUG_LEVEL_WARN);
            UTIL_Logging.logException(exLog);
        }
    }
    
    public static void testUtilityRFC(){
        integer i = 0;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        
    }
    
}