unpackaged/main/default/objects/ETM_Sales_Vehicle_Inventory__c/ETM_Sales_Vehicle_Inventory__c.object-meta.xml
<CustomObject>
    <label>Sales Vehicle Inventory</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Vehicle Description</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Sales Vehicle Inventory</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/ETM_Sales_Vehicle_Inventory__c/fields/ETM_Price__c.field-meta.xml
<CustomField>
    <fullName>ETM_Price__c</fullName>
    <label>Retail Price including VAT</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

unpackaged/main/default/objects/ETM_Sales_Vehicle_Inventory__c/fields/ETM_Vehicle_Status__c.field-meta.xml
<CustomField>
    <fullName>ETM_Vehicle_Status__c</fullName>
    <label>Vehicle Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>Advertised</fullName>
            </value>
            <value>
                <fullName>Available</fullName>
            </value>
            <value>
                <fullName>Booked</fullName>
            </value>
            <value>
                <fullName>Contract Cancelled</fullName>
            </value>
            <value>
                <fullName>Inactive-Reconditioning</fullName>
            </value>
            <value>
                <fullName>Inspection</fullName>
                <default>true</default>
                <label>Inspection</label>
            </value>
            <value>
                <fullName>Purchase</fullName>
            </value>
            <value>
                <fullName>Ready for Photoshoot</fullName>
            </value>
            <value>
                <fullName>Rejected</fullName>
            </value>
            <value>
                <fullName>Removed from Platforms</fullName>
            </value>
            <value>
                <fullName>Sold</fullName>
                <isActive>false</isActive>
                <label>Sold</label>
            </value>
            <value>
                <fullName>Sold through Auction</fullName>
            </value>
            <value>
                <fullName>Sold through Showroom</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/classes/SalesVehicalInventryTrgHnadlerTest.cls
@IsTest
public class SalesVehicalInventryTrgHnadlerTest {
  
    @IsTest
    static void testVehiclePriceChange() {
        ETM_Sales_Vehicle_Inventory__c vehicle = new ETM_Sales_Vehicle_Inventory__c();
        vehicle.Name = 'Test Vehicle';
        vehicle.ETM_Price__c = 10000;
        vehicle.ETM_Vehicle_Status__c='Contract Cancelled';
        insert vehicle;
        
       vehicle.ETM_Price__c = 20000;
       vehicle.ETM_Vehicle_Status__c='Ready for Photoshoot';
       update vehicle;
        
    }    
    

}