unpackaged/main/default/objects/ETM_Sales_Vehicle_Inventory__c/ETM_Sales_Vehicle_Inventory__c.object-meta.xml
<CustomObject>
    <label>Sales Vehicle Inventory</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Vehicle Description</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Sales Vehicle Inventory</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/ETM_Sales_Vehicle_Inventory__c/fields/ETM_Chassis_No__c.field-meta.xml
<CustomField>
    <fullName>ETM_Chassis_No__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Chassis No</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/ETM_Sales_Vehicle_Inventory__c/fields/ETM_Plate_No__c.field-meta.xml
<CustomField>
    <fullName>ETM_Plate_No__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Plate No</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/ETM_Sales_Vehicle_Inventory__c/fields/ETM_Vehicle_No__c.field-meta.xml
<CustomField>
    <fullName>ETM_Vehicle_No__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>ET Internal No</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/ETM_Vehicle_Test_Drive__c/ETM_Vehicle_Test_Drive__c.object-meta.xml
<CustomObject>
    <label>Vehicle Test Drive</label>
    <nameField>
        <displayFormat>TD-{000000}</displayFormat>
        <label>Test Drive</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Vehicle Test Drive</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/ETM_Vehicle_Test_Drive__c/fields/ETM_Lead__c.field-meta.xml
<CustomField>
    <fullName>ETM_Lead__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Lead</label>
    <referenceTo>Lead</referenceTo>
    <relationshipLabel>Vehicle Test Drive</relationshipLabel>
    <relationshipName>ET_Vehicle_Test_Drive</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/ETM_Vehicle_Test_Drive__c/fields/ETM_Status__c.field-meta.xml
<CustomField>
    <fullName>ETM_Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Initiated</fullName>
                <default>true</default>
                <label>Initiated</label>
            </value>
            <value>
                <fullName>Scheduled</fullName>
            </value>
            <value>
                <fullName>Selected</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
            <value>
                <fullName>Reschedule</fullName>
            </value>
            <value>
                <fullName>Rejected</fullName>
            </value>
            <value>
                <fullName>Completed</fullName>
                <isActive>false</isActive>
                <label>Completed</label>
            </value>
            <value>
                <fullName>Planned</fullName>
                <isActive>false</isActive>
                <label>Planned</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/ETM_Vehicle_Test_Drive__c/fields/ETM_Vehicle_No__c.field-meta.xml
<CustomField>
    <fullName>ETM_Vehicle_No__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Vehicle No</label>
    <referenceTo>ETM_Sales_Vehicle_Inventory__c</referenceTo>
    <relationshipLabel>Vehicle Test Drive</relationshipLabel>
    <relationshipName>ET_Vehicle_Test_Drive</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Lead/fields/ETM_Vehicle_No__c.field-meta.xml
<CustomField>
    <fullName>ETM_Vehicle_No__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Vehicle No</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Lead/fields/ETSALES_Budget__c.field-meta.xml
<CustomField>
    <fullName>ETSALES_Budget__c</fullName>
    <label>Customer Budget</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

unpackaged/main/default/objects/Lead/fields/ETSALES_Lead_Rating__c.field-meta.xml
<CustomField>
    <fullName>ETSALES_Lead_Rating__c</fullName>
    <label>Prospect Rating</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Hot</fullName>
            </value>
            <value>
                <fullName>Warm</fullName>
            </value>
            <value>
                <fullName>Cold</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/classes/ETM_testDrive_trigger_Test.cls
@isTest
public class ETM_testDrive_trigger_Test {
    
    @isTest
    static void testDriveTriggerMethod() { 
        
        Lead ld = new Lead();
        ld.LastName = 'LastName';
        ld.Company = 'testCompany';
        ld.Phone = '12345678';
        ld.MobilePhone = '987654321';
        ld.Email = 'testEmail@123.com';
        ld.ETSALES_Budget__c   = 123456798;
        ld.ETSALES_Lead_Rating__c  = 'Hot';
        insert ld;
        Test.startTest();
        ETM_Sales_Vehicle_Inventory__c vehInv = new ETM_Sales_Vehicle_Inventory__c(Name='Test Vehicle',ETM_Vehicle_No__c='12345',ETM_Plate_No__c='123',ETM_Chassis_No__c='321');
        insert vehInv;
        ETM_Vehicle_Test_Drive__c vht = new ETM_Vehicle_Test_Drive__c(ETM_Vehicle_No__c=vehInv.Id,ETM_Status__c='Initiated',ETM_Lead__c=ld.Id);
        insert vht;
        vht.ETM_Status__c='Selected'; 
        update vht;
        Test.stopTest();
    }
    
}