unpackaged/main/default/objects/Case/recordTypes/Services.recordType-meta.xml
<RecordType>
    <fullName>Services</fullName>
    <active>true</active>
    <businessProcess>Services</businessProcess>
    <description>الخدمات</description>
    <label>Services</label>
</RecordType>

unpackaged/main/default/objects/Case/recordTypes/Vehicle_Inspection_Services.recordType-meta.xml
<RecordType>
    <fullName>Vehicle_Inspection_Services</fullName>
    <active>true</active>
    <businessProcess>Services</businessProcess>
    <label>Vehicle Inspection Services</label>
</RecordType>

unpackaged/main/default/objects/ET_Customer_Vehicle__c/ET_Customer_Vehicle__c.object-meta.xml
<CustomObject>
    <label>Customer Vehicle</label>
    <nameField>
        <displayFormat>CV-{000000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Customer Vehicles</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/ET_Customer_Vehicle__c/fields/Chassis_No__c.field-meta.xml
<CustomField>
    <fullName>Chassis_No__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Chassis No</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/ET_Customer_Vehicle__c/fields/Plate_No__c.field-meta.xml
<CustomField>
    <fullName>Plate_No__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Plate No</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/ET_Customer_Vehicle__c/fields/Registration_Type__c.field-meta.xml
<CustomField>
    <fullName>Registration_Type__c</fullName>
    <label>Registration Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Registered</fullName>
            </value>
            <value>
                <fullName>Un-Registered</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/ET_Customer_Vehicle__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <defaultValue>&quot;Active&quot;</defaultValue>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Active</fullName>
            </value>
            <value>
                <fullName>Frozen</fullName>
            </value>
            <value>
                <fullName>Inactive</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/classes/ETI_FeedBackPageControllerTest.cls
@isTest
public class ETI_FeedBackPageControllerTest {
    private static testmethod void testmethodInspection(){
        
        ET_Customer_Vehicle__c etcv1 = new ET_Customer_Vehicle__c();
        etcv1.OwnerId = userinfo.getUserId();
        etcv1.Chassis_No__c = 'D032B5GC000790';
        etcv1.Plate_No__c = '';
        etcv1.status__c = 'Active';
        etcv1.Registration_Type__c ='Registered';
            
        insert etcv1;
        ETI_FeedBackPageController.getVehIdFrmChassisNo('D032B5GC000790'); 
        ETI_FeedBackPageController.getRecordTypeId('Case','Vehicle_Inspection_Services'); 
        ETI_FeedBackPageController.getUserVehicles(UserInfo.getUserId());
        ETI_FeedBackPageController.getCaseTypes('Vehicle Inspection Services');
        ETI_B2B_FeedBackPageController.getVehIdFrmChassisNo('D032B5GC000790'); 
        ETI_B2B_FeedBackPageController.getRecordTypeId('Case','Vehicle_Inspection_Services'); 
        ETI_B2B_FeedBackPageController.getUserVehicles(UserInfo.getUserId());
        ETI_B2B_FeedBackPageController.getCaseTypes('Vehicle Inspection Services');
    }
}