unpackaged/main/default/objects/ETT_Tools_Allocation__c/ETT_Tools_Allocation__c.object-meta.xml
<CustomObject>
    <label>Tools/Material Allocation</label>
    <nameField>
        <displayFormat>TA-{000}</displayFormat>
        <label>Tools Allocation Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Tools/Material Allocation</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

unpackaged/main/default/objects/ETT_Tools_Allocation__c/fields/Allocation_Status__c.field-meta.xml
<CustomField>
    <fullName>Allocation_Status__c</fullName>
    <label>Allocation Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Submitted for Approval</fullName>
            </value>
            <value>
                <fullName>Approved by Supervisor</fullName>
            </value>
            <value>
                <fullName>Approved by Storekeeper</fullName>
            </value>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>Rejected</fullName>
            </value>
            <value>
                <fullName>Obsolete</fullName>
            </value>
            <value>
                <fullName>Almost Used</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/ETT_Tools_Allocation__c/fields/ETT_Allocated_Stocks__c.field-meta.xml
<CustomField>
    <fullName>ETT_Allocated_Stocks__c</fullName>
    <label>Allocated Stocks</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

unpackaged/main/default/objects/ETT_Tools_Allocation__c/fields/ETT_Allocated_Units_to_Station__c.field-meta.xml
<CustomField>
    <fullName>ETT_Allocated_Units_to_Station__c</fullName>
    <inlineHelpText>For record type of &quot;Tools&quot; this will be always 1 since the usage of single tool to be tracked</inlineHelpText>
    <label>Allocated Units to Station</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

unpackaged/main/default/objects/ETT_Tools_Allocation__c/fields/ETT_Available_Stocks__c.field-meta.xml
<CustomField>
    <fullName>ETT_Available_Stocks__c</fullName>
    <formula>ETT_Allocated_Stocks__c-ETT_Used_Stock__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Available Stocks</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

unpackaged/main/default/objects/ETT_Tools_Allocation__c/fields/ETT_Previous_Tools_Allocation__c.field-meta.xml
<CustomField>
    <fullName>ETT_Previous_Tools_Allocation__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Previous Tools Allocation</label>
    <referenceTo>ETT_Tools_Allocation__c</referenceTo>
    <relationshipName>Previous_Tools_Allocation</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/ETT_Tools_Allocation__c/fields/ETT_Tools_Master__c.field-meta.xml
<CustomField>
    <fullName>ETT_Tools_Master__c</fullName>
    <label>Master Record</label>
    <referenceTo>ETT_Tools_Master__c</referenceTo>
    <relationshipLabel>Tools/Material Allocation</relationshipLabel>
    <relationshipName>Tools_Allocation</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

unpackaged/main/default/objects/ETT_Tools_Allocation__c/fields/ETT_Unit_type__c.field-meta.xml
<CustomField>
    <fullName>ETT_Unit_type__c</fullName>
    <formula>TEXT(ETT_Tools_Master__r.ETT_Unit_type__c)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Unit type</label>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/ETT_Tools_Allocation__c/fields/ETT_Usage_End_time__c.field-meta.xml
<CustomField>
    <fullName>ETT_Usage_End_time__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Usage End time</label>
    <type>DateTime</type>
</CustomField>

unpackaged/main/default/objects/ETT_Tools_Allocation__c/fields/ETT_Usage_Start_time__c.field-meta.xml
<CustomField>
    <fullName>ETT_Usage_Start_time__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Usage Start time</label>
    <type>DateTime</type>
</CustomField>

unpackaged/main/default/objects/ETT_Tools_Master__c/ETT_Tools_Master__c.object-meta.xml
<CustomObject>
    <label>Tools &amp; Materials Master</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Product Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Tools &amp; Materials Master</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/ETT_Tools_Master__c/fields/ETT_Maintenance_Frquency__c.field-meta.xml
<CustomField>
    <fullName>ETT_Maintenance_Frquency__c</fullName>
    <label>Maintenance Frequency</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Daily</fullName>
            </value>
            <value>
                <fullName>Weekly</fullName>
            </value>
            <value>
                <fullName>Monthly</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/ETT_Tools_Master__c/fields/ETT_Serial_No__c.field-meta.xml
<CustomField>
    <fullName>ETT_Serial_No__c</fullName>
    <caseSensitive>true</caseSensitive>
    <encryptionScheme>None</encryptionScheme>
    <inlineHelpText>Unique serial number code for individual tool/material if applicable</inlineHelpText>
    <label>Serial No</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

unpackaged/main/default/objects/ETT_Tools_Master__c/fields/ETT_Status__c.field-meta.xml
<CustomField>
    <fullName>ETT_Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Available</fullName>
            </value>
            <value>
                <fullName>Obsolete</fullName>
            </value>
            <value>
                <fullName>Submitted for Approval</fullName>
            </value>
            <value>
                <fullName>Rejected</fullName>
            </value>
            <value>
                <fullName>Under Maintenance</fullName>
            </value>
            <value>
                <fullName>Approved by Supervisor</fullName>
            </value>
            <value>
                <fullName>Approved by Storekeeper</fullName>
            </value>
            <value>
                <fullName>Approved</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/ETT_Tools_Master__c/fields/ETT_Tool_type__c.field-meta.xml
<CustomField>
    <fullName>ETT_Tool_type__c</fullName>
    <label>Product Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Blade</fullName>
            </value>
            <value>
                <fullName>Motor</fullName>
            </value>
            <value>
                <fullName>Accessories</fullName>
            </value>
            <value>
                <fullName>Side Buffer</fullName>
            </value>
            <value>
                <fullName>Suction Pipeline</fullName>
            </value>
            <value>
                <fullName>Suction Filter</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/ETT_Tools_Master__c/fields/ETT_Total_Unallocated_Stock_Value__c.field-meta.xml
<CustomField>
    <fullName>ETT_Total_Unallocated_Stock_Value__c</fullName>
    <formula>ETT_Stock_Value__c-ETT_Total_Allocated_Stock_Value__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Total Unallocated Stock Value</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

unpackaged/main/default/objects/ETT_Tools_Master__c/fields/ETT_Unique_Code__c.field-meta.xml
<CustomField>
    <fullName>ETT_Unique_Code__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <externalId>true</externalId>
    <label>Item Code</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/ETT_Tools_Master__c/fields/ETT_Unit_type__c.field-meta.xml
<CustomField>
    <fullName>ETT_Unit_type__c</fullName>
    <label>Unit type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Quantity based</fullName>
            </value>
            <value>
                <fullName>Length (meters based)</fullName>
            </value>
            <value>
                <fullName>Weight(Kgm based)</fullName>
            </value>
            <value>
                <fullName>Litre based</fullName>
            </value>
            <value>
                <fullName>Individual product</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/ETT_Tools_Master__c/fields/ETT_Usage_type__c.field-meta.xml
<CustomField>
    <fullName>ETT_Usage_type__c</fullName>
    <label>Usage type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Consumable</fullName>
            </value>
            <value>
                <fullName>Depreciable</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/classes/ETT_ToolMaterialsMasterTriggerUtility.cls
public class ETT_ToolMaterialsMasterTriggerUtility{
    public static void preProcessingAllocation(List<ETT_Tools_Master__c> newList,Map<Id,ETT_Tools_Master__c> oldMap){
    
    }
    
    public static void postProcessingAllocation(List<ETT_Tools_Master__c> newList,Map<Id,ETT_Tools_Master__c> oldMap){
    }
    
    public static void preProcessingAllocation(List<ETT_Tools_Allocation__c> newList,Map<Id,ETT_Tools_Allocation__c> oldMap){
        Map<Id,ETT_Tools_Master__c> toolMasterMap=new Map<Id,ETT_Tools_Master__c>();
        
        for(ETT_Tools_Allocation__c ta:newList){
            if(String.isNotBlank(ta.Allocation_Status__c)){
                toolMasterMap.put(ta.ETT_Tools_Master__c,null);
            }
        }
        
        for(ETT_Tools_Master__c tm:[Select Id,Name,ETT_Item_Description__c,ETT_Status__c,ETT_Unit_type__c,ETT_Unique_Code__c,ETT_Tool_type__c,ETT_Maintenance_Frquency__c,ETT_Usage_type__c,ETT_Serial_No__c,ETT_Total_Unallocated_Stock_Value__c from ETT_Tools_Master__c where Id IN:toolMasterMap.keyset()]){
            toolMasterMap.put(tm.Id,tm);
        }
        
        for(ETT_Tools_Allocation__c ta:newList){ 
            if(oldMap!=null && oldMap.get(ta.Id).Allocation_Status__c!= ta.Allocation_Status__c){     
                if(ta.Allocation_Status__c=='Approved by Storekeeper' || ta.Allocation_Status__c=='Approved'){
                    if(ta.ETT_Allocated_Units_to_Station__c <1){
                        ta.AddError('Allocated units to station to be greater than 0');
                    }
                    else if((toolMasterMap.get(ta.ETT_Tools_Master__c).ETT_Usage_type__c=='Consumable' || toolMasterMap.get(ta.ETT_Tools_Master__c).ETT_Usage_type__c=='Depreciable') && toolMasterMap.get(ta.ETT_Tools_Master__c).ETT_Total_Unallocated_Stock_Value__c < ta.ETT_Allocated_Stocks__c){
                        ta.AddError('Allocated stocks are not matching with stock level for the master record. please add more stocks before approving allocation.');
                    }
                    else if(toolMasterMap.get(ta.ETT_Tools_Master__c).ETT_Status__c!='Available'){
                        ta.AddError('Related tool/material master should be in available status before approving alloation.');
                    }
                    else if(toolMasterMap.get(ta.ETT_Tools_Master__c).ETT_Unit_type__c=='Individual product' && String.isBlank(toolMasterMap.get(ta.ETT_Tools_Master__c).ETT_Serial_No__c)){
                        ta.AddError('Related tool/material master should have serial no if the master\'s unit type is "Individual product".');
                    }
                    
                    if(ta.Allocation_Status__c=='Approved'){
                        ta.ETT_Usage_Start_time__c=System.now();
                    }
                }
            }
        }
    }
    
    public static void postProcessingAllocation(List<ETT_Tools_Allocation__c> newList,Map<Id,ETT_Tools_Allocation__c> oldMap){
        Map<Id,ETT_Tools_Master__c> toolMasterMap=new Map<Id,ETT_Tools_Master__c>();
        List<ETT_Tools_Master__c> toolMasterToUpdate=new List<ETT_Tools_Master__c>();
        List<ETT_Tools_Allocation__c> toolAllocationToUpdate=new List<ETT_Tools_Allocation__c>();
        Map<Id,ETT_Tools_Allocation__c> toolAllocatonMap=new Map<Id,ETT_Tools_Allocation__c>();
        
        for(ETT_Tools_Allocation__c ta:newList){
            if(String.isNotBlank(ta.Allocation_Status__c)){
                toolMasterMap.put(ta.ETT_Tools_Master__c,null);
            }
            toolAllocatonMap.put(ta.Id,null);
        }
        
        if(toolAllocatonMap.keyset() !=null && toolAllocatonMap.keyset().size() >0){
            toolAllocatonMap=new Map<Id,ETT_Tools_Allocation__c>([Select Id,ETT_Previous_Tools_Allocation__c,ETT_Previous_Tools_Allocation__r.ETT_Tools_Master__c,ETT_Previous_Tools_Allocation__r.ETT_Available_Stocks__c,ETT_Previous_Tools_Allocation__r.ETT_Tools_Master__r.ETT_Usage_type__c from ETT_Tools_Allocation__c where Id IN:toolAllocatonMap.keyset()]);
        }
        for(ETT_Tools_Master__c tm:[Select Id,Name,ETT_Item_Description__c,ETT_Unit_type__c,ETT_Status__c,ETT_Unique_Code__c,ETT_Tool_type__c,ETT_Maintenance_Frquency__c,ETT_Usage_type__c,ETT_Serial_No__c from ETT_Tools_Master__c where Id IN:toolMasterMap.keyset()]){
            toolMasterMap.put(tm.Id,tm);
        }
        
        for(ETT_Tools_Allocation__c ta:newList){            
            if(oldMap!=null && oldMap.get(ta.Id).Allocation_Status__c!= ta.Allocation_Status__c){
                if(ta.Allocation_Status__c=='Approved' && ta.ETT_Previous_Tools_Allocation__c!=null){
                    ETT_Tools_Allocation__c newTa=new ETT_Tools_Allocation__c(Id=ta.ETT_Previous_Tools_Allocation__c);
                    if(toolAllocatonMap.get(ta.Id).ETT_Previous_Tools_Allocation__r.ETT_Tools_Master__r.ETT_Usage_type__c=='Consumable' && toolAllocatonMap.get(ta.Id).ETT_Previous_Tools_Allocation__r.ETT_Available_Stocks__c>0){
                       newTa.Allocation_Status__c='Almost Used';
                    }
                    else{
                       newTa.Allocation_Status__c='Obsolete';
                       newTa.ETT_Usage_End_time__c=System.now();
                    }
                    
                    toolAllocationToUpdate.add(newTa);
                    if(toolMasterMap.get(ta.ETT_Tools_Master__c).ETT_Unit_type__c=='Individual product'){
                        toolMasterToUpdate.add(new ETT_Tools_Master__c(Id=toolAllocatonMap.get(ta.Id).ETT_Previous_Tools_Allocation__r.ETT_Tools_Master__c,ETT_Status__c='Obsolete'));
                    }                    
                }
                else if(ta.Allocation_Status__c=='Rejected' && toolMasterMap.get(ta.ETT_Tools_Master__c).ETT_Unit_type__c=='Individual product'){
                    toolMasterToUpdate.add(new ETT_Tools_Master__c(Id=ta.ETT_Tools_Master__c,ETT_Status__c='Rejected'));
                }
            }
        }
        
        if(toolAllocationToUpdate.size() >0){
            update toolAllocationToUpdate;
        }
        if(toolMasterToUpdate.size() >0){
            update toolMasterToUpdate;
        }
    }
}