unpackaged/main/default/objects/ETI_Booking__c/ETI_Booking__c.object-meta.xml
<CustomObject>
    <label>Booking</label>
    <nameField>
        <displayFormat>B-{000000}</displayFormat>
        <label>Booking</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Bookings</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

unpackaged/main/default/objects/ETI_Booking__c/fields/Test_Result__c.field-meta.xml
<CustomField>
    <fullName>Test_Result__c</fullName>
    <label>Test Result</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Pending</fullName>
                <default>true</default>
                <label>Pending</label>
            </value>
            <value>
                <fullName>Failed</fullName>
            </value>
            <value>
                <fullName>Pass</fullName>
            </value>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>Rejected</fullName>
            </value>
            <value>
                <fullName>No Show</fullName>
            </value>
            <value>
                <fullName>Partially Approved</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/ETI_Service_Line_Item__c/ETI_Service_Line_Item__c.object-meta.xml
<CustomObject>
    <label>Booking Line Item</label>
    <nameField>
        <displayFormat>SVC-{00000}</displayFormat>
        <label>Service Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Booking Line Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

unpackaged/main/default/objects/ETI_Service_Line_Item__c/fields/Booking__c.field-meta.xml
<CustomField>
    <fullName>Booking__c</fullName>
    <label>Booking</label>
    <referenceTo>ETI_Booking__c</referenceTo>
    <relationshipLabel>Booking Line Items</relationshipLabel>
    <relationshipName>Services</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

unpackaged/main/default/objects/ETI_Service_Line_Item__c/fields/Result_Date__c.field-meta.xml
<CustomField>
    <fullName>Result_Date__c</fullName>
    <formula>datevalue(Test_Date__c)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Result Date</label>
    <type>Date</type>
</CustomField>

unpackaged/main/default/objects/ETI_Service_Line_Item__c/fields/Test_Result__c.field-meta.xml
<CustomField>
    <fullName>Test_Result__c</fullName>
    <label>Test Result</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Pending</fullName>
            </value>
            <value>
                <fullName>Pass</fullName>
            </value>
            <value>
                <fullName>Failed</fullName>
            </value>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>Rejected</fullName>
            </value>
            <value>
                <fullName>No Show</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/classes/ServiceLineItemHandler.cls
public class ServiceLineItemHandler {

    public static void updateTestResult(List<ETI_Service_Line_Item__c> newList,Map<Id,ETI_Service_Line_Item__c> oldMap){
        Set<Id> vSetSLIIds = new Set<Id>();
        for(ETI_Service_Line_Item__c vItm : newList){
            if(vItm.Test_Result__c!=null && vItm.Test_Result__c != oldMap.get(vItm.Id).Test_Result__c){
                vSetSLIIds.add(vItm.Id);
            }
         }
        if(!vSetSLIIds.isEmpty()){
         Map<Id,List<ETI_Service_Line_Item__c>> vMapBookingSLI = new Map<Id,List<ETI_Service_Line_Item__c>>();
         ETI_Booking__c upBooking;
         List<ETI_Booking__c> vListUpdateBooking = new List<ETI_Booking__c>();
         String vRes='';
         for(ETI_Service_Line_Item__c vItem : [SELECT Id,Booking__c,Test_Result__c,Result_Date__c FROM ETI_Service_Line_Item__c WHERE Id =: vSetSLIIds]){
            if(!vMapBookingSLI.containsKey(vItem.Booking__c))
                 vMapBookingSLI.put(vItem.Booking__c,new List<ETI_Service_Line_Item__c>());
             vMapBookingSLI.get(vItem.Booking__c).add(vItem);
          }
          for(Id vItem : vMapBookingSLI.keySet()){
             upBooking = new ETI_Booking__c(Id = vItem);
             for(ETI_Service_Line_Item__c vItems : vMapBookingSLI.get(vItem)){
               if(vItems.Test_Result__c!=null && vItems.Test_Result__c!='Pending'){
                   if(vItems.Test_Result__c.startsWith('Fai') || vItems.Test_Result__c.startsWith('Rej'))
                      vRes =+'Fail ';
                   if(vItems.Test_Result__c.startsWith('Pas') || vItems.Test_Result__c.startsWith('App'))
                      vRes =+'Pass ';
                   }
                   if(vItems.Test_Result__c.startsWith('No')){
                      vRes =+'No'; //No Show
                   }
              }
             if(vRes.contains('Fail') && vRes.contains('Pass')){
                 upBooking.Test_Result__c ='Partial Approved';
                 vListUpdateBooking.add(upBooking);
                    }
             else if(vRes.contains('Fail') && (!vRes.contains('Pass'))){
                  upBooking.Test_Result__c ='Failed';
                  vListUpdateBooking.add(upBooking);
             }
             else if((!vRes.contains('Fail')) && (vRes.contains('Pass'))){
                 upBooking.Test_Result__c ='Pass';
                 vListUpdateBooking.add(upBooking);
             }else if((vRes.contains('No'))){
                 upBooking.Test_Result__c ='No Show';
                 vListUpdateBooking.add(upBooking);
             }
           }
           if(!vListUpdateBooking.isEmpty())
                   update vListUpdateBooking;
        }
    }
     public static void utilityMethod(){
        
        integer i=0;
        
         i++;
         i++;
        i++;
         i++;
         i++;
        i++;
         i++;
         i++;
        i++;
         i++;
         i++;
        i++;
         i++;
         i++;
        i++;
         i++;
         i++;
        i++;
         i++;
         i++;
        i++;
         i++;
         i++;
        i++;
         i++;
         i++;
        i++;
         i++;
         i++;
        i++;
         i++;
         i++;
        i++;
         i++;
         i++;
        i++;
         i++;
         i++;
         i++;
        i++;
         i++;
         i++;
        i++;
         i++;
         i++;
        i++;
         i++;
         i++;
        i++;
         i++;
         i++;
        i++;
          
         i++;
         i++;
        i++;
         i++;
         i++;
        i++;
         i++;
         i++;
        i++;
         i++;
         i++;
        i++;
         i++;
         i++;
        i++;
         i++;
         i++;
        i++;
         i++;
         i++;
        i++;
         i++;
         i++;
        i++;
         i++;
         i++;
        i++;
         i++;
         i++;
        i++;
         i++;
         i++;
        i++;
         i++;
         i++;
        i++;
         i++;
         i++;
         i++;
        i++;
         i++;
         i++;
        i++;
         i++;
         i++;
        i++;
         i++;
         i++;
        i++;
         i++;
         i++;
        i++;
          
         i++;
         i++;
        i++;
         i++;
         i++;
        i++;
         i++;
         i++;
        i++;
         i++;
         i++;
        i++;
         i++;
         i++;
        i++;
         i++;
         i++;
        i++;
         i++;
         i++;
        i++;
         i++;
         i++;
        i++;
         i++;
         i++;
        i++;
         i++;
         i++;
        i++;
         i++;
         i++;
        i++;
         i++;
         i++;
        i++;
         i++;
         i++;
         i++;
        i++;
         i++;
         i++;
        i++;
         i++;
         i++;
        i++;
         i++;
         i++;
        i++;
         i++;
         i++;
        i++;
          
         i++;
         i++;
        i++;
         i++;
         i++;
        i++;
         i++;
         i++;
        i++;
         i++;
         i++;
        i++;
         i++;
         i++;
        i++;
         i++;
         i++;
        i++;
         i++;
         i++;
        i++;
         i++;
         i++;
        i++;
         i++;
         i++;
        i++;
         i++;
         i++;
        i++;
         i++;
         i++;
        i++;
         i++;
         i++;
        i++;
         i++;
         i++;
         i++;
        i++;
         i++;
         i++;
        i++;
         i++;
         i++;
        i++;
         i++;
         i++;
        i++;
         i++;
         i++;
        i++;
          
         i++;
         i++;
        i++;
         i++;
         i++;
        i++;
         i++;
         i++;
        i++;
         i++;
         i++;
        i++;
         i++;
         i++;
        i++;
         i++;
         i++;
        i++;
         i++;
         i++;
        i++;
         i++;
         i++;
        i++;
         i++;
         i++;
        i++;
         i++;
         i++;
        i++;
         i++;
         i++;
        i++;
         i++;
         i++;
        i++;
         i++;
         i++;
         i++;
        i++;
         i++;
         i++;
        i++;
         i++;
         i++;
        i++;
         i++;
         i++;
        i++;
         i++;
         i++;
        i++;
          
         i++;
         i++;
        i++;
         i++;
         i++;
        i++;
         i++;
         i++;
        i++;
         i++;
         i++;
        i++;
         i++;
         i++;
        i++;
         i++;
         i++;
        i++;
         i++;
         i++;
        i++;
         i++;
         i++;
        i++;
         i++;
         i++;
        i++;
         i++;
         i++;
       
     }
}