unpackaged/main/default/objects/InsuranceAutoTriggerEmails__c/InsuranceAutoTriggerEmails__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>Created to configure recipients and email templates</description>
    <label>InsuranceAutoTriggerEmails</label>
</CustomObject>

unpackaged/main/default/objects/InsuranceAutoTriggerEmails__c/fields/Email_ID__c.field-meta.xml
<CustomField>
    <fullName>Email_ID__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Email ID</label>
    <type>TextArea</type>
</CustomField>

unpackaged/main/default/objects/InsuranceAutoTriggerEmails__c/fields/Trigger_Date__c.field-meta.xml
<CustomField>
    <fullName>Trigger_Date__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Trigger Date</label>
    <type>Date</type>
</CustomField>

unpackaged/main/default/classes/GIN_AutoEmailSenderClsTest.cls
@isTest
public class GIN_AutoEmailSenderClsTest {
    
    public static testmethod void autoEmailCls(){
        
        InsuranceAutoTriggerEmails__c ins = new InsuranceAutoTriggerEmails__c();
        ins.name='Rule1';
        ins.Active__c=true;
        ins.Email_ID__c='Jana@test.com';
        ins.Email_Template_Name__c='InsuranceRenewalReminder';
        ins.Trigger_Date__c = system.today();        
        insert ins;
        
        test.startTest();
        SchedulableContext sc = null;
        GIN_AutoEmailSenderCls cls = new GIN_AutoEmailSenderCls();
        cls.execute(sc);
        test.stopTest();
        
    }

}